In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
string = 'Rank;Sourceid;Title;Type;Issn;SJR;SJR Best Quartile;H index;Total Docs. (2021);Total Docs. (3years);Total Refs.;Total Cites (3years);Citable Docs. (3years);Cites / Doc. (2years);Ref. / Doc.;Country;Region;Publisher;Coverage;Categories;Areas'
str_list = [(idx, i.strip()) for idx, i in enumerate(string.rsplit(';'))]
str_list

[(0, 'Rank'),
 (1, 'Sourceid'),
 (2, 'Title'),
 (3, 'Type'),
 (4, 'Issn'),
 (5, 'SJR'),
 (6, 'SJR Best Quartile'),
 (7, 'H index'),
 (8, 'Total Docs. (2021)'),
 (9, 'Total Docs. (3years)'),
 (10, 'Total Refs.'),
 (11, 'Total Cites (3years)'),
 (12, 'Citable Docs. (3years)'),
 (13, 'Cites / Doc. (2years)'),
 (14, 'Ref. / Doc.'),
 (15, 'Country'),
 (16, 'Region'),
 (17, 'Publisher'),
 (18, 'Coverage'),
 (19, 'Categories'),
 (20, 'Areas')]

First, make new files to replace `'&amp;'` with `&`

In [3]:
folder_path = r'G:\My Drive\BrainStation\BrainStationCapstone\Scripts and Notebooks\Raw Data\2023-03-03 Journal IF Datasets'
folder_out = r'G:\My Drive\BrainStation\BrainStationCapstone\Scripts and Notebooks\Raw Data\2023-03-03 Journal IF Datasets\output'
folder = os.listdir(folder_path)[:-1]

for file in folder:
    path = os.path.join(folder_path, file)
    print(file)
    out_path = os.path.join(folder_out, file).replace('.csv', '')
    with open(path, 'r') as f:
        with open(out_path + '_out.txt', 'a') as g:
            for idx, line in enumerate(f):
                    new_line = line.replace('&amp;', '&')
                    g.write(new_line)

scimagojr 2021  Subject Area - Materials Science.csv
scimagojr 2021  Subject Area - Environmental Science.csv
scimagojr 2021  Subject Area - Engineering.csv
scimagojr 2021  Subject Area - Energy.csv
scimagojr 2021  Subject Area - Chemistry.csv
scimagojr 2021  Subject Area - Physics and Astronomy.csv
scimagojr 2021  Subject Area - Chemical Engineering.csv
scimagojr 2021  Subject Area - Multidisciplinary.csv

In [4]:
folder = os.listdir(folder_out)

df = pd.DataFrame()

for file in folder:
    path = os.path.join(folder_out, file)
    print(file)
    temp_file = np.genfromtxt(path, delimiter=';', usecols = (2,3,5,7,15,16), dtype = '<U500')
    temp_df = pd.DataFrame(temp_file[1:], columns = temp_file[0,:])
    df = pd.concat([df, temp_df], axis = 0)
df

scimagojr 2021  Subject Area - Materials Science_out.txt
scimagojr 2021  Subject Area - Environmental Science_out.txt
scimagojr 2021  Subject Area - Engineering_out.txt
scimagojr 2021  Subject Area - Energy_out.txt
scimagojr 2021  Subject Area - Chemistry_out.txt
scimagojr 2021  Subject Area - Physics and Astronomy_out.txt
scimagojr 2021  Subject Area - Chemical Engineering_out.txt
scimagojr 2021  Subject Area - Multidisciplinary_out.txt

,Title,Type,SJR,H index,Country,Region
0,"""Nature Reviews Materials""",journal,"23,876",131,United Kingdom,Western Europe
1,"""Nature Energy""",journal,"16,736",160,United States,Northern America
2,"""Nature Materials""",journal,"12,229",507,United Kingdom,Western Europe
3,"""Nature Nanotechnology""",journal,"11,698",368,United Kingdom,Western Europe
4,"""Nature Photonics""",journal,"10,991",339,United Kingdom,Western Europe
...,...,...,...,...,...,...
689,"""Research and Development (Barrington, Illinois)""",journal,"0,101",3,United States,Northern America
690,"""Taiwan Review""",journal,"0,100",3,Taiwan,Asiatic Region
691,"""Informacion Tecnologica (discontinued)""",journal,,15,Chile,Latin America
692,"""International Journal of Advanced and Applied...",journal,,2,Taiwan,Asiatic Region
693,"""Journal of Scientific Exploration (discontinu...",journal,,18,United States,Northern America

Drop duplicated rows

In [5]:
df.duplicated().sum()

41355

In [6]:
df1 = df.drop_duplicates(ignore_index = True)
df1.head()

,Title,Type,SJR,H index,Country,Region
0,"""Nature Reviews Materials""",journal,"23,876",131,United Kingdom,Western Europe
1,"""Nature Energy""",journal,"16,736",160,United States,Northern America
2,"""Nature Materials""",journal,"12,229",507,United Kingdom,Western Europe
3,"""Nature Nanotechnology""",journal,"11,698",368,United Kingdom,Western Europe
4,"""Nature Photonics""",journal,"10,991",339,United Kingdom,Western Europe

Remove `""` from `Title` and replace `,` with `.` in `SJR`

In [7]:
df1_1 = df1.assign(Title = df1.apply(lambda x: x['Title'].replace('"', ''), axis = 1))
df2 = df1_1.assign(SJR = df1_1.apply(lambda x: x['SJR'].replace(',', '.'), axis = 1))

In [8]:
df2.head()

,Title,Type,SJR,H index,Country,Region
0,Nature Reviews Materials,journal,23.876,131,United Kingdom,Western Europe
1,Nature Energy,journal,16.736,160,United States,Northern America
2,Nature Materials,journal,12.229,507,United Kingdom,Western Europe
3,Nature Nanotechnology,journal,11.698,368,United Kingdom,Western Europe
4,Nature Photonics,journal,10.991,339,United Kingdom,Western Europe

Make `SJR` a `float` data type, and `H index` an `integer` data type

In [9]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6522 entries, 0 to 6521
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Title    6522 non-null   object
 1   Type     6522 non-null   object
 2   SJR      6522 non-null   object
 3   H index  6522 non-null   object
 4   Country  6522 non-null   object
 5   Region   6522 non-null   object
dtypes: object(6)
memory usage: 305.8+ KB

In [10]:
df2['Type'].value_counts()

journal                       6068
trade journal                  213
book series                    134
conference and proceedings     105
Type                             1
 Part A: Applications"           1
Name: Type, dtype: int64

In [11]:
display(df2[df2['Type'] == ' Part A: Applications"'])
idx = df2[df2['Type'] == ' Part A: Applications"'].index

,Title,Type,SJR,H index,Country,Region
6037,Numerical Heat Transfer,"Part A: Applications""","""15210634. 10407782""",Q2,"33,56",United Kingdom

In [12]:
df2.loc[idx, :] = ['Numerical Heat Transfer; Part A: Applications', 'journal', 0.684 ,75, 'United Kingdom', 'Western Europe']

In [13]:
df2['Type'].value_counts()

journal                       6069
trade journal                  213
book series                    134
conference and proceedings     105
Type                             1
Name: Type, dtype: int64

In [14]:
display(df2[df2['Type'] == 'Type'])
idx = df2[df2['Type'] == 'Type'].index

      Title  Type  SJR  H index  Country  Region
1367  Title  Type  SJR  H index  Country  Region

This column doesn't have any useful information, so we'll drop it.

In [15]:
df2.drop(idx, axis = 0, inplace = True)

In [16]:
display(df2[df2['Type'] == 'Type'])

Empty DataFrame
Columns: [Title, Type, SJR, H index, Country, Region]
Index: []

In [17]:
df2['Type'].value_counts()

journal                       6069
trade journal                  213
book series                    134
conference and proceedings     105
Name: Type, dtype: int64

In [18]:
for idx in df2['H index'].index:
    try: 
        df2.loc[idx, 'H index'] = int(df2.loc[idx, 'H index'])
    except:
        df2.loc[idx, 'H index'] = np.nan

for idx in df2['SJR'].index:
    try: 
        df2.loc[idx, 'SJR'] = float(df2.loc[idx, 'SJR'])
    except:
        df2.loc[idx, 'SJR'] = np.nan

In [19]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6521 entries, 0 to 6521
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Title    6521 non-null   object
 1   Type     6521 non-null   object
 2   SJR      6434 non-null   object
 3   H index  6521 non-null   object
 4   Country  6521 non-null   object
 5   Region   6521 non-null   object
dtypes: object(6)
memory usage: 614.7+ KB

The `dtype` of the columns won't read as numeric data types since there are some `NaN` values

Converting the Titles into Names

In [20]:
import re

def edit_title2(row):
    title = row
    
    # Get rid of 'The'
    title = re.sub(r'^The\s', '', title)
    
    # Get rid of colons
    title = re.sub(r':', '', title)
    
    # Get rid of hyphens
    title = re.sub(r'-', '', title)
    
    # Insert spaces in '&word' case
    title = re.sub(r'\&', '& ', title)
    
    # Get rid of double spacing
    title = re.sub(r'  ', ' ', title)
    
    # Get rid of '(discontinued)'
    title = re.sub(r'\(discontinued\)', '', title)
    
    return title.strip().lower()

In [21]:
df3 = df2.assign(Title = df2['Title'].apply(edit_title2))

In [22]:
df3

,Title,Type,SJR,H index,Country,Region
0,nature reviews materials,journal,23.876,131,United Kingdom,Western Europe
1,nature energy,journal,16.736,160,United States,Northern America
2,nature materials,journal,12.229,507,United Kingdom,Western Europe
3,nature nanotechnology,journal,11.698,368,United Kingdom,Western Europe
4,nature photonics,journal,10.991,339,United Kingdom,Western Europe
...,...,...,...,...,...,...
6517,bulletin de la societe vaudoise des sciences n...,journal,0.101,11,Switzerland,Western Europe
6518,radovi zavoda za znanstvenoistrazivacki i umje...,journal,0.101,1,Croatia,Eastern Europe
6519,taiwan review,journal,0.1,3,Taiwan,Asiatic Region
6520,international journal of advanced and applied ...,journal,NaN,2,Taiwan,Asiatic Region
6521,journal of scientific exploration,journal,NaN,18,United States,Northern America

In [23]:
df3[df3['Title'] == 'solidstate electronics']

,Title,Type,SJR,H index,Country,Region
657,solidstate electronics,journal,0.415,98,United Kingdom,Western Europe

In [24]:
id_df = pd.DataFrame(np.arange(0, df3.shape[0] + 1, 1), columns = ['id'])
df4 = pd.concat([id_df, df3], axis = 1)

In [25]:
df4['Title'].isna().sum()

1

In [26]:
idx = df4[df4['Title'].isna()].index

In [27]:
df4.drop(1367, axis = 0, inplace = True)

In [28]:
df4['Title'].isna().sum()

0

In [29]:
cleanPath = r'G:\My Drive\BrainStation\BrainStationCapstone\Scripts and Notebooks\Cleaned Data'
clean_file = os.path.join(cleanPath, '2023-03-04 Journal Data Frame Cleaning V1.csv')
df4.to_csv(clean_file, index=False)

In [30]:
clean_file

'G:\\My Drive\\BrainStation\\BrainStationCapstone\\Scripts and Notebooks\\Cleaned Data\\2023-03-04 Journal Data Frame Cleaning V1.csv'

---