In [1]:
import numpy as np
import pandas as pd

In [8]:
jour_df = pd.read_csv(r'G:\My Drive\BrainStation\BrainStationCapstone\Scripts and Notebooks\Cleaned Data\2023-03-03 Journal IRF Cleaning out.1.csv').drop('Unnamed: 0', axis = 1)
jour_df.head()

,id,Title,Type,SJR,H index,Country,Region
0,0,nature reviews materials,journal,23.875000,131,United Kingdom,Western Europe
1,1,nature energy,journal,16.734375,160,United States,Northern America
2,2,nature materials,journal,12.226562,507,United Kingdom,Western Europe
3,3,nature nanotechnology,journal,11.695312,368,United Kingdom,Western Europe
4,4,nature photonics,journal,10.992188,339,United Kingdom,Western Europe

In [9]:
df = pd.read_csv(r"G:\My Drive\BrainStation\BrainStationCapstone\Scripts and Notebooks\Raw Data\2023-03-03 Export\2023-03-02 Cleaning DataSet V2.2.1 out.csv", low_memory = True).drop('Unnamed: 0', axis = 1)
df.head()

,Cites,Title,Year,Source,GSRank,Type,ECC,CitesPerYear,CitesPerAuthor,AuthorCount,query_id,first_auth,second_auth,third_auth
0,4186,low trap-state density and long carrier diffus...,2015.0,science,1,Journal article,4186,523.25,523,8,0.0,d shi,v adinolfi,r comin
1,2319,perovskite light-emitting diodes with external...,2018.0,nature,2,Journal article,2319,463.80,258,9,0.0,k lin,j xing,ln quan
2,2163,solution-processed pbs quantum dot infrared ph...,2005.0,nature materials,3,Journal article,2163,120.17,309,7,0.0,sa mcdonald,g konstantatos,s zhang
3,1951,efficient and stable solution-processed planar...,2017.0,science,4,Journal article,1951,325.17,279,7,0.0,h tan,a jain,o voznyy
4,1897,ultrasensitive solution-cast quantum dot photo...,2006.0,nature,5,Journal article,1897,111.59,271,7,0.0,g konstantatos,i howard,a fischer

In [12]:
join_df1 = pd.merge(left = df, right = jour_df, left_on = 'Source', right_on = 'Title')
join_df1.head()

,Cites,Title_x,Year,Source,GSRank,Type_x,ECC,CitesPerYear,CitesPerAuthor,AuthorCount,...,first_auth,second_auth,third_auth,id,Title_y,Type_y,SJR,H index,Country,Region
0,4186,low trap-state density and long carrier diffus...,2015.0,science,1,Journal article,4186,523.25,523,8,...,d shi,v adinolfi,r comin,4967,science,journal,14.585938,1229,United States,Northern America
1,1951,efficient and stable solution-processed planar...,2017.0,science,4,Journal article,1951,325.17,279,7,...,h tan,a jain,o voznyy,4967,science,journal,14.585938,1229,United States,Northern America
2,1756,homogeneously dispersed multimetal oxygen-evol...,2016.0,science,7,Journal article,1756,250.86,251,7,...,b zhang,x zheng,o voznyy,4967,science,journal,14.585938,1229,United States,Northern America
3,1343,co2 electroreduction to ethylene via hydroxide...,2018.0,science,11,Journal article,1343,268.60,224,6,...,ct dinh,t burdyny,mg kibria,4967,science,journal,14.585938,1229,United States,Northern America
4,1168,what would it take for renewably powered elect...,2019.0,science,14,Journal article,1168,292.00,195,6,...,p de luna,c hahn,d higgins,4967,science,journal,14.585938,1229,United States,Northern America

In [14]:
before = df.shape[0]
after = join_df1.shape[0]

print("{:.0%} of the rows merged!".format(after/before))

83% of the rows merged!

Find where the journal names didn't merge using left join.

In [28]:
left_join = pd.merge(left = df, right = jour_df, left_on = 'Source', right_on = 'Title', how = 'left')
left_join.sample(5)

,Cites,Title_x,Year,Source,GSRank,Type_x,ECC,CitesPerYear,CitesPerAuthor,AuthorCount,...,first_auth,second_auth,third_auth,id,Title_y,Type_y,SJR,H index,Country,Region
22063,16,a novel er3+ ions doped zirconium magnesium bo...,2021.0,solid state sciences,8,Journal article,16,8.00,8,2,...,k mariselvam,j liu,NaN,452.0,solid state sciences,journal,0.557129,93.0,France,Western Europe
10956,9,a cation study on rice husk biomass pretreatme...,2017.0,acs sustainable chemistry &engineering,49,Journal article,9,1.50,2,4,...,bby lau,t yeung,rj patterson,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17969,53,nitric oxide biosensors based on the immobiliz...,2006.0,electroanalysis an international journal devot...,8,Journal article,53,3.12,13,4,...,e topoglidis,cj campbell,aeg cass,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19331,189,inversion symmetry and bulk rashba effect in m...,2018.0,nature communications,9,Journal article,189,37.80,27,7,...,k frohna,t deshpande,j harter,3910.0,nature communications,journal,4.847656,410.0,United Kingdom,Western Europe
126,237,quantum junction solar cells,2012.0,nano letters,130,Journal article,237,21.55,30,8,...,j tang,h liu,d zhitomirsky,29.0,nano letters,journal,3.761719,511.0,United States,Northern America

In [35]:
nan_idx = left_join['id'][left_join['id'].isna() == True].index
nan_df = left_join.loc[nan_idx, :]

In [36]:
nan_df.head()

,Cites,Title_x,Year,Source,GSRank,Type_x,ECC,CitesPerYear,CitesPerAuthor,AuthorCount,...,first_auth,second_auth,third_auth,id,Title_y,Type_y,SJR,H index,Country,Region
88,305,colloidal quantum dot ligand engineering for h...,2016.0,energy &environmental science,92,Journal article,305,43.57,51,6,...,r wang,y shang,p kanjanaboos,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,261,lighting the local area: optical code-division...,2000.0,ieee network,116,Journal article,261,11.35,131,2,...,a stok,eh sargent,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144,211,combined high alkalinity and pressurization en...,2018.0,energy &environmental science,148,Journal article,211,42.20,35,6,...,cm gabardo,a seifitokaldani,jp edwards,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,149,colloidal quantum dot photodetectors,2011.0,infrared physics &technology,199,Journal article,149,12.42,75,2,...,g konstantatos,eh sargent,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209,134,nanomorphology-enhanced gas-evolution intensif...,2017.0,acs sustainable chemistry &engineering,221,Journal article,134,22.33,19,7,...,t burdyny,pj graham,y pang,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
nan_df['Source'].value_counts()

energy &environmental science                199
journal of materials chemistry               102
bulletin of the american physical society     97
journal of physics d applied physics          91
chemistry–a european journal                  80
                                            ...
évolution                                      1
fuel cells (online)                            1
inzynieria materialowa                         1
philosophical magazine a                       1
journal of the indian botanical society        1
Name: Source, Length: 1207, dtype: int64

Start with `energy &environmental science `

In [271]:
def find_word(row, word):
    result = np.char.find(row['Title'], word)
    if result != -1:
        print(result, row['Title'])
        return True
    elif result > -1:
        return False

In [44]:
jour_df.apply(find_word, word = 'energy and', axis = 1);

0 energy and environmental materials
0 energy and environmental science
32 wiley interdisciplinary reviews energy and environment
13 economics of energy and environmental policy
25 international journal of energy and environmental engineering
0 energy and environment
23 strategic planning for energy and the environment
24 economics and policy of energy and the environment
9 european energy and environmental law review
0 energy and ai
0 energy and buildings
0 energy and built environment
17 geomechanics for energy and the environment
12 progress in energy and combustion science
6 green energy and environment
12 sustainable energy and fuels
35 geomechanics and geophysics for geoenergy and georesources
11 journal of energy and natural resources law
11 journal of energy and development
10 renewable energy and power quality journal
59 reneng dongli gongcheng/journal of engineering for thermal energy and power

Replace with `energy and environmental science`

In [277]:
def genjoin(replace_dic):
    
    global df 
    
    # replace the words in the original data frame
    df = df.replace(replace_dic)
    
    # Perform Left Join
    left_join = pd.merge(left = df, right = jour_df, left_on = 'Source', right_on = 'Title', how = 'left')
    
    # Find Null Values
    nan_idx = left_join['id'][left_join['id'].isna() == True].index
    nan_df = left_join.loc[nan_idx, :]
    
    print(f"There are {left_join.isna().sum().sum()} Remaining Nulls")

    return nan_df['Source'].value_counts()

In [61]:
genjoin({'energy &environmental science':'energy and environmental science'})

journal of materials chemistry               102
bulletin of the american physical society     97
journal of physics d applied physics          91
chemistry–a european journal                  80
physica status solidi (a)                     76
                                            ...
évolution                                      1
fuel cells (online)                            1
inzynieria materialowa                         1
philosophical magazine a                       1
journal of the indian botanical society        1
Name: Source, Length: 1206, dtype: int64

In [54]:
jour_df.apply(find_word, word = 'journal of materials chemistry', axis = 1);

0 journal of materials chemistry a
0 journal of materials chemistry c
0 journal of materials chemistry b

Need to figure out which variation the paper is of `journal of materials chemistry`

In [65]:
test_df = df.loc[df['Source'][df['Source'] == 'journal of materials chemistry'].index, :]

In [69]:
print(f"Ther are {test_df.shape[0]} articles")

Ther are 102 articles

...this might take a while. Let's knock out `journal physics d applied physics`

In [71]:
jour_df.apply(find_word, word = 'applied physics', axis = 1);

18 journal physics d applied physics
8 current applied physics
0 applied physics a materials science and processing
4 epj applied physics
0 applied physics express
20 japanese journal of applied physics
0 applied physics reviews
0 applied physics letters
11 journal of applied physics
0 applied physics b lasers and optics
27 journal of theoretical and applied physics
36 johns hopkins apl technical digest (applied physics laboratory)
27 indian journal of pure and applied physics
0 applied physics

In [72]:
genjoin({'journal of physics d applied physics':'journal physics d applied physics'})

journal of materials chemistry               102
bulletin of the american physical society     97
chemistry–a european journal                  80
physica status solidi (a)                     76
journal of nanoscience and nanotechnology     66
                                            ...
évolution                                      1
fuel cells (online)                            1
inzynieria materialowa                         1
philosophical magazine a                       1
journal of the indian botanical society        1
Name: Source, Length: 1205, dtype: int64

In [73]:
jour_df.apply(find_word, word = 'a european journal', axis = 1);

10 chemistry a european journal

In [84]:
genjoin({'chemistry–a european journal':'chemistry a european journal'})

There are 27431 Remaining Nulls

journal of materials chemistry               102
bulletin of the american physical society     97
physica status solidi (a)                     76
journal of nanoscience and nanotechnology     66
crystal growth &design                        61
                                            ...
évolution                                      1
fuel cells (online)                            1
inzynieria materialowa                         1
philosophical magazine a                       1
journal of the indian botanical society        1
Name: Source, Length: 1204, dtype: int64

In [85]:
jour_df.apply(find_word, word = 'physica status solidi', axis = 1);

0 physica status solidi rapid research letters
0 physica status solidi (a) applications and materials science
0 physica status solidi (b) basic research

In [86]:
genjoin({'physica status solidi (a)':'physica status solidi (a) applications and materials science'})

There are 26899 Remaining Nulls

journal of materials chemistry               102
bulletin of the american physical society     97
journal of nanoscience and nanotechnology     66
crystal growth &design                        61
applied physics a                             56
                                            ...
évolution                                      1
fuel cells (online)                            1
inzynieria materialowa                         1
philosophical magazine a                       1
journal of the indian botanical society        1
Name: Source, Length: 1203, dtype: int64

In [88]:
jour_df.apply(find_word, word = 'crystal growth', axis = 1);

12 progress in crystal growth and characterization of materials
0 crystal growth and design
11 journal of crystal growth

In [89]:
genjoin({'crystal growth &design':'crystal growth and design'})

There are 26472 Remaining Nulls

journal of materials chemistry               102
bulletin of the american physical society     97
journal of nanoscience and nanotechnology     66
applied physics a                             56
matter                                        54
                                            ...
évolution                                      1
fuel cells (online)                            1
inzynieria materialowa                         1
philosophical magazine a                       1
journal of the indian botanical society        1
Name: Source, Length: 1202, dtype: int64

In [91]:
jour_df.apply(find_word, word = 'matter', axis = 1);

27 annual review of condensed matter physics
9 granular matter
29 journal of physics condensed matter
10 condensed matter
20 physica b condensed matter
24 computational condensed matter
0 matter and radiation at extremes
21 journal of condensed matter nuclear science
5 soft matter
10 condensed matter physics
22 advances in condensed matter physics

In [96]:
def getspec_df(key):
    global df
    return df[df['Source'] == key]['Title'].values

In [99]:
missing_jour = ['matter', 'journal of nanoscience and nanotechnology']

In [100]:
genjoin({'crystal growth &design':'crystal growth and design'}).head(10)

There are 26472 Remaining Nulls

journal of materials chemistry                    102
bulletin of the american physical society          97
journal of nanoscience and nanotechnology          66
applied physics a                                  56
matter                                             54
chemical physics letters                           54
journal of vacuum science &technology a vacuum     53
physica status solidi (b)                          52
physical review-section b-condensed matter         44
acs sustainable chemistry &engineering             40
Name: Source, dtype: int64

In [105]:
jour_df.apply(find_word, word = 'journal of vacuum science', axis = 1);

0 journal of vacuum science and technology a vacuum, surfaces and films
0 journal of vacuum science and technology bnanotechnology and microelectronics
31 zhenkong kexue yu jishu xuebao/journal of vacuum science and technology

In [106]:
genjoin({'journal of vacuum science &technology a vacuum':'journal of vacuum science and technology a vacuum, surfaces and films'}).head(10)

There are 26101 Remaining Nulls

journal of materials chemistry                102
bulletin of the american physical society      97
journal of nanoscience and nanotechnology      66
applied physics a                              56
chemical physics letters                       54
matter                                         54
physica status solidi (b)                      52
physical review-section b-condensed matter     44
acs sustainable chemistry &engineering         40
japanese journal of applied physics            36
Name: Source, dtype: int64

In [107]:
jour_df.apply(find_word, word = 'physica status solidi (b)', axis = 1);

0 physica status solidi (b) basic research

In [108]:
genjoin({'physica status solidi (b)':'physica status solidi (b) basic research'}).head(10)

There are 25737 Remaining Nulls

journal of materials chemistry                        102
bulletin of the american physical society              97
journal of nanoscience and nanotechnology              66
applied physics a                                      56
matter                                                 54
chemical physics letters                               54
physical review-section b-condensed matter             44
acs sustainable chemistry &engineering                 40
japanese journal of applied physics                    36
physica status solidi (rrl)–rapid research letters     34
Name: Source, dtype: int64

In [110]:
jour_df.apply(find_word, word = 'physical review', axis = 1);

0 physical review b
0 physical review materials
0 physical review fluids
0 physical review x
0 physical review letters
0 physical review d
0 physical review applied
0 physical review c
0 physical review physics education research
0 physical review accelerators and beams
0 physical review e

In [111]:
genjoin({'physical review-section b-condensed matter':'physical review b'}).head(10)

There are 25429 Remaining Nulls

journal of materials chemistry                        102
bulletin of the american physical society              97
journal of nanoscience and nanotechnology              66
applied physics a                                      56
matter                                                 54
chemical physics letters                               54
acs sustainable chemistry &engineering                 40
japanese journal of applied physics                    36
sustainable energy &fuels                              34
physica status solidi (rrl)–rapid research letters     34
Name: Source, dtype: int64

In [112]:
jour_df.apply(find_word, word = 'acs sustainable chemistry', axis = 1);

0 acs sustainable chemistry and engineering

In [113]:
genjoin({'acs sustainable chemistry &engineering':'acs sustainable chemistry and engineering'}).head(10)

There are 25149 Remaining Nulls

journal of materials chemistry                        102
bulletin of the american physical society              97
journal of nanoscience and nanotechnology              66
applied physics a                                      56
matter                                                 54
chemical physics letters                               54
japanese journal of applied physics                    36
sustainable energy &fuels                              34
physica status solidi (rrl)–rapid research letters     34
ecs transactions                                       32
Name: Source, dtype: int64

In [116]:
jour_df.apply(find_word, word = 'sustainable energy', axis = 1);

28 materials for renewable and sustainable energy
27 environmental progress and sustainable energy
0 sustainable energy, grids and networks
44 technology and economics of smart grids and sustainable energy
21 ieee transactions on sustainable energy
14 renewable and sustainable energy reviews
0 sustainable energy and fuels
0 sustainable energy technologies and assessments
25 international journal of sustainable energy planning and management
25 international journal of sustainable energy
25 journal of renewable and sustainable energy

In [117]:
genjoin({'sustainable energy &fuels':'sustainable energy and fuels'}).head(10)

There are 24911 Remaining Nulls

journal of materials chemistry                        102
bulletin of the american physical society              97
journal of nanoscience and nanotechnology              66
applied physics a                                      56
chemical physics letters                               54
matter                                                 54
japanese journal of applied physics                    36
physica status solidi (rrl)–rapid research letters     34
light science &applications                            32
ecs transactions                                       32
Name: Source, dtype: int64

In [118]:
jour_df.apply(find_word, word = 'physica status solidi', axis = 1);

0 physica status solidi rapid research letters
0 physica status solidi (a) applications and materials science
0 physica status solidi (b) basic research

In [119]:
genjoin({'physica status solidi (rrl)–rapid research letters':'physica status solidi rapid research letters'}).head(10)

There are 24673 Remaining Nulls

journal of materials chemistry                       102
bulletin of the american physical society             97
journal of nanoscience and nanotechnology             66
applied physics a                                     56
matter                                                54
chemical physics letters                              54
japanese journal of applied physics                   36
light science &applications                           32
ecs transactions                                      32
acta crystallographica a-foundation and advances      30
Name: Source, dtype: int64

In [120]:
jour_df.apply(find_word, word = 'light science', axis = 1);

0 light science and applications

In [121]:
genjoin({'light science &applications':'light science and applications'}).head(10)

There are 24449 Remaining Nulls

journal of materials chemistry                          102
bulletin of the american physical society                97
journal of nanoscience and nanotechnology                66
applied physics a                                        56
matter                                                   54
chemical physics letters                                 54
japanese journal of applied physics                      36
ecs transactions                                         32
acta crystallographica a-foundation and advances         30
physica e low-dimensional systems and nanostructures     27
Name: Source, dtype: int64

...my wrist hurts, lets try to automate this.

In [272]:
jour_df.apply(find_word, word = 'acta crystallographica', axis = 1);

0 acta crystallographica section a foundations and advances
0 acta crystallographica section b structural science, crystal engineering and materials
0 acta crystallographica section e crystallographic communications
0 acta crystallographica. section c, structural chemistry
0 acta crystallographica section fstructural biology communications

In [278]:
genjoin({'acta crystallographica a-foundation and advances':'acta crystallographica section a foundations and advances'}).head(10)

There are 24435 Remaining Nulls

journal of materials chemistry                          102
bulletin of the american physical society                97
journal of nanoscience and nanotechnology                66
applied physics a                                        56
chemical physics letters                                 54
matter                                                   54
japanese journal of applied physics                      36
ecs transactions                                         32
acta crystallographica a-foundation and advances         30
physica e low-dimensional systems and nanostructures     27
Name: Source, dtype: int64

In [280]:
jour_df.apply(find_word, word = 'systems and nanostructures', axis = 1);

25 physica e lowdimensional systems and nanostructures

In [286]:
genjoin({'physica e low-dimensional systems and nanostructures':'physica e lowdimensional systems and nanostructures'}).head(20)

There are 24246 Remaining Nulls

journal of materials chemistry                                              102
bulletin of the american physical society                                    97
journal of nanoscience and nanotechnology                                    66
applied physics a                                                            56
matter                                                                       54
chemical physics letters                                                     54
japanese journal of applied physics                                          36
ecs transactions                                                             32
acta crystallographica a-foundation and advances                             30
studies in surface science and catalysis                                     25
optics letters                                                               23
journal of vacuum science &technology b microelectronics and nanometer …     23
laser &photonics reviews                                                     22
solid-state electronics                                                      21
journal of non-crystalline solids                                            21
inorganic chemistry communications                                           20
energy procedia                                                              20
materials science and engineering b                                          19
journal of the korean magnetics society                                      18
cleo qels_fundamental science                                                18
Name: Source, dtype: int64

In [284]:
jour_df.apply(find_word, word = 'studies in surface science and catalysis', axis = 1);

In [285]:
missing_jour.append('studies in surface science and catalysis')

In [290]:
jour_df.apply(find_word, word = 'magnetics society', axis = 1);

15 journal of the magnetics society of japan
29 applied computational electromagnetics society journal

A lot of journals that should be in the data base are not showing up. Need to look the data base again.

In [295]:
df.to_csv(r'G:\My Drive\BrainStation\BrainStationCapstone\Scripts and Notebooks\Cleaned Data\2023-03-03 Joining Journal DF out.csv')

In [297]:
missing_jour

['matter',
 'journal of nanoscience and nanotechnology',
 'studies in surface science and catalysis']

In [299]:
join_df1 = pd.merge(left = df, right = jour_df, left_on = 'Source', right_on = 'Title')
join_df1.head()

before = df.shape[0]
after = join_df1.shape[0]

print("{:.0%} of the rows merged!".format(after/before))

86% of the rows merged!

---