In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r"G:\My Drive\BrainStation\BrainStationCapstone\Scripts and Notebooks\Raw Data\2023-03-03 Export\full_results_PoPCites_V2.2.csv",low_memory = True)

In [3]:
df.head()

,Unnamed: 0,Cites,Authors,Title,Year,Source,Publisher,ArticleURL,CitesURL,GSRank,...,EndPage,ECC,CitesPerYear,CitesPerAuthor,AuthorCount,Age,Abstract,FullTextURL,RelatedURL,query_id
0,0,4186,"D Shi, V Adinolfi, R Comin, M Yuan, E Alarousu...",Low trap-state density and long carrier diffus...,2015.0,Science,NaN,NaN,https://scholar.google.com/scholar?oi=bibs&hl=...,1,...,522.0,4186,523.25,523,8,8.0,NaN,NaN,NaN,0.0
1,1,2319,"K Lin, J Xing, LN Quan, FPG de Arquer, X Gong,...",Perovskite light-emitting diodes with external...,2018.0,Nature,NaN,NaN,https://scholar.google.com/scholar?oi=bibs&hl=...,2,...,248.0,2319,463.80,258,9,5.0,NaN,NaN,NaN,0.0
2,2,2163,"SA McDonald, G Konstantatos, S Zhang, PW Cyr, ...",Solution-processed PbS quantum dot infrared ph...,2005.0,Nature materials,NaN,NaN,https://scholar.google.com/scholar?oi=bibs&hl=...,3,...,142.0,2163,120.17,309,7,18.0,NaN,NaN,NaN,0.0
3,3,1951,"H Tan, A Jain, O Voznyy, X Lan, FP García de A...",Efficient and stable solution-processed planar...,2017.0,Science,NaN,NaN,https://scholar.google.com/scholar?oi=bibs&hl=...,4,...,726.0,1951,325.17,279,7,6.0,NaN,NaN,NaN,0.0
4,4,1897,"G Konstantatos, I Howard, A Fischer, S Hooglan...",Ultrasensitive solution-cast quantum dot photo...,2006.0,Nature,NaN,NaN,https://scholar.google.com/scholar?oi=bibs&hl=...,5,...,183.0,1897,111.59,271,7,17.0,NaN,NaN,NaN,0.0

In [4]:
df = df.drop(['Unnamed: 0', 'Publisher', 'ArticleURL', 'Abstract', 'FullTextURL', 'RelatedURL'], axis = 1)

In [5]:
df.head()

,Cites,Authors,Title,Year,Source,CitesURL,GSRank,QueryDate,Type,DOI,...,Volume,Issue,StartPage,EndPage,ECC,CitesPerYear,CitesPerAuthor,AuthorCount,Age,query_id
0,4186,"D Shi, V Adinolfi, R Comin, M Yuan, E Alarousu...",Low trap-state density and long carrier diffus...,2015.0,Science,https://scholar.google.com/scholar?oi=bibs&hl=...,1,2023-03-02 08:59:01,Journal article,NaN,...,347.0,6221.0,519.0,522.0,4186,523.25,523,8,8.0,0.0
1,2319,"K Lin, J Xing, LN Quan, FPG de Arquer, X Gong,...",Perovskite light-emitting diodes with external...,2018.0,Nature,https://scholar.google.com/scholar?oi=bibs&hl=...,2,2023-03-02 08:59:01,Journal article,NaN,...,562.0,7726.0,245.0,248.0,2319,463.80,258,9,5.0,0.0
2,2163,"SA McDonald, G Konstantatos, S Zhang, PW Cyr, ...",Solution-processed PbS quantum dot infrared ph...,2005.0,Nature materials,https://scholar.google.com/scholar?oi=bibs&hl=...,3,2023-03-02 08:59:01,Journal article,NaN,...,4.0,2.0,138.0,142.0,2163,120.17,309,7,18.0,0.0
3,1951,"H Tan, A Jain, O Voznyy, X Lan, FP García de A...",Efficient and stable solution-processed planar...,2017.0,Science,https://scholar.google.com/scholar?oi=bibs&hl=...,4,2023-03-02 08:59:01,Journal article,NaN,...,355.0,6326.0,722.0,726.0,1951,325.17,279,7,6.0,0.0
4,1897,"G Konstantatos, I Howard, A Fischer, S Hooglan...",Ultrasensitive solution-cast quantum dot photo...,2006.0,Nature,https://scholar.google.com/scholar?oi=bibs&hl=...,5,2023-03-02 08:59:01,Journal article,NaN,...,442.0,7099.0,180.0,183.0,1897,111.59,271,7,17.0,0.0

In [6]:
num = df.isna().sum().sum()
print(f"There are {num} null values")

There are 114829 null values

In [7]:
df['Type'].value_counts()

Journal article     24889
Conference paper     2124
Book chapter          852
Abstract              729
Patent                600
Preprint              325
Book                  118
Online document         3
Name: Type, dtype: int64

In [8]:
df1 = df[df['Type'] == 'Journal article']

In [9]:
num = df1.isna().sum().sum()
print(f"There are {num} null values")

There are 60510 null values

In [10]:
df2 = df1.drop(['DOI', 'Volume', 'Issue', 'ISSN'], axis = 1)

In [11]:
num = df2.isna().sum().sum()
print(f"There are {num} null values")

There are 3876 null values

In [12]:
df2['Type'].value_counts()

Journal article    24889
Name: Type, dtype: int64

In [13]:
df2.isna().sum()

Cites                0
Authors              9
Title                0
Year                12
Source               1
CitesURL             0
GSRank               0
QueryDate            0
Type                 0
CitationURL          0
StartPage         1834
EndPage           2008
ECC                  0
CitesPerYear         0
CitesPerAuthor       0
AuthorCount          0
Age                 12
query_id             0
dtype: int64

In [14]:
df3 = df2.drop(['StartPage', 'EndPage', 'Age'], axis = 1)

In [15]:
df3.isna().sum()

Cites              0
Authors            9
Title              0
Year              12
Source             1
CitesURL           0
GSRank             0
QueryDate          0
Type               0
CitationURL        0
ECC                0
CitesPerYear       0
CitesPerAuthor     0
AuthorCount        0
query_id           0
dtype: int64

In [16]:
num = df3.isna().sum().sum()
print(f"There are {num} null values")

There are 22 null values

In [17]:
df4 = df3.dropna(subset=['Authors', 'Year'])

In [18]:
df4.isna().sum()

Cites             0
Authors           0
Title             0
Year              0
Source            1
CitesURL          0
GSRank            0
QueryDate         0
Type              0
CitationURL       0
ECC               0
CitesPerYear      0
CitesPerAuthor    0
AuthorCount       0
query_id          0
dtype: int64

In [19]:
df4.head()

,Cites,Authors,Title,Year,Source,CitesURL,GSRank,QueryDate,Type,CitationURL,ECC,CitesPerYear,CitesPerAuthor,AuthorCount,query_id
0,4186,"D Shi, V Adinolfi, R Comin, M Yuan, E Alarousu...",Low trap-state density and long carrier diffus...,2015.0,Science,https://scholar.google.com/scholar?oi=bibs&hl=...,1,2023-03-02 08:59:01,Journal article,https://scholar.google.com/citations?view_op=v...,4186,523.25,523,8,0.0
1,2319,"K Lin, J Xing, LN Quan, FPG de Arquer, X Gong,...",Perovskite light-emitting diodes with external...,2018.0,Nature,https://scholar.google.com/scholar?oi=bibs&hl=...,2,2023-03-02 08:59:01,Journal article,https://scholar.google.com/citations?view_op=v...,2319,463.80,258,9,0.0
2,2163,"SA McDonald, G Konstantatos, S Zhang, PW Cyr, ...",Solution-processed PbS quantum dot infrared ph...,2005.0,Nature materials,https://scholar.google.com/scholar?oi=bibs&hl=...,3,2023-03-02 08:59:01,Journal article,https://scholar.google.com/citations?view_op=v...,2163,120.17,309,7,0.0
3,1951,"H Tan, A Jain, O Voznyy, X Lan, FP García de A...",Efficient and stable solution-processed planar...,2017.0,Science,https://scholar.google.com/scholar?oi=bibs&hl=...,4,2023-03-02 08:59:01,Journal article,https://scholar.google.com/citations?view_op=v...,1951,325.17,279,7,0.0
4,1897,"G Konstantatos, I Howard, A Fischer, S Hooglan...",Ultrasensitive solution-cast quantum dot photo...,2006.0,Nature,https://scholar.google.com/scholar?oi=bibs&hl=...,5,2023-03-02 08:59:01,Journal article,https://scholar.google.com/citations?view_op=v...,1897,111.59,271,7,0.0

In [20]:
rows, cols = df4.shape
print(f'There are {rows} rows')

There are 24868 rows

In [31]:
df4[df4['Source'].isna()].values

array([[21, 'MP Hung, D Wang, J Jiang, M Furuta',
        'ECS Solid State Lett. 3', 2014.0, nan,
        'https://scholar.google.com/scholar?oi=bibs&hl=en&cites=16519469448441430027',
        7, '2023-03-02 04:46:13', 'Journal article',
        'https://scholar.google.com/citations?view_op=view_citation&hl=en&user=nS8KEh4AAAAJ&pagesize=100&citation_for_view=nS8KEh4AAAAJ:ns9cj8rnVeAC',
        21, 2.33, 5, 4, 346.0]], dtype=object)

In [33]:
df4 = df4.dropna(subset = ['Source'])

In [35]:
df4.isna().sum()

Cites             0
Authors           0
Title             0
Year              0
Source            0
CitesURL          0
GSRank            0
QueryDate         0
Type              0
CitationURL       0
ECC               0
CitesPerYear      0
CitesPerAuthor    0
AuthorCount       0
query_id          0
dtype: int64

In [34]:
rows, cols = df4.shape
print(f'There are {rows} rows')

There are 24867 rows

In [36]:
import re
pattern = r'^(.*?)\s+(\d+)\s+\((\d+)\),\s+(.*)$'

vals = df4['Source'].values
index = df4['Source'].index

for idx, val in enumerate(df4['Source'].values):

    # match pattern to citation
    match = re.match(pattern, val)

    if match:
        journal = match.group(1)   # 'Optics Express'
        volume = match.group(2)    # '27'
        issue = match.group(3)     # '20'
        pages = match.group(4)     # 'A1419-A'

        # print extracted values
        print(val)
        print('Journal:', journal)
        print('\n')
        
        df4.loc[index[idx], 'Source'] = journal
        
    else:
        pass

Science 364 (6438), eaav
Journal: Science


Science 361 (6408), eaat
Journal: Science


Science 353 (6302), aac
Journal: Science


Science 373 (6555), eaaz
Journal: Science


Science Advances 6 (42), eabb
Journal: Science Advances


Science advances 6 (42), eabc
Journal: Science advances


Journal of Optics A: Pure and Applied Optics 4 (6), S
Journal: Journal of Optics A: Pure and Applied Optics


Physical Review E 62 (4), R
Journal: Physical Review E


Optics Express 18 (103), A451-A
Journal: Optics Express


Science Advances 6 (12), eaay
Journal: Science Advances


Science 367 (6482), eabb
Journal: Science


Optics express 19 (106), A1281-A
Journal: Optics express


Optics express 19 (106), A1237-A
Journal: Optics express


Applied Physics Letters 106 (11), 32_
Journal: Applied Physics Letters


Applied Physics Letters 107 (6), 79_
Journal: Applied Physics Letters


Applied Catalysis A, General 1 (153), N3-N
Journal: Applied Catalysis A, General


Applied Catalysis A: General 143 (2), N7-N
Journal: Applied Catalysis A: General


Applied Catalysis A: General 142 (1), N
Journal: Applied Catalysis A: General


Applied Catalysis A: General 142 (1), n2-n
Journal: Applied Catalysis A: General


Applied Catalysis A: General 133 (1), n6-n
Journal: Applied Catalysis A: General


Applied Catalysis B: Environmental 1 (6), N
Journal: Applied Catalysis B: Environmental


Applied Catalysis A: General 133 (1), n4-n
Journal: Applied Catalysis A: General


Applied Catalysis A, General 1 (129), n7-n
Journal: Applied Catalysis A, General


applied catalysis A: General 112 (1), N4-N
Journal: applied catalysis A: General


APPLIED CATALYSIS A-GENERAL 81 (1), N15-N
Journal: APPLIED CATALYSIS A-GENERAL


Nano Letters 18 (1), 535-539.
Journal: Nano Letters


Bulletin of the Russian Academy of Sciences: Physics 86 (1), S24-S
Journal: Bulletin of the Russian Academy of Sciences: Physics


Bulletin of the Russian Academy of Sciences: Physics 86 (1), S20-S
Journal: Bulletin of the Russian Academy of Sciences: Physics


Bulletin of the Russian Academy of Sciences: Physics 86 (1), S179-S
Journal: Bulletin of the Russian Academy of Sciences: Physics


Bulletin of the Russian Academy of Sciences: Physics 86 (1), S201-S
Journal: Bulletin of the Russian Academy of Sciences: Physics


Bulletin of the Russian Academy of Sciences: Physics 86 (1), S127-S
Journal: Bulletin of the Russian Academy of Sciences: Physics


Bulletin of the Russian Academy of Sciences: Physics 86 (1), S191-S
Journal: Bulletin of the Russian Academy of Sciences: Physics


Bulletin of the Russian Academy of Sciences: Physics 86 (1), S152-S
Journal: Bulletin of the Russian Academy of Sciences: Physics


Science Advances 6 (42), eabb
Journal: Science Advances


Applied Physics Letters 104 (6), 29_
Journal: Applied Physics Letters


Science advances 8 (2), eabk
Journal: Science advances


Applied Physics Letters 106 (7), 21_
Journal: Applied Physics Letters


Applied Physics Letters 102 (18), 84_
Journal: Applied Physics Letters


Applied Physics Letters 105 (22), 178_
Journal: Applied Physics Letters


Physical Review-Section B-Condensed Matter 63 (12), 121302R
Journal: Physical Review-Section B-Condensed Matter


HUMAN GENE THERAPY 28 (12), A124-A
Journal: HUMAN GENE THERAPY


Physical Review-Section B-Condensed Matter 65 (24), 241301R
Journal: Physical Review-Section B-Condensed Matter


Science 368 (6497), eaba
Journal: Science


Science advances 5 (4), eaav
Journal: Science advances


Photonics Research 8 (11), A56-A
Journal: Photonics Research


Journal of The Electrochemical Society 155 (2), G
Journal: Journal of The Electrochemical Society


Science Advances 4 (5), eaar
Journal: Science Advances


ECS Solid State Letters 1 (5), Q
Journal: ECS Solid State Letters


Nanotechnology 15 (4), S
Journal: Nanotechnology


Electrochemical and solid-state letters 11 (3), G
Journal: Electrochemical and solid-state letters


Nanotechnology 17 (11), S
Journal: Nanotechnology


Surface science 418 (1), L8-L
Journal: Surface science


Journal of the Electrochemical Society 150 (7), G
Journal: Journal of the Electrochemical Society


Surface science 515 (1), L469-L
Journal: Surface science


Journal of the Electrochemical Society 156 (1), H
Journal: Journal of the Electrochemical Society


Science Advances 5 (8), eaaw
Journal: Science Advances


Surface science 459 (3), L475-L
Journal: Surface science


Journal of the Electrochemical Society 150 (7), G
Journal: Journal of the Electrochemical Society


Science Advances 7 (3), eabd
Journal: Science Advances


Advanced Materials 24 (23), OP159-OP
Journal: Advanced Materials


Optics express 26 (2), A66-A
Journal: Optics express


Applied Physics Letters 106 (2), 4_
Journal: Applied Physics Letters


Photonics Research 8 (10), A39-A
Journal: Photonics Research


Photonics Research 8 (9), A25-A
Journal: Photonics Research


Science advances 5 (12), eaay
Journal: Science advances


Science 368 (6488), eaay
Journal: Science


Proceedings of the National Academy of Sciences 114 (33), E6739-
Journal: Proceedings of the National Academy of Sciences


Applied Physics Letters 103 (24), 236_
Journal: Applied Physics Letters


Electrochemical and Solid-State Letters 8 (10), J
Journal: Electrochemical and Solid-State Letters


Applied Physics Letters 107 (7), 81_
Journal: Applied Physics Letters


Optics express 24 (22), A1454-A
Journal: Optics express


Optics express 23 (7), A391-A
Journal: Optics express


Journal of The Electrochemical Society 156 (11), H
Journal: Journal of The Electrochemical Society


Journal of The Electrochemical Society 153 (8), G
Journal: Journal of The Electrochemical Society


Journal of The Electrochemical Society 154 (1), H
Journal: Journal of The Electrochemical Society


Journal of The Electrochemical Society 154 (6), H
Journal: Journal of The Electrochemical Society


Electrochemical and solid-state letters 8 (3), G
Journal: Electrochemical and solid-state letters


Journal of The Electrochemical Society 154 (6), H
Journal: Journal of The Electrochemical Society


Current Applied Physics 10 (3), S361-S
Journal: Current Applied Physics


Journal of the Electrochemical Society 154 (6), H
Journal: Journal of the Electrochemical Society


Optics express 23 (15), A858-A
Journal: Optics express


Chinese Journal of Lasers 50 (1), 0113002-
Journal: Chinese Journal of Lasers


Journal of the Electrochemical Society 148 (4), C
Journal: Journal of the Electrochemical Society


Journal of the Electrochemical Society 150 (9), C
Journal: Journal of the Electrochemical Society


Journal of The Electrochemical Society 149 (11), C
Journal: Journal of The Electrochemical Society


Journal of the Electrochemical Society 152 (2), C
Journal: Journal of the Electrochemical Society


Electrochemical and solid-state letters 9 (2), H
Journal: Electrochemical and solid-state letters


Journal of The Electrochemical Society 151 (1), H
Journal: Journal of The Electrochemical Society


Journal of Nanophotonics 5 (1), 051816-
Journal: Journal of Nanophotonics


Electrochemical and Solid State Letters 9 (2), H
Journal: Electrochemical and Solid State Letters


Journal of the Electrochemical Society 151 (1), H
Journal: Journal of the Electrochemical Society


Journal of the Electrochemical Society 150 (9), C
Journal: Journal of the Electrochemical Society


Science Advances 7 (8), eabd
Journal: Science Advances


Science Advances 6 (45), eabb
Journal: Science Advances


National Science Review 9 (7), nwac
Journal: National Science Review


National Science Review 9 (10), nwac
Journal: National Science Review


Journal of Applied Physics 110 (9), 094108-
Journal: Journal of Applied Physics


Physical Review B 55 (2), R
Journal: Physical Review B


Applied Physics Letters 100 (19), 192907-
Journal: Applied Physics Letters


Journal of applied physics 101 (10), 104115-
Journal: Journal of applied physics


Applied Physics Letters 96 (24), 242902-
Journal: Applied Physics Letters


Applied Physics Letters 93 (26), 262901-
Journal: Applied Physics Letters


Applied Physics Letters 98 (7), 072907-
Journal: Applied Physics Letters


Journal of Applied Physics 112 (6), 064114-
Journal: Journal of Applied Physics


Journal of Physics: Condensed Matter 18 (17), R
Journal: Journal of Physics: Condensed Matter


Science advances 5 (2), eaau
Journal: Science advances


Physical Review B 55 (4), R
Journal: Physical Review B


Physical Review B 58 (12), R
Journal: Physical Review B


Science advances 8 (1), eabj
Journal: Science advances


Physical Review B 56 (20), R
Journal: Physical Review B


Physical Review B 105 (22), L
Journal: Physical Review B


Physical Review-Section B-Condensed Matter 67 (2), 20101R
Journal: Physical Review-Section B-Condensed Matter


Physical Review-Section B-Condensed Matter 58 (12), R
Journal: Physical Review-Section B-Condensed Matter


Journal of Applied Physics 117 (17), 17C
Journal: Journal of Applied Physics


Archives of Metallurgy and Materials 60 (1), 381-
Journal: Archives of Metallurgy and Materials


Applied Physics Letters 105 (18), 166_
Journal: Applied Physics Letters


Science Advances 6 (42), eabb
Journal: Science Advances


Science Advances 8 (8), eabl
Journal: Science Advances


JOSA B 36 (2), A79-A
Journal: JOSA B


BIOPHYSICAL JOURNAL 70 (2), TU535-TU
Journal: BIOPHYSICAL JOURNAL


ECS Journal of Solid State Science and Technology 3 (2), N
Journal: ECS Journal of Solid State Science and Technology


Journal of the Anatomical Society of India 2 (65), S64-S
Journal: Journal of the Anatomical Society of India


Optics Express 23 (24), A1720-A
Journal: Optics Express


Optics Express 23 (11), A502-A
Journal: Optics Express


Optics Express 24 (14), A1083-A
Journal: Optics Express


Optics Express 24 (6), A434-A
Journal: Optics Express


Optics Express 21 (105), A883-A
Journal: Optics Express


Optics Express 22 (101), A111-A
Journal: Optics Express


Optics Express 24 (6), A460-A
Journal: Optics Express


Optics express 20 (102), A157-A
Journal: Optics express


Optics Express 19 (102), A136-A
Journal: Optics Express


Optics Express 27 (20), A1419-A
Journal: Optics Express


Optics Express 22 (102), A452-A
Journal: Optics Express


Optics Express 26 (18), A761-A
Journal: Optics Express


Journal of Applied Physics 111 (8), 089901-
Journal: Journal of Applied Physics


Science advances 3 (10), eaao
Journal: Science advances


Science 368 (6488), eaay
Journal: Science


Science Advances 7 (18), eabf
Journal: Science Advances


Archives of Materials Science and Engineering 72 (2), 86-
Journal: Archives of Materials Science and Engineering


Journal of The Electrochemical Society 152 (12), A
Journal: Journal of The Electrochemical Society


Archives of Materials Science and Engineering 72 (1), 16-
Journal: Archives of Materials Science and Engineering


Journal of the Electrochemical Society 152 (12), A
Journal: Journal of the Electrochemical Society


Journal of Physics: Condensed Matter 18 (42), L
Journal: Journal of Physics: Condensed Matter


Journal of Physics: Condensed Matter 17 (40), S
Journal: Journal of Physics: Condensed Matter


Journal of Optics A: Pure and Applied Optics 8 (7), S
Journal: Journal of Optics A: Pure and Applied Optics


Physical Review B 62 (24), R
Journal: Physical Review B


Physical Review B 59 (24), R
Journal: Physical Review B


Physical Review B 61 (8), R
Journal: Physical Review B


Semiconductor science and technology 18 (10), S
Journal: Semiconductor science and technology


Physical Review-Section B-Condensed Matter 61 (8), R
Journal: Physical Review-Section B-Condensed Matter


Physical Review-Section B-Condensed Matter 62 (24), R
Journal: Physical Review-Section B-Condensed Matter


Physical Review-Section B-Condensed Matter 59 (24), R
Journal: Physical Review-Section B-Condensed Matter


Journal of Physics: Condensed Matter 18 (17), R
Journal: Journal of Physics: Condensed Matter


Journal of Physics: Condensed Matter 11 (48), L
Journal: Journal of Physics: Condensed Matter


Journal of Physics C: Solid State Physics 20 (26), L
Journal: Journal of Physics C: Solid State Physics


Journal of Physics C: Solid State Physics 19 (15), L
Journal: Journal of Physics C: Solid State Physics


Physical Review-Section B-Condensed Matter 67 (2), 20101R
Journal: Physical Review-Section B-Condensed Matter


Physical Review B 63 (8), 5204/1-5204/
Journal: Physical Review B


Applied Physics Letters 103 (5), 142_
Journal: Applied Physics Letters


Applied Physics Letters 106 (17), 45_
Journal: Applied Physics Letters


Science Advances 7 (18), eabf
Journal: Science Advances


Journal of the Electrochemical Society 159 (10), F
Journal: Journal of the Electrochemical Society


Science 361 (6408), eaat
Journal: Science


Journal of Semiconductors 42 (3), 030201-
Journal: Journal of Semiconductors


Journal of Physics: Condensed Matter 16 (29), R
Journal: Journal of Physics: Condensed Matter


Science advances 3 (9), eaao
Journal: Science advances


Journal of the Electrochemical Society 159 (2), H
Journal: Journal of the Electrochemical Society


Journal of the Electrochemical Society 159 (2), H
Journal: Journal of the Electrochemical Society


Science advances 3 (12), eaaq
Journal: Science advances


Biophysical Journal 100 (3), 624a
Journal: Biophysical Journal


Biophysical Journal 98 (3), 605a
Journal: Biophysical Journal


Science Advances 6 (42), eabb
Journal: Science Advances


Journal of The Electrochemical Society 164 (13), C
Journal: Journal of The Electrochemical Society


Optics Express 24 (6), A674-A
Journal: Optics Express


Science Advances 8 (29), eabp
Journal: Science Advances


Science Advances 8 (30), eabn
Journal: Science Advances


Journal of The Electrochemical Society 154 (8), H
Journal: Journal of The Electrochemical Society


ECS Journal of Solid State Science and Technology 6 (6), M
Journal: ECS Journal of Solid State Science and Technology


Journal of The Electrochemical Society 154 (8), H
Journal: Journal of The Electrochemical Society


ECS Journal of Solid State Science and Technology 6 (6), M
Journal: ECS Journal of Solid State Science and Technology


Science 352 (6283), aad
Journal: Science


Applied Physics Letters 103 (15), 190_
Journal: Applied Physics Letters


ECS Solid State Letters 3 (6), N
Journal: ECS Solid State Letters


Journal of The Electrochemical Society 161 (14), F
Journal: Journal of The Electrochemical Society


Journal of The Electrochemical Society 161 (14), F
Journal: Journal of The Electrochemical Society


Journal of Magnetism and Magnetic Materials 304 (1), e106-
Journal: Journal of Magnetism and Magnetic Materials


Journal of Magnetism and Magnetic Materials 316 (2), e215-
Journal: Journal of Magnetism and Magnetic Materials


Journal of Magnetism and Magnetic Materials 304 (1), e152-
Journal: Journal of Magnetism and Magnetic Materials


Journal of applied physics 99 (8), 08M
Journal: Journal of applied physics


Journal of Magnetism and Magnetic Materials 310 (2), e876-
Journal: Journal of Magnetism and Magnetic Materials


Journal of Magnetism and Magnetic Materials 310 (2), e618-
Journal: Journal of Magnetism and Magnetic Materials


Journal of Magnetism and Magnetic Materials 304 (1), e106-
Journal: Journal of Magnetism and Magnetic Materials


Journal of Magnetism and Magnetic Materials 316 (2), e215-
Journal: Journal of Magnetism and Magnetic Materials


Journal of Magnetism and Magnetic Materials 304 (1), e152-
Journal: Journal of Magnetism and Magnetic Materials


Journal of applied physics 99 (8), 08M
Journal: Journal of applied physics


Journal of Magnetism and Magnetic Materials 310 (2), e876-
Journal: Journal of Magnetism and Magnetic Materials


Journal of Magnetism and Magnetic Materials 310 (2), e618-
Journal: Journal of Magnetism and Magnetic Materials


Biophysical Journal 106 (2), 605a
Journal: Biophysical Journal


Biophysical Journal 106 (2), 605a
Journal: Biophysical Journal


Science Advances 7 (50), eabi
Journal: Science Advances


Journal of The Electrochemical Society 160 (2), H
Journal: Journal of The Electrochemical Society


Journal of The Electrochemical Society 166 (16), F
Journal: Journal of The Electrochemical Society


Journal of The Electrochemical Society 162 (7), D
Journal: Journal of The Electrochemical Society


Biophysical Journal 100 (3), 27a
Journal: Biophysical Journal


Small 16 (12), Article number:
Journal: Small


Small 16 (12), Article number:
Journal: Small


Acta Crystallographica Section E: Structure Reports Online 63 (6), o2893-o
Journal: Acta Crystallographica Section E: Structure Reports Online


Acta Crystallographica Section E: Structure Reports Online 63 (6), o2894-o
Journal: Acta Crystallographica Section E: Structure Reports Online


Acta Crystallographica Section E: Structure Reports Online 63 (6), o2893-o
Journal: Acta Crystallographica Section E: Structure Reports Online


Acta Crystallographica Section E: Structure Reports Online 63 (6), o2894-o
Journal: Acta Crystallographica Section E: Structure Reports Online


JOURNAL OF THE ELECTROCHEMICAL SOCIETY 125 (8), C366-C
Journal: JOURNAL OF THE ELECTROCHEMICAL SOCIETY


JOURNAL OF THE ELECTROCHEMICAL SOCIETY 125 (8), C366-C
Journal: JOURNAL OF THE ELECTROCHEMICAL SOCIETY


Croatica Chemica Acta 90 (2), T1-T
Journal: Croatica Chemica Acta


Acta Crystallographica Section E: Structure Reports Online 57 (9), o893-o
Journal: Acta Crystallographica Section E: Structure Reports Online


Croatica Chemica Acta 90 (2), T1-T
Journal: Croatica Chemica Acta


Acta Crystallographica Section E: Structure Reports Online 57 (9), o893-o
Journal: Acta Crystallographica Section E: Structure Reports Online


Science Advances 7 (52), eabj
Journal: Science Advances


Photonics Research 8 (11), A56-A
Journal: Photonics Research


Photonics Research 8 (11), A56-A
Journal: Photonics Research


physica status solidi (a) 193 (1), R4-R
Journal: physica status solidi (a)


physica status solidi (a) 193 (1), R4-R
Journal: physica status solidi (a)


Science advances 7 (16), eabf
Journal: Science advances


National Science Review 8 (9), nwaa
Journal: National Science Review


Science Advances 8 (30), eabq
Journal: Science Advances


Science advances 7 (16), eabf
Journal: Science advances


National Science Review 8 (9), nwaa
Journal: National Science Review


Science Advances 8 (30), eabq
Journal: Science Advances


CADERNO DE FÍSICA DA UEFS 1 (17), 1301.1
Journal: CADERNO DE FÍSICA DA UEFS


Caderno de Física da UEFS 14 (02), 2401.1-2401.
Journal: Caderno de Física da UEFS


Journal of the Electrochemical Society 157 (8), A
Journal: Journal of the Electrochemical Society


Journal of the Electrochemical Society 157 (8), A
Journal: Journal of the Electrochemical Society


Science advances 5 (5), eaau
Journal: Science advances


stress 200 (4), 3.
Journal: stress


Journal of Biomedical Optics 16 (6), 066002-
Journal: Journal of Biomedical Optics


Journal of Biomedical Optics 16 (6), 066002-
Journal: Journal of Biomedical Optics


Proceedings of the National Academy of Sciences 112 (30), E3987-
Journal: Proceedings of the National Academy of Sciences


Science advances 7 (49), eabj
Journal: Science advances


Science advances 7 (49), eabj
Journal: Science advances


Physical Review Applied 17 (5), L
Journal: Physical Review Applied


Physical Review B 106 (4), L
Journal: Physical Review B


Physical Review B 106 (4), L
Journal: Physical Review B


Biochemical Society Transactions 28 (1), A44-A
Journal: Biochemical Society Transactions


Biochemical Society Transactions 28 (1), A44-A
Journal: Biochemical Society Transactions


Applied Physics Letters 105 (2), 105_
Journal: Applied Physics Letters


Applied Physics Letters 105 (2), 105_
Journal: Applied Physics Letters


Journal of Instrumentation 8 (12), C
Journal: Journal of Instrumentation


Journal of Instrumentation 12 (05), P
Journal: Journal of Instrumentation



In [37]:
df4['Source'].value_counts()

The Journal of Physical Chemistry C                        792
Advanced Materials                                         667
ACS Energy Letters                                         552
Physical Review B                                          552
Applied Physics Letters                                    518
                                                          ...
Chem. Eur. J.                                                1
J. Phys. Chem. Lett.                                         1
Nonlinear Optics of Liquid and Photorefractive Crystals      1
Electronic Processes in Organic Materials                    1
Nano convergence                                             1
Name: Source, Length: 2771, dtype: int64

In [38]:
df5 = df4.assign(Source = df4['Source'].apply(lambda row: np.char.capitalize(str(row))))

In [39]:
df5['Source'].value_counts()

The journal of physical chemistry c                             800
Advanced materials                                              724
Applied physics letters                                         673
Acs energy letters                                              578
Physical review b                                               564
                                                               ...
International journal of modern physics b 14 (29n31)              1
Gravitational wave detection ii                                   1
International journal of modern physics b 13 (conf-9810174-)      1
Journal of alloys and compounds(switzerland)                      1
Journal of the indian botanical society 74 (1-4)                  1
Name: Source, Length: 2443, dtype: int64

In [40]:
import re
pattern = r'^([^,]+)'

vals = df5['Source'].values
index = df5['Source'].index

for idx, val in enumerate(df5['Source'].values):

    # match pattern to citation
    match = re.match(pattern, val)

    if match:
        journal = match.group(1)
        
        # print extracted values
        print(val)
        print('Journal:', journal)
        print('\n')
        
        df5.loc[index[idx], 'Source'] = journal
        
    else:
        pass

Science
Journal: Science


Nature
Journal: Nature


Nature materials
Journal: Nature materials


Science
Journal: Science


Nature
Journal: Nature


Nature nanotechnology
Journal: Nature nanotechnology


Science
Journal: Science


Nature materials
Journal: Nature materials


Nature photonics
Journal: Nature photonics


Nature nanotechnology
Journal: Nature nanotechnology


Science
Journal: Science


Nature nanotechnology
Journal: Nature nanotechnology


Nature
Journal: Nature


Science
Journal: Science


Nature
Journal: Nature


Nature communications
Journal: Nature communications


Journal of the american chemical society
Journal: Journal of the american chemical society


Science
Journal: Science


Chemical reviews
Journal: Chemical reviews


Nature
Journal: Nature


Nature reviews materials
Journal: Nature reviews materials


Science
Journal: Science


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Joule
Journal: Joule


Nature energy
Journal: Nature energy


Nature photonics
Journal: Nature photonics


Nature photonics
Journal: Nature photonics


Nano letters
Journal: Nano letters


Nature communications
Journal: Nature communications


Nature communications
Journal: Nature communications


Journal of the american chemical society
Journal: Journal of the american chemical society


Chemical reviews
Journal: Chemical reviews


Science
Journal: Science


Nature catalysis
Journal: Nature catalysis


Science
Journal: Science


Nature energy
Journal: Nature energy


Nature catalysis
Journal: Nature catalysis


Nature materials
Journal: Nature materials


Nature chemistry
Journal: Nature chemistry


Nature materials
Journal: Nature materials


Nature nanotechnology
Journal: Nature nanotechnology


Nature
Journal: Nature


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Chemical reviews
Journal: Chemical reviews


Advanced materials
Journal: Advanced materials


Chemical reviews
Journal: Chemical reviews


Applied physics letters
Journal: Applied physics letters


Nature communications
Journal: Nature communications


Nature
Journal: Nature


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nature
Journal: Nature


Nature energy
Journal: Nature energy


Nature photonics
Journal: Nature photonics


Nature photonics
Journal: Nature photonics


Nature catalysis
Journal: Nature catalysis


Science
Journal: Science


Nature photonics
Journal: Nature photonics


Nature nanotechnology
Journal: Nature nanotechnology


Nature materials
Journal: Nature materials


Nature chemistry
Journal: Nature chemistry


Nature nanotechnology
Journal: Nature nanotechnology


Acs nano
Journal: Acs nano


Acs nano
Journal: Acs nano


Ieee communications magazine
Journal: Ieee communications magazine


Nature photonics
Journal: Nature photonics


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


Nature materials
Journal: Nature materials


Chemistry of materials
Journal: Chemistry of materials


Nature energy
Journal: Nature energy


Acs nano
Journal: Acs nano


Nature nanotechnology
Journal: Nature nanotechnology


Advanced materials
Journal: Advanced materials


Science
Journal: Science


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nature energy
Journal: Nature energy


Journal of the american chemical society
Journal: Journal of the american chemical society


Applied physics letters
Journal: Applied physics letters


Advanced functional materials
Journal: Advanced functional materials


Chemistry of materials
Journal: Chemistry of materials


Joule
Journal: Joule


Nature materials
Journal: Nature materials


Nature materials
Journal: Nature materials


Science
Journal: Science


Nature
Journal: Nature


Advanced materials
Journal: Advanced materials


Energy &environmental science
Journal: Energy &environmental science


Advanced materials
Journal: Advanced materials


Acs photonics
Journal: Acs photonics


Nature energy
Journal: Nature energy


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


Nature materials
Journal: Nature materials


Acs nano
Journal: Acs nano


Nature reviews materials
Journal: Nature reviews materials


Nano letters
Journal: Nano letters


Nature communications
Journal: Nature communications


Nature catalysis
Journal: Nature catalysis


Reviews of modern physics
Journal: Reviews of modern physics


Acs catalysis
Journal: Acs catalysis


Nature catalysis
Journal: Nature catalysis


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced materials
Journal: Advanced materials


Nature photonics
Journal: Nature photonics


Nature communications
Journal: Nature communications


Acs nano
Journal: Acs nano


Applied physics letters
Journal: Applied physics letters


Nature nanotechnology
Journal: Nature nanotechnology


Nature materials
Journal: Nature materials


Ieee network
Journal: Ieee network


Nature photonics
Journal: Nature photonics


Joule
Journal: Joule


Nature energy
Journal: Nature energy


Nature nanotechnology
Journal: Nature nanotechnology


Journal of the american chemical society
Journal: Journal of the american chemical society


Science
Journal: Science


Nature catalysis
Journal: Nature catalysis


Nature catalysis
Journal: Nature catalysis


Nature chemistry
Journal: Nature chemistry


Acs nano
Journal: Acs nano


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Nano letters
Journal: Nano letters


Nano letters
Journal: Nano letters


Nature
Journal: Nature


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Advanced materials
Journal: Advanced materials


Applied physics letters
Journal: Applied physics letters


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Optics express
Journal: Optics express


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature communications
Journal: Nature communications


Nature chemistry
Journal: Nature chemistry


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


Nature photonics
Journal: Nature photonics


Nature communications
Journal: Nature communications


Nature nanotechnology
Journal: Nature nanotechnology


Energy &environmental science
Journal: Energy &environmental science


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Applied physics letters
Journal: Applied physics letters


Nature chemistry
Journal: Nature chemistry


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Nature
Journal: Nature


Nano letters
Journal: Nano letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Acs energy letters
Journal: Acs energy letters


Joule
Journal: Joule


Nature nanotechnology
Journal: Nature nanotechnology


Applied physics letters
Journal: Applied physics letters


Nano letters
Journal: Nano letters


Applied physics letters
Journal: Applied physics letters


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


Nature
Journal: Nature


Advanced materials
Journal: Advanced materials


Nature biomedical engineering
Journal: Nature biomedical engineering


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


Applied physics letters
Journal: Applied physics letters


Advanced materials
Journal: Advanced materials


Applied physics letters
Journal: Applied physics letters


Acs nano
Journal: Acs nano


Journal of the american chemical society
Journal: Journal of the american chemical society


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Advanced functional materials
Journal: Advanced functional materials


Nature communications
Journal: Nature communications


Nature
Journal: Nature


Nano letters
Journal: Nano letters


Langmuir
Journal: Langmuir


Advanced materials
Journal: Advanced materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Nano letters
Journal: Nano letters


Acs energy letters
Journal: Acs energy letters


Angewandte chemie
Journal: Angewandte chemie


Advanced materials
Journal: Advanced materials


Acs energy letters
Journal: Acs energy letters


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Nature catalysis
Journal: Nature catalysis


Infrared physics &technology
Journal: Infrared physics &technology


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Advanced materials
Journal: Advanced materials


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced materials
Journal: Advanced materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs nano
Journal: Acs nano


Analytical chemistry
Journal: Analytical chemistry


Ieee journal of quantum electronics
Journal: Ieee journal of quantum electronics


Nature catalysis
Journal: Nature catalysis


Nano letters
Journal: Nano letters


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


Journal of the american chemical society
Journal: Journal of the american chemical society


Applied physics letters
Journal: Applied physics letters


Journal of lightwave technology
Journal: Journal of lightwave technology


Advanced materials
Journal: Advanced materials


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


Small
Journal: Small


Advanced energy materials
Journal: Advanced energy materials


Nature communications
Journal: Nature communications


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced functional materials
Journal: Advanced functional materials


Science
Journal: Science


Advanced materials
Journal: Advanced materials


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Applied physics letters
Journal: Applied physics letters


Nature energy
Journal: Nature energy


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Applied physics letters
Journal: Applied physics letters


Advanced materials
Journal: Advanced materials


Nature energy
Journal: Nature energy


Accounts of chemical research
Journal: Accounts of chemical research


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Acs nano
Journal: Acs nano


Nature communications
Journal: Nature communications


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs energy letters
Journal: Acs energy letters


Nano letters
Journal: Nano letters


Nature energy
Journal: Nature energy


Energy &environmental science
Journal: Energy &environmental science


Nature photonics
Journal: Nature photonics


Advanced science
Journal: Advanced science


Advanced materials
Journal: Advanced materials


Nature reviews materials
Journal: Nature reviews materials


Angewandte chemie
Journal: Angewandte chemie


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature communications
Journal: Nature communications


Joule
Journal: Joule


Langmuir
Journal: Langmuir


Nature communications
Journal: Nature communications


Optics letters
Journal: Optics letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature
Journal: Nature


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Nature materials
Journal: Nature materials


Acs nano
Journal: Acs nano


Lab on a chip
Journal: Lab on a chip


Acs energy letters
Journal: Acs energy letters


Nature energy
Journal: Nature energy


Acs energy letters
Journal: Acs energy letters


Applied physics letters
Journal: Applied physics letters


Scientific reports
Journal: Scientific reports


Nature reviews materials
Journal: Nature reviews materials


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Nature photonics
Journal: Nature photonics


Journal of the american chemical society
Journal: Journal of the american chemical society


Applied physics letters
Journal: Applied physics letters


Nature electronics
Journal: Nature electronics


Physical review letters
Journal: Physical review letters


Science advances
Journal: Science advances


Joule
Journal: Joule


Advanced materials
Journal: Advanced materials


Science advances
Journal: Science advances


Nature communications
Journal: Nature communications


Acs nano
Journal: Acs nano


Acs nano
Journal: Acs nano


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced materials
Journal: Advanced materials


Acs energy letters
Journal: Acs energy letters


Nature energy
Journal: Nature energy


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced materials
Journal: Advanced materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Joule
Journal: Joule


Advanced materials
Journal: Advanced materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature electronics
Journal: Nature electronics


Acs nano
Journal: Acs nano


Acs energy letters
Journal: Acs energy letters


Advanced materials
Journal: Advanced materials


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Journal of materials chemistry
Journal: Journal of materials chemistry


Nature materials
Journal: Nature materials


Analytical chemistry
Journal: Analytical chemistry


Acs energy letters
Journal: Acs energy letters


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Energy &environmental science
Journal: Energy &environmental science


Nature communications
Journal: Nature communications


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Acs energy letters
Journal: Acs energy letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced materials
Journal: Advanced materials


Joule
Journal: Joule


Nature communications
Journal: Nature communications


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Applied physics letters
Journal: Applied physics letters


Smartmat
Journal: Smartmat


Energy &environmental science
Journal: Energy &environmental science


Ieee communications letters
Journal: Ieee communications letters


Nature energy
Journal: Nature energy


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Applied physics letters
Journal: Applied physics letters


Nature communications
Journal: Nature communications


Physical review b
Journal: Physical review b


Matter
Journal: Matter


Acs energy letters
Journal: Acs energy letters


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Science advances
Journal: Science advances


Advanced materials
Journal: Advanced materials


Acs energy letters
Journal: Acs energy letters


Acs applied energy materials
Journal: Acs applied energy materials


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Journal of materials chemistry
Journal: Journal of materials chemistry


Josa b
Journal: Josa b


Acs energy letters
Journal: Acs energy letters


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


Physical review b
Journal: Physical review b


Nature catalysis
Journal: Nature catalysis


Nature chemistry
Journal: Nature chemistry


Ieee journal of solid-state circuits
Journal: Ieee journal of solid-state circuits


Physical review b
Journal: Physical review b


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Nature photonics
Journal: Nature photonics


Physical review b
Journal: Physical review b


Green chemistry
Journal: Green chemistry


Applied physics letters
Journal: Applied physics letters


Josa b
Journal: Josa b


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Angewandte chemie
Journal: Angewandte chemie


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Analytical chemistry
Journal: Analytical chemistry


Applied physics letters
Journal: Applied physics letters


Ieee communications letters
Journal: Ieee communications letters


Advanced materials
Journal: Advanced materials


Advanced functional materials
Journal: Advanced functional materials


Small
Journal: Small


Nano letters
Journal: Nano letters


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Synthetic metals
Journal: Synthetic metals


Nature communications
Journal: Nature communications


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Applied physics letters
Journal: Applied physics letters


Ieee communications letters
Journal: Ieee communications letters


Nano letters
Journal: Nano letters


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Advanced optical materials
Journal: Advanced optical materials


Nano letters
Journal: Nano letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Energy &environmental science
Journal: Energy &environmental science


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Joule
Journal: Joule


Nano letters
Journal: Nano letters


Journal of optics a: pure and applied optics
Journal: Journal of optics a: pure and applied optics


Nature communications
Journal: Nature communications


Nature communications
Journal: Nature communications


Nano letters
Journal: Nano letters


Applied physics letters
Journal: Applied physics letters


Nature communications
Journal: Nature communications


Advanced materials

The journal of physical chemistry c
Journal: The journal of physical chemistry c


Optical probes of conjugated polymers
Journal: Optical probes of conjugated polymers


Macromolecular chemistry and physics
Journal: Macromolecular chemistry and physics


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of chemical physics
Journal: The journal of chemical physics


Macromolecules
Journal: Macromolecules


Energy &environmental science
Journal: Energy &environmental science


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced functional materials
Journal: Advanced functional materials


Chemphyschem
Journal: Chemphyschem


Synthetic metals
Journal: Synthetic metals


Advanced energy materials
Journal: Advanced energy materials


Physical review b
Journal: Physical review b


Macromolecules
Journal: Macromolecules


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Colloid and polymer science
Journal: Colloid and polymer science


Berichte der bunsengesellschaft für physikalische chemie
Journal: Berichte der bunsengesellschaft für physikalische chemie


Macromolecules
Journal: Macromolecules


Applied physics letters
Journal: Applied physics letters


The journal of chemical physics
Journal: The journal of chemical physics


Polymer
Journal: Polymer


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced functional materials
Journal: Advanced functional materials


Molecular crystals and liquid crystals
Journal: Molecular crystals and liquid crystals


Journal of the american chemical society
Journal: Journal of the american chemical society


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Advanced materials
Journal: Advanced materials


Advanced electronic materials
Journal: Advanced electronic materials


Journal of applied physics
Journal: Journal of applied physics


Solar rrl
Journal: Solar rrl


Apl materials
Journal: Apl materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Macromolecular symposia
Journal: Macromolecular symposia


Berichte der bunsengesellschaft für physikalische chemie
Journal: Berichte der bunsengesellschaft für physikalische chemie


Acs energy letters
Journal: Acs energy letters


Physical review applied
Journal: Physical review applied


Journal of polymer science part b: polymer physics
Journal: Journal of polymer science part b: polymer physics


Adv. funct. mater
Journal: Adv. funct. mater


Berichte der bunsengesellschaft für physikalische chemie
Journal: Berichte der bunsengesellschaft für physikalische chemie


Physical review b
Journal: Physical review b


Macromolecules
Journal: Macromolecules


Macromolecular chemistry and physics
Journal: Macromolecular chemistry and physics


Synthetic metals
Journal: Synthetic metals


Advanced energy materials
Journal: Advanced energy materials


The journal of chemical physics
Journal: The journal of chemical physics


Science and technology of advanced materials
Journal: Science and technology of advanced materials


Journal of applied physics
Journal: Journal of applied physics


Applied physics letters
Journal: Applied physics letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Applied physics letters
Journal: Applied physics letters


Solar rrl
Journal: Solar rrl


Advanced energy materials
Journal: Advanced energy materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Thin solid films
Journal: Thin solid films


Energy &environmental science
Journal: Energy &environmental science


Nature communications
Journal: Nature communications


Chemistry of materials
Journal: Chemistry of materials


Macromolecules
Journal: Macromolecules


Physica status solidi (a)
Journal: Physica status solidi (a)


Macromolecular rapid communications
Journal: Macromolecular rapid communications


The journal of chemical physics
Journal: The journal of chemical physics


Liquid crystals
Journal: Liquid crystals


Macromolecules
Journal: Macromolecules


Advanced energy materials
Journal: Advanced energy materials


Solar rrl
Journal: Solar rrl


Rsc advances
Journal: Rsc advances


Acs energy letters
Journal: Acs energy letters


Frontiers in chemistry
Journal: Frontiers in chemistry


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Chemphyschem
Journal: Chemphyschem


Applied physics a
Journal: Applied physics a


Journal of polymer science part a: polymer chemistry
Journal: Journal of polymer science part a: polymer chemistry


Energy procedia
Journal: Energy procedia


Journal of applied physics
Journal: Journal of applied physics


Nanotechnology
Journal: Nanotechnology


Macromolecules
Journal: Macromolecules


Physica status solidi (a)
Journal: Physica status solidi (a)


Organic photovoltaics iv
Journal: Organic photovoltaics iv


Angewandte chemie-german edition
Journal: Angewandte chemie-german edition


Organic light-emitting materials and devices iii
Journal: Organic light-emitting materials and devices iii


Chem. mater
Journal: Chem. mater


Makromolekulare chemie. macromolecular symposia
Journal: Makromolekulare chemie. macromolecular symposia


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Physica status solidi (a)
Journal: Physica status solidi (a)


Liquid crystals iv
Journal: Liquid crystals iv


Chemical physics letters 202 (1-2)
Journal: Chemical physics letters 202 (1-2)


Nonlinear optical properties of organic materials iv
Journal: Nonlinear optical properties of organic materials iv


Electronic properties of conjugated polymers iii
Journal: Electronic properties of conjugated polymers iii


Materials horizons
Journal: Materials horizons


Acs applied polymer materials
Journal: Acs applied polymer materials


Journal of applied physics
Journal: Journal of applied physics


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of applied physics
Journal: Journal of applied physics


Applied physics reviews
Journal: Applied physics reviews


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Applied physics letters
Journal: Applied physics letters


Journal of luminescence 112 (1-4)
Journal: Journal of luminescence 112 (1-4)


Electronic properties of conjugated polymers iii
Journal: Electronic properties of conjugated polymers iii


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Synthetic metals
Journal: Synthetic metals


Organic photonics and photovoltaics
Journal: Organic photonics and photovoltaics


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Nonlinear optical properties of organic materials vii
Journal: Nonlinear optical properties of organic materials vii


Applied physics letters
Journal: Applied physics letters


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Synthetic metals
Journal: Synthetic metals


Second-order organic nonlinear optics
Journal: Second-order organic nonlinear optics


Chemical materials
Journal: Chemical materials


Makromolekulare chemie. macromolecular symposia
Journal: Makromolekulare chemie. macromolecular symposia


Advanced energy materials
Journal: Advanced energy materials


Advanced functional materials
Journal: Advanced functional materials


Journal of applied physics
Journal: Journal of applied physics


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Physical review applied
Journal: Physical review applied


J. phys. chem. lett
Journal: J. phys. chem. lett


Physics, chemistry and application of nanostructures: reviews and short …
Journal: Physics


Organic photonic materials and devices ix
Journal: Organic photonic materials and devices ix


Journal of applied physics
Journal: Journal of applied physics


Optical materials
Journal: Optical materials


Nonlinear optical properties of advanced materials
Journal: Nonlinear optical properties of advanced materials


Advanced materials
Journal: Advanced materials


Special publications of the royal society of chemistry
Journal: Special publications of the royal society of chemistry


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Organic photovoltaics iv
Journal: Organic photovoltaics iv


Nature communications
Journal: Nature communications


Nature communications
Journal: Nature communications


Communications physics
Journal: Communications physics


Solar rrl
Journal: Solar rrl


Advanced materials
Journal: Advanced materials


Advanced energy materials
Journal: Advanced energy materials


Physical review applied
Journal: Physical review applied


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs nano
Journal: Acs nano


Advanced energy materials
Journal: Advanced energy materials


Printed memory and circuits
Journal: Printed memory and circuits


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Vakuum in forschung und praxis
Journal: Vakuum in forschung und praxis


Advanced materials
Journal: Advanced materials


Macromolecular chemistry and physics
Journal: Macromolecular chemistry and physics


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Nonlinear optical effects in organic polymers
Journal: Nonlinear optical effects in organic polymers


Electrical and related properties of organic solids
Journal: Electrical and related properties of organic solids


Verhandlungen der deutschen physikalischen gesellschaft
Journal: Verhandlungen der deutschen physikalischen gesellschaft


Verhandlungen der deutschen physikalischen gesellschaft
Journal: Verhandlungen der deutschen physikalischen gesellschaft


Verhandlungen der deutschen physikalischen gesellschaft
Journal: Verhandlungen der deutschen physikalischen gesellschaft


Verhandlungen der deutschen physikalischen gesellschaft
Journal: Verhandlungen der deutschen physikalischen gesellschaft


Organic optoelectronics and photonics ii
Journal: Organic optoelectronics and photonics ii


Nanophotonics
Journal: Nanophotonics


Nanomanipulation with light ii
Journal: Nanomanipulation with light ii


Verhandlungen der deutschen physikalischen gesellschaft
Journal: Verhandlungen der deutschen physikalischen gesellschaft


Verhandlungen der deutschen physikalischen gesellschaft
Journal: Verhandlungen der deutschen physikalischen gesellschaft


Verhandlungen der deutschen physikalischen gesellschaft
Journal: Verhandlungen der deutschen physikalischen gesellschaft


Organic light-emitting materials and devices vii
Journal: Organic light-emitting materials and devices vii


Chemphyschem
Journal: Chemphyschem


Macromolecules
Journal: Macromolecules


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Applied physics letters
Journal: Applied physics letters


Journal of applied physics
Journal: Journal of applied physics


Journal of applied physics
Journal: Journal of applied physics


Journal of physical chemistry b-condensed phase
Journal: Journal of physical chemistry b-condensed phase


Appl. phys. lett
Journal: Appl. phys. lett


Journal of applied physics
Journal: Journal of applied physics


Macromolecules
Journal: Macromolecules


El 96 berlin
Journal: El 96 berlin


Nonlinear optical properties of advanced materials
Journal: Nonlinear optical properties of advanced materials


Chemical physics letters
Journal: Chemical physics letters


Nonlinear optical properties of organic materials
Journal: Nonlinear optical properties of organic materials


Organic materials for non-linear optics ii
Journal: Organic materials for non-linear optics ii


J. phys. chem
Journal: J. phys. chem


Special publication
Journal: Special publication


Special publication
Journal: Special publication


Chemcatchem
Journal: Chemcatchem


Chemical reviews
Journal: Chemical reviews


Catalysis communications
Journal: Catalysis communications


The journal of physical chemistry
Journal: The journal of physical chemistry


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Chemsuschem
Journal: Chemsuschem


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Topics in catalysis
Journal: Topics in catalysis


Catalysis today
Journal: Catalysis today


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Journal of catalysis
Journal: Journal of catalysis


Journal of catalysis
Journal: Journal of catalysis


Journal of catalysis
Journal: Journal of catalysis


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of materials chemistry
Journal: Journal of materials chemistry


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Journal of catalysis
Journal: Journal of catalysis


Catalysis letters
Journal: Catalysis letters


Journal of catalysis
Journal: Journal of catalysis


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of catalysis
Journal: Journal of catalysis


Journal of molecular catalysis a: chemical
Journal: Journal of molecular catalysis a: chemical


Applied catalysis a: general
Journal: Applied catalysis a: general


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Journal of catalysis
Journal: Journal of catalysis


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Catalysis today
Journal: Catalysis today


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Applied catalysis a: general
Journal: Applied catalysis a: general


Chemsuschem
Journal: Chemsuschem


Journal of materials chemistry
Journal: Journal of materials chemistry


Topics in catalysis
Journal: Topics in catalysis


Journal of catalysis
Journal: Journal of catalysis


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Journal of catalysis
Journal: Journal of catalysis


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Journal of catalysis
Journal: Journal of catalysis


Journal of materials chemistry
Journal: Journal of materials chemistry


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Journal of catalysis
Journal: Journal of catalysis


Journal of materials chemistry
Journal: Journal of materials chemistry


International journal of hydrogen energy
Journal: International journal of hydrogen energy


J. chim. phys
Journal: J. chim. phys


Journal of molecular catalysis
Journal: Journal of molecular catalysis


Applied catalysis a: general
Journal: Applied catalysis a: general


Topics in catalysis
Journal: Topics in catalysis


Journal of catalysis
Journal: Journal of catalysis


Acs catalysis
Journal: Acs catalysis


Catalysis today
Journal: Catalysis today


Acs catalysis
Journal: Acs catalysis


Journal of catalysis
Journal: Journal of catalysis


Catalysis today
Journal: Catalysis today


International journal of hydrogen energy
Journal: International journal of hydrogen energy


Catalysis
Journal: Catalysis


Journal of catalysis
Journal: Journal of catalysis


Environmental science &technology
Journal: Environmental science &technology


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Journal of molecular catalysis a: chemical 268 (1-2)
Journal: Journal of molecular catalysis a: chemical 268 (1-2)


Studies in surface science and catalysis
Journal: Studies in surface science and catalysis


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Industrial &engineering chemistry research
Journal: Industrial &engineering chemistry research


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of catalysis
Journal: Journal of catalysis


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Journal of molecular catalysis a: chemical 175 (1-2)
Journal: Journal of molecular catalysis a: chemical 175 (1-2)


Catalysis today
Journal: Catalysis today


Applied catalysis a: general
Journal: Applied catalysis a: general


Catalysis communications
Journal: Catalysis communications


Catalysis letters
Journal: Catalysis letters


International journal of hydrogen energy
Journal: International journal of hydrogen energy


Journal of catalysis
Journal: Journal of catalysis


Journal of molecular catalysis a: chemical 293 (1-2)
Journal: Journal of molecular catalysis a: chemical 293 (1-2)


Journal of propulsion and power
Journal: Journal of propulsion and power


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of catalysis
Journal: Journal of catalysis


Oil &gas science and technology–revue d’ifp energies nouvelles
Journal: Oil &gas science and technology–revue d’ifp energies nouvelles


Acs catalysis
Journal: Acs catalysis


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Applied catalysis
Journal: Applied catalysis


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Journal of catalysis
Journal: Journal of catalysis


Journal of molecular catalysis a: chemical 320 (1-2)
Journal: Journal of molecular catalysis a: chemical 320 (1-2)


Journal of catalysis
Journal: Journal of catalysis


Applied catalysis a: general
Journal: Applied catalysis a: general


Catalysis communications
Journal: Catalysis communications


Applied catalysis
Journal: Applied catalysis


Applied catalysis
Journal: Applied catalysis


Applied catalysis a: general
Journal: Applied catalysis a: general


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Journal of materials chemistry
Journal: Journal of materials chemistry


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Journal of catalysis
Journal: Journal of catalysis


Journal of the less common metals
Journal: Journal of the less common metals


Microporous and mesoporous materials
Journal: Microporous and mesoporous materials


Solid state sciences
Journal: Solid state sciences


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Topics in catalysis
Journal: Topics in catalysis


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Studies in surface science and catalysis
Journal: Studies in surface science and catalysis


Catalysts
Journal: Catalysts


Journal of catalysis
Journal: Journal of catalysis


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Chemical engineering research and design
Journal: Chemical engineering research and design



Advanced materials
Journal: Advanced materials


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nature communications
Journal: Nature communications


Physical review letters
Journal: Physical review letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Nanotechnology
Journal: Nanotechnology


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


Advanced optical materials
Journal: Advanced optical materials


Light: science &applications
Journal: Light: science &applications


Advanced materials
Journal: Advanced materials


Physical review letters
Journal: Physical review letters


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Science
Journal: Science


Advanced functional materials
Journal: Advanced functional materials


Angewandte chemie
Journal: Angewandte chemie


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced materials
Journal: Advanced materials


Applied physics letters
Journal: Applied physics letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs nano
Journal: Acs nano


Chemistry of materials
Journal: Chemistry of materials


Nanoscale
Journal: Nanoscale


Acs nano
Journal: Acs nano


Applied physics letters
Journal: Applied physics letters


Aip advances
Journal: Aip advances


Scientific reports
Journal: Scientific reports


Nature communications
Journal: Nature communications


Nano letters
Journal: Nano letters


Nano letters
Journal: Nano letters


Nanotechnology
Journal: Nanotechnology


Advanced functional materials
Journal: Advanced functional materials


Physical review b
Journal: Physical review b


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Nature communications
Journal: Nature communications


Nature communications
Journal: Nature communications


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced functional materials
Journal: Advanced functional materials


Physical review b
Journal: Physical review b


Advanced functional materials
Journal: Advanced functional materials


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Applied physics reviews
Journal: Applied physics reviews


Nature communications
Journal: Nature communications


Nature communications
Journal: Nature communications


Advanced energy materials
Journal: Advanced energy materials


Acs photonics
Journal: Acs photonics


Inorganic chemistry
Journal: Inorganic chemistry


Applied physics letters
Journal: Applied physics letters


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Acs energy letters
Journal: Acs energy letters


Scientific reports
Journal: Scientific reports


Physical review b
Journal: Physical review b


Applied physics letters
Journal: Applied physics letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Physical review b
Journal: Physical review b


Nanotechnology
Journal: Nanotechnology


Advanced materials
Journal: Advanced materials


Physical review x
Journal: Physical review x


Advanced functional materials
Journal: Advanced functional materials


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Langmuir
Journal: Langmuir


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Dalton transactions
Journal: Dalton transactions


Science advances
Journal: Science advances


Acs photonics
Journal: Acs photonics


Acs nano
Journal: Acs nano


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of the american chemical society
Journal: Journal of the american chemical society


Applied physics letters
Journal: Applied physics letters


Acs nano
Journal: Acs nano


Journal of applied physics
Journal: Journal of applied physics


Nano letters
Journal: Nano letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Applied physics letters
Journal: Applied physics letters


Chemistry of materials
Journal: Chemistry of materials


Advanced materials
Journal: Advanced materials


Nanoscale
Journal: Nanoscale


Advanced materials
Journal: Advanced materials


Advanced materials interfaces
Journal: Advanced materials interfaces


Advanced optical materials
Journal: Advanced optical materials


Physical review applied
Journal: Physical review applied


Nanotechnology
Journal: Nanotechnology


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Advanced functional materials
Journal: Advanced functional materials


Scientific reports
Journal: Scientific reports


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Applied physics letters
Journal: Applied physics letters


Physical review b
Journal: Physical review b


Applied physics letters
Journal: Applied physics letters


Acs energy letters
Journal: Acs energy letters


Nature communications
Journal: Nature communications


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs energy letters
Journal: Acs energy letters


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Acs energy letters
Journal: Acs energy letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Physical review b
Journal: Physical review b


Advanced materials
Journal: Advanced materials


Small
Journal: Small


Acs nano
Journal: Acs nano


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Nano energy
Journal: Nano energy


Nano letters
Journal: Nano letters


Small methods
Journal: Small methods


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced electronic materials
Journal: Advanced electronic materials


Applied physics letters
Journal: Applied physics letters


Journal of applied physics
Journal: Journal of applied physics


Applied physics letters
Journal: Applied physics letters


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Nanotechnology
Journal: Nanotechnology


Advanced functional materials
Journal: Advanced functional materials


Nanotechnology
Journal: Nanotechnology


Advanced functional materials
Journal: Advanced functional materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Small
Journal: Small


Electrochimica acta
Journal: Electrochimica acta


Physical review b
Journal: Physical review b


Applied physics letters
Journal: Applied physics letters


Physical review b
Journal: Physical review b


Small
Journal: Small


Advanced energy materials
Journal: Advanced energy materials


Applied physics letters
Journal: Applied physics letters


Scientific reports
Journal: Scientific reports


Nature communications
Journal: Nature communications


Acs nano
Journal: Acs nano


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Advanced functional materials
Journal: Advanced functional materials


Nano energy
Journal: Nano energy


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Physical review letters
Journal: Physical review letters


Physical review b
Journal: Physical review b


Applied physics letters
Journal: Applied physics letters


Nano letters
Journal: Nano letters


Thin solid films
Journal: Thin solid films


Applied physics letters
Journal: Applied physics letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Materials horizons
Journal: Materials horizons


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Advanced functional materials
Journal: Advanced functional materials


Inorganic chemistry
Journal: Inorganic chemistry


Advanced electronic materials
Journal: Advanced electronic materials


Npg asia materials
Journal: Npg asia materials


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Chemistry of materials
Journal: Chemistry of materials


Nano energy
Journal: Nano energy


Journal of luminescence
Journal: Journal of luminescence


Nano energy
Journal: Nano energy


Physical review b
Journal: Physical review b


Applied physics reviews
Journal: Applied physics reviews


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nature
Journal: Nature


Advanced functional materials
Journal: Advanced functional materials


Small
Journal: Small


Advanced optical materials
Journal: Advanced optical materials


Small
Journal: Small


Aip advances
Journal: Aip advances


Inorganic chemistry communications
Journal: Inorganic chemistry communications


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Advanced materials
Journal: Advanced materials


Apl materials
Journal: Apl materials


Nanoscale
Journal: Nanoscale


Journal of applied physics
Journal: Journal of applied physics


Journal of magnetism and magnetic materials 220 (2-3)
Journal: Journal of magnetism and magnetic materials 220 (2-3)


Chemistry of materials
Journal: Chemistry of materials


Carbon
Journal: Carbon


Acs materials letters
Journal: Acs materials letters


Advanced energy materials
Journal: Advanced energy materials


Advanced electronic materials
Journal: Advanced electronic materials


Optics express
Journal: Optics express


Applied physics letters
Journal: Applied physics letters


Carbon
Journal: Carbon


Solar rrl
Journal: Solar rrl


Advanced optical materials
Journal: Advanced optical materials


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Physical review b
Journal: Physical review b


Applied physics letters
Journal: Applied physics letters


Photonics research
Journal: Photonics research


Physical review letters
Journal: Physical review letters


Journal of colloid and interface science
Journal: Journal of colloid and interface science


Acs nano
Journal: Acs nano


Advanced functional materials
Journal: Advanced functional materials


Applied physics letters
Journal: Applied physics letters


Physical review letters
Journal: Physical review letters


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced functional materials
Journal: Advanced functional materials


Advanced materials interfaces
Journal: Advanced materials interfaces


Applied physics letters
Journal: Applied physics letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nano letters
Journal: Nano letters


Nano letters
Journal: Nano letters


Chemical communications
Journal: Chemical communications


Nano letters
Journal: Nano letters


Advanced functional materials
Journal: Advanced functional materials


Small structures
Journal: Small structures


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemical engineering journal
Journal: Chemical engineering journal


Advanced science
Journal: Advanced science


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Acs energy letters
Journal: Acs energy letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of electroceramics
Journal: Journal of electroceramics


Advanced functional materials
Journal: Advanced functional materials


Nano letters
Journal: Nano letters


Scientific reports
Journal: Scientific reports


Aip advances
Journal: Aip advances


Crystal growth &design
Journal: Crystal growth &design


Applied physics letters
Journal: Applied physics letters


Advanced materials
Journal: Advanced materials


Advanced science
Journal: Advanced science


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Advanced energy materials
Journal: Advanced energy materials


Advanced materials interfaces
Journal: Advanced materials interfaces


Small
Journal: Small


Applied physics letters
Journal: Applied physics letters


Advanced functional materials
Journal: Advanced functional materials


Applied physics letters
Journal: Applied physics letters


Acs nano
Journal: Acs nano


Journal of applied physics
Journal: Journal of applied physics


Journal of vacuum science &technology a: vacuum, surfaces, and films 12 (4 …
Journal: Journal of vacuum science &technology a: vacuum


Advanced functional materials
Journal: Advanced functional materials


Optics letters
Journal: Optics letters


Applied physics letters
Journal: Applied physics letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Chemistry of materials
Journal: Chemistry of materials


Crystengcomm
Journal: Crystengcomm


Nanoscale
Journal: Nanoscale


Nanoscale
Journal: Nanoscale


Applied materials today
Journal: Applied materials today


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nano research
Journal: Nano research


Acs applied electronic materials
Journal: Acs applied electronic materials


Applied physics letters
Journal: Applied physics letters


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Critical reviews in solid state and materials sciences
Journal: Critical reviews in solid state and materials sciences


Acs nano
Journal: Acs nano


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Scientific reports
Journal: Scientific reports


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Applied surface science
Journal: Applied surface science


Physical review b
Journal: Physical review b


Photonics research
Journal: Photonics research


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of applied physics
Journal: Journal of applied physics


Journal of mechanical strength
Journal: Journal of mechanical strength


Physical review b
Journal: Physical review b


Journal of materials chemistry
Journal: Journal of materials chemistry


Journal of applied physics
Journal: Journal of applied physics


Nano energy
Journal: Nano energy


Advanced functional materials
Journal: Advanced functional materials


Advanced science
Journal: Advanced science


Acs energy letters
Journal: Acs energy letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Applied physics letters
Journal: Applied physics letters


Superlattices and microstructures
Journal: Superlattices and microstructures


Philosophical magazine letters 87 (3-4)
Journal: Philosophical magazine letters 87 (3-4)


Nano energy
Journal: Nano energy


New journal of physics
Journal: New journal of physics


Applied physics letters
Journal: Applied physics letters


Optics express
Journal: Optics express


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Scientific reports
Journal: Scientific reports


Small
Journal: Small


Interfaces
Journal: Interfaces


Journal of applied physics
Journal: Journal of applied physics


Materials today physics
Journal: Materials today physics


Applied physics letters
Journal: Applied physics letters


Journal of applied physics
Journal: Journal of applied physics


Physical review b
Journal: Physical review b


Advanced optical materials
Journal: Advanced optical materials


Energy &environmental science
Journal: Energy &environmental science


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Aip advances
Journal: Aip advances


Small
Journal: Small


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced functional materials
Journal: Advanced functional materials


Nanoscale research letters
Journal: Nanoscale research letters


Chemical engineering journal
Journal: Chemical engineering journal


Small
Journal: Small


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced optical materials
Journal: Advanced optical materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acta crystallographica section e: crystallographic communications 72 (12 …
Journal: Acta crystallographica section e: crystallographic communications 72 (12 …


Small
Journal: Small


Acs photonics
Journal: Acs photonics


Acs materials letters
Journal: Acs materials letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Applied physics letters
Journal: Applied physics letters


Acs energy letters
Journal: Acs energy letters


Communications materials
Journal: Communications materials


Solar rrl
Journal: Solar rrl


Accounts of materials research
Journal: Accounts of materials research


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Superconductor science and technology
Journal: Superconductor science and technology


Ieee transactions on applied superconductivity
Journal: Ieee transactions on applied superconductivity


Nano-micro letters
Journal: Nano-micro letters


Chemical reviews
Journal: Chemical reviews


Advanced electronic materials
Journal: Advanced electronic materials


Npg asia materials
Journal: Npg asia materials


Small
Journal: Small


Advanced science
Journal: Advanced science


Small
Journal: Small


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced materials
Journal: Advanced materials


The innovation
Journal: The innovation



Advanced energy materials
Journal: Advanced energy materials


Acs photonics
Journal: Acs photonics


Acs applied electronic materials
Journal: Acs applied electronic materials


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Organic photovoltaics iv
Journal: Organic photovoltaics iv


Journal of crystal growth 257 (1-2)
Journal: Journal of crystal growth 257 (1-2)


Acs omega
Journal: Acs omega


Acs applied energy materials
Journal: Acs applied energy materials


Journal of luminescence
Journal: Journal of luminescence


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Applied physics letters
Journal: Applied physics letters


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physica status solidi (b)
Journal: Physica status solidi (b)


Nanoscale
Journal: Nanoscale


Chemistry of materials
Journal: Chemistry of materials


Apl materials
Journal: Apl materials


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Advanced optical materials
Journal: Advanced optical materials


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Acta materialia
Journal: Acta materialia


Nanomaterials
Journal: Nanomaterials


Nanotechnology
Journal: Nanotechnology


Advanced optical materials
Journal: Advanced optical materials


Physical review applied
Journal: Physical review applied


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of optoelectronics and advanced materials
Journal: Journal of optoelectronics and advanced materials


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Chemsuschem
Journal: Chemsuschem


Advanced optical materials
Journal: Advanced optical materials


Acs applied nano materials
Journal: Acs applied nano materials


Nanomaterials
Journal: Nanomaterials


Nano
Journal: Nano


Journal of crystal growth 240 (1-2)
Journal: Journal of crystal growth 240 (1-2)


Advanced materials technologies
Journal: Advanced materials technologies


Resources policy
Journal: Resources policy


Nature energy
Journal: Nature energy


Thin solid films
Journal: Thin solid films


Acs applied energy materials
Journal: Acs applied energy materials


Advanced optical materials
Journal: Advanced optical materials


Advanced optical materials
Journal: Advanced optical materials


Low-dimensional materials and devices 2021
Journal: Low-dimensional materials and devices 2021


Chemistry of materials
Journal: Chemistry of materials


Nanomaterials
Journal: Nanomaterials


Frontiers in materials
Journal: Frontiers in materials


Ecs transactions
Journal: Ecs transactions


Journal of crystal growth
Journal: Journal of crystal growth


Advanced optical materials
Journal: Advanced optical materials


Chemistry of materials
Journal: Chemistry of materials


Solar rrl
Journal: Solar rrl


Applied surface science
Journal: Applied surface science


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Nanoscale
Journal: Nanoscale


Energy technology
Journal: Energy technology


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Solar rrl
Journal: Solar rrl


Advanced functional materials
Journal: Advanced functional materials


Catalysts
Journal: Catalysts


Electrochimica acta
Journal: Electrochimica acta


Nanomaterials
Journal: Nanomaterials


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Solar rrl
Journal: Solar rrl


Acs applied energy materials
Journal: Acs applied energy materials


Nano letters
Journal: Nano letters


Integrated photonics research, silicon and nanophotonics, itu1c.
Journal: Integrated photonics research


Rsc advances
Journal: Rsc advances


Phys. chem. chem. phys
Journal: Phys. chem. chem. phys


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Advanced functional materials
Journal: Advanced functional materials


Verhandlungen der deutschen physikalischen gesellschaft
Journal: Verhandlungen der deutschen physikalischen gesellschaft


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Science
Journal: Science


Nature materials
Journal: Nature materials


Nature photonics
Journal: Nature photonics


Energy &environmental science
Journal: Energy &environmental science


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature communications
Journal: Nature communications


Optics express
Journal: Optics express


Science
Journal: Science


Advanced functional materials
Journal: Advanced functional materials


Nature photonics
Journal: Nature photonics


Nature energy
Journal: Nature energy


Nature energy
Journal: Nature energy


Advanced energy materials
Journal: Advanced energy materials


Energy &environmental science
Journal: Energy &environmental science


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Chem
Journal: Chem


Small
Journal: Small


Nano letters
Journal: Nano letters


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Nature communications
Journal: Nature communications


Accounts of chemical research
Journal: Accounts of chemical research


Nature communications
Journal: Nature communications


Advanced functional materials
Journal: Advanced functional materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs nano
Journal: Acs nano


Carbon
Journal: Carbon


Advanced energy materials
Journal: Advanced energy materials


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Nano letters
Journal: Nano letters


Science bulletin
Journal: Science bulletin


Crystal growth &design
Journal: Crystal growth &design


Macromolecules
Journal: Macromolecules


Nano materials science
Journal: Nano materials science


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Nanotechnology
Journal: Nanotechnology


Solar rrl
Journal: Solar rrl


Advanced functional materials
Journal: Advanced functional materials


Science advances
Journal: Science advances


Advanced materials
Journal: Advanced materials


Energy &environmental science
Journal: Energy &environmental science


Advanced optical materials
Journal: Advanced optical materials


Nanoscale
Journal: Nanoscale


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced materials
Journal: Advanced materials


Energy &environmental materials
Journal: Energy &environmental materials


Physical review b
Journal: Physical review b


Polymer chemistry
Journal: Polymer chemistry


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Advanced energy materials
Journal: Advanced energy materials


Acs nano
Journal: Acs nano


Acs nano
Journal: Acs nano


Advanced functional materials
Journal: Advanced functional materials


Small
Journal: Small


Acs omega
Journal: Acs omega


Applied physics letters
Journal: Applied physics letters


Advanced materials
Journal: Advanced materials


Optics express
Journal: Optics express


Journal of the american chemical society
Journal: Journal of the american chemical society


Small
Journal: Small


Advanced materials
Journal: Advanced materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Nano energy
Journal: Nano energy


Acs nano
Journal: Acs nano


Optics express
Journal: Optics express


Advanced functional materials
Journal: Advanced functional materials


Advanced functional materials
Journal: Advanced functional materials


Nano energy
Journal: Nano energy


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Small
Journal: Small


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Applied physics letters
Journal: Applied physics letters


Nature communications
Journal: Nature communications


Acs materials letters
Journal: Acs materials letters


Small
Journal: Small


Joule
Journal: Joule


Science china materials
Journal: Science china materials


Small
Journal: Small


Advanced optical materials
Journal: Advanced optical materials


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Communications physics
Journal: Communications physics


Applied physics letters
Journal: Applied physics letters


Acta materialia
Journal: Acta materialia


Advanced materials
Journal: Advanced materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Optics express
Journal: Optics express


Nano energy
Journal: Nano energy


Frontiers in chemistry
Journal: Frontiers in chemistry


Small methods
Journal: Small methods


Nanoscale
Journal: Nanoscale


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nano energy
Journal: Nano energy


Applied physics letters
Journal: Applied physics letters


Macromolecular rapid communications
Journal: Macromolecular rapid communications


Applied physics letters
Journal: Applied physics letters


Small
Journal: Small


Materials today physics
Journal: Materials today physics


Photonics research
Journal: Photonics research


Advanced optical materials
Journal: Advanced optical materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Materials today physics
Journal: Materials today physics


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced optical materials
Journal: Advanced optical materials


Solar rrl
Journal: Solar rrl


Advanced materials interfaces
Journal: Advanced materials interfaces


Small
Journal: Small


Nano energy
Journal: Nano energy


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Applied physics letters
Journal: Applied physics letters


Journal of optics a: pure and applied optics
Journal: Journal of optics a: pure and applied optics


Rsc advances
Journal: Rsc advances


Small
Journal: Small


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Plasmonics
Journal: Plasmonics


Solar rrl
Journal: Solar rrl


Thin solid films
Journal: Thin solid films


Applied physics letters
Journal: Applied physics letters


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Advanced functional materials
Journal: Advanced functional materials


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Small
Journal: Small


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Chemnanomat
Journal: Chemnanomat


Small
Journal: Small


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Solar rrl
Journal: Solar rrl


Polymer chemistry
Journal: Polymer chemistry


Small
Journal: Small


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Small methods
Journal: Small methods


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced science
Journal: Advanced science


Nano energy
Journal: Nano energy


Applied surface science
Journal: Applied surface science


Applied mechanics reviews
Journal: Applied mechanics reviews


Nano energy
Journal: Nano energy


Advanced optical materials
Journal: Advanced optical materials


Applied physics letters
Journal: Applied physics letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced optical materials
Journal: Advanced optical materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Light: science &applications
Journal: Light: science &applications


Advanced functional materials
Journal: Advanced functional materials


Small
Journal: Small


Acs nano
Journal: Acs nano


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Nanoscale advances
Journal: Nanoscale advances


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Nanoscale
Journal: Nanoscale


Research on chemical intermediates
Journal: Research on chemical intermediates


Journal of energy chemistry
Journal: Journal of energy chemistry


Frontiers of optoelectronics
Journal: Frontiers of optoelectronics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Npj flexible electronics
Journal: Npj flexible electronics


Chemsuschem
Journal: Chemsuschem


Small
Journal: Small


Chemical engineering journal
Journal: Chemical engineering journal


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Physical review b
Journal: Physical review b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemical engineering journal
Journal: Chemical engineering journal


Solar energy
Journal: Solar energy


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nano energy
Journal: Nano energy


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of materials chemistry c
Journal: Journal of materials chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Advanced optical materials
Journal: Advanced optical materials


Optics express
Journal: Optics express


Energy &environmental materials
Journal: Energy &environmental materials


Nanotechnology
Journal: Nanotechnology


Photonics research
Journal: Photonics research


Nanomaterials
Journal: Nanomaterials


Ccs chemistry
Journal: Ccs chemistry


Nature materials
Journal: Nature materials


Small
Journal: Small


Advanced optical materials
Journal: Advanced optical materials


Chemical communications
Journal: Chemical communications


Small
Journal: Small


Dyes and pigments
Journal: Dyes and pigments


Solar rrl
Journal: Solar rrl


Advanced functional materials
Journal: Advanced functional materials


Optics express
Journal: Optics express


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nanoscale
Journal: Nanoscale


Infomat
Journal: Infomat


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Organic electronics
Journal: Organic electronics


Australian journal of chemistry
Journal: Australian journal of chemistry


Energy &environmental materials
Journal: Energy &environmental materials


Small
Journal: Small


Applied surface science
Journal: Applied surface science


Acs applied electronic materials
Journal: Acs applied electronic materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Nano select
Journal: Nano select


Solar rrl
Journal: Solar rrl


Science china chemistry
Journal: Science china chemistry


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Rsc advances
Journal: Rsc advances


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Small
Journal: Small


Nature communications
Journal: Nature communications


Small
Journal: Small


Advanced optical materials
Journal: Advanced optical materials


Advanced functional materials
Journal: Advanced functional materials


Chinese chemical letters
Journal: Chinese chemical letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of energy chemistry
Journal: Journal of energy chemistry


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Materials today advances
Journal: Materials today advances


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied electronic materials
Journal: Acs applied electronic materials


Journal of applied physics
Journal: Journal of applied physics


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Acta physica sinica
Journal: Acta physica sinica


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced functional materials
Journal: Advanced functional materials


Nature communications
Journal: Nature communications


Advanced optical materials
Journal: Advanced optical materials


Nanomaterials
Journal: Nanomaterials


Chinese journal of chemistry
Journal: Chinese journal of chemistry


Advanced optical materials
Journal: Advanced optical materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced optical materials
Journal: Advanced optical materials


Advanced optical materials
Journal: Advanced optical materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Small
Journal: Small


Advanced energy materials
Journal: Advanced energy materials


Small
Journal: Small


Advanced materials
Journal: Advanced materials


Advanced functional materials
Journal: Advanced functional materials


Applied physics letters
Journal: Applied physics letters


Acs energy letters
Journal: Acs energy letters


Chemical engineering journal
Journal: Chemical engineering journal


Chemistry–a european journal
Journal: Chemistry–a european journal


Acs energy letters
Journal: Acs energy letters


Chemical engineering journal
Journal: Chemical engineering journal


Chemical society reviews
Journal: Chemical society reviews


Advanced science
Journal: Advanced science


Solar rrl
Journal: Solar rrl


Solar rrl
Journal: Solar rrl


Chemical engineering journal
Journal: Chemical engineering journal


Chemistry of materials
Journal: Chemistry of materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced functional materials
Journal: Advanced functional materials


Small structures
Journal: Small structures


Chemical engineering journal
Journal: Chemical engineering journal


Science china chemistry
Journal: Science china chemistry


Npj flexible electronics
Journal: Npj flexible electronics


Perovskite materials and devices
Journal: Perovskite materials and devices


Chemical reviews
Journal: Chemical reviews


Advanced engineering materials
Journal: Advanced engineering materials


Sustainable energy &fuels
Journal: Sustainable energy &fuels


Small
Journal: Small


Small
Journal: Small


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Science china materials

Organic optoelectronics and photonics iii
Journal: Organic optoelectronics and photonics iii


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Verhandlungen der deutschen physikalischen gesellschaft
Journal: Verhandlungen der deutschen physikalischen gesellschaft


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Macromolecular symposia
Journal: Macromolecular symposia


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Journal of physical chemistry b-condensed phase
Journal: Journal of physical chemistry b-condensed phase


Journal of non-crystalline solids
Journal: Journal of non-crystalline solids


Journal of electroanalytical chemistry
Journal: Journal of electroanalytical chemistry


Boletín de la sociedad española de cerámica y vidrio
Journal: Boletín de la sociedad española de cerámica y vidrio


Boletin de la sociedad espanola de ceramica y vidrio
Journal: Boletin de la sociedad espanola de ceramica y vidrio


Boletín de la sociedad española de cerámica y vidrio
Journal: Boletín de la sociedad española de cerámica y vidrio


Am. j. phys
Journal: Am. j. phys


Advanced energy materials
Journal: Advanced energy materials


Energy &environmental science
Journal: Energy &environmental science


Advanced energy materials
Journal: Advanced energy materials


Advanced materials
Journal: Advanced materials


Chemistry of materials
Journal: Chemistry of materials


Science
Journal: Science


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Advanced energy materials
Journal: Advanced energy materials


Energy &environmental science
Journal: Energy &environmental science


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Nano energy
Journal: Nano energy


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced functional materials
Journal: Advanced functional materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Ieee electron device letters
Journal: Ieee electron device letters


Materials science and engineering: r: reports
Journal: Materials science and engineering: r: reports


Energy technology
Journal: Energy technology


Advanced energy materials
Journal: Advanced energy materials


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Optics express
Journal: Optics express


Acs energy letters
Journal: Acs energy letters


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced energy materials
Journal: Advanced energy materials


Advanced functional materials
Journal: Advanced functional materials


Advances in optoelectronics
Journal: Advances in optoelectronics


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Nature
Journal: Nature


Applied physics letters
Journal: Applied physics letters


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Applied physics letters
Journal: Applied physics letters


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Applied physics a
Journal: Applied physics a


Optics express
Journal: Optics express


Journal of applied physics
Journal: Journal of applied physics


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Applied physics letters
Journal: Applied physics letters


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Journal of crystal growth
Journal: Journal of crystal growth


Small
Journal: Small


Advanced energy materials
Journal: Advanced energy materials


Energy procedia
Journal: Energy procedia


Science and technology of advanced materials
Journal: Science and technology of advanced materials


Applied physics letters
Journal: Applied physics letters


Advanced electronic materials
Journal: Advanced electronic materials


Microscopy and microanalysis
Journal: Microscopy and microanalysis


Advanced energy materials
Journal: Advanced energy materials


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Advances in optoelectronics
Journal: Advances in optoelectronics


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Nano energy
Journal: Nano energy


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Chemistry in australia
Journal: Chemistry in australia


Physica status solidi (a)
Journal: Physica status solidi (a)


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Physica status solidi (rrl)–rapid research letters
Journal: Physica status solidi (rrl)–rapid research letters


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Advanced functional materials
Journal: Advanced functional materials


Acs materials letters
Journal: Acs materials letters


Applied physics letters
Journal: Applied physics letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs applied energy materials
Journal: Acs applied energy materials


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Ieee transactions on electron devices
Journal: Ieee transactions on electron devices


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Sustainable energy &fuels
Journal: Sustainable energy &fuels


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Advanced energy materials
Journal: Advanced energy materials


Journal of applied physics
Journal: Journal of applied physics


Journal of micromechanics and microengineering
Journal: Journal of micromechanics and microengineering


Electrochemical and solid-state letters
Journal: Electrochemical and solid-state letters


Journal of crystal growth 154 (1-2)
Journal: Journal of crystal growth 154 (1-2)


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Advanced energy materials
Journal: Advanced energy materials


Solar rrl
Journal: Solar rrl


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Journal of applied physics
Journal: Journal of applied physics


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Journal of crystal growth 241 (1-2)
Journal: Journal of crystal growth 241 (1-2)


Solar rrl
Journal: Solar rrl


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Applied physics letters
Journal: Applied physics letters


Recent developments in crystal growth research
Journal: Recent developments in crystal growth research


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Acs applied energy materials
Journal: Acs applied energy materials


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Energy procedia
Journal: Energy procedia


Energy procedia
Journal: Energy procedia


Energy procedia
Journal: Energy procedia


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Rare metals
Journal: Rare metals


Solar rrl
Journal: Solar rrl


Solar rrl
Journal: Solar rrl


Optical nanostructures and advanced materials for photovoltaics, pth3b.
Journal: Optical nanostructures and advanced materials for photovoltaics


Energy procedia
Journal: Energy procedia


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Energy procedia
Journal: Energy procedia


Current applied physics
Journal: Current applied physics


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Solar rrl
Journal: Solar rrl


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Ann arbor
Journal: Ann arbor


Journal of crystal growth
Journal: Journal of crystal growth


J. cryst. growth
Journal: J. cryst. growth


Applied physics letters
Journal: Applied physics letters


Solar rrl
Journal: Solar rrl


Advanced energy materials
Journal: Advanced energy materials


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Energy procedia
Journal: Energy procedia


Outlook
Journal: Outlook


Nice, france
Journal: Nice


Materials today physics
Journal: Materials today physics


Optical nanostructures and advanced materials for photovoltaics, ptu2c.
Journal: Optical nanostructures and advanced materials for photovoltaics


Organization studies
Journal: Organization studies


Power engineering international
Journal: Power engineering international


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Nature reviews materials
Journal: Nature reviews materials


Advanced science
Journal: Advanced science


Solar rrl
Journal: Solar rrl


Energy &environmental science
Journal: Energy &environmental science


Advanced energy materials
Journal: Advanced energy materials


Organic, hybrid, and perovskite photovoltaics xix
Journal: Organic


Nano energy
Journal: Nano energy


Optical nanostructures and advanced materials for photovoltaics, pth3b.
Journal: Optical nanostructures and advanced materials for photovoltaics


Energy procedia
Journal: Energy procedia


Optics for solar energy, rw4b.
Journal: Optics for solar energy


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Rare metals
Journal: Rare metals


European journal of biochemistry
Journal: European journal of biochemistry


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Chemistry of materials
Journal: Chemistry of materials


Advanced materials
Journal: Advanced materials


Chemical science
Journal: Chemical science


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs nano
Journal: Acs nano


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs nano
Journal: Acs nano


Advanced functional materials
Journal: Advanced functional materials


Advanced functional materials
Journal: Advanced functional materials


Nanotechnology
Journal: Nanotechnology


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemistry of materials
Journal: Chemistry of materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced optical materials
Journal: Advanced optical materials


Advanced functional materials
Journal: Advanced functional materials


Nanotechnology
Journal: Nanotechnology


Nanoscale
Journal: Nanoscale


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced functional materials
Journal: Advanced functional materials


Advanced functional materials
Journal: Advanced functional materials


Angewandte chemie
Journal: Angewandte chemie


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced optical materials
Journal: Advanced optical materials


Nature communications
Journal: Nature communications


Advanced science
Journal: Advanced science


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Nano research
Journal: Nano research


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Advanced optical materials
Journal: Advanced optical materials


Nanoscale
Journal: Nanoscale


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Nano energy
Journal: Nano energy


Advanced materials
Journal: Advanced materials


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Chinese chemical letters
Journal: Chinese chemical letters


Science bulletin
Journal: Science bulletin


Langmuir
Journal: Langmuir


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Crystal growth &design
Journal: Crystal growth &design


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Light: science &applications
Journal: Light: science &applications


Advanced optical materials
Journal: Advanced optical materials


Advanced optical materials
Journal: Advanced optical materials


Advanced functional materials
Journal: Advanced functional materials


Optics express
Journal: Optics express


Nature materials
Journal: Nature materials


Advanced functional materials
Journal: Advanced functional materials


Optics express
Journal: Optics express


Physical review letters
Journal: Physical review letters


Advanced functional materials
Journal: Advanced functional materials


Chemnanomat
Journal: Chemnanomat


Nanotechnology
Journal: Nanotechnology


Advanced materials
Journal: Advanced materials


Nano research
Journal: Nano research


Journal of optics
Journal: Journal of optics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Langmuir
Journal: Langmuir


Acs photonics
Journal: Acs photonics


Nanotechnology
Journal: Nanotechnology


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nanotechnology
Journal: Nanotechnology


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Particle &particle systems characterization
Journal: Particle &particle systems characterization


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Nanoscale
Journal: Nanoscale


中国光学
Journal: 中国光学


Chemphyschem
Journal: Chemphyschem


Nanophotonics
Journal: Nanophotonics


Journal of materials chemistry
Journal: Journal of materials chemistry


Nature photonics
Journal: Nature photonics


Communications physics
Journal: Communications physics


Chinese journal of catalysis
Journal: Chinese journal of catalysis


Biosensors and bioelectronics
Journal: Biosensors and bioelectronics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced optical materials
Journal: Advanced optical materials


Optics express
Journal: Optics express


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Microchimica acta
Journal: Microchimica acta


Cell reports physical science
Journal: Cell reports physical science


Chemistry of materials
Journal: Chemistry of materials


Advanced optical materials
Journal: Advanced optical materials


Advanced materials
Journal: Advanced materials


Science bulletin
Journal: Science bulletin


Rsc advances
Journal: Rsc advances


Journal of materials chemistry
Journal: Journal of materials chemistry


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Iranian biomedical journal
Journal: Iranian biomedical journal


Chinese journal of chemistry
Journal: Chinese journal of chemistry


Advanced optical materials
Journal: Advanced optical materials


Chem
Journal: Chem


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs photonics
Journal: Acs photonics


Physica status solidi (rrl)–rapid research letters
Journal: Physica status solidi (rrl)–rapid research letters


Physica status solidi (rrl)–rapid research letters
Journal: Physica status solidi (rrl)–rapid research letters


Ieee journal of selected topics in quantum electronics
Journal: Ieee journal of selected topics in quantum electronics


Chinese optics
Journal: Chinese optics


Nanoscale
Journal: Nanoscale


Frontiers in chemistry
Journal: Frontiers in chemistry


Advanced optical materials
Journal: Advanced optical materials


Langmuir
Journal: Langmuir


Progress in chemistry
Journal: Progress in chemistry


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Advanced optical materials
Journal: Advanced optical materials


Nano letters
Journal: Nano letters


中国光学
Journal: 中国光学


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nanoscale
Journal: Nanoscale



Journal: Applied physics letters


Journal of applied physics
Journal: Journal of applied physics


Journal of applied physics
Journal: Journal of applied physics


Sensors and actuators: physical
Journal: Sensors and actuators: physical


Scientific reports
Journal: Scientific reports


Journal of applied physics
Journal: Journal of applied physics


Applied physics letters
Journal: Applied physics letters


Nature materials
Journal: Nature materials


Journal of materials science
Journal: Journal of materials science


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Advanced functional materials
Journal: Advanced functional materials


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Journal of applied physics
Journal: Journal of applied physics


Applied physics letters
Journal: Applied physics letters


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Physical review b
Journal: Physical review b


Annales de chimie science des materiaux
Journal: Annales de chimie science des materiaux


Nature communications
Journal: Nature communications


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Journal of applied physics
Journal: Journal of applied physics


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Science
Journal: Science


Journal of applied physics
Journal: Journal of applied physics


Applied physics letters
Journal: Applied physics letters


Ieee transactions on ultrasonics, ferroelectrics, and frequency control 51 …
Journal: Ieee transactions on ultrasonics


Journal of applied physics
Journal: Journal of applied physics


Physical review b
Journal: Physical review b


Applied physics letters
Journal: Applied physics letters


Journal of polymer science part b: polymer physics
Journal: Journal of polymer science part b: polymer physics


Journal of applied physics
Journal: Journal of applied physics


Journal of applied physics
Journal: Journal of applied physics


Journal of applied physics
Journal: Journal of applied physics


Journal of materials science
Journal: Journal of materials science


Physical review letters
Journal: Physical review letters


Physical review b
Journal: Physical review b


Journal of applied physics
Journal: Journal of applied physics


Journal of applied physics
Journal: Journal of applied physics


Physical review b
Journal: Physical review b


Applied physics letters
Journal: Applied physics letters


Journal of the european ceramic society 19 (6-7)
Journal: Journal of the european ceramic society 19 (6-7)


Journal of applied physics
Journal: Journal of applied physics


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Acta materialia
Journal: Acta materialia


Applied physics letters
Journal: Applied physics letters


Journal of applied physics
Journal: Journal of applied physics


Journal of applied physics
Journal: Journal of applied physics


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Materials letters
Journal: Materials letters


Journal of materials research
Journal: Journal of materials research


Applied physics letters
Journal: Applied physics letters


Physical review b
Journal: Physical review b


Journal of applied physics
Journal: Journal of applied physics


Journal of applied physics
Journal: Journal of applied physics


Nature communications
Journal: Nature communications


Acta materialia
Journal: Acta materialia


Journal of applied physics
Journal: Journal of applied physics


Japanese journal of applied physics 50 (5r)
Journal: Japanese journal of applied physics 50 (5r)


Journal of electroceramics
Journal: Journal of electroceramics


Journal of applied physics
Journal: Journal of applied physics


Advanced functional materials
Journal: Advanced functional materials


Applied physics letters
Journal: Applied physics letters


Ferroelectrics
Journal: Ferroelectrics


Journal of applied physics
Journal: Journal of applied physics


Ferroelectrics
Journal: Ferroelectrics


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Sensors and actuators a: physical
Journal: Sensors and actuators a: physical


Applied physics letters
Journal: Applied physics letters


Materials science and engineering: b
Journal: Materials science and engineering: b


Advanced materials
Journal: Advanced materials


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Ferroelectrics
Journal: Ferroelectrics


Journal of materials science
Journal: Journal of materials science


Journal of applied physics
Journal: Journal of applied physics


Nature communications
Journal: Nature communications


Journal of applied physics
Journal: Journal of applied physics


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Advanced functional materials
Journal: Advanced functional materials


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Science
Journal: Science


Japanese journal of applied physics 56 (10s), 10pa
Journal: Japanese journal of applied physics 56 (10s)


Journal of electroceramics
Journal: Journal of electroceramics


Ferroelectrics
Journal: Ferroelectrics


Materials horizons
Journal: Materials horizons


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Ferroelectrics
Journal: Ferroelectrics


Composites part b: engineering
Journal: Composites part b: engineering


Applied physics letters
Journal: Applied physics letters


Journal of applied physics
Journal: Journal of applied physics


Advanced materials
Journal: Advanced materials


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Composites science and technology
Journal: Composites science and technology


Acta materialia 60 (13-14)
Journal: Acta materialia 60 (13-14)


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Ferroelectrics
Journal: Ferroelectrics


Journal of applied physics
Journal: Journal of applied physics


Polymer
Journal: Polymer


Mrs bulletin
Journal: Mrs bulletin


Ferroelectrics
Journal: Ferroelectrics


Ferroelectrics
Journal: Ferroelectrics


Journal of applied physics
Journal: Journal of applied physics


Applied physics letters
Journal: Applied physics letters


Smart materials and structures
Journal: Smart materials and structures


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Applied physics letters
Journal: Applied physics letters


Ferroelectrics letters section
Journal: Ferroelectrics letters section


Physical review materials
Journal: Physical review materials


Applied physics letters
Journal: Applied physics letters


Journal of electroceramics
Journal: Journal of electroceramics


Ieee transactions on ultrasonics, ferroelectrics, and frequency control 38 …
Journal: Ieee transactions on ultrasonics


Applied physics letters
Journal: Applied physics letters


Journal of materials science letters
Journal: Journal of materials science letters


Applied physics letters
Journal: Applied physics letters


G. ye (woodhead, cambridge, 2008)
Journal: G. ye (woodhead


Ieee transactions on ultrasonics, ferroelectrics, and frequency control 52 …
Journal: Ieee transactions on ultrasonics


Materials
Journal: Materials


Journal of applied physics
Journal: Journal of applied physics


Applied optics
Journal: Applied optics


Physical review letters
Journal: Physical review letters


Journal of materials science
Journal: Journal of materials science


Ferroelectrics
Journal: Ferroelectrics


Journal of sol-gel science and technology
Journal: Journal of sol-gel science and technology


Nature
Journal: Nature


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Japanese journal of applied physics 41 (11s)
Journal: Japanese journal of applied physics 41 (11s)


Ferroelectrics
Journal: Ferroelectrics


Boletin-sociedad espanola de ceramica y vidrio
Journal: Boletin-sociedad espanola de ceramica y vidrio


Ferroelectrics
Journal: Ferroelectrics


Ferroelectrics letters section
Journal: Ferroelectrics letters section


Applied physics letters
Journal: Applied physics letters


Journal of applied physics
Journal: Journal of applied physics


Journal of applied crystallography
Journal: Journal of applied crystallography


Japanese journal of applied physics 50 (5r)
Journal: Japanese journal of applied physics 50 (5r)


Ferroelectrics
Journal: Ferroelectrics


Nature communications
Journal: Nature communications


Acta materialia
Journal: Acta materialia


Advanced functional materials
Journal: Advanced functional materials


Crystals
Journal: Crystals


Polymer international
Journal: Polymer international


Journal of polymer science part b: polymer physics
Journal: Journal of polymer science part b: polymer physics


Journal of the european ceramic society 19 (article), xiii-xiv
Journal: Journal of the european ceramic society 19 (article)


Ieee transactions on ultrasonics ferroelectrics and frequency control 33 (lc …
Journal: Ieee transactions on ultrasonics ferroelectrics and frequency control 33 (lc …


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Physical review materials
Journal: Physical review materials


Nano letters
Journal: Nano letters


Ieee transactions on ultrasonics, ferroelectrics, and frequency control 69 …
Journal: Ieee transactions on ultrasonics


Coupled systems mechanics
Journal: Coupled systems mechanics


Polar oxides
Journal: Polar oxides


Boletín de la sociedad española de cerámica y vidrio
Journal: Boletín de la sociedad española de cerámica y vidrio


Boletín de la sociedad española de cerámica y vidrio
Journal: Boletín de la sociedad española de cerámica y vidrio


Nature
Journal: Nature


Nature
Journal: Nature


The journal of chemical physics
Journal: The journal of chemical physics


Nature materials
Journal: Nature materials


Proceedings of the national academy of sciences
Journal: Proceedings of the national academy of sciences


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Physical review letters
Journal: Physical review letters


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Physical review letters
Journal: Physical review letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Physical review b
Journal: Physical review b


Nature materials
Journal: Nature materials


Physical review b
Journal: Physical review b


Physica b: condensed matter
Journal: Physica b: condensed matter


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Solid state communications
Journal: Solid state communications


Physical review letters
Journal: Physical review letters


Science advances
Journal: Science advances


Chemical science
Journal: Chemical science


The journal of chemical physics
Journal: The journal of chemical physics


Ieee transactions on industry applications
Journal: Ieee transactions on industry applications


Acta psychiatrica scandinavica
Journal: Acta psychiatrica scandinavica


Inorganic chemistry
Journal: Inorganic chemistry


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Physical review letters
Journal: Physical review letters


Inorganic chemistry
Journal: Inorganic chemistry


Physical review b
Journal: Physical review b


Physical review letters
Journal: Physical review letters


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Advanced optical materials
Journal: Advanced optical materials


Physical review b
Journal: Physical review b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemical physics letters 430 (1-3)
Journal: Chemical physics letters 430 (1-3)


Physical review b
Journal: Physical review b


Phys. rev. b
Journal: Phys. rev. b


The journal of physical chemistry a
Journal: The journal of physical chemistry a


International journal of quantum chemistry
Journal: International journal of quantum chemistry


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Inorganic chemistry
Journal: Inorganic chemistry


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Adv. quantum chem.
Journal: Adv. quantum chem.


Phys. rev. b
Journal: Phys. rev. b


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Physical review b
Journal: Physical review b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review b
Journal: Physical review b


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Physical review b
Journal: Physical review b


Science advances
Journal: Science advances


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Chemical physics letters 426 (1-3)
Journal: Chemical physics letters 426 (1-3)


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemphyschem
Journal: Chemphyschem


Physical review b
Journal: Physical review b


The journal of chemical physics
Journal: The journal of chemical physics


Chemistry–a european journal
Journal: Chemistry–a european journal


The journal of chemical physics
Journal: The journal of chemical physics


Physical review b
Journal: Physical review b


Ieee transactions on industry applications
Journal: Ieee transactions on industry applications


Physical review letters
Journal: Physical review letters


Physical review b
Journal: Physical review b


Journal of chemical theory and computation
Journal: Journal of chemical theory and computation


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Physical review letters
Journal: Physical review letters


Nanophotonics
Journal: Nanophotonics


Energies
Journal: Energies


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of chemical education
Journal: Journal of chemical education


Inorganic chemistry
Journal: Inorganic chemistry


Physical review b
Journal: Physical review b


Fertility and sterility
Journal: Fertility and sterility


Optical materials express
Journal: Optical materials express


Journal of computational chemistry
Journal: Journal of computational chemistry


Physical review b
Journal: Physical review b


The journal of chemical physics
Journal: The journal of chemical physics


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Dalton transactions
Journal: Dalton transactions


Inorganic chemistry
Journal: Inorganic chemistry


European journal of inorganic chemistry
Journal: European journal of inorganic chemistry


Physical review c
Journal: Physical review c


Physical review a
Journal: Physical review a


J. chem. phys
Journal: J. chem. phys


Physics letters a 248 (2-4)
Journal: Physics letters a 248 (2-4)


Iscience
Journal: Iscience


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Physical review b
Journal: Physical review b


The journal of chemical physics
Journal: The journal of chemical physics


Chemical physics letters 374 (1-2)
Journal: Chemical physics letters 374 (1-2)


Physical review a
Journal: Physical review a


Nature communications
Journal: Nature communications


Chemistry–a european journal
Journal: Chemistry–a european journal


Applied acoustics
Journal: Applied acoustics


Physical review b
Journal: Physical review b


Physical review a
Journal: Physical review a


Physical review a
Journal: Physical review a


Chemical physics
Journal: Chemical physics


Physical review b
Journal: Physical review b


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Physical review b
Journal: Physical review b


Ieee transactions on industry applications
Journal: Ieee transactions on industry applications


Ieee transactions on industry applications
Journal: Ieee transactions on industry applications


Inorganic chemistry
Journal: Inorganic chemistry


Journal of fluorine chemistry
Journal: Journal of fluorine chemistry


Engineering systems design and analysis
Journal: Engineering systems design and analysis


Advanced functional materials
Journal: Advanced functional materials


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


The journal of chemical physics
Journal: The journal of chemical physics


International journal of quantum chemistry
Journal: International journal of quantum chemistry


Chemistry–a european journal
Journal: Chemistry–a european journal


Desalination
Journal: Desalination


Nature communications
Journal: Nature communications


Ieee transactions on industry applications
Journal: Ieee transactions on industry applications


The journal of chemical physics
Journal: The journal of chemical physics


Physical review letters
Journal: Physical review letters


Physical review b
Journal: Physical review b


Ieee transactions on industry applications
Journal: Ieee transactions on industry applications


Mrs advances
Journal: Mrs advances


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Computer physics communications
Journal: Computer physics communications


Physical review b
Journal: Physical review b


Optics express
Journal: Optics express


Nature materials
Journal: Nature materials


Physical review b
Journal: Physical review b


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Journal of physical chemistry
Journal: Journal of physical chemistry


Investigación y ciencia
Journal: Investigación y ciencia


Materiales compuestos
Journal: Materiales compuestos


Dalton transactions
Journal: Dalton transactions


Journal of chemical education
Journal: Journal of chemical education


Chemistry. a european journal
Journal: Chemistry. a european journal


Journal of chemical theory and computation
Journal: Journal of chemical theory and computation


Ieee transactions on industry applications,
Journal: Ieee transactions on industry applications


Ieee transactions on industry applications
Journal: Ieee transactions on industry applications


Automática e instrumentación
Journal: Automática e instrumentación


Ieee transactions on industry applications,
Journal: Ieee transactions on industry applications


Ieee transactions on industry applications,
Journal: Ieee transactions on industry applications


Ieee transactions on industry applications,
Journal: Ieee transactions on industry applications



Journal of the american chemical society
Journal: Journal of the american chemical society


Nature communications
Journal: Nature communications


Energy &environmental science
Journal: Energy &environmental science


Nature communications volume
Journal: Nature communications volume


Joule, doi: 10.1016/j.joule.2017.09.
Journal: Joule


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Energy &environmental science
Journal: Energy &environmental science


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Nature
Journal: Nature


Advanced energy materials, doi: 10.1002/aenm.
Journal: Advanced energy materials


Advanced materials
Journal: Advanced materials


Advanced energy materials, doi: 10.1002/aenm.
Journal: Advanced energy materials


Nano energy
Journal: Nano energy


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Energy &environmental science
Journal: Energy &environmental science


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced energy materials 6 (doi: 10.1002/aenm.201501868)
Journal: Advanced energy materials 6 (doi: 10.1002/aenm.201501868)


Energy &environmental science
Journal: Energy &environmental science


Energy &environmental science
Journal: Energy &environmental science


Acs energy letters
Journal: Acs energy letters


Chemistry–a european journal
Journal: Chemistry–a european journal


Advanced energy materials
Journal: Advanced energy materials


Advanced energy materials, doi: 10.1002/aenm.
Journal: Advanced energy materials


Nature communications
Journal: Nature communications


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced energy materials
Journal: Advanced energy materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced materials
Journal: Advanced materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced energy materials
Journal: Advanced energy materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Joule
Journal: Joule


Advanced energy materials
Journal: Advanced energy materials


Dalton transactions
Journal: Dalton transactions


Advanced energy materials
Journal: Advanced energy materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Energy &environmental science
Journal: Energy &environmental science


Acs nano
Journal: Acs nano


Acs energy letters
Journal: Acs energy letters


Chemical science
Journal: Chemical science


Chemical communications
Journal: Chemical communications


Advanced materials
Journal: Advanced materials


Advanced energy materials
Journal: Advanced energy materials


Energy &environmental science
Journal: Energy &environmental science


Journal of power sources
Journal: Journal of power sources


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Materials advances
Journal: Materials advances


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Chemsuschem
Journal: Chemsuschem


Journal of fluorine chemistry
Journal: Journal of fluorine chemistry


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Sci
Journal: Sci


Advanced energy materials
Journal: Advanced energy materials


Advanced energy materials
Journal: Advanced energy materials


Energy &environmental science
Journal: Energy &environmental science


Advanced energy materials
Journal: Advanced energy materials


Nature energy
Journal: Nature energy


Advanced energy materials
Journal: Advanced energy materials


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Energy &environmental science
Journal: Energy &environmental science


Acs energy letters
Journal: Acs energy letters


Energy &environmental science
Journal: Energy &environmental science


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced energy materials
Journal: Advanced energy materials


Acs energy letters
Journal: Acs energy letters


Advanced energy materials
Journal: Advanced energy materials


Advanced materials
Journal: Advanced materials


Advanced materials interfaces
Journal: Advanced materials interfaces


Acs energy letters
Journal: Acs energy letters


Energy &environmental science
Journal: Energy &environmental science


Nano energy
Journal: Nano energy


Chemsuschem, doi: 10.1002/cssc.
Journal: Chemsuschem


Organic electronics
Journal: Organic electronics


Advanced energy materials
Journal: Advanced energy materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Small
Journal: Small


Sci. adv
Journal: Sci. adv


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Acs applied nano materials
Journal: Acs applied nano materials


Crystal growth &design
Journal: Crystal growth &design


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs nano
Journal: Acs nano


Advanced energy materials
Journal: Advanced energy materials


Journal of power sources
Journal: Journal of power sources


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Materials chemistry and physics
Journal: Materials chemistry and physics


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Solar rrl
Journal: Solar rrl


Optical materials express
Journal: Optical materials express


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Advanced engineering materials
Journal: Advanced engineering materials


Angewandte chemie
Journal: Angewandte chemie


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced materials interfaces
Journal: Advanced materials interfaces


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Acs energy letters
Journal: Acs energy letters


The journal of chemical physics
Journal: The journal of chemical physics


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Chemical communications
Journal: Chemical communications


International journal of hydrogen energy
Journal: International journal of hydrogen energy


Chemistry of materials
Journal: Chemistry of materials


Sustainable energy &fuels
Journal: Sustainable energy &fuels


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Solar rrl
Journal: Solar rrl


Soft matter
Journal: Soft matter


Energy &environmental science
Journal: Energy &environmental science


Journal of physics: energy
Journal: Journal of physics: energy


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Nanoscale
Journal: Nanoscale


Solar rrl
Journal: Solar rrl


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Chempluschem
Journal: Chempluschem


Journal of power sources
Journal: Journal of power sources


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Chemistry–a european journal
Journal: Chemistry–a european journal


Chemsuschem
Journal: Chemsuschem


Acs materials letters
Journal: Acs materials letters


Advanced optical materials
Journal: Advanced optical materials


Chemistry–a european journal
Journal: Chemistry–a european journal


Joule
Journal: Joule


Crystals
Journal: Crystals


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Chemistry of materials
Journal: Chemistry of materials


Acs energy letters
Journal: Acs energy letters


Angewandte chemie
Journal: Angewandte chemie


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced energy materials
Journal: Advanced energy materials


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Crystal growth &design
Journal: Crystal growth &design


Energy technology
Journal: Energy technology


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Materials advances
Journal: Materials advances


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Phys. chem. chem. phys
Journal: Phys. chem. chem. phys


Acs nano
Journal: Acs nano


Physica status solidi (rrl)–rapid research letters
Journal: Physica status solidi (rrl)–rapid research letters


Frontiers in electronics
Journal: Frontiers in electronics


Emerging photovoltaic materials
Journal: Emerging photovoltaic materials


Science
Journal: Science


Advanced energy materials
Journal: Advanced energy materials


Communications materials
Journal: Communications materials


Acs energy letters
Journal: Acs energy letters


Acs applied energy materials
Journal: Acs applied energy materials


Energy technology
Journal: Energy technology


Chemistry–a european journal
Journal: Chemistry–a european journal


Materials advances
Journal: Materials advances


Angewandte chemie
Journal: Angewandte chemie


Advanced optical materials
Journal: Advanced optical materials


Advanced optical materials
Journal: Advanced optical materials


Chemistry–a european journal
Journal: Chemistry–a european journal


Angew. chem. int. ed
Journal: Angew. chem. int. ed


Acs nano
Journal: Acs nano


J. mater. chem
Journal: J. mater. chem


Science
Journal: Science


Science
Journal: Science


Environmental science
Journal: Environmental science


Technologies
Journal: Technologies


Dalton trans
Journal: Dalton trans


Acta crystallographica
Journal: Acta crystallographica


Acta crystallographica
Journal: Acta crystallographica


Science
Journal: Science


Nature nanotechnology
Journal: Nature nanotechnology


Science
Journal: Science


Nature nanotechnology
Journal: Nature nanotechnology


Nature
Journal: Nature


Nature communications
Journal: Nature communications


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


Nature materials
Journal: Nature materials


Nature materials
Journal: Nature materials


Nature
Journal: Nature


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Nature
Journal: Nature


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nature energy
Journal: Nature energy


Nature nanotechnology
Journal: Nature nanotechnology


Nature materials
Journal: Nature materials


Nature chemistry
Journal: Nature chemistry


Nature photonics
Journal: Nature photonics


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


Nature energy
Journal: Nature energy


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced functional materials
Journal: Advanced functional materials


Joule
Journal: Joule


Nature
Journal: Nature


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Acs catalysis
Journal: Acs catalysis


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature photonics
Journal: Nature photonics


Nature communications
Journal: Nature communications


Nature nanotechnology
Journal: Nature nanotechnology


Nature photonics
Journal: Nature photonics


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature catalysis
Journal: Nature catalysis


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


Nature photonics
Journal: Nature photonics


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Nature
Journal: Nature


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs nano
Journal: Acs nano


Nature communications
Journal: Nature communications


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Physical review letters
Journal: Physical review letters


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced materials
Journal: Advanced materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


Nature communications
Journal: Nature communications


Nature photonics
Journal: Nature photonics


Advanced materials
Journal: Advanced materials


Nature reviews materials
Journal: Nature reviews materials


Nature communications
Journal: Nature communications


Joule
Journal: Joule


Nature materials
Journal: Nature materials


Physical review b
Journal: Physical review b


Acs nano
Journal: Acs nano


Nature energy
Journal: Nature energy


Acs energy letters
Journal: Acs energy letters


Advanced materials
Journal: Advanced materials


Physical review letters
Journal: Physical review letters


Science advances
Journal: Science advances


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Joule
Journal: Joule


Acs nano
Journal: Acs nano


Physical review b
Journal: Physical review b


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Physical review b
Journal: Physical review b


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


Nano energy
Journal: Nano energy


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Frontiers of physics
Journal: Frontiers of physics


Langmuir
Journal: Langmuir


Nature communications
Journal: Nature communications


Applied physics letters
Journal: Applied physics letters


Small
Journal: Small


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Nano letters
Journal: Nano letters


Nature communications
Journal: Nature communications


Applied surface science
Journal: Applied surface science


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature communications
Journal: Nature communications


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nano letters
Journal: Nano letters


Acs energy letters
Journal: Acs energy letters


Acs nano
Journal: Acs nano


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


Langmuir
Journal: Langmuir


Nature communications
Journal: Nature communications


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


Nano letters
Journal: Nano letters


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs photonics
Journal: Acs photonics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced materials
Journal: Advanced materials


Matter
Journal: Matter


Physical review b
Journal: Physical review b


Scientific reports
Journal: Scientific reports


Advanced energy materials
Journal: Advanced energy materials


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


The journal of chemical physics
Journal: The journal of chemical physics


Advanced materials
Journal: Advanced materials


Chemistry of materials
Journal: Chemistry of materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of laser micro/nanoengineering
Journal: Journal of laser micro/nanoengineering


Nature communications
Journal: Nature communications


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced optical materials
Journal: Advanced optical materials


Advanced functional materials
Journal: Advanced functional materials


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs materials letters
Journal: Acs materials letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of the american chemical society
Journal: Journal of the american chemical society


Nano energy
Journal: Nano energy


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Acs nano
Journal: Acs nano


Nature materials
Journal: Nature materials


Communications materials
Journal: Communications materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs energy letters
Journal: Acs energy letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Chem
Journal: Chem


Joule
Journal: Joule


Chemistry squared
Journal: Chemistry squared


Acs materials letters
Journal: Acs materials letters


Rare metals
Journal: Rare metals


Acs materials letters
Journal: Acs materials letters


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Jlmn-journal of laser micro/nanoengineering
Journal: Jlmn-journal of laser micro/nanoengineering


Advanced materials
Journal: Advanced materials


Advanced optical materials
Journal: Advanced optical materials


Journal of electroanalytical chemistry
Journal: Journal of electroanalytical chemistry


Acs central science

Optics for solar energy, st2a.
Journal: Optics for solar energy


Optics for solar energy, st2a.
Journal: Optics for solar energy


Journal of applied physics
Journal: Journal of applied physics


Energie, macht, vernunft
Journal: Energie


Science
Journal: Science


Science
Journal: Science


Nature materials
Journal: Nature materials


Chemical reviews
Journal: Chemical reviews


Nano letters
Journal: Nano letters


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Science advances
Journal: Science advances


Nature photonics
Journal: Nature photonics


Nature energy
Journal: Nature energy


Nature energy
Journal: Nature energy


Nano letters
Journal: Nano letters


Science
Journal: Science


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature materials
Journal: Nature materials


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Energy &environmental science
Journal: Energy &environmental science


Acs nano
Journal: Acs nano


Nano letters
Journal: Nano letters


Accounts of chemical research
Journal: Accounts of chemical research


Journal of the american chemical society
Journal: Journal of the american chemical society


Nano letters
Journal: Nano letters


Materials today
Journal: Materials today


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nano letters
Journal: Nano letters


Nano letters
Journal: Nano letters


Joule
Journal: Joule


Acs nano
Journal: Acs nano


Nature communications
Journal: Nature communications


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs energy letters
Journal: Acs energy letters


Scientific reports
Journal: Scientific reports


Nano letters
Journal: Nano letters


Nature nanotechnology
Journal: Nature nanotechnology


Nature communications
Journal: Nature communications


Chemical science
Journal: Chemical science


Advanced energy materials
Journal: Advanced energy materials


Nano letters
Journal: Nano letters


Energy &environmental science
Journal: Energy &environmental science


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Nano letters
Journal: Nano letters


Science
Journal: Science


Advanced energy materials
Journal: Advanced energy materials


Nano letters
Journal: Nano letters


Joule
Journal: Joule


Joule
Journal: Joule


Nature communications
Journal: Nature communications


Acs nano
Journal: Acs nano


Acs nano
Journal: Acs nano


Acs energy letters
Journal: Acs energy letters


Chemical communications
Journal: Chemical communications


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs energy letters
Journal: Acs energy letters


Energy &environmental science
Journal: Energy &environmental science


Acs nano
Journal: Acs nano


Chemistry of materials
Journal: Chemistry of materials


Solid state communications
Journal: Solid state communications


Acs nano
Journal: Acs nano


Chemistry of materials
Journal: Chemistry of materials


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs energy letters
Journal: Acs energy letters


Nano letters
Journal: Nano letters


Journal of crystal growth
Journal: Journal of crystal growth


Acs nano
Journal: Acs nano


Nanotechnology
Journal: Nanotechnology


Nature sustainability
Journal: Nature sustainability


Nano letters
Journal: Nano letters


Nano letters
Journal: Nano letters


Physical review b
Journal: Physical review b


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


Energy &environmental science
Journal: Energy &environmental science


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Acs nano
Journal: Acs nano


Applied physics letters
Journal: Applied physics letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nano letters
Journal: Nano letters


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Philosophical transactions of the royal society a: mathematical, physical …
Journal: Philosophical transactions of the royal society a: mathematical


Energy &environmental science
Journal: Energy &environmental science


Nano letters
Journal: Nano letters


Advanced energy materials
Journal: Advanced energy materials


Advanced energy materials
Journal: Advanced energy materials


Acs energy letters
Journal: Acs energy letters


Nanotechnology
Journal: Nanotechnology


Acs energy letters
Journal: Acs energy letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Energy &environmental science
Journal: Energy &environmental science


Journal of the american chemical society
Journal: Journal of the american chemical society


Chemical reviews
Journal: Chemical reviews


Acs energy letters
Journal: Acs energy letters


Science
Journal: Science


Acs energy letters
Journal: Acs energy letters


Physical review b
Journal: Physical review b


Science advances
Journal: Science advances


Advanced materials
Journal: Advanced materials


Nature photonics
Journal: Nature photonics


Nano energy
Journal: Nano energy


Advanced energy materials
Journal: Advanced energy materials


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs energy letters
Journal: Acs energy letters


Advanced optical materials
Journal: Advanced optical materials


Acs photonics
Journal: Acs photonics


Nature
Journal: Nature


Chemistry of materials
Journal: Chemistry of materials


Nature photonics
Journal: Nature photonics


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


Acs materials letters
Journal: Acs materials letters


Advanced functional materials
Journal: Advanced functional materials


Joule
Journal: Joule


Chemical engineering journal
Journal: Chemical engineering journal


Solar energy
Journal: Solar energy


Joule
Journal: Joule


Acs nano
Journal: Acs nano


Acs energy letters
Journal: Acs energy letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Joule
Journal: Joule


Cell reports physical science
Journal: Cell reports physical science


Nano lett
Journal: Nano lett


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Applied physics letters
Journal: Applied physics letters


Advanced materials
Journal: Advanced materials


Nature
Journal: Nature


Science
Journal: Science


Nature energy
Journal: Nature energy


Chemistry-a european journal
Journal: Chemistry-a european journal


Frontiers in optics, sm
Journal: Frontiers in optics


Journal of power sources
Journal: Journal of power sources


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs energy letters
Journal: Acs energy letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journées nationales du photovoltaïque, jnpv
Journal: Journées nationales du photovoltaïque


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Acs nano
Journal: Acs nano


Nano letters (print)
Journal: Nano letters (print)


Physical review letters
Journal: Physical review letters


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Angewandte chemie
Journal: Angewandte chemie


Physical review b
Journal: Physical review b


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Powder metallurgy
Journal: Powder metallurgy


Journal of materials processing technology
Journal: Journal of materials processing technology


Materials science and engineering: a
Journal: Materials science and engineering: a


Materials research bulletin
Journal: Materials research bulletin


International journal of hydrogen energy
Journal: International journal of hydrogen energy


Journal of materials chemistry
Journal: Journal of materials chemistry


Electrochimica acta
Journal: Electrochimica acta


Journal of the european ceramic society 27 (13-15)
Journal: Journal of the european ceramic society 27 (13-15)


Chemistry of materials
Journal: Chemistry of materials


Materials science and engineering: a
Journal: Materials science and engineering: a


Journal of materials processing technology 175 (1-3)
Journal: Journal of materials processing technology 175 (1-3)


Renewable energy
Journal: Renewable energy


Chemistry of materials
Journal: Chemistry of materials


Metallurgical and materials transactions a
Journal: Metallurgical and materials transactions a


Journal of solid state chemistry 177 (4-5)
Journal: Journal of solid state chemistry 177 (4-5)


Chemistry of materials
Journal: Chemistry of materials


Journal of power sources
Journal: Journal of power sources


Journal of membrane science
Journal: Journal of membrane science


International journal of hydrogen energy
Journal: International journal of hydrogen energy


Journal of materials chemistry
Journal: Journal of materials chemistry


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Journal of non-crystalline solids
Journal: Journal of non-crystalline solids


Ceramics international
Journal: Ceramics international


Journal of non-crystalline solids
Journal: Journal of non-crystalline solids


International journal of applied ceramic technology
Journal: International journal of applied ceramic technology


Materials letters
Journal: Materials letters


Polymer testing
Journal: Polymer testing


Electrochimica acta
Journal: Electrochimica acta


Physical review b
Journal: Physical review b


Journal of materials chemistry
Journal: Journal of materials chemistry


Journal of materials processing technology
Journal: Journal of materials processing technology


Journal of power sources
Journal: Journal of power sources


Journal of power sources
Journal: Journal of power sources


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of materials processing technology
Journal: Journal of materials processing technology


Journal of materials processing technology
Journal: Journal of materials processing technology


Archives of materials science and engineering
Journal: Archives of materials science and engineering


Journal of the chemical society, dalton transactions
Journal: Journal of the chemical society


Journal of achievements in materials and manufacturing engineering 27 (2 …
Journal: Journal of achievements in materials and manufacturing engineering 27 (2 …


European polymer journal
Journal: European polymer journal


Powder technology
Journal: Powder technology


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Journal of materials processing technology 119 (1-3)
Journal: Journal of materials processing technology 119 (1-3)


Solid state communications
Journal: Solid state communications


Rsc advances
Journal: Rsc advances


International journal of applied ceramic technology
Journal: International journal of applied ceramic technology


Journal of materials chemistry
Journal: Journal of materials chemistry


Electrochimica acta
Journal: Electrochimica acta


Solid state ionics
Journal: Solid state ionics


Journal of achievements in materials and manufacturing engineering
Journal: Journal of achievements in materials and manufacturing engineering


Powder metallurgy
Journal: Powder metallurgy


Dalton transactions
Journal: Dalton transactions


Ceramics international
Journal: Ceramics international


Materials characterization
Journal: Materials characterization


Journal of materials processing technology
Journal: Journal of materials processing technology


Journal of power sources
Journal: Journal of power sources


Journal of polymer science part a: polymer chemistry
Journal: Journal of polymer science part a: polymer chemistry


Journal of materials science
Journal: Journal of materials science


Journal of non-crystalline solids 305 (1-3)
Journal: Journal of non-crystalline solids 305 (1-3)


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Inorganic chemistry
Journal: Inorganic chemistry


Journal of materials processing technology
Journal: Journal of materials processing technology


Inorganic chemistry
Journal: Inorganic chemistry


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Electrochimica acta
Journal: Electrochimica acta


International journal of powder metallurgy
Journal: International journal of powder metallurgy


Materials letters
Journal: Materials letters


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Journal of achievements in materials and manufacturing engineering
Journal: Journal of achievements in materials and manufacturing engineering


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Ceramics international
Journal: Ceramics international


Journal of luminescence
Journal: Journal of luminescence


Powder metallurgy
Journal: Powder metallurgy


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Ceramics international
Journal: Ceramics international


Fuel cells
Journal: Fuel cells


Powder metallurgy
Journal: Powder metallurgy


Journal of materials science
Journal: Journal of materials science


Polymer
Journal: Polymer


Journal of materials research and technology
Journal: Journal of materials research and technology


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Advanced powder technology
Journal: Advanced powder technology


Dalton transactions
Journal: Dalton transactions


Solid state ionics
Journal: Solid state ionics


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Molecules
Journal: Molecules


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Powder metallurgy
Journal: Powder metallurgy


Polymers
Journal: Polymers


Electrochimica acta
Journal: Electrochimica acta


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Solid state ionics
Journal: Solid state ionics


Electrochimica acta
Journal: Electrochimica acta


Polymers
Journal: Polymers


Acta astronautica
Journal: Acta astronautica


Chemelectrochem
Journal: Chemelectrochem


Nanomaterials
Journal: Nanomaterials


International journal of engineering research &science
Journal: International journal of engineering research &science


Boletín de la sociedad española de cerámica y vidrio
Journal: Boletín de la sociedad española de cerámica y vidrio


Chemistry of materials
Journal: Chemistry of materials


Inorganic chemistry
Journal: Inorganic chemistry


Archives of materials science and engineering
Journal: Archives of materials science and engineering


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Hemijska industrija
Journal: Hemijska industrija


Boletín de la sociedad española de cerámica y vidrio
Journal: Boletín de la sociedad española de cerámica y vidrio


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Manufacturing engineering
Journal: Manufacturing engineering


Tecnología y desarrollo
Journal: Tecnología y desarrollo


Inżynieria materiałowa
Journal: Inżynieria materiałowa


Solid state ionics ii: volume 210
Journal: Solid state ionics ii: volume 210


Journal of power sources
Journal: Journal of power sources


Polymers
Journal: Polymers


Batteries &supercaps
Journal: Batteries &supercaps


Évolution
Journal: Évolution


Journal of materials chemistry
Journal: Journal of materials chemistry


Powder metallurgy
Journal: Powder metallurgy


Archives of materials science and engineering
Journal: Archives of materials science and engineering


Fuel cells (online)
Journal: Fuel cells (online)


Solid state ionics
Journal: Solid state ionics


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Ciencia uanl
Journal: Ciencia uanl


Inzynieria materialowa
Journal: Inzynieria materialowa


Ciencia uanl
Journal: Ciencia uanl


Ciencia uanl
Journal: Ciencia uanl


Boletin de la sociedad espanola de ceramica y vidrio
Journal: Boletin de la sociedad espanola de ceramica y vidrio


Boletín de la sociedad española de cerámica y vidrio
Journal: Boletín de la sociedad española de cerámica y vidrio


Boletin-sociedad espanola de ceramica y vidrio
Journal: Boletin-sociedad espanola de ceramica y vidrio


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Boletin-sociedad espanola de ceramica y vidrio
Journal: Boletin-sociedad espanola de ceramica y vidrio


Physica c: superconductivity
Journal: Physica c: superconductivity


Solid state ionics
Journal: Solid state ionics


Boletín de la sociedad española de cerámica y vidrio
Journal: Boletín de la sociedad española de cerámica y vidrio


Solid state ionics
Journal: Solid state ionics


Nature materials
Journal: Nature materials


Nano letters
Journal: Nano letters


Journal of materials research
Journal: Journal of materials research


Applied physics letters
Journal: Applied physics letters


Nano letters
Journal: Nano letters


Nano letters
Journal: Nano letters


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Journal of applied physics
Journal: Journal of applied physics


Journal of materials research
Journal: Journal of materials research


Nano letters
Journal: Nano letters


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Advanced energy materials
Journal: Advanced energy materials


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Applied physics letters
Journal: Applied physics letters


Advanced materials
Journal: Advanced materials


Applied physics letters
Journal: Applied physics letters


Advanced electronic materials
Journal: Advanced electronic materials


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Nano letters
Journal: Nano letters



Journal: Journal of materials chemistry c


Beilstein journal of nanotechnology
Journal: Beilstein journal of nanotechnology


Physica status solidi (a)
Journal: Physica status solidi (a)


Journal of modern optics 49 (14-15)
Journal: Journal of modern optics 49 (14-15)


Physica status solidi (a)
Journal: Physica status solidi (a)


Rsc advances
Journal: Rsc advances


Energy &environmental science
Journal: Energy &environmental science


Nature
Journal: Nature


Mrs advances
Journal: Mrs advances


Chemistry–a european journal
Journal: Chemistry–a european journal


Physica status solidi (b)
Journal: Physica status solidi (b)


Comptes rendus de l'académie des sciences-series iv-physics
Journal: Comptes rendus de l'académie des sciences-series iv-physics


Advanced optical materials
Journal: Advanced optical materials


Physica status solidi (b)
Journal: Physica status solidi (b)


Nature
Journal: Nature


Acs nano
Journal: Acs nano


Cell reports physical science
Journal: Cell reports physical science


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


European journal of physics
Journal: European journal of physics


Journal of materials chemistry c
Journal: Journal of materials chemistry c


J. mater. chem
Journal: J. mater. chem


Psst
Journal: Psst


Nature
Journal: Nature


Nanofibers–production, properties and functional applications
Journal: Nanofibers–production


Physical review letters
Journal: Physical review letters


Physical review letters
Journal: Physical review letters


Physical review letters
Journal: Physical review letters


Frontiers in optics, wv
Journal: Frontiers in optics


Physica status solidi-a-applied research
Journal: Physica status solidi-a-applied research


Comptes rendus de l'academie des sciences series iv physics
Journal: Comptes rendus de l'academie des sciences series iv physics


Physica status solidi (b)
Journal: Physica status solidi (b)


Physica status solidi (b)
Journal: Physica status solidi (b)


Physica status solidi (a)
Journal: Physica status solidi (a)


Physica status solidi-b-basic research
Journal: Physica status solidi-b-basic research


Physica status solidi-a-applied research
Journal: Physica status solidi-a-applied research


Physica status solidi-b-basic research
Journal: Physica status solidi-b-basic research


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Physica status solidi-a-applied research
Journal: Physica status solidi-a-applied research


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Applied magnetic resonance
Journal: Applied magnetic resonance


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


The journal of chemical physics
Journal: The journal of chemical physics


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


The journal of physical chemistry a
Journal: The journal of physical chemistry a


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


International journal of quantum chemistry
Journal: International journal of quantum chemistry


Physical review b
Journal: Physical review b


The journal of chemical physics
Journal: The journal of chemical physics


Physical review b
Journal: Physical review b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review b
Journal: Physical review b


Solid state communications
Journal: Solid state communications


Solid state communications
Journal: Solid state communications


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Physica status solidi (b)
Journal: Physica status solidi (b)


Inorganic chemistry
Journal: Inorganic chemistry


Solid state communications
Journal: Solid state communications


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review letters
Journal: Physical review letters


Chemical physics letters 385 (3-4)
Journal: Chemical physics letters 385 (3-4)


Physical review letters
Journal: Physical review letters


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Physical review b
Journal: Physical review b


Chemical physics letters
Journal: Chemical physics letters


The journal of chemical physics
Journal: The journal of chemical physics


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Physical review b
Journal: Physical review b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review b
Journal: Physical review b


Chemical physics letters 430 (1-3)
Journal: Chemical physics letters 430 (1-3)


Physical review b
Journal: Physical review b


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Physical review b
Journal: Physical review b


The journal of chemical physics
Journal: The journal of chemical physics


Inorganic chemistry
Journal: Inorganic chemistry


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Adv. quantum chem.
Journal: Adv. quantum chem.


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Chemical physics
Journal: Chemical physics


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Physical review b
Journal: Physical review b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review b
Journal: Physical review b


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Physical review b
Journal: Physical review b


Chemical physics letters 426 (1-3)
Journal: Chemical physics letters 426 (1-3)


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemphyschem
Journal: Chemphyschem


Physical review b
Journal: Physical review b


The journal of chemical physics
Journal: The journal of chemical physics


Physical review b
Journal: Physical review b


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Physical review b
Journal: Physical review b


International journal of quantum chemistry
Journal: International journal of quantum chemistry


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal de chimie physique
Journal: Journal de chimie physique


Solid state communications
Journal: Solid state communications


Physics letters a
Journal: Physics letters a


Journal of chemical theory and computation
Journal: Journal of chemical theory and computation


Journal of molecular structure: theochem 537 (1-3)
Journal: Journal of molecular structure: theochem 537 (1-3)


Physical review b
Journal: Physical review b


Inorganic chemistry
Journal: Inorganic chemistry


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


High pressure research
Journal: High pressure research


Physical review b
Journal: Physical review b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of chemical education
Journal: Journal of chemical education


Inorganic chemistry
Journal: Inorganic chemistry


Physical review b
Journal: Physical review b


International journal of quantum chemistry
Journal: International journal of quantum chemistry


Journal of physics c: solid state physics
Journal: Journal of physics c: solid state physics


Physical review b
Journal: Physical review b


The journal of chemical physics
Journal: The journal of chemical physics


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Physical review b
Journal: Physical review b


Theoretical chemistry accounts
Journal: Theoretical chemistry accounts


Medicina intensiva
Journal: Medicina intensiva


Journal of molecular structure: theochem 759 (1-3)
Journal: Journal of molecular structure: theochem 759 (1-3)


International journal of quantum chemistry
Journal: International journal of quantum chemistry


Inorganic chemistry
Journal: Inorganic chemistry


Chemical physics letters 473 (1-3)
Journal: Chemical physics letters 473 (1-3)


Chemical physics letters 374 (1-2)
Journal: Chemical physics letters 374 (1-2)


Chemical physics letters
Journal: Chemical physics letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


International journal of quantum chemistry
Journal: International journal of quantum chemistry


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


International journal of quantum chemistry
Journal: International journal of quantum chemistry


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Physical review b
Journal: Physical review b


Chemical physics letters 374 (1-2)
Journal: Chemical physics letters 374 (1-2)


Chemistry–a european journal
Journal: Chemistry–a european journal


Physical review b
Journal: Physical review b


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Chemical physics
Journal: Chemical physics


Physical review b
Journal: Physical review b


Applied magnetic resonance
Journal: Applied magnetic resonance


Physical review b
Journal: Physical review b


Solid state communications
Journal: Solid state communications


Inorganic chemistry
Journal: Inorganic chemistry


Inorganic chemistry
Journal: Inorganic chemistry


Journal of fluorine chemistry
Journal: Journal of fluorine chemistry


Journal of molecular structure. theochem
Journal: Journal of molecular structure. theochem


Journal de chimie physique
Journal: Journal de chimie physique


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Journal of physics and chemistry of solids
Journal: Journal of physics and chemistry of solids


International journal of quantum chemistry
Journal: International journal of quantum chemistry


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Chemistry–a european journal
Journal: Chemistry–a european journal


The journal of chemical physics
Journal: The journal of chemical physics


Recent advances in density functional methods
Journal: Recent advances in density functional methods


Physical review b
Journal: Physical review b


Studies
Journal: Studies


Studies in physical and theoretical chemistry
Journal: Studies in physical and theoretical chemistry


Journal of physics c: solid state physics
Journal: Journal of physics c: solid state physics


Chemistry–a european journal
Journal: Chemistry–a european journal


Journal of physical chemistry
Journal: Journal of physical chemistry


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Physical review b
Journal: Physical review b


International journal of quantum chemistry
Journal: International journal of quantum chemistry


Lecture series on computer and computational sciences
Journal: Lecture series on computer and computational sciences


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Physica status solidi (c)
Journal: Physica status solidi (c)


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


International journal of quantum chemistry
Journal: International journal of quantum chemistry


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Journal of chemical physics
Journal: Journal of chemical physics


Journal of molecular structure: theochem 330 (1-3)
Journal: Journal of molecular structure: theochem 330 (1-3)


New journal of chemistry (1987)
Journal: New journal of chemistry (1987)


Radiation effects and defects in solids
Journal: Radiation effects and defects in solids


Sol. st. commun.
Journal: Sol. st. commun.


Physical review b
Journal: Physical review b


Nature
Journal: Nature


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Nature materials
Journal: Nature materials


Chemistry of materials
Journal: Chemistry of materials


Chemical physics letters 287 (1-2)
Journal: Chemical physics letters 287 (1-2)


Nature materials
Journal: Nature materials


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Joule
Journal: Joule


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of the american chemical society
Journal: Journal of the american chemical society


Chemical communications
Journal: Chemical communications


Advanced energy materials
Journal: Advanced energy materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature nanotechnology
Journal: Nature nanotechnology


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Thin solid films
Journal: Thin solid films


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs energy letters
Journal: Acs energy letters


Nature communications
Journal: Nature communications


Angewandte chemie
Journal: Angewandte chemie


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review b
Journal: Physical review b


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced energy materials
Journal: Advanced energy materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced functional materials
Journal: Advanced functional materials


Zeitschrift für physikalische chemie
Journal: Zeitschrift für physikalische chemie


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature communications
Journal: Nature communications


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of applied physics
Journal: Journal of applied physics


Advanced energy materials
Journal: Advanced energy materials


Acs nano
Journal: Acs nano


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Chemistry of materials
Journal: Chemistry of materials


Aip advances
Journal: Aip advances


Acs omega
Journal: Acs omega


Advanced materials
Journal: Advanced materials


The journal of physical chemistry b
Journal: The journal of physical chemistry b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry b
Journal: The journal of physical chemistry b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of materials chemistry
Journal: Journal of materials chemistry


Physical review b
Journal: Physical review b


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Advanced materials
Journal: Advanced materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs energy letters
Journal: Acs energy letters


Advanced materials
Journal: Advanced materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Chemical physics letters 461 (1-3)
Journal: Chemical physics letters 461 (1-3)


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of photochemistry and photobiology a: chemistry 148 (1-3)
Journal: Journal of photochemistry and photobiology a: chemistry 148 (1-3)


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nano letters
Journal: Nano letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Polymer chemistry
Journal: Polymer chemistry


Physical review b
Journal: Physical review b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Journal of applied physics
Journal: Journal of applied physics


Journal of applied physics
Journal: Journal of applied physics


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Journal of photochemistry and photobiology a: chemistry 217 (2-3)
Journal: Journal of photochemistry and photobiology a: chemistry 217 (2-3)


Physical review b
Journal: Physical review b


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Chemical physics letters 244 (5-6)
Journal: Chemical physics letters 244 (5-6)


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


The journal of chemical physics
Journal: The journal of chemical physics


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs energy letters
Journal: Acs energy letters


Sustainable energy &fuels

Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Physical review letters
Journal: Physical review letters


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Physica status solidi-a-applied research
Journal: Physica status solidi-a-applied research


Physica status solidi-a-applied research
Journal: Physica status solidi-a-applied research


Physica status solidi-b-basic research
Journal: Physica status solidi-b-basic research


Nature materials
Journal: Nature materials


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Inorganic chemistry
Journal: Inorganic chemistry


Physical review research
Journal: Physical review research


Computational materials science
Journal: Computational materials science


Indian journal of physics
Journal: Indian journal of physics


Rsc advances
Journal: Rsc advances


Physica b: condensed matter
Journal: Physica b: condensed matter


Bulletin of materials science
Journal: Bulletin of materials science


Physical review b
Journal: Physical review b


Materials research express
Journal: Materials research express


Semiconductors
Journal: Semiconductors


Phys. scr
Journal: Phys. scr


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Rsc advances
Journal: Rsc advances


International journal of modern physics b
Journal: International journal of modern physics b


Armenian journal of physics
Journal: Armenian journal of physics


Physica scripta
Journal: Physica scripta


Nano-structures &nano-objects
Journal: Nano-structures &nano-objects


Aip advances
Journal: Aip advances


Physical review materials
Journal: Physical review materials


Indian journal of physics
Journal: Indian journal of physics


Materials chemistry and physics
Journal: Materials chemistry and physics


International journal of modern physics b
Journal: International journal of modern physics b


Rsc advances
Journal: Rsc advances


Nature communications
Journal: Nature communications


Journal of molecular structure
Journal: Journal of molecular structure


Physical review b
Journal: Physical review b


Computational materials science
Journal: Computational materials science


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Materials research express
Journal: Materials research express


Journal of physical science
Journal: Journal of physical science


Journal of theoretical and applied physics
Journal: Journal of theoretical and applied physics


Mod. phys. letts. b
Journal: Mod. phys. letts. b


Physica scripta
Journal: Physica scripta


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Journal of chemical &engineering data
Journal: Journal of chemical &engineering data


Nano letters
Journal: Nano letters


Indian journal of physics
Journal: Indian journal of physics


Physica b: condensed matter
Journal: Physica b: condensed matter


Physical review b
Journal: Physical review b


Rsc advances
Journal: Rsc advances


Materials science in semiconductor processing
Journal: Materials science in semiconductor processing


Nano letters
Journal: Nano letters


Heliyon
Journal: Heliyon


International nano letters
Journal: International nano letters


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of computational electronics
Journal: Journal of computational electronics


Journal of nepal physical society
Journal: Journal of nepal physical society


Communications physics
Journal: Communications physics


Rsc advances
Journal: Rsc advances


Tribhuvan university journal
Journal: Tribhuvan university journal


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Chinese physics b
Journal: Chinese physics b


Journal of superconductivity and novel magnetism
Journal: Journal of superconductivity and novel magnetism


Journal of applied physics
Journal: Journal of applied physics


Solid state communications
Journal: Solid state communications


Journal of applied physics
Journal: Journal of applied physics


Journal of nepal physical society
Journal: Journal of nepal physical society


Indian journal of physics
Journal: Indian journal of physics


Physica b: condensed matter
Journal: Physica b: condensed matter


Npj quantum materials
Journal: Npj quantum materials


Rsc advances
Journal: Rsc advances


Materials today communications
Journal: Materials today communications


Asian journal of medical sciences
Journal: Asian journal of medical sciences


Physical review b
Journal: Physical review b


Journal of advanced physics
Journal: Journal of advanced physics


Modern physics letters b
Journal: Modern physics letters b


Scientific world
Journal: Scientific world


Chemistry–a european journal
Journal: Chemistry–a european journal


Indian journal of physics
Journal: Indian journal of physics


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Solid state communications
Journal: Solid state communications


Journal of nepal physical society
Journal: Journal of nepal physical society


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Physical review b
Journal: Physical review b


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Bhairahawa campus journal
Journal: Bhairahawa campus journal


Kathmandu university medical journal
Journal: Kathmandu university medical journal


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Chemistry–a european journal
Journal: Chemistry–a european journal


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Physical review b 100 (inl/jou-19-55318-rev000)
Journal: Physical review b 100 (inl/jou-19-55318-rev000)


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Chinese physics b
Journal: Chinese physics b


Journal of materials science and engineering a 6 (5-6)
Journal: Journal of materials science and engineering a 6 (5-6)


Advanced science letters
Journal: Advanced science letters


Revue marocaine de la matière condensée
Journal: Revue marocaine de la matière condensée


Journal of materials science and engineering. a 1 (1a)
Journal: Journal of materials science and engineering. a 1 (1a)


Modern physics letters b
Journal: Modern physics letters b


Nature materials
Journal: Nature materials


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Inorganic chemistry
Journal: Inorganic chemistry


Physical review research
Journal: Physical review research


Computational materials science
Journal: Computational materials science


Indian journal of physics
Journal: Indian journal of physics


Rsc advances
Journal: Rsc advances


Physica b: condensed matter
Journal: Physica b: condensed matter


Bulletin of materials science
Journal: Bulletin of materials science


Physical review b
Journal: Physical review b


Materials research express
Journal: Materials research express


Semiconductors
Journal: Semiconductors


Phys. scr
Journal: Phys. scr


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Rsc advances
Journal: Rsc advances


International journal of modern physics b
Journal: International journal of modern physics b


Armenian journal of physics
Journal: Armenian journal of physics


Physica scripta
Journal: Physica scripta


Nano-structures &nano-objects
Journal: Nano-structures &nano-objects


Aip advances
Journal: Aip advances


Physical review materials
Journal: Physical review materials


Indian journal of physics
Journal: Indian journal of physics


Materials chemistry and physics
Journal: Materials chemistry and physics


International journal of modern physics b
Journal: International journal of modern physics b


Rsc advances
Journal: Rsc advances


Nature communications
Journal: Nature communications


Journal of molecular structure
Journal: Journal of molecular structure


Physical review b
Journal: Physical review b


Computational materials science
Journal: Computational materials science


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Materials research express
Journal: Materials research express


Journal of physical science
Journal: Journal of physical science


Journal of theoretical and applied physics
Journal: Journal of theoretical and applied physics


Mod. phys. letts. b
Journal: Mod. phys. letts. b


Physica scripta
Journal: Physica scripta


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Journal of chemical &engineering data
Journal: Journal of chemical &engineering data


Nano letters
Journal: Nano letters


Indian journal of physics
Journal: Indian journal of physics


Physica b: condensed matter
Journal: Physica b: condensed matter


Physical review b
Journal: Physical review b


Rsc advances
Journal: Rsc advances


Materials science in semiconductor processing
Journal: Materials science in semiconductor processing


Nano letters
Journal: Nano letters


Heliyon
Journal: Heliyon


International nano letters
Journal: International nano letters


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of computational electronics
Journal: Journal of computational electronics


Journal of nepal physical society
Journal: Journal of nepal physical society


Communications physics
Journal: Communications physics


Rsc advances
Journal: Rsc advances


Tribhuvan university journal
Journal: Tribhuvan university journal


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Chinese physics b
Journal: Chinese physics b


Journal of superconductivity and novel magnetism
Journal: Journal of superconductivity and novel magnetism


Journal of applied physics
Journal: Journal of applied physics


Solid state communications
Journal: Solid state communications


Journal of applied physics
Journal: Journal of applied physics


Journal of nepal physical society
Journal: Journal of nepal physical society


Indian journal of physics
Journal: Indian journal of physics


Physica b: condensed matter
Journal: Physica b: condensed matter


Npj quantum materials
Journal: Npj quantum materials


Rsc advances
Journal: Rsc advances


Materials today communications
Journal: Materials today communications


Asian journal of medical sciences
Journal: Asian journal of medical sciences


Physical review b
Journal: Physical review b


Journal of advanced physics
Journal: Journal of advanced physics


Modern physics letters b
Journal: Modern physics letters b


Scientific world
Journal: Scientific world


Chemistry–a european journal
Journal: Chemistry–a european journal


Indian journal of physics
Journal: Indian journal of physics


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Solid state communications
Journal: Solid state communications


Journal of nepal physical society
Journal: Journal of nepal physical society


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Physical review b
Journal: Physical review b


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Bhairahawa campus journal
Journal: Bhairahawa campus journal


Kathmandu university medical journal
Journal: Kathmandu university medical journal


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Chemistry–a european journal
Journal: Chemistry–a european journal


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Physical review b 100 (inl/jou-19-55318-rev000)
Journal: Physical review b 100 (inl/jou-19-55318-rev000)


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Chinese physics b
Journal: Chinese physics b


Journal of materials science and engineering a 6 (5-6)
Journal: Journal of materials science and engineering a 6 (5-6)


Advanced science letters
Journal: Advanced science letters


Revue marocaine de la matière condensée
Journal: Revue marocaine de la matière condensée


Journal of materials science and engineering. a 1 (1a)
Journal: Journal of materials science and engineering. a 1 (1a)


Modern physics letters b
Journal: Modern physics letters b


Nature energy
Journal: Nature energy


Nature communications
Journal: Nature communications


Journal of the american chemical society
Journal: Journal of the american chemical society


Inorganic chemistry
Journal: Inorganic chemistry


Acs nano
Journal: Acs nano


Nano letters
Journal: Nano letters


Acs energy letters
Journal: Acs energy letters


Chemistry of materials
Journal: Chemistry of materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Chemical science
Journal: Chemical science


Science advances
Journal: Science advances


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs energy letters
Journal: Acs energy letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Acs nano
Journal: Acs nano


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Communications physics
Journal: Communications physics


Acs energy letters
Journal: Acs energy letters


Crystal growth &design
Journal: Crystal growth &design


Npg asia materials
Journal: Npg asia materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Chemistry of materials
Journal: Chemistry of materials


Advanced materials
Journal: Advanced materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Chemistry–a european journal
Journal: Chemistry–a european journal


Organic letters
Journal: Organic letters


Acs materials letters
Journal: Acs materials letters


Acs nano
Journal: Acs nano


Chemistry–a european journal
Journal: Chemistry–a european journal


Advanced energy materials
Journal: Advanced energy materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced functional materials
Journal: Advanced functional materials


Advanced optical materials
Journal: Advanced optical materials


Acs materials letters
Journal: Acs materials letters


Nature communications
Journal: Nature communications


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Chemistry–a european journal
Journal: Chemistry–a european journal


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Acs energy letters
Journal: Acs energy letters


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Nanoscale horizons
Journal: Nanoscale horizons


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Advanced energy materials
Journal: Advanced energy materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Joule
Journal: Joule


Acs materials letters
Journal: Acs materials letters


Acs energy letters
Journal: Acs energy letters


Chemical communications
Journal: Chemical communications


Advanced energy materials
Journal: Advanced energy materials


Acs applied energy materials
Journal: Acs applied energy materials


Acs materials letters
Journal: Acs materials letters


The journal of chemical physics
Journal: The journal of chemical physics


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs energy letters
Journal: Acs energy letters


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Chemistry of materials
Journal: Chemistry of materials


Nature communications
Journal: Nature communications


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nature communications
Journal: Nature communications


Organic electronics
Journal: Organic electronics


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Matter
Journal: Matter


Nature communications
Journal: Nature communications


Acs materials letters
Journal: Acs materials letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced energy materials
Journal: Advanced energy materials


Apl materials
Journal: Apl materials


Small
Journal: Small


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nature communications
Journal: Nature communications


Acs energy letters
Journal: Acs energy letters


Scientific reports
Journal: Scientific reports


Advanced materials
Journal: Advanced materials


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Acs nano
Journal: Acs nano


Chem
Journal: Chem


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nature energy
Journal: Nature energy


Physica status solidi (rrl)–rapid research letters
Journal: Physica status solidi (rrl)–rapid research letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs materials letters
Journal: Acs materials letters


Journal of polymer science part a: polymer chemistry
Journal: Journal of polymer science part a: polymer chemistry


Advanced materials
Journal: Advanced materials


Energy technology
Journal: Energy technology


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


Journal of the american chemical society

Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Solid state communications
Journal: Solid state communications


Chemphyschem
Journal: Chemphyschem


Journal of applied physics
Journal: Journal of applied physics


European physical journal b
Journal: European physical journal b


Apl materials
Journal: Apl materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Applied surface science
Journal: Applied surface science


Applied surface science
Journal: Applied surface science


The european physical journal b
Journal: The european physical journal b


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Physical review b
Journal: Physical review b


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of vacuum science &technology b: microelectronics and nanometer …
Journal: Journal of vacuum science &technology b: microelectronics and nanometer …


Nanotechnology
Journal: Nanotechnology


Physical review b
Journal: Physical review b


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Turkish journal of physics
Journal: Turkish journal of physics


Wiley interdisciplinary reviews: computational molecular science
Journal: Wiley interdisciplinary reviews: computational molecular science


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


The european physical journal b
Journal: The european physical journal b


Journal of molecular structure
Journal: Journal of molecular structure


Nanotechnology
Journal: Nanotechnology


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Rsc advances
Journal: Rsc advances


Turkish journal of physics
Journal: Turkish journal of physics


J phys: condens matter
Journal: J phys: condens matter


Physical review materials
Journal: Physical review materials


Bulletin of the american physical society
Journal: Bulletin of the american physical society


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Proposed for publication in applied physics letters.
Journal: Proposed for publication in applied physics letters.


Proposed for publication in applied physics letters.
Journal: Proposed for publication in applied physics letters.


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Turkish journal of physics
Journal: Turkish journal of physics


Turkish journal of physics
Journal: Turkish journal of physics


J. phys; condens. matter
Journal: J. phys; condens. matter


Nano letters
Journal: Nano letters


Nanotechnology
Journal: Nanotechnology


Nanotechnology
Journal: Nanotechnology


Langmuir
Journal: Langmuir


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of materials chemistry
Journal: Journal of materials chemistry


Electrochimica acta
Journal: Electrochimica acta


Nanoscale
Journal: Nanoscale


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of nanomaterials
Journal: Journal of nanomaterials


Advanced materials interfaces
Journal: Advanced materials interfaces


New journal of chemistry
Journal: New journal of chemistry


New journal of chemistry
Journal: New journal of chemistry


Nanotechnology
Journal: Nanotechnology


Langmuir
Journal: Langmuir


Journal of materials chemistry
Journal: Journal of materials chemistry


Rsc advances
Journal: Rsc advances


Ieee sensors journal
Journal: Ieee sensors journal


Journal of materials chemistry
Journal: Journal of materials chemistry


Journal of lightwave technology
Journal: Journal of lightwave technology


Nanotechnology
Journal: Nanotechnology


Advanced optical materials
Journal: Advanced optical materials


Ieee photonics journal
Journal: Ieee photonics journal


Optics letters
Journal: Optics letters


Nanomaterials
Journal: Nanomaterials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nanophotonics
Journal: Nanophotonics


Rsc advances
Journal: Rsc advances


Nanomaterials
Journal: Nanomaterials


Applied surface science
Journal: Applied surface science


Journal of luminescence
Journal: Journal of luminescence


Acs omega
Journal: Acs omega


Nanoscale research letters
Journal: Nanoscale research letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Optics express
Journal: Optics express


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Acs applied polymer materials
Journal: Acs applied polymer materials


Liver transplantation
Journal: Liver transplantation


Nanotechnology
Journal: Nanotechnology


Physica status solidi (a)
Journal: Physica status solidi (a)


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Applied surface science
Journal: Applied surface science


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Photonics technology letters
Journal: Photonics technology letters


Polymer
Journal: Polymer


Semicond. phys. quantum electron. optoelectron
Journal: Semicond. phys. quantum electron. optoelectron


Advances in resist materials and processing technology xxx
Journal: Advances in resist materials and processing technology xxx


Nanomaterials
Journal: Nanomaterials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advances in resist materials and processing technology xxx
Journal: Advances in resist materials and processing technology xxx


J. phys. chem. c
Journal: J. phys. chem. c


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs applied nano materials
Journal: Acs applied nano materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Matter
Journal: Matter


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Nanophotonics iv
Journal: Nanophotonics iv


Acs applied energy materials
Journal: Acs applied energy materials


Nanoscale
Journal: Nanoscale


Materials letters
Journal: Materials letters


Nato science for peace and security series b: physics and biophysics
Journal: Nato science for peace and security series b: physics and biophysics


Journal of lightwave technology
Journal: Journal of lightwave technology


Optica pura y aplicada
Journal: Optica pura y aplicada


Mètode science studies journal: annual review
Journal: Mètode science studies journal: annual review


Human gene therapy
Journal: Human gene therapy


Ix congreso nacional del color: alicante
Journal: Ix congreso nacional del color: alicante


Nano letters
Journal: Nano letters


Nanotechnology
Journal: Nanotechnology


Nanotechnology
Journal: Nanotechnology


Langmuir
Journal: Langmuir


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of materials chemistry
Journal: Journal of materials chemistry


Electrochimica acta
Journal: Electrochimica acta


Nanoscale
Journal: Nanoscale


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of nanomaterials
Journal: Journal of nanomaterials


Advanced materials interfaces
Journal: Advanced materials interfaces


New journal of chemistry
Journal: New journal of chemistry


New journal of chemistry
Journal: New journal of chemistry


Nanotechnology
Journal: Nanotechnology


Langmuir
Journal: Langmuir


Journal of materials chemistry
Journal: Journal of materials chemistry


Rsc advances
Journal: Rsc advances


Ieee sensors journal
Journal: Ieee sensors journal


Journal of materials chemistry
Journal: Journal of materials chemistry


Journal of lightwave technology
Journal: Journal of lightwave technology


Nanotechnology
Journal: Nanotechnology


Advanced optical materials
Journal: Advanced optical materials


Ieee photonics journal
Journal: Ieee photonics journal


Optics letters
Journal: Optics letters


Nanomaterials
Journal: Nanomaterials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nanophotonics
Journal: Nanophotonics


Rsc advances
Journal: Rsc advances


Nanomaterials
Journal: Nanomaterials


Applied surface science
Journal: Applied surface science


Journal of luminescence
Journal: Journal of luminescence


Acs omega
Journal: Acs omega


Nanoscale research letters
Journal: Nanoscale research letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Optics express
Journal: Optics express


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Acs applied polymer materials
Journal: Acs applied polymer materials


Liver transplantation
Journal: Liver transplantation


Nanotechnology
Journal: Nanotechnology


Physica status solidi (a)
Journal: Physica status solidi (a)


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Applied surface science
Journal: Applied surface science


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Photonics technology letters
Journal: Photonics technology letters


Polymer
Journal: Polymer


Semicond. phys. quantum electron. optoelectron
Journal: Semicond. phys. quantum electron. optoelectron


Advances in resist materials and processing technology xxx
Journal: Advances in resist materials and processing technology xxx


Nanomaterials
Journal: Nanomaterials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advances in resist materials and processing technology xxx
Journal: Advances in resist materials and processing technology xxx


J. phys. chem. c
Journal: J. phys. chem. c


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs applied nano materials
Journal: Acs applied nano materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Matter
Journal: Matter


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Nanophotonics iv
Journal: Nanophotonics iv


Acs applied energy materials
Journal: Acs applied energy materials


Nanoscale
Journal: Nanoscale


Materials letters
Journal: Materials letters


Nato science for peace and security series b: physics and biophysics
Journal: Nato science for peace and security series b: physics and biophysics


Journal of lightwave technology
Journal: Journal of lightwave technology


Optica pura y aplicada
Journal: Optica pura y aplicada


Mètode science studies journal: annual review
Journal: Mètode science studies journal: annual review


Human gene therapy
Journal: Human gene therapy


Ix congreso nacional del color: alicante
Journal: Ix congreso nacional del color: alicante


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of applied crystallography
Journal: Journal of applied crystallography


Applied thermal engineering
Journal: Applied thermal engineering


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Physical review b
Journal: Physical review b


Journal of applied crystallography
Journal: Journal of applied crystallography


Journal of molecular structure
Journal: Journal of molecular structure


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Solar energy
Journal: Solar energy


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Journal of molecular structure
Journal: Journal of molecular structure


Materials research bulletin
Journal: Materials research bulletin


Acta crystallographica section b: structural science
Journal: Acta crystallographica section b: structural science


Dalton transactions
Journal: Dalton transactions


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Journal of molecular structure
Journal: Journal of molecular structure


Journal of energy storage
Journal: Journal of energy storage


Journal of molecular structure
Journal: Journal of molecular structure


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of applied crystallography
Journal: Journal of applied crystallography


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Journal of molecular structure
Journal: Journal of molecular structure


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Physica status solidi (b)
Journal: Physica status solidi (b)


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Dalton transactions
Journal: Dalton transactions


Journal of molecular structure
Journal: Journal of molecular structure


Solar energy
Journal: Solar energy


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Metrologia
Journal: Metrologia


Dalton transactions
Journal: Dalton transactions


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Ferroelectrics
Journal: Ferroelectrics


Infrared physics &technology
Journal: Infrared physics &technology


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of molecular structure
Journal: Journal of molecular structure


Acta crystallographica section b: structural science
Journal: Acta crystallographica section b: structural science


Thermochimica acta
Journal: Thermochimica acta


Polyhedron
Journal: Polyhedron


Journal of molecular structure
Journal: Journal of molecular structure


Materials research bulletin
Journal: Materials research bulletin


Oriental journal of chemistry
Journal: Oriental journal of chemistry


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Journal of energy storage
Journal: Journal of energy storage


Journal of applied crystallography
Journal: Journal of applied crystallography


Journal de physique i
Journal: Journal de physique i


Solid state communications
Journal: Solid state communications


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Phase transitions: a multinational journal
Journal: Phase transitions: a multinational journal


Polyhedron
Journal: Polyhedron


Journal of molecular structure
Journal: Journal of molecular structure


Journal of thermal analysis
Journal: Journal of thermal analysis


Acta crystallographica section b: structural science
Journal: Acta crystallographica section b: structural science


Phase transitions: a multinational journal
Journal: Phase transitions: a multinational journal


Journal of nuclear materials
Journal: Journal of nuclear materials


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Journal of molecular structure
Journal: Journal of molecular structure


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Powder diffraction 34 (s1), s48-s
Journal: Powder diffraction 34 (s1)


Journal of electronic materials
Journal: Journal of electronic materials


Physical review b
Journal: Physical review b


Open access library journal
Journal: Open access library journal


Acta crystallographica a-foundation and advances 63, s182-s
Journal: Acta crystallographica a-foundation and advances 63


Dalton transactions
Journal: Dalton transactions


Crystals
Journal: Crystals


Acta crystallographica a-foundation and advances 65, s328-s
Journal: Acta crystallographica a-foundation and advances 65


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Ferroelectrics
Journal: Ferroelectrics


Dalton transactions
Journal: Dalton transactions


Csedu
Journal: Csedu


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Journal of molecular structure
Journal: Journal of molecular structure


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Journal of molecular structure
Journal: Journal of molecular structure


Acta crystallographica a-foundation and advances 67, c243-c
Journal: Acta crystallographica a-foundation and advances 67


Acta crystallographica a-foundation and advances 64, c546-c
Journal: Acta crystallographica a-foundation and advances 64


Acta crystallographica a-foundation and advances 58, c339-c
Journal: Acta crystallographica a-foundation and advances 58


Ferroelectrics
Journal: Ferroelectrics


Anales afa
Journal: Anales afa


Solid state communications
Journal: Solid state communications


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of applied crystallography
Journal: Journal of applied crystallography


Applied thermal engineering
Journal: Applied thermal engineering


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Physical review b
Journal: Physical review b


Journal of applied crystallography
Journal: Journal of applied crystallography


Journal of molecular structure
Journal: Journal of molecular structure


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Solar energy
Journal: Solar energy


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Journal of molecular structure
Journal: Journal of molecular structure


Materials research bulletin
Journal: Materials research bulletin


Acta crystallographica section b: structural science
Journal: Acta crystallographica section b: structural science


Dalton transactions
Journal: Dalton transactions


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Journal of molecular structure
Journal: Journal of molecular structure


Journal of energy storage
Journal: Journal of energy storage


Journal of molecular structure
Journal: Journal of molecular structure


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of applied crystallography
Journal: Journal of applied crystallography


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Journal of molecular structure
Journal: Journal of molecular structure


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Physica status solidi (b)
Journal: Physica status solidi (b)


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Dalton transactions
Journal: Dalton transactions



Chemistry of materials
Journal: Chemistry of materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Chemistry of materials
Journal: Chemistry of materials


Physical review b
Journal: Physical review b


Journal of materials chemistry
Journal: Journal of materials chemistry


Physical review b
Journal: Physical review b


International journal of inorganic materials
Journal: International journal of inorganic materials


Physical review b
Journal: Physical review b


Solid state communications
Journal: Solid state communications


Inorganic chemistry
Journal: Inorganic chemistry


Physical review b
Journal: Physical review b


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Inorganic chemistry
Journal: Inorganic chemistry


Chemistry of materials
Journal: Chemistry of materials


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Acs catalysis
Journal: Acs catalysis


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Dalton transactions
Journal: Dalton transactions


Physical review b
Journal: Physical review b


Nuclear medicine and biology
Journal: Nuclear medicine and biology


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Nature
Journal: Nature


Physical review b
Journal: Physical review b


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Inorganic chemistry
Journal: Inorganic chemistry


Solid state sciences
Journal: Solid state sciences


Journal of the chemical society, dalton transactions
Journal: Journal of the chemical society


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Inorganic chemistry
Journal: Inorganic chemistry


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Physical review b
Journal: Physical review b


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Inorganic chemistry
Journal: Inorganic chemistry


Inorganic chemistry
Journal: Inorganic chemistry


Acs applied bio materials
Journal: Acs applied bio materials


Inorganic chemistry
Journal: Inorganic chemistry


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Scientific reports
Journal: Scientific reports


Physical review materials
Journal: Physical review materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Physical review b
Journal: Physical review b


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Chemistry of materials
Journal: Chemistry of materials


Dalton transactions
Journal: Dalton transactions


Physical review b
Journal: Physical review b


Superconductor science and technology
Journal: Superconductor science and technology


Inorganic chemistry communications
Journal: Inorganic chemistry communications


Materials research bulletin
Journal: Materials research bulletin


Inorganic chemistry
Journal: Inorganic chemistry


Inorganic chemistry
Journal: Inorganic chemistry


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Journal of physics. condensed matter
Journal: Journal of physics. condensed matter


Superconductor science and technology
Journal: Superconductor science and technology


European journal of nuclear medicine and molecular imaging 36, s393-s
Journal: European journal of nuclear medicine and molecular imaging 36


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Materials research bulletin
Journal: Materials research bulletin


Inorganic chemistry communications
Journal: Inorganic chemistry communications


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Journal of physics. condensed matter
Journal: Journal of physics. condensed matter


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Physical review b: condensed matter and materials physics
Journal: Physical review b: condensed matter and materials physics


Acta crystallographica a-foundation and advances
Journal: Acta crystallographica a-foundation and advances


Social studies
Journal: Social studies


Nano letters
Journal: Nano letters


Nano letters
Journal: Nano letters


Nature communications
Journal: Nature communications


Nature photonics
Journal: Nature photonics


Acs energy letters
Journal: Acs energy letters


Nano letters
Journal: Nano letters


Nature photonics
Journal: Nature photonics


Acs nano
Journal: Acs nano


Journal of the american chemical society
Journal: Journal of the american chemical society


Chemistry of materials
Journal: Chemistry of materials


Acs nano
Journal: Acs nano


Acs nano
Journal: Acs nano


Journal of the american chemical society
Journal: Journal of the american chemical society


Nanoscale
Journal: Nanoscale


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Nature materials
Journal: Nature materials


Acs applied nano materials
Journal: Acs applied nano materials


Chemistry of materials
Journal: Chemistry of materials


Inorganic chemistry
Journal: Inorganic chemistry


Journal of the american chemical society
Journal: Journal of the american chemical society


Chemistry of materials
Journal: Chemistry of materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs nano
Journal: Acs nano


Journal of renewable and sustainable energy
Journal: Journal of renewable and sustainable energy


Acs nano
Journal: Acs nano


Structural dynamics
Journal: Structural dynamics


Acs materials letters
Journal: Acs materials letters


Science advances
Journal: Science advances


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs nano
Journal: Acs nano


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Advanced optical materials
Journal: Advanced optical materials


Chemistry of materials
Journal: Chemistry of materials


Angewandte chemie
Journal: Angewandte chemie


Applied physics a
Journal: Applied physics a


Nature communications
Journal: Nature communications


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of nanomaterials
Journal: Journal of nanomaterials


Acs nano
Journal: Acs nano


Nano energy
Journal: Nano energy


Advanced science
Journal: Advanced science


Molecular crystals and liquid crystals
Journal: Molecular crystals and liquid crystals


Acs nano
Journal: Acs nano


Dyes and pigments
Journal: Dyes and pigments


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nature communications
Journal: Nature communications


Thin solid films
Journal: Thin solid films


Acs energy letters
Journal: Acs energy letters


Inorganic chemistry
Journal: Inorganic chemistry


Advanced materials
Journal: Advanced materials


Applied optics
Journal: Applied optics


Laser physics letters
Journal: Laser physics letters


Science and technology of advanced materials
Journal: Science and technology of advanced materials


Batteries &supercaps
Journal: Batteries &supercaps


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Macromolecular symposia
Journal: Macromolecular symposia


Advanced science
Journal: Advanced science


Laser physics letters
Journal: Laser physics letters


Ukr. j. phys. opt
Journal: Ukr. j. phys. opt


Acs energy letters
Journal: Acs energy letters


Quantum sensing and nanophotonic devices x
Journal: Quantum sensing and nanophotonic devices x


Journal of biomedical materials research part b: applied biomaterials 100 (1 …
Journal: Journal of biomedical materials research part b: applied biomaterials 100 (1 …


Advanced materials
Journal: Advanced materials


Advanced energy materials
Journal: Advanced energy materials


Chemistry of materials
Journal: Chemistry of materials


Chemphyschem
Journal: Chemphyschem


Molecular crystals and liquid crystals
Journal: Molecular crystals and liquid crystals


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Molecular crystals and liquid crystals
Journal: Molecular crystals and liquid crystals


Acs photonics
Journal: Acs photonics


Nature photonics
Journal: Nature photonics


Journal of laser micro/nanoengineering
Journal: Journal of laser micro/nanoengineering


Biophysical journal
Journal: Biophysical journal


Biophysical journal
Journal: Biophysical journal


Ukr. j. phys. opt
Journal: Ukr. j. phys. opt


Electronic processes in organic materials
Journal: Electronic processes in organic materials


Nonlinear optics of liquid and photorefractive crystals
Journal: Nonlinear optics of liquid and photorefractive crystals


Nature energy
Journal: Nature energy


Light: science &applications
Journal: Light: science &applications


Science advances
Journal: Science advances


Acs energy letters
Journal: Acs energy letters


Communications physics
Journal: Communications physics


Journal of the american chemical society
Journal: Journal of the american chemical society


Chemistry of materials
Journal: Chemistry of materials


Acs nano
Journal: Acs nano


Angewandte chemie
Journal: Angewandte chemie


Acs materials letters
Journal: Acs materials letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nanoscale
Journal: Nanoscale


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced energy materials
Journal: Advanced energy materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced energy materials
Journal: Advanced energy materials


Nanoscale
Journal: Nanoscale


J. phys. chem. lett.
Journal: J. phys. chem. lett.


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemistry–a european journal
Journal: Chemistry–a european journal


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Light: science &applications
Journal: Light: science &applications


Advanced materials
Journal: Advanced materials


Acs omega
Journal: Acs omega


Acs omega
Journal: Acs omega


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


Chem. eur. j.
Journal: Chem. eur. j.


Small
Journal: Small


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Nano letters
Journal: Nano letters


Nature communications
Journal: Nature communications


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Light: science &applications
Journal: Light: science &applications


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


New journal of chemistry
Journal: New journal of chemistry


Journal of the american chemical society
Journal: Journal of the american chemical society


Chemistry–a european journal
Journal: Chemistry–a european journal


Journal of the american chemical society
Journal: Journal of the american chemical society


Global challenges
Journal: Global challenges


Chemical physics letters
Journal: Chemical physics letters


Chemistry–a european journal
Journal: Chemistry–a european journal


Chemistry–a european journal
Journal: Chemistry–a european journal


Advanced materials
Journal: Advanced materials


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Inorganic chemistry
Journal: Inorganic chemistry


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemistry–an asian journal
Journal: Chemistry–an asian journal


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Acs materials letters
Journal: Acs materials letters


Acs energy letters
Journal: Acs energy letters


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


Chemphyschem
Journal: Chemphyschem


Advanced functional materials
Journal: Advanced functional materials


Advanced materials
Journal: Advanced materials


Communications chemistry
Journal: Communications chemistry


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Acs materials letters
Journal: Acs materials letters


Advanced optical materials
Journal: Advanced optical materials


Chemistry of materials
Journal: Chemistry of materials


Nano letters
Journal: Nano letters


Chemical science
Journal: Chemical science


Advanced energy materials
Journal: Advanced energy materials


Cleo: applications and technology, ath1i.
Journal: Cleo: applications and technology


Global challenges
Journal: Global challenges


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Chemistry of materials
Journal: Chemistry of materials


Nature nanotechnology
Journal: Nature nanotechnology


Chemistry of materials
Journal: Chemistry of materials


Materials horizons
Journal: Materials horizons


Chemistry of materials
Journal: Chemistry of materials


Acta crystallographica section e: crystallographic communications 73 (4 …
Journal: Acta crystallographica section e: crystallographic communications 73 (4 …


Combustion science and technology
Journal: Combustion science and technology


Mendeleev communications
Journal: Mendeleev communications


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Applied nanoscience
Journal: Applied nanoscience


Chemistry of materials
Journal: Chemistry of materials


Doklady akademii nauk-rossijskaya akademiya nauk
Journal: Doklady akademii nauk-rossijskaya akademiya nauk


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Mendeleev communications
Journal: Mendeleev communications


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Mendeleev communications
Journal: Mendeleev communications


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Mendeleev communications
Journal: Mendeleev communications


Mendeleev communications
Journal: Mendeleev communications


Journal of energy chemistry
Journal: Journal of energy chemistry


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Glass physics &chemistry
Journal: Glass physics &chemistry


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Rsc advances
Journal: Rsc advances


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Mendeleev communications
Journal: Mendeleev communications


Molecules
Journal: Molecules


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Russian journal of inorganic chemistry
Journal: Russian journal of inorganic chemistry


Chemistry of materials
Journal: Chemistry of materials


Molecules
Journal: Molecules


Frontiers in chemistry
Journal: Frontiers in chemistry


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nanomaterials
Journal: Nanomaterials


Acta crystallographica section e: crystallographic communications 77 (7 …
Journal: Acta crystallographica section e: crystallographic communications 77 (7 …


Frontiers in chemistry
Journal: Frontiers in chemistry


Acs materials letters
Journal: Acs materials letters


Molecules
Journal: Molecules


Journal of physical chemistry c
Journal: Journal of physical chemistry c


Mendeleev communications
Journal: Mendeleev communications


Mendeleev communications
Journal: Mendeleev communications


Nanosystems: physics, chemistry, mathematics
Journal: Nanosystems: physics


Journal of energy chemistry
Journal: Journal of energy chemistry


Mendeleev communications
Journal: Mendeleev communications


Russian journal of inorganic chemistry
Journal: Russian journal of inorganic chemistry


Russian journal of inorganic chemistry
Journal: Russian journal of inorganic chemistry


Crystals
Journal: Crystals


Mendeleev communications
Journal: Mendeleev communications


Chemistry of materials
Journal: Chemistry of materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Acs omega
Journal: Acs omega


Mendeleev communications
Journal: Mendeleev communications


Mendeleev communications
Journal: Mendeleev communications


Mendeleev communications
Journal: Mendeleev communications


Japanese journal of applied physics 61 (se), s
Journal: Japanese journal of applied physics 61 (se)


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nanomaterials
Journal: Nanomaterials


International journal of molecular sciences
Journal: International journal of molecular sciences


Mendeleev communications
Journal: Mendeleev communications


Inorganic materials
Journal: Inorganic materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of materials chemistry a

Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Infomat
Journal: Infomat


Laser science, jtu4a.
Journal: Laser science


Applied physics letters
Journal: Applied physics letters


Organic electronics
Journal: Organic electronics


中国材料进展
Journal: 中国材料进展


Advanced functional materials
Journal: Advanced functional materials


Optoelectronic devices and integration v
Journal: Optoelectronic devices and integration v


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Nano energy
Journal: Nano energy


Materials today physics
Journal: Materials today physics


Nature reviews physics
Journal: Nature reviews physics


Advanced functional materials
Journal: Advanced functional materials


Optics express
Journal: Optics express


中国光学
Journal: 中国光学


Advanced materials
Journal: Advanced materials


Spie micro+ nano materials, devices, and applications 2019
Journal: Spie micro+ nano materials


Angewandte chemie
Journal: Angewandte chemie


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Advanced functional materials
Journal: Advanced functional materials


Science
Journal: Science


Acs nano
Journal: Acs nano


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature materials
Journal: Nature materials


Nature nanotechnology
Journal: Nature nanotechnology


Angewandte chemie
Journal: Angewandte chemie


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Acs energy letters
Journal: Acs energy letters


Chemistry of materials
Journal: Chemistry of materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Crystal growth and design
Journal: Crystal growth and design


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Acs nano
Journal: Acs nano


Nanotechnology
Journal: Nanotechnology


Langmuir
Journal: Langmuir


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Chemistry of materials
Journal: Chemistry of materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Angewandte chemie international edition
Journal: Angewandte chemie international edition


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Langmuir
Journal: Langmuir


Advanced materials
Journal: Advanced materials


Chemical science
Journal: Chemical science


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Nanotechnology
Journal: Nanotechnology


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced energy materials
Journal: Advanced energy materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nanoscale
Journal: Nanoscale


Nano letters
Journal: Nano letters


Analytical biochemistry
Journal: Analytical biochemistry


Chemistry of materials
Journal: Chemistry of materials


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Nanoscale
Journal: Nanoscale


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Journal of materials chemistry
Journal: Journal of materials chemistry


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Chemical communications
Journal: Chemical communications


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Langmuir
Journal: Langmuir


Advanced functional materials
Journal: Advanced functional materials


Nano research
Journal: Nano research


Journal of materials chemistry a
Journal: Journal of materials chemistry a


The journal of physical chemistry c
Journal: The journal of physical chemistry c


应用化学
Journal: 应用化学


Nano research
Journal: Nano research


化工矿产地质
Journal: 化工矿产地质


Organic electronics
Journal: Organic electronics


Applied physics letters
Journal: Applied physics letters


Nanoscale
Journal: Nanoscale


Nanoscale
Journal: Nanoscale


Chemical science
Journal: Chemical science


Chemical communications
Journal: Chemical communications


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Nanoscale
Journal: Nanoscale


Journal of applied physics
Journal: Journal of applied physics


Chemical communications
Journal: Chemical communications


应用化学
Journal: 应用化学


Materials advances
Journal: Materials advances


Crystal growth &design
Journal: Crystal growth &design


Advanced functional materials
Journal: Advanced functional materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Nanotechnology
Journal: Nanotechnology


Chinese journal of chemistry
Journal: Chinese journal of chemistry


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Crystal growth and design
Journal: Crystal growth and design


Chemphyschem
Journal: Chemphyschem


矿物岩石地球化学通报
Journal: 矿物岩石地球化学通报


Bull. mineral. petrol. geochem
Journal: Bull. mineral. petrol. geochem


Nanoscale
Journal: Nanoscale


Nanoscale advances
Journal: Nanoscale advances


Nanoscale
Journal: Nanoscale


Chemical journal of chinese universities-chinese
Journal: Chemical journal of chinese universities-chinese


Crystengcomm
Journal: Crystengcomm


Advanced optical materials
Journal: Advanced optical materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Macromolecular rapid communications
Journal: Macromolecular rapid communications


中国材料进展
Journal: 中国材料进展


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Chemistry–a european journal
Journal: Chemistry–a european journal


Molecules
Journal: Molecules


Chemical communications
Journal: Chemical communications


Chinese journal of chemistry
Journal: Chinese journal of chemistry


Nanoscience and nanotechnology letters
Journal: Nanoscience and nanotechnology letters


Sensors and actuators b: chemical
Journal: Sensors and actuators b: chemical


Rsc advances
Journal: Rsc advances


The journal of chemical physics
Journal: The journal of chemical physics


Applied physics letters
Journal: Applied physics letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Applied physics letters
Journal: Applied physics letters


Nano-micro letters
Journal: Nano-micro letters


Journal of applied physics
Journal: Journal of applied physics


Nano today
Journal: Nano today


Nano letters
Journal: Nano letters


Journal of applied physics
Journal: Journal of applied physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs applied energy materials
Journal: Acs applied energy materials


Acta astronautica
Journal: Acta astronautica


Applied physics letters
Journal: Applied physics letters


Applied materials today
Journal: Applied materials today


Nanoscale
Journal: Nanoscale


Carbon
Journal: Carbon


Acs applied nano materials
Journal: Acs applied nano materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Thin solid films
Journal: Thin solid films


Scientific reports
Journal: Scientific reports


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Macromolecules
Journal: Macromolecules


Nanoscale
Journal: Nanoscale


Applied physics letters
Journal: Applied physics letters


Database
Journal: Database


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


The journal of chemical physics
Journal: The journal of chemical physics


Inorganic chemistry
Journal: Inorganic chemistry


Materials chemistry and physics
Journal: Materials chemistry and physics


Chemelectrochem
Journal: Chemelectrochem


Scientific reports
Journal: Scientific reports


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Electronic materials
Journal: Electronic materials


Canadian journal of physics 92 (7/8)
Journal: Canadian journal of physics 92 (7/8)


Faraday discussions
Journal: Faraday discussions


Journal of nano research
Journal: Journal of nano research


Ecs journal of solid state science and technology
Journal: Ecs journal of solid state science and technology


Journal of renewable and sustainable energy
Journal: Journal of renewable and sustainable energy


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Science of advanced materials
Journal: Science of advanced materials


Faraday discussions
Journal: Faraday discussions


Photonics north 2013
Journal: Photonics north 2013


Nanotechnology
Journal: Nanotechnology


Journal of applied physics
Journal: Journal of applied physics


Faraday discussions
Journal: Faraday discussions


Materials
Journal: Materials


Nano select
Journal: Nano select


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Ecs journal of solid state science and technology
Journal: Ecs journal of solid state science and technology


Physica a: statistical mechanics and its applications
Journal: Physica a: statistical mechanics and its applications


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


한국광전자학회지 journal of photonic science and technology
Journal: 한국광전자학회지 journal of photonic science and technology


Radiation
Journal: Radiation


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of visualized experiments: jove
Journal: Journal of visualized experiments: jove


Science of advanced materials
Journal: Science of advanced materials


Organic photonics iv
Journal: Organic photonics iv


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced photonics research
Journal: Advanced photonics research


Novel optical materials and applications, jtu1a.
Journal: Novel optical materials and applications


2020 photonics north (pn)
Journal: 2020 photonics north (pn)


2020 photonics north (pn)
Journal: 2020 photonics north (pn)


Chinese optics letters
Journal: Chinese optics letters


Chinese optics letters
Journal: Chinese optics letters


Faraday discussions
Journal: Faraday discussions


Faraday discussions
Journal: Faraday discussions


Sensors and actuators b: chemical
Journal: Sensors and actuators b: chemical


Rsc advances
Journal: Rsc advances


The journal of chemical physics
Journal: The journal of chemical physics


Applied physics letters
Journal: Applied physics letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Applied physics letters
Journal: Applied physics letters


Nano-micro letters
Journal: Nano-micro letters


Journal of applied physics
Journal: Journal of applied physics


Nano today
Journal: Nano today


Nano letters
Journal: Nano letters


Journal of applied physics
Journal: Journal of applied physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs applied energy materials
Journal: Acs applied energy materials


Acta astronautica
Journal: Acta astronautica


Applied physics letters
Journal: Applied physics letters


Applied materials today
Journal: Applied materials today


Nanoscale
Journal: Nanoscale


Carbon
Journal: Carbon


Acs applied nano materials
Journal: Acs applied nano materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Thin solid films
Journal: Thin solid films


Scientific reports
Journal: Scientific reports


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Macromolecules
Journal: Macromolecules


Nanoscale
Journal: Nanoscale


Applied physics letters
Journal: Applied physics letters


Database
Journal: Database


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


The journal of chemical physics
Journal: The journal of chemical physics


Inorganic chemistry
Journal: Inorganic chemistry


Materials chemistry and physics
Journal: Materials chemistry and physics


Chemelectrochem
Journal: Chemelectrochem


Scientific reports
Journal: Scientific reports


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Electronic materials
Journal: Electronic materials


Canadian journal of physics 92 (7/8)
Journal: Canadian journal of physics 92 (7/8)


Faraday discussions
Journal: Faraday discussions


Journal of nano research
Journal: Journal of nano research


Ecs journal of solid state science and technology
Journal: Ecs journal of solid state science and technology


Journal of renewable and sustainable energy
Journal: Journal of renewable and sustainable energy


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Science of advanced materials
Journal: Science of advanced materials


Faraday discussions
Journal: Faraday discussions


Photonics north 2013
Journal: Photonics north 2013


Nanotechnology
Journal: Nanotechnology


Journal of applied physics
Journal: Journal of applied physics


Faraday discussions
Journal: Faraday discussions


Materials
Journal: Materials


Nano select
Journal: Nano select


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Ecs journal of solid state science and technology
Journal: Ecs journal of solid state science and technology


Physica a: statistical mechanics and its applications
Journal: Physica a: statistical mechanics and its applications


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


한국광전자학회지 journal of photonic science and technology
Journal: 한국광전자학회지 journal of photonic science and technology


Radiation
Journal: Radiation


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of visualized experiments: jove
Journal: Journal of visualized experiments: jove


Science of advanced materials
Journal: Science of advanced materials


Organic photonics iv
Journal: Organic photonics iv


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced photonics research
Journal: Advanced photonics research


Novel optical materials and applications, jtu1a.
Journal: Novel optical materials and applications


2020 photonics north (pn)
Journal: 2020 photonics north (pn)


2020 photonics north (pn)
Journal: 2020 photonics north (pn)


Chinese optics letters
Journal: Chinese optics letters


Chinese optics letters
Journal: Chinese optics letters


Faraday discussions
Journal: Faraday discussions


Faraday discussions
Journal: Faraday discussions


Journal of catalysis
Journal: Journal of catalysis


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Catalysis today
Journal: Catalysis today


Clinics
Journal: Clinics


Catalysis today
Journal: Catalysis today


Journal of catalysis
Journal: Journal of catalysis


Catalysis communications
Journal: Catalysis communications


Catalysis communications
Journal: Catalysis communications


Catalysis today
Journal: Catalysis today


International journal of hydrogen energy
Journal: International journal of hydrogen energy


Journal of materials science
Journal: Journal of materials science


Journal of molecular catalysis a: chemical 253 (1-2)
Journal: Journal of molecular catalysis a: chemical 253 (1-2)


Applied catalysis a: general
Journal: Applied catalysis a: general


Catalysis today
Journal: Catalysis today


Catalysis today
Journal: Catalysis today


Interações (campo grande)
Journal: Interações (campo grande)


International journal of hydrogen energy
Journal: International journal of hydrogen energy


Appl. catal. b: env
Journal: Appl. catal. b: env


Journal of microwaves, optoelectronics and electromagnetic applications 10 …
Journal: Journal of microwaves


Olhares &trilhas
Journal: Olhares &trilhas


Diamond and related materials
Journal: Diamond and related materials


Journal of telemedicine and telecare 6 (2_suppl)
Journal: Journal of telemedicine and telecare 6 (2_suppl)


Materials research
Journal: Materials research


Ceramics international
Journal: Ceramics international


Inorganic chemistry communications volume 14
Journal: Inorganic chemistry communications volume 14


Matéria (rio de janeiro)
Journal: Matéria (rio de janeiro)


Materia-rio de janeiro
Journal: Materia-rio de janeiro


The faseb journal 29, 754.
Journal: The faseb journal 29


História social da língua nacional
Journal: História social da língua nacional


Intertexto
Journal: Intertexto


Journal of telemedicine and telecare 6 (2_suppl)
Journal: Journal of telemedicine and telecare 6 (2_suppl)


Journal of catalysis
Journal: Journal of catalysis


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Catalysis today
Journal: Catalysis today


Clinics
Journal: Clinics


Catalysis today
Journal: Catalysis today


Journal of catalysis
Journal: Journal of catalysis


Catalysis communications
Journal: Catalysis communications


Catalysis communications
Journal: Catalysis communications


Catalysis today
Journal: Catalysis today


International journal of hydrogen energy
Journal: International journal of hydrogen energy


Journal of materials science
Journal: Journal of materials science


Journal of molecular catalysis a: chemical 253 (1-2)
Journal: Journal of molecular catalysis a: chemical 253 (1-2)


Applied catalysis a: general
Journal: Applied catalysis a: general


Catalysis today
Journal: Catalysis today


Catalysis today
Journal: Catalysis today


Interações (campo grande)
Journal: Interações (campo grande)


International journal of hydrogen energy
Journal: International journal of hydrogen energy


Appl. catal. b: env
Journal: Appl. catal. b: env


Journal of microwaves, optoelectronics and electromagnetic applications 10 …
Journal: Journal of microwaves


Olhares &trilhas
Journal: Olhares &trilhas


Diamond and related materials
Journal: Diamond and related materials


Journal of telemedicine and telecare 6 (2_suppl)
Journal: Journal of telemedicine and telecare 6 (2_suppl)


Materials research
Journal: Materials research


Ceramics international
Journal: Ceramics international


Inorganic chemistry communications volume 14
Journal: Inorganic chemistry communications volume 14


Matéria (rio de janeiro)
Journal: Matéria (rio de janeiro)


Materia-rio de janeiro
Journal: Materia-rio de janeiro


The faseb journal 29, 754.
Journal: The faseb journal 29



Coatings
Journal: Coatings


Acs applied nano materials
Journal: Acs applied nano materials


Key engineering materials
Journal: Key engineering materials


Optics express
Journal: Optics express


Zeitschrift für naturforschung b
Journal: Zeitschrift für naturforschung b


Inorganic chemistry
Journal: Inorganic chemistry


Zeitschrift für naturforschung b
Journal: Zeitschrift für naturforschung b


Clinical pharmacology and pharmacokinetics
Journal: Clinical pharmacology and pharmacokinetics


Optical properties of semiconductor nanostructures
Journal: Optical properties of semiconductor nanostructures


Revista romana de materiale
Journal: Revista romana de materiale


Zeitschrift für naturforschung b
Journal: Zeitschrift für naturforschung b


Synthetic metals 103 (1-3)
Journal: Synthetic metals 103 (1-3)


Microcrystalline and nanocrystalline semiconductors
Journal: Microcrystalline and nanocrystalline semiconductors


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of non-crystalline solids 347 (1-3)
Journal: Journal of non-crystalline solids 347 (1-3)


Journal of non-crystalline solids
Journal: Journal of non-crystalline solids


Solid state communications
Journal: Solid state communications


Advanced materials for optics and electronics
Journal: Advanced materials for optics and electronics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Synthetic metals
Journal: Synthetic metals


Journal of materials chemistry
Journal: Journal of materials chemistry


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Zeitschrift für naturforschung b
Journal: Zeitschrift für naturforschung b


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Applied physics letters
Journal: Applied physics letters


Nanoscale
Journal: Nanoscale


Acs omega
Journal: Acs omega


Journal of physics and chemistry of solids
Journal: Journal of physics and chemistry of solids


Monatshefte für chemie/chemical monthly
Journal: Monatshefte für chemie/chemical monthly


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Solid state sciences
Journal: Solid state sciences


The journal of physical chemistry b
Journal: The journal of physical chemistry b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Applied materials today
Journal: Applied materials today


Polyhedron
Journal: Polyhedron


Polyhedron
Journal: Polyhedron


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Microporous and mesoporous materials
Journal: Microporous and mesoporous materials


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Smart materials in medicine
Journal: Smart materials in medicine


International journal of modern physics b 15 (28n30)
Journal: International journal of modern physics b 15 (28n30)


Applied clay science
Journal: Applied clay science


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Thin solid films
Journal: Thin solid films


Journal of physics and chemistry of solids
Journal: Journal of physics and chemistry of solids


Materials chemistry frontiers
Journal: Materials chemistry frontiers


Applied surface science
Journal: Applied surface science


Advanced materials for optics and electronics
Journal: Advanced materials for optics and electronics


Journal of materials science &technology
Journal: Journal of materials science &technology


Applied materials today
Journal: Applied materials today


Journal of polymer science part b: polymer physics
Journal: Journal of polymer science part b: polymer physics


Journal of electronic materials
Journal: Journal of electronic materials


Journal of luminescence
Journal: Journal of luminescence


Journal of sol-gel science and technology
Journal: Journal of sol-gel science and technology


Microporous and mesoporous materials
Journal: Microporous and mesoporous materials


Journal of optoelectronics and advanced materials
Journal: Journal of optoelectronics and advanced materials


Zeitschrift für naturforschung b
Journal: Zeitschrift für naturforschung b


Journal of sol-gel science and technology
Journal: Journal of sol-gel science and technology


Applied physics a
Journal: Applied physics a


Zeitschrift für naturforschung b
Journal: Zeitschrift für naturforschung b


Coatings
Journal: Coatings


Acs applied nano materials
Journal: Acs applied nano materials


Key engineering materials
Journal: Key engineering materials


Optics express
Journal: Optics express


Zeitschrift für naturforschung b
Journal: Zeitschrift für naturforschung b


Inorganic chemistry
Journal: Inorganic chemistry


Zeitschrift für naturforschung b
Journal: Zeitschrift für naturforschung b


Clinical pharmacology and pharmacokinetics
Journal: Clinical pharmacology and pharmacokinetics


Optical properties of semiconductor nanostructures
Journal: Optical properties of semiconductor nanostructures


Revista romana de materiale
Journal: Revista romana de materiale


Zeitschrift für naturforschung b
Journal: Zeitschrift für naturforschung b


Synthetic metals 103 (1-3)
Journal: Synthetic metals 103 (1-3)


Microcrystalline and nanocrystalline semiconductors
Journal: Microcrystalline and nanocrystalline semiconductors


Chemical reviews
Journal: Chemical reviews


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Chemical communications
Journal: Chemical communications


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Nature communications
Journal: Nature communications


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced materials
Journal: Advanced materials


Chemistry–a european journal
Journal: Chemistry–a european journal


Acs nano
Journal: Acs nano


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced materials
Journal: Advanced materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature chemistry
Journal: Nature chemistry


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Chemical communications
Journal: Chemical communications


Advanced functional materials
Journal: Advanced functional materials


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Dalton transactions
Journal: Dalton transactions


Crystal growth &design
Journal: Crystal growth &design


Nature communications
Journal: Nature communications


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Crystengcomm
Journal: Crystengcomm


Iucrj
Journal: Iucrj


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Inorganic chemistry
Journal: Inorganic chemistry


Crystal growth &design
Journal: Crystal growth &design


Crystengcomm
Journal: Crystengcomm


Crystal growth &design
Journal: Crystal growth &design


Inorganic chemistry
Journal: Inorganic chemistry


Crystal growth &design
Journal: Crystal growth &design


Inorganic chemistry
Journal: Inorganic chemistry


Crystal growth &design
Journal: Crystal growth &design


Inorganic chemistry
Journal: Inorganic chemistry


Crystengcomm
Journal: Crystengcomm


Crystal growth &design
Journal: Crystal growth &design


Inorganic chemistry
Journal: Inorganic chemistry


Crystengcomm
Journal: Crystengcomm


Crystal growth &design
Journal: Crystal growth &design


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Chemical science
Journal: Chemical science


Dalton transactions
Journal: Dalton transactions


Nature communications
Journal: Nature communications


Iucrj
Journal: Iucrj


Crystal growth &design
Journal: Crystal growth &design


Inorganic chemistry
Journal: Inorganic chemistry


Crystengcomm
Journal: Crystengcomm


Inorganic chemistry
Journal: Inorganic chemistry


Inorganic chemistry
Journal: Inorganic chemistry


Analyst
Journal: Analyst


Crystengcomm
Journal: Crystengcomm


Inorganic chemistry communications
Journal: Inorganic chemistry communications


Chemical communications
Journal: Chemical communications


Crystal growth &design
Journal: Crystal growth &design


Crystengcomm
Journal: Crystengcomm


Crystal growth &design
Journal: Crystal growth &design


Australian journal of chemistry
Journal: Australian journal of chemistry


Crystengcomm
Journal: Crystengcomm


Bulletin of the korean chemical society
Journal: Bulletin of the korean chemical society


Iucrj
Journal: Iucrj


European journal of inorganic chemistry
Journal: European journal of inorganic chemistry


Rsc advances
Journal: Rsc advances


Inorganic chemistry
Journal: Inorganic chemistry


Dalton transactions
Journal: Dalton transactions


Inorganica chimica acta
Journal: Inorganica chimica acta


Iucrj
Journal: Iucrj


Supramolecular chemistry
Journal: Supramolecular chemistry


Iucrj
Journal: Iucrj


Inorganic chemistry
Journal: Inorganic chemistry


Australian journal of chemistry
Journal: Australian journal of chemistry


Inorganic chemistry
Journal: Inorganic chemistry


Inorganic chemistry
Journal: Inorganic chemistry


Acs omega
Journal: Acs omega


Chemical communications
Journal: Chemical communications


Frontiers in optics, ftu5f.
Journal: Frontiers in optics


Chemical communications
Journal: Chemical communications


Chemical reviews
Journal: Chemical reviews


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Chemical communications
Journal: Chemical communications


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Nature communications
Journal: Nature communications


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced materials
Journal: Advanced materials


Chemistry–a european journal
Journal: Chemistry–a european journal


Acs nano
Journal: Acs nano


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced materials
Journal: Advanced materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature chemistry
Journal: Nature chemistry


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Chemical communications
Journal: Chemical communications


Advanced functional materials
Journal: Advanced functional materials


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Dalton transactions
Journal: Dalton transactions


Crystal growth &design
Journal: Crystal growth &design


Nature communications
Journal: Nature communications


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Crystengcomm
Journal: Crystengcomm


Iucrj
Journal: Iucrj


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Inorganic chemistry
Journal: Inorganic chemistry


Crystal growth &design
Journal: Crystal growth &design


Crystengcomm
Journal: Crystengcomm


Crystal growth &design
Journal: Crystal growth &design


Inorganic chemistry
Journal: Inorganic chemistry


Crystal growth &design
Journal: Crystal growth &design


Inorganic chemistry
Journal: Inorganic chemistry


Crystal growth &design
Journal: Crystal growth &design


Inorganic chemistry
Journal: Inorganic chemistry


Crystengcomm
Journal: Crystengcomm


Crystal growth &design
Journal: Crystal growth &design


Inorganic chemistry
Journal: Inorganic chemistry


Crystengcomm
Journal: Crystengcomm


Crystal growth &design
Journal: Crystal growth &design


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Chemical science
Journal: Chemical science


Dalton transactions
Journal: Dalton transactions


Nature communications
Journal: Nature communications


Iucrj
Journal: Iucrj


Crystal growth &design
Journal: Crystal growth &design


Inorganic chemistry
Journal: Inorganic chemistry


Crystengcomm
Journal: Crystengcomm


Inorganic chemistry
Journal: Inorganic chemistry


Inorganic chemistry
Journal: Inorganic chemistry


Analyst
Journal: Analyst


Crystengcomm
Journal: Crystengcomm


Inorganic chemistry communications
Journal: Inorganic chemistry communications


Chemical communications
Journal: Chemical communications


Crystal growth &design
Journal: Crystal growth &design


Crystengcomm
Journal: Crystengcomm


Crystal growth &design
Journal: Crystal growth &design


Australian journal of chemistry
Journal: Australian journal of chemistry


Crystengcomm
Journal: Crystengcomm


Bulletin of the korean chemical society
Journal: Bulletin of the korean chemical society


Iucrj
Journal: Iucrj


European journal of inorganic chemistry
Journal: European journal of inorganic chemistry


Rsc advances
Journal: Rsc advances


Inorganic chemistry
Journal: Inorganic chemistry


Dalton transactions
Journal: Dalton transactions


Inorganica chimica acta
Journal: Inorganica chimica acta


Iucrj
Journal: Iucrj


Supramolecular chemistry
Journal: Supramolecular chemistry


Iucrj
Journal: Iucrj


Inorganic chemistry
Journal: Inorganic chemistry


Australian journal of chemistry
Journal: Australian journal of chemistry


Inorganic chemistry
Journal: Inorganic chemistry


Inorganic chemistry
Journal: Inorganic chemistry


Acs omega
Journal: Acs omega


Chemical communications
Journal: Chemical communications


Frontiers in optics, ftu5f.
Journal: Frontiers in optics


Chemical communications
Journal: Chemical communications


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Solid state communications
Journal: Solid state communications


Journal of applied physics
Journal: Journal of applied physics


Journal of crystal growth 258 (3-4)
Journal: Journal of crystal growth 258 (3-4)


Applied physics letters
Journal: Applied physics letters


Journal of crystal growth 270 (1-2)
Journal: Journal of crystal growth 270 (1-2)


Journal of applied physics
Journal: Journal of applied physics


Applied surface science
Journal: Applied surface science


Scientific reports
Journal: Scientific reports


Journal of applied physics
Journal: Journal of applied physics


Aip advances
Journal: Aip advances


Applied surface science
Journal: Applied surface science


Organic electronics
Journal: Organic electronics


Japanese journal of applied physics 47 (1s)
Journal: Japanese journal of applied physics 47 (1s)


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Japanese journal of applied physics 47 (1s)
Journal: Japanese journal of applied physics 47 (1s)


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Journal of applied physics
Journal: Journal of applied physics


Applied surface science
Journal: Applied surface science


Journal of the korean physical society
Journal: Journal of the korean physical society


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Hyperfine interactions
Journal: Hyperfine interactions


Bulletin of the korean chemical society
Journal: Bulletin of the korean chemical society


Current applied physics
Journal: Current applied physics


Journal of the korean physical society
Journal: Journal of the korean physical society


Advanced materials interfaces
Journal: Advanced materials interfaces


Applied physics letters
Journal: Applied physics letters


Journal of electroceramics
Journal: Journal of electroceramics


Physica status solidi (b)
Journal: Physica status solidi (b)


Journal of the korean physical society
Journal: Journal of the korean physical society


Applied surface science
Journal: Applied surface science


Applied physics letters
Journal: Applied physics letters


Journal of materials research
Journal: Journal of materials research


Nanoscale
Journal: Nanoscale


Journal of magnetics
Journal: Journal of magnetics


Ieee transactions on magnetics
Journal: Ieee transactions on magnetics


Journal of applied physics
Journal: Journal of applied physics


Applied physics letters
Journal: Applied physics letters


Journal of applied physics
Journal: Journal of applied physics


Scientific reports
Journal: Scientific reports


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Current applied physics
Journal: Current applied physics


Journal of the korean vacuum society
Journal: Journal of the korean vacuum society


한국세라믹학회지
Journal: 한국세라믹학회지


Journal of applied physics
Journal: Journal of applied physics


Acs applied electronic materials
Journal: Acs applied electronic materials


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


이학논집
Journal: 이학논집


Journal of the korean magnetics society
Journal: Journal of the korean magnetics society


Journal of the korean magnetics society
Journal: Journal of the korean magnetics society


Advanced materials interfaces
Journal: Advanced materials interfaces


한국자기학회 학술연구발표회 논문개요집
Journal: 한국자기학회 학술연구발표회 논문개요집


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Journal of the korean ceramic society
Journal: Journal of the korean ceramic society


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Journal of the korean magnetics society
Journal: Journal of the korean magnetics society


Journal of the korean magnetics society
Journal: Journal of the korean magnetics society


Journal of magnetics
Journal: Journal of magnetics


Journal of the korean magnetics society
Journal: Journal of the korean magnetics society


Journal of the korean magnetics society
Journal: Journal of the korean magnetics society


Journal of the korean magnetics society
Journal: Journal of the korean magnetics society


Journal of the korean magnetics society
Journal: Journal of the korean magnetics society


한국자기학회 학술연구발표회 논문개요집
Journal: 한국자기학회 학술연구발표회 논문개요집


한국자기학회 학술연구발표회 논문개요집
Journal: 한국자기학회 학술연구발표회 논문개요집


한국자기학회 학술연구발표회 논문개요집
Journal: 한국자기학회 학술연구발표회 논문개요집


Journal of the korean magnetics society
Journal: Journal of the korean magnetics society


한국자기학회 학술연구발표회 논문개요집
Journal: 한국자기학회 학술연구발표회 논문개요집


한국자기학회 학술연구발표회 논문개요집
Journal: 한국자기학회 학술연구발표회 논문개요집


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Solid state communications
Journal: Solid state communications


Journal of applied physics
Journal: Journal of applied physics


Journal of crystal growth 258 (3-4)
Journal: Journal of crystal growth 258 (3-4)


Applied physics letters
Journal: Applied physics letters


Journal of crystal growth 270 (1-2)
Journal: Journal of crystal growth 270 (1-2)


Journal of applied physics
Journal: Journal of applied physics


Applied surface science
Journal: Applied surface science


Scientific reports
Journal: Scientific reports


Journal of applied physics

Journal of power sources
Journal: Journal of power sources


Cell reports physical science
Journal: Cell reports physical science


Rsc advances
Journal: Rsc advances


Energy technology
Journal: Energy technology


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of organometallic chemistry
Journal: Journal of organometallic chemistry


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Applied thermal engineering
Journal: Applied thermal engineering


Tetrahedron
Journal: Tetrahedron


Journal of power sources
Journal: Journal of power sources


Journal of applied physics
Journal: Journal of applied physics


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced energy materials
Journal: Advanced energy materials


Radiation physics and chemistry
Journal: Radiation physics and chemistry


Electrochimica acta
Journal: Electrochimica acta


Solar energy
Journal: Solar energy


Materials
Journal: Materials


Australian journal of chemistry
Journal: Australian journal of chemistry


Chemical communications
Journal: Chemical communications


Rsc advances
Journal: Rsc advances


Chempluschem
Journal: Chempluschem


Photochemical &photobiological sciences
Journal: Photochemical &photobiological sciences


Solar rrl
Journal: Solar rrl


Advanced photonics research
Journal: Advanced photonics research


Materials letters
Journal: Materials letters


Journal of chemical crystallography
Journal: Journal of chemical crystallography


Journal of colloid and interface science
Journal: Journal of colloid and interface science


Advanced functional materials
Journal: Advanced functional materials


Small
Journal: Small


Small
Journal: Small


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Solid state ionics
Journal: Solid state ionics


Acs applied energy materials
Journal: Acs applied energy materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Chemical engineering journal
Journal: Chemical engineering journal


Nature communications
Journal: Nature communications


Small methods
Journal: Small methods


Advanced functional materials
Journal: Advanced functional materials


Advanced energy materials
Journal: Advanced energy materials


Solid state ionics
Journal: Solid state ionics


Chemistry of materials
Journal: Chemistry of materials


Nano energy
Journal: Nano energy


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of physics: energy
Journal: Journal of physics: energy


Advanced energy materials
Journal: Advanced energy materials


Open ceramics
Journal: Open ceramics


Acta crystallographica section e: structure reports online
Journal: Acta crystallographica section e: structure reports online


European journal of mineralogy
Journal: European journal of mineralogy


Acta crystallographica a-foundation and advances 66, s311-s
Journal: Acta crystallographica a-foundation and advances 66


Physical review b
Journal: Physical review b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acta crystallographica section e: structure reports online
Journal: Acta crystallographica section e: structure reports online


Materials advances
Journal: Materials advances


Journal of hazardous materials
Journal: Journal of hazardous materials


Acta crystallographica section b: structural science, crystal engineering …
Journal: Acta crystallographica section b: structural science


Journal of large-scale research facilities jlsrf 6, a139-a
Journal: Journal of large-scale research facilities jlsrf 6


Journal of the physical society of japan
Journal: Journal of the physical society of japan


Chemelectrochem
Journal: Chemelectrochem


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Applied physics a 74, s1098-s
Journal: Applied physics a 74


Journal of materials science &technology
Journal: Journal of materials science &technology


Acta cryst 67, c681-c
Journal: Acta cryst 67


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acta crystallographica a-foundation and advances 77, c758-c
Journal: Acta crystallographica a-foundation and advances 77


Acta crystallographica a-foundation and advances 77, c1064-c
Journal: Acta crystallographica a-foundation and advances 77


Open ceramics
Journal: Open ceramics


Acta crystallographica a-foundation and advances 75, e317-
Journal: Acta crystallographica a-foundation and advances 75


Acta cryst
Journal: Acta cryst


Acta crystallographica a-foundation and advances 74, e321-
Journal: Acta crystallographica a-foundation and advances 74


Materials science and condensed matter physics
Journal: Materials science and condensed matter physics


Acta cryst. a 73, c283-c
Journal: Acta cryst. a 73


Acta cryst 72, s
Journal: Acta cryst 72


Acta crystallographica a-foundation and advances 67, c799-c
Journal: Acta crystallographica a-foundation and advances 67


Acta cryst 67, c799-c
Journal: Acta cryst 67


Diffusion fundamentals
Journal: Diffusion fundamentals


Parameters 536, 12.
Journal: Parameters 536


Verhandlungen der deutschen physikalischen gesellschaft
Journal: Verhandlungen der deutschen physikalischen gesellschaft


Acta crystallographica a-foundation and advances 58, c187-c
Journal: Acta crystallographica a-foundation and advances 58


Berlin, techn. univ., diss.
Journal: Berlin


Solid state ionics
Journal: Solid state ionics


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Solid state ionics
Journal: Solid state ionics


Acs applied energy materials
Journal: Acs applied energy materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Chemical engineering journal
Journal: Chemical engineering journal


Nature communications
Journal: Nature communications


Small methods
Journal: Small methods


Advanced functional materials
Journal: Advanced functional materials


Advanced energy materials
Journal: Advanced energy materials


Solid state ionics
Journal: Solid state ionics


Chemistry of materials
Journal: Chemistry of materials


Nano energy
Journal: Nano energy


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of physics: energy
Journal: Journal of physics: energy


Advanced energy materials
Journal: Advanced energy materials


Open ceramics
Journal: Open ceramics


Acta crystallographica section e: structure reports online
Journal: Acta crystallographica section e: structure reports online


European journal of mineralogy
Journal: European journal of mineralogy


Acta crystallographica a-foundation and advances 66, s311-s
Journal: Acta crystallographica a-foundation and advances 66


Physical review b
Journal: Physical review b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acta crystallographica section e: structure reports online
Journal: Acta crystallographica section e: structure reports online


Materials advances
Journal: Materials advances


Journal of hazardous materials
Journal: Journal of hazardous materials


Acta crystallographica section b: structural science, crystal engineering …
Journal: Acta crystallographica section b: structural science


Journal of large-scale research facilities jlsrf 6, a139-a
Journal: Journal of large-scale research facilities jlsrf 6


Journal of the physical society of japan
Journal: Journal of the physical society of japan


Chemelectrochem
Journal: Chemelectrochem


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Applied physics a 74, s1098-s
Journal: Applied physics a 74


Journal of materials science &technology
Journal: Journal of materials science &technology


Acta cryst 67, c681-c
Journal: Acta cryst 67


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acta crystallographica a-foundation and advances 77, c758-c
Journal: Acta crystallographica a-foundation and advances 77


Acta crystallographica a-foundation and advances 77, c1064-c
Journal: Acta crystallographica a-foundation and advances 77


Open ceramics
Journal: Open ceramics


Acta crystallographica a-foundation and advances 75, e317-
Journal: Acta crystallographica a-foundation and advances 75


Acta cryst
Journal: Acta cryst


Acta crystallographica a-foundation and advances 74, e321-
Journal: Acta crystallographica a-foundation and advances 74


Materials science and condensed matter physics
Journal: Materials science and condensed matter physics


Acta cryst. a 73, c283-c
Journal: Acta cryst. a 73


Acta cryst 72, s
Journal: Acta cryst 72


Acta crystallographica a-foundation and advances 67, c799-c
Journal: Acta crystallographica a-foundation and advances 67


Acta cryst 67, c799-c
Journal: Acta cryst 67


Diffusion fundamentals
Journal: Diffusion fundamentals


Parameters 536, 12.
Journal: Parameters 536


Verhandlungen der deutschen physikalischen gesellschaft
Journal: Verhandlungen der deutschen physikalischen gesellschaft


Acta crystallographica a-foundation and advances 58, c187-c
Journal: Acta crystallographica a-foundation and advances 58


Berlin, techn. univ., diss.
Journal: Berlin


Solid state ionics
Journal: Solid state ionics


Energy &environmental science
Journal: Energy &environmental science


Nature photonics
Journal: Nature photonics


Nano letters
Journal: Nano letters


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Small
Journal: Small


Physical review b
Journal: Physical review b


Nano letters
Journal: Nano letters


Chemistry of materials
Journal: Chemistry of materials


Acs nano
Journal: Acs nano


Chemistry of materials
Journal: Chemistry of materials


Nano letters
Journal: Nano letters


Chemistry of materials
Journal: Chemistry of materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Nano letters
Journal: Nano letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemistry of materials
Journal: Chemistry of materials


Advanced science
Journal: Advanced science


Physical review b
Journal: Physical review b


Acs nano
Journal: Acs nano


Small
Journal: Small


Acs photonics
Journal: Acs photonics


Chemical science
Journal: Chemical science


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Nano letters
Journal: Nano letters


Acs applied electronic materials
Journal: Acs applied electronic materials


Acs applied energy materials
Journal: Acs applied energy materials


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nano letters
Journal: Nano letters


Solar rrl
Journal: Solar rrl


Science china chemistry
Journal: Science china chemistry


Materials chemistry frontiers
Journal: Materials chemistry frontiers


Acs photonics
Journal: Acs photonics


Solar rrl
Journal: Solar rrl


Chemphyschem
Journal: Chemphyschem


Chemsuschem
Journal: Chemsuschem


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Solar rrl
Journal: Solar rrl


Rsc advances
Journal: Rsc advances


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of physical chemistry c
Journal: Journal of physical chemistry c


European journal of inorganic chemistry
Journal: European journal of inorganic chemistry


Acs energy letters
Journal: Acs energy letters


Advanced materials interfaces
Journal: Advanced materials interfaces


Acs applied nano materials
Journal: Acs applied nano materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs sensors
Journal: Acs sensors


Advanced functional materials
Journal: Advanced functional materials


Advanced optical materials
Journal: Advanced optical materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced photonics research
Journal: Advanced photonics research


Acs photonics
Journal: Acs photonics


Inorganic chemistry
Journal: Inorganic chemistry


Nanoscale
Journal: Nanoscale


Physica status solidi c
Journal: Physica status solidi c


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Apl materials
Journal: Apl materials


Journal of chemical physics
Journal: Journal of chemical physics


Chemistry of materials
Journal: Chemistry of materials


Acs energy letters
Journal: Acs energy letters


Advanced optical materials
Journal: Advanced optical materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Nano letters
Journal: Nano letters


Nano letters
Journal: Nano letters


Science
Journal: Science


Nature communications
Journal: Nature communications


Nano letters
Journal: Nano letters


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs nano
Journal: Acs nano


Acs nano
Journal: Acs nano


Energy &environmental science
Journal: Energy &environmental science


Acs applied nano materials
Journal: Acs applied nano materials


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Acs nano
Journal: Acs nano


Acs nano
Journal: Acs nano


Journal of the american chemical society
Journal: Journal of the american chemical society


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Acs nano
Journal: Acs nano


Chemistry of materials
Journal: Chemistry of materials


Green chemistry
Journal: Green chemistry


Acs nano
Journal: Acs nano


Small
Journal: Small


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs nano
Journal: Acs nano


Nano letters
Journal: Nano letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs central science
Journal: Acs central science


Acs energy letters
Journal: Acs energy letters


Applied catalysis a: general
Journal: Applied catalysis a: general


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Acs nano
Journal: Acs nano


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Acs photonics
Journal: Acs photonics


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Applied physics letters
Journal: Applied physics letters


Advanced energy materials
Journal: Advanced energy materials


Chemphyschem
Journal: Chemphyschem


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Chemical science
Journal: Chemical science


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced materials
Journal: Advanced materials


New biotechnology, s72-s
Journal: New biotechnology


Advanced materials
Journal: Advanced materials


Organic photonics and photovoltaics
Journal: Organic photonics and photovoltaics


Nature materials
Journal: Nature materials


Icest
Journal: Icest


Advanced functional materials
Journal: Advanced functional materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Scientific reports
Journal: Scientific reports


Acs biomaterials science &engineering
Journal: Acs biomaterials science &engineering


Chemical communications
Journal: Chemical communications


Nanoscale
Journal: Nanoscale


2d materials
Journal: 2d materials


Journal of colloid and interface science
Journal: Journal of colloid and interface science


Small
Journal: Small


Small
Journal: Small


Nanomaterials
Journal: Nanomaterials


Nanoscale
Journal: Nanoscale


Nanomedicine: nanotechnology, biology and medicine
Journal: Nanomedicine: nanotechnology


Advanced optical materials
Journal: Advanced optical materials


Nanoscale
Journal: Nanoscale


Nanotechnology
Journal: Nanotechnology


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Physical review b
Journal: Physical review b


Ecs transactions
Journal: Ecs transactions


Journal of nanoparticle research
Journal: Journal of nanoparticle research


Nanoscale research letters
Journal: Nanoscale research letters


Acs biomaterials science &engineering
Journal: Acs biomaterials science &engineering


Pharmaceutics
Journal: Pharmaceutics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Plos one
Journal: Plos one


Acs applied nano materials
Journal: Acs applied nano materials


Royal society open science
Journal: Royal society open science


Canadian journal of chemistry
Journal: Canadian journal of chemistry


Nanoscale
Journal: Nanoscale


Acs biomaterials science &engineering
Journal: Acs biomaterials science &engineering


Journal of coordination chemistry
Journal: Journal of coordination chemistry


Nanoscale
Journal: Nanoscale


Journal of nanomedicine research
Journal: Journal of nanomedicine research


Nanomaterials
Journal: Nanomaterials


Ecs transactions
Journal: Ecs transactions


Advanced materials interfaces
Journal: Advanced materials interfaces


Ecs transactions
Journal: Ecs transactions


Advanced functional materials
Journal: Advanced functional materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Scientific reports
Journal: Scientific reports


Acs biomaterials science &engineering
Journal: Acs biomaterials science &engineering


Chemical communications
Journal: Chemical communications


Nanoscale
Journal: Nanoscale


2d materials
Journal: 2d materials


Journal of colloid and interface science
Journal: Journal of colloid and interface science


Small
Journal: Small


Small
Journal: Small


Nanomaterials
Journal: Nanomaterials


Nanoscale
Journal: Nanoscale


Nanomedicine: nanotechnology, biology and medicine
Journal: Nanomedicine: nanotechnology


Advanced optical materials
Journal: Advanced optical materials


Nanoscale
Journal: Nanoscale


Nanotechnology
Journal: Nanotechnology


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Physical review b
Journal: Physical review b


Ecs transactions

Chemsuschem
Journal: Chemsuschem


Acs catalysis
Journal: Acs catalysis


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Applied physics letters
Journal: Applied physics letters


Advanced theory and simulations
Journal: Advanced theory and simulations


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Acta materialia
Journal: Acta materialia


Chemistry of materials
Journal: Chemistry of materials


Chemical physics
Journal: Chemical physics


Energy storage materials
Journal: Energy storage materials


Small
Journal: Small


Apl materials
Journal: Apl materials


Energy storage materials
Journal: Energy storage materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs catalysis
Journal: Acs catalysis


Journal of applied physics
Journal: Journal of applied physics


Applied physics reviews
Journal: Applied physics reviews


Applied physics letters
Journal: Applied physics letters


Nanoscale
Journal: Nanoscale


Journal of catalysis
Journal: Journal of catalysis


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of applied physics
Journal: Journal of applied physics


Advanced sustainable systems
Journal: Advanced sustainable systems


Particle &particle systems characterization
Journal: Particle &particle systems characterization


Materials advances
Journal: Materials advances


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review b
Journal: Physical review b


Advanced theory and simulations
Journal: Advanced theory and simulations


Advanced materials
Journal: Advanced materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Current opinion in electrochemistry
Journal: Current opinion in electrochemistry


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Physical review b
Journal: Physical review b


Europhysics letters
Journal: Europhysics letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Small
Journal: Small


Advanced theory and simulations
Journal: Advanced theory and simulations


Advanced theory and simulations
Journal: Advanced theory and simulations


Advanced theory and simulations
Journal: Advanced theory and simulations


Small
Journal: Small


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Optics express
Journal: Optics express


Nanoscale research letters
Journal: Nanoscale research letters


Acs photonics
Journal: Acs photonics


Applied materials today
Journal: Applied materials today


Materials letters
Journal: Materials letters


Optical materials
Journal: Optical materials


Advanced functional materials
Journal: Advanced functional materials


Nanoscale
Journal: Nanoscale


Chinese physics b
Journal: Chinese physics b


Nano-micro letters
Journal: Nano-micro letters


Ieee photonics technology letters
Journal: Ieee photonics technology letters


Solid-state electronics
Journal: Solid-state electronics


Energy
Journal: Energy


Chemical engineering journal
Journal: Chemical engineering journal


Ieee photonics journal
Journal: Ieee photonics journal


Journal of power sources
Journal: Journal of power sources


Acs photonics
Journal: Acs photonics


Solar energy
Journal: Solar energy


Photonics research
Journal: Photonics research


Acs applied nano materials
Journal: Acs applied nano materials


Optics express
Journal: Optics express


Chinese physics letters
Journal: Chinese physics letters


Applied optics
Journal: Applied optics


Energy
Journal: Energy


Applied optics
Journal: Applied optics


Applied physics letters
Journal: Applied physics letters


Materials letters
Journal: Materials letters


Chemical engineering journal
Journal: Chemical engineering journal


Acs applied energy materials
Journal: Acs applied energy materials


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Scientific reports
Journal: Scientific reports


Optics express
Journal: Optics express


Physica e: low-dimensional systems and nanostructures
Journal: Physica e: low-dimensional systems and nanostructures


Applied optics
Journal: Applied optics


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Ieee access
Journal: Ieee access


Applied optics
Journal: Applied optics


Functional materials letters
Journal: Functional materials letters


Annalen der physik
Journal: Annalen der physik


Applied optics
Journal: Applied optics


Quantum electronics
Journal: Quantum electronics


Chinese physics letters
Journal: Chinese physics letters


Solar energy
Journal: Solar energy


Advanced functional materials
Journal: Advanced functional materials


Applied optics
Journal: Applied optics


Applied optics
Journal: Applied optics


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Communications physics
Journal: Communications physics


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Frontiers in physics
Journal: Frontiers in physics


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Nanoscale research letters
Journal: Nanoscale research letters


Journal of power sources
Journal: Journal of power sources


Acs photonics
Journal: Acs photonics


Solar energy
Journal: Solar energy


Applied optics
Journal: Applied optics


Optics express
Journal: Optics express


Applied physics letters
Journal: Applied physics letters


Optical materials express
Journal: Optical materials express


Annalen der physik
Journal: Annalen der physik


Bandaoti jishu(semiconductor technology)
Journal: Bandaoti jishu(semiconductor technology)


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Optics express
Journal: Optics express


Nanoscale research letters
Journal: Nanoscale research letters


Acs photonics
Journal: Acs photonics


Applied materials today
Journal: Applied materials today


Materials letters
Journal: Materials letters


Optical materials
Journal: Optical materials


Advanced functional materials
Journal: Advanced functional materials


Nanoscale
Journal: Nanoscale


Chinese physics b
Journal: Chinese physics b


Nano-micro letters
Journal: Nano-micro letters


Ieee photonics technology letters
Journal: Ieee photonics technology letters


Solid-state electronics
Journal: Solid-state electronics


Energy
Journal: Energy


Chemical engineering journal
Journal: Chemical engineering journal


Ieee photonics journal
Journal: Ieee photonics journal


Journal of power sources
Journal: Journal of power sources


Acs photonics
Journal: Acs photonics


Solar energy
Journal: Solar energy


Photonics research
Journal: Photonics research


Acs applied nano materials
Journal: Acs applied nano materials


Optics express
Journal: Optics express


Chinese physics letters
Journal: Chinese physics letters


Applied optics
Journal: Applied optics


Energy
Journal: Energy


Applied optics
Journal: Applied optics


Applied physics letters
Journal: Applied physics letters


Materials letters
Journal: Materials letters


Chemical engineering journal
Journal: Chemical engineering journal


Acs applied energy materials
Journal: Acs applied energy materials


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Scientific reports
Journal: Scientific reports


Optics express
Journal: Optics express


Physica e: low-dimensional systems and nanostructures
Journal: Physica e: low-dimensional systems and nanostructures


Applied optics
Journal: Applied optics


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Ieee access
Journal: Ieee access


Applied optics
Journal: Applied optics


Functional materials letters
Journal: Functional materials letters


Annalen der physik
Journal: Annalen der physik


Applied optics
Journal: Applied optics


Quantum electronics
Journal: Quantum electronics


Chinese physics letters
Journal: Chinese physics letters


Solar energy
Journal: Solar energy


Advanced functional materials
Journal: Advanced functional materials


Applied optics
Journal: Applied optics


Applied optics
Journal: Applied optics


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Communications physics
Journal: Communications physics


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Frontiers in physics
Journal: Frontiers in physics


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Nanoscale research letters
Journal: Nanoscale research letters


Journal of power sources
Journal: Journal of power sources


Acs photonics
Journal: Acs photonics


Solar energy
Journal: Solar energy


Applied optics
Journal: Applied optics


Optics express
Journal: Optics express


Applied physics letters
Journal: Applied physics letters


Optical materials express
Journal: Optical materials express


Annalen der physik
Journal: Annalen der physik


Bandaoti jishu(semiconductor technology)
Journal: Bandaoti jishu(semiconductor technology)


Materials today
Journal: Materials today


Journal of materials chemistry
Journal: Journal of materials chemistry


Advanced functional materials
Journal: Advanced functional materials


Advanced materials
Journal: Advanced materials


Chemistry of materials
Journal: Chemistry of materials


Inorganic chemistry
Journal: Inorganic chemistry


Acs photonics
Journal: Acs photonics


Journal of the american chemical society
Journal: Journal of the american chemical society


Nano letters
Journal: Nano letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Advanced energy materials
Journal: Advanced energy materials


Chemistry of materials
Journal: Chemistry of materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of materials chemistry
Journal: Journal of materials chemistry


Chemistry-a european journal
Journal: Chemistry-a european journal


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Dalton transactions
Journal: Dalton transactions


Advanced energy materials
Journal: Advanced energy materials


Advanced optical materials
Journal: Advanced optical materials


Reports on progress in physics
Journal: Reports on progress in physics


Nano letters
Journal: Nano letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Dalton transactions
Journal: Dalton transactions


Acs photonics
Journal: Acs photonics


Advanced materials technologies
Journal: Advanced materials technologies


Dalton transactions
Journal: Dalton transactions


Journal of materials chemistry
Journal: Journal of materials chemistry


Journal of the society for information display
Journal: Journal of the society for information display


Nano letters
Journal: Nano letters


Ieee transactions on applied superconductivity
Journal: Ieee transactions on applied superconductivity


Advanced optical materials
Journal: Advanced optical materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Crystal growth &design
Journal: Crystal growth &design


Advanced optical materials
Journal: Advanced optical materials


Advanced optical materials
Journal: Advanced optical materials


Crystal growth &design
Journal: Crystal growth &design


Advanced functional materials
Journal: Advanced functional materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Organic electronics
Journal: Organic electronics


Journal of the society for information display
Journal: Journal of the society for information display


Dalton transactions
Journal: Dalton transactions


Journal of nanoscience and nanotechnology
Journal: Journal of nanoscience and nanotechnology


Flexible and printed electronics
Journal: Flexible and printed electronics


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Beilstein journal of organic chemistry
Journal: Beilstein journal of organic chemistry


Advanced optical materials
Journal: Advanced optical materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Advanced materials
Journal: Advanced materials


Advanced optical materials
Journal: Advanced optical materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Organic light emitting materials and devices xvi
Journal: Organic light emitting materials and devices xvi


Journal of the american chemical society
Journal: Journal of the american chemical society


Materials letters
Journal: Materials letters


Carbon
Journal: Carbon


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs energy letters
Journal: Acs energy letters


Npj 2d materials and applications
Journal: Npj 2d materials and applications


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Solar energy
Journal: Solar energy


Acs applied energy materials
Journal: Acs applied energy materials


Acs energy letters
Journal: Acs energy letters


Applied physics letters
Journal: Applied physics letters


The journal of chemical physics
Journal: The journal of chemical physics


The journal of physical chemistry a
Journal: The journal of physical chemistry a


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Applied surface science
Journal: Applied surface science


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Chemical physics letters 507 (1-3)
Journal: Chemical physics letters 507 (1-3)


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


The journal of physical chemistry a
Journal: The journal of physical chemistry a


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Chemical physics letters 493 (1-3)
Journal: Chemical physics letters 493 (1-3)


Chemical physics letters 382 (1-2)
Journal: Chemical physics letters 382 (1-2)


Acs photonics
Journal: Acs photonics


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Dalton transactions
Journal: Dalton transactions


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs omega
Journal: Acs omega


Rsc advances
Journal: Rsc advances


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


Chemical physics letters
Journal: Chemical physics letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nanotechnology
Journal: Nanotechnology


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Organic electronics
Journal: Organic electronics


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


Journal of photochemistry and photobiology a: chemistry 188 (2-3)
Journal: Journal of photochemistry and photobiology a: chemistry 188 (2-3)


Chemical physics letters 406 (4-6)
Journal: Chemical physics letters 406 (4-6)


Physica e: low-dimensional systems and nanostructures
Journal: Physica e: low-dimensional systems and nanostructures


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


Journal of the chinese chemical society
Journal: Journal of the chinese chemical society


Journal of chemical sciences
Journal: Journal of chemical sciences


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Spectrochimica acta part a: molecular and biomolecular spectroscopy 60 (8-9 …
Journal: Spectrochimica acta part a: molecular and biomolecular spectroscopy 60 (8-9 …


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Acs omega
Journal: Acs omega


Rsc advances
Journal: Rsc advances


Materials advances
Journal: Materials advances


Applied physics letters
Journal: Applied physics letters


Ieee electron device letters
Journal: Ieee electron device letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Materials letters
Journal: Materials letters


Carbon
Journal: Carbon


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs energy letters
Journal: Acs energy letters


Npj 2d materials and applications
Journal: Npj 2d materials and applications


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Solar energy
Journal: Solar energy


Acs applied energy materials
Journal: Acs applied energy materials


Acs energy letters
Journal: Acs energy letters


Applied physics letters
Journal: Applied physics letters


The journal of chemical physics
Journal: The journal of chemical physics


The journal of physical chemistry a
Journal: The journal of physical chemistry a


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Applied surface science
Journal: Applied surface science


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Chemical physics letters 507 (1-3)
Journal: Chemical physics letters 507 (1-3)


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


The journal of physical chemistry a

Acta materialia
Journal: Acta materialia


Applied physics letters
Journal: Applied physics letters


Matter
Journal: Matter


Applied physics letters
Journal: Applied physics letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Journal of materials science &technology
Journal: Journal of materials science &technology


Materialia
Journal: Materialia


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Scripta materialia
Journal: Scripta materialia


Acs energy letters
Journal: Acs energy letters


Journal of materiomics
Journal: Journal of materiomics


Materials characterization
Journal: Materials characterization


Acta materialia
Journal: Acta materialia


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Scripta materialia
Journal: Scripta materialia


Chinese physics b
Journal: Chinese physics b


Scripta materialia
Journal: Scripta materialia


Scripta materialia
Journal: Scripta materialia


Physics letters a
Journal: Physics letters a


Physica status solidi (rrl)–rapid research letters
Journal: Physica status solidi (rrl)–rapid research letters


Journal of luminescence
Journal: Journal of luminescence


Ceramics international
Journal: Ceramics international


Rsc advances
Journal: Rsc advances


International journal of quantum chemistry
Journal: International journal of quantum chemistry


Ceramics international
Journal: Ceramics international


Physica b: condensed matter
Journal: Physica b: condensed matter


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Materials letters
Journal: Materials letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Inorganic chemistry
Journal: Inorganic chemistry


Ceramics international
Journal: Ceramics international


Scripta materialia
Journal: Scripta materialia


Chemical communications
Journal: Chemical communications


Rare metals
Journal: Rare metals


Royal society open science
Journal: Royal society open science


Journal of energy chemistry
Journal: Journal of energy chemistry


Scripta materialia
Journal: Scripta materialia


Acs energy letters
Journal: Acs energy letters


Scripta materialia
Journal: Scripta materialia


Journal of advanced ceramics
Journal: Journal of advanced ceramics


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Solar rrl
Journal: Solar rrl


Nature communications
Journal: Nature communications


Nature communications
Journal: Nature communications


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of the american ceramic society
Journal: Journal of the american ceramic society


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acta materialia
Journal: Acta materialia


Applied physics letters
Journal: Applied physics letters


Matter
Journal: Matter


Applied physics letters
Journal: Applied physics letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Journal of materials science &technology
Journal: Journal of materials science &technology


Materialia
Journal: Materialia


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Scripta materialia
Journal: Scripta materialia


Acs energy letters
Journal: Acs energy letters


Journal of materiomics
Journal: Journal of materiomics


Materials characterization
Journal: Materials characterization


Acta materialia
Journal: Acta materialia


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Scripta materialia
Journal: Scripta materialia


Chinese physics b
Journal: Chinese physics b


Scripta materialia
Journal: Scripta materialia


Scripta materialia
Journal: Scripta materialia


Physics letters a
Journal: Physics letters a


Physica status solidi (rrl)–rapid research letters
Journal: Physica status solidi (rrl)–rapid research letters


Journal of luminescence
Journal: Journal of luminescence


Ceramics international
Journal: Ceramics international


Rsc advances
Journal: Rsc advances


International journal of quantum chemistry
Journal: International journal of quantum chemistry


Ceramics international
Journal: Ceramics international


Physica b: condensed matter
Journal: Physica b: condensed matter


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Materials letters
Journal: Materials letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Inorganic chemistry
Journal: Inorganic chemistry


Ceramics international
Journal: Ceramics international


Scripta materialia
Journal: Scripta materialia


Chemical communications
Journal: Chemical communications


Rare metals
Journal: Rare metals


Royal society open science
Journal: Royal society open science


Journal of energy chemistry
Journal: Journal of energy chemistry


Scripta materialia
Journal: Scripta materialia


Acs energy letters
Journal: Acs energy letters


Scripta materialia
Journal: Scripta materialia


Journal of advanced ceramics
Journal: Journal of advanced ceramics


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Solar rrl
Journal: Solar rrl


Nature photonics
Journal: Nature photonics


Chemical science
Journal: Chemical science


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Nanoscale
Journal: Nanoscale


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of display technology
Journal: Journal of display technology


Organic electronics
Journal: Organic electronics


Organic electronics
Journal: Organic electronics


Chinese physics b
Journal: Chinese physics b


Rsc advances
Journal: Rsc advances


Optics &laser technology
Journal: Optics &laser technology


Dyes and pigments
Journal: Dyes and pigments


Physica status solidi (a)
Journal: Physica status solidi (a)


Organic electronics
Journal: Organic electronics


Physica status solidi (a)
Journal: Physica status solidi (a)


Organic electronics
Journal: Organic electronics


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Synthetic metals
Journal: Synthetic metals


Iscience
Journal: Iscience


Organic electronics
Journal: Organic electronics


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Physica e: low-dimensional systems and nanostructures
Journal: Physica e: low-dimensional systems and nanostructures


Chinese physics b
Journal: Chinese physics b


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Optical materials
Journal: Optical materials


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Nanoscale research letters
Journal: Nanoscale research letters


Physica status solidi (a)
Journal: Physica status solidi (a)


Physica status solidi (a)
Journal: Physica status solidi (a)


Molecular crystals and liquid crystals
Journal: Molecular crystals and liquid crystals


Chinese physics b
Journal: Chinese physics b


Materials science in semiconductor processing
Journal: Materials science in semiconductor processing


Nanoscience and nanotechnology letters
Journal: Nanoscience and nanotechnology letters


Frontiers of materials science
Journal: Frontiers of materials science


Physica status solidi (a)
Journal: Physica status solidi (a)


光学学报
Journal: 光学学报


Key engineering materials
Journal: Key engineering materials


光学学报
Journal: 光学学报


Physica status solidi (a)
Journal: Physica status solidi (a)


Molecular crystals and liquid crystals
Journal: Molecular crystals and liquid crystals


Optoelectronics letters
Journal: Optoelectronics letters


Sustainable energy &fuels
Journal: Sustainable energy &fuels


J. mater. chem
Journal: J. mater. chem


Surface and coatings technology
Journal: Surface and coatings technology


发光学报
Journal: 发光学报


强激光与粒子束
Journal: 强激光与粒子束


强激光与粒子束
Journal: 强激光与粒子束


功能材料
Journal: 功能材料


Nature photonics
Journal: Nature photonics


Chemical science
Journal: Chemical science


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Nanoscale
Journal: Nanoscale


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of display technology
Journal: Journal of display technology


Organic electronics
Journal: Organic electronics


Organic electronics
Journal: Organic electronics


Chinese physics b
Journal: Chinese physics b


Rsc advances
Journal: Rsc advances


Optics &laser technology
Journal: Optics &laser technology


Dyes and pigments
Journal: Dyes and pigments


Physica status solidi (a)
Journal: Physica status solidi (a)


Organic electronics
Journal: Organic electronics


Physica status solidi (a)
Journal: Physica status solidi (a)


Organic electronics
Journal: Organic electronics


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Synthetic metals
Journal: Synthetic metals


Iscience
Journal: Iscience


Organic electronics
Journal: Organic electronics


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Physica e: low-dimensional systems and nanostructures
Journal: Physica e: low-dimensional systems and nanostructures


Chinese physics b
Journal: Chinese physics b


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Optical materials
Journal: Optical materials


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Nanoscale research letters
Journal: Nanoscale research letters


Physica status solidi (a)
Journal: Physica status solidi (a)


Physica status solidi (a)
Journal: Physica status solidi (a)


Molecular crystals and liquid crystals
Journal: Molecular crystals and liquid crystals


Chinese physics b
Journal: Chinese physics b


Materials science in semiconductor processing
Journal: Materials science in semiconductor processing


Nanoscience and nanotechnology letters
Journal: Nanoscience and nanotechnology letters


Frontiers of materials science
Journal: Frontiers of materials science


Physica status solidi (a)
Journal: Physica status solidi (a)


光学学报
Journal: 光学学报


Key engineering materials
Journal: Key engineering materials


光学学报
Journal: 光学学报


Physica status solidi (a)
Journal: Physica status solidi (a)


Molecular crystals and liquid crystals
Journal: Molecular crystals and liquid crystals


Optoelectronics letters
Journal: Optoelectronics letters


Sustainable energy &fuels
Journal: Sustainable energy &fuels


J. mater. chem
Journal: J. mater. chem


Surface and coatings technology
Journal: Surface and coatings technology


发光学报
Journal: 发光学报


强激光与粒子束
Journal: 强激光与粒子束


强激光与粒子束
Journal: 强激光与粒子束


功能材料
Journal: 功能材料


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Advanced functional materials
Journal: Advanced functional materials


Acta materialia
Journal: Acta materialia


Journal of materials chemistry
Journal: Journal of materials chemistry


Physical review b
Journal: Physical review b


Acta materialia
Journal: Acta materialia


Journal of applied physics
Journal: Journal of applied physics


Materials science and engineering: c
Journal: Materials science and engineering: c


Acta materialia
Journal: Acta materialia


Colloids and surfaces b: biointerfaces
Journal: Colloids and surfaces b: biointerfaces


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Ieee transactions on ultrasonics, ferroelectrics, and frequency control 58 …
Journal: Ieee transactions on ultrasonics


Electrochimica acta
Journal: Electrochimica acta


Dyes and pigments
Journal: Dyes and pigments


Journal of applied physics
Journal: Journal of applied physics


Nature materials
Journal: Nature materials


Open ceramics
Journal: Open ceramics


Synthetic metals
Journal: Synthetic metals


Dyes and pigments
Journal: Dyes and pigments


Materials
Journal: Materials


Geologija
Journal: Geologija


Actuators
Journal: Actuators


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Crystals
Journal: Crystals


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Physical review applied
Journal: Physical review applied


Scripta materialia
Journal: Scripta materialia


Angewandte chemie
Journal: Angewandte chemie


International journal of hydrogen energy
Journal: International journal of hydrogen energy


Materials letters
Journal: Materials letters


Acs applied electronic materials
Journal: Acs applied electronic materials


Journal of materials science
Journal: Journal of materials science


Advances in electroceramic materials ii
Journal: Advances in electroceramic materials ii


Journal of materials science
Journal: Journal of materials science


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Nuclear materials and energy
Journal: Nuclear materials and energy


Nanoscale
Journal: Nanoscale


Scripta materialia
Journal: Scripta materialia


Nanoscale
Journal: Nanoscale


Journal of applied physics
Journal: Journal of applied physics


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Structural dynamics
Journal: Structural dynamics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Microelectronics reliability
Journal: Microelectronics reliability


Journal of nuclear materials
Journal: Journal of nuclear materials


Micron
Journal: Micron


Open chemistry
Journal: Open chemistry


Open chemistry
Journal: Open chemistry


Environmental science and pollution research
Journal: Environmental science and pollution research


Green processing and synthesis
Journal: Green processing and synthesis


Reviews in inorganic chemistry
Journal: Reviews in inorganic chemistry


Critical reviews in solid state and materials sciences
Journal: Critical reviews in solid state and materials sciences


International journal of environmental science and technology
Journal: International journal of environmental science and technology


Iet nanobiotechnology
Journal: Iet nanobiotechnology


Reviews in inorganic chemistry
Journal: Reviews in inorganic chemistry


Microelectronic engineering
Journal: Microelectronic engineering


Soil and sediment contamination: an international journal
Journal: Soil and sediment contamination: an international journal


Sydowia
Journal: Sydowia


Phosphorus, sulfur, and silicon and the related elements
Journal: Phosphorus


Zeitschrift für physikalische chemie
Journal: Zeitschrift für physikalische chemie


Reviews in inorganic chemistry
Journal: Reviews in inorganic chemistry


International journal of hydrogen energy
Journal: International journal of hydrogen energy


Journal of plant diseases and protection
Journal: Journal of plant diseases and protection


International journal of ambient energy
Journal: International journal of ambient energy


Renewable energy
Journal: Renewable energy


Biologia
Journal: Biologia


Journal of inorganic and organometallic polymers and materials
Journal: Journal of inorganic and organometallic polymers and materials


International journal of economic and environmental geology
Journal: International journal of economic and environmental geology


Soil &environment
Journal: Soil &environment


Soil environ
Journal: Soil environ


Results in physics
Journal: Results in physics


International journal of economic and environmental geology
Journal: International journal of economic and environmental geology


Archives of phytopathology and plant protection 54 (17-18)
Journal: Archives of phytopathology and plant protection 54 (17-18)


Environmental science and pollution research
Journal: Environmental science and pollution research


International journal of environmental analytical chemistry
Journal: International journal of environmental analytical chemistry


Green chemistry letters and reviews
Journal: Green chemistry letters and reviews


International journal of environmental analytical chemistry
Journal: International journal of environmental analytical chemistry


Reviews in inorganic chemistry
Journal: Reviews in inorganic chemistry


International journal of environmental analytical chemistry
Journal: International journal of environmental analytical chemistry


Reviews in inorganic chemistry
Journal: Reviews in inorganic chemistry


Soil and sediment contamination: an international journal
Journal: Soil and sediment contamination: an international journal


International journal of environmental science and technology
Journal: International journal of environmental science and technology


Polymers
Journal: Polymers


2d nanomaterials: chemistry and properties
Journal: 2d nanomaterials: chemistry and properties


Electroactive polymeric materials
Journal: Electroactive polymeric materials


Canadian metallurgical quarterly
Journal: Canadian metallurgical quarterly


International journal of economic and environmental geology
Journal: International journal of economic and environmental geology


Ceramics international
Journal: Ceramics international


Aprendizagem significativa em revista/meaningful learning review
Journal: Aprendizagem significativa em revista/meaningful learning review


Micron
Journal: Micron


Inorganic chemistry
Journal: Inorganic chemistry


Ceramics international
Journal: Ceramics international


Caderno de física da uefs
Journal: Caderno de física da uefs


Revista thema
Journal: Revista thema


International journal of educational studies
Journal: International journal of educational studies


Chemical physics letters
Journal: Chemical physics letters


Solid state communications
Journal: Solid state communications


Computational materials science
Journal: Computational materials science


Ceramics international
Journal: Ceramics international


Lat. am. j. phys. educ. vol
Journal: Lat. am. j. phys. educ. vol


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Journal of materials research and technology
Journal: Journal of materials research and technology



Physical review b
Journal: Physical review b


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced optical materials
Journal: Advanced optical materials


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemistry of materials
Journal: Chemistry of materials


Surface science
Journal: Surface science


Advanced materials
Journal: Advanced materials


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Microelectronic engineering
Journal: Microelectronic engineering


Physical review b
Journal: Physical review b


Physical review letters
Journal: Physical review letters


Nature communications
Journal: Nature communications


Joule
Journal: Joule


Acs nano
Journal: Acs nano


Acs energy letters
Journal: Acs energy letters


Physical review letters
Journal: Physical review letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemistry of materials
Journal: Chemistry of materials


Acs nano
Journal: Acs nano


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced materials
Journal: Advanced materials


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Applied physics letters
Journal: Applied physics letters


Advanced energy materials
Journal: Advanced energy materials


Physical review b
Journal: Physical review b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review materials
Journal: Physical review materials


Crystengcomm
Journal: Crystengcomm


Physical review b
Journal: Physical review b


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced optical materials
Journal: Advanced optical materials


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemistry of materials
Journal: Chemistry of materials


Surface science
Journal: Surface science


Advanced materials
Journal: Advanced materials


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Microelectronic engineering
Journal: Microelectronic engineering


Physical review b
Journal: Physical review b


Carbon
Journal: Carbon


Nature photonics
Journal: Nature photonics


Solar rrl
Journal: Solar rrl


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


Matter
Journal: Matter


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Nature energy
Journal: Nature energy


Nano letters
Journal: Nano letters


Science advances
Journal: Science advances


Rsc advances
Journal: Rsc advances


Scientific reports
Journal: Scientific reports


Nanoscale
Journal: Nanoscale


Journal of power sources
Journal: Journal of power sources


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Sustainable energy &fuels
Journal: Sustainable energy &fuels


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nanoscale
Journal: Nanoscale


Nanoscale
Journal: Nanoscale


2d materials
Journal: 2d materials


Advanced materials
Journal: Advanced materials


Journal of applied physics
Journal: Journal of applied physics


Material matters™
Journal: Material matters™


Carbon
Journal: Carbon


Nature photonics
Journal: Nature photonics


Solar rrl
Journal: Solar rrl


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


Matter
Journal: Matter


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Nature energy
Journal: Nature energy


Nano letters
Journal: Nano letters


Science advances
Journal: Science advances


Rsc advances
Journal: Rsc advances


Scientific reports
Journal: Scientific reports


Nanoscale
Journal: Nanoscale


Journal of power sources
Journal: Journal of power sources


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Sustainable energy &fuels
Journal: Sustainable energy &fuels


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nanoscale
Journal: Nanoscale


Nanoscale
Journal: Nanoscale


2d materials
Journal: 2d materials


Advanced materials
Journal: Advanced materials


Journal of applied physics
Journal: Journal of applied physics


Material matters™
Journal: Material matters™


Advanced functional materials
Journal: Advanced functional materials


Advanced science
Journal: Advanced science


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Renewable and sustainable energy reviews
Journal: Renewable and sustainable energy reviews


International journal of hydrogen energy
Journal: International journal of hydrogen energy


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Acs applied energy materials
Journal: Acs applied energy materials


Korean journal of chemical engineering
Journal: Korean journal of chemical engineering


Solar energy
Journal: Solar energy


Renewable energy
Journal: Renewable energy


Organic electronics
Journal: Organic electronics


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Chemical communications
Journal: Chemical communications


Green chemistry
Journal: Green chemistry


Nanoscale
Journal: Nanoscale


Nanotechnology
Journal: Nanotechnology


Materials today energy
Journal: Materials today energy


Inorganic chemistry
Journal: Inorganic chemistry


Solar energy
Journal: Solar energy


International journal of hydrogen energy
Journal: International journal of hydrogen energy


Acs applied energy materials
Journal: Acs applied energy materials


Solar rrl
Journal: Solar rrl


Green energy &environment
Journal: Green energy &environment


Journal of non-crystalline solids
Journal: Journal of non-crystalline solids


Materials research express
Journal: Materials research express


Solar rrl
Journal: Solar rrl


Ieee transactions on terahertz science and technology
Journal: Ieee transactions on terahertz science and technology


New journal of chemistry
Journal: New journal of chemistry


Applied surface science
Journal: Applied surface science


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Journal of materials science
Journal: Journal of materials science


Journal of non-crystalline solids
Journal: Journal of non-crystalline solids


Semiconductor science and technology
Journal: Semiconductor science and technology


Materials chemistry and physics
Journal: Materials chemistry and physics


Microchimica acta
Journal: Microchimica acta


Optica
Journal: Optica


Journal of materials science
Journal: Journal of materials science


Ieee transactions on electron devices
Journal: Ieee transactions on electron devices


Solar energy
Journal: Solar energy


Materials science and engineering b
Journal: Materials science and engineering b


The light house journal of natural sciences
Journal: The light house journal of natural sciences


The light house journal of natural sciences
Journal: The light house journal of natural sciences


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Int j hydrogen energy
Journal: Int j hydrogen energy


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Chemical science
Journal: Chemical science


Ieee transactions on electron devices
Journal: Ieee transactions on electron devices


Applied physics letters
Journal: Applied physics letters


Nanomaterials
Journal: Nanomaterials


Review of scientific instruments
Journal: Review of scientific instruments


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Thin solid films
Journal: Thin solid films


Ieee transactions on electron devices
Journal: Ieee transactions on electron devices


Physica status solidi (rrl)–rapid research letters
Journal: Physica status solidi (rrl)–rapid research letters


Chemistry of materials
Journal: Chemistry of materials


Applied physics letters
Journal: Applied physics letters


Ieee electron device letters
Journal: Ieee electron device letters


Ferroelectrics
Journal: Ferroelectrics


Spin
Journal: Spin


Crystengcomm
Journal: Crystengcomm


Applied physics letters
Journal: Applied physics letters


Apl materials
Journal: Apl materials


Applied physics a
Journal: Applied physics a


Frontiers in nanotechnology
Journal: Frontiers in nanotechnology


Ieee transactions on electron devices
Journal: Ieee transactions on electron devices


Ieee journal of the electron devices society
Journal: Ieee journal of the electron devices society


Applied physics letters
Journal: Applied physics letters


Applied physics. a, materials science and processing
Journal: Applied physics. a


Journal of electroanalytical chemistry 517 (1-2)
Journal: Journal of electroanalytical chemistry 517 (1-2)


Analytical chemistry
Journal: Analytical chemistry


Langmuir
Journal: Langmuir


Langmuir
Journal: Langmuir


Faraday discussions
Journal: Faraday discussions


Journal of the american chemical society
Journal: Journal of the american chemical society


Chembiochem
Journal: Chembiochem


Electroanalysis: an international journal devoted to fundamental and …
Journal: Electroanalysis: an international journal devoted to fundamental and …


Electroanalysis: an international journal devoted to fundamental and …
Journal: Electroanalysis: an international journal devoted to fundamental and …


Inorganic chemistry communications
Journal: Inorganic chemistry communications


Bioelectrochemistry
Journal: Bioelectrochemistry


Analytica chimica acta
Journal: Analytica chimica acta


Analytica chimica acta 686 (1-2)
Journal: Analytica chimica acta 686 (1-2)


Materials
Journal: Materials


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Electroanalysis
Journal: Electroanalysis


Coatings
Journal: Coatings


Talanta
Journal: Talanta


Materials chemistry frontiers
Journal: Materials chemistry frontiers


Analytical methods
Journal: Analytical methods


Frontiers of materials science
Journal: Frontiers of materials science


Vaccines
Journal: Vaccines


Coatings
Journal: Coatings


Brain sciences
Journal: Brain sciences


Colloid and polymer science
Journal: Colloid and polymer science


Coatings
Journal: Coatings


Diffusion fundamentals 2, 109.1-109.
Journal: Diffusion fundamentals 2


Mesoporous metal oxide films
Journal: Mesoporous metal oxide films


Nanomaterials
Journal: Nanomaterials


Clinical pharmacology and pharmacokinetics
Journal: Clinical pharmacology and pharmacokinetics


Clinical pharmacology and pharmacokinetics
Journal: Clinical pharmacology and pharmacokinetics


Biochemical society transactions
Journal: Biochemical society transactions


Journal of electroanalytical chemistry 517 (1-2)
Journal: Journal of electroanalytical chemistry 517 (1-2)


Analytical chemistry
Journal: Analytical chemistry


Langmuir
Journal: Langmuir


Langmuir
Journal: Langmuir


Faraday discussions
Journal: Faraday discussions


Journal of the american chemical society
Journal: Journal of the american chemical society


Chembiochem
Journal: Chembiochem


Electroanalysis: an international journal devoted to fundamental and …
Journal: Electroanalysis: an international journal devoted to fundamental and …


Electroanalysis: an international journal devoted to fundamental and …
Journal: Electroanalysis: an international journal devoted to fundamental and …


Inorganic chemistry communications
Journal: Inorganic chemistry communications


Bioelectrochemistry
Journal: Bioelectrochemistry


Analytica chimica acta
Journal: Analytica chimica acta


Analytica chimica acta 686 (1-2)
Journal: Analytica chimica acta 686 (1-2)


Materials
Journal: Materials


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Electroanalysis
Journal: Electroanalysis


Coatings
Journal: Coatings


Talanta
Journal: Talanta


Materials chemistry frontiers
Journal: Materials chemistry frontiers


Analytical methods
Journal: Analytical methods


Frontiers of materials science
Journal: Frontiers of materials science


Vaccines
Journal: Vaccines


Coatings
Journal: Coatings


Brain sciences
Journal: Brain sciences


Colloid and polymer science
Journal: Colloid and polymer science


Coatings
Journal: Coatings


Diffusion fundamentals 2, 109.1-109.
Journal: Diffusion fundamentals 2


Mesoporous metal oxide films
Journal: Mesoporous metal oxide films


Nanomaterials
Journal: Nanomaterials


Clinical pharmacology and pharmacokinetics
Journal: Clinical pharmacology and pharmacokinetics


Clinical pharmacology and pharmacokinetics
Journal: Clinical pharmacology and pharmacokinetics


Biochemical society transactions
Journal: Biochemical society transactions


Am. j. polym. sci
Journal: Am. j. polym. sci


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Solar energy
Journal: Solar energy


Synthetic metals
Journal: Synthetic metals


Journal of applied physics
Journal: Journal of applied physics


Journal of nuclear materials
Journal: Journal of nuclear materials


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Journal of luminescence
Journal: Journal of luminescence


Applied surface science
Journal: Applied surface science


Optical materials
Journal: Optical materials


Journal of electronic materials
Journal: Journal of electronic materials


Journal of nuclear materials
Journal: Journal of nuclear materials


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Sustainable energy &fuels
Journal: Sustainable energy &fuels


Journal of materials
Journal: Journal of materials


Solar energy
Journal: Solar energy


Mrs advances
Journal: Mrs advances


Journal of electronic materials
Journal: Journal of electronic materials


New journal of chemistry
Journal: New journal of chemistry


Physica b january
Journal: Physica b january


Indian journal of physics
Journal: Indian journal of physics


International journal of engineering technology, management and applied …
Journal: International journal of engineering technology


Am. j. polym. sci
Journal: Am. j. polym. sci


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Solar energy
Journal: Solar energy


Synthetic metals
Journal: Synthetic metals


Journal of applied physics
Journal: Journal of applied physics


Journal of nuclear materials
Journal: Journal of nuclear materials


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Journal of luminescence
Journal: Journal of luminescence


Applied surface science
Journal: Applied surface science


Optical materials
Journal: Optical materials


Journal of electronic materials
Journal: Journal of electronic materials


Journal of nuclear materials
Journal: Journal of nuclear materials


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Sustainable energy &fuels
Journal: Sustainable energy &fuels


Journal of materials
Journal: Journal of materials


Solar energy
Journal: Solar energy


Mrs advances
Journal: Mrs advances


Journal of electronic materials
Journal: Journal of electronic materials


New journal of chemistry
Journal: New journal of chemistry


Physica b january
Journal: Physica b january


Indian journal of physics
Journal: Indian journal of physics


International journal of engineering technology, management and applied …
Journal: International journal of engineering technology


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced materials
Journal: Advanced materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced functional materials
Journal: Advanced functional materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Advanced science
Journal: Advanced science


Advanced materials
Journal: Advanced materials


Acs energy letters
Journal: Acs energy letters


Physical review b
Journal: Physical review b


Scientific reports
Journal: Scientific reports


Nature communications
Journal: Nature communications


Particle &particle systems characterization
Journal: Particle &particle systems characterization


Advanced materials
Journal: Advanced materials


Apl materials
Journal: Apl materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nano energy
Journal: Nano energy


Acs omega
Journal: Acs omega


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Acs photonics
Journal: Acs photonics


Chemical communications
Journal: Chemical communications


Applied physics letters
Journal: Applied physics letters


Acs applied energy materials
Journal: Acs applied energy materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Rsc advances
Journal: Rsc advances


Organic electronics
Journal: Organic electronics


Advanced electronic materials
Journal: Advanced electronic materials


Applied physics letters
Journal: Applied physics letters


Small
Journal: Small


Advanced optical materials
Journal: Advanced optical materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Small
Journal: Small


Royal society open science
Journal: Royal society open science


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced materials
Journal: Advanced materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced functional materials
Journal: Advanced functional materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Advanced science
Journal: Advanced science


Advanced materials

Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


Energy &environmental science
Journal: Energy &environmental science


Acs energy letters
Journal: Acs energy letters


Organic electronics
Journal: Organic electronics


Journal of applied physics
Journal: Journal of applied physics


Matter
Journal: Matter


Http://dspace.mit.edu/handle/1721.1/
Journal: Http://dspace.mit.edu/handle/1721.1/


Joule
Journal: Joule


Physical review applied
Journal: Physical review applied


Joule
Journal: Joule


Applied physics letters
Journal: Applied physics letters


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Physical review b
Journal: Physical review b


Nature energy
Journal: Nature energy


New journal of physics
Journal: New journal of physics


Advanced materials
Journal: Advanced materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs nano
Journal: Acs nano


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Nano energy
Journal: Nano energy


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Nano energy
Journal: Nano energy


Electrochimica acta
Journal: Electrochimica acta


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Applied surface science
Journal: Applied surface science


Acs applied energy materials
Journal: Acs applied energy materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nano energy
Journal: Nano energy


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Nano energy
Journal: Nano energy


Chemistry of materials
Journal: Chemistry of materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Electrochimica acta
Journal: Electrochimica acta


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced energy materials
Journal: Advanced energy materials


Electrochimica acta
Journal: Electrochimica acta


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Journal of power sources
Journal: Journal of power sources


Electrochimica acta
Journal: Electrochimica acta


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Review of scientific instruments
Journal: Review of scientific instruments


Applied energy
Journal: Applied energy


Nano energy
Journal: Nano energy


材料工程
Journal: 材料工程


Journal of colloid and interface science
Journal: Journal of colloid and interface science


Applied surface science
Journal: Applied surface science


Nano energy
Journal: Nano energy


Journal of energy chemistry
Journal: Journal of energy chemistry


Journal of energy chemistry
Journal: Journal of energy chemistry


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs nano
Journal: Acs nano


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Nano energy
Journal: Nano energy


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Nano energy
Journal: Nano energy


Electrochimica acta
Journal: Electrochimica acta


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Applied surface science
Journal: Applied surface science


Acs applied energy materials
Journal: Acs applied energy materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nano energy
Journal: Nano energy


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Nano energy
Journal: Nano energy


Chemistry of materials
Journal: Chemistry of materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Electrochimica acta
Journal: Electrochimica acta


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced energy materials
Journal: Advanced energy materials


Electrochimica acta
Journal: Electrochimica acta


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Journal of power sources
Journal: Journal of power sources


Electrochimica acta
Journal: Electrochimica acta


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Review of scientific instruments
Journal: Review of scientific instruments


Applied energy
Journal: Applied energy


Nano energy
Journal: Nano energy


材料工程
Journal: 材料工程


Journal of colloid and interface science
Journal: Journal of colloid and interface science


Applied surface science
Journal: Applied surface science


Nano energy
Journal: Nano energy


Journal of energy chemistry
Journal: Journal of energy chemistry


Journal of energy chemistry
Journal: Journal of energy chemistry


Nature communications
Journal: Nature communications


Acs energy letters
Journal: Acs energy letters


Chemistry of materials
Journal: Chemistry of materials


Acs energy letters
Journal: Acs energy letters


Scientific reports
Journal: Scientific reports


Angewandte chemie
Journal: Angewandte chemie


Acs energy letters
Journal: Acs energy letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Chem
Journal: Chem


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Advanced functional materials
Journal: Advanced functional materials


Mrs bulletin
Journal: Mrs bulletin


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Organic electronics
Journal: Organic electronics


Acs nano
Journal: Acs nano


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Chemsuschem
Journal: Chemsuschem


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs nano
Journal: Acs nano


Journal of power sources
Journal: Journal of power sources


Acs nano
Journal: Acs nano


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Chemsuschem
Journal: Chemsuschem


Journal of materials chemistry a
Journal: Journal of materials chemistry a


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs applied energy materials
Journal: Acs applied energy materials


Applied physics letters
Journal: Applied physics letters


Science advances
Journal: Science advances


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Nature photonics
Journal: Nature photonics


Nature materials
Journal: Nature materials


Energy &environmental science
Journal: Energy &environmental science


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Nano letters
Journal: Nano letters


Dalton transactions
Journal: Dalton transactions


Advanced energy materials
Journal: Advanced energy materials


Nature communications
Journal: Nature communications


Journal of the american chemical society
Journal: Journal of the american chemical society


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Nature materials
Journal: Nature materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced optical materials
Journal: Advanced optical materials


Physical review b
Journal: Physical review b


Jacs au
Journal: Jacs au


Energy &environmental science
Journal: Energy &environmental science


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced optical materials
Journal: Advanced optical materials


Energy &environmental science
Journal: Energy &environmental science


Science
Journal: Science


Nature communications
Journal: Nature communications


Nature communications
Journal: Nature communications


Science advances
Journal: Science advances


Acs energy letters
Journal: Acs energy letters


Acs nano
Journal: Acs nano


Nature photonics
Journal: Nature photonics


Energy &environmental science
Journal: Energy &environmental science


Chemical reviews
Journal: Chemical reviews


Advanced energy materials
Journal: Advanced energy materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs nano
Journal: Acs nano


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Physical review applied
Journal: Physical review applied


Rsc advances
Journal: Rsc advances


Joule
Journal: Joule


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of materials chemistry a
Journal: Journal of materials chemistry a


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Small
Journal: Small


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs photonics
Journal: Acs photonics


Pure and applied chemistry
Journal: Pure and applied chemistry


Solar rrl
Journal: Solar rrl


Journal of luminescence
Journal: Journal of luminescence


Pure and applied chemistry
Journal: Pure and applied chemistry


Physical chemistry of interfaces and nanomaterials xv
Journal: Physical chemistry of interfaces and nanomaterials xv


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Applied physics letters
Journal: Applied physics letters


Materials letters
Journal: Materials letters


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Journal of applied physics
Journal: Journal of applied physics


Applied physics letters
Journal: Applied physics letters


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Acta materialia
Journal: Acta materialia


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Materials horizons
Journal: Materials horizons


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Materials letters
Journal: Materials letters


Inorganic chemistry
Journal: Inorganic chemistry


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Ieee transactions on ultrasonics, ferroelectrics, and frequency control 58 …
Journal: Ieee transactions on ultrasonics


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Journal of power sources
Journal: Journal of power sources


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Journal of thermal spray technology
Journal: Journal of thermal spray technology


Macromolecules
Journal: Macromolecules


Ieee transactions on magnetics
Journal: Ieee transactions on magnetics


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Applied physics letters
Journal: Applied physics letters


Journal of advanced dielectrics
Journal: Journal of advanced dielectrics


Applied physics letters
Journal: Applied physics letters


American ceramic society bulletin
Journal: American ceramic society bulletin


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Applied physics letters
Journal: Applied physics letters


Materials letters
Journal: Materials letters


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Journal of applied physics
Journal: Journal of applied physics


Applied physics letters
Journal: Applied physics letters


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Acta materialia
Journal: Acta materialia


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Materials horizons
Journal: Materials horizons


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Materials letters
Journal: Materials letters


Inorganic chemistry
Journal: Inorganic chemistry


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Ieee transactions on ultrasonics, ferroelectrics, and frequency control 58 …
Journal: Ieee transactions on ultrasonics


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Journal of power sources
Journal: Journal of power sources


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Journal of thermal spray technology
Journal: Journal of thermal spray technology


Macromolecules
Journal: Macromolecules


Ieee transactions on magnetics
Journal: Ieee transactions on magnetics


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Applied physics letters
Journal: Applied physics letters


Journal of advanced dielectrics
Journal: Journal of advanced dielectrics


Applied physics letters
Journal: Applied physics letters


American ceramic society bulletin
Journal: American ceramic society bulletin


Japanese journal of applied physics 55 (2s), 02bf
Journal: Japanese journal of applied physics 55 (2s)


Japanese journal of applied physics
Journal: Japanese journal of applied physics


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


International journal of biological macromolecules
Journal: International journal of biological macromolecules


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs applied nano materials
Journal: Acs applied nano materials


Japanese journal of applied physics
Journal: Japanese journal of applied physics


International journal of biological macromolecules
Journal: International journal of biological macromolecules


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Engineering research express
Journal: Engineering research express


Rsc advances
Journal: Rsc advances


Journal of nanoscience and nanotechnology
Journal: Journal of nanoscience and nanotechnology


Journal of composites science
Journal: Journal of composites science


Journal of composites science
Journal: Journal of composites science


Structural health monitoring
Journal: Structural health monitoring


Scientific reports
Journal: Scientific reports


Journal of photopolymer science and technology
Journal: Journal of photopolymer science and technology


Journal of photopolymer science and technology
Journal: Journal of photopolymer science and technology


Sensors and actuators a: physical
Journal: Sensors and actuators a: physical


Sensors
Journal: Sensors


Ecs journal of solid state science and technology
Journal: Ecs journal of solid state science and technology


Ieice technical report; ieice tech. rep.
Journal: Ieice technical report; ieice tech. rep.


Ieice technical report; ieice tech. rep.
Journal: Ieice technical report; ieice tech. rep.


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


Acs nano
Journal: Acs nano


Nature communications
Journal: Nature communications


Nanoscale
Journal: Nanoscale


Advanced materials
Journal: Advanced materials


Chemical communications
Journal: Chemical communications


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Chemical communications
Journal: Chemical communications


Advanced materials
Journal: Advanced materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced functional materials
Journal: Advanced functional materials


Nanoscale
Journal: Nanoscale


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Chemical communications
Journal: Chemical communications


Applied physics letters
Journal: Applied physics letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Acs nano
Journal: Acs nano


Nanotechnology
Journal: Nanotechnology


Applied physics letters
Journal: Applied physics letters


Applied materials today
Journal: Applied materials today


Nanoscale
Journal: Nanoscale


Npj 2d materials and applications
Journal: Npj 2d materials and applications


Chemical communications
Journal: Chemical communications


Journal of vacuum science &technology b, nanotechnology and …
Journal: Journal of vacuum science &technology b


Advanced electronic materials
Journal: Advanced electronic materials


Scientific reports
Journal: Scientific reports


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Carbon
Journal: Carbon


Journal of vacuum science &technology a: vacuum, surfaces, and films 38 (5 …
Journal: Journal of vacuum science &technology a: vacuum


Mrs advances
Journal: Mrs advances


Nanotechnology
Journal: Nanotechnology


Journal of nanoscience and nanotechnology
Journal: Journal of nanoscience and nanotechnology


Mrs advances
Journal: Mrs advances


Mrs advances
Journal: Mrs advances


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


Acs nano
Journal: Acs nano


Nature communications
Journal: Nature communications


Nanoscale
Journal: Nanoscale


Advanced materials
Journal: Advanced materials


Chemical communications
Journal: Chemical communications


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Chemical communications
Journal: Chemical communications


Advanced materials
Journal: Advanced materials


Acs applied materials &interfaces

Journal of materials chemistry a
Journal: Journal of materials chemistry a


Nano letters
Journal: Nano letters


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Ieee transactions on electron devices
Journal: Ieee transactions on electron devices


Applied physics letters
Journal: Applied physics letters


Materials
Journal: Materials


Optics for solar energy, sow2c.
Journal: Optics for solar energy


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Solar rrl
Journal: Solar rrl


Advanced electronic materials
Journal: Advanced electronic materials


Applied physics letters
Journal: Applied physics letters


Organic electronics
Journal: Organic electronics


Organic electronics
Journal: Organic electronics


Npj flexible electronics
Journal: Npj flexible electronics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Organic electronics
Journal: Organic electronics


Synthetic metals
Journal: Synthetic metals


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Organic electronics
Journal: Organic electronics


Journal of power sources
Journal: Journal of power sources


Journal of energy chemistry
Journal: Journal of energy chemistry


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Sci. china mater
Journal: Sci. china mater


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Organic electronics
Journal: Organic electronics


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of renewable and sustainable energy
Journal: Journal of renewable and sustainable energy


Physica b: condensed matter
Journal: Physica b: condensed matter


Interdisciplinary materials
Journal: Interdisciplinary materials


Matter
Journal: Matter


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Applied physics a
Journal: Applied physics a


Energychem
Journal: Energychem


Journal of hazardous materials
Journal: Journal of hazardous materials


Nanoscale
Journal: Nanoscale


J. mater. chem
Journal: J. mater. chem


Chemical communications
Journal: Chemical communications


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Materials horizons
Journal: Materials horizons


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Rsc advances
Journal: Rsc advances


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of the society for information display
Journal: Journal of the society for information display


Faraday discussions
Journal: Faraday discussions


Nature communications
Journal: Nature communications


Nature communications
Journal: Nature communications


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Npj computational materials
Journal: Npj computational materials


Chemical communications
Journal: Chemical communications


Physical review b
Journal: Physical review b


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Molecular systems design &engineering
Journal: Molecular systems design &engineering


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced functional materials
Journal: Advanced functional materials


Advanced theory and simulations
Journal: Advanced theory and simulations


Materials advances
Journal: Materials advances


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Chemistry of materials
Journal: Chemistry of materials


Acs applied nano materials
Journal: Acs applied nano materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Npj computational materials
Journal: Npj computational materials


Acs applied energy materials
Journal: Acs applied energy materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry b
Journal: The journal of physical chemistry b


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Small methods
Journal: Small methods


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Chemical science
Journal: Chemical science


Advanced theory and simulations
Journal: Advanced theory and simulations


Journal of the american chemical society
Journal: Journal of the american chemical society


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Chemistry of materials
Journal: Chemistry of materials


Acs nano
Journal: Acs nano


Chemistry of materials
Journal: Chemistry of materials


Chemical communications
Journal: Chemical communications


Journal of materials chemistry a
Journal: Journal of materials chemistry a


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Chemistry of materials
Journal: Chemistry of materials


Journal of solid state chemistry
Journal: Journal of solid state chemistry


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemistry of materials
Journal: Chemistry of materials


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Chemical communications
Journal: Chemical communications


Applied energy
Journal: Applied energy


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Nanotechnology
Journal: Nanotechnology


Chemsuschem
Journal: Chemsuschem


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Applied energy
Journal: Applied energy


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Rsc advances
Journal: Rsc advances


Advanced functional materials
Journal: Advanced functional materials


Energy &environmental science
Journal: Energy &environmental science


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of materiomics
Journal: Journal of materiomics


Nanophotonics
Journal: Nanophotonics


Solar rrl
Journal: Solar rrl


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


New journal of chemistry
Journal: New journal of chemistry


Dalton transactions
Journal: Dalton transactions


Rsc advances
Journal: Rsc advances


Chemistryselect
Journal: Chemistryselect


Journal of energy chemistry
Journal: Journal of energy chemistry


Rsc advances
Journal: Rsc advances


Rsc advances
Journal: Rsc advances


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Materials science in semiconductor processing
Journal: Materials science in semiconductor processing


Rsc advances
Journal: Rsc advances


Rsc advances
Journal: Rsc advances


Dalton transactions
Journal: Dalton transactions


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Rsc advances
Journal: Rsc advances


Acs applied energy materials
Journal: Acs applied energy materials


Chemistry of materials
Journal: Chemistry of materials


Advanced optical materials
Journal: Advanced optical materials


Crystengcomm
Journal: Crystengcomm


Chemistry of materials
Journal: Chemistry of materials


Journal of semiconductors
Journal: Journal of semiconductors


Acs central science
Journal: Acs central science


Energy technology
Journal: Energy technology


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Rsc advances
Journal: Rsc advances


Advanced functional materials
Journal: Advanced functional materials


Energy &environmental science
Journal: Energy &environmental science


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of materiomics
Journal: Journal of materiomics


Nanophotonics
Journal: Nanophotonics


Solar rrl
Journal: Solar rrl


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


New journal of chemistry
Journal: New journal of chemistry


Dalton transactions
Journal: Dalton transactions


Rsc advances
Journal: Rsc advances


Chemistryselect
Journal: Chemistryselect


Journal of energy chemistry
Journal: Journal of energy chemistry


Rsc advances
Journal: Rsc advances


Rsc advances
Journal: Rsc advances


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Materials science in semiconductor processing
Journal: Materials science in semiconductor processing


Rsc advances
Journal: Rsc advances


Rsc advances
Journal: Rsc advances


Dalton transactions
Journal: Dalton transactions


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Rsc advances
Journal: Rsc advances


Acs applied energy materials
Journal: Acs applied energy materials


Chemistry of materials
Journal: Chemistry of materials


Advanced optical materials
Journal: Advanced optical materials


Crystengcomm
Journal: Crystengcomm


Chemistry of materials
Journal: Chemistry of materials


Journal of semiconductors
Journal: Journal of semiconductors


Acs central science
Journal: Acs central science


Energy technology
Journal: Energy technology


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Applied physics letters
Journal: Applied physics letters


Applied surface science
Journal: Applied surface science


Beilstein journal of nanotechnology
Journal: Beilstein journal of nanotechnology


Beilstein journal of nanotechnology
Journal: Beilstein journal of nanotechnology


Thin solid films
Journal: Thin solid films


Beilstein journal of nanotechnology
Journal: Beilstein journal of nanotechnology


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Applied surface science
Journal: Applied surface science


Thin solid films
Journal: Thin solid films


Vacuum
Journal: Vacuum


Macromolecular bioscience
Journal: Macromolecular bioscience


Applied surface science
Journal: Applied surface science


Journal of electrical engineering
Journal: Journal of electrical engineering


Appl. surf. sci.
Journal: Appl. surf. sci.


Phys. status solidi a
Journal: Phys. status solidi a


Physica status solidi (a)
Journal: Physica status solidi (a)


Int. j. electrochem. sci
Journal: Int. j. electrochem. sci


Applied surface science
Journal: Applied surface science


Materials
Journal: Materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Chemosensors
Journal: Chemosensors


한국진공학회 학술발표회초록집
Journal: 한국진공학회 학술발표회초록집


Acta universitatis carolinae. mathematica et physica
Journal: Acta universitatis carolinae. mathematica et physica


Nature energy
Journal: Nature energy


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Inorganic chemistry
Journal: Inorganic chemistry


Inorganic chemistry
Journal: Inorganic chemistry


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Inorganic chemistry
Journal: Inorganic chemistry


Small methods
Journal: Small methods


Materials advances
Journal: Materials advances


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


New journal of chemistry
Journal: New journal of chemistry


Inorganic chemistry frontiers
Journal: Inorganic chemistry frontiers


Polyhedron
Journal: Polyhedron


Small
Journal: Small


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Molecules
Journal: Molecules


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Polyhedron
Journal: Polyhedron


Iscience
Journal: Iscience


Spectrochimica acta part a: molecular and biomolecular spectroscopy
Journal: Spectrochimica acta part a: molecular and biomolecular spectroscopy


Journal of solid state chemistry
Journal: Journal of solid state chemistry


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs materials au
Journal: Acs materials au


Chemical communications
Journal: Chemical communications


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Rsc advances
Journal: Rsc advances


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Chemical physics letters 506 (4-6)
Journal: Chemical physics letters 506 (4-6)


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


Chemphyschem
Journal: Chemphyschem


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Nucleic acids research
Journal: Nucleic acids research


Carbon
Journal: Carbon


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


Scientific reports
Journal: Scientific reports


Journal of molecular structure
Journal: Journal of molecular structure


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Faraday discussions
Journal: Faraday discussions


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of optics
Journal: Journal of optics


Faraday discussions
Journal: Faraday discussions


Journal of luminescence
Journal: Journal of luminescence


Journal of applied physics
Journal: Journal of applied physics


Journal of biological physics
Journal: Journal of biological physics


Biophysical journal
Journal: Biophysical journal


Biophysical journal
Journal: Biophysical journal


Faraday discussions
Journal: Faraday discussions


Faraday discussions
Journal: Faraday discussions


Methods and applications in fluorescence
Journal: Methods and applications in fluorescence


Biophysical journal
Journal: Biophysical journal


Solar energy
Journal: Solar energy


Journal of applied physics
Journal: Journal of applied physics


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Solar energy
Journal: Solar energy


Journal of applied physics
Journal: Journal of applied physics


Physical review b
Journal: Physical review b


International journal in multidisciplinary studies (ijms)
Journal: International journal in multidisciplinary studies (ijms)


International journal of multidisciplinary studies
Journal: International journal of multidisciplinary studies


Journal of the national science foundation of sri lanka
Journal: Journal of the national science foundation of sri lanka


Nature energy
Journal: Nature energy


J. am. chem. soc
Journal: J. am. chem. soc


Journal of the american chemical society
Journal: Journal of the american chemical society


Angewandte chemie international edition
Journal: Angewandte chemie international edition


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Phys. rev. b
Journal: Phys. rev. b


Chemical science
Journal: Chemical science


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Green chemistry
Journal: Green chemistry


Chemical science
Journal: Chemical science


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Phys. rev. materials
Journal: Phys. rev. materials


Physical review b
Journal: Physical review b


Chemical science
Journal: Chemical science


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Physical review b
Journal: Physical review b


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Physical review b
Journal: Physical review b


Acs energy letters
Journal: Acs energy letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


The journal of chemical physics
Journal: The journal of chemical physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry a
Journal: The journal of physical chemistry a


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of physics: energy
Journal: Journal of physics: energy


Frontiers in chemistry
Journal: Frontiers in chemistry


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of the american chemical society
Journal: Journal of the american chemical society


The european physical journal d
Journal: The european physical journal d


Nature energy
Journal: Nature energy


J. am. chem. soc
Journal: J. am. chem. soc


Journal of the american chemical society
Journal: Journal of the american chemical society


Angewandte chemie international edition
Journal: Angewandte chemie international edition


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Phys. rev. b
Journal: Phys. rev. b


Chemical science
Journal: Chemical science


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Green chemistry
Journal: Green chemistry


Chemical science
Journal: Chemical science


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Phys. rev. materials
Journal: Phys. rev. materials


Physical review b
Journal: Physical review b


Chemical science
Journal: Chemical science


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Physical review b
Journal: Physical review b


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Physical review b
Journal: Physical review b


Acs energy letters
Journal: Acs energy letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


The journal of chemical physics
Journal: The journal of chemical physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry a
Journal: The journal of physical chemistry a


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of physics: energy
Journal: Journal of physics: energy


Frontiers in chemistry
Journal: Frontiers in chemistry


Journal of physics: condensed matter

Advanced materials interfaces
Journal: Advanced materials interfaces


Advanced energy materials
Journal: Advanced energy materials


Scientific reports
Journal: Scientific reports


Materials today 30,
Journal: Materials today 30


Science
Journal: Science


Nano letters
Journal: Nano letters


Nature communications
Journal: Nature communications


Acs nano
Journal: Acs nano


Nature
Journal: Nature


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs nano
Journal: Acs nano


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs nano
Journal: Acs nano


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Structural dynamics
Journal: Structural dynamics


Nano letters
Journal: Nano letters


Nano letters
Journal: Nano letters


Advanced optical materials
Journal: Advanced optical materials


Applied physics letters
Journal: Applied physics letters


Chemistry of materials
Journal: Chemistry of materials


1foldr import 2019-10-08 batch
Journal: 1foldr import 2019-10-08 batch


Advanced materials
Journal: Advanced materials


Acs nano, s1-s
Journal: Acs nano


Acta materialia
Journal: Acta materialia


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Angewandte chemie
Journal: Angewandte chemie


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Annual review of materials research
Journal: Annual review of materials research


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Scripta materialia
Journal: Scripta materialia


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Acta materialia
Journal: Acta materialia


International journal of material and mechanical engineering
Journal: International journal of material and mechanical engineering


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Scripta materialia
Journal: Scripta materialia


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Materials &design
Journal: Materials &design


Scripta materialia
Journal: Scripta materialia


Frontiers in materials
Journal: Frontiers in materials


Coatings
Journal: Coatings


Scripta materialia
Journal: Scripta materialia


Ceramics international
Journal: Ceramics international


Acta materialia
Journal: Acta materialia


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Angewandte chemie
Journal: Angewandte chemie


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Annual review of materials research
Journal: Annual review of materials research


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Scripta materialia
Journal: Scripta materialia


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Acta materialia
Journal: Acta materialia


International journal of material and mechanical engineering
Journal: International journal of material and mechanical engineering


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Scripta materialia
Journal: Scripta materialia


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Materials &design
Journal: Materials &design


Scripta materialia
Journal: Scripta materialia


Frontiers in materials
Journal: Frontiers in materials


Coatings
Journal: Coatings


Scripta materialia
Journal: Scripta materialia


Ceramics international
Journal: Ceramics international


Chemical communications
Journal: Chemical communications


Angewandte chemie
Journal: Angewandte chemie


Nature materials
Journal: Nature materials


Advanced energy materials
Journal: Advanced energy materials


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Small methods
Journal: Small methods


Nanoscale
Journal: Nanoscale


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nano energy
Journal: Nano energy


Nanoscale
Journal: Nanoscale


Advanced science
Journal: Advanced science


Science china materials
Journal: Science china materials


Rsc advances
Journal: Rsc advances


Advanced functional materials
Journal: Advanced functional materials


Angewandte chemie
Journal: Angewandte chemie


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Solar rrl
Journal: Solar rrl


Small methods
Journal: Small methods


Advanced functional materials
Journal: Advanced functional materials


Advanced energy materials
Journal: Advanced energy materials


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Chemical communications
Journal: Chemical communications


Angewandte chemie
Journal: Angewandte chemie


Nature materials
Journal: Nature materials


Advanced energy materials
Journal: Advanced energy materials


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Small methods
Journal: Small methods


Nanoscale
Journal: Nanoscale


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nano energy
Journal: Nano energy


Nanoscale
Journal: Nanoscale


Advanced science
Journal: Advanced science


Science china materials
Journal: Science china materials


Rsc advances
Journal: Rsc advances


Advanced functional materials
Journal: Advanced functional materials


Angewandte chemie
Journal: Angewandte chemie


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Solar rrl
Journal: Solar rrl


Small methods
Journal: Small methods


Advanced functional materials
Journal: Advanced functional materials


Advanced energy materials
Journal: Advanced energy materials


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nano energy
Journal: Nano energy


Synthetic metals
Journal: Synthetic metals


Applied surface science
Journal: Applied surface science


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Crystal growth &design
Journal: Crystal growth &design


Materials research bulletin
Journal: Materials research bulletin


Materials research bulletin
Journal: Materials research bulletin


Journal of applied physics
Journal: Journal of applied physics


Journal of applied physics
Journal: Journal of applied physics


Materials letters
Journal: Materials letters


Nano energy
Journal: Nano energy


Ferroelectrics
Journal: Ferroelectrics


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Langmuir
Journal: Langmuir


Solar energy
Journal: Solar energy


Applied physics letters
Journal: Applied physics letters


Materials letters
Journal: Materials letters


Interfaces
Journal: Interfaces


Applied physics reviews
Journal: Applied physics reviews


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Materials research express
Journal: Materials research express


Materials research express
Journal: Materials research express


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Nano energy
Journal: Nano energy


Materials research innovations
Journal: Materials research innovations


Nature
Journal: Nature


Nature nanotechnology
Journal: Nature nanotechnology


Science
Journal: Science


Science advances
Journal: Science advances


Science advances
Journal: Science advances


Acs energy letters
Journal: Acs energy letters


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Methods and protocols
Journal: Methods and protocols


Cleo: science and innovations, sf1o.
Journal: Cleo: science and innovations


Cleo: qels_fundamental science, ftu1o.
Journal: Cleo: qels_fundamental science


Cleo: qels_fundamental science, ftu1o.
Journal: Cleo: qels_fundamental science


Cleo: qels_fundamental science, fm4f.
Journal: Cleo: qels_fundamental science


Cleo: qels_fundamental science, fth4f.
Journal: Cleo: qels_fundamental science


Cleo: qels_fundamental science, fth4f.
Journal: Cleo: qels_fundamental science


Aip advances
Journal: Aip advances


Applied physics a
Journal: Applied physics a


Computational condensed matter
Journal: Computational condensed matter


Acta physica polonica, a.
Journal: Acta physica polonica


Journal of alloys and compounds
Journal: Journal of alloys and compounds


The european physical journal plus
Journal: The european physical journal plus


Journal of theoretical and computational chemistry
Journal: Journal of theoretical and computational chemistry


Chinese journal of physics
Journal: Chinese journal of physics


Chinese journal of physics
Journal: Chinese journal of physics


Chinese journal of physics
Journal: Chinese journal of physics


Journal of electronic materials
Journal: Journal of electronic materials


Chinese physics b
Journal: Chinese physics b


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


International journal of quantum chemistry
Journal: International journal of quantum chemistry


Applied physics a
Journal: Applied physics a


Crystal research and technology
Journal: Crystal research and technology


Chemical physics letters
Journal: Chemical physics letters


High temperatures--high pressures
Journal: High temperatures--high pressures


Polyhedron
Journal: Polyhedron


High temperatures--high pressures
Journal: High temperatures--high pressures


Materials science in semiconductor processing
Journal: Materials science in semiconductor processing


Ecs journal of solid state science and technology
Journal: Ecs journal of solid state science and technology


Journal of computational electronics
Journal: Journal of computational electronics


Canadian journal of physics
Journal: Canadian journal of physics


Indian journal of physics
Journal: Indian journal of physics


Nature energy
Journal: Nature energy


Acs energy letters
Journal: Acs energy letters


Chemistry of materials
Journal: Chemistry of materials


Nature communications
Journal: Nature communications


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Chemsuschem
Journal: Chemsuschem


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs energy letters
Journal: Acs energy letters


Advanced optical materials
Journal: Advanced optical materials


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Advanced energy materials
Journal: Advanced energy materials


Nano letters
Journal: Nano letters


Acs energy letters
Journal: Acs energy letters


Advanced functional materials
Journal: Advanced functional materials


Acs energy letters
Journal: Acs energy letters


Advanced materials
Journal: Advanced materials


Communications chemistry
Journal: Communications chemistry


Acs energy letters
Journal: Acs energy letters


Nature energy
Journal: Nature energy


Acs energy letters
Journal: Acs energy letters


Chemistry of materials
Journal: Chemistry of materials


Nature communications
Journal: Nature communications


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Chemsuschem
Journal: Chemsuschem


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs energy letters
Journal: Acs energy letters


Advanced optical materials
Journal: Advanced optical materials


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Advanced energy materials
Journal: Advanced energy materials


Nano letters
Journal: Nano letters


Acs energy letters
Journal: Acs energy letters


Advanced functional materials
Journal: Advanced functional materials


Acs energy letters
Journal: Acs energy letters


Advanced materials
Journal: Advanced materials


Communications chemistry
Journal: Communications chemistry


Acs energy letters
Journal: Acs energy letters


Joule
Journal: Joule


Energy &environmental science
Journal: Energy &environmental science


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Nano today
Journal: Nano today


Advanced materials
Journal: Advanced materials


Physical review applied
Journal: Physical review applied


Energy &environmental science
Journal: Energy &environmental science


Energy &environmental science
Journal: Energy &environmental science


Joule
Journal: Joule


Rsc advances
Journal: Rsc advances


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Physical review b
Journal: Physical review b


Acs photonics
Journal: Acs photonics


Pure and applied chemistry
Journal: Pure and applied chemistry


Science advances
Journal: Science advances


Joule
Journal: Joule


Energy &environmental science
Journal: Energy &environmental science


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Nano today
Journal: Nano today


Advanced materials
Journal: Advanced materials


Physical review applied
Journal: Physical review applied


Energy &environmental science
Journal: Energy &environmental science


Energy &environmental science
Journal: Energy &environmental science


Joule
Journal: Joule


Rsc advances
Journal: Rsc advances


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Physical review b
Journal: Physical review b


Acs photonics
Journal: Acs photonics


Pure and applied chemistry
Journal: Pure and applied chemistry


Science advances
Journal: Science advances


Advanced energy materials
Journal: Advanced energy materials


Applied physics letters
Journal: Applied physics letters


Advanced materials
Journal: Advanced materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Chemistry of materials
Journal: Chemistry of materials


Science advances
Journal: Science advances


Advanced science
Journal: Advanced science


Acs nano
Journal: Acs nano


Acs photonics
Journal: Acs photonics


Acs photonics
Journal: Acs photonics


Nanoscale
Journal: Nanoscale


Advanced materials
Journal: Advanced materials


Optics express
Journal: Optics express


Acs photonics
Journal: Acs photonics


Light: science &applications
Journal: Light: science &applications


Chinese physics b
Journal: Chinese physics b


Nanoscale
Journal: Nanoscale


Journal of applied physics
Journal: Journal of applied physics


Nature communications
Journal: Nature communications


Nano letters
Journal: Nano letters


Science advances
Journal: Science advances


Advanced energy materials
Journal: Advanced energy materials


Applied physics letters
Journal: Applied physics letters


Nanoimaging and nanospectroscopy iv
Journal: Nanoimaging and nanospectroscopy iv


Chemical science
Journal: Chemical science


Electrochimica acta
Journal: Electrochimica acta


Applied surface science
Journal: Applied surface science


European journal of medicinal chemistry
Journal: European journal of medicinal chemistry


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


European journal of medicinal chemistry
Journal: European journal of medicinal chemistry


Ecomat
Journal: Ecomat


Small
Journal: Small


Chemmedchem
Journal: Chemmedchem


Nature communications
Journal: Nature communications


Inorganic chemistry
Journal: Inorganic chemistry


Acs applied bio materials
Journal: Acs applied bio materials


Advanced optical materials
Journal: Advanced optical materials


Bioorganic chemistry
Journal: Bioorganic chemistry


Nano research
Journal: Nano research


Biochimica et biophysica acta (bba)-biomembranes
Journal: Biochimica et biophysica acta (bba)-biomembranes


Optics letters
Journal: Optics letters


Chemical engineering journal
Journal: Chemical engineering journal


Journal of rare earths
Journal: Journal of rare earths


Food control
Journal: Food control


Cellulose
Journal: Cellulose


Optics letters
Journal: Optics letters


Acs nano
Journal: Acs nano


Acs nano
Journal: Acs nano


New journal of chemistry
Journal: New journal of chemistry


Advanced optical materials
Journal: Advanced optical materials


Applied materials today
Journal: Applied materials today


Materials &design
Journal: Materials &design


Electrochimica acta
Journal: Electrochimica acta


Carbon
Journal: Carbon


Applied surface science
Journal: Applied surface science


Current applied physics
Journal: Current applied physics


Journal of energy chemistry
Journal: Journal of energy chemistry


Catalysis today
Journal: Catalysis today


Catalysis communications
Journal: Catalysis communications


Carbon
Journal: Carbon


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Macromolecular rapid communications
Journal: Macromolecular rapid communications


Current applied physics
Journal: Current applied physics


Molecular catalysis
Journal: Molecular catalysis


Biochemical engineering journal
Journal: Biochemical engineering journal


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Applied surface science
Journal: Applied surface science


Energy technology
Journal: Energy technology


Korean journal of materials research
Journal: Korean journal of materials research


Electrochimica acta
Journal: Electrochimica acta


Molecular catalysis
Journal: Molecular catalysis


Macromolecular rapid communications
Journal: Macromolecular rapid communications


Journal of the electrochemical society
Journal: Journal of the electrochemical society


폴리머
Journal: 폴리머


Applied surface science
Journal: Applied surface science


Journal of applied polymer science
Journal: Journal of applied polymer science


Journal of rare earths
Journal: Journal of rare earths


Molecular catalysis
Journal: Molecular catalysis


Korean journal of materials research
Journal: Korean journal of materials research


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces



Sensors and actuators b: chemical
Journal: Sensors and actuators b: chemical


Nanotechnology
Journal: Nanotechnology


Nanotechnology
Journal: Nanotechnology


Nanotechnology
Journal: Nanotechnology


Nano energy
Journal: Nano energy


Acs applied nano materials
Journal: Acs applied nano materials


Journal of colloid and interface science
Journal: Journal of colloid and interface science


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Journal of raman spectroscopy
Journal: Journal of raman spectroscopy


Applied physics letters
Journal: Applied physics letters


Npg asia materials
Journal: Npg asia materials


Rsc advances
Journal: Rsc advances


Sensors and actuators b: chemical
Journal: Sensors and actuators b: chemical


Npg asia materials
Journal: Npg asia materials


Advanced science letters
Journal: Advanced science letters


Sci. adv. today
Journal: Sci. adv. today


Advanced functional materials
Journal: Advanced functional materials


Angewandte chemie
Journal: Angewandte chemie


Physical review letters
Journal: Physical review letters


Physical review b
Journal: Physical review b


Advanced functional materials
Journal: Advanced functional materials


Physical review letters
Journal: Physical review letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Advanced materials
Journal: Advanced materials


Physical review letters
Journal: Physical review letters


Inorganic chemistry
Journal: Inorganic chemistry


Solid state ionics
Journal: Solid state ionics


Acs omega
Journal: Acs omega


Rsc advances
Journal: Rsc advances


Digital discovery
Journal: Digital discovery


Physical review materials
Journal: Physical review materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review b
Journal: Physical review b


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Dalton transactions
Journal: Dalton transactions


Physical review b
Journal: Physical review b


Catalysis science &technology
Journal: Catalysis science &technology


Physical review b
Journal: Physical review b


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of catalysis
Journal: Journal of catalysis


Computational materials science
Journal: Computational materials science


Chemcatchem
Journal: Chemcatchem


Organometallics
Journal: Organometallics


Physical review b
Journal: Physical review b


Inorganic chemistry
Journal: Inorganic chemistry


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Rsc advances
Journal: Rsc advances


Computational materials science
Journal: Computational materials science


Applied surface science
Journal: Applied surface science


Solid state sciences
Journal: Solid state sciences


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Journal of molecular graphics and modelling
Journal: Journal of molecular graphics and modelling


Dalton transactions
Journal: Dalton transactions


Chemical physics letters
Journal: Chemical physics letters


Ultrasonics sonochemistry
Journal: Ultrasonics sonochemistry


Ceramics international
Journal: Ceramics international


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Journal of electronic materials
Journal: Journal of electronic materials


Ceramics international
Journal: Ceramics international


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Chemical engineering journal
Journal: Chemical engineering journal


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Nanotechnology
Journal: Nanotechnology


Materials science in semiconductor processing
Journal: Materials science in semiconductor processing


Chemical engineering journal
Journal: Chemical engineering journal


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Sn applied sciences
Journal: Sn applied sciences


Ceramics international
Journal: Ceramics international


Bulletin of materials science
Journal: Bulletin of materials science


Journal of porous materials
Journal: Journal of porous materials


Colloids and surfaces b: biointerfaces
Journal: Colloids and surfaces b: biointerfaces


Materials science in semiconductor processing
Journal: Materials science in semiconductor processing


Ionics
Journal: Ionics


Journal of colloid and interface science
Journal: Journal of colloid and interface science


Applied physics a
Journal: Applied physics a


Scientific reports
Journal: Scientific reports


Small
Journal: Small


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Scientific reports
Journal: Scientific reports


Advanced sustainable systems
Journal: Advanced sustainable systems


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of the korean physical society
Journal: Journal of the korean physical society


Acs nano
Journal: Acs nano


Advanced energy materials
Journal: Advanced energy materials


Acs energy letters
Journal: Acs energy letters


Journal of the korean physical society
Journal: Journal of the korean physical society


Journal of the korean physical society
Journal: Journal of the korean physical society


Advanced energy materials
Journal: Advanced energy materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Scientific reports
Journal: Scientific reports


Applied surface science
Journal: Applied surface science


Advanced photonics research
Journal: Advanced photonics research


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Chemistry of materials
Journal: Chemistry of materials


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


New journal of chemistry
Journal: New journal of chemistry


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Physical review b
Journal: Physical review b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Scientific reports
Journal: Scientific reports


Journal of physics: materials
Journal: Journal of physics: materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Scientific reports
Journal: Scientific reports


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Nanoscale advances
Journal: Nanoscale advances


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Materials advances
Journal: Materials advances


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Applied physics letters
Journal: Applied physics letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Applied physics letters
Journal: Applied physics letters


Journal of physics: materials
Journal: Journal of physics: materials


Scientific reports
Journal: Scientific reports


Apl materials
Journal: Apl materials


Nature communications
Journal: Nature communications


Scientific reports
Journal: Scientific reports


Acs photonics
Journal: Acs photonics


The journal of chemical physics
Journal: The journal of chemical physics


Energy &environmental science
Journal: Energy &environmental science


Physical review applied
Journal: Physical review applied


Physical review applied
Journal: Physical review applied


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Ultrafast phenomena and nanophotonics xxi
Journal: Ultrafast phenomena and nanophotonics xxi


Advanced functional materials
Journal: Advanced functional materials


Frontiers in biological detection: from nanosensors to systems xiv
Journal: Frontiers in biological detection: from nanosensors to systems xiv


Physical chemistry of semiconductor materials and interfaces xx
Journal: Physical chemistry of semiconductor materials and interfaces xx


Physical chemistry of semiconductor materials and interfaces xx
Journal: Physical chemistry of semiconductor materials and interfaces xx


Nature communications
Journal: Nature communications


Nature communications
Journal: Nature communications


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Rsc advances
Journal: Rsc advances


Physica b: condensed matter
Journal: Physica b: condensed matter


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Inorganic chemistry communications
Journal: Inorganic chemistry communications


Ceramics international
Journal: Ceramics international


Journal of rare earths
Journal: Journal of rare earths


Journal of superconductivity and novel magnetism
Journal: Journal of superconductivity and novel magnetism


Journal of superconductivity and novel magnetism
Journal: Journal of superconductivity and novel magnetism


Journal of superconductivity and novel magnetism
Journal: Journal of superconductivity and novel magnetism


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Journal of superconductivity and novel magnetism
Journal: Journal of superconductivity and novel magnetism


Journal of low temperature physics
Journal: Journal of low temperature physics


Journal of superconductivity and novel magnetism
Journal: Journal of superconductivity and novel magnetism


Journal of superconductivity and novel magnetism
Journal: Journal of superconductivity and novel magnetism


Journal of superconductivity and novel magnetism
Journal: Journal of superconductivity and novel magnetism


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Physica. b, condensed matter
Journal: Physica. b


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Science
Journal: Science


Energy &environmental science
Journal: Energy &environmental science


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced energy materials
Journal: Advanced energy materials


Acs photonics
Journal: Acs photonics


Acs applied energy materials
Journal: Acs applied energy materials


Journal of applied physics
Journal: Journal of applied physics


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Chemsuschem
Journal: Chemsuschem


Acs photonics
Journal: Acs photonics


Energy technology
Journal: Energy technology


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemsuschem
Journal: Chemsuschem


Energy &environmental science
Journal: Energy &environmental science


Advanced energy materials
Journal: Advanced energy materials


Joule
Journal: Joule


Energy &environmental science
Journal: Energy &environmental science


Energy &environmental science
Journal: Energy &environmental science


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced energy materials
Journal: Advanced energy materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Science
Journal: Science


Acs energy letters
Journal: Acs energy letters


Small methods
Journal: Small methods


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemical science
Journal: Chemical science


Prx energy
Journal: Prx energy


Small methods
Journal: Small methods


Advanced energy materials
Journal: Advanced energy materials


Joule
Journal: Joule


Energy &environmental science
Journal: Energy &environmental science


Energy &environmental science
Journal: Energy &environmental science


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced energy materials
Journal: Advanced energy materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Science
Journal: Science


Acs energy letters
Journal: Acs energy letters


Small methods
Journal: Small methods


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemical science
Journal: Chemical science


Prx energy
Journal: Prx energy


Small methods
Journal: Small methods


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Chemical communications
Journal: Chemical communications


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs catalysis
Journal: Acs catalysis


Acs materials letters
Journal: Acs materials letters


Chemical science
Journal: Chemical science


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Tetrahedron
Journal: Tetrahedron


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Chemistry of materials
Journal: Chemistry of materials


Acs materials letters
Journal: Acs materials letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Nano convergence
Journal: Nano convergence


Advanced science
Journal: Advanced science


Nanotechnology
Journal: Nanotechnology


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Carbon
Journal: Carbon


Advanced optical materials
Journal: Advanced optical materials


Journal of pharmaceutical innovation
Journal: Journal of pharmaceutical innovation


Sensor review
Journal: Sensor review


Nanoscale horizons
Journal: Nanoscale horizons


Ieee transactions on nanotechnology
Journal: Ieee transactions on nanotechnology


Rsc advances
Journal: Rsc advances


Ieee transactions on electron devices
Journal: Ieee transactions on electron devices


Ecs solid state letters
Journal: Ecs solid state letters


Applied physics express
Journal: Applied physics express


Applied physics letters
Journal: Applied physics letters


Ecs journal of solid state science and technology
Journal: Ecs journal of solid state science and technology


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Ecs journal of solid state science and technology
Journal: Ecs journal of solid state science and technology


Solid-state electronics
Journal: Solid-state electronics


Japanese journal of applied physics 53 (3s1), 03cc
Journal: Japanese journal of applied physics 53 (3s1)


Ieee transactions on electron devices
Journal: Ieee transactions on electron devices


Ecs journal of solid state science and technology
Journal: Ecs journal of solid state science and technology


Materials letters
Journal: Materials letters


Ieee transactions on electron devices
Journal: Ieee transactions on electron devices


Ecs solid state letters
Journal: Ecs solid state letters


Ecs transactions
Journal: Ecs transactions


Ecs transactions
Journal: Ecs transactions


Scientific reports
Journal: Scientific reports


Nature communications
Journal: Nature communications


Nanoscale
Journal: Nanoscale


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced functional materials
Journal: Advanced functional materials


Nanomaterials
Journal: Nanomaterials


Energy science &engineering
Journal: Energy science &engineering


Advanced functional materials
Journal: Advanced functional materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Ecs transactions
Journal: Ecs transactions


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Ecs transactions
Journal: Ecs transactions


Ecs transactions
Journal: Ecs transactions


Nanoscale
Journal: Nanoscale


Nanoscale advances
Journal: Nanoscale advances


Inorganic chemistry
Journal: Inorganic chemistry


Chemical communications
Journal: Chemical communications


Chemical communications
Journal: Chemical communications


Iucrj
Journal: Iucrj


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced materials
Journal: Advanced materials


Crystals
Journal: Crystals


Iucrj
Journal: Iucrj


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Dalton transactions
Journal: Dalton transactions


Dalton transactions
Journal: Dalton transactions


Chemistry of materials
Journal: Chemistry of materials


Inorganic chemistry
Journal: Inorganic chemistry


European journal of inorganic chemistry
Journal: European journal of inorganic chemistry


Apl materials
Journal: Apl materials


Chemistry of materials
Journal: Chemistry of materials


Acta crystallographica section b: structural science, crystal engineering …
Journal: Acta crystallographica section b: structural science


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Advanced materials
Journal: Advanced materials


Arpn journal of engineering and applied sciences
Journal: Arpn journal of engineering and applied sciences


Int. j. mech. mechatronics eng. ijmme-ijens
Journal: Int. j. mech. mechatronics eng. ijmme-ijens


Jurnal teknologi
Journal: Jurnal teknologi


Jurnal teknologi
Journal: Jurnal teknologi


Electrochimica acta
Journal: Electrochimica acta


International journal on advanced science, engineering and information …
Journal: International journal on advanced science


Journal of telecommunication, electronic and computer engineering (jtec) 8 …
Journal: Journal of telecommunication


Electrochimica acta
Journal: Electrochimica acta


Journal of telecommunication, electronic and computer engineering (jtec) 10 …
Journal: Journal of telecommunication


Journal of telecommunication, electronic and computer engineering (jtec) 10 …

Journal of applied physics
Journal: Journal of applied physics


Materials chemistry and physics
Journal: Materials chemistry and physics


Ceramics international
Journal: Ceramics international


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Ceramics international
Journal: Ceramics international


Ceramics international
Journal: Ceramics international


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Journal of sol-gel science and technology
Journal: Journal of sol-gel science and technology


Journal of low temperature physics 207 (1-2)
Journal: Journal of low temperature physics 207 (1-2)


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Journal of non-crystalline solids
Journal: Journal of non-crystalline solids


Ceramics international
Journal: Ceramics international


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Journal of physics and chemistry of solids
Journal: Journal of physics and chemistry of solids


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Acs energy letters
Journal: Acs energy letters


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Molecular crystals and liquid crystals
Journal: Molecular crystals and liquid crystals


Chinese physics b
Journal: Chinese physics b


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Physica e: low-dimensional systems and nanostructures
Journal: Physica e: low-dimensional systems and nanostructures


Jetp letters
Journal: Jetp letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


Chemosphere
Journal: Chemosphere


Science
Journal: Science


Environmental science and pollution research
Journal: Environmental science and pollution research


Water research
Journal: Water research


Bioresource technology
Journal: Bioresource technology


Applied surface science
Journal: Applied surface science


Renewable energy
Journal: Renewable energy


Journal of soils and sediments
Journal: Journal of soils and sediments


Separation and purification technology
Journal: Separation and purification technology


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Nanoscale
Journal: Nanoscale


Chemical engineering journal
Journal: Chemical engineering journal


Cell reports physical science
Journal: Cell reports physical science


Chemical communications
Journal: Chemical communications


Chemeca 2021: advance, disrupt and sustain: advance, disrupt and sustain
Journal: Chemeca 2021: advance


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


Chemosphere
Journal: Chemosphere


Science
Journal: Science


Environmental science and pollution research
Journal: Environmental science and pollution research


Water research
Journal: Water research


Bioresource technology
Journal: Bioresource technology


Applied surface science
Journal: Applied surface science


Renewable energy
Journal: Renewable energy


Journal of soils and sediments
Journal: Journal of soils and sediments


Separation and purification technology
Journal: Separation and purification technology


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Nanoscale
Journal: Nanoscale


Chemical engineering journal
Journal: Chemical engineering journal


Cell reports physical science
Journal: Cell reports physical science


Chemical communications
Journal: Chemical communications


Chemeca 2021: advance, disrupt and sustain: advance, disrupt and sustain
Journal: Chemeca 2021: advance


Chemistry of materials
Journal: Chemistry of materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Electrochimica acta
Journal: Electrochimica acta


Sensors and actuators b: chemical
Journal: Sensors and actuators b: chemical


Acs nano
Journal: Acs nano


Electrochimica acta
Journal: Electrochimica acta


Chemelectrochem
Journal: Chemelectrochem


Nanotechnology
Journal: Nanotechnology


Nanoscale
Journal: Nanoscale


Nanoscale
Journal: Nanoscale


Applied surface science
Journal: Applied surface science


Nanotechnology
Journal: Nanotechnology


Langmuir
Journal: Langmuir


Acs applied nano materials
Journal: Acs applied nano materials


Journal of colloid and interface science
Journal: Journal of colloid and interface science


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Acs energy letters
Journal: Acs energy letters


Apl materials
Journal: Apl materials


Energy &environmental science
Journal: Energy &environmental science


Acs energy letters
Journal: Acs energy letters


Advanced energy materials
Journal: Advanced energy materials


Solar rrl
Journal: Solar rrl


Advanced energy materials
Journal: Advanced energy materials


Solar rrl
Journal: Solar rrl


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced energy materials
Journal: Advanced energy materials


Nature communications
Journal: Nature communications


Energy &environmental science
Journal: Energy &environmental science


Acs applied energy materials
Journal: Acs applied energy materials


Organic electronics
Journal: Organic electronics


Advanced functional materials
Journal: Advanced functional materials


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


Thin solid films
Journal: Thin solid films


Applied physics letters
Journal: Applied physics letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Eng
Journal: Eng


Energy technology
Journal: Energy technology


Epj photovoltaics
Journal: Epj photovoltaics


Energies
Journal: Energies


Epj photovoltaics
Journal: Epj photovoltaics


Acs energy letters
Journal: Acs energy letters


Advanced materials
Journal: Advanced materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Sustainable energy &fuels
Journal: Sustainable energy &fuels


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of luminescence
Journal: Journal of luminescence


Apl materials
Journal: Apl materials


Advanced energy materials
Journal: Advanced energy materials


The journal of chemical physics
Journal: The journal of chemical physics


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Mediterranean archaeology &archaeometry
Journal: Mediterranean archaeology &archaeometry


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


Acs applied nano materials
Journal: Acs applied nano materials


Matter
Journal: Matter


Journal of environmental sciences
Journal: Journal of environmental sciences


Chemistry–a european journal
Journal: Chemistry–a european journal


Environmental science: nano
Journal: Environmental science: nano


Journal of environmental chemical engineering
Journal: Journal of environmental chemical engineering


Nano energy
Journal: Nano energy


Clean technologies and environmental policy
Journal: Clean technologies and environmental policy


Environmental science and pollution research
Journal: Environmental science and pollution research


Analytical methods
Journal: Analytical methods


Journal of environmental sciences
Journal: Journal of environmental sciences


Rsc advances
Journal: Rsc advances


Phosphorus, sulfur, and silicon and the related elements
Journal: Phosphorus


Science advances
Journal: Science advances


Advanced energy materials
Journal: Advanced energy materials


Advanced science
Journal: Advanced science


Nano energy
Journal: Nano energy


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Nano energy
Journal: Nano energy


Nano energy
Journal: Nano energy


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Nature catalysis
Journal: Nature catalysis


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of power sources
Journal: Journal of power sources


Advanced science
Journal: Advanced science


한국에너지기후변화학회 학술대회
Journal: 한국에너지기후변화학회 학술대회


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Advanced materials
Journal: Advanced materials


Nano research
Journal: Nano research


Journal of optics
Journal: Journal of optics


Nano research
Journal: Nano research


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Advanced materials
Journal: Advanced materials


Advanced optical materials
Journal: Advanced optical materials


Nano research
Journal: Nano research


Advanced functional materials
Journal: Advanced functional materials


Apl materials
Journal: Apl materials


Advanced optical materials
Journal: Advanced optical materials


Acs nano
Journal: Acs nano


Infomat
Journal: Infomat


Advanced materials
Journal: Advanced materials


Advanced optical materials
Journal: Advanced optical materials


Nano letters
Journal: Nano letters


Journal of alloys and compounds
Journal: Journal of alloys and compounds


International journal of science and research (ijsr)
Journal: International journal of science and research (ijsr)


Materials characterization
Journal: Materials characterization


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Int. j. chem. sci
Journal: Int. j. chem. sci


Advanced materials research
Journal: Advanced materials research


International journal of industrial chemistry
Journal: International journal of industrial chemistry


Oriental journal of chemistry
Journal: Oriental journal of chemistry


Oriental journal of chemistry
Journal: Oriental journal of chemistry


Oriental journal of chemistry
Journal: Oriental journal of chemistry


Oriental journal of chemistry
Journal: Oriental journal of chemistry


Oriental journal of chemistry
Journal: Oriental journal of chemistry


Energy and environment focus
Journal: Energy and environment focus


European journal of physics
Journal: European journal of physics


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Chemelectrochem
Journal: Chemelectrochem


Physica status solidi (a)
Journal: Physica status solidi (a)


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Applied surface science
Journal: Applied surface science


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Physics education
Journal: Physics education


Chemphyschem
Journal: Chemphyschem


Journal of luminescence
Journal: Journal of luminescence


Electrochimica acta
Journal: Electrochimica acta


Physical review materials
Journal: Physical review materials


Physical review b
Journal: Physical review b


Applied physics letters
Journal: Applied physics letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Physical review materials
Journal: Physical review materials


Acs applied electronic materials
Journal: Acs applied electronic materials


Chemical society reviews
Journal: Chemical society reviews


Nature
Journal: Nature


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


Trends in chemistry
Journal: Trends in chemistry


Scripta materialia
Journal: Scripta materialia


Nanotechnology
Journal: Nanotechnology


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Chemistry–a european journal
Journal: Chemistry–a european journal


Apl materials
Journal: Apl materials


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Mrs bulletin
Journal: Mrs bulletin


Advanced energy materials
Journal: Advanced energy materials


Angewandte chemie
Journal: Angewandte chemie


Advanced energy materials
Journal: Advanced energy materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Small
Journal: Small


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Materials today physics
Journal: Materials today physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nanoscale
Journal: Nanoscale


Nanotechnology
Journal: Nanotechnology


Advanced energy materials
Journal: Advanced energy materials


Advanced materials
Journal: Advanced materials


Energy &environmental science
Journal: Energy &environmental science


Nano energy
Journal: Nano energy


Advanced energy materials
Journal: Advanced energy materials


Chemical science
Journal: Chemical science


Advanced science
Journal: Advanced science


Advanced energy materials
Journal: Advanced energy materials


Organic electronics
Journal: Organic electronics


Advanced energy materials
Journal: Advanced energy materials


Acs energy letters
Journal: Acs energy letters


Advanced energy materials
Journal: Advanced energy materials


Nano energy
Journal: Nano energy


Advanced functional materials
Journal: Advanced functional materials


Advanced energy materials
Journal: Advanced energy materials


Ieee journal of selected topics in quantum electronics
Journal: Ieee journal of selected topics in quantum electronics


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs energy letters
Journal: Acs energy letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Infomat
Journal: Infomat


Cryogenics
Journal: Cryogenics


Langmuir
Journal: Langmuir


Nature communications
Journal: Nature communications


Infomat
Journal: Infomat


Science
Journal: Science


Energy &environmental materials
Journal: Energy &environmental materials


Joule
Journal: Joule


Rsc advances
Journal: Rsc advances


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Solar rrl
Journal: Solar rrl


Applied physics letters
Journal: Applied physics letters


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Acs sensors
Journal: Acs sensors


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of catalysis
Journal: Journal of catalysis


Analytical chemistry
Journal: Analytical chemistry


Acs applied polymer materials
Journal: Acs applied polymer materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Materials advances
Journal: Materials advances


Acs applied energy materials
Journal: Acs applied energy materials


Nature reviews materials
Journal: Nature reviews materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced energy materials
Journal: Advanced energy materials


Organic electronics
Journal: Organic electronics


Chemistry of materials
Journal: Chemistry of materials


Applied physics letters
Journal: Applied physics letters


Organic electronics
Journal: Organic electronics


Materials advances
Journal: Materials advances


Organic electronics
Journal: Organic electronics


Journal of applied physics
Journal: Journal of applied physics


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced functional materials
Journal: Advanced functional materials


Nature
Journal: Nature


Nature
Journal: Nature


Lille
Journal: Lille


Materials research bulletin
Journal: Materials research bulletin


Applied surface science
Journal: Applied surface science


Materials research bulletin
Journal: Materials research bulletin


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Materials characterization
Journal: Materials characterization


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Ceramics international
Journal: Ceramics international


Ceramics international
Journal: Ceramics international


Ceramics international
Journal: Ceramics international


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Ceramics international
Journal: Ceramics international


Journal of advanced dielectrics
Journal: Journal of advanced dielectrics


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Ceramics international
Journal: Ceramics international


Applied surface science
Journal: Applied surface science


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Journal of nanoparticle research
Journal: Journal of nanoparticle research


Ceramics international
Journal: Ceramics international


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Upb scientific bulletin, series b
Journal: Upb scientific bulletin


Nanomaterials
Journal: Nanomaterials


Journal of materials research and technology
Journal: Journal of materials research and technology


Magnetic, ferroelectric, and multiferroic metal oxides
Journal: Magnetic


University politehnica of bucharest scientific bulletin series b-chemistry …
Journal: University politehnica of bucharest scientific bulletin series b-chemistry …


Nano-structures &nano-objects
Journal: Nano-structures &nano-objects


Organic electronics
Journal: Organic electronics


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Materials
Journal: Materials


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Materials letters
Journal: Materials letters



The journal of physical chemistry c
Journal: The journal of physical chemistry c


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Light-emitting devices, materials, and applications xxiv
Journal: Light-emitting devices


Chemical engineering journal
Journal: Chemical engineering journal


Science
Journal: Science


Advanced materials
Journal: Advanced materials


Nature energy
Journal: Nature energy


Acs energy letters
Journal: Acs energy letters


Advanced energy materials
Journal: Advanced energy materials


Acs energy letters
Journal: Acs energy letters


Solar rrl
Journal: Solar rrl


Science
Journal: Science


Advanced materials
Journal: Advanced materials


Nature energy
Journal: Nature energy


Acs energy letters
Journal: Acs energy letters


Advanced energy materials
Journal: Advanced energy materials


Acs energy letters
Journal: Acs energy letters


Solar rrl
Journal: Solar rrl


Advanced functional materials
Journal: Advanced functional materials


Infomat
Journal: Infomat


Solar rrl
Journal: Solar rrl


Molecules
Journal: Molecules


Acs applied energy materials
Journal: Acs applied energy materials


Organic electronics
Journal: Organic electronics


Advanced optical materials
Journal: Advanced optical materials


Frontiers in materials
Journal: Frontiers in materials


Advanced functional materials
Journal: Advanced functional materials


Infomat
Journal: Infomat


Solar rrl
Journal: Solar rrl


Molecules
Journal: Molecules


Acs applied energy materials
Journal: Acs applied energy materials


Organic electronics
Journal: Organic electronics


Advanced optical materials
Journal: Advanced optical materials


Frontiers in materials
Journal: Frontiers in materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Angewandte chemie
Journal: Angewandte chemie


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced materials interfaces
Journal: Advanced materials interfaces


Chemsuschem
Journal: Chemsuschem


Inorganica chimica acta
Journal: Inorganica chimica acta


Acs catalysis
Journal: Acs catalysis


Angewandte chemie
Journal: Angewandte chemie


Tetrahedron letters
Journal: Tetrahedron letters


Journal of physical organic chemistry
Journal: Journal of physical organic chemistry


Journal of organometallic chemistry
Journal: Journal of organometallic chemistry


Results in chemistry
Journal: Results in chemistry


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Chemical communications
Journal: Chemical communications


Chemcatchem
Journal: Chemcatchem


Applied catalysis a: general
Journal: Applied catalysis a: general


Rsc advances
Journal: Rsc advances


Thermochimica acta
Journal: Thermochimica acta


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Thermochimica acta
Journal: Thermochimica acta


American ceramic society (acers) bulletin
Journal: American ceramic society (acers) bulletin


Journal of membrane science
Journal: Journal of membrane science


Journal of solid state electrochemistry
Journal: Journal of solid state electrochemistry


Journal of industrial and engineering chemistry
Journal: Journal of industrial and engineering chemistry


Organic electronics
Journal: Organic electronics


Applied physics letters
Journal: Applied physics letters


Rsc advances
Journal: Rsc advances


Acs applied energy materials
Journal: Acs applied energy materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Ionics
Journal: Ionics


Thin solid films
Journal: Thin solid films


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nature materials
Journal: Nature materials


Acs energy letters
Journal: Acs energy letters


Acs omega
Journal: Acs omega


Sustainable energy &fuels
Journal: Sustainable energy &fuels


Nature chemistry
Journal: Nature chemistry


Advanced materials
Journal: Advanced materials


Advanced functional materials
Journal: Advanced functional materials


Crystal growth &design
Journal: Crystal growth &design


Applied physics letters
Journal: Applied physics letters


Advanced functional materials
Journal: Advanced functional materials


Crystal growth &design
Journal: Crystal growth &design


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nano energy
Journal: Nano energy


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Sustainable energy &fuels
Journal: Sustainable energy &fuels


Chinese journal of chemistry
Journal: Chinese journal of chemistry


Nanomaterials
Journal: Nanomaterials


Organic electronics
Journal: Organic electronics


Journal of physics: photonics
Journal: Journal of physics: photonics


Advanced materials interfaces
Journal: Advanced materials interfaces


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Nature photonics
Journal: Nature photonics


Applied physics letters
Journal: Applied physics letters


Advanced functional materials
Journal: Advanced functional materials


Advanced optical materials
Journal: Advanced optical materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of vacuum science &technology a: vacuum, surfaces, and films 39 (4 …
Journal: Journal of vacuum science &technology a: vacuum


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of vacuum science &technology a: vacuum, surfaces, and films 39 (1 …
Journal: Journal of vacuum science &technology a: vacuum


Acs applied electronic materials
Journal: Acs applied electronic materials


Materials horizons
Journal: Materials horizons


Advanced functional materials
Journal: Advanced functional materials


Materials &design
Journal: Materials &design


Solar energy
Journal: Solar energy


Applied surface science
Journal: Applied surface science


Solar energy
Journal: Solar energy


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


Solar energy
Journal: Solar energy


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Acs applied energy materials
Journal: Acs applied energy materials


Applied surface science
Journal: Applied surface science


Langmuir
Journal: Langmuir


Scientific reports
Journal: Scientific reports


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Nano express
Journal: Nano express


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of materials research
Journal: Journal of materials research


Surfaces and interfaces
Journal: Surfaces and interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


European journal of organic chemistry
Journal: European journal of organic chemistry


Acs applied nano materials
Journal: Acs applied nano materials


Acs applied energy materials
Journal: Acs applied energy materials


Energy technology
Journal: Energy technology


Acs applied electronic materials
Journal: Acs applied electronic materials


Acs applied nano materials
Journal: Acs applied nano materials


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Applied physics letters
Journal: Applied physics letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Nature
Journal: Nature


Applied physics letters
Journal: Applied physics letters


Journal of applied physics
Journal: Journal of applied physics


Nature
Journal: Nature


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Journal of applied physics
Journal: Journal of applied physics


Nature
Journal: Nature


Applied physics letters
Journal: Applied physics letters


Journal of applied physics
Journal: Journal of applied physics


Nature
Journal: Nature


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Journal of applied physics
Journal: Journal of applied physics


Industrial &engineering chemistry research
Journal: Industrial &engineering chemistry research


Nanoscale advances
Journal: Nanoscale advances


Colloid and interface science communications
Journal: Colloid and interface science communications


Journal of hazardous materials
Journal: Journal of hazardous materials


Acs applied nano materials
Journal: Acs applied nano materials


Nanomaterials
Journal: Nanomaterials


Nanoscale advances
Journal: Nanoscale advances


Journal of materials chemistry a
Journal: Journal of materials chemistry a


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Joule
Journal: Joule


Journal of the american chemical society
Journal: Journal of the american chemical society


Materials advances
Journal: Materials advances


Advanced functional materials
Journal: Advanced functional materials


Advanced optical materials
Journal: Advanced optical materials


Chemical communications
Journal: Chemical communications


Advanced functional materials
Journal: Advanced functional materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Chemistry of materials
Journal: Chemistry of materials


Acs appl. mater. interfaces
Journal: Acs appl. mater. interfaces


Journal of materials chemistry c
Journal: Journal of materials chemistry c


European journal of organic chemistry
Journal: European journal of organic chemistry


Int. j. innov. res. sci. eng. technol.
Journal: Int. j. innov. res. sci. eng. technol.


Advanced materials research
Journal: Advanced materials research


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Materials advances
Journal: Materials advances


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced engineering materials
Journal: Advanced engineering materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Frontiers in energy research
Journal: Frontiers in energy research


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of vacuum science &technology b, nanotechnology and …
Journal: Journal of vacuum science &technology b


Papers in physics
Journal: Papers in physics


Macromolecules
Journal: Macromolecules


Advanced optical materials
Journal: Advanced optical materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nano energy
Journal: Nano energy


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Nanomaterials
Journal: Nanomaterials


Acs applied electronic materials
Journal: Acs applied electronic materials


Advanced science
Journal: Advanced science


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Applied materials today
Journal: Applied materials today


Microporous and mesoporous materials
Journal: Microporous and mesoporous materials


Materials letters
Journal: Materials letters


Materials chemistry frontiers
Journal: Materials chemistry frontiers


Applied surface science
Journal: Applied surface science


Applied materials today
Journal: Applied materials today


Journal of luminescence
Journal: Journal of luminescence


Ceramics international
Journal: Ceramics international


Journal of molecular structure
Journal: Journal of molecular structure


Ionics
Journal: Ionics


Ecs transactions
Journal: Ecs transactions


Materials chemistry and physics
Journal: Materials chemistry and physics


Materials today communications
Journal: Materials today communications


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Dalton transactions
Journal: Dalton transactions


International journal of quantum chemistry
Journal: International journal of quantum chemistry


Materials chemistry frontiers
Journal: Materials chemistry frontiers


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of molecular modeling
Journal: Journal of molecular modeling


Materials horizons
Journal: Materials horizons


Chemistry of materials
Journal: Chemistry of materials


Nature photonics
Journal: Nature photonics


Nature photonics
Journal: Nature photonics


Nature photonics
Journal: Nature photonics


J. pharm pharm scien
Journal: J. pharm pharm scien


Energies
Journal: Energies


Current applied physics
Journal: Current applied physics


Energy technology
Journal: Energy technology


Langmuir
Journal: Langmuir


Advanced engineering materials
Journal: Advanced engineering materials


Materials advances
Journal: Materials advances


Solar
Journal: Solar


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nanoscale
Journal: Nanoscale


Matter
Journal: Matter


Crystal growth &design
Journal: Crystal growth &design


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Progress in natural science: materials international
Journal: Progress in natural science: materials international


Chemical science
Journal: Chemical science


Sensors and actuators b: chemical
Journal: Sensors and actuators b: chemical


Machine learning and knowledge extraction
Journal: Machine learning and knowledge extraction


International journal of energy research
Journal: International journal of energy research


Mrs advances
Journal: Mrs advances


Organic and hybrid sensors and bioelectronics xv
Journal: Organic and hybrid sensors and bioelectronics xv


Organic and hybrid sensors and bioelectronics xv
Journal: Organic and hybrid sensors and bioelectronics xv


Organic and hybrid sensors and bioelectronics xiv
Journal: Organic and hybrid sensors and bioelectronics xiv


Journal of applied physics
Journal: Journal of applied physics


Ceramics international
Journal: Ceramics international


Langmuir
Journal: Langmuir


Applied physics letters
Journal: Applied physics letters


Applied physics reviews
Journal: Applied physics reviews


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Materials letters
Journal: Materials letters


Nano energy
Journal: Nano energy


Rsc advances
Journal: Rsc advances


Journal of alloys and compounds
Journal: Journal of alloys and compounds


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of photonics for energy
Journal: Journal of photonics for energy


Quimica nova
Journal: Quimica nova


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemistry–a european journal
Journal: Chemistry–a european journal


Chemistry–a european journal
Journal: Chemistry–a european journal


Advanced materials
Journal: Advanced materials


Nature nanotechnology
Journal: Nature nanotechnology


Materials &design
Journal: Materials &design


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Thin solid films
Journal: Thin solid films


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Radiation physics and chemistry
Journal: Radiation physics and chemistry


Acs applied energy materials
Journal: Acs applied energy materials


Advanced materials
Journal: Advanced materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of chemical information and modeling
Journal: Journal of chemical information and modeling


Nature communications
Journal: Nature communications


Apl materials
Journal: Apl materials


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Batteries
Journal: Batteries


Nature communications
Journal: Nature communications


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced optical materials
Journal: Advanced optical materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nature communications
Journal: Nature communications


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced optical materials
Journal: Advanced optical materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Science
Journal: Science


Advanced science
Journal: Advanced science


Thin solid films
Journal: Thin solid films


Next generation technologies for solar energy conversion vii
Journal: Next generation technologies for solar energy conversion vii


Advanced science
Journal: Advanced science


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Nano-micro letters
Journal: Nano-micro letters


Science of advanced materials
Journal: Science of advanced materials


Journal of saudi chemical society
Journal: Journal of saudi chemical society


Chemistry of materials
Journal: Chemistry of materials


Energy &environmental science
Journal: Energy &environmental science


Chemsuschem
Journal: Chemsuschem


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs nano
Journal: Acs nano


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Nanoscale
Journal: Nanoscale


Rsc advances
Journal: Rsc advances


Nature communications
Journal: Nature communications


Journal of materials chemistry
Journal: Journal of materials chemistry


Journal of physical chemistry letters
Journal: Journal of physical chemistry letters


Nature electronics
Journal: Nature electronics


Nanoscale
Journal: Nanoscale


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Chemistry-a european journal
Journal: Chemistry-a european journal


Acs photonics
Journal: Acs photonics


Nanoscale
Journal: Nanoscale


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of co2 utilization
Journal: Journal of co2 utilization


Topics in catalysis
Journal: Topics in catalysis


Solid state ionics
Journal: Solid state ionics


International journal of hydrogen energy
Journal: International journal of hydrogen energy


Fuel
Journal: Fuel


Small methods
Journal: Small methods


Small methods
Journal: Small methods


Nature nanotechnology
Journal: Nature nanotechnology


Acs energy letters
Journal: Acs energy letters


Journal of the american chemical society

In [41]:
df5['Source'].value_counts()

The journal of physical chemistry c                     800
Advanced materials                                      727
Applied physics letters                                 673
Acs energy letters                                      578
Physical review b                                       564
                                                       ...
Metallurgical and materials transactions a                1
Journal of materials processing technology 175 (1-3)      1
Nano letters (print)                                      1
Nano lett                                                 1
Journal of the indian botanical society 74 (1-4)          1
Name: Source, Length: 2294, dtype: int64

In [42]:
import re
pattern = r'^([^\d]+)'

vals = df5['Source'].values
index = df5['Source'].index

for idx, val in enumerate(df5['Source'].values):

    # match pattern to citation
    match = re.match(pattern, val)

    if match:
        journal = match.group(1)
        
        # print extracted values
        print(val)
        print('Journal:', journal)
        print('\n')
        
        df5.loc[index[idx], 'Source'] = journal
        
    else:
        pass

Science
Journal: Science


Nature
Journal: Nature


Nature materials
Journal: Nature materials


Science
Journal: Science


Nature
Journal: Nature


Nature nanotechnology
Journal: Nature nanotechnology


Science
Journal: Science


Nature materials
Journal: Nature materials


Nature photonics
Journal: Nature photonics


Nature nanotechnology
Journal: Nature nanotechnology


Science
Journal: Science


Nature nanotechnology
Journal: Nature nanotechnology


Nature
Journal: Nature


Science
Journal: Science


Nature
Journal: Nature


Nature communications
Journal: Nature communications


Journal of the american chemical society
Journal: Journal of the american chemical society


Science
Journal: Science


Chemical reviews
Journal: Chemical reviews


Nature
Journal: Nature


Nature reviews materials
Journal: Nature reviews materials


Science
Journal: Science


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Joule
Journal: Joule


Nature energy
Journal: Nature energy


Nature photonics
Journal: Nature photonics


Nature photonics
Journal: Nature photonics


Nano letters
Journal: Nano letters


Nature communications
Journal: Nature communications


Nature communications
Journal: Nature communications


Journal of the american chemical society
Journal: Journal of the american chemical society


Chemical reviews
Journal: Chemical reviews


Science
Journal: Science


Nature catalysis
Journal: Nature catalysis


Science
Journal: Science


Nature energy
Journal: Nature energy


Nature catalysis
Journal: Nature catalysis


Nature materials
Journal: Nature materials


Nature chemistry
Journal: Nature chemistry


Nature materials
Journal: Nature materials


Nature nanotechnology
Journal: Nature nanotechnology


Nature
Journal: Nature


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Chemical reviews
Journal: Chemical reviews


Advanced materials
Journal: Advanced materials


Chemical reviews
Journal: Chemical reviews


Applied physics letters
Journal: Applied physics letters


Nature communications
Journal: Nature communications


Nature
Journal: Nature


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nature
Journal: Nature


Nature energy
Journal: Nature energy


Nature photonics
Journal: Nature photonics


Nature photonics
Journal: Nature photonics


Nature catalysis
Journal: Nature catalysis


Science
Journal: Science


Nature photonics
Journal: Nature photonics


Nature nanotechnology
Journal: Nature nanotechnology


Nature materials
Journal: Nature materials


Nature chemistry
Journal: Nature chemistry


Nature nanotechnology
Journal: Nature nanotechnology


Acs nano
Journal: Acs nano


Acs nano
Journal: Acs nano


Ieee communications magazine
Journal: Ieee communications magazine


Nature photonics
Journal: Nature photonics


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


Nature materials
Journal: Nature materials


Chemistry of materials
Journal: Chemistry of materials


Nature energy
Journal: Nature energy


Acs nano
Journal: Acs nano


Nature nanotechnology
Journal: Nature nanotechnology


Advanced materials
Journal: Advanced materials


Science
Journal: Science


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nature energy
Journal: Nature energy


Journal of the american chemical society
Journal: Journal of the american chemical society


Applied physics letters
Journal: Applied physics letters


Advanced functional materials
Journal: Advanced functional materials


Chemistry of materials
Journal: Chemistry of materials


Joule
Journal: Joule


Nature materials
Journal: Nature materials


Nature materials
Journal: Nature materials


Science
Journal: Science


Nature
Journal: Nature


Advanced materials
Journal: Advanced materials


Energy &environmental science
Journal: Energy &environmental science


Advanced materials
Journal: Advanced materials


Acs photonics
Journal: Acs photonics


Nature energy
Journal: Nature energy


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


Nature materials
Journal: Nature materials


Acs nano
Journal: Acs nano


Nature reviews materials
Journal: Nature reviews materials


Nano letters
Journal: Nano letters


Nature communications
Journal: Nature communications


Nature catalysis
Journal: Nature catalysis


Reviews of modern physics
Journal: Reviews of modern physics


Acs catalysis
Journal: Acs catalysis


Nature catalysis
Journal: Nature catalysis


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced materials
Journal: Advanced materials


Nature photonics
Journal: Nature photonics


Nature communications
Journal: Nature communications


Acs nano
Journal: Acs nano


Applied physics letters
Journal: Applied physics letters


Nature nanotechnology
Journal: Nature nanotechnology


Nature materials
Journal: Nature materials


Ieee network
Journal: Ieee network


Nature photonics
Journal: Nature photonics


Joule
Journal: Joule


Nature energy
Journal: Nature energy


Nature nanotechnology
Journal: Nature nanotechnology


Journal of the american chemical society
Journal: Journal of the american chemical society


Science
Journal: Science


Nature catalysis
Journal: Nature catalysis


Nature catalysis
Journal: Nature catalysis


Nature chemistry
Journal: Nature chemistry


Acs nano
Journal: Acs nano


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Nano letters
Journal: Nano letters


Nano letters
Journal: Nano letters


Nature
Journal: Nature


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Advanced materials
Journal: Advanced materials


Applied physics letters
Journal: Applied physics letters


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Optics express
Journal: Optics express


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature communications
Journal: Nature communications


Nature chemistry
Journal: Nature chemistry


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


Nature photonics
Journal: Nature photonics


Nature communications
Journal: Nature communications


Nature nanotechnology
Journal: Nature nanotechnology


Energy &environmental science
Journal: Energy &environmental science


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Applied physics letters
Journal: Applied physics letters


Nature chemistry
Journal: Nature chemistry


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Nature
Journal: Nature


Nano letters
Journal: Nano letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Acs energy letters
Journal: Acs energy letters


Joule
Journal: Joule


Nature nanotechnology
Journal: Nature nanotechnology


Applied physics letters
Journal: Applied physics letters


Nano letters
Journal: Nano letters


Applied physics letters
Journal: Applied physics letters


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


Nature
Journal: Nature


Advanced materials
Journal: Advanced materials


Nature biomedical engineering
Journal: Nature biomedical engineering


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


Applied physics letters
Journal: Applied physics letters


Advanced materials
Journal: Advanced materials


Applied physics letters
Journal: Applied physics letters


Acs nano
Journal: Acs nano


Journal of the american chemical society
Journal: Journal of the american chemical society


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Advanced functional materials
Journal: Advanced functional materials


Nature communications
Journal: Nature communications


Nature
Journal: Nature


Nano letters
Journal: Nano letters


Langmuir
Journal: Langmuir


Advanced materials
Journal: Advanced materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Nano letters
Journal: Nano letters


Acs energy letters
Journal: Acs energy letters


Angewandte chemie
Journal: Angewandte chemie


Advanced materials
Journal: Advanced materials


Acs energy letters
Journal: Acs energy letters


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Nature catalysis
Journal: Nature catalysis


Infrared physics &technology
Journal: Infrared physics &technology


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Advanced materials
Journal: Advanced materials


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced materials
Journal: Advanced materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs nano
Journal: Acs nano


Analytical chemistry
Journal: Analytical chemistry


Ieee journal of quantum electronics
Journal: Ieee journal of quantum electronics


Nature catalysis
Journal: Nature catalysis


Nano letters
Journal: Nano letters


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


Journal of the american chemical society
Journal: Journal of the american chemical society


Applied physics letters
Journal: Applied physics letters


Journal of lightwave technology
Journal: Journal of lightwave technology


Advanced materials
Journal: Advanced materials


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


Small
Journal: Small


Advanced energy materials
Journal: Advanced energy materials


Nature communications
Journal: Nature communications


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced functional materials
Journal: Advanced functional materials


Science
Journal: Science


Advanced materials
Journal: Advanced materials


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Applied physics letters
Journal: Applied physics letters


Nature energy
Journal: Nature energy


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Applied physics letters
Journal: Applied physics letters


Advanced materials
Journal: Advanced materials


Nature energy
Journal: Nature energy


Accounts of chemical research
Journal: Accounts of chemical research


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Acs nano
Journal: Acs nano


Nature communications
Journal: Nature communications


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs energy letters
Journal: Acs energy letters


Nano letters
Journal: Nano letters


Nature energy
Journal: Nature energy


Energy &environmental science
Journal: Energy &environmental science


Nature photonics
Journal: Nature photonics


Advanced science
Journal: Advanced science


Advanced materials
Journal: Advanced materials


Nature reviews materials
Journal: Nature reviews materials


Angewandte chemie
Journal: Angewandte chemie


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature communications
Journal: Nature communications


Joule
Journal: Joule


Langmuir
Journal: Langmuir


Nature communications
Journal: Nature communications


Optics letters
Journal: Optics letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature
Journal: Nature


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Nature materials
Journal: Nature materials


Acs nano
Journal: Acs nano


Lab on a chip
Journal: Lab on a chip


Acs energy letters
Journal: Acs energy letters


Nature energy
Journal: Nature energy


Acs energy letters
Journal: Acs energy letters


Applied physics letters
Journal: Applied physics letters


Scientific reports
Journal: Scientific reports


Nature reviews materials
Journal: Nature reviews materials


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Nature photonics
Journal: Nature photonics


Journal of the american chemical society
Journal: Journal of the american chemical society


Applied physics letters
Journal: Applied physics letters


Nature electronics
Journal: Nature electronics


Physical review letters
Journal: Physical review letters


Science advances
Journal: Science advances


Joule
Journal: Joule


Advanced materials
Journal: Advanced materials


Science advances
Journal: Science advances


Nature communications
Journal: Nature communications


Acs nano
Journal: Acs nano


Acs nano
Journal: Acs nano


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced materials
Journal: Advanced materials


Acs energy letters
Journal: Acs energy letters


Nature energy
Journal: Nature energy


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced materials
Journal: Advanced materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Joule
Journal: Joule


Advanced materials
Journal: Advanced materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature electronics
Journal: Nature electronics


Acs nano
Journal: Acs nano


Acs energy letters
Journal: Acs energy letters


Advanced materials
Journal: Advanced materials


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Journal of materials chemistry
Journal: Journal of materials chemistry


Nature materials
Journal: Nature materials


Analytical chemistry
Journal: Analytical chemistry


Acs energy letters
Journal: Acs energy letters


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Energy &environmental science
Journal: Energy &environmental science


Nature communications
Journal: Nature communications


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Acs energy letters
Journal: Acs energy letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced materials
Journal: Advanced materials


Joule
Journal: Joule


Nature communications
Journal: Nature communications


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Applied physics letters
Journal: Applied physics letters


Smartmat
Journal: Smartmat


Energy &environmental science
Journal: Energy &environmental science


Ieee communications letters
Journal: Ieee communications letters


Nature energy
Journal: Nature energy


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Applied physics letters
Journal: Applied physics letters


Nature communications
Journal: Nature communications


Physical review b
Journal: Physical review b


Matter
Journal: Matter


Acs energy letters
Journal: Acs energy letters


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Science advances
Journal: Science advances


Advanced materials
Journal: Advanced materials


Acs energy letters
Journal: Acs energy letters


Acs applied energy materials
Journal: Acs applied energy materials


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Journal of materials chemistry
Journal: Journal of materials chemistry


Josa b
Journal: Josa b


Acs energy letters
Journal: Acs energy letters


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


Physical review b
Journal: Physical review b


Nature catalysis
Journal: Nature catalysis


Nature chemistry
Journal: Nature chemistry


Ieee journal of solid-state circuits
Journal: Ieee journal of solid-state circuits


Physical review b
Journal: Physical review b


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Nature photonics
Journal: Nature photonics


Physical review b
Journal: Physical review b


Green chemistry
Journal: Green chemistry


Applied physics letters
Journal: Applied physics letters


Josa b
Journal: Josa b


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Angewandte chemie
Journal: Angewandte chemie


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Analytical chemistry
Journal: Analytical chemistry


Applied physics letters
Journal: Applied physics letters


Ieee communications letters
Journal: Ieee communications letters


Advanced materials
Journal: Advanced materials


Advanced functional materials
Journal: Advanced functional materials


Small
Journal: Small


Nano letters
Journal: Nano letters


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Synthetic metals
Journal: Synthetic metals


Nature communications
Journal: Nature communications


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Applied physics letters
Journal: Applied physics letters


Ieee communications letters
Journal: Ieee communications letters


Nano letters
Journal: Nano letters


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Advanced optical materials
Journal: Advanced optical materials


Nano letters
Journal: Nano letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Energy &environmental science
Journal: Energy &environmental science


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Joule
Journal: Joule


Nano letters
Journal: Nano letters


Journal of optics a: pure and applied optics
Journal: Journal of optics a: pure and applied optics


Nature communications
Journal: Nature communications


Nature communications
Journal: Nature communications


Nano letters
Journal: Nano letters


Applied physics letters
Journal: Applied physics letters


Nature communications
Journal: Nature communications


Advanced materials

Macromolecules
Journal: Macromolecules


Journal of materials chemistry c
Journal: Journal of materials chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Optical probes of conjugated polymers
Journal: Optical probes of conjugated polymers


Macromolecular chemistry and physics
Journal: Macromolecular chemistry and physics


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of chemical physics
Journal: The journal of chemical physics


Macromolecules
Journal: Macromolecules


Energy &environmental science
Journal: Energy &environmental science


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced functional materials
Journal: Advanced functional materials


Chemphyschem
Journal: Chemphyschem


Synthetic metals
Journal: Synthetic metals


Advanced energy materials
Journal: Advanced energy materials


Physical review b
Journal: Physical review b


Macromolecules
Journal: Macromolecules


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Colloid and polymer science
Journal: Colloid and polymer science


Berichte der bunsengesellschaft für physikalische chemie
Journal: Berichte der bunsengesellschaft für physikalische chemie


Macromolecules
Journal: Macromolecules


Applied physics letters
Journal: Applied physics letters


The journal of chemical physics
Journal: The journal of chemical physics


Polymer
Journal: Polymer


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced functional materials
Journal: Advanced functional materials


Molecular crystals and liquid crystals
Journal: Molecular crystals and liquid crystals


Journal of the american chemical society
Journal: Journal of the american chemical society


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Advanced materials
Journal: Advanced materials


Advanced electronic materials
Journal: Advanced electronic materials


Journal of applied physics
Journal: Journal of applied physics


Solar rrl
Journal: Solar rrl


Apl materials
Journal: Apl materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Macromolecular symposia
Journal: Macromolecular symposia


Berichte der bunsengesellschaft für physikalische chemie
Journal: Berichte der bunsengesellschaft für physikalische chemie


Acs energy letters
Journal: Acs energy letters


Physical review applied
Journal: Physical review applied


Journal of polymer science part b: polymer physics
Journal: Journal of polymer science part b: polymer physics


Adv. funct. mater
Journal: Adv. funct. mater


Berichte der bunsengesellschaft für physikalische chemie
Journal: Berichte der bunsengesellschaft für physikalische chemie


Physical review b
Journal: Physical review b


Macromolecules
Journal: Macromolecules


Macromolecular chemistry and physics
Journal: Macromolecular chemistry and physics


Synthetic metals
Journal: Synthetic metals


Advanced energy materials
Journal: Advanced energy materials


The journal of chemical physics
Journal: The journal of chemical physics


Science and technology of advanced materials
Journal: Science and technology of advanced materials


Journal of applied physics
Journal: Journal of applied physics


Applied physics letters
Journal: Applied physics letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Applied physics letters
Journal: Applied physics letters


Solar rrl
Journal: Solar rrl


Advanced energy materials
Journal: Advanced energy materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Thin solid films
Journal: Thin solid films


Energy &environmental science
Journal: Energy &environmental science


Nature communications
Journal: Nature communications


Chemistry of materials
Journal: Chemistry of materials


Macromolecules
Journal: Macromolecules


Physica status solidi (a)
Journal: Physica status solidi (a)


Macromolecular rapid communications
Journal: Macromolecular rapid communications


The journal of chemical physics
Journal: The journal of chemical physics


Liquid crystals
Journal: Liquid crystals


Macromolecules
Journal: Macromolecules


Advanced energy materials
Journal: Advanced energy materials


Solar rrl
Journal: Solar rrl


Rsc advances
Journal: Rsc advances


Acs energy letters
Journal: Acs energy letters


Frontiers in chemistry
Journal: Frontiers in chemistry


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Chemphyschem
Journal: Chemphyschem


Applied physics a
Journal: Applied physics a


Journal of polymer science part a: polymer chemistry
Journal: Journal of polymer science part a: polymer chemistry


Energy procedia
Journal: Energy procedia


Journal of applied physics
Journal: Journal of applied physics


Nanotechnology
Journal: Nanotechnology


Macromolecules
Journal: Macromolecules


Physica status solidi (a)
Journal: Physica status solidi (a)


Organic photovoltaics iv
Journal: Organic photovoltaics iv


Angewandte chemie-german edition
Journal: Angewandte chemie-german edition


Organic light-emitting materials and devices iii
Journal: Organic light-emitting materials and devices iii


Chem. mater
Journal: Chem. mater


Makromolekulare chemie. macromolecular symposia
Journal: Makromolekulare chemie. macromolecular symposia


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Physica status solidi (a)
Journal: Physica status solidi (a)


Liquid crystals iv
Journal: Liquid crystals iv


Chemical physics letters 202 (1-2)
Journal: Chemical physics letters


Nonlinear optical properties of organic materials iv
Journal: Nonlinear optical properties of organic materials iv


Electronic properties of conjugated polymers iii
Journal: Electronic properties of conjugated polymers iii


Materials horizons
Journal: Materials horizons


Acs applied polymer materials
Journal: Acs applied polymer materials


Journal of applied physics
Journal: Journal of applied physics


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of applied physics
Journal: Journal of applied physics


Applied physics reviews
Journal: Applied physics reviews


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Applied physics letters
Journal: Applied physics letters


Journal of luminescence 112 (1-4)
Journal: Journal of luminescence


Electronic properties of conjugated polymers iii
Journal: Electronic properties of conjugated polymers iii


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Synthetic metals
Journal: Synthetic metals


Organic photonics and photovoltaics
Journal: Organic photonics and photovoltaics


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Nonlinear optical properties of organic materials vii
Journal: Nonlinear optical properties of organic materials vii


Applied physics letters
Journal: Applied physics letters


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Synthetic metals
Journal: Synthetic metals


Second-order organic nonlinear optics
Journal: Second-order organic nonlinear optics


Chemical materials
Journal: Chemical materials


Makromolekulare chemie. macromolecular symposia
Journal: Makromolekulare chemie. macromolecular symposia


Advanced energy materials
Journal: Advanced energy materials


Advanced functional materials
Journal: Advanced functional materials


Journal of applied physics
Journal: Journal of applied physics


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Physical review applied
Journal: Physical review applied


J. phys. chem. lett
Journal: J. phys. chem. lett


Physics
Journal: Physics


Organic photonic materials and devices ix
Journal: Organic photonic materials and devices ix


Journal of applied physics
Journal: Journal of applied physics


Optical materials
Journal: Optical materials


Nonlinear optical properties of advanced materials
Journal: Nonlinear optical properties of advanced materials


Advanced materials
Journal: Advanced materials


Special publications of the royal society of chemistry
Journal: Special publications of the royal society of chemistry


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Organic photovoltaics iv
Journal: Organic photovoltaics iv


Nature communications
Journal: Nature communications


Nature communications
Journal: Nature communications


Communications physics
Journal: Communications physics


Solar rrl
Journal: Solar rrl


Advanced materials
Journal: Advanced materials


Advanced energy materials
Journal: Advanced energy materials


Physical review applied
Journal: Physical review applied


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs nano
Journal: Acs nano


Advanced energy materials
Journal: Advanced energy materials


Printed memory and circuits
Journal: Printed memory and circuits


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Vakuum in forschung und praxis
Journal: Vakuum in forschung und praxis


Advanced materials
Journal: Advanced materials


Macromolecular chemistry and physics
Journal: Macromolecular chemistry and physics


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Nonlinear optical effects in organic polymers
Journal: Nonlinear optical effects in organic polymers


Electrical and related properties of organic solids
Journal: Electrical and related properties of organic solids


Verhandlungen der deutschen physikalischen gesellschaft
Journal: Verhandlungen der deutschen physikalischen gesellschaft


Verhandlungen der deutschen physikalischen gesellschaft
Journal: Verhandlungen der deutschen physikalischen gesellschaft


Verhandlungen der deutschen physikalischen gesellschaft
Journal: Verhandlungen der deutschen physikalischen gesellschaft


Verhandlungen der deutschen physikalischen gesellschaft
Journal: Verhandlungen der deutschen physikalischen gesellschaft


Organic optoelectronics and photonics ii
Journal: Organic optoelectronics and photonics ii


Nanophotonics
Journal: Nanophotonics


Nanomanipulation with light ii
Journal: Nanomanipulation with light ii


Verhandlungen der deutschen physikalischen gesellschaft
Journal: Verhandlungen der deutschen physikalischen gesellschaft


Verhandlungen der deutschen physikalischen gesellschaft
Journal: Verhandlungen der deutschen physikalischen gesellschaft


Verhandlungen der deutschen physikalischen gesellschaft
Journal: Verhandlungen der deutschen physikalischen gesellschaft


Organic light-emitting materials and devices vii
Journal: Organic light-emitting materials and devices vii


Chemphyschem
Journal: Chemphyschem


Macromolecules
Journal: Macromolecules


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Applied physics letters
Journal: Applied physics letters


Journal of applied physics
Journal: Journal of applied physics


Journal of applied physics
Journal: Journal of applied physics


Journal of physical chemistry b-condensed phase
Journal: Journal of physical chemistry b-condensed phase


Appl. phys. lett
Journal: Appl. phys. lett


Journal of applied physics
Journal: Journal of applied physics


Macromolecules
Journal: Macromolecules


El 96 berlin
Journal: El


Nonlinear optical properties of advanced materials
Journal: Nonlinear optical properties of advanced materials


Chemical physics letters
Journal: Chemical physics letters


Nonlinear optical properties of organic materials
Journal: Nonlinear optical properties of organic materials


Organic materials for non-linear optics ii
Journal: Organic materials for non-linear optics ii


J. phys. chem
Journal: J. phys. chem


Special publication
Journal: Special publication


Special publication
Journal: Special publication


Chemcatchem
Journal: Chemcatchem


Chemical reviews
Journal: Chemical reviews


Catalysis communications
Journal: Catalysis communications


The journal of physical chemistry
Journal: The journal of physical chemistry


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Chemsuschem
Journal: Chemsuschem


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Topics in catalysis
Journal: Topics in catalysis


Catalysis today
Journal: Catalysis today


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Journal of catalysis
Journal: Journal of catalysis


Journal of catalysis
Journal: Journal of catalysis


Journal of catalysis
Journal: Journal of catalysis


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of materials chemistry
Journal: Journal of materials chemistry


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Journal of catalysis
Journal: Journal of catalysis


Catalysis letters
Journal: Catalysis letters


Journal of catalysis
Journal: Journal of catalysis


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of catalysis
Journal: Journal of catalysis


Journal of molecular catalysis a: chemical
Journal: Journal of molecular catalysis a: chemical


Applied catalysis a: general
Journal: Applied catalysis a: general


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Journal of catalysis
Journal: Journal of catalysis


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Catalysis today
Journal: Catalysis today


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Applied catalysis a: general
Journal: Applied catalysis a: general


Chemsuschem
Journal: Chemsuschem


Journal of materials chemistry
Journal: Journal of materials chemistry


Topics in catalysis
Journal: Topics in catalysis


Journal of catalysis
Journal: Journal of catalysis


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Journal of catalysis
Journal: Journal of catalysis


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Journal of catalysis
Journal: Journal of catalysis


Journal of materials chemistry
Journal: Journal of materials chemistry


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Journal of catalysis
Journal: Journal of catalysis


Journal of materials chemistry
Journal: Journal of materials chemistry


International journal of hydrogen energy
Journal: International journal of hydrogen energy


J. chim. phys
Journal: J. chim. phys


Journal of molecular catalysis
Journal: Journal of molecular catalysis


Applied catalysis a: general
Journal: Applied catalysis a: general


Topics in catalysis
Journal: Topics in catalysis


Journal of catalysis
Journal: Journal of catalysis


Acs catalysis
Journal: Acs catalysis


Catalysis today
Journal: Catalysis today


Acs catalysis
Journal: Acs catalysis


Journal of catalysis
Journal: Journal of catalysis


Catalysis today
Journal: Catalysis today


International journal of hydrogen energy
Journal: International journal of hydrogen energy


Catalysis
Journal: Catalysis


Journal of catalysis
Journal: Journal of catalysis


Environmental science &technology
Journal: Environmental science &technology


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Journal of molecular catalysis a: chemical 268 (1-2)
Journal: Journal of molecular catalysis a: chemical


Studies in surface science and catalysis
Journal: Studies in surface science and catalysis


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Industrial &engineering chemistry research
Journal: Industrial &engineering chemistry research


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of catalysis
Journal: Journal of catalysis


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Journal of molecular catalysis a: chemical 175 (1-2)
Journal: Journal of molecular catalysis a: chemical


Catalysis today
Journal: Catalysis today


Applied catalysis a: general
Journal: Applied catalysis a: general


Catalysis communications
Journal: Catalysis communications


Catalysis letters
Journal: Catalysis letters


International journal of hydrogen energy
Journal: International journal of hydrogen energy


Journal of catalysis
Journal: Journal of catalysis


Journal of molecular catalysis a: chemical 293 (1-2)
Journal: Journal of molecular catalysis a: chemical


Journal of propulsion and power
Journal: Journal of propulsion and power


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of catalysis
Journal: Journal of catalysis


Oil &gas science and technology–revue d’ifp energies nouvelles
Journal: Oil &gas science and technology–revue d’ifp energies nouvelles


Acs catalysis
Journal: Acs catalysis


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Applied catalysis
Journal: Applied catalysis


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Journal of catalysis
Journal: Journal of catalysis


Journal of molecular catalysis a: chemical 320 (1-2)
Journal: Journal of molecular catalysis a: chemical


Journal of catalysis
Journal: Journal of catalysis


Applied catalysis a: general
Journal: Applied catalysis a: general


Catalysis communications
Journal: Catalysis communications


Applied catalysis
Journal: Applied catalysis


Applied catalysis
Journal: Applied catalysis


Applied catalysis a: general
Journal: Applied catalysis a: general


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Journal of materials chemistry
Journal: Journal of materials chemistry


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Journal of catalysis
Journal: Journal of catalysis


Journal of the less common metals
Journal: Journal of the less common metals


Microporous and mesoporous materials
Journal: Microporous and mesoporous materials


Solid state sciences
Journal: Solid state sciences


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Topics in catalysis
Journal: Topics in catalysis


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Studies in surface science and catalysis
Journal: Studies in surface science and catalysis


Catalysts
Journal: Catalysts


Journal of catalysis
Journal: Journal of catalysis


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics



Advanced materials
Journal: Advanced materials


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Acs applied energy materials
Journal: Acs applied energy materials


Communications physics
Journal: Communications physics


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced functional materials
Journal: Advanced functional materials


Small
Journal: Small


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Chemical physics letters 341 (3-4)
Journal: Chemical physics letters


Journal of nanophotonics
Journal: Journal of nanophotonics


Organic electronics
Journal: Organic electronics


Macromolecular rapid communications
Journal: Macromolecular rapid communications


Organic electronics
Journal: Organic electronics


Advanced materials
Journal: Advanced materials


Chemical physics letters
Journal: Chemical physics letters


Applied physics letters
Journal: Applied physics letters


Chemical communications
Journal: Chemical communications


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Macromolecular rapid communications
Journal: Macromolecular rapid communications


Scientific reports
Journal: Scientific reports


Synthetic metals
Journal: Synthetic metals


Advanced energy materials
Journal: Advanced energy materials


Physical review b
Journal: Physical review b


Nano energy
Journal: Nano energy


The european physical journal e
Journal: The european physical journal e


Science china chemistry
Journal: Science china chemistry


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Science advances
Journal: Science advances


Advanced optical materials
Journal: Advanced optical materials


Scientific reports
Journal: Scientific reports


Organic electronics
Journal: Organic electronics


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of polymer science part b: polymer physics
Journal: Journal of polymer science part b: polymer physics


Applied physics letters
Journal: Applied physics letters


Synthetic metals
Journal: Synthetic metals


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Ieee journal of selected topics in quantum electronics
Journal: Ieee journal of selected topics in quantum electronics


Nano letters
Journal: Nano letters


Physical review b
Journal: Physical review b


Physical review letters
Journal: Physical review letters


Journal of luminescence
Journal: Journal of luminescence


Applied physics letters
Journal: Applied physics letters


Macromolecular rapid communications
Journal: Macromolecular rapid communications


Journal of microscopy
Journal: Journal of microscopy


Applied physics letters
Journal: Applied physics letters


Energy &environmental science
Journal: Energy &environmental science


Advanced functional materials
Journal: Advanced functional materials


Crystengcomm
Journal: Crystengcomm


Nano letters
Journal: Nano letters


Ieee journal of selected topics in quantum electronics
Journal: Ieee journal of selected topics in quantum electronics


The journal of chemical physics
Journal: The journal of chemical physics


Light: science &applications
Journal: Light: science &applications


Applied physics letters
Journal: Applied physics letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Organic electronics
Journal: Organic electronics


Applied physics letters
Journal: Applied physics letters


Synthetic metals
Journal: Synthetic metals


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Rsc advances
Journal: Rsc advances


Optics express
Journal: Optics express


Journal of luminescence
Journal: Journal of luminescence


Applied physics letters
Journal: Applied physics letters


Journal of materials chemistry
Journal: Journal of materials chemistry


Advanced functional materials
Journal: Advanced functional materials


Applied physics letters
Journal: Applied physics letters


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Advanced energy materials
Journal: Advanced energy materials


Journal of applied physics
Journal: Journal of applied physics


Nanoscale
Journal: Nanoscale


Science china chemistry
Journal: Science china chemistry


Journal of applied physics
Journal: Journal of applied physics


Angewandte chemie
Journal: Angewandte chemie


Materials
Journal: Materials


Applied physics letters
Journal: Applied physics letters


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Applied physics reviews
Journal: Applied physics reviews


Acs omega
Journal: Acs omega


Acs nano
Journal: Acs nano


Journal of applied physics
Journal: Journal of applied physics


Advanced materials
Journal: Advanced materials


Advanced science
Journal: Advanced science


Advanced optical materials
Journal: Advanced optical materials


Thin solid films
Journal: Thin solid films


Physica status solidi (b)
Journal: Physica status solidi (b)


Synthetic metals
Journal: Synthetic metals


Energy science &engineering
Journal: Energy science &engineering


Josa b
Journal: Josa b


Acs photonics
Journal: Acs photonics


Acs photonics
Journal: Acs photonics


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Biointerphases
Journal: Biointerphases


Rsc advances
Journal: Rsc advances


Organic electronics
Journal: Organic electronics


Ultramicroscopy
Journal: Ultramicroscopy


Journal of applied physics
Journal: Journal of applied physics


Synthetic metals
Journal: Synthetic metals


Nature communications
Journal: Nature communications


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Organic photovoltaics x
Journal: Organic photovoltaics x


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Advanced science
Journal: Advanced science


The journal of chemical physics
Journal: The journal of chemical physics


Vacuum
Journal: Vacuum


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Apl materials
Journal: Apl materials


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Journal of materials chemistry
Journal: Journal of materials chemistry


Applied physics letters
Journal: Applied physics letters


Physical review b
Journal: Physical review b


Optics express
Journal: Optics express


Journal of luminescence
Journal: Journal of luminescence


Applied physics letters
Journal: Applied physics letters


Advanced energy materials
Journal: Advanced energy materials


Aip advances
Journal: Aip advances


Rsc advances
Journal: Rsc advances


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Physical review b
Journal: Physical review b


Journal of materials chemistry
Journal: Journal of materials chemistry


Organic light-emitting materials and devices v
Journal: Organic light-emitting materials and devices v


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of electron spectroscopy and related phenomena
Journal: Journal of electron spectroscopy and related phenomena


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Physical review b
Journal: Physical review b


Applied physics letters
Journal: Applied physics letters


Synthetic metals
Journal: Synthetic metals


Thin solid films
Journal: Thin solid films


Journal of display technology
Journal: Journal of display technology


Materials science and engineering: b
Journal: Materials science and engineering: b


Physica status solidi (c)
Journal: Physica status solidi (c)


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Chemical physics letters 468 (1-3)
Journal: Chemical physics letters


Chemistry of materials
Journal: Chemistry of materials


Acs applied energy materials
Journal: Acs applied energy materials


Applied physics express
Journal: Applied physics express


Polymers for advanced technologies
Journal: Polymers for advanced technologies


Organic electronics
Journal: Organic electronics


Thin films and nanostructures
Journal: Thin films and nanostructures


Organic light-emitting materials and devices iii
Journal: Organic light-emitting materials and devices iii


Scientific reports
Journal: Scientific reports


European polymer journal
Journal: European polymer journal


New journal of physics
Journal: New journal of physics


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Energy &environmental materials
Journal: Energy &environmental materials


Chemsuschem
Journal: Chemsuschem


The journal of chemical physics
Journal: The journal of chemical physics


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of materials research
Journal: Journal of materials research


Nanotechnology
Journal: Nanotechnology


Rsc advances
Journal: Rsc advances


Phys. rev. lett
Journal: Phys. rev. lett


Advanced quantum technologies
Journal: Advanced quantum technologies


Organic light-emitting materials and devices iv
Journal: Organic light-emitting materials and devices iv


Organic light-emitting materials and devices ii
Journal: Organic light-emitting materials and devices ii


International journal of electrochemical science
Journal: International journal of electrochemical science


Journal of saudi chemical society
Journal: Journal of saudi chemical society


Advanced optical materials
Journal: Advanced optical materials


Advanced functional materials
Journal: Advanced functional materials


Ultrafast phenomena and nanophotonics xvi
Journal: Ultrafast phenomena and nanophotonics xvi


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Solar rrl
Journal: Solar rrl


Advanced quantum technologies
Journal: Advanced quantum technologies


Malaysian journal of analytical sciences
Journal: Malaysian journal of analytical sciences


Silicon photonics ix
Journal: Silicon photonics ix


Integrated optics: devices
Journal: Integrated optics: devices


Advanced functional materials
Journal: Advanced functional materials


Advanced energy materials
Journal: Advanced energy materials


Advanced energy materials
Journal: Advanced energy materials


Acs photonics
Journal: Acs photonics


Molecules
Journal: Molecules


Advanced science
Journal: Advanced science


Advanced science
Journal: Advanced science


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Chemsuschem
Journal: Chemsuschem


Journal of applied physics
Journal: Journal of applied physics


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Nonlinear optics and applications xii
Journal: Nonlinear optics and applications xii


J. mater. chem
Journal: J. mater. chem


Physica e: low-dimensional systems and nanostructures
Journal: Physica e: low-dimensional systems and nanostructures


Communications physics
Journal: Communications physics


Advanced optical materials
Journal: Advanced optical materials


Scientific reports
Journal: Scientific reports


Microscopy and analysis
Journal: Microscopy and analysis


Scientific reports
Journal: Scientific reports


Advanced functional materials
Journal: Advanced functional materials


Nature communications
Journal: Nature communications


Light manipulating organic materials and devices ii
Journal: Light manipulating organic materials and devices ii


Organic photovoltaics xvi
Journal: Organic photovoltaics xvi


Nature communications
Journal: Nature communications


Advanced optical materials
Journal: Advanced optical materials


Organic nanophotonics
Journal: Organic nanophotonics


Cleo: qels_fundamental science
Journal: Cleo: qels_fundamental science


Advanced energy materials
Journal: Advanced energy materials


Radiotherapy and oncology
Journal: Radiotherapy and oncology


Microscopy of semiconducting materials
Journal: Microscopy of semiconducting materials


Organic light emitting materials and devices xi
Journal: Organic light emitting materials and devices xi


Journal of luminescence
Journal: Journal of luminescence


J. mater. chem
Journal: J. mater. chem


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Physical review letters
Journal: Physical review letters


Organic light-emitting materials and devices
Journal: Organic light-emitting materials and devices


El 96 berlin
Journal: El


Organic thin films for photonic applications
Journal: Organic thin films for photonic applications


Materials science and engineering: c
Journal: Materials science and engineering: c


Nano research
Journal: Nano research


Applied physics letters
Journal: Applied physics letters


Physical review letters
Journal: Physical review letters


Journal of applied physics
Journal: Journal of applied physics


Nano letters
Journal: Nano letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review b
Journal: Physical review b


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Optics and photonics news
Journal: Optics and photonics news


Physical review b
Journal: Physical review b


Nanotechnology
Journal: Nanotechnology


Advanced materials
Journal: Advanced materials


Physical review b
Journal: Physical review b


Nanotechnology
Journal: Nanotechnology


Langmuir
Journal: Langmuir


Physical review b
Journal: Physical review b


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Applied physics letters
Journal: Applied physics letters


Polymers and polymer composites
Journal: Polymers and polymer composites


Journal of materials chemistry
Journal: Journal of materials chemistry


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Science advances
Journal: Science advances


Acs nano
Journal: Acs nano


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Electrochimica acta
Journal: Electrochimica acta


Advanced materials
Journal: Advanced materials


Applied physics letters
Journal: Applied physics letters


Physical review b
Journal: Physical review b


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Optica
Journal: Optica


Physical review b
Journal: Physical review b


Nanoscale
Journal: Nanoscale


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Physical review b
Journal: Physical review b


Journal of nanomaterials
Journal: Journal of nanomaterials


Advanced materials interfaces
Journal: Advanced materials interfaces


New journal of chemistry
Journal: New journal of chemistry


Apl materials
Journal: Apl materials


New journal of chemistry
Journal: New journal of chemistry


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nanotechnology
Journal: Nanotechnology


Applied surface science
Journal: Applied surface science


New journal of physics
Journal: New journal of physics


Nanotechnology
Journal: Nanotechnology


Langmuir
Journal: Langmuir


Journal of materials chemistry
Journal: Journal of materials chemistry


Optics express
Journal: Optics express


Le journal de physique iv 3 (c5)
Journal: Le journal de physique iv


Applied physics letters
Journal: Applied physics letters


Rsc advances
Journal: Rsc advances


Ieee sensors journal
Journal: Ieee sensors journal


Scientific reports
Journal: Scientific reports


Journal of applied physics
Journal: Journal of applied physics


Nanotechnology
Journal: Nanotechnology


Ieee journal of quantum electronics
Journal: Ieee journal of quantum electronics


Joule
Journal: Joule


Journal of nanoscience and nanotechnology
Journal: Journal of nanoscience and nanotechnology


Journal of materials chemistry
Journal: Journal of materials chemistry


Physical review b
Journal: Physical review b


Acs photonics
Journal: Acs photonics


Nanoscale
Journal: Nanoscale


Optics express
Journal: Optics express


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced optical materials
Journal: Advanced optical materials


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Physical review letters
Journal: Physical review letters


Nanotechnology
Journal: Nanotechnology


Physical review b
Journal: Physical review b


Journal of lightwave technology
Journal: Journal of lightwave technology


Optics letters
Journal: Optics letters


Photonics and nanostructures-fundamentals and applications
Journal: Photonics and nanostructures-fundamentals and applications


Ieee photonics journal
Journal: Ieee photonics journal


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Journal of luminescence
Journal: Journal of luminescence


Advanced optical materials
Journal: Advanced optical materials


Journal of applied physics
Journal: Journal of applied physics


Rsc advances
Journal: Rsc advances


Optics letters
Journal: Optics letters


Journal of applied physics
Journal: Journal of applied physics


Journal of applied physics
Journal: Journal of applied physics


Nanomaterials
Journal: Nanomaterials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nanosci. nanotechnol
Journal: Nanosci. nanotechnol


Nanophotonics
Journal: Nanophotonics


Nanotechnology
Journal: Nanotechnology


Physical review b
Journal: Physical review b


Applied physics a
Journal: Applied physics a


Rsc advances
Journal: Rsc advances


Applied physics letters
Journal: Applied physics letters


Acs photonics
Journal: Acs photonics


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Nanotechnology
Journal: Nanotechnology


Nanomaterials
Journal: Nanomaterials


Applied surface science
Journal: Applied surface science


Journal of applied physics
Journal: Journal of applied physics


Physica e: low-dimensional systems and nanostructures
Journal: Physica e: low-dimensional systems and nanostructures


Journal of applied physics
Journal: Journal of applied physics


Acs omega
Journal: Acs omega


Optics communications
Journal: Optics communications


The european physical journal b-condensed matter and complex systems 40 (4 …
Journal: The european physical journal b-condensed matter and complex systems


Journal of luminescence
Journal: Journal of luminescence


Nanophotonics
Journal: Nanophotonics


Nanoscale research letters
Journal: Nanoscale research letters


Nano letters
Journal: Nano letters


Nanotechnology
Journal: Nanotechnology


Ieee photonics journal
Journal: Ieee photonics journal


Phys. stat. sol. (a)
Journal: Phys. stat. sol. (a)


Plasmonics
Journal: Plasmonics


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Solid state communications
Journal: Solid state communications


Journal of materials chemistry c

Chemical reviews
Journal: Chemical reviews


Acs nano
Journal: Acs nano


Journal of applied physics
Journal: Journal of applied physics


Chemical communications
Journal: Chemical communications


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Energy &environmental science
Journal: Energy &environmental science


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Nanotechnology
Journal: Nanotechnology


Journal of applied physics
Journal: Journal of applied physics


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Energy &environmental science
Journal: Energy &environmental science


Acs nano
Journal: Acs nano


Science
Journal: Science


Journal of crystal growth 274 (3-4)
Journal: Journal of crystal growth


Nanotechnology
Journal: Nanotechnology


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of applied physics
Journal: Journal of applied physics


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Applied physics letters
Journal: Applied physics letters


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of crystal growth
Journal: Journal of crystal growth


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Applied physics letters
Journal: Applied physics letters


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Journal of applied physics
Journal: Journal of applied physics


Journal of applied physics
Journal: Journal of applied physics


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Nature communications
Journal: Nature communications


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Applied physics letters
Journal: Applied physics letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Applied physics letters
Journal: Applied physics letters


Chemistry of materials
Journal: Chemistry of materials


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Journal of applied physics
Journal: Journal of applied physics


Journal of vacuum science &technology b: microelectronics and nanometer …
Journal: Journal of vacuum science &technology b: microelectronics and nanometer …


Journal of applied physics
Journal: Journal of applied physics


Crystal growth and design
Journal: Crystal growth and design


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Journal of applied physics
Journal: Journal of applied physics


Chemical communications
Journal: Chemical communications


Surface science
Journal: Surface science


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of applied physics
Journal: Journal of applied physics


Journal of the electrochemical society
Journal: Journal of the electrochemical society


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemistry of materials
Journal: Chemistry of materials


Acs nano
Journal: Acs nano


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Journal of vacuum science &technology b: microelectronics and nanometer …
Journal: Journal of vacuum science &technology b: microelectronics and nanometer …


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Review of scientific instruments
Journal: Review of scientific instruments


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Journal of applied physics
Journal: Journal of applied physics


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


The journal of chemical physics
Journal: The journal of chemical physics


Review of scientific instruments
Journal: Review of scientific instruments


Solid state technology
Journal: Solid state technology


Applied physics letters
Journal: Applied physics letters


Thin solid films
Journal: Thin solid films


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Thin solid films
Journal: Thin solid films


Chemical communications
Journal: Chemical communications


Chemical communications
Journal: Chemical communications


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Applied physics letters
Journal: Applied physics letters


Science
Journal: Science


Nano letters
Journal: Nano letters


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of applied physics
Journal: Journal of applied physics


Pure and applied chemistry
Journal: Pure and applied chemistry


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Chemistry of materials
Journal: Chemistry of materials


Journal of materials research
Journal: Journal of materials research


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Chemical physics letters 329 (3-4)
Journal: Chemical physics letters


Materials science in semiconductor processing
Journal: Materials science in semiconductor processing


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of vacuum science &technology b
Journal: Journal of vacuum science &technology b


Journal of applied physics
Journal: Journal of applied physics


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Journal of applied physics
Journal: Journal of applied physics


Applied physics letters
Journal: Applied physics letters


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Physical review letters
Journal: Physical review letters


Surface science 572 (2-3)
Journal: Surface science


Nanoscale
Journal: Nanoscale


Physical review materials
Journal: Physical review materials


Langmuir
Journal: Langmuir


Physical review materials
Journal: Physical review materials


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Carbon
Journal: Carbon


Journal of applied physics
Journal: Journal of applied physics


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Chemistry of materials
Journal: Chemistry of materials


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Green chemistry
Journal: Green chemistry


Surface science
Journal: Surface science


Journal of the electrochemical society
Journal: Journal of the electrochemical society


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of applied physics
Journal: Journal of applied physics


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Thin solid films
Journal: Thin solid films


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Journal of vacuum science &technology b: microelectronics and nanometer …
Journal: Journal of vacuum science &technology b: microelectronics and nanometer …


Applied physics letters
Journal: Applied physics letters


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Physical review b
Journal: Physical review b


Nanotech. l. &bus.
Journal: Nanotech. l. &bus.


Journal of applied physics
Journal: Journal of applied physics


Chemical physics letters 344 (3-4)
Journal: Chemical physics letters


Journal of vacuum science &technology b: microelectronics and nanometer …
Journal: Journal of vacuum science &technology b: microelectronics and nanometer …


Chemical communications
Journal: Chemical communications


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Review of scientific instruments
Journal: Review of scientific instruments


Journal of vacuum science &technology b: microelectronics and nanometer …
Journal: Journal of vacuum science &technology b: microelectronics and nanometer …


Applied physics letters
Journal: Applied physics letters


Chemical communications
Journal: Chemical communications


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs energy letters
Journal: Acs energy letters


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Chemistry of materials
Journal: Chemistry of materials


Chemical physics letters 414 (1-3)
Journal: Chemical physics letters


Journal of applied physics
Journal: Journal of applied physics


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Chemical physics letters 474 (1-3)
Journal: Chemical physics letters


Acs materials letters
Journal: Acs materials letters


Review of scientific instruments
Journal: Review of scientific instruments


Science advances
Journal: Science advances


Chemistry of materials
Journal: Chemistry of materials


Ieee transactions on plasma science
Journal: Ieee transactions on plasma science


Solid state technology
Journal: Solid state technology


Applied physics letters
Journal: Applied physics letters


Electrophoresis
Journal: Electrophoresis


Special publications of the royal society of chemistry
Journal: Special publications of the royal society of chemistry


Nanotechnology
Journal: Nanotechnology


Journal of vacuum science &technology b: microelectronics and nanometer …
Journal: Journal of vacuum science &technology b: microelectronics and nanometer …


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Ieee transactions on plasma science
Journal: Ieee transactions on plasma science


Surface science
Journal: Surface science


Nanotechnology
Journal: Nanotechnology


Journal of applied physics
Journal: Journal of applied physics


Surface science 540 (2-3)
Journal: Surface science


Plasma sources science and technology
Journal: Plasma sources science and technology


Sustainable energy &fuels
Journal: Sustainable energy &fuels


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Chemistry of materials
Journal: Chemistry of materials


Journal of applied physics
Journal: Journal of applied physics


Ieee transactions on plasma science
Journal: Ieee transactions on plasma science


Ieee transactions on plasma science
Journal: Ieee transactions on plasma science


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Journal of renewable and sustainable energy
Journal: Journal of renewable and sustainable energy


Physical review materials
Journal: Physical review materials


Microscopy and microanalysis
Journal: Microscopy and microanalysis


Acs applied electronic materials
Journal: Acs applied electronic materials


Materials horizons
Journal: Materials horizons


Physical review materials
Journal: Physical review materials


Ieee transactions on plasma science
Journal: Ieee transactions on plasma science


Japanese journal of applied physics 41 (12a)
Journal: Japanese journal of applied physics


Digital discovery
Journal: Digital discovery


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Research@ ua
Journal: Research@ ua


Journal of applied physics
Journal: Journal of applied physics


Joule
Journal: Joule


Advanced functional materials
Journal: Advanced functional materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Journal of vacuum science and technology-section a
Journal: Journal of vacuum science and technology-section a


Spie milestone series ms
Journal: Spie milestone series ms


Journal of vacuum science and technology. a
Journal: Journal of vacuum science and technology. a


Ieee transactions on plasma science
Journal: Ieee transactions on plasma science


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Ieee transactions on plasma science
Journal: Ieee transactions on plasma science


Ieee transactions on plasma science
Journal: Ieee transactions on plasma science


Ieee transactions on plasma science
Journal: Ieee transactions on plasma science


Journal of applied physics
Journal: Journal of applied physics


Review of scientific instruments
Journal: Review of scientific instruments


Ieee transactions on plasma science
Journal: Ieee transactions on plasma science


Journal of the korean physical society 35 (suppl. 4)
Journal: Journal of the korean physical society


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Nano letters
Journal: Nano letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature communications
Journal: Nature communications


Nano letters
Journal: Nano letters


Accounts of chemical research
Journal: Accounts of chemical research


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemical reviews
Journal: Chemical reviews


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs nano
Journal: Acs nano


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nanotechnology
Journal: Nanotechnology


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs nano
Journal: Acs nano


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Inorganica chimica acta
Journal: Inorganica chimica acta


Applied physics letters
Journal: Applied physics letters


Chemical society reviews
Journal: Chemical society reviews


Nanotechnology
Journal: Nanotechnology


Advanced energy materials
Journal: Advanced energy materials


Nano letters
Journal: Nano letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Energy &environmental science
Journal: Energy &environmental science


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs nano
Journal: Acs nano


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Applied physics letters
Journal: Applied physics letters


Journal of materials chemistry a
Journal: Journal of materials chemistry a


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemistry of materials
Journal: Chemistry of materials


Acs nano
Journal: Acs nano


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced energy materials
Journal: Advanced energy materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Nano letters
Journal: Nano letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Acs energy letters
Journal: Acs energy letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs energy letters
Journal: Acs energy letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Chemelectrochem
Journal: Chemelectrochem


The journal of physical chemistry c
Journal: The journal of physical chemistry c



Acs energy letters
Journal: Acs energy letters


Science
Journal: Science


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Nature energy
Journal: Nature energy


Organic
Journal: Organic


Langmuir
Journal: Langmuir


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Journées nationales du photovoltaïque
Journal: Journées nationales du photovoltaïque


Synthetic metals
Journal: Synthetic metals


Journal of vacuum science and technology. a
Journal: Journal of vacuum science and technology. a


Interfaces
Journal: Interfaces


Phys. status solidi a
Journal: Phys. status solidi a


Ecs transactions
Journal: Ecs transactions


Appl. phys. lett
Journal: Appl. phys. lett


Journal of vacuum science and technology-section b-microelectronics …
Journal: Journal of vacuum science and technology-section b-microelectronics …


Journal of vacuum science and technology-section b-microelectronics …
Journal: Journal of vacuum science and technology-section b-microelectronics …


Journal of electronic materials
Journal: Journal of electronic materials


Polski tygodnik lekarski (warsaw
Journal: Polski tygodnik lekarski (warsaw


Nature materials
Journal: Nature materials


Nature nanotechnology
Journal: Nature nanotechnology


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature materials
Journal: Nature materials


Nature materials
Journal: Nature materials


Advanced materials
Journal: Advanced materials


Nature materials
Journal: Nature materials


Nature materials
Journal: Nature materials


Energy &environmental science
Journal: Energy &environmental science


Energy &environmental science
Journal: Energy &environmental science


Advanced energy materials
Journal: Advanced energy materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature materials
Journal: Nature materials


Nature communications
Journal: Nature communications


Nature communications
Journal: Nature communications


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature nanotechnology
Journal: Nature nanotechnology


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


Nature communications
Journal: Nature communications


Advanced energy materials
Journal: Advanced energy materials


Advanced materials
Journal: Advanced materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced materials
Journal: Advanced materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of the american chemical society
Journal: Journal of the american chemical society


Energy &environmental science
Journal: Energy &environmental science


Energy &environmental science
Journal: Energy &environmental science


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Nature
Journal: Nature


Advanced materials
Journal: Advanced materials


Chemical communications
Journal: Chemical communications


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Thin solid films
Journal: Thin solid films


Acs energy letters
Journal: Acs energy letters


Advanced materials
Journal: Advanced materials


Advanced energy materials
Journal: Advanced energy materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Joule
Journal: Joule


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Chemical reviews
Journal: Chemical reviews


Advanced materials
Journal: Advanced materials


Joule
Journal: Joule


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Macromolecules
Journal: Macromolecules


Advanced science
Journal: Advanced science


Advanced functional materials
Journal: Advanced functional materials


Nature communications
Journal: Nature communications


Nano letters
Journal: Nano letters


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Acs nano
Journal: Acs nano


Science advances
Journal: Science advances


Acs energy letters
Journal: Acs energy letters


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Thin solid films
Journal: Thin solid films


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of catalysis
Journal: Journal of catalysis


Nature materials
Journal: Nature materials


Advanced materials
Journal: Advanced materials


Advanced functional materials
Journal: Advanced functional materials


Advanced energy materials
Journal: Advanced energy materials


Nature photonics
Journal: Nature photonics


Joule
Journal: Joule


Advanced materials
Journal: Advanced materials


Journal of applied physics
Journal: Journal of applied physics


Nature communications
Journal: Nature communications


Acs energy letters
Journal: Acs energy letters


Advanced materials
Journal: Advanced materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced materials
Journal: Advanced materials


Applied organometallic chemistry
Journal: Applied organometallic chemistry


Advanced energy materials
Journal: Advanced energy materials


Nanoscale
Journal: Nanoscale


Physica status solidi (rrl)–rapid research letters
Journal: Physica status solidi (rrl)–rapid research letters


Advanced energy materials
Journal: Advanced energy materials


Advanced science
Journal: Advanced science


Advanced functional materials
Journal: Advanced functional materials


Acs nano
Journal: Acs nano


Acs nano
Journal: Acs nano


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Materials horizons
Journal: Materials horizons


Advanced materials
Journal: Advanced materials


Proceedings of the national academy of sciences
Journal: Proceedings of the national academy of sciences


Journal of applied physics
Journal: Journal of applied physics


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Advanced electronic materials
Journal: Advanced electronic materials


Advanced energy materials
Journal: Advanced energy materials


Advanced functional materials
Journal: Advanced functional materials


Applied surface science
Journal: Applied surface science


Journal of materials chemistry
Journal: Journal of materials chemistry


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced energy materials
Journal: Advanced energy materials


Small
Journal: Small


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced functional materials
Journal: Advanced functional materials


Advanced materials (deerfield beach
Journal: Advanced materials (deerfield beach


Nature communications
Journal: Nature communications


Thin solid films
Journal: Thin solid films


Applied physics letters
Journal: Applied physics letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nano energy
Journal: Nano energy


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs energy letters
Journal: Acs energy letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Nanoscale
Journal: Nanoscale


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced functional materials
Journal: Advanced functional materials


Acs energy letters
Journal: Acs energy letters


Science advances
Journal: Science advances


Advanced materials
Journal: Advanced materials


Acs energy letters
Journal: Acs energy letters


Carbon
Journal: Carbon


Chemistry of materials
Journal: Chemistry of materials


Solar rrl
Journal: Solar rrl


Advanced functional materials
Journal: Advanced functional materials


Advanced energy materials
Journal: Advanced energy materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Mrs communications
Journal: Mrs communications


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Nano energy
Journal: Nano energy


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Journal of materials chemistry
Journal: Journal of materials chemistry


Cell reports physical science
Journal: Cell reports physical science


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of chemical physics
Journal: The journal of chemical physics


Advanced functional materials
Journal: Advanced functional materials


Solar rrl
Journal: Solar rrl


Advanced optical materials
Journal: Advanced optical materials


Advanced energy materials
Journal: Advanced energy materials


Sn applied sciences
Journal: Sn applied sciences


Light: science &applications
Journal: Light: science &applications


Advanced functional materials
Journal: Advanced functional materials


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Nano energy
Journal: Nano energy


Journal of materials research
Journal: Journal of materials research


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Applied physics letters
Journal: Applied physics letters


Advanced functional materials
Journal: Advanced functional materials


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Journal of materials chemistry
Journal: Journal of materials chemistry


Solar rrl
Journal: Solar rrl


Advanced energy materials
Journal: Advanced energy materials


Acs applied energy materials
Journal: Acs applied energy materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of applied physics
Journal: Journal of applied physics


Advanced materials technologies
Journal: Advanced materials technologies


Advanced functional materials
Journal: Advanced functional materials


Chemistry of materials
Journal: Chemistry of materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Advanced materials
Journal: Advanced materials


Thin solid films
Journal: Thin solid films


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced electronic materials
Journal: Advanced electronic materials


Solar rrl
Journal: Solar rrl


Chemistry of materials
Journal: Chemistry of materials


Solar rrl
Journal: Solar rrl


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Applied physics letters
Journal: Applied physics letters


Thin solid films
Journal: Thin solid films


Journal of physics: materials
Journal: Journal of physics: materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Solar rrl
Journal: Solar rrl


Journal of materials research
Journal: Journal of materials research


Optical materials
Journal: Optical materials


Advanced materials interfaces
Journal: Advanced materials interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Applied physics a
Journal: Applied physics a


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Acs applied energy materials
Journal: Acs applied energy materials


Chemical physics letters
Journal: Chemical physics letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Applied physics reviews
Journal: Applied physics reviews


Nanotechnology
Journal: Nanotechnology


Energy technology
Journal: Energy technology


Cogent engineering
Journal: Cogent engineering


Advanced materials
Journal: Advanced materials


Applied physics letters
Journal: Applied physics letters


Organic photonics and photovoltaics
Journal: Organic photonics and photovoltaics


Polymer chemistry
Journal: Polymer chemistry


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Advanced materials
Journal: Advanced materials


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Plos one
Journal: Plos one


Journal of applied physics
Journal: Journal of applied physics


Advanced materials
Journal: Advanced materials


Materials
Journal: Materials


Advanced energy materials
Journal: Advanced energy materials


Advanced materials
Journal: Advanced materials


Acs photonics
Journal: Acs photonics


Advanced functional materials
Journal: Advanced functional materials


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Spie newsroom 10 (2.1201309)
Journal: Spie newsroom


Optical interference coatings
Journal: Optical interference coatings


Optical interference coatings
Journal: Optical interference coatings


Nature communications
Journal: Nature communications


Organic and hybrid light emitting materials and devices xxv
Journal: Organic and hybrid light emitting materials and devices xxv


Nature photonics
Journal: Nature photonics


Organic
Journal: Organic


Advanced materials technologies
Journal: Advanced materials technologies


Advanced materials interfaces
Journal: Advanced materials interfaces


Physical chemistry of semiconductor materials and interfaces xvi
Journal: Physical chemistry of semiconductor materials and interfaces xvi


Organic field-effect transistors xvi
Journal: Organic field-effect transistors xvi


Pnas
Journal: Pnas


Acs energy letters
Journal: Acs energy letters


Advanced energy materials
Journal: Advanced energy materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Organic photovoltaics xvi
Journal: Organic photovoltaics xvi


Advanced functional materials
Journal: Advanced functional materials


Physical chemistry of interfaces and nanomaterials xiii
Journal: Physical chemistry of interfaces and nanomaterials xiii


Advanced functional materials
Journal: Advanced functional materials


Optical nanostructures and advanced materials for photovoltaics
Journal: Optical nanostructures and advanced materials for photovoltaics


Advanced materials
Journal: Advanced materials


Verhandlungen der deutschen physikalischen gesellschaft
Journal: Verhandlungen der deutschen physikalischen gesellschaft


Optical interference coatings
Journal: Optical interference coatings


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Organic electronics
Journal: Organic electronics


Journal of electroanalytical chemistry
Journal: Journal of electroanalytical chemistry


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs nano
Journal: Acs nano


The journal of physical chemistry b
Journal: The journal of physical chemistry b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Inorganica chimica acta
Journal: Inorganica chimica acta


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Energy &environmental science
Journal: Energy &environmental science


Applied physics letters
Journal: Applied physics letters


Advanced energy materials
Journal: Advanced energy materials


Advanced energy materials
Journal: Advanced energy materials


Nano letters
Journal: Nano letters


Journal of electroanalytical chemistry
Journal: Journal of electroanalytical chemistry


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Energy &environmental science
Journal: Energy &environmental science


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Electrochemistry communications
Journal: Electrochemistry communications


Applied physics letters
Journal: Applied physics letters


Journal of applied physics
Journal: Journal of applied physics


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Chemical physics letters 422 (1-3)
Journal: Chemical physics letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Applied physics letters
Journal: Applied physics letters


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Applied physics letters
Journal: Applied physics letters


Energy &environmental science
Journal: Energy &environmental science


Advanced energy materials
Journal: Advanced energy materials


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Chemical physics letters 465 (1-3)
Journal: Chemical physics letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of solid state electrochemistry
Journal: Journal of solid state electrochemistry


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of applied physics
Journal: Journal of applied physics


Journal of applied physics
Journal: Journal of applied physics


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Electrochemistry communications
Journal: Electrochemistry communications


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Electrochimica acta
Journal: Electrochimica acta


Acs nano
Journal: Acs nano


Electrochimica acta
Journal: Electrochimica acta


Applied physics letters
Journal: Applied physics letters


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Physical chemistry chemical physics

Rsc advances
Journal: Rsc advances


Electrochimica acta
Journal: Electrochimica acta


Journal of materials chemistry
Journal: Journal of materials chemistry


Organic electronics
Journal: Organic electronics


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Sensors and actuators a: physical
Journal: Sensors and actuators a: physical


Electrochimica acta
Journal: Electrochimica acta


Physica status solidi (a)
Journal: Physica status solidi (a)


Solar rrl
Journal: Solar rrl


Chemelectrochem
Journal: Chemelectrochem


Solar rrl
Journal: Solar rrl


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Solar rrl
Journal: Solar rrl


Journal of nanophotonics
Journal: Journal of nanophotonics


Advanced energy materials
Journal: Advanced energy materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nanomaterials
Journal: Nanomaterials


Oxide-based materials and devices ix
Journal: Oxide-based materials and devices ix


Acs applied energy materials
Journal: Acs applied energy materials


Acs applied energy materials
Journal: Acs applied energy materials


Journal of materials science
Journal: Journal of materials science


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


Electrochimica acta
Journal: Electrochimica acta


Langmuir
Journal: Langmuir


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Nuclear engineering and design
Journal: Nuclear engineering and design


Turkish journal of physics
Journal: Turkish journal of physics


International journal of quantum chemistry
Journal: International journal of quantum chemistry


Journal of electroanalytical chemistry
Journal: Journal of electroanalytical chemistry


Thin solid films
Journal: Thin solid films


Journal of engineering sciences
Journal: Journal of engineering sciences


Oxide-based materials and devices v
Journal: Oxide-based materials and devices v


Chemsuschem
Journal: Chemsuschem


Materials chemistry and physics
Journal: Materials chemistry and physics


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of power sources
Journal: Journal of power sources


Journal of electroanalytical chemistry
Journal: Journal of electroanalytical chemistry


Journal of computational chemistry
Journal: Journal of computational chemistry


Oxide-based materials and devices vi
Journal: Oxide-based materials and devices vi


Oxide-based materials and devices vi
Journal: Oxide-based materials and devices vi


Electrochimica acta
Journal: Electrochimica acta


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Oxide-based materials and devices ix
Journal: Oxide-based materials and devices ix


Oxide-based materials and devices viii
Journal: Oxide-based materials and devices viii


Oxide-based materials and devices vii
Journal: Oxide-based materials and devices vii


Electrochimica acta
Journal: Electrochimica acta


Physica status solidi (b)
Journal: Physica status solidi (b)


Ecs transactions
Journal: Ecs transactions


Physica status solidi (a)
Journal: Physica status solidi (a)


Journal of electroanalytical chemistry
Journal: Journal of electroanalytical chemistry


Nano energy
Journal: Nano energy


Energies
Journal: Energies


Oxide-based materials and devices viii
Journal: Oxide-based materials and devices viii


Physica status solidi (b)
Journal: Physica status solidi (b)


Journal of surface engineered materials and advanced technology
Journal: Journal of surface engineered materials and advanced technology


Oxide-based materials and devices vi
Journal: Oxide-based materials and devices vi


Journal of electroanalytical chemistry (1992) 598 (1-2)
Journal: Journal of electroanalytical chemistry (


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Oxide-based materials and devices v
Journal: Oxide-based materials and devices v


Oxide-based materials and devices iv
Journal: Oxide-based materials and devices iv


Journal of electroanalytical chemistry 598 (1-2)
Journal: Journal of electroanalytical chemistry


Advanced materials interfaces
Journal: Advanced materials interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nano energy
Journal: Nano energy


Oxide-based materials and devices viii
Journal: Oxide-based materials and devices viii


Oxide-based materials and devices iv
Journal: Oxide-based materials and devices iv


Zinc oxide materials and devices iv
Journal: Zinc oxide materials and devices iv


Ecs transactions
Journal: Ecs transactions


Ionics
Journal: Ionics


Journal of engineering sciences
Journal: Journal of engineering sciences


Photoniques
Journal: Photoniques


Nature communications
Journal: Nature communications


Small methods
Journal: Small methods


Applied physics letters
Journal: Applied physics letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Electronics
Journal: Electronics


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Oxide-based materials and devices xi
Journal: Oxide-based materials and devices xi


Electronics
Journal: Electronics


Optical components and materials xv
Journal: Optical components and materials xv


Multidisciplinarity in modern science for the benefit of society
Journal: Multidisciplinarity in modern science for the benefit of society


Superlattices and microstructures
Journal: Superlattices and microstructures


Moldavian journal of the physical sciences 15 (3-4)
Journal: Moldavian journal of the physical sciences


Ecs transactions
Journal: Ecs transactions


Oxide-based materials and devices iii
Journal: Oxide-based materials and devices iii


Physica status solidi. a
Journal: Physica status solidi. a


L'actualité chimique
Journal: L'actualité chimique


Electrochemical and solid state letters
Journal: Electrochemical and solid state letters


Journal of electroanalytical chemistry
Journal: Journal of electroanalytical chemistry


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Applied physics letters
Journal: Applied physics letters


Appl. phys. lett.
Journal: Appl. phys. lett.


Nature materials
Journal: Nature materials


Advanced materials
Journal: Advanced materials


Nature photonics
Journal: Nature photonics


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Nature energy
Journal: Nature energy


Advanced materials
Journal: Advanced materials


Nature
Journal: Nature


Nature photonics
Journal: Nature photonics


Nature energy
Journal: Nature energy


Advanced materials
Journal: Advanced materials


Nature energy
Journal: Nature energy


Nature materials
Journal: Nature materials


Nature materials
Journal: Nature materials


Advanced materials
Journal: Advanced materials


Applied physics letters
Journal: Applied physics letters


Nature communications
Journal: Nature communications


Science
Journal: Science


Advanced materials
Journal: Advanced materials


Nature energy
Journal: Nature energy


Journal of the american chemical society
Journal: Journal of the american chemical society


Energy &environmental science
Journal: Energy &environmental science


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Npj flexible electronics
Journal: Npj flexible electronics


Joule
Journal: Joule


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


Energy &environmental science
Journal: Energy &environmental science


Advanced energy materials
Journal: Advanced energy materials


Advanced functional materials
Journal: Advanced functional materials


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Science
Journal: Science


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced materials
Journal: Advanced materials


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Advanced energy materials
Journal: Advanced energy materials


Advanced materials
Journal: Advanced materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced functional materials
Journal: Advanced functional materials


Nature communications
Journal: Nature communications


Nanoscale
Journal: Nanoscale


Advanced materials
Journal: Advanced materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Science china chemistry
Journal: Science china chemistry


Joule
Journal: Joule


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Chinese journal of chemistry
Journal: Chinese journal of chemistry


Advanced energy materials
Journal: Advanced energy materials


Advanced materials
Journal: Advanced materials


Applied physics letters
Journal: Applied physics letters


Nature energy
Journal: Nature energy


Materials horizons
Journal: Materials horizons


Advanced energy materials
Journal: Advanced energy materials


Nature
Journal: Nature


Energy &environmental science
Journal: Energy &environmental science


Mater. sci
Journal: Mater. sci


Nano energy
Journal: Nano energy


Physical review letters
Journal: Physical review letters


Applied physics letters
Journal: Applied physics letters


Advanced optical materials
Journal: Advanced optical materials


Chem
Journal: Chem


Advanced functional materials
Journal: Advanced functional materials


Nature communications
Journal: Nature communications


Nature energy
Journal: Nature energy


Angewandte chemie
Journal: Angewandte chemie


Science bulletin
Journal: Science bulletin


Nature communications
Journal: Nature communications


Advanced optical materials
Journal: Advanced optical materials


Advanced materials
Journal: Advanced materials


Advanced functional materials
Journal: Advanced functional materials


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Nature communications
Journal: Nature communications


Materials today nano
Journal: Materials today nano


Journal of applied physics
Journal: Journal of applied physics


Advanced electronic materials
Journal: Advanced electronic materials


Advanced energy materials
Journal: Advanced energy materials


Advanced science
Journal: Advanced science


Advanced energy materials
Journal: Advanced energy materials


Chemical society reviews
Journal: Chemical society reviews


Advanced functional materials
Journal: Advanced functional materials


Acs nano
Journal: Acs nano


Nature electronics
Journal: Nature electronics


Nature communications
Journal: Nature communications


Advanced optical materials
Journal: Advanced optical materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Applied physics letters
Journal: Applied physics letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Aggregate
Journal: Aggregate


Science china chemistry
Journal: Science china chemistry


Angewandte chemie
Journal: Angewandte chemie


Angewandte chemie
Journal: Angewandte chemie


Joule
Journal: Joule


Nature communications
Journal: Nature communications


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced energy materials
Journal: Advanced energy materials


Advanced energy materials
Journal: Advanced energy materials


Advanced functional materials
Journal: Advanced functional materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced functional materials
Journal: Advanced functional materials


Nature photonics
Journal: Nature photonics


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Science advances
Journal: Science advances


Energy &environmental science
Journal: Energy &environmental science


Acs energy letters
Journal: Acs energy letters


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of materials chemistry a
Journal: Journal of materials chemistry a


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced materials
Journal: Advanced materials


Joule
Journal: Joule


Advanced materials
Journal: Advanced materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs energy letters
Journal: Acs energy letters


Chemistry of materials
Journal: Chemistry of materials


Matter
Journal: Matter


Advanced energy materials
Journal: Advanced energy materials


Physica status solidi (a)
Journal: Physica status solidi (a)


Organic electronics
Journal: Organic electronics


Nano letters
Journal: Nano letters


Nature communications
Journal: Nature communications


Nano letters
Journal: Nano letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced materials interfaces
Journal: Advanced materials interfaces


Scientific reports
Journal: Scientific reports


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Science china chemistry
Journal: Science china chemistry


Nature communications
Journal: Nature communications


Applied physics letters
Journal: Applied physics letters


Energy &environmental science
Journal: Energy &environmental science


Acs energy letters
Journal: Acs energy letters


Advanced functional materials
Journal: Advanced functional materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Solar rrl
Journal: Solar rrl


Advanced materials
Journal: Advanced materials


Applied physics letters
Journal: Applied physics letters


Science
Journal: Science


Science advances
Journal: Science advances


Nature communications
Journal: Nature communications


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Organic electronics
Journal: Organic electronics


Nature communications
Journal: Nature communications


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Applied physics letters
Journal: Applied physics letters


Science
Journal: Science


National science review
Journal: National science review


Physical review applied
Journal: Physical review applied


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Nature photonics
Journal: Nature photonics


Cell reports physical science
Journal: Cell reports physical science


Trends in chemistry
Journal: Trends in chemistry


Science china chemistry
Journal: Science china chemistry


Advanced materials interfaces
Journal: Advanced materials interfaces


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Organic electronics
Journal: Organic electronics


Joule
Journal: Joule


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Small structures
Journal: Small structures


Applied physics letters
Journal: Applied physics letters


Solid state communications
Journal: Solid state communications


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Israel journal of chemistry
Journal: Israel journal of chemistry


Journal of applied physics
Journal: Journal of applied physics


Materials science and engineering: b
Journal: Materials science and engineering: b


Science bulletin
Journal: Science bulletin


Acs photonics
Journal: Acs photonics


Small
Journal: Small


Advanced materials
Journal: Advanced materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of applied physics
Journal: Journal of applied physics


Nature communications
Journal: Nature communications


Advanced functional materials
Journal: Advanced functional materials


Chemical science
Journal: Chemical science


Solar rrl
Journal: Solar rrl


Applied physics letters
Journal: Applied physics letters


Advanced materials
Journal: Advanced materials


Acs photonics
Journal: Acs photonics


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Small
Journal: Small


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Solar rrl
Journal: Solar rrl


Small
Journal: Small


Journal of applied physics
Journal: Journal of applied physics


Applied physics a
Journal: Applied physics a


Matter
Journal: Matter


Advanced functional materials
Journal: Advanced functional materials


Nano energy
Journal: Nano energy


Small methods
Journal: Small methods


Chemistry of materials
Journal: Chemistry of materials


Thin solid films
Journal: Thin solid films


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced optical materials
Journal: Advanced optical materials


Chemical science
Journal: Chemical science


Materials chemistry frontiers
Journal: Materials chemistry frontiers


Journal of electroceramics
Journal: Journal of electroceramics


Joule
Journal: Joule


Adv. energy mater
Journal: Adv. energy mater


Journal of applied physics
Journal: Journal of applied physics


Nature communications
Journal: Nature communications


Acs energy letters
Journal: Acs energy letters


Science china chemistry
Journal: Science china chemistry


Aggregate
Journal: Aggregate


Solar rrl
Journal: Solar rrl


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of energy chemistry
Journal: Journal of energy chemistry


Chemical communications
Journal: Chemical communications


Rsc advances
Journal: Rsc advances


Advanced energy materials
Journal: Advanced energy materials


Macromolecular rapid communications
Journal: Macromolecular rapid communications


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Science china chemistry
Journal: Science china chemistry


Solar rrl
Journal: Solar rrl


Europhysics letters
Journal: Europhysics letters


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Optics express
Journal: Optics express


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nano energy
Journal: Nano energy


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced materials
Journal: Advanced materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Solar rrl
Journal: Solar rrl


Joule
Journal: Joule


Chem
Journal: Chem


Advanced optical materials
Journal: Advanced optical materials


The journal of physical chemistry c

The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of physical chemistry b
Journal: Journal of physical chemistry b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of alloys and compounds
Journal: Journal of alloys and compounds


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nanoscale
Journal: Nanoscale


Applied physics letters
Journal: Applied physics letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Journal of photochemistry and photobiology c: photochemistry reviews
Journal: Journal of photochemistry and photobiology c: photochemistry reviews


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemical physics letters 407 (4-6)
Journal: Chemical physics letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Materials letters
Journal: Materials letters


Chemical physics letters 473 (1-3)
Journal: Chemical physics letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemistry–a european journal
Journal: Chemistry–a european journal


Langmuir
Journal: Langmuir


Optical materials
Journal: Optical materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nanoscale
Journal: Nanoscale


Optical materials
Journal: Optical materials


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of luminescence 111 (1-2)
Journal: Journal of luminescence


Spectrochimica acta part a: molecular and biomolecular spectroscopy 54 (13 …
Journal: Spectrochimica acta part a: molecular and biomolecular spectroscopy


Chemical physics letters 387 (1-3)
Journal: Chemical physics letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nanoscale
Journal: Nanoscale


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Optics &laser technology
Journal: Optics &laser technology


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of materials chemistry
Journal: Journal of materials chemistry


Journal of colloid and interface science
Journal: Journal of colloid and interface science


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Crystal growth &design
Journal: Crystal growth &design


Solid state communications
Journal: Solid state communications


Rsc advances
Journal: Rsc advances


Chemphyschem
Journal: Chemphyschem


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Chemical physics letters 440 (1-3)
Journal: Chemical physics letters


Nanoscale
Journal: Nanoscale


Journal of applied physics
Journal: Journal of applied physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of luminescence
Journal: Journal of luminescence


Chemical physics letters 413 (4-6)
Journal: Chemical physics letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


Crystengcomm
Journal: Crystengcomm


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Optical materials
Journal: Optical materials


Chemphyschem
Journal: Chemphyschem


Chemphyschem
Journal: Chemphyschem


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Small
Journal: Small


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Crystal growth and design
Journal: Crystal growth and design


Optical materials
Journal: Optical materials


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of photochemistry and photobiology c: photochemistry reviews
Journal: Journal of photochemistry and photobiology c: photochemistry reviews


Journal of materials chemistry c
Journal: Journal of materials chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Applied physics letters
Journal: Applied physics letters


Crystal growth and design
Journal: Crystal growth and design


Journal of luminescence
Journal: Journal of luminescence


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of luminescence
Journal: Journal of luminescence


Materials letters
Journal: Materials letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


Journal of applied physics
Journal: Journal of applied physics


Optical materials
Journal: Optical materials


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Rsc advances
Journal: Rsc advances


Chemphyschem
Journal: Chemphyschem


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Chemphyschem
Journal: Chemphyschem


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Materials letters
Journal: Materials letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Journal of sol-gel science and technology
Journal: Journal of sol-gel science and technology


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Bulletin of materials science
Journal: Bulletin of materials science


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nanoscale
Journal: Nanoscale


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemical physics letters 462 (1-3)
Journal: Chemical physics letters


Nano-structures &nano-objects
Journal: Nano-structures &nano-objects


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemphyschem
Journal: Chemphyschem


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Journal of chemical sciences
Journal: Journal of chemical sciences


Chemistry–a european journal
Journal: Chemistry–a european journal


Nanoscale
Journal: Nanoscale


Acs omega
Journal: Acs omega


Photochemical &photobiological sciences
Journal: Photochemical &photobiological sciences


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of luminescence
Journal: Journal of luminescence


Rsc advances
Journal: Rsc advances


Applied physics letters
Journal: Applied physics letters


Acs applied nano materials
Journal: Acs applied nano materials


Transactions of the indian ceramic society
Journal: Transactions of the indian ceramic society


Journal of nanoscience and nanotechnology
Journal: Journal of nanoscience and nanotechnology


Chemical communications
Journal: Chemical communications


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Reviews in nanoscience and nanotechnology
Journal: Reviews in nanoscience and nanotechnology


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Materials letters
Journal: Materials letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemphyschem
Journal: Chemphyschem


Journal of nanoscience and nanotechnology
Journal: Journal of nanoscience and nanotechnology


The journal of physical chemistry b
Journal: The journal of physical chemistry b


J. opt. soc. am. b
Journal: J. opt. soc. am. b


J. opt. soc. am. b
Journal: J. opt. soc. am. b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of nanomaterials
Journal: Journal of nanomaterials


Chemphyschem
Journal: Chemphyschem


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemical physics letters 405 (4-6)
Journal: Chemical physics letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Solid state communications
Journal: Solid state communications


Materials letters
Journal: Materials letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Bulletin of materials science
Journal: Bulletin of materials science


Materials horizons
Journal: Materials horizons


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of nanoparticle research
Journal: Journal of nanoparticle research


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of applied physics
Journal: Journal of applied physics


Journal of materials science letters
Journal: Journal of materials science letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of non-crystalline solids
Journal: Journal of non-crystalline solids


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Small
Journal: Small


Rsc advances
Journal: Rsc advances


Rsc advances
Journal: Rsc advances


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Applied physics letters
Journal: Applied physics letters


Nanomaterials
Journal: Nanomaterials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Bulletin of materials science
Journal: Bulletin of materials science


Pramana
Journal: Pramana


Bulletin of materials science
Journal: Bulletin of materials science


Bulletin of materials science
Journal: Bulletin of materials science


Journal of non-crystalline solids
Journal: Journal of non-crystalline solids


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of luminescence
Journal: Journal of luminescence


Journal of nanoscience and nanotechnology
Journal: Journal of nanoscience and nanotechnology


Materials letters
Journal: Materials letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of nanoparticle research
Journal: Journal of nanoparticle research


Journal of fluorescence
Journal: Journal of fluorescence


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nanoscale advances
Journal: Nanoscale advances


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemistry–an asian journal
Journal: Chemistry–an asian journal


Gold bulletin
Journal: Gold bulletin


Synthetic metals
Journal: Synthetic metals


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Chemistryselect
Journal: Chemistryselect


Journal of nanoscience and nanotechnology
Journal: Journal of nanoscience and nanotechnology


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of nanoscience and nanotechnology
Journal: Journal of nanoscience and nanotechnology


Gold bulletin
Journal: Gold bulletin


Chemphyschem
Journal: Chemphyschem


Physics and chemistry of glasses
Journal: Physics and chemistry of glasses


Inorganic chemistry
Journal: Inorganic chemistry


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Bulletin of materials science
Journal: Bulletin of materials science


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of nanoscience and nanotechnology
Journal: Journal of nanoscience and nanotechnology


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Materials research express
Journal: Materials research express


Acs applied nano materials
Journal: Acs applied nano materials


Optical materials: x
Journal: Optical materials: x


Chemphyschem
Journal: Chemphyschem


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Gold bulletin
Journal: Gold bulletin


Journal of nanophotonics
Journal: Journal of nanophotonics


Journal of physics and chemistry of solids
Journal: Journal of physics and chemistry of solids


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Colloidal nanoparticles for biomedical applications xiii
Journal: Colloidal nanoparticles for biomedical applications xiii


Journal of materials science letters
Journal: Journal of materials science letters


Transactions of the indian ceramic society
Journal: Transactions of the indian ceramic society


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


Acs applied nano materials
Journal: Acs applied nano materials


International journal of nanoscience 10 (01n02)
Journal: International journal of nanoscience


Optical materials
Journal: Optical materials


Indian journal of physics
Journal: Indian journal of physics


Physics and chemistry of glasses
Journal: Physics and chemistry of glasses


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemnanomat
Journal: Chemnanomat


Nanoscale
Journal: Nanoscale


Small
Journal: Small


Nanoparticle assembly: from fundamentals to applications
Journal: Nanoparticle assembly: from fundamentals to applications


International journal of nanoscience 10 (04n05)
Journal: International journal of nanoscience


Journal of physics. d
Journal: Journal of physics. d


Indian journal of virology
Journal: Indian journal of virology


Frontiers in optics
Journal: Frontiers in optics


Transactions of the indian ceramic society
Journal: Transactions of the indian ceramic society


Materials letters
Journal: Materials letters


Science
Journal: Science


Nature materials
Journal: Nature materials


Advanced materials
Journal: Advanced materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature
Journal: Nature


Joule
Journal: Joule


Journal of the american chemical society
Journal: Journal of the american chemical society


Energy &environmental science
Journal: Energy &environmental science


Nano energy
Journal: Nano energy


Nature photonics
Journal: Nature photonics


Advanced materials
Journal: Advanced materials


Science
Journal: Science


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Nanoscale
Journal: Nanoscale


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Macromolecular rapid communications
Journal: Macromolecular rapid communications


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


Journal of materials chemistry
Journal: Journal of materials chemistry


Journal of the american chemical society
Journal: Journal of the american chemical society


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Advanced energy materials
Journal: Advanced energy materials


Energy &environmental science
Journal: Energy &environmental science


Chemistry of materials
Journal: Chemistry of materials


Acs nano
Journal: Acs nano


Macromolecules
Journal: Macromolecules


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Macromolecules
Journal: Macromolecules


Advanced materials
Journal: Advanced materials


Journal of materials chemistry
Journal: Journal of materials chemistry


Macromolecules
Journal: Macromolecules


Particle &particle systems characterization
Journal: Particle &particle systems characterization


Journal of applied physics
Journal: Journal of applied physics


Macromolecules
Journal: Macromolecules


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


Nanoscale
Journal: Nanoscale


Scientific reports
Journal: Scientific reports


Organic letters
Journal: Organic letters


Macromolecules
Journal: Macromolecules


Advanced energy materials
Journal: Advanced energy materials


Applied physics letters
Journal: Applied physics letters


Energy &environmental science
Journal: Energy &environmental science


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Energy &environmental science
Journal: Energy &environmental science


Energy &environmental science
Journal: Energy &environmental science


Macromolecules
Journal: Macromolecules


Advanced functional materials
Journal: Advanced functional materials


Macromolecules
Journal: Macromolecules


Macromolecules
Journal: Macromolecules


Applied physics letters
Journal: Applied physics letters


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


Advanced energy materials
Journal: Advanced energy materials


Advanced materials
Journal: Advanced materials


Advanced energy materials

Dyes and pigments
Journal: Dyes and pigments


Journal of applied spectroscopy
Journal: Journal of applied spectroscopy


Smart optical inorganic structures and devices
Journal: Smart optical inorganic structures and devices


Acs applied energy materials
Journal: Acs applied energy materials


Lithuanian journal of physics
Journal: Lithuanian journal of physics


Plasmonics
Journal: Plasmonics


Nanoscale research letters
Journal: Nanoscale research letters


Physica status solidi (a)
Journal: Physica status solidi (a)


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physica status solidi (b)
Journal: Physica status solidi (b)


Molecular crystals and liquid crystals
Journal: Molecular crystals and liquid crystals


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Lithuanian physics journal
Journal: Lithuanian physics journal


Optical organic and semiconductor inorganic materials
Journal: Optical organic and semiconductor inorganic materials


Zhurnal fizicheskoi khimii
Journal: Zhurnal fizicheskoi khimii


Organic electronics
Journal: Organic electronics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physica status solidi (rrl)–rapid research letters
Journal: Physica status solidi (rrl)–rapid research letters


Chemical physics
Journal: Chemical physics


Advanced organic and inorganic optical materials
Journal: Advanced organic and inorganic optical materials


Physica status solidi (rrl)–rapid research letters
Journal: Physica status solidi (rrl)–rapid research letters


Photonics
Journal: Photonics


Physica status solidi (a)
Journal: Physica status solidi (a)


Lithuanian journal of physics
Journal: Lithuanian journal of physics


Synthetic metals
Journal: Synthetic metals


Optical instrumentation for energy and environmental applications
Journal: Optical instrumentation for energy and environmental applications


Nanomaterials: application &properties'
Journal: Nanomaterials: application &properties'


Lithuanian journal of physics and technical sciences
Journal: Lithuanian journal of physics and technical sciences


Physical review letters
Journal: Physical review letters


Optical organic and inorganic materials
Journal: Optical organic and inorganic materials


Optical organic and inorganic materials
Journal: Optical organic and inorganic materials


Journal of physical chemistry a
Journal: Journal of physical chemistry a


Journal of physical chemistry b-condensed phase
Journal: Journal of physical chemistry b-condensed phase


Biophysical journal
Journal: Biophysical journal


Lithuanian physics journal c/c of litovskii fizicheskii sbornik
Journal: Lithuanian physics journal c/c of litovskii fizicheskii sbornik


Lithuanian physics journal 34 (1-2)
Journal: Lithuanian physics journal


Laser spectroscopy of biomolecules
Journal: Laser spectroscopy of biomolecules


Synthetic metals
Journal: Synthetic metals


Mode-locked lasers and ultrafast phenomena
Journal: Mode-locked lasers and ultrafast phenomena


Science
Journal: Science


Nature
Journal: Nature


Nature materials
Journal: Nature materials


Nature materials
Journal: Nature materials


Nature communications
Journal: Nature communications


Acs nano
Journal: Acs nano


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Apl materials
Journal: Apl materials


Nature communications
Journal: Nature communications


Acs nano
Journal: Acs nano


Extreme mechanics letters
Journal: Extreme mechanics letters


Scientific reports
Journal: Scientific reports


Advanced energy materials
Journal: Advanced energy materials


Electrochemistry communications
Journal: Electrochemistry communications


Electroanalysis: an international journal devoted to fundamental and …
Journal: Electroanalysis: an international journal devoted to fundamental and …


Electroanalysis: an international journal devoted to fundamental and …
Journal: Electroanalysis: an international journal devoted to fundamental and …


International journal of non-linear mechanics
Journal: International journal of non-linear mechanics


Chemistry of materials
Journal: Chemistry of materials


Scientific reports
Journal: Scientific reports


Applied materials today
Journal: Applied materials today


Electrochemistry communications
Journal: Electrochemistry communications


The internet journal of gynaecology and obstetrics
Journal: The internet journal of gynaecology and obstetrics


Advanced functional materials
Journal: Advanced functional materials


Chemical communications
Journal: Chemical communications


Acs nano
Journal: Acs nano


Biosensors and bioelectronics
Journal: Biosensors and bioelectronics


Macromolecules
Journal: Macromolecules


Electrochimica acta
Journal: Electrochimica acta


Acs nano
Journal: Acs nano


Advanced energy materials
Journal: Advanced energy materials


Acs applied nano materials
Journal: Acs applied nano materials


C
Journal: C


Materials today
Journal: Materials today


Advanced materials
Journal: Advanced materials


Powder technology
Journal: Powder technology


Acs nano
Journal: Acs nano


Science advances
Journal: Science advances


Langmuir
Journal: Langmuir


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Physical review b
Journal: Physical review b


Progress in additive manufacturing
Journal: Progress in additive manufacturing


Physical review applied
Journal: Physical review applied


International journal of hydrogen energy
Journal: International journal of hydrogen energy


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Acs nano
Journal: Acs nano


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Additive manufacturing
Journal: Additive manufacturing


Journal of applied physics
Journal: Journal of applied physics


Npj 2d materials and applications
Journal: Npj


Chemnanomat
Journal: Chemnanomat


Nanoscale
Journal: Nanoscale


Applied physics letters
Journal: Applied physics letters


Scandinavian journal of immunology
Journal: Scandinavian journal of immunology


Advanced science
Journal: Advanced science


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Surface and coatings technology
Journal: Surface and coatings technology


Journal of non-newtonian fluid mechanics
Journal: Journal of non-newtonian fluid mechanics


Particulate science and technology
Journal: Particulate science and technology


Smart materials and structures
Journal: Smart materials and structures


Advanced optical materials
Journal: Advanced optical materials


Acs nano
Journal: Acs nano


Rapid prototyping journal
Journal: Rapid prototyping journal


Acs nano
Journal: Acs nano


Physica status solidi (a)
Journal: Physica status solidi (a)


Electroanalysis
Journal: Electroanalysis


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Biointerphases
Journal: Biointerphases


Journal of surgical research
Journal: Journal of surgical research


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nanotechnology
Journal: Nanotechnology


Lupus
Journal: Lupus


Inorganic chemistry
Journal: Inorganic chemistry


Rsc advances
Journal: Rsc advances


Materials and manufacturing processes
Journal: Materials and manufacturing processes


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Haryana vet
Journal: Haryana vet


Environmental science: water research &technology
Journal: Environmental science: water research &technology


Applied materials today
Journal: Applied materials today


Int. j. health sci. res
Journal: Int. j. health sci. res


Smart materials and structures
Journal: Smart materials and structures


Ieee sensors journal
Journal: Ieee sensors journal


Smart materials and structures
Journal: Smart materials and structures


Haryana veterinarian
Journal: Haryana veterinarian


Journal of personality and clinical studies
Journal: Journal of personality and clinical studies


Rsc advances
Journal: Rsc advances


Inorganica chimica acta
Journal: Inorganica chimica acta


Buff bull
Journal: Buff bull


Micro-and nanotechnology sensors
Journal: Micro-and nanotechnology sensors


Ecs journal of solid state science and technology
Journal: Ecs journal of solid state science and technology


Haryana vet
Journal: Haryana vet


Manufacturing letters
Journal: Manufacturing letters


Applied materials today
Journal: Applied materials today


Ecs transactions
Journal: Ecs transactions


Manuscript under review
Journal: Manuscript under review


Cytokine
Journal: Cytokine


J. chem. phys
Journal: J. chem. phys


Indian journal of clinical psychology
Journal: Indian journal of clinical psychology


Biointerphases
Journal: Biointerphases


Bmj supportive &palliative care 13 (suppl 1)
Journal: Bmj supportive &palliative care


Journal of pharmaceutical sciences and research
Journal: Journal of pharmaceutical sciences and research


Rsc advances
Journal: Rsc advances


New journal of chemistry
Journal: New journal of chemistry


Rsc advances
Journal: Rsc advances


Npj 2d materials and applications
Journal: Npj


American journal of respiratory and critical care medicine
Journal: American journal of respiratory and critical care medicine


J anal pharm res
Journal: J anal pharm res


Journal of the anatomical society of india
Journal: Journal of the anatomical society of india


Structural health monitoring
Journal: Structural health monitoring


Advanced optical materials
Journal: Advanced optical materials


Advances in structural health management and composite structures
Journal: Advances in structural health management and composite structures


Manual on membrane lipids
Journal: Manual on membrane lipids


Cytokine
Journal: Cytokine


Year book of dermatology and dermatological surgery 2012
Journal: Year book of dermatology and dermatological surgery


Haryana veterinarian
Journal: Haryana veterinarian


Intensive care medicine
Journal: Intensive care medicine


Journal of immunology and immunopathology 6 (supp1)
Journal: Journal of immunology and immunopathology


Journal of immunology and immunopathology 6 (supp1)
Journal: Journal of immunology and immunopathology


Chemosphere
Journal: Chemosphere


Antec 92--shaping the future.
Journal: Antec


Journal of personality and clinical studies
Journal: Journal of personality and clinical studies


Journal of all india institute of speech and hearing
Journal: Journal of all india institute of speech and hearing


Gastroenterology
Journal: Gastroenterology


Gastroenterology
Journal: Gastroenterology


Nature materials
Journal: Nature materials


Chemistry of materials
Journal: Chemistry of materials


The journal of chemical physics
Journal: The journal of chemical physics


Nature materials
Journal: Nature materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Chemistry of materials
Journal: Chemistry of materials


International reviews in physical chemistry
Journal: International reviews in physical chemistry


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Physical review letters
Journal: Physical review letters


Advanced materials
Journal: Advanced materials


Nature nanotechnology
Journal: Nature nanotechnology


Journal of the american chemical society
Journal: Journal of the american chemical society


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced functional materials
Journal: Advanced functional materials


Nature chemistry
Journal: Nature chemistry


Nano letters
Journal: Nano letters


Chemphyschem
Journal: Chemphyschem


The journal of chemical physics
Journal: The journal of chemical physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nature communications
Journal: Nature communications


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs nano
Journal: Acs nano


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Angewandte chemie
Journal: Angewandte chemie


The journal of physical chemistry b
Journal: The journal of physical chemistry b


International journal of quantum chemistry
Journal: International journal of quantum chemistry


Nano letters
Journal: Nano letters


The journal of chemical physics
Journal: The journal of chemical physics


The journal of organic chemistry
Journal: The journal of organic chemistry


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Chemistry of materials
Journal: Chemistry of materials


Nanoscale
Journal: Nanoscale


Chemsuschem
Journal: Chemsuschem


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Beilstein journal of nanotechnology
Journal: Beilstein journal of nanotechnology


Acs omega
Journal: Acs omega


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Journal of materials chemistry
Journal: Journal of materials chemistry


Journal of materials chemistry
Journal: Journal of materials chemistry


Nature communications
Journal: Nature communications


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review b
Journal: Physical review b


Nature chemistry
Journal: Nature chemistry


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Physical review b
Journal: Physical review b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Angewandte chemie international edition
Journal: Angewandte chemie international edition


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of chemical physics
Journal: The journal of chemical physics


International journal of quantum chemistry 75 (4‐5)
Journal: International journal of quantum chemistry


Acs nano
Journal: Acs nano


Advanced functional materials
Journal: Advanced functional materials


Physica status solidi (b)
Journal: Physica status solidi (b)


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry b
Journal: The journal of physical chemistry b


The journal of physical chemistry b
Journal: The journal of physical chemistry b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Chemical science
Journal: Chemical science


Beilstein journal of organic chemistry
Journal: Beilstein journal of organic chemistry


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Advanced materials
Journal: Advanced materials


Chemical science
Journal: Chemical science


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Rsc advances
Journal: Rsc advances


The journal of organic chemistry
Journal: The journal of organic chemistry


Chempluschem
Journal: Chempluschem


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Organic chemistry frontiers
Journal: Organic chemistry frontiers


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry a
Journal: The journal of physical chemistry a


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Energy technology
Journal: Energy technology


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Nano letters
Journal: Nano letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Organic letters
Journal: Organic letters


The journal of physical chemistry b
Journal: The journal of physical chemistry b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of chemical physics
Journal: The journal of chemical physics


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Acs energy letters
Journal: Acs energy letters


Acs applied energy materials
Journal: Acs applied energy materials


The journal of physical chemistry a
Journal: The journal of physical chemistry a


The journal of chemical physics
Journal: The journal of chemical physics


The journal of physical chemistry a
Journal: The journal of physical chemistry a


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Tetrahedron
Journal: Tetrahedron


The journal of physical chemistry a
Journal: The journal of physical chemistry a


The journal of organic chemistry
Journal: The journal of organic chemistry


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Chemistry–a european journal
Journal: Chemistry–a european journal


The journal of physical chemistry b
Journal: The journal of physical chemistry b


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Solar rrl
Journal: Solar rrl


Molecular simulation
Journal: Molecular simulation


Journal of molecular structure: theochem 464 (1-3)
Journal: Journal of molecular structure: theochem


The journal of physical chemistry c
Journal: The journal of physical chemistry c



Physical review b
Journal: Physical review b


Journal of physics and chemistry of solids 67 (9-10)
Journal: Journal of physics and chemistry of solids


Physica status solidi (b)
Journal: Physica status solidi (b)


Nature chemistry
Journal: Nature chemistry


Applied physics letters
Journal: Applied physics letters


Journal of applied physics
Journal: Journal of applied physics


Scientific reports
Journal: Scientific reports


Physica status solidi (b)
Journal: Physica status solidi (b)


Solid state communications
Journal: Solid state communications


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of physics and chemistry of solids
Journal: Journal of physics and chemistry of solids


Physics of the solid state
Journal: Physics of the solid state


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Physica status solidi (b)
Journal: Physica status solidi (b)


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of physics and chemistry of solids
Journal: Journal of physics and chemistry of solids


Journal of applied physics
Journal: Journal of applied physics


Advanced materials
Journal: Advanced materials


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Physica status solidi (c)
Journal: Physica status solidi (c)


Nature communications
Journal: Nature communications


Inorganic chemistry
Journal: Inorganic chemistry


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Physica status solidi (b)
Journal: Physica status solidi (b)


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physica status solidi (b)
Journal: Physica status solidi (b)


Applied physics letters
Journal: Applied physics letters


High pressure research
Journal: High pressure research


Physical review b
Journal: Physical review b


Ceramics international
Journal: Ceramics international


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Applied physics letters
Journal: Applied physics letters


Physical review b
Journal: Physical review b


Acta crystallographica section b: structural science
Journal: Acta crystallographica section b: structural science


Physics of the solid state
Journal: Physics of the solid state


Nature communications
Journal: Nature communications


Journal of experimental and theoretical physics letters
Journal: Journal of experimental and theoretical physics letters


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Journal of applied physics
Journal: Journal of applied physics


Physica status solidi (b)
Journal: Physica status solidi (b)


Solid state communications
Journal: Solid state communications


Journal of experimental and theoretical physics letters
Journal: Journal of experimental and theoretical physics letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of applied physics
Journal: Journal of applied physics


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Dalton transactions
Journal: Dalton transactions


Journal of applied physics
Journal: Journal of applied physics


Physical review b
Journal: Physical review b


Journal of experimental and theoretical physics letters
Journal: Journal of experimental and theoretical physics letters


Scientific reports
Journal: Scientific reports


Journal of applied physics
Journal: Journal of applied physics


Chemistry of materials
Journal: Chemistry of materials


Applied physics letters
Journal: Applied physics letters


High pressure research
Journal: High pressure research


Journal of experimental and theoretical physics letters
Journal: Journal of experimental and theoretical physics letters


Jetp letters
Journal: Jetp letters


Physical review b
Journal: Physical review b


Applied physics letters
Journal: Applied physics letters


Physica status solidi (b)
Journal: Physica status solidi (b)


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Crystengcomm
Journal: Crystengcomm


Materials research express
Journal: Materials research express


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Jetp letters
Journal: Jetp letters


The european physical journal-applied physics 27 (1-3)
Journal: The european physical journal-applied physics


Physica e: low-dimensional systems and nanostructures
Journal: Physica e: low-dimensional systems and nanostructures


Inorganic chemistry
Journal: Inorganic chemistry


Journal of experimental and theoretical physics letters
Journal: Journal of experimental and theoretical physics letters


Physica status solidi (b)
Journal: Physica status solidi (b)


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Superconductor science and technology
Journal: Superconductor science and technology


Phys chem minerals
Journal: Phys chem minerals


American mineralogist
Journal: American mineralogist


Acs earth and space chemistry
Journal: Acs earth and space chemistry


The european physical journal plus
Journal: The european physical journal plus


Physical review b
Journal: Physical review b


High pressure research
Journal: High pressure research


High pressure research
Journal: High pressure research


Physica b: condensed matter
Journal: Physica b: condensed matter


Physica status solidi (b)
Journal: Physica status solidi (b)


Applied physics letters
Journal: Applied physics letters


American mineralogist
Journal: American mineralogist


Semiconductors
Journal: Semiconductors


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physica status solidi (b)
Journal: Physica status solidi (b)


Journal of electronic materials
Journal: Journal of electronic materials


Physica status solidi (b)
Journal: Physica status solidi (b)


Physica status solidi (b)
Journal: Physica status solidi (b)


International journal of high pressure research 17 (3-6)
Journal: International journal of high pressure research


Physics of the solid state
Journal: Physics of the solid state


Physica status solidi (b)
Journal: Physica status solidi (b)


Micromachining and microfabrication process technology xviii
Journal: Micromachining and microfabrication process technology xviii


Physics of the solid state
Journal: Physics of the solid state


Physica status solidi (b)
Journal: Physica status solidi (b)


Technical physics letters
Journal: Technical physics letters


Advanced science
Journal: Advanced science


Journal of the american chemical society
Journal: Journal of the american chemical society


Inorganic chemistry
Journal: Inorganic chemistry


Applied physics letters
Journal: Applied physics letters


Acta physica polonica a
Journal: Acta physica polonica a


Jetp letters
Journal: Jetp letters


Journal of the physical society of japan 76 (suppl. a)
Journal: Journal of the physical society of japan


Pis' ma v zhurnal ehksperimental'noj i teoreticheskoj fiziki
Journal: Pis' ma v zhurnal ehksperimental'noj i teoreticheskoj fiziki


Physics of the solid state
Journal: Physics of the solid state


Journal of applied physics
Journal: Journal of applied physics


American mineralogist: journal of earth and planetary materials
Journal: American mineralogist: journal of earth and planetary materials


Physics of the solid state
Journal: Physics of the solid state


Journal of low temperature physics
Journal: Journal of low temperature physics


Micromachining and microfabrication process technology ix
Journal: Micromachining and microfabrication process technology ix


Micromachining and microfabrication process technology viii
Journal: Micromachining and microfabrication process technology viii


Process and equipment control in microelectronic manufacturing ii
Journal: Process and equipment control in microelectronic manufacturing ii


Chemistry of materials
Journal: Chemistry of materials


Inorganic chemistry
Journal: Inorganic chemistry


Inorganic chemistry
Journal: Inorganic chemistry


Chemical research in chinese universities
Journal: Chemical research in chinese universities


Advanced materials
Journal: Advanced materials


Journal of thermoelectricity
Journal: Journal of thermoelectricity


Journal of physics and chemistry of solids
Journal: Journal of physics and chemistry of solids


Physics of the solid state
Journal: Physics of the solid state


Physical review b
Journal: Physical review b


Dalton transactions
Journal: Dalton transactions


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Angewandte chemie
Journal: Angewandte chemie


Scientific reports
Journal: Scientific reports


Fizika i tekhnika poluprovodnikov
Journal: Fizika i tekhnika poluprovodnikov


American mineralogist
Journal: American mineralogist


Joint airapt-25th &ehprg-53rd
Journal: Joint airapt-


Joint airapt-25th &ehprg-53rd
Journal: Joint airapt-


Joint airapt-25th &ehprg-53rd
Journal: Joint airapt-


Angewandte chemie
Journal: Angewandte chemie


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Journal of physics and chemistry of solids
Journal: Journal of physics and chemistry of solids


Acta crystallographica a-foundation and advances 67
Journal: Acta crystallographica a-foundation and advances


Acta crystallographica a-foundation and advances 67
Journal: Acta crystallographica a-foundation and advances


Physical review b condensed matter and materials physics
Journal: Physical review b condensed matter and materials physics


Phys. stat. sol.(b)
Journal: Phys. stat. sol.(b)


Journal of the physical society of japan 76 (suppl. a)
Journal: Journal of the physical society of japan


Fizika tverdogo tela
Journal: Fizika tverdogo tela


Verhandlungen der deutschen physikalischen gesellschaft
Journal: Verhandlungen der deutschen physikalischen gesellschaft


Fizika tverdogo tela
Journal: Fizika tverdogo tela


Fizika tverdogo tela
Journal: Fizika tverdogo tela


Pis' ma v zhurnal tekhnicheskoj fiziki
Journal: Pis' ma v zhurnal tekhnicheskoj fiziki


Smart sensors
Journal: Smart sensors


Thermosense xxv
Journal: Thermosense xxv


Nature communications
Journal: Nature communications


Inorganic chemistry
Journal: Inorganic chemistry


Scientific reports
Journal: Scientific reports


Joule
Journal: Joule


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Energy &environmental science
Journal: Energy &environmental science


Acs energy letters
Journal: Acs energy letters


Nanoscale
Journal: Nanoscale


Nano letters
Journal: Nano letters


Acs energy letters
Journal: Acs energy letters


Advanced functional materials
Journal: Advanced functional materials


Combustion and flame
Journal: Combustion and flame


Chemical communications
Journal: Chemical communications


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Environmental science &technology
Journal: Environmental science &technology


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nanoscale
Journal: Nanoscale


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemical physics letters 405 (1-3)
Journal: Chemical physics letters


Advanced functional materials
Journal: Advanced functional materials


Acs energy letters
Journal: Acs energy letters


Advanced materials
Journal: Advanced materials


Chemistry–a european journal
Journal: Chemistry–a european journal


Sustainable energy &fuels
Journal: Sustainable energy &fuels


Acs energy letters
Journal: Acs energy letters


Chemistry of materials
Journal: Chemistry of materials


Solar energy
Journal: Solar energy


Acs energy letters
Journal: Acs energy letters


Combustion and flame
Journal: Combustion and flame


Scientific reports
Journal: Scientific reports


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced functional materials
Journal: Advanced functional materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Rapid communications in mass spectrometry: an international journal devoted …
Journal: Rapid communications in mass spectrometry: an international journal devoted …


Advanced functional materials
Journal: Advanced functional materials


Optics express
Journal: Optics express


Advanced materials
Journal: Advanced materials


Acs photonics
Journal: Acs photonics


International journal of mass spectrometry
Journal: International journal of mass spectrometry


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Ieee sensors journal
Journal: Ieee sensors journal


Chemistry of materials
Journal: Chemistry of materials


Journal of applied physics
Journal: Journal of applied physics


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Inorganic chemistry
Journal: Inorganic chemistry


Chemsuschem
Journal: Chemsuschem


Advanced energy materials
Journal: Advanced energy materials


Advanced functional materials
Journal: Advanced functional materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Apl materials
Journal: Apl materials


Chemistry of materials
Journal: Chemistry of materials


Optics express
Journal: Optics express


Rsc advances
Journal: Rsc advances


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Acs applied electronic materials
Journal: Acs applied electronic materials


Solar energy
Journal: Solar energy


Journal of nanomaterials
Journal: Journal of nanomaterials


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Journal of optics a: pure and applied optics
Journal: Journal of optics a: pure and applied optics


Synthetic metals
Journal: Synthetic metals


Journal of nanoparticle research
Journal: Journal of nanoparticle research


Scripta materialia
Journal: Scripta materialia


Scientific reports
Journal: Scientific reports


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Optics and lasers in engineering
Journal: Optics and lasers in engineering


Applied physics b
Journal: Applied physics b


Energy technology
Journal: Energy technology


Thin solid films
Journal: Thin solid films


Advanced functional materials
Journal: Advanced functional materials


Materials research express
Journal: Materials research express


Physica status solidi (a)
Journal: Physica status solidi (a)


Carbon (new york
Journal: Carbon (new york


Journal of molecular spectroscopy
Journal: Journal of molecular spectroscopy


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs energy letters
Journal: Acs energy letters


Semiconductor science and technology
Journal: Semiconductor science and technology


Acs photonics
Journal: Acs photonics


Chemical communications
Journal: Chemical communications


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Molecules
Journal: Molecules


Solar rrl
Journal: Solar rrl


Coatings
Journal: Coatings


Acs applied energy materials
Journal: Acs applied energy materials


Physica status solidi (a)
Journal: Physica status solidi (a)


Physics procedia
Journal: Physics procedia


Advanced materials
Journal: Advanced materials


Physica status solidi (a)
Journal: Physica status solidi (a)


Solar rrl
Journal: Solar rrl


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced electronic materials
Journal: Advanced electronic materials


Chempluschem
Journal: Chempluschem


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Carbon
Journal: Carbon


Energy procedia
Journal: Energy procedia


Physica status solidi (a)
Journal: Physica status solidi (a)


Spectrochimica acta part a: molecular and biomolecular spectroscopy 58 (11 …
Journal: Spectrochimica acta part a: molecular and biomolecular spectroscopy


Journal of optics a: pure and applied optics
Journal: Journal of optics a: pure and applied optics


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs applied energy materials
Journal: Acs applied energy materials


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Chemical physics letters
Journal: Chemical physics letters


Polymer composites
Journal: Polymer composites


Superconductor science and technology
Journal: Superconductor science and technology


Finanza locale
Journal: Finanza locale


Journal of photonics for energy
Journal: Journal of photonics for energy


Sustainable energy &fuels
Journal: Sustainable energy &fuels


Chemsuschem
Journal: Chemsuschem


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nanotechnology
Journal: Nanotechnology


Physica status solidi (c)
Journal: Physica status solidi (c)


Applied physics b
Journal: Applied physics b


Report rds/par2013/
Journal: Report rds/par


Physics procedia
Journal: Physics procedia


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Optical materials
Journal: Optical materials


Physica status solidi (a)
Journal: Physica status solidi (a)


Physics procedia
Journal: Physics procedia


Chem. eng. trans
Journal: Chem. eng. trans


Chemical engineering transactions
Journal: Chemical engineering transactions


Acs applied energy materials
Journal: Acs applied energy materials


Solar rrl
Journal: Solar rrl


Chemsuschem
Journal: Chemsuschem


Report rds/par2014/
Journal: Report rds/par


Organic photonics v
Journal: Organic photonics v


Chem. eng. trans
Journal: Chem. eng. trans


Infomat
Journal: Infomat


Infomat
Journal: Infomat


Advanced electronic materials
Journal: Advanced electronic materials


Cleo: science and innovations
Journal: Cleo: science and innovations


Advanced functional materials
Journal: Advanced functional materials


Chemsuschem
Journal: Chemsuschem


Europhysics news
Journal: Europhysics news


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Scientific reports
Journal: Scientific reports


Journal materials science
Journal: Journal materials science


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Physica status solidi. a
Journal: Physica status solidi. a


Physica status solidi. a
Journal: Physica status solidi. a


Energy procedia
Journal: Energy procedia


Sensor letters
Journal: Sensor letters


Advanced materials
Journal: Advanced materials


Applied physics b
Journal: Applied physics b


Chemical engineering
Journal: Chemical engineering


Chemical engineering
Journal: Chemical engineering


The journal of physical chemistry b
Journal: The journal of physical chemistry b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Carbon
Journal: Carbon


Applied surface science
Journal: Applied surface science


Plant cell reports
Journal: Plant cell reports


Biosensors and bioelectronics
Journal: Biosensors and bioelectronics


International journal of hydrogen energy

Physica status solidi c
Journal: Physica status solidi c


Physica status solidi c
Journal: Physica status solidi c


Physica status solidi c
Journal: Physica status solidi c


Physical review b
Journal: Physical review b


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Physica status solidi a (applied research)
Journal: Physica status solidi a (applied research)


Applied physics letters
Journal: Applied physics letters


Journal of applied physics
Journal: Journal of applied physics


Physical review b
Journal: Physical review b


Applied physics letters
Journal: Applied physics letters


Physica status solidi-b-basic research
Journal: Physica status solidi-b-basic research


Journal of catalysis
Journal: Journal of catalysis


Inorganic chemistry
Journal: Inorganic chemistry


Surface and coatings technology
Journal: Surface and coatings technology


Renewable energy
Journal: Renewable energy


Physical review b
Journal: Physical review b


Acta materialia
Journal: Acta materialia


Plasma processes and polymers
Journal: Plasma processes and polymers


Acta materialia
Journal: Acta materialia


Solid state sciences
Journal: Solid state sciences


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review b
Journal: Physical review b


Spin
Journal: Spin


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Surface and coatings technology
Journal: Surface and coatings technology


Acta materialia
Journal: Acta materialia


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Thin solid films
Journal: Thin solid films


Materials
Journal: Materials


Vacuum
Journal: Vacuum


Solid state sciences
Journal: Solid state sciences


Apl materials
Journal: Apl materials


Solid state sciences
Journal: Solid state sciences


Surface and coatings technology
Journal: Surface and coatings technology


Applied physics letters
Journal: Applied physics letters


Chemistry of materials
Journal: Chemistry of materials


Acta materialia
Journal: Acta materialia


Physical review b
Journal: Physical review b


Journal of electronic materials
Journal: Journal of electronic materials


Langmuir
Journal: Langmuir


Nano energy
Journal: Nano energy


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Thermochimica acta 457 (1-2)
Journal: Thermochimica acta


Acta materialia
Journal: Acta materialia


Solid state sciences
Journal: Solid state sciences


Apl materials
Journal: Apl materials


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Faraday discusions
Journal: Faraday discusions


Journal of electronic materials
Journal: Journal of electronic materials


Advanced functional materials
Journal: Advanced functional materials


Inorganic chemistry
Journal: Inorganic chemistry


Physical review letters
Journal: Physical review letters


Materials chemistry and physics
Journal: Materials chemistry and physics


Coatings
Journal: Coatings


Scientific reports
Journal: Scientific reports


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Aerosol science and technology
Journal: Aerosol science and technology


Applied physics letters
Journal: Applied physics letters


Solid state sciences
Journal: Solid state sciences


Cellulose
Journal: Cellulose


Solid state communications
Journal: Solid state communications


Journal of materials research
Journal: Journal of materials research


Physica status solidi (rrl)–rapid research letters
Journal: Physica status solidi (rrl)–rapid research letters


Journal of electronic materials
Journal: Journal of electronic materials


Applied physics letters
Journal: Applied physics letters


Aip advances
Journal: Aip advances


Inorganic chemistry
Journal: Inorganic chemistry


Journal of materials chemistry
Journal: Journal of materials chemistry


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Acta materialia
Journal: Acta materialia


Solid-solid phase transformations in inorganic material
Journal: Solid-solid phase transformations in inorganic material


Journal of nuclear materials
Journal: Journal of nuclear materials


Rare metals
Journal: Rare metals


Nano letters
Journal: Nano letters


Applied physics letters
Journal: Applied physics letters


Nanotechnology
Journal: Nanotechnology


Journal of applied physics
Journal: Journal of applied physics


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Physical review b
Journal: Physical review b


Semiconductor science and technology
Journal: Semiconductor science and technology


Journal of materials research
Journal: Journal of materials research


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Crystal research and technology
Journal: Crystal research and technology


Journal of the korean ceramic society
Journal: Journal of the korean ceramic society


Journal of applied physics
Journal: Journal of applied physics


Nanotechnology
Journal: Nanotechnology


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Electrochimica acta
Journal: Electrochimica acta


Journal of applied physics
Journal: Journal of applied physics


Entropy
Journal: Entropy


Chimia
Journal: Chimia


Physica status solidi (a)
Journal: Physica status solidi (a)


Coatings
Journal: Coatings


Zeitschrift für anorganische und allgemeine chemie
Journal: Zeitschrift für anorganische und allgemeine chemie


Journal of crystal growth
Journal: Journal of crystal growth


Crystal growth &design
Journal: Crystal growth &design


Polymer
Journal: Polymer


Applied physics letters
Journal: Applied physics letters


Materials
Journal: Materials


Angewandte chemie
Journal: Angewandte chemie


Science and technology of advanced materials
Journal: Science and technology of advanced materials


Rsc adv.
Journal: Rsc adv.


Nanotechnology
Journal: Nanotechnology


Journal of alloys and compounds 509 (supplement 1)
Journal: Journal of alloys and compounds


Apl materials
Journal: Apl materials


Thin solid films
Journal: Thin solid films


Phys. rev. b
Journal: Phys. rev. b


Physica status solidi@rrl doi: 10.1002/pssr.
Journal: Physica status solidi@rrl doi:


Mtz-motortechnische zeitschrift
Journal: Mtz-motortechnische zeitschrift


Book "advances in electronic ceramics"
Journal: Book "advances in electronic ceramics"


Superficies y vacío
Journal: Superficies y vacío


Advanced electronic materials
Journal: Advanced electronic materials


Applied physics letters
Journal: Applied physics letters


Int. j. of advanced applied physics research
Journal: Int. j. of advanced applied physics research


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Thin solid films
Journal: Thin solid films


Mtz worldwide
Journal: Mtz worldwide


Current applied physics
Journal: Current applied physics


Anales de la asociacion quimica argentina
Journal: Anales de la asociacion quimica argentina


Nanotechnology
Journal: Nanotechnology


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Frontiers in nanotechnology
Journal: Frontiers in nanotechnology


Matéria (rio de janeiro)
Journal: Matéria (rio de janeiro)


Matéria (rio de janeiro)
Journal: Matéria (rio de janeiro)


Applied physics letters
Journal: Applied physics letters


Research@ ua
Journal: Research@ ua


Catalysis today (print)
Journal: Catalysis today (print)


Journal of physics. d
Journal: Journal of physics. d


Thermoelektrik
Journal: Thermoelektrik


Zeitschrift für anorganische und allgemeine chemie
Journal: Zeitschrift für anorganische und allgemeine chemie


Journal of applied physics
Journal: Journal of applied physics


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Inorganic chemistry
Journal: Inorganic chemistry


Solid-state chemistry of inorganic materials iv: volume 755
Journal: Solid-state chemistry of inorganic materials iv: volume


Journal of crystal growth 254 (3-4)
Journal: Journal of crystal growth


Solid state sciences
Journal: Solid state sciences


Solid state sciences
Journal: Solid state sciences


Revista mexicana de física
Journal: Revista mexicana de física


Physical review letters
Journal: Physical review letters


Physical review b
Journal: Physical review b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nature communications
Journal: Nature communications


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review b
Journal: Physical review b


Nano letters
Journal: Nano letters


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Acs nano
Journal: Acs nano


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review letters
Journal: Physical review letters


Applied physics letters
Journal: Applied physics letters


Applied physics reviews
Journal: Applied physics reviews


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review b
Journal: Physical review b


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Applied physics letters
Journal: Applied physics letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of applied physics
Journal: Journal of applied physics


Physical review b
Journal: Physical review b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Applied physics reviews
Journal: Applied physics reviews


Journal of applied physics
Journal: Journal of applied physics


Physical review b
Journal: Physical review b


Semiconductor science and technology
Journal: Semiconductor science and technology


Journal of applied physics
Journal: Journal of applied physics


Journal of applied physics
Journal: Journal of applied physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of applied physics
Journal: Journal of applied physics


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Nature communications
Journal: Nature communications


Physical review materials
Journal: Physical review materials


Nanoscale
Journal: Nanoscale


Wiley interdisciplinary reviews: computational molecular science
Journal: Wiley interdisciplinary reviews: computational molecular science


Nanoscale
Journal: Nanoscale


Physical review b
Journal: Physical review b


Rev.: comput. mol. sci
Journal: Rev.: comput. mol. sci


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Scientific reports
Journal: Scientific reports


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Physical review b
Journal: Physical review b


Medical image analysis
Journal: Medical image analysis


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Nano letters
Journal: Nano letters


Nanotechnology
Journal: Nanotechnology


Applied surface science
Journal: Applied surface science


Acs nano
Journal: Acs nano


Physical review b
Journal: Physical review b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nanotechnology
Journal: Nanotechnology


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Geothermics
Journal: Geothermics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Rsc advances
Journal: Rsc advances


Physical review b
Journal: Physical review b


Journal of materials chemistry c
Journal: Journal of materials chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review b
Journal: Physical review b


Metals
Journal: Metals


Nanoscale
Journal: Nanoscale


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Materials research express
Journal: Materials research express


Chemphyschem
Journal: Chemphyschem


Applied surface science
Journal: Applied surface science


The journal of chemical physics
Journal: The journal of chemical physics


The journal of chemical physics
Journal: The journal of chemical physics


Apl materials
Journal: Apl materials


Computational condensed matter
Journal: Computational condensed matter


Applied surface science
Journal: Applied surface science


Applied surface science
Journal: Applied surface science


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Journal of applied physics
Journal: Journal of applied physics


Journal of materials chemistry c
Journal: Journal of materials chemistry c


The european physical journal-applied physics
Journal: The european physical journal-applied physics


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Materials chemistry and physics
Journal: Materials chemistry and physics


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Acs applied nano materials
Journal: Acs applied nano materials


Nanotechnology
Journal: Nanotechnology


Applied surface science
Journal: Applied surface science


Physical review b
Journal: Physical review b


Applied surface science
Journal: Applied surface science


Nanotechnology
Journal: Nanotechnology


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Physical review b
Journal: Physical review b


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Journal of semiconductors
Journal: Journal of semiconductors


Langmuir
Journal: Langmuir


Nanoscale
Journal: Nanoscale


Metals
Journal: Metals


Wiley interdisciplinary reviews: computational molecular science
Journal: Wiley interdisciplinary reviews: computational molecular science


Journal of non-crystalline solids
Journal: Journal of non-crystalline solids


Materials science and engineering: a
Journal: Materials science and engineering: a


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Inorganic chemistry frontiers
Journal: Inorganic chemistry frontiers


Beilstein journal of nanotechnology
Journal: Beilstein journal of nanotechnology


Procedia structural integrity
Journal: Procedia structural integrity


Beilstein journal of nanotechnology
Journal: Beilstein journal of nanotechnology


Journal of molecular structure
Journal: Journal of molecular structure


Nanotechnology
Journal: Nanotechnology


Manufacturing engineering
Journal: Manufacturing engineering


Journal of applied physics
Journal: Journal of applied physics


Journal of applied physics
Journal: Journal of applied physics


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Applied surface science
Journal: Applied surface science


Chemphyschem
Journal: Chemphyschem


Rsc advances
Journal: Rsc advances


Metals
Journal: Metals


Applied surface science
Journal: Applied surface science


Journal of materials research
Journal: Journal of materials research


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Beilstein journal of nanotechnology
Journal: Beilstein journal of nanotechnology


Computational materials science
Journal: Computational materials science


Geothermics
Journal: Geothermics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Sae international journal of materials and manufacturing
Journal: Sae international journal of materials and manufacturing


Applied physics letters
Journal: Applied physics letters


Afyon kocatepe üniversitesi fen ve mühendislik bilimleri dergisi
Journal: Afyon kocatepe üniversitesi fen ve mühendislik bilimleri dergisi


Physical review b
Journal: Physical review b


American journal of physics
Journal: American journal of physics


Physical review b
Journal: Physical review b


Solid-state electronics
Journal: Solid-state electronics


Ieee transactions on magnetics
Journal: Ieee transactions on magnetics


Journal of electroceramics
Journal: Journal of electroceramics


Solid state sciences
Journal: Solid state sciences


Aip advances
Journal: Aip advances


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Applied physics letters
Journal: Applied physics letters


Mater res soc symp proc
Journal: Mater res soc symp proc


Journal of applied physics
Journal: Journal of applied physics


Advances in science and technology
Journal: Advances in science and technology


Nato science for peace and security series b: physics and biophysics
Journal: Nato science for peace and security series b: physics and biophysics


Journal of applied physics
Journal: Journal of applied physics


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Journal of magnetism and magnetic materials 156 (1-3)
Journal: Journal of magnetism and magnetic materials


Journal of applied physics
Journal: Journal of applied physics


Journal of magnetism and magnetic materials 156 (1-3)
Journal: Journal of magnetism and magnetic materials


Mrs advances
Journal: Mrs advances


Mrs advances
Journal: Mrs advances


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


The journal of supercomputing
Journal: The journal of supercomputing


Physical review b
Journal: Physical review b


Journal of magnetism and magnetic materials 156 (1-3)
Journal: Journal of magnetism and magnetic materials


Review of scientific instruments
Journal: Review of scientific instruments


Ieee transactions on magnetics
Journal: Ieee transactions on magnetics


Aip advances
Journal: Aip advances


Advances and applications in electroceramics
Journal: Advances and applications in electroceramics


Review of scientific instruments

Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


Angewandte chemie
Journal: Angewandte chemie


Nature energy
Journal: Nature energy


Nano research
Journal: Nano research


Nature photonics
Journal: Nature photonics


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs nano
Journal: Acs nano


Applied physics reviews
Journal: Applied physics reviews


Energy &environmental science
Journal: Energy &environmental science


Advanced energy materials
Journal: Advanced energy materials


Energy &environmental science
Journal: Energy &environmental science


Acs nano
Journal: Acs nano


American chemical society
Journal: American chemical society


Journal of physical chemistry b
Journal: Journal of physical chemistry b


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Energy &environmental science
Journal: Energy &environmental science


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Nano letters
Journal: Nano letters


Journal of physical chemistry b
Journal: Journal of physical chemistry b


Nature communications
Journal: Nature communications


Acs nano
Journal: Acs nano


Nature communications
Journal: Nature communications


Nano letters
Journal: Nano letters


Applied physics letters
Journal: Applied physics letters


Materials letters
Journal: Materials letters


Journal of physical chemistry b
Journal: Journal of physical chemistry b


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs nano
Journal: Acs nano


Acs catalysis
Journal: Acs catalysis


Nature chemistry
Journal: Nature chemistry


Acs nano
Journal: Acs nano


Acs energy letters
Journal: Acs energy letters


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Acs nano
Journal: Acs nano


Chemical reviews
Journal: Chemical reviews


Acs energy letters
Journal: Acs energy letters


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Nano letters
Journal: Nano letters


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


Nature communications
Journal: Nature communications


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Energy &environmental science
Journal: Energy &environmental science


Journal of physical chemistry b
Journal: Journal of physical chemistry b


Nanoscale
Journal: Nanoscale


Nano research
Journal: Nano research


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Journal of physical chemistry c
Journal: Journal of physical chemistry c


Nanoscale horizons
Journal: Nanoscale horizons


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review b
Journal: Physical review b


Acs nano
Journal: Acs nano


Journal of photochemistry and photobiology a: chemistry 142 (2-3)
Journal: Journal of photochemistry and photobiology a: chemistry


Acs nano
Journal: Acs nano


Physical review b
Journal: Physical review b


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs nano
Journal: Acs nano


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Energy &environmental science
Journal: Energy &environmental science


Acs nano
Journal: Acs nano


Nano letters
Journal: Nano letters


Journal of alloys and compounds 454 (1-2)
Journal: Journal of alloys and compounds


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs energy letters
Journal: Acs energy letters


Advanced electronic materials
Journal: Advanced electronic materials


Acs energy letters
Journal: Acs energy letters


Science advances
Journal: Science advances


Nano energy
Journal: Nano energy


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Journal of the american chemical society
Journal: Journal of the american chemical society


Materials horizons
Journal: Materials horizons


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Review of scientific instruments
Journal: Review of scientific instruments


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Energy &environmental science
Journal: Energy &environmental science


Nanoscale
Journal: Nanoscale


Acs nano
Journal: Acs nano


Journal of vacuum science &technology b
Journal: Journal of vacuum science &technology b


Advanced materials
Journal: Advanced materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nature photonics
Journal: Nature photonics


Dalton transactions
Journal: Dalton transactions


Applied physics letters
Journal: Applied physics letters


Advanced functional materials
Journal: Advanced functional materials


Journal of energy chemistry
Journal: Journal of energy chemistry


Acs nano
Journal: Acs nano


Acs energy letters
Journal: Acs energy letters


Advanced electronic materials
Journal: Advanced electronic materials


Journal of applied physics
Journal: Journal of applied physics


Nanoscale
Journal: Nanoscale


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nanoscale
Journal: Nanoscale


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Nanoscale
Journal: Nanoscale


Energy &environmental science
Journal: Energy &environmental science


Acs applied electronic materials
Journal: Acs applied electronic materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced functional materials
Journal: Advanced functional materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Acs photonics
Journal: Acs photonics


Nanoscale
Journal: Nanoscale


Acs nano
Journal: Acs nano


Advanced electronic materials
Journal: Advanced electronic materials


Nano letters
Journal: Nano letters


Applied physics letters
Journal: Applied physics letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of applied physics
Journal: Journal of applied physics


Materials horizons
Journal: Materials horizons


Journal of materials research
Journal: Journal of materials research


Acs applied polymer materials
Journal: Acs applied polymer materials


Acs energy letters
Journal: Acs energy letters


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


Acs applied nano materials
Journal: Acs applied nano materials


Nanoscale
Journal: Nanoscale


Physical chemistry of interfaces and nanomaterials iv
Journal: Physical chemistry of interfaces and nanomaterials iv


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of crystal growth
Journal: Journal of crystal growth


Thin solid films
Journal: Thin solid films


Nature communications
Journal: Nature communications


Science
Journal: Science


Acs energy letters
Journal: Acs energy letters


Nature communications
Journal: Nature communications


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nature energy
Journal: Nature energy


Accounts of chemical research
Journal: Accounts of chemical research


Nature energy
Journal: Nature energy


Acs energy letters
Journal: Acs energy letters


Science
Journal: Science


Nature nanotechnology
Journal: Nature nanotechnology


Chemical communications
Journal: Chemical communications


Advanced optical materials
Journal: Advanced optical materials


Science
Journal: Science


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs energy letters
Journal: Acs energy letters


Nature energy
Journal: Nature energy


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nature reviews materials
Journal: Nature reviews materials


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Acs photonics
Journal: Acs photonics


Advanced materials
Journal: Advanced materials


Nature photonics
Journal: Nature photonics


Nature communications
Journal: Nature communications


Chemistry of materials
Journal: Chemistry of materials


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Optics express
Journal: Optics express


Acs energy letters
Journal: Acs energy letters


Chemistry of materials
Journal: Chemistry of materials


Nature photonics
Journal: Nature photonics


Advanced science
Journal: Advanced science


Physical review letters
Journal: Physical review letters


Nature communications
Journal: Nature communications


Journal of energy chemistry
Journal: Journal of energy chemistry


Advanced materials
Journal: Advanced materials


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs energy letters
Journal: Acs energy letters


Chemistry of materials
Journal: Chemistry of materials


Nature materials
Journal: Nature materials


Acs energy letters
Journal: Acs energy letters


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs materials letters
Journal: Acs materials letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Acs materials letters
Journal: Acs materials letters


Advanced materials
Journal: Advanced materials


Journal of vacuum science &technology b
Journal: Journal of vacuum science &technology b


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Nature communications
Journal: Nature communications


Nature communications
Journal: Nature communications


Carbon
Journal: Carbon


Nature energy
Journal: Nature energy


Acs energy letters
Journal: Acs energy letters


Joule
Journal: Joule


Advanced materials
Journal: Advanced materials


Advanced optical materials
Journal: Advanced optical materials


Advanced optical materials
Journal: Advanced optical materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs energy letters
Journal: Acs energy letters


Acs materials letters
Journal: Acs materials letters


Joule
Journal: Joule


Advanced functional materials
Journal: Advanced functional materials


Advanced materials
Journal: Advanced materials


Chemphyschem
Journal: Chemphyschem


Acs nano
Journal: Acs nano


Carbon
Journal: Carbon


Chemistry of materials
Journal: Chemistry of materials


Advanced optical materials
Journal: Advanced optical materials


Advanced science
Journal: Advanced science


Acs catalysis
Journal: Acs catalysis


Advanced science
Journal: Advanced science


Inorganic materials
Journal: Inorganic materials


Acs materials letters
Journal: Acs materials letters


Chemistry of materials
Journal: Chemistry of materials


Materials today
Journal: Materials today


Journal of materials research
Journal: Journal of materials research


Chemistry of materials
Journal: Chemistry of materials


Acs nano
Journal: Acs nano


Journal of materials research
Journal: Journal of materials research


Communications materials
Journal: Communications materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nature electronics
Journal: Nature electronics


Applied physics letters
Journal: Applied physics letters


Advanced materials
Journal: Advanced materials


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Acs materials letters
Journal: Acs materials letters


Chirality
Journal: Chirality


Advanced optical materials
Journal: Advanced optical materials


Inorganic materials
Journal: Inorganic materials


Advanced optical materials
Journal: Advanced optical materials


Crystengcomm
Journal: Crystengcomm


Mater. energy
Journal: Mater. energy


Acs materials au
Journal: Acs materials au


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Chemistry of materials
Journal: Chemistry of materials


Journal of semiconductors
Journal: Journal of semiconductors


Advanced materials
Journal: Advanced materials


Chem
Journal: Chem


Journal of chemical education
Journal: Journal of chemical education


Science bulletin
Journal: Science bulletin


Advanced electronic materials
Journal: Advanced electronic materials


Solar rrl
Journal: Solar rrl


Acs central science
Journal: Acs central science


Nano letters
Journal: Nano letters


Nature communications
Journal: Nature communications


Nature photonics
Journal: Nature photonics


Nature communications
Journal: Nature communications


Nature communications
Journal: Nature communications


日本物理学会講演概要集 72
Journal: 日本物理学会講演概要集


Foundations of crystallography 70
Journal: Foundations of crystallography


Nano letters
Journal: Nano letters


Nano letters
Journal: Nano letters


Science
Journal: Science


Nature communications
Journal: Nature communications


Acs energy letters
Journal: Acs energy letters


Nature
Journal: Nature


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs nano
Journal: Acs nano


Acs nano
Journal: Acs nano


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature
Journal: Nature


Advanced materials
Journal: Advanced materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs nano
Journal: Acs nano


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs energy letters
Journal: Acs energy letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature materials
Journal: Nature materials


Nano letters
Journal: Nano letters


Nature materials
Journal: Nature materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs nano
Journal: Acs nano


Acs energy letters
Journal: Acs energy letters


Angewandte chemie
Journal: Angewandte chemie


Nature communications
Journal: Nature communications


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs nano
Journal: Acs nano


Nature
Journal: Nature


Nano letters
Journal: Nano letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Small
Journal: Small


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced science
Journal: Advanced science


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Chemistry of materials
Journal: Chemistry of materials


Acs nano
Journal: Acs nano


Langmuir
Journal: Langmuir


Chimia 71 (7-8)
Journal: Chimia


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Scientific reports
Journal: Scientific reports


Nature communications
Journal: Nature communications


Acs nano
Journal: Acs nano


Nano letters
Journal: Nano letters


Nano letters
Journal: Nano letters


Acs central science
Journal: Acs central science


Nature communications
Journal: Nature communications


Chimia
Journal: Chimia


Acs nano
Journal: Acs nano


Acs applied nano materials
Journal: Acs applied nano materials


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Nature communications
Journal: Nature communications


Nano letters
Journal: Nano letters


Acs photonics
Journal: Acs photonics


Scientific reports
Journal: Scientific reports


Acs nano
Journal: Acs nano


Frontiers in chemistry
Journal: Frontiers in chemistry


Theoretical and experimental chemistry
Journal: Theoretical and experimental chemistry


Nature communications
Journal: Nature communications


Nanoscale
Journal: Nanoscale


Acs energy letters
Journal: Acs energy letters


Advanced optical materials
Journal: Advanced optical materials


Acs photonics
Journal: Acs photonics


Acs applied energy materials
Journal: Acs applied energy materials


Nano letters
Journal: Nano letters


Applied physics letters
Journal: Applied physics letters


Acs applied nano materials
Journal: Acs applied nano materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Chemphyschem
Journal: Chemphyschem


Acs catalysis
Journal: Acs catalysis


Acs nano
Journal: Acs nano


Nano letters
Journal: Nano letters


Journal of applied physics
Journal: Journal of applied physics


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


Theoretical and experimental chemistry
Journal: Theoretical and experimental chemistry


Acs energy letters
Journal: Acs energy letters


Nanotechnology
Journal: Nanotechnology


Acs nano
Journal: Acs nano


Acs applied nano materials
Journal: Acs applied nano materials


Advanced energy materials
Journal: Advanced energy materials


Chemistry of materials
Journal: Chemistry of materials


Applied physics reviews
Journal: Applied physics reviews


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Acs nano
Journal: Acs nano


Acs photonics
Journal: Acs photonics


Journal of physics b: atomic

Matter
Journal: Matter


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Nanophotonics iv
Journal: Nanophotonics iv


Acs applied energy materials
Journal: Acs applied energy materials


Nanoscale
Journal: Nanoscale


Materials letters
Journal: Materials letters


Nato science for peace and security series b: physics and biophysics
Journal: Nato science for peace and security series b: physics and biophysics


Journal of lightwave technology
Journal: Journal of lightwave technology


Optica pura y aplicada
Journal: Optica pura y aplicada


Mètode science studies journal: annual review
Journal: Mètode science studies journal: annual review


Human gene therapy
Journal: Human gene therapy


Ix congreso nacional del color: alicante
Journal: Ix congreso nacional del color: alicante


Nano letters
Journal: Nano letters


Nanotechnology
Journal: Nanotechnology


Nanotechnology
Journal: Nanotechnology


Langmuir
Journal: Langmuir


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of materials chemistry
Journal: Journal of materials chemistry


Electrochimica acta
Journal: Electrochimica acta


Nanoscale
Journal: Nanoscale


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of nanomaterials
Journal: Journal of nanomaterials


Advanced materials interfaces
Journal: Advanced materials interfaces


New journal of chemistry
Journal: New journal of chemistry


New journal of chemistry
Journal: New journal of chemistry


Nanotechnology
Journal: Nanotechnology


Langmuir
Journal: Langmuir


Journal of materials chemistry
Journal: Journal of materials chemistry


Rsc advances
Journal: Rsc advances


Ieee sensors journal
Journal: Ieee sensors journal


Journal of materials chemistry
Journal: Journal of materials chemistry


Journal of lightwave technology
Journal: Journal of lightwave technology


Nanotechnology
Journal: Nanotechnology


Advanced optical materials
Journal: Advanced optical materials


Ieee photonics journal
Journal: Ieee photonics journal


Optics letters
Journal: Optics letters


Nanomaterials
Journal: Nanomaterials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nanophotonics
Journal: Nanophotonics


Rsc advances
Journal: Rsc advances


Nanomaterials
Journal: Nanomaterials


Applied surface science
Journal: Applied surface science


Journal of luminescence
Journal: Journal of luminescence


Acs omega
Journal: Acs omega


Nanoscale research letters
Journal: Nanoscale research letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Optics express
Journal: Optics express


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Acs applied polymer materials
Journal: Acs applied polymer materials


Liver transplantation
Journal: Liver transplantation


Nanotechnology
Journal: Nanotechnology


Physica status solidi (a)
Journal: Physica status solidi (a)


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Applied surface science
Journal: Applied surface science


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Photonics technology letters
Journal: Photonics technology letters


Polymer
Journal: Polymer


Semicond. phys. quantum electron. optoelectron
Journal: Semicond. phys. quantum electron. optoelectron


Advances in resist materials and processing technology xxx
Journal: Advances in resist materials and processing technology xxx


Nanomaterials
Journal: Nanomaterials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advances in resist materials and processing technology xxx
Journal: Advances in resist materials and processing technology xxx


J. phys. chem. c
Journal: J. phys. chem. c


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs applied nano materials
Journal: Acs applied nano materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Matter
Journal: Matter


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Nanophotonics iv
Journal: Nanophotonics iv


Acs applied energy materials
Journal: Acs applied energy materials


Nanoscale
Journal: Nanoscale


Materials letters
Journal: Materials letters


Nato science for peace and security series b: physics and biophysics
Journal: Nato science for peace and security series b: physics and biophysics


Journal of lightwave technology
Journal: Journal of lightwave technology


Optica pura y aplicada
Journal: Optica pura y aplicada


Mètode science studies journal: annual review
Journal: Mètode science studies journal: annual review


Human gene therapy
Journal: Human gene therapy


Ix congreso nacional del color: alicante
Journal: Ix congreso nacional del color: alicante


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of applied crystallography
Journal: Journal of applied crystallography


Applied thermal engineering
Journal: Applied thermal engineering


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Physical review b
Journal: Physical review b


Journal of applied crystallography
Journal: Journal of applied crystallography


Journal of molecular structure
Journal: Journal of molecular structure


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Solar energy
Journal: Solar energy


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Journal of molecular structure
Journal: Journal of molecular structure


Materials research bulletin
Journal: Materials research bulletin


Acta crystallographica section b: structural science
Journal: Acta crystallographica section b: structural science


Dalton transactions
Journal: Dalton transactions


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Journal of molecular structure
Journal: Journal of molecular structure


Journal of energy storage
Journal: Journal of energy storage


Journal of molecular structure
Journal: Journal of molecular structure


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of applied crystallography
Journal: Journal of applied crystallography


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Journal of molecular structure
Journal: Journal of molecular structure


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Physica status solidi (b)
Journal: Physica status solidi (b)


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Dalton transactions
Journal: Dalton transactions


Journal of molecular structure
Journal: Journal of molecular structure


Solar energy
Journal: Solar energy


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Metrologia
Journal: Metrologia


Dalton transactions
Journal: Dalton transactions


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Ferroelectrics
Journal: Ferroelectrics


Infrared physics &technology
Journal: Infrared physics &technology


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of molecular structure
Journal: Journal of molecular structure


Acta crystallographica section b: structural science
Journal: Acta crystallographica section b: structural science


Thermochimica acta
Journal: Thermochimica acta


Polyhedron
Journal: Polyhedron


Journal of molecular structure
Journal: Journal of molecular structure


Materials research bulletin
Journal: Materials research bulletin


Oriental journal of chemistry
Journal: Oriental journal of chemistry


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Journal of energy storage
Journal: Journal of energy storage


Journal of applied crystallography
Journal: Journal of applied crystallography


Journal de physique i
Journal: Journal de physique i


Solid state communications
Journal: Solid state communications


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Phase transitions: a multinational journal
Journal: Phase transitions: a multinational journal


Polyhedron
Journal: Polyhedron


Journal of molecular structure
Journal: Journal of molecular structure


Journal of thermal analysis
Journal: Journal of thermal analysis


Acta crystallographica section b: structural science
Journal: Acta crystallographica section b: structural science


Phase transitions: a multinational journal
Journal: Phase transitions: a multinational journal


Journal of nuclear materials
Journal: Journal of nuclear materials


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Journal of molecular structure
Journal: Journal of molecular structure


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Powder diffraction 34 (s1)
Journal: Powder diffraction


Journal of electronic materials
Journal: Journal of electronic materials


Physical review b
Journal: Physical review b


Open access library journal
Journal: Open access library journal


Acta crystallographica a-foundation and advances 63
Journal: Acta crystallographica a-foundation and advances


Dalton transactions
Journal: Dalton transactions


Crystals
Journal: Crystals


Acta crystallographica a-foundation and advances 65
Journal: Acta crystallographica a-foundation and advances


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Ferroelectrics
Journal: Ferroelectrics


Dalton transactions
Journal: Dalton transactions


Csedu
Journal: Csedu


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Journal of molecular structure
Journal: Journal of molecular structure


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Journal of molecular structure
Journal: Journal of molecular structure


Acta crystallographica a-foundation and advances 67
Journal: Acta crystallographica a-foundation and advances


Acta crystallographica a-foundation and advances 64
Journal: Acta crystallographica a-foundation and advances


Acta crystallographica a-foundation and advances 58
Journal: Acta crystallographica a-foundation and advances


Ferroelectrics
Journal: Ferroelectrics


Anales afa
Journal: Anales afa


Solid state communications
Journal: Solid state communications


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of applied crystallography
Journal: Journal of applied crystallography


Applied thermal engineering
Journal: Applied thermal engineering


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Physical review b
Journal: Physical review b


Journal of applied crystallography
Journal: Journal of applied crystallography


Journal of molecular structure
Journal: Journal of molecular structure


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Solar energy
Journal: Solar energy


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Journal of molecular structure
Journal: Journal of molecular structure


Materials research bulletin
Journal: Materials research bulletin


Acta crystallographica section b: structural science
Journal: Acta crystallographica section b: structural science


Dalton transactions
Journal: Dalton transactions


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Journal of molecular structure
Journal: Journal of molecular structure


Journal of energy storage
Journal: Journal of energy storage


Journal of molecular structure
Journal: Journal of molecular structure


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of applied crystallography
Journal: Journal of applied crystallography


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Journal of molecular structure
Journal: Journal of molecular structure


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Physica status solidi (b)
Journal: Physica status solidi (b)


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Dalton transactions
Journal: Dalton transactions


Journal of molecular structure
Journal: Journal of molecular structure


Solar energy
Journal: Solar energy


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Metrologia
Journal: Metrologia


Dalton transactions
Journal: Dalton transactions


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Ferroelectrics
Journal: Ferroelectrics


Infrared physics &technology
Journal: Infrared physics &technology


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of molecular structure
Journal: Journal of molecular structure


Acta crystallographica section b: structural science
Journal: Acta crystallographica section b: structural science


Thermochimica acta
Journal: Thermochimica acta


Polyhedron
Journal: Polyhedron


Journal of molecular structure
Journal: Journal of molecular structure


Materials research bulletin
Journal: Materials research bulletin


Oriental journal of chemistry
Journal: Oriental journal of chemistry


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Journal of energy storage
Journal: Journal of energy storage


Journal of applied crystallography
Journal: Journal of applied crystallography


Journal de physique i
Journal: Journal de physique i


Solid state communications
Journal: Solid state communications


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Phase transitions: a multinational journal
Journal: Phase transitions: a multinational journal


Polyhedron
Journal: Polyhedron


Journal of molecular structure
Journal: Journal of molecular structure


Journal of thermal analysis
Journal: Journal of thermal analysis


Acta crystallographica section b: structural science
Journal: Acta crystallographica section b: structural science


Phase transitions: a multinational journal
Journal: Phase transitions: a multinational journal


Journal of nuclear materials
Journal: Journal of nuclear materials


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Journal of molecular structure
Journal: Journal of molecular structure


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Powder diffraction 34 (s1)
Journal: Powder diffraction


Journal of electronic materials
Journal: Journal of electronic materials


Physical review b
Journal: Physical review b


Open access library journal
Journal: Open access library journal


Acta crystallographica a-foundation and advances 63
Journal: Acta crystallographica a-foundation and advances


Dalton transactions
Journal: Dalton transactions


Crystals
Journal: Crystals


Acta crystallographica a-foundation and advances 65
Journal: Acta crystallographica a-foundation and advances


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Ferroelectrics
Journal: Ferroelectrics


Dalton transactions
Journal: Dalton transactions


Csedu
Journal: Csedu


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Journal of molecular structure
Journal: Journal of molecular structure


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Journal of molecular structure
Journal: Journal of molecular structure


Acta crystallographica a-foundation and advances 67
Journal: Acta crystallographica a-foundation and advances


Acta crystallographica a-foundation and advances 64
Journal: Acta crystallographica a-foundation and advances


Acta crystallographica a-foundation and advances 58
Journal: Acta crystallographica a-foundation and advances


Ferroelectrics
Journal: Ferroelectrics


Anales afa
Journal: Anales afa


Solid state communications
Journal: Solid state communications


Nature communications
Journal: Nature communications


Physica e: low-dimensional systems and nanostructures
Journal: Physica e: low-dimensional systems and nanostructures


Advanced functional materials
Journal: Advanced functional materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Nature communications
Journal: Nature communications


Cell reports physical science
Journal: Cell reports physical science


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Acs energy letters
Journal: Acs energy letters


Nano energy
Journal: Nano energy


Advanced materials
Journal: Advanced materials


Applied physics letters
Journal: Applied physics letters


Advanced energy materials
Journal: Advanced energy materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Applied physics letters
Journal: Applied physics letters


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced functional materials
Journal: Advanced functional materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Nano energy
Journal: Nano energy


Advanced functional materials
Journal: Advanced functional materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nanotechnology
Journal: Nanotechnology


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Applied physics letters
Journal: Applied physics letters


Advanced science
Journal: Advanced science


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Solar rrl
Journal: Solar rrl


Rsc advances
Journal: Rsc advances


Nanotechnology
Journal: Nanotechnology


Journal of colloid and interface science
Journal: Journal of colloid and interface science


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Chemical engineering journal
Journal: Chemical engineering journal


Physical review letters
Journal: Physical review letters


Nanoscale
Journal: Nanoscale


Rsc advances
Journal: Rsc advances


Europhysics letters
Journal: Europhysics letters


Applied physics letters
Journal: Applied physics letters


Nano energy
Journal: Nano energy


Heliyon
Journal: Heliyon


Bioresource technology
Journal: Bioresource technology


Nanoscale
Journal: Nanoscale


Japanese journal of applied physics 53 (5s1)
Journal: Japanese journal of applied physics


Nanotechnology
Journal: Nanotechnology


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


Materials letters
Journal: Materials letters


Rsc advances
Journal: Rsc advances


Journal of applied physics
Journal: Journal of applied physics


Next generation technologies for solar energy conversion v

Mendeleev communications
Journal: Mendeleev communications


Russian journal of inorganic chemistry
Journal: Russian journal of inorganic chemistry


Russian journal of inorganic chemistry
Journal: Russian journal of inorganic chemistry


Crystals
Journal: Crystals


Mendeleev communications
Journal: Mendeleev communications


Chemistry of materials
Journal: Chemistry of materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Acs omega
Journal: Acs omega


Mendeleev communications
Journal: Mendeleev communications


Mendeleev communications
Journal: Mendeleev communications


Mendeleev communications
Journal: Mendeleev communications


Japanese journal of applied physics 61 (se)
Journal: Japanese journal of applied physics


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nanomaterials
Journal: Nanomaterials


International journal of molecular sciences
Journal: International journal of molecular sciences


Mendeleev communications
Journal: Mendeleev communications


Inorganic materials
Journal: Inorganic materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Chemistry of materials
Journal: Chemistry of materials


Nature nanotechnology
Journal: Nature nanotechnology


Chemistry of materials
Journal: Chemistry of materials


Materials horizons
Journal: Materials horizons


Chemistry of materials
Journal: Chemistry of materials


Acta crystallographica section e: crystallographic communications 73 (4 …
Journal: Acta crystallographica section e: crystallographic communications


Combustion science and technology
Journal: Combustion science and technology


Mendeleev communications
Journal: Mendeleev communications


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Applied nanoscience
Journal: Applied nanoscience


Chemistry of materials
Journal: Chemistry of materials


Doklady akademii nauk-rossijskaya akademiya nauk
Journal: Doklady akademii nauk-rossijskaya akademiya nauk


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Mendeleev communications
Journal: Mendeleev communications


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Mendeleev communications
Journal: Mendeleev communications


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Mendeleev communications
Journal: Mendeleev communications


Mendeleev communications
Journal: Mendeleev communications


Journal of energy chemistry
Journal: Journal of energy chemistry


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Glass physics &chemistry
Journal: Glass physics &chemistry


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Rsc advances
Journal: Rsc advances


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Mendeleev communications
Journal: Mendeleev communications


Molecules
Journal: Molecules


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Russian journal of inorganic chemistry
Journal: Russian journal of inorganic chemistry


Chemistry of materials
Journal: Chemistry of materials


Molecules
Journal: Molecules


Frontiers in chemistry
Journal: Frontiers in chemistry


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nanomaterials
Journal: Nanomaterials


Acta crystallographica section e: crystallographic communications 77 (7 …
Journal: Acta crystallographica section e: crystallographic communications


Frontiers in chemistry
Journal: Frontiers in chemistry


Acs materials letters
Journal: Acs materials letters


Molecules
Journal: Molecules


Journal of physical chemistry c
Journal: Journal of physical chemistry c


Mendeleev communications
Journal: Mendeleev communications


Mendeleev communications
Journal: Mendeleev communications


Nanosystems: physics
Journal: Nanosystems: physics


Journal of energy chemistry
Journal: Journal of energy chemistry


Mendeleev communications
Journal: Mendeleev communications


Russian journal of inorganic chemistry
Journal: Russian journal of inorganic chemistry


Russian journal of inorganic chemistry
Journal: Russian journal of inorganic chemistry


Crystals
Journal: Crystals


Mendeleev communications
Journal: Mendeleev communications


Chemistry of materials
Journal: Chemistry of materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Acs omega
Journal: Acs omega


Mendeleev communications
Journal: Mendeleev communications


Mendeleev communications
Journal: Mendeleev communications


Mendeleev communications
Journal: Mendeleev communications


Japanese journal of applied physics 61 (se)
Journal: Japanese journal of applied physics


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nanomaterials
Journal: Nanomaterials


International journal of molecular sciences
Journal: International journal of molecular sciences


Mendeleev communications
Journal: Mendeleev communications


Inorganic materials
Journal: Inorganic materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of organic chemistry
Journal: The journal of organic chemistry


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Recueil des travaux chimiques des pays‐bas
Journal: Recueil des travaux chimiques des pays‐bas


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Chemistry–a european journal
Journal: Chemistry–a european journal


Chemistry–a european journal
Journal: Chemistry–a european journal


Journal of the american chemical society
Journal: Journal of the american chemical society


Chemistry–a european journal
Journal: Chemistry–a european journal


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Molecules
Journal: Molecules


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Macromolecules
Journal: Macromolecules


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Coordination chemistry reviews 230 (1-2)
Journal: Coordination chemistry reviews


Inorganic chemistry
Journal: Inorganic chemistry


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemical physics letters 194 (4-6)
Journal: Chemical physics letters


Photochemical &photobiological sciences
Journal: Photochemical &photobiological sciences


Photochemical &photobiological sciences
Journal: Photochemical &photobiological sciences


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Organic letters
Journal: Organic letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Energy &environmental science
Journal: Energy &environmental science


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemistry–a european journal
Journal: Chemistry–a european journal


The journal of physical chemistry b
Journal: The journal of physical chemistry b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Sensors
Journal: Sensors


Applied sciences
Journal: Applied sciences


Photochemical &photobiological sciences
Journal: Photochemical &photobiological sciences


Spectrochimica acta part a: molecular spectroscopy
Journal: Spectrochimica acta part a: molecular spectroscopy


Applied sciences
Journal: Applied sciences


The european physical journal-applied physics
Journal: The european physical journal-applied physics


Langmuir
Journal: Langmuir


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Chemistry–a european journal
Journal: Chemistry–a european journal


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Chemistry–a european journal
Journal: Chemistry–a european journal


Chemistryselect
Journal: Chemistryselect


Photochemical &photobiological sciences
Journal: Photochemical &photobiological sciences


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


The journal of physical chemistry b
Journal: The journal of physical chemistry b


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Journal of spectroscopy
Journal: Journal of spectroscopy


Chemsuschem
Journal: Chemsuschem


European journal of organic chemistry
Journal: European journal of organic chemistry


Turkish journal of chemistry
Journal: Turkish journal of chemistry


Organic &biomolecular chemistry
Journal: Organic &biomolecular chemistry


Chemical physics letters 355 (1-2)
Journal: Chemical physics letters


Recueil des travaux chimiques des pays‐bas
Journal: Recueil des travaux chimiques des pays‐bas


The open inorganic chemistry journal
Journal: The open inorganic chemistry journal


Helvetica chimica acta
Journal: Helvetica chimica acta


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Chemistry–a european journal
Journal: Chemistry–a european journal


Dalton transactions
Journal: Dalton transactions


Chemistry–a european journal
Journal: Chemistry–a european journal


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Electrochemistry communications
Journal: Electrochemistry communications


Comprehensive series in photosciences
Journal: Comprehensive series in photosciences


Inorganic chemistry
Journal: Inorganic chemistry


Antibiotics
Journal: Antibiotics


Photosynthesis research
Journal: Photosynthesis research


Chemphotochem
Journal: Chemphotochem


Angewandte chemie
Journal: Angewandte chemie


Photochemistry and photobiology
Journal: Photochemistry and photobiology


Photochemical &photobiological sciences
Journal: Photochemical &photobiological sciences


Nanopages
Journal: Nanopages


European journal of organic chemistry
Journal: European journal of organic chemistry


Angewandte chemie
Journal: Angewandte chemie


Chemical physics letters 429 (1-3)
Journal: Chemical physics letters


Open chemistry
Journal: Open chemistry


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Molecules
Journal: Molecules


Beilstein journal of organic chemistry
Journal: Beilstein journal of organic chemistry


Journal of photochemistry and photobiology
Journal: Journal of photochemistry and photobiology


Molecules
Journal: Molecules


Journal of porphyrins and phthalocyanines
Journal: Journal of porphyrins and phthalocyanines


Journal of porphyrins and phthalocyanines
Journal: Journal of porphyrins and phthalocyanines


Epa newsletter
Journal: Epa newsletter


Science
Journal: Science


Nature communications
Journal: Nature communications


Science
Journal: Science


Antioxidants &redox signaling
Journal: Antioxidants &redox signaling


Nature communications
Journal: Nature communications


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced energy materials
Journal: Advanced energy materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Joule
Journal: Joule


Journal of the american chemical society
Journal: Journal of the american chemical society


Sustainable energy &fuels
Journal: Sustainable energy &fuels


Advanced materials
Journal: Advanced materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs energy letters
Journal: Acs energy letters


Joule
Journal: Joule


Science
Journal: Science


Advanced materials
Journal: Advanced materials


Advanced functional materials
Journal: Advanced functional materials


Nature chemistry
Journal: Nature chemistry


Angewandte chemie
Journal: Angewandte chemie


Advanced functional materials
Journal: Advanced functional materials


Joule
Journal: Joule


Macromolecules
Journal: Macromolecules


Solar rrl
Journal: Solar rrl


Acs energy letters
Journal: Acs energy letters


Nature
Journal: Nature


Joule
Journal: Joule


Chemistry of materials
Journal: Chemistry of materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Chemical science
Journal: Chemical science


Chem
Journal: Chem


Solar rrl
Journal: Solar rrl


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Nature photonics
Journal: Nature photonics


Acs energy letters
Journal: Acs energy letters


Chemical communications
Journal: Chemical communications


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Journal of fluorine chemistry
Journal: Journal of fluorine chemistry


Advanced energy materials
Journal: Advanced energy materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Acs energy letters
Journal: Acs energy letters


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Solar rrl
Journal: Solar rrl


Chemical science
Journal: Chemical science


Nanoscale
Journal: Nanoscale


Dyes and pigments
Journal: Dyes and pigments


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Organic electronics
Journal: Organic electronics


Journal of fluorine chemistry
Journal: Journal of fluorine chemistry


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Materials horizons
Journal: Materials horizons


Acs energy letters
Journal: Acs energy letters


Advanced materials
Journal: Advanced materials


Sustainable energy &fuels
Journal: Sustainable energy &fuels


Organic electronics
Journal: Organic electronics


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Science
Journal: Science


Acs applied nano materials
Journal: Acs applied nano materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Scientific reports
Journal: Scientific reports


Organic
Journal: Organic


Advanced energy materials
Journal: Advanced energy materials


Organic
Journal: Organic


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Efficient preparations of fluorine compounds
Journal: Efficient preparations of fluorine compounds


Free radical biology and medicine 43
Journal: Free radical biology and medicine


Accounting
Journal: Accounting


Saudi journal of biological sciences
Journal: Saudi journal of biological sciences


Scientific reports
Journal: Scientific reports


Ceramics international
Journal: Ceramics international


Scientific reports
Journal: Scientific reports


Phase transitions
Journal: Phase transitions


Acta metallurgica sinica (english letters)
Journal: Acta metallurgica sinica (english letters)


Frontiers in microbiology
Journal: Frontiers in microbiology


Colloids and surfaces b: biointerfaces
Journal: Colloids and surfaces b: biointerfaces


Journal of electroceramics
Journal: Journal of electroceramics


Catalysts
Journal: Catalysts


Scientific reports
Journal: Scientific reports


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


International journal of chemical kinetics
Journal: International journal of chemical kinetics


Rsc advances
Journal: Rsc advances


Nanomaterials
Journal: Nanomaterials


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Vacuum
Journal: Vacuum


Journal of nanomaterials
Journal: Journal of nanomaterials


Journal of the chinese chemical society
Journal: Journal of the chinese chemical society


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Journal of nanomaterials
Journal: Journal of nanomaterials


Spectrochimica acta part a: molecular and biomolecular spectroscopy
Journal: Spectrochimica acta part a: molecular and biomolecular spectroscopy


Vacuum
Journal: Vacuum


Arabian journal of chemistry
Journal: Arabian journal of chemistry


European journal of chemistry
Journal: European journal of chemistry


Ceramics international
Journal: Ceramics international


Scientific reports
Journal: Scientific reports


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


Journal of the chilean chemical society
Journal: Journal of the chilean chemical society


Molecules
Journal: Molecules


Spectrochimica acta part a: molecular and biomolecular spectroscopy
Journal: Spectrochimica acta part a: molecular and biomolecular spectroscopy


Applied sciences
Journal: Applied sciences


Journal of electronic materials
Journal: Journal of electronic materials


Journal of nanoscience and nanotechnology
Journal: Journal of nanoscience and nanotechnology


Science of advanced materials
Journal: Science of advanced materials


International journal of polymer analysis and characterization
Journal: International journal of polymer analysis and characterization


Journal of molecular structure
Journal: Journal of molecular structure


Colloids and surfaces b: biointerfaces
Journal: Colloids and surfaces b: biointerfaces


Indian j. sci. technol
Journal: Indian j. sci. technol


Journal of thermal analysis and calorimetry
Journal: Journal of thermal analysis and calorimetry


Journal of coordination chemistry
Journal: Journal of coordination chemistry


Journal of polymers and the environment
Journal: Journal of polymers and the environment


Colloids and surfaces a: physicochemical and engineering aspects
Journal: Colloids and surfaces a: physicochemical and engineering aspects


Progress in reaction kinetics and mechanism
Journal: Progress in reaction kinetics and mechanism



Journal of materials science
Journal: Journal of materials science


Journal of molecular catalysis a: chemical 253 (1-2)
Journal: Journal of molecular catalysis a: chemical


Applied catalysis a: general
Journal: Applied catalysis a: general


Catalysis today
Journal: Catalysis today


Catalysis today
Journal: Catalysis today


Interações (campo grande)
Journal: Interações (campo grande)


International journal of hydrogen energy
Journal: International journal of hydrogen energy


Appl. catal. b: env
Journal: Appl. catal. b: env


Journal of microwaves
Journal: Journal of microwaves


Olhares &trilhas
Journal: Olhares &trilhas


Diamond and related materials
Journal: Diamond and related materials


Journal of telemedicine and telecare 6 (2_suppl)
Journal: Journal of telemedicine and telecare


Materials research
Journal: Materials research


Ceramics international
Journal: Ceramics international


Inorganic chemistry communications volume 14
Journal: Inorganic chemistry communications volume


Matéria (rio de janeiro)
Journal: Matéria (rio de janeiro)


Materia-rio de janeiro
Journal: Materia-rio de janeiro


The faseb journal 29
Journal: The faseb journal


História social da língua nacional
Journal: História social da língua nacional


Intertexto
Journal: Intertexto


Journal of telemedicine and telecare 6 (2_suppl)
Journal: Journal of telemedicine and telecare


Science
Journal: Science


Energy &environmental science
Journal: Energy &environmental science


Advanced materials
Journal: Advanced materials


Science
Journal: Science


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Energy &environmental science
Journal: Energy &environmental science


Advanced functional materials
Journal: Advanced functional materials


Science
Journal: Science


Nature communications
Journal: Nature communications


Nature communications
Journal: Nature communications


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced energy materials
Journal: Advanced energy materials


Nano letters
Journal: Nano letters


Science
Journal: Science


Advanced energy materials
Journal: Advanced energy materials


Nature communications
Journal: Nature communications


Nature communications
Journal: Nature communications


Advanced functional materials
Journal: Advanced functional materials


Nature communications
Journal: Nature communications


Nature energy
Journal: Nature energy


Energy &environmental science
Journal: Energy &environmental science


Acs nano
Journal: Acs nano


Acs nano
Journal: Acs nano


Acs nano
Journal: Acs nano


Energy &environmental science
Journal: Energy &environmental science


Nano letters
Journal: Nano letters


Chemistry of materials
Journal: Chemistry of materials


Materials horizons
Journal: Materials horizons


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced materials
Journal: Advanced materials


Nature reviews chemistry
Journal: Nature reviews chemistry


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Joule
Journal: Joule


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs energy letters
Journal: Acs energy letters


Advanced energy materials
Journal: Advanced energy materials


Applied physics letters
Journal: Applied physics letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Advanced energy materials
Journal: Advanced energy materials


Nature energy
Journal: Nature energy


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Sustainable energy &fuels
Journal: Sustainable energy &fuels


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Materials horizons
Journal: Materials horizons


Energy &environmental science
Journal: Energy &environmental science


Advanced functional materials
Journal: Advanced functional materials


Energy &environmental science
Journal: Energy &environmental science


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Science
Journal: Science


Acs energy letters
Journal: Acs energy letters


Acs nano
Journal: Acs nano


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Advanced materials interfaces
Journal: Advanced materials interfaces


Applied energy
Journal: Applied energy


Applied physics letters
Journal: Applied physics letters


Acs applied energy materials
Journal: Acs applied energy materials


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of the american chemical society
Journal: Journal of the american chemical society


J. mater. chem. a
Journal: J. mater. chem. a


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Applied energy
Journal: Applied energy


The embo journal
Journal: The embo journal


Chemistry of materials
Journal: Chemistry of materials


Nanoscale
Journal: Nanoscale


Chemistry of materials
Journal: Chemistry of materials


Applied physics letters
Journal: Applied physics letters


Nano energy
Journal: Nano energy


Acs energy letters
Journal: Acs energy letters


Acs applied energy materials
Journal: Acs applied energy materials


Advanced materials
Journal: Advanced materials


Nature energy
Journal: Nature energy


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs energy letters
Journal: Acs energy letters


Advanced energy materials
Journal: Advanced energy materials


Quarterly journal of the royal meteorological society
Journal: Quarterly journal of the royal meteorological society


Applied physics letters
Journal: Applied physics letters


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Acs energy letters
Journal: Acs energy letters


Acs nano
Journal: Acs nano


Advanced functional materials
Journal: Advanced functional materials


Nano letters
Journal: Nano letters


Acs energy letters
Journal: Acs energy letters


Chemistry of materials
Journal: Chemistry of materials


Acs nano
Journal: Acs nano


Chemistry of materials
Journal: Chemistry of materials


Advanced functional materials
Journal: Advanced functional materials


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Energy storage materials
Journal: Energy storage materials


Acs catalysis
Journal: Acs catalysis


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced functional materials
Journal: Advanced functional materials


Chemphyschem
Journal: Chemphyschem


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Chemistry of materials
Journal: Chemistry of materials


Small
Journal: Small


Chempluschem
Journal: Chempluschem


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs nano
Journal: Acs nano


Acs energy letters
Journal: Acs energy letters


Chemistry of materials
Journal: Chemistry of materials


Langmuir
Journal: Langmuir


Nature energy
Journal: Nature energy


Nanoscale horizons
Journal: Nanoscale horizons


Langmuir
Journal: Langmuir


Journal of the american chemical society
Journal: Journal of the american chemical society


Chemistry of materials
Journal: Chemistry of materials


Acs applied energy materials
Journal: Acs applied energy materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemistry of materials
Journal: Chemistry of materials


Nanotechnology
Journal: Nanotechnology


Materials chemistry and physics
Journal: Materials chemistry and physics


Chemistry of materials
Journal: Chemistry of materials


Materials advances
Journal: Materials advances


Advanced optical materials
Journal: Advanced optical materials


Nanoscale advances
Journal: Nanoscale advances


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Carbohydrate polymers
Journal: Carbohydrate polymers


Small
Journal: Small


Advanced optical materials
Journal: Advanced optical materials


Acs nano
Journal: Acs nano


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Advanced materials
Journal: Advanced materials


Materials advances
Journal: Materials advances


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of nanomaterials
Journal: Journal of nanomaterials


Nanoscale
Journal: Nanoscale


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Acs applied nano materials
Journal: Acs applied nano materials


Journal of physics: materials
Journal: Journal of physics: materials


Nano letters
Journal: Nano letters


Advanced optical materials
Journal: Advanced optical materials


Nanoscale
Journal: Nanoscale


Chemistry of materials
Journal: Chemistry of materials


Advanced functional materials
Journal: Advanced functional materials


Physical review applied
Journal: Physical review applied


Advanced functional materials
Journal: Advanced functional materials


Advanced optical materials
Journal: Advanced optical materials


Physica status solidi (rrl)–rapid research letters
Journal: Physica status solidi (rrl)–rapid research letters


Sustainability
Journal: Sustainability


Acs nano
Journal: Acs nano


Advanced functional materials
Journal: Advanced functional materials


Nano letters
Journal: Nano letters


Acs energy letters
Journal: Acs energy letters


Chemistry of materials
Journal: Chemistry of materials


Acs nano
Journal: Acs nano


Chemistry of materials
Journal: Chemistry of materials


Advanced functional materials
Journal: Advanced functional materials


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Energy storage materials
Journal: Energy storage materials


Acs catalysis
Journal: Acs catalysis


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced functional materials
Journal: Advanced functional materials


Chemphyschem
Journal: Chemphyschem


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Chemistry of materials
Journal: Chemistry of materials


Small
Journal: Small


Chempluschem
Journal: Chempluschem


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs nano
Journal: Acs nano


Acs energy letters
Journal: Acs energy letters


Chemistry of materials
Journal: Chemistry of materials


Langmuir
Journal: Langmuir


Nature energy
Journal: Nature energy


Nanoscale horizons
Journal: Nanoscale horizons


Langmuir
Journal: Langmuir


Journal of the american chemical society
Journal: Journal of the american chemical society


Chemistry of materials
Journal: Chemistry of materials


Acs applied energy materials
Journal: Acs applied energy materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemistry of materials
Journal: Chemistry of materials


Nanotechnology
Journal: Nanotechnology


Materials chemistry and physics
Journal: Materials chemistry and physics


Chemistry of materials
Journal: Chemistry of materials


Materials advances
Journal: Materials advances


Advanced optical materials
Journal: Advanced optical materials


Nanoscale advances
Journal: Nanoscale advances


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Carbohydrate polymers
Journal: Carbohydrate polymers


Small
Journal: Small


Advanced optical materials
Journal: Advanced optical materials


Acs nano
Journal: Acs nano


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Advanced materials
Journal: Advanced materials


Materials advances
Journal: Materials advances


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of nanomaterials
Journal: Journal of nanomaterials


Nanoscale
Journal: Nanoscale


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Acs applied nano materials
Journal: Acs applied nano materials


Journal of physics: materials
Journal: Journal of physics: materials


Nano letters
Journal: Nano letters


Advanced optical materials
Journal: Advanced optical materials


Nanoscale
Journal: Nanoscale


Chemistry of materials
Journal: Chemistry of materials


Advanced functional materials
Journal: Advanced functional materials


Physical review applied
Journal: Physical review applied


Advanced functional materials
Journal: Advanced functional materials


Advanced optical materials
Journal: Advanced optical materials


Physica status solidi (rrl)–rapid research letters
Journal: Physica status solidi (rrl)–rapid research letters


Sustainability
Journal: Sustainability


Nature communications
Journal: Nature communications


Nano letters
Journal: Nano letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Energy &environmental science
Journal: Energy &environmental science


Nature energy
Journal: Nature energy


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Nature energy
Journal: Nature energy


Applied physics letters
Journal: Applied physics letters


Chemistry of materials
Journal: Chemistry of materials


Advanced functional materials
Journal: Advanced functional materials


Carbon
Journal: Carbon


Advanced materials
Journal: Advanced materials


Materials horizons
Journal: Materials horizons


Nature communications
Journal: Nature communications


Journal of materials chemistry a
Journal: Journal of materials chemistry a


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Chemical society reviews
Journal: Chemical society reviews


Journal of materials chemistry a
Journal: Journal of materials chemistry a


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced materials
Journal: Advanced materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Chemistry–a european journal
Journal: Chemistry–a european journal


Journal of colloid and interface science
Journal: Journal of colloid and interface science


Chemistry–a european journal
Journal: Chemistry–a european journal


Acs energy letters
Journal: Acs energy letters


Advanced energy materials
Journal: Advanced energy materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Macromolecules
Journal: Macromolecules


Macromolecules
Journal: Macromolecules


Dalton transactions
Journal: Dalton transactions


European journal of inorganic chemistry
Journal: European journal of inorganic chemistry


International journal of electrochemical science
Journal: International journal of electrochemical science


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Chemistry–a european journal
Journal: Chemistry–a european journal


Organometallics
Journal: Organometallics


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Fuel
Journal: Fuel


Inorganic chemistry
Journal: Inorganic chemistry


Nanoscale
Journal: Nanoscale


Science
Journal: Science


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Carbon
Journal: Carbon


Small methods
Journal: Small methods


Chemistry–a european journal
Journal: Chemistry–a european journal


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Carbon
Journal: Carbon


Dalton transactions
Journal: Dalton transactions


Langmuir
Journal: Langmuir


Journal of solid state electrochemistry
Journal: Journal of solid state electrochemistry


Journal of organometallic chemistry
Journal: Journal of organometallic chemistry


Microporous and mesoporous materials
Journal: Microporous and mesoporous materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemistry–an asian journal
Journal: Chemistry–an asian journal


Communications materials
Journal: Communications materials


Nanotechnology
Journal: Nanotechnology


Thin solid films
Journal: Thin solid films


Physical review applied
Journal: Physical review applied


Carbon
Journal: Carbon


Nanoscale
Journal: Nanoscale


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review materials
Journal: Physical review materials


Oaj materials and devices
Journal: Oaj materials and devices


Physica status solidi (b)
Journal: Physica status solidi (b)


Anales de la academia de ciencias de cuba
Journal: Anales de la academia de ciencias de cuba


Synfacts
Journal: Synfacts


Https://doi.org/10.5281/zenodo.
Journal: Https://doi.org/


Science
Journal: Science


Science
Journal: Science


Energy &environmental science
Journal: Energy &environmental science


Nature materials
Journal: Nature materials


Materials horizons
Journal: Materials horizons


Accounts of chemical research
Journal: Accounts of chemical research


Nano letters
Journal: Nano letters


Nature communications
Journal: Nature communications


Acs energy letters
Journal: Acs energy letters


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Nature communications
Journal: Nature communications


Nano letters
Journal: Nano letters


Joule
Journal: Joule


Physical review letters
Journal: Physical review letters


Advanced energy materials
Journal: Advanced energy materials


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Philosophical magazine
Journal: Philosophical magazine


Applied physics letters
Journal: Applied physics letters


Phys. rev. lett.
Journal: Phys. rev. lett.


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters



Applied physics letters
Journal: Applied physics letters


Journal of materials research
Journal: Journal of materials research


Nanoscale
Journal: Nanoscale


Journal of magnetics
Journal: Journal of magnetics


Ieee transactions on magnetics
Journal: Ieee transactions on magnetics


Journal of applied physics
Journal: Journal of applied physics


Applied physics letters
Journal: Applied physics letters


Journal of applied physics
Journal: Journal of applied physics


Scientific reports
Journal: Scientific reports


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Current applied physics
Journal: Current applied physics


Journal of the korean vacuum society
Journal: Journal of the korean vacuum society


한국세라믹학회지
Journal: 한국세라믹학회지


Journal of applied physics
Journal: Journal of applied physics


Acs applied electronic materials
Journal: Acs applied electronic materials


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


이학논집
Journal: 이학논집


Journal of the korean magnetics society
Journal: Journal of the korean magnetics society


Journal of the korean magnetics society
Journal: Journal of the korean magnetics society


Advanced materials interfaces
Journal: Advanced materials interfaces


한국자기학회 학술연구발표회 논문개요집
Journal: 한국자기학회 학술연구발표회 논문개요집


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Journal of the korean ceramic society
Journal: Journal of the korean ceramic society


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Journal of the korean magnetics society
Journal: Journal of the korean magnetics society


Journal of the korean magnetics society
Journal: Journal of the korean magnetics society


Journal of magnetics
Journal: Journal of magnetics


Journal of the korean magnetics society
Journal: Journal of the korean magnetics society


Journal of the korean magnetics society
Journal: Journal of the korean magnetics society


Journal of the korean magnetics society
Journal: Journal of the korean magnetics society


Journal of the korean magnetics society
Journal: Journal of the korean magnetics society


한국자기학회 학술연구발표회 논문개요집
Journal: 한국자기학회 학술연구발표회 논문개요집


한국자기학회 학술연구발표회 논문개요집
Journal: 한국자기학회 학술연구발표회 논문개요집


한국자기학회 학술연구발표회 논문개요집
Journal: 한국자기학회 학술연구발표회 논문개요집


Journal of the korean magnetics society
Journal: Journal of the korean magnetics society


한국자기학회 학술연구발표회 논문개요집
Journal: 한국자기학회 학술연구발표회 논문개요집


한국자기학회 학술연구발표회 논문개요집
Journal: 한국자기학회 학술연구발표회 논문개요집


Nature energy
Journal: Nature energy


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Matter
Journal: Matter


Advanced energy materials
Journal: Advanced energy materials


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


Nano energy
Journal: Nano energy


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemistry–a european journal
Journal: Chemistry–a european journal


Nanoscale
Journal: Nanoscale


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Langmuir
Journal: Langmuir


Acs nano
Journal: Acs nano


Green chemistry
Journal: Green chemistry


Chemistry–a european journal
Journal: Chemistry–a european journal


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Chemistry–a european journal
Journal: Chemistry–a european journal


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemistry–a european journal
Journal: Chemistry–a european journal


Journal of materials chemistry
Journal: Journal of materials chemistry


Journal of materials chemistry
Journal: Journal of materials chemistry


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Chemical engineering journal
Journal: Chemical engineering journal


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of colloid and interface science
Journal: Journal of colloid and interface science


Optical materials express
Journal: Optical materials express


Advances in colloid and interface science
Journal: Advances in colloid and interface science


Chemphyschem
Journal: Chemphyschem


Science of the total environment
Journal: Science of the total environment


Chemical communications
Journal: Chemical communications


Advanced functional materials
Journal: Advanced functional materials


Optics express
Journal: Optics express


Journal of materials chemistry c
Journal: Journal of materials chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of colloid and interface science
Journal: Journal of colloid and interface science


Industrial &engineering chemistry research
Journal: Industrial &engineering chemistry research


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Electrochimica acta
Journal: Electrochimica acta


Journal of materials chemistry
Journal: Journal of materials chemistry


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Advanced optical materials
Journal: Advanced optical materials


Journal of colloid and interface science
Journal: Journal of colloid and interface science


Chemosphere
Journal: Chemosphere


Acs energy letters
Journal: Acs energy letters


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Chemosphere
Journal: Chemosphere


Nanoscale
Journal: Nanoscale


Journal of porphyrins and phthalocyanines 13 (04n05)
Journal: Journal of porphyrins and phthalocyanines


Chemical engineering journal
Journal: Chemical engineering journal


Journal of luminescence
Journal: Journal of luminescence


Electrochemistry communications
Journal: Electrochemistry communications


Solar rrl
Journal: Solar rrl


Journal of the american chemical society
Journal: Journal of the american chemical society


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Rsc advances
Journal: Rsc advances


Biophysical journal
Journal: Biophysical journal


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Dyes and pigments
Journal: Dyes and pigments


Nanoscale
Journal: Nanoscale


Rsc advances
Journal: Rsc advances


Angewandte chemie
Journal: Angewandte chemie


Acc. chem. res
Journal: Acc. chem. res


Nature energy
Journal: Nature energy


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Matter
Journal: Matter


Advanced energy materials
Journal: Advanced energy materials


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


Nano energy
Journal: Nano energy


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemistry–a european journal
Journal: Chemistry–a european journal


Nanoscale
Journal: Nanoscale


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Langmuir
Journal: Langmuir


Acs nano
Journal: Acs nano


Green chemistry
Journal: Green chemistry


Chemistry–a european journal
Journal: Chemistry–a european journal


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Chemistry–a european journal
Journal: Chemistry–a european journal


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemistry–a european journal
Journal: Chemistry–a european journal


Journal of materials chemistry
Journal: Journal of materials chemistry


Journal of materials chemistry
Journal: Journal of materials chemistry


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Chemical engineering journal
Journal: Chemical engineering journal


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of colloid and interface science
Journal: Journal of colloid and interface science


Optical materials express
Journal: Optical materials express


Advances in colloid and interface science
Journal: Advances in colloid and interface science


Chemphyschem
Journal: Chemphyschem


Science of the total environment
Journal: Science of the total environment


Chemical communications
Journal: Chemical communications


Advanced functional materials
Journal: Advanced functional materials


Optics express
Journal: Optics express


Journal of materials chemistry c
Journal: Journal of materials chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of colloid and interface science
Journal: Journal of colloid and interface science


Industrial &engineering chemistry research
Journal: Industrial &engineering chemistry research


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Electrochimica acta
Journal: Electrochimica acta


Journal of materials chemistry
Journal: Journal of materials chemistry


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Advanced optical materials
Journal: Advanced optical materials


Journal of colloid and interface science
Journal: Journal of colloid and interface science


Chemosphere
Journal: Chemosphere


Acs energy letters
Journal: Acs energy letters


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Chemosphere
Journal: Chemosphere


Nanoscale
Journal: Nanoscale


Journal of porphyrins and phthalocyanines 13 (04n05)
Journal: Journal of porphyrins and phthalocyanines


Chemical engineering journal
Journal: Chemical engineering journal


Journal of luminescence
Journal: Journal of luminescence


Electrochemistry communications
Journal: Electrochemistry communications


Solar rrl
Journal: Solar rrl


Journal of the american chemical society
Journal: Journal of the american chemical society


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Rsc advances
Journal: Rsc advances


Biophysical journal
Journal: Biophysical journal


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Dyes and pigments
Journal: Dyes and pigments


Nanoscale
Journal: Nanoscale


Rsc advances
Journal: Rsc advances


Angewandte chemie
Journal: Angewandte chemie


Acc. chem. res
Journal: Acc. chem. res


Case studies in construction materials
Journal: Case studies in construction materials


Heliyon
Journal: Heliyon


Materials chemistry and physics
Journal: Materials chemistry and physics


Journal of combustion
Journal: Journal of combustion


Data in brief
Journal: Data in brief


Applied clay science
Journal: Applied clay science


Results in physics
Journal: Results in physics


Journal of king saud university-engineering sciences
Journal: Journal of king saud university-engineering sciences


Applied clay science
Journal: Applied clay science


Case studies in thermal engineering
Journal: Case studies in thermal engineering


Results in physics
Journal: Results in physics


Nigerian journal of technology
Journal: Nigerian journal of technology


Procedia manufacturing
Journal: Procedia manufacturing


Tribology in industry
Journal: Tribology in industry


Materials letters
Journal: Materials letters


World journal of engineering
Journal: World journal of engineering


Tribology in industry
Journal: Tribology in industry


Data in brief
Journal: Data in brief


Results in physics
Journal: Results in physics


West indian journal of engineering
Journal: West indian journal of engineering


Applied clay science
Journal: Applied clay science


Materials chemistry and physics
Journal: Materials chemistry and physics


Scientific african
Journal: Scientific african


Results in physics
Journal: Results in physics


Palestine technical university research journal
Journal: Palestine technical university research journal


Applied clay science
Journal: Applied clay science


Tribology in industry
Journal: Tribology in industry


World journal of engineering
Journal: World journal of engineering


Silicon
Journal: Silicon


Nigerian journal of technology
Journal: Nigerian journal of technology


Palestine technical university research journal
Journal: Palestine technical university research journal


West indian journal of engineering
Journal: West indian journal of engineering


Polymer bulletin
Journal: Polymer bulletin


Case studies in construction materials
Journal: Case studies in construction materials


Iosr journal of engineering
Journal: Iosr journal of engineering


Wit transactions on ecology and the environment
Journal: Wit transactions on ecology and the environment


Data in brief
Journal: Data in brief


Engineering reports
Journal: Engineering reports


Heliyon
Journal: Heliyon


Pelagia research library
Journal: Pelagia research library


Polymer bulletin
Journal: Polymer bulletin


International journal of engineering pedagogy
Journal: International journal of engineering pedagogy


Procedia manufacturing
Journal: Procedia manufacturing


Bulgarian journal of science and education policy
Journal: Bulgarian journal of science and education policy


World journal of engineering
Journal: World journal of engineering


World journal of engineering
Journal: World journal of engineering


Journal of the korean ceramic society
Journal: Journal of the korean ceramic society


Scientific reports
Journal: Scientific reports


Journal of the australian ceramic society
Journal: Journal of the australian ceramic society


Catalysts
Journal: Catalysts


Materials letters
Journal: Materials letters


International journal of low-carbon technologies
Journal: International journal of low-carbon technologies


Nigerian journal of technology
Journal: Nigerian journal of technology


World journal of engineering
Journal: World journal of engineering


West indian journal of engineering
Journal: West indian journal of engineering


World journal of engineering
Journal: World journal of engineering


Materials chemistry and physics
Journal: Materials chemistry and physics


Iranian polymer journal
Journal: Iranian polymer journal


Journal of environmental chemical engineering
Journal: Journal of environmental chemical engineering


Mrs advances
Journal: Mrs advances


The journal of t he association of professional engineers of trinidad and …
Journal: The journal of t he association of professional engineers of trinidad and …


The journal of the association of professional engineers of trinidad and …
Journal: The journal of the association of professional engineers of trinidad and …


Au journal of technology
Journal: Au journal of technology


International jurnal of modern engineering research
Journal: International jurnal of modern engineering research


Case studies in construction materials
Journal: Case studies in construction materials


Heliyon
Journal: Heliyon


Materials chemistry and physics
Journal: Materials chemistry and physics


Journal of combustion
Journal: Journal of combustion


Data in brief
Journal: Data in brief


Applied clay science
Journal: Applied clay science


Results in physics
Journal: Results in physics


Journal of king saud university-engineering sciences
Journal: Journal of king saud university-engineering sciences


Applied clay science
Journal: Applied clay science


Case studies in thermal engineering
Journal: Case studies in thermal engineering


Results in physics
Journal: Results in physics


Nigerian journal of technology
Journal: Nigerian journal of technology


Procedia manufacturing
Journal: Procedia manufacturing


Tribology in industry
Journal: Tribology in industry


Materials letters
Journal: Materials letters


World journal of engineering
Journal: World journal of engineering


Tribology in industry
Journal: Tribology in industry


Data in brief
Journal: Data in brief


Results in physics
Journal: Results in physics


West indian journal of engineering
Journal: West indian journal of engineering


Applied clay science
Journal: Applied clay science


Materials chemistry and physics
Journal: Materials chemistry and physics


Scientific african
Journal: Scientific african


Results in physics
Journal: Results in physics


Palestine technical university research journal
Journal: Palestine technical university research journal


Applied clay science
Journal: Applied clay science


Tribology in industry
Journal: Tribology in industry


World journal of engineering
Journal: World journal of engineering


Silicon
Journal: Silicon


Nigerian journal of technology
Journal: Nigerian journal of technology


Palestine technical university research journal
Journal: Palestine technical university research journal


West indian journal of engineering
Journal: West indian journal of engineering


Polymer bulletin
Journal: Polymer bulletin


Case studies in construction materials
Journal: Case studies in construction materials


Iosr journal of engineering
Journal: Iosr journal of engineering


Wit transactions on ecology and the environment
Journal: Wit transactions on ecology and the environment


Data in brief
Journal: Data in brief


Engineering reports
Journal: Engineering reports


Heliyon
Journal: Heliyon


Pelagia research library
Journal: Pelagia research library


Polymer bulletin
Journal: Polymer bulletin


International journal of engineering pedagogy
Journal: International journal of engineering pedagogy


Procedia manufacturing
Journal: Procedia manufacturing


Bulgarian journal of science and education policy
Journal: Bulgarian journal of science and education policy


World journal of engineering
Journal: World journal of engineering


World journal of engineering
Journal: World journal of engineering


Journal of the korean ceramic society
Journal: Journal of the korean ceramic society


Scientific reports
Journal: Scientific reports


Journal of the australian ceramic society
Journal: Journal of the australian ceramic society


Catalysts

Chemsuschem
Journal: Chemsuschem


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Solar rrl
Journal: Solar rrl


Rsc advances
Journal: Rsc advances


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of physical chemistry c
Journal: Journal of physical chemistry c


European journal of inorganic chemistry
Journal: European journal of inorganic chemistry


Acs energy letters
Journal: Acs energy letters


Advanced materials interfaces
Journal: Advanced materials interfaces


Acs applied nano materials
Journal: Acs applied nano materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs sensors
Journal: Acs sensors


Advanced functional materials
Journal: Advanced functional materials


Advanced optical materials
Journal: Advanced optical materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced photonics research
Journal: Advanced photonics research


Acs photonics
Journal: Acs photonics


Inorganic chemistry
Journal: Inorganic chemistry


Nanoscale
Journal: Nanoscale


Physica status solidi c
Journal: Physica status solidi c


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Apl materials
Journal: Apl materials


Journal of chemical physics
Journal: Journal of chemical physics


Chemistry of materials
Journal: Chemistry of materials


Acs energy letters
Journal: Acs energy letters


Advanced optical materials
Journal: Advanced optical materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Nano letters
Journal: Nano letters


Nano letters
Journal: Nano letters


Science
Journal: Science


Nature communications
Journal: Nature communications


Nano letters
Journal: Nano letters


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs nano
Journal: Acs nano


Acs nano
Journal: Acs nano


Energy &environmental science
Journal: Energy &environmental science


Acs applied nano materials
Journal: Acs applied nano materials


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Acs nano
Journal: Acs nano


Acs nano
Journal: Acs nano


Journal of the american chemical society
Journal: Journal of the american chemical society


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Acs nano
Journal: Acs nano


Chemistry of materials
Journal: Chemistry of materials


Green chemistry
Journal: Green chemistry


Acs nano
Journal: Acs nano


Small
Journal: Small


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs nano
Journal: Acs nano


Nano letters
Journal: Nano letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs central science
Journal: Acs central science


Acs energy letters
Journal: Acs energy letters


Applied catalysis a: general
Journal: Applied catalysis a: general


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Acs nano
Journal: Acs nano


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Acs photonics
Journal: Acs photonics


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Applied physics letters
Journal: Applied physics letters


Advanced energy materials
Journal: Advanced energy materials


Chemphyschem
Journal: Chemphyschem


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Chemical science
Journal: Chemical science


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced materials
Journal: Advanced materials


New biotechnology
Journal: New biotechnology


Advanced materials
Journal: Advanced materials


Organic photonics and photovoltaics
Journal: Organic photonics and photovoltaics


Nature materials
Journal: Nature materials


Icest
Journal: Icest


Advanced functional materials
Journal: Advanced functional materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Scientific reports
Journal: Scientific reports


Acs biomaterials science &engineering
Journal: Acs biomaterials science &engineering


Chemical communications
Journal: Chemical communications


Nanoscale
Journal: Nanoscale


Journal of colloid and interface science
Journal: Journal of colloid and interface science


Small
Journal: Small


Small
Journal: Small


Nanomaterials
Journal: Nanomaterials


Nanoscale
Journal: Nanoscale


Nanomedicine: nanotechnology
Journal: Nanomedicine: nanotechnology


Advanced optical materials
Journal: Advanced optical materials


Nanoscale
Journal: Nanoscale


Nanotechnology
Journal: Nanotechnology


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Physical review b
Journal: Physical review b


Ecs transactions
Journal: Ecs transactions


Journal of nanoparticle research
Journal: Journal of nanoparticle research


Nanoscale research letters
Journal: Nanoscale research letters


Acs biomaterials science &engineering
Journal: Acs biomaterials science &engineering


Pharmaceutics
Journal: Pharmaceutics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Plos one
Journal: Plos one


Acs applied nano materials
Journal: Acs applied nano materials


Royal society open science
Journal: Royal society open science


Canadian journal of chemistry
Journal: Canadian journal of chemistry


Nanoscale
Journal: Nanoscale


Acs biomaterials science &engineering
Journal: Acs biomaterials science &engineering


Journal of coordination chemistry
Journal: Journal of coordination chemistry


Nanoscale
Journal: Nanoscale


Journal of nanomedicine research
Journal: Journal of nanomedicine research


Nanomaterials
Journal: Nanomaterials


Ecs transactions
Journal: Ecs transactions


Advanced materials interfaces
Journal: Advanced materials interfaces


Ecs transactions
Journal: Ecs transactions


Advanced functional materials
Journal: Advanced functional materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Scientific reports
Journal: Scientific reports


Acs biomaterials science &engineering
Journal: Acs biomaterials science &engineering


Chemical communications
Journal: Chemical communications


Nanoscale
Journal: Nanoscale


Journal of colloid and interface science
Journal: Journal of colloid and interface science


Small
Journal: Small


Small
Journal: Small


Nanomaterials
Journal: Nanomaterials


Nanoscale
Journal: Nanoscale


Nanomedicine: nanotechnology
Journal: Nanomedicine: nanotechnology


Advanced optical materials
Journal: Advanced optical materials


Nanoscale
Journal: Nanoscale


Nanotechnology
Journal: Nanotechnology


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Physical review b
Journal: Physical review b


Ecs transactions
Journal: Ecs transactions


Journal of nanoparticle research
Journal: Journal of nanoparticle research


Nanoscale research letters
Journal: Nanoscale research letters


Acs biomaterials science &engineering
Journal: Acs biomaterials science &engineering


Pharmaceutics
Journal: Pharmaceutics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Plos one
Journal: Plos one


Acs applied nano materials
Journal: Acs applied nano materials


Royal society open science
Journal: Royal society open science


Canadian journal of chemistry
Journal: Canadian journal of chemistry


Nanoscale
Journal: Nanoscale


Acs biomaterials science &engineering
Journal: Acs biomaterials science &engineering


Journal of coordination chemistry
Journal: Journal of coordination chemistry


Nanoscale
Journal: Nanoscale


Journal of nanomedicine research
Journal: Journal of nanomedicine research


Nanomaterials
Journal: Nanomaterials


Ecs transactions
Journal: Ecs transactions


Advanced materials interfaces
Journal: Advanced materials interfaces


Ecs transactions
Journal: Ecs transactions


Nature
Journal: Nature


Nature communications
Journal: Nature communications


Nature
Journal: Nature


Physics reports
Journal: Physics reports


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


Advanced materials
Journal: Advanced materials


Scientific reports
Journal: Scientific reports


Small
Journal: Small


Applied physics reviews
Journal: Applied physics reviews


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Nanoscale
Journal: Nanoscale


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Chemical reviews
Journal: Chemical reviews


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Small
Journal: Small


Nanoscale
Journal: Nanoscale


Nanoscale research letters
Journal: Nanoscale research letters


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Nature communications
Journal: Nature communications


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


Nanotechnology
Journal: Nanotechnology


Nanoscale research letters
Journal: Nanoscale research letters


Appl. phys. lett.
Journal: Appl. phys. lett.


Nature communications
Journal: Nature communications


Chemistry of materials
Journal: Chemistry of materials


Nanoscale research letters
Journal: Nanoscale research letters


Applied physics letters
Journal: Applied physics letters


Nanoscale
Journal: Nanoscale


Dalton transactions
Journal: Dalton transactions


Nanoscale research letters
Journal: Nanoscale research letters


Applied physics letters
Journal: Applied physics letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Advanced optical materials
Journal: Advanced optical materials


Inorganic chemistry frontiers
Journal: Inorganic chemistry frontiers


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Nanotechnology
Journal: Nanotechnology


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Crystengcomm
Journal: Crystengcomm


Rsc advances
Journal: Rsc advances


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nano research
Journal: Nano research


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Nano letters
Journal: Nano letters


Optical materials
Journal: Optical materials


Materials science in semiconductor processing
Journal: Materials science in semiconductor processing


Small
Journal: Small


Scientific reports
Journal: Scientific reports


Nanotechnology
Journal: Nanotechnology


Science china physics
Journal: Science china physics


Applied physics letters
Journal: Applied physics letters


Chemical engineering journal
Journal: Chemical engineering journal


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Ferroelectrics
Journal: Ferroelectrics


Aip advances
Journal: Aip advances


Journal of applied physics
Journal: Journal of applied physics


Advanced materials
Journal: Advanced materials


Journal of applied physics
Journal: Journal of applied physics


Scientific reports
Journal: Scientific reports


Journal of applied physics
Journal: Journal of applied physics


Journal of wuhan university of technology-mater. sci. ed.
Journal: Journal of wuhan university of technology-mater. sci. ed.


Chemical society reviews
Journal: Chemical society reviews


Materials today physics
Journal: Materials today physics


Advanced optical materials
Journal: Advanced optical materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


物理学报
Journal: 物理学报


Analytical letters
Journal: Analytical letters


Journal of experimental nanoscience
Journal: Journal of experimental nanoscience


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


Int. j. eng. res. appl
Journal: Int. j. eng. res. appl


Journal of hazardous materials
Journal: Journal of hazardous materials


Int. j. adv. res. sci. eng
Journal: Int. j. adv. res. sci. eng


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


Acs applied electronic materials
Journal: Acs applied electronic materials


Physica b: condensed matter
Journal: Physica b: condensed matter


Nanoscale
Journal: Nanoscale


Inorganic chemistry
Journal: Inorganic chemistry


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


Acs applied electronic materials
Journal: Acs applied electronic materials


Chemical and pharmaceutical bulletin
Journal: Chemical and pharmaceutical bulletin


Microchemical journal
Journal: Microchemical journal


Journal of physics and chemistry of solids
Journal: Journal of physics and chemistry of solids


Microchimica acta
Journal: Microchimica acta


Inorganic chemistry
Journal: Inorganic chemistry


Chemical engineering journal
Journal: Chemical engineering journal


Inorganic chemistry
Journal: Inorganic chemistry


New journal of chemistry
Journal: New journal of chemistry


Journal of electroanalytical chemistry
Journal: Journal of electroanalytical chemistry


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Journal of materials research and technology
Journal: Journal of materials research and technology


Ijsrd—international journal for scientific research &development
Journal: Ijsrd—international journal for scientific research &development


Inorganic chemistry
Journal: Inorganic chemistry


Physica b: condensed matter
Journal: Physica b: condensed matter


Solid state sciences
Journal: Solid state sciences


Journal of materials research and technology
Journal: Journal of materials research and technology


Journal of nanoscience and nanotechnology
Journal: Journal of nanoscience and nanotechnology


Optik
Journal: Optik


International journal of advance research in science
Journal: International journal of advance research in science


Surfaces and interfaces
Journal: Surfaces and interfaces


Journal of nanoscience and nanotechnology
Journal: Journal of nanoscience and nanotechnology


International journal of advance research in science and engineering (ijarse …
Journal: International journal of advance research in science and engineering (ijarse …


Journal of materials research and technology
Journal: Journal of materials research and technology


Chemia analityczna
Journal: Chemia analityczna


Chemical engineering journal
Journal: Chemical engineering journal


Journal of molecular liquids
Journal: Journal of molecular liquids


Environmental research
Journal: Environmental research


Journal of industrial and engineering chemistry
Journal: Journal of industrial and engineering chemistry


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Sensors &transducers
Journal: Sensors &transducers


Environmental research
Journal: Environmental research


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Journal of materials nanoscience
Journal: Journal of materials nanoscience


International journal of research in pharmacy and chemistry
Journal: International journal of research in pharmacy and chemistry


Int. j. chem. res.
Journal: Int. j. chem. res.


Anal. lett
Journal: Anal. lett


Chemosphere
Journal: Chemosphere


Inorganic chemistry
Journal: Inorganic chemistry


International journal for research in applied science and engineering …
Journal: International journal for research in applied science and engineering …


Journal of molecular liquids
Journal: Journal of molecular liquids


Chemosphere
Journal: Chemosphere


Microchemical journal
Journal: Microchemical journal


Environmental research
Journal: Environmental research


Molecules
Journal: Molecules


Sustainable energy technologies and assessments
Journal: Sustainable energy technologies and assessments


J. indian chem. soc
Journal: J. indian chem. soc


World journal of pharmaceutical research 3 (5 suppl.)
Journal: World journal of pharmaceutical research


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Analytical letters
Journal: Analytical letters


Journal of experimental nanoscience
Journal: Journal of experimental nanoscience


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


Int. j. eng. res. appl
Journal: Int. j. eng. res. appl


Journal of hazardous materials
Journal: Journal of hazardous materials


Int. j. adv. res. sci. eng
Journal: Int. j. adv. res. sci. eng


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


Acs applied electronic materials
Journal: Acs applied electronic materials


Physica b: condensed matter
Journal: Physica b: condensed matter


Nanoscale
Journal: Nanoscale


Inorganic chemistry
Journal: Inorganic chemistry


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


Acs applied electronic materials
Journal: Acs applied electronic materials


Chemical and pharmaceutical bulletin
Journal: Chemical and pharmaceutical bulletin


Microchemical journal
Journal: Microchemical journal


Journal of physics and chemistry of solids
Journal: Journal of physics and chemistry of solids


Microchimica acta
Journal: Microchimica acta


Inorganic chemistry
Journal: Inorganic chemistry


Chemical engineering journal
Journal: Chemical engineering journal


Inorganic chemistry
Journal: Inorganic chemistry


New journal of chemistry
Journal: New journal of chemistry


Journal of electroanalytical chemistry
Journal: Journal of electroanalytical chemistry


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Journal of materials research and technology
Journal: Journal of materials research and technology


Ijsrd—international journal for scientific research &development
Journal: Ijsrd—international journal for scientific research &development


Inorganic chemistry
Journal: Inorganic chemistry


Physica b: condensed matter
Journal: Physica b: condensed matter


Solid state sciences
Journal: Solid state sciences


Journal of materials research and technology
Journal: Journal of materials research and technology


Journal of nanoscience and nanotechnology
Journal: Journal of nanoscience and nanotechnology


Optik
Journal: Optik


International journal of advance research in science
Journal: International journal of advance research in science


Surfaces and interfaces
Journal: Surfaces and interfaces


Journal of nanoscience and nanotechnology
Journal: Journal of nanoscience and nanotechnology


International journal of advance research in science and engineering (ijarse …

Chemical physics
Journal: Chemical physics


Energy storage materials
Journal: Energy storage materials


Small
Journal: Small


Apl materials
Journal: Apl materials


Energy storage materials
Journal: Energy storage materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs catalysis
Journal: Acs catalysis


Journal of applied physics
Journal: Journal of applied physics


Applied physics reviews
Journal: Applied physics reviews


Applied physics letters
Journal: Applied physics letters


Nanoscale
Journal: Nanoscale


Journal of catalysis
Journal: Journal of catalysis


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of applied physics
Journal: Journal of applied physics


Advanced sustainable systems
Journal: Advanced sustainable systems


Particle &particle systems characterization
Journal: Particle &particle systems characterization


Materials advances
Journal: Materials advances


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review b
Journal: Physical review b


Advanced theory and simulations
Journal: Advanced theory and simulations


Advanced materials
Journal: Advanced materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Current opinion in electrochemistry
Journal: Current opinion in electrochemistry


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Physical review b
Journal: Physical review b


Europhysics letters
Journal: Europhysics letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Small
Journal: Small


Advanced theory and simulations
Journal: Advanced theory and simulations


Advanced theory and simulations
Journal: Advanced theory and simulations


Advanced theory and simulations
Journal: Advanced theory and simulations


Small
Journal: Small


Energy &environmental science
Journal: Energy &environmental science


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Acs energy letters
Journal: Acs energy letters


Acs catalysis
Journal: Acs catalysis


Applied physics letters
Journal: Applied physics letters


Nature communications
Journal: Nature communications


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nature communications
Journal: Nature communications


Small
Journal: Small


Scientific reports
Journal: Scientific reports


Small
Journal: Small


Small
Journal: Small


Acs catalysis
Journal: Acs catalysis


Nanoscale
Journal: Nanoscale


Journal of applied physics
Journal: Journal of applied physics


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nature catalysis
Journal: Nature catalysis


Materials horizons
Journal: Materials horizons


Chemsuschem
Journal: Chemsuschem


Acs catalysis
Journal: Acs catalysis


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Applied physics letters
Journal: Applied physics letters


Advanced theory and simulations
Journal: Advanced theory and simulations


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Acta materialia
Journal: Acta materialia


Chemistry of materials
Journal: Chemistry of materials


Chemical physics
Journal: Chemical physics


Energy storage materials
Journal: Energy storage materials


Small
Journal: Small


Apl materials
Journal: Apl materials


Energy storage materials
Journal: Energy storage materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs catalysis
Journal: Acs catalysis


Journal of applied physics
Journal: Journal of applied physics


Applied physics reviews
Journal: Applied physics reviews


Applied physics letters
Journal: Applied physics letters


Nanoscale
Journal: Nanoscale


Journal of catalysis
Journal: Journal of catalysis


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of applied physics
Journal: Journal of applied physics


Advanced sustainable systems
Journal: Advanced sustainable systems


Particle &particle systems characterization
Journal: Particle &particle systems characterization


Materials advances
Journal: Materials advances


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review b
Journal: Physical review b


Advanced theory and simulations
Journal: Advanced theory and simulations


Advanced materials
Journal: Advanced materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Current opinion in electrochemistry
Journal: Current opinion in electrochemistry


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Physical review b
Journal: Physical review b


Europhysics letters
Journal: Europhysics letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Small
Journal: Small


Advanced theory and simulations
Journal: Advanced theory and simulations


Advanced theory and simulations
Journal: Advanced theory and simulations


Advanced theory and simulations
Journal: Advanced theory and simulations


Small
Journal: Small


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Optics express
Journal: Optics express


Nanoscale research letters
Journal: Nanoscale research letters


Acs photonics
Journal: Acs photonics


Applied materials today
Journal: Applied materials today


Materials letters
Journal: Materials letters


Optical materials
Journal: Optical materials


Advanced functional materials
Journal: Advanced functional materials


Nanoscale
Journal: Nanoscale


Chinese physics b
Journal: Chinese physics b


Nano-micro letters
Journal: Nano-micro letters


Ieee photonics technology letters
Journal: Ieee photonics technology letters


Solid-state electronics
Journal: Solid-state electronics


Energy
Journal: Energy


Chemical engineering journal
Journal: Chemical engineering journal


Ieee photonics journal
Journal: Ieee photonics journal


Journal of power sources
Journal: Journal of power sources


Acs photonics
Journal: Acs photonics


Solar energy
Journal: Solar energy


Photonics research
Journal: Photonics research


Acs applied nano materials
Journal: Acs applied nano materials


Optics express
Journal: Optics express


Chinese physics letters
Journal: Chinese physics letters


Applied optics
Journal: Applied optics


Energy
Journal: Energy


Applied optics
Journal: Applied optics


Applied physics letters
Journal: Applied physics letters


Materials letters
Journal: Materials letters


Chemical engineering journal
Journal: Chemical engineering journal


Acs applied energy materials
Journal: Acs applied energy materials


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Scientific reports
Journal: Scientific reports


Optics express
Journal: Optics express


Physica e: low-dimensional systems and nanostructures
Journal: Physica e: low-dimensional systems and nanostructures


Applied optics
Journal: Applied optics


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Ieee access
Journal: Ieee access


Applied optics
Journal: Applied optics


Functional materials letters
Journal: Functional materials letters


Annalen der physik
Journal: Annalen der physik


Applied optics
Journal: Applied optics


Quantum electronics
Journal: Quantum electronics


Chinese physics letters
Journal: Chinese physics letters


Solar energy
Journal: Solar energy


Advanced functional materials
Journal: Advanced functional materials


Applied optics
Journal: Applied optics


Applied optics
Journal: Applied optics


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Communications physics
Journal: Communications physics


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Frontiers in physics
Journal: Frontiers in physics


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Nanoscale research letters
Journal: Nanoscale research letters


Journal of power sources
Journal: Journal of power sources


Acs photonics
Journal: Acs photonics


Solar energy
Journal: Solar energy


Applied optics
Journal: Applied optics


Optics express
Journal: Optics express


Applied physics letters
Journal: Applied physics letters


Optical materials express
Journal: Optical materials express


Annalen der physik
Journal: Annalen der physik


Bandaoti jishu(semiconductor technology)
Journal: Bandaoti jishu(semiconductor technology)


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Optics express
Journal: Optics express


Nanoscale research letters
Journal: Nanoscale research letters


Acs photonics
Journal: Acs photonics


Applied materials today
Journal: Applied materials today


Materials letters
Journal: Materials letters


Optical materials
Journal: Optical materials


Advanced functional materials
Journal: Advanced functional materials


Nanoscale
Journal: Nanoscale


Chinese physics b
Journal: Chinese physics b


Nano-micro letters
Journal: Nano-micro letters


Ieee photonics technology letters
Journal: Ieee photonics technology letters


Solid-state electronics
Journal: Solid-state electronics


Energy
Journal: Energy


Chemical engineering journal
Journal: Chemical engineering journal


Ieee photonics journal
Journal: Ieee photonics journal


Journal of power sources
Journal: Journal of power sources


Acs photonics
Journal: Acs photonics


Solar energy
Journal: Solar energy


Photonics research
Journal: Photonics research


Acs applied nano materials
Journal: Acs applied nano materials


Optics express
Journal: Optics express


Chinese physics letters
Journal: Chinese physics letters


Applied optics
Journal: Applied optics


Energy
Journal: Energy


Applied optics
Journal: Applied optics


Applied physics letters
Journal: Applied physics letters


Materials letters
Journal: Materials letters


Chemical engineering journal
Journal: Chemical engineering journal


Acs applied energy materials
Journal: Acs applied energy materials


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Scientific reports
Journal: Scientific reports


Optics express
Journal: Optics express


Physica e: low-dimensional systems and nanostructures
Journal: Physica e: low-dimensional systems and nanostructures


Applied optics
Journal: Applied optics


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Ieee access
Journal: Ieee access


Applied optics
Journal: Applied optics


Functional materials letters
Journal: Functional materials letters


Annalen der physik
Journal: Annalen der physik


Applied optics
Journal: Applied optics


Quantum electronics
Journal: Quantum electronics


Chinese physics letters
Journal: Chinese physics letters


Solar energy
Journal: Solar energy


Advanced functional materials
Journal: Advanced functional materials


Applied optics
Journal: Applied optics


Applied optics
Journal: Applied optics


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Communications physics
Journal: Communications physics


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Frontiers in physics
Journal: Frontiers in physics


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Nanoscale research letters
Journal: Nanoscale research letters


Journal of power sources
Journal: Journal of power sources


Acs photonics
Journal: Acs photonics


Solar energy
Journal: Solar energy


Applied optics
Journal: Applied optics


Optics express
Journal: Optics express


Applied physics letters
Journal: Applied physics letters


Optical materials express
Journal: Optical materials express


Annalen der physik
Journal: Annalen der physik


Bandaoti jishu(semiconductor technology)
Journal: Bandaoti jishu(semiconductor technology)


Materials today
Journal: Materials today


Journal of materials chemistry
Journal: Journal of materials chemistry


Advanced functional materials
Journal: Advanced functional materials


Advanced materials
Journal: Advanced materials


Chemistry of materials
Journal: Chemistry of materials


Inorganic chemistry
Journal: Inorganic chemistry


Acs photonics
Journal: Acs photonics


Journal of the american chemical society
Journal: Journal of the american chemical society


Nano letters
Journal: Nano letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Advanced energy materials
Journal: Advanced energy materials


Chemistry of materials
Journal: Chemistry of materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of materials chemistry
Journal: Journal of materials chemistry


Chemistry-a european journal
Journal: Chemistry-a european journal


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Dalton transactions
Journal: Dalton transactions


Advanced energy materials
Journal: Advanced energy materials


Advanced optical materials
Journal: Advanced optical materials


Reports on progress in physics
Journal: Reports on progress in physics


Nano letters
Journal: Nano letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Dalton transactions
Journal: Dalton transactions


Acs photonics
Journal: Acs photonics


Advanced materials technologies
Journal: Advanced materials technologies


Dalton transactions
Journal: Dalton transactions


Journal of materials chemistry
Journal: Journal of materials chemistry


Journal of the society for information display
Journal: Journal of the society for information display


Nano letters
Journal: Nano letters


Ieee transactions on applied superconductivity
Journal: Ieee transactions on applied superconductivity


Advanced optical materials
Journal: Advanced optical materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Crystal growth &design
Journal: Crystal growth &design


Advanced optical materials
Journal: Advanced optical materials


Advanced optical materials
Journal: Advanced optical materials


Crystal growth &design
Journal: Crystal growth &design


Advanced functional materials
Journal: Advanced functional materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Organic electronics
Journal: Organic electronics


Journal of the society for information display
Journal: Journal of the society for information display


Dalton transactions
Journal: Dalton transactions


Journal of nanoscience and nanotechnology
Journal: Journal of nanoscience and nanotechnology


Flexible and printed electronics
Journal: Flexible and printed electronics


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Beilstein journal of organic chemistry
Journal: Beilstein journal of organic chemistry


Advanced optical materials
Journal: Advanced optical materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Advanced materials
Journal: Advanced materials


Advanced optical materials
Journal: Advanced optical materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Organic light emitting materials and devices xvi
Journal: Organic light emitting materials and devices xvi


Journal of the american chemical society
Journal: Journal of the american chemical society


Materials letters
Journal: Materials letters


Carbon
Journal: Carbon


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs energy letters
Journal: Acs energy letters


Npj 2d materials and applications
Journal: Npj


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Solar energy
Journal: Solar energy


Acs applied energy materials
Journal: Acs applied energy materials


Acs energy letters
Journal: Acs energy letters


Applied physics letters
Journal: Applied physics letters


The journal of chemical physics
Journal: The journal of chemical physics


The journal of physical chemistry a
Journal: The journal of physical chemistry a


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Applied surface science
Journal: Applied surface science


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Chemical physics letters 507 (1-3)
Journal: Chemical physics letters


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


The journal of physical chemistry a
Journal: The journal of physical chemistry a


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Chemical physics letters 493 (1-3)
Journal: Chemical physics letters


Chemical physics letters 382 (1-2)
Journal: Chemical physics letters


Acs photonics
Journal: Acs photonics


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Dalton transactions
Journal: Dalton transactions


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs omega
Journal: Acs omega


Rsc advances
Journal: Rsc advances


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


Chemical physics letters
Journal: Chemical physics letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nanotechnology
Journal: Nanotechnology


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Organic electronics
Journal: Organic electronics


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


Journal of photochemistry and photobiology a: chemistry 188 (2-3)
Journal: Journal of photochemistry and photobiology a: chemistry


Chemical physics letters 406 (4-6)
Journal: Chemical physics letters


Physica e: low-dimensional systems and nanostructures

Nanoscale
Journal: Nanoscale


Cell reports physical science
Journal: Cell reports physical science


Acs applied energy materials
Journal: Acs applied energy materials


Advanced energy materials
Journal: Advanced energy materials


Acs catalysis
Journal: Acs catalysis


Applied physics letters
Journal: Applied physics letters


Angewandte chemie
Journal: Angewandte chemie


Acs energy letters
Journal: Acs energy letters


Nachrichten aus der chemie
Journal: Nachrichten aus der chemie


Nature reviews chemistry
Journal: Nature reviews chemistry


Chem
Journal: Chem


Conferentie hopv
Journal: Conferentie hopv


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Physica status solidi (rrl)–rapid research letters
Journal: Physica status solidi (rrl)–rapid research letters


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Advanced energy materials
Journal: Advanced energy materials


Applied physics letters
Journal: Applied physics letters


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Journal of applied physics
Journal: Journal of applied physics


Physica status solidi (rrl)–rapid research letters 4 (5‐6)
Journal: Physica status solidi (rrl)–rapid research letters


Thin solid films
Journal: Thin solid films


Scientific reports
Journal: Scientific reports


Thin solid films
Journal: Thin solid films


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Acta materialia
Journal: Acta materialia


Journal of applied physics
Journal: Journal of applied physics


Journal of applied physics
Journal: Journal of applied physics


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Photovoltaics
Journal: Photovoltaics


Applied physics letters
Journal: Applied physics letters


Physica status solidi (b)
Journal: Physica status solidi (b)


Journal of applied crystallography
Journal: Journal of applied crystallography


Applied surface science
Journal: Applied surface science


Epj photovoltaics
Journal: Epj photovoltaics


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Applied physics letters
Journal: Applied physics letters


Journal of applied physics
Journal: Journal of applied physics


Applied physics letters
Journal: Applied physics letters


Ultramicroscopy
Journal: Ultramicroscopy


Thin solid films
Journal: Thin solid films


Physica status solidi (rrl)–rapid research letters
Journal: Physica status solidi (rrl)–rapid research letters


Thin solid films
Journal: Thin solid films


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Thin solid films
Journal: Thin solid films


Applied physics a
Journal: Applied physics a


Japanese journal of applied physics 51 (10s)
Journal: Japanese journal of applied physics


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Thin solid films
Journal: Thin solid films


Journal of applied crystallography
Journal: Journal of applied crystallography


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Physica status solidi (rrl)–rapid research letters
Journal: Physica status solidi (rrl)–rapid research letters


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Advanced energy materials
Journal: Advanced energy materials


Applied physics letters
Journal: Applied physics letters


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Journal of applied physics
Journal: Journal of applied physics


Physica status solidi (rrl)–rapid research letters 4 (5‐6)
Journal: Physica status solidi (rrl)–rapid research letters


Thin solid films
Journal: Thin solid films


Scientific reports
Journal: Scientific reports


Thin solid films
Journal: Thin solid films


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Acta materialia
Journal: Acta materialia


Journal of applied physics
Journal: Journal of applied physics


Journal of applied physics
Journal: Journal of applied physics


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Photovoltaics
Journal: Photovoltaics


Applied physics letters
Journal: Applied physics letters


Physica status solidi (b)
Journal: Physica status solidi (b)


Journal of applied crystallography
Journal: Journal of applied crystallography


Applied surface science
Journal: Applied surface science


Epj photovoltaics
Journal: Epj photovoltaics


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Applied physics letters
Journal: Applied physics letters


Journal of applied physics
Journal: Journal of applied physics


Applied physics letters
Journal: Applied physics letters


Ultramicroscopy
Journal: Ultramicroscopy


Thin solid films
Journal: Thin solid films


Physica status solidi (rrl)–rapid research letters
Journal: Physica status solidi (rrl)–rapid research letters


Thin solid films
Journal: Thin solid films


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Thin solid films
Journal: Thin solid films


Applied physics a
Journal: Applied physics a


Japanese journal of applied physics 51 (10s)
Journal: Japanese journal of applied physics


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Thin solid films
Journal: Thin solid films


Journal of applied crystallography
Journal: Journal of applied crystallography


Joule
Journal: Joule


Acs nano
Journal: Acs nano


Nano letters
Journal: Nano letters


Science
Journal: Science


Acs nano
Journal: Acs nano


Acs energy letters
Journal: Acs energy letters


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Acs nano
Journal: Acs nano


Journal of applied physics
Journal: Journal of applied physics


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Chemistry of materials
Journal: Chemistry of materials


Chemical communications
Journal: Chemical communications


Journal of vacuum science &technology b
Journal: Journal of vacuum science &technology b


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced materials
Journal: Advanced materials


Chemistry of materials
Journal: Chemistry of materials


Acs nano
Journal: Acs nano


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Chemical physics
Journal: Chemical physics


Acs nano
Journal: Acs nano


Scientific reports
Journal: Scientific reports


Acs materials letters
Journal: Acs materials letters


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Scientific reports
Journal: Scientific reports


Nanoscale
Journal: Nanoscale


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Acs energy letters
Journal: Acs energy letters


Acs nano
Journal: Acs nano


Joule
Journal: Joule


Acs nano
Journal: Acs nano


Nano letters
Journal: Nano letters


Science
Journal: Science


Acs nano
Journal: Acs nano


Acs energy letters
Journal: Acs energy letters


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Acs nano
Journal: Acs nano


Journal of applied physics
Journal: Journal of applied physics


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Chemistry of materials
Journal: Chemistry of materials


Chemical communications
Journal: Chemical communications


Journal of vacuum science &technology b
Journal: Journal of vacuum science &technology b


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced materials
Journal: Advanced materials


Chemistry of materials
Journal: Chemistry of materials


Acs nano
Journal: Acs nano


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Chemical physics
Journal: Chemical physics


Acs nano
Journal: Acs nano


Scientific reports
Journal: Scientific reports


Acs materials letters
Journal: Acs materials letters


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Scientific reports
Journal: Scientific reports


Nanoscale
Journal: Nanoscale


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Acs energy letters
Journal: Acs energy letters


Acs nano
Journal: Acs nano


Light: science &applications
Journal: Light: science &applications


Nature communications
Journal: Nature communications


Nature electronics
Journal: Nature electronics


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Small
Journal: Small


Science advances
Journal: Science advances


Advanced functional materials
Journal: Advanced functional materials


Scientific reports
Journal: Scientific reports


Advanced science
Journal: Advanced science


Advanced science
Journal: Advanced science


Light: science &applications
Journal: Light: science &applications


Advanced electronic materials
Journal: Advanced electronic materials


Light: science &applications
Journal: Light: science &applications


Nano research
Journal: Nano research


Infomat
Journal: Infomat


Advanced materials
Journal: Advanced materials


Applied physics letters
Journal: Applied physics letters


Nanotechnology
Journal: Nanotechnology


Advanced materials
Journal: Advanced materials


Optics express
Journal: Optics express


Ieee transactions on electron devices
Journal: Ieee transactions on electron devices


Ieee transactions on electron devices
Journal: Ieee transactions on electron devices


Infrared physics &technology
Journal: Infrared physics &technology


Lwt
Journal: Lwt


Advanced materials
Journal: Advanced materials


Physical review b
Journal: Physical review b


Advanced functional materials
Journal: Advanced functional materials


Nanoscale
Journal: Nanoscale


Small
Journal: Small


National science review
Journal: National science review


Optical materials express
Journal: Optical materials express


Applied physics letters
Journal: Applied physics letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Nature communications
Journal: Nature communications


Rsc advances
Journal: Rsc advances


Optics express
Journal: Optics express


Nano letters
Journal: Nano letters


Optics express
Journal: Optics express


Physical review b
Journal: Physical review b


Nanotechnology
Journal: Nanotechnology


Science advances
Journal: Science advances


Light: science &applications
Journal: Light: science &applications


Materials research express
Journal: Materials research express


Energy reports
Journal: Energy reports


Infrared physics &technology
Journal: Infrared physics &technology


Optics letters
Journal: Optics letters


Advanced optical materials
Journal: Advanced optical materials


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Infrared physics &technology
Journal: Infrared physics &technology


Infrared physics &technology
Journal: Infrared physics &technology


Advanced electronic materials
Journal: Advanced electronic materials


Applied physics letters
Journal: Applied physics letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Light: science &applications
Journal: Light: science &applications


Nature communications
Journal: Nature communications


Nature electronics
Journal: Nature electronics


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Small
Journal: Small


Science advances
Journal: Science advances


Advanced functional materials
Journal: Advanced functional materials


Scientific reports
Journal: Scientific reports


Advanced science
Journal: Advanced science


Advanced science
Journal: Advanced science


Light: science &applications
Journal: Light: science &applications


Advanced electronic materials
Journal: Advanced electronic materials


Light: science &applications
Journal: Light: science &applications


Nano research
Journal: Nano research


Infomat
Journal: Infomat


Advanced materials
Journal: Advanced materials


Applied physics letters
Journal: Applied physics letters


Nanotechnology
Journal: Nanotechnology


Advanced materials
Journal: Advanced materials


Optics express
Journal: Optics express


Ieee transactions on electron devices
Journal: Ieee transactions on electron devices


Ieee transactions on electron devices
Journal: Ieee transactions on electron devices


Infrared physics &technology
Journal: Infrared physics &technology


Lwt
Journal: Lwt


Advanced materials
Journal: Advanced materials


Physical review b
Journal: Physical review b


Advanced functional materials
Journal: Advanced functional materials


Nanoscale
Journal: Nanoscale


Small
Journal: Small


National science review
Journal: National science review


Optical materials express
Journal: Optical materials express


Applied physics letters
Journal: Applied physics letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Nature communications
Journal: Nature communications


Rsc advances
Journal: Rsc advances


Optics express
Journal: Optics express


Nano letters
Journal: Nano letters


Optics express
Journal: Optics express


Physical review b
Journal: Physical review b


Nanotechnology
Journal: Nanotechnology


Science advances
Journal: Science advances


Light: science &applications
Journal: Light: science &applications


Materials research express
Journal: Materials research express


Energy reports
Journal: Energy reports


Infrared physics &technology
Journal: Infrared physics &technology


Optics letters
Journal: Optics letters


Advanced optical materials
Journal: Advanced optical materials


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Infrared physics &technology
Journal: Infrared physics &technology


Infrared physics &technology
Journal: Infrared physics &technology


Advanced electronic materials
Journal: Advanced electronic materials


Applied physics letters
Journal: Applied physics letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Nature communications
Journal: Nature communications


Nature communications
Journal: Nature communications


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of the american ceramic society
Journal: Journal of the american ceramic society


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acta materialia
Journal: Acta materialia


Applied physics letters
Journal: Applied physics letters


Matter
Journal: Matter


Applied physics letters
Journal: Applied physics letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Journal of materials science &technology
Journal: Journal of materials science &technology


Materialia
Journal: Materialia


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Scripta materialia
Journal: Scripta materialia


Acs energy letters
Journal: Acs energy letters


Journal of materiomics
Journal: Journal of materiomics


Materials characterization
Journal: Materials characterization


Acta materialia
Journal: Acta materialia


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Scripta materialia
Journal: Scripta materialia


Chinese physics b
Journal: Chinese physics b


Scripta materialia
Journal: Scripta materialia


Scripta materialia
Journal: Scripta materialia


Physics letters a
Journal: Physics letters a


Physica status solidi (rrl)–rapid research letters
Journal: Physica status solidi (rrl)–rapid research letters


Journal of luminescence
Journal: Journal of luminescence


Ceramics international
Journal: Ceramics international


Rsc advances
Journal: Rsc advances


International journal of quantum chemistry
Journal: International journal of quantum chemistry


Ceramics international
Journal: Ceramics international


Physica b: condensed matter
Journal: Physica b: condensed matter


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Materials letters
Journal: Materials letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Inorganic chemistry
Journal: Inorganic chemistry


Ceramics international
Journal: Ceramics international


Scripta materialia
Journal: Scripta materialia


Chemical communications
Journal: Chemical communications


Rare metals
Journal: Rare metals


Royal society open science
Journal: Royal society open science


Journal of energy chemistry
Journal: Journal of energy chemistry


Scripta materialia
Journal: Scripta materialia


Acs energy letters
Journal: Acs energy letters


Scripta materialia
Journal: Scripta materialia


Journal of advanced ceramics
Journal: Journal of advanced ceramics


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Solar rrl
Journal: Solar rrl


Nature communications
Journal: Nature communications


Nature communications
Journal: Nature communications


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of the american ceramic society
Journal: Journal of the american ceramic society


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acta materialia
Journal: Acta materialia


Applied physics letters
Journal: Applied physics letters


Matter
Journal: Matter


Applied physics letters
Journal: Applied physics letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of alloys and compounds

The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemical physics impact
Journal: Chemical physics impact


The journal of physical chemistry b 126 (prof. kankan bhattacharyya …
Journal: The journal of physical chemistry b


Journal of luminescence
Journal: Journal of luminescence


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Israps bulletin 28 (1&2)
Journal: Israps bulletin


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Chemical physics letters 402 (4-6)
Journal: Chemical physics letters


The journal of physical chemistry a
Journal: The journal of physical chemistry a


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Phys. chem. chem. phys.
Journal: Phys. chem. chem. phys.


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Current science
Journal: Current science


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs catalysis 4
Journal: Acs catalysis


Angewandte chemie
Journal: Angewandte chemie


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Research on chemical intermediates
Journal: Research on chemical intermediates


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


The journal of physical chemistry b
Journal: The journal of physical chemistry b


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Rsc advances
Journal: Rsc advances


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nanoscale advances
Journal: Nanoscale advances


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemical communications
Journal: Chemical communications


Nanoscale
Journal: Nanoscale


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Carbohydrate research
Journal: Carbohydrate research


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Spectrochimica acta part a: molecular and biomolecular spectroscopy
Journal: Spectrochimica acta part a: molecular and biomolecular spectroscopy


Journal of the chinese chemical society
Journal: Journal of the chinese chemical society


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters 13
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemical physics impact
Journal: Chemical physics impact


The journal of physical chemistry b 126 (prof. kankan bhattacharyya …
Journal: The journal of physical chemistry b


Journal of luminescence
Journal: Journal of luminescence


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Israps bulletin 28 (1&2)
Journal: Israps bulletin


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Journal of the american chemical society
Journal: Journal of the american chemical society


Science advances
Journal: Science advances


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Advanced functional materials
Journal: Advanced functional materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Acs nano
Journal: Acs nano


Matter
Journal: Matter


Advanced functional materials
Journal: Advanced functional materials


The journal of organic chemistry
Journal: The journal of organic chemistry


Advanced functional materials
Journal: Advanced functional materials


Solar rrl
Journal: Solar rrl


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Advanced energy materials
Journal: Advanced energy materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs applied energy materials
Journal: Acs applied energy materials


Advanced functional materials
Journal: Advanced functional materials


Advanced materials
Journal: Advanced materials


Macromolecular rapid communications
Journal: Macromolecular rapid communications


Advanced energy materials
Journal: Advanced energy materials


Chemistry–a european journal
Journal: Chemistry–a european journal


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Sustainable energy &fuels
Journal: Sustainable energy &fuels


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Organic electronics
Journal: Organic electronics


Frontiers in chemistry
Journal: Frontiers in chemistry


Organic electronics
Journal: Organic electronics


Energy technology
Journal: Energy technology


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Acs applied energy materials
Journal: Acs applied energy materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of physics: materials
Journal: Journal of physics: materials


Acs energy letters
Journal: Acs energy letters


Nanoscale
Journal: Nanoscale


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Angewandte chemie
Journal: Angewandte chemie


Advanced energy materials
Journal: Advanced energy materials


Advanced energy materials
Journal: Advanced energy materials


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Journal of the american chemical society
Journal: Journal of the american chemical society


Science advances
Journal: Science advances


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Advanced functional materials
Journal: Advanced functional materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Acs nano
Journal: Acs nano


Matter
Journal: Matter


Advanced functional materials
Journal: Advanced functional materials


The journal of organic chemistry
Journal: The journal of organic chemistry


Advanced functional materials
Journal: Advanced functional materials


Solar rrl
Journal: Solar rrl


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Advanced energy materials
Journal: Advanced energy materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs applied energy materials
Journal: Acs applied energy materials


Advanced functional materials
Journal: Advanced functional materials


Advanced materials
Journal: Advanced materials


Macromolecular rapid communications
Journal: Macromolecular rapid communications


Advanced energy materials
Journal: Advanced energy materials


Chemistry–a european journal
Journal: Chemistry–a european journal


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Sustainable energy &fuels
Journal: Sustainable energy &fuels


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Organic electronics
Journal: Organic electronics


Frontiers in chemistry
Journal: Frontiers in chemistry


Organic electronics
Journal: Organic electronics


Energy technology
Journal: Energy technology


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Acs applied energy materials
Journal: Acs applied energy materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of physics: materials
Journal: Journal of physics: materials


Acs energy letters
Journal: Acs energy letters


Nanoscale
Journal: Nanoscale


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Angewandte chemie
Journal: Angewandte chemie


Advanced energy materials
Journal: Advanced energy materials


Advanced energy materials
Journal: Advanced energy materials


Nature physics
Journal: Nature physics


Nature communications
Journal: Nature communications


Physical review letters
Journal: Physical review letters


Nature photonics
Journal: Nature photonics


Applied physics letters
Journal: Applied physics letters


Physical review b
Journal: Physical review b


Applied physics letters
Journal: Applied physics letters


Phys. rev. b
Journal: Phys. rev. b


Review of scientific instruments
Journal: Review of scientific instruments


Crystengcomm
Journal: Crystengcomm


Acs applied nano materials
Journal: Acs applied nano materials


Rsc advances
Journal: Rsc advances


Crystengcomm
Journal: Crystengcomm


Applied physics letters
Journal: Applied physics letters


Scientific reports
Journal: Scientific reports


Crystengcomm
Journal: Crystengcomm


Journal of molecular structure
Journal: Journal of molecular structure


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Phys. rev. b
Journal: Phys. rev. b


Langmuir
Journal: Langmuir


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Crystal growth &design
Journal: Crystal growth &design


Physical review materials
Journal: Physical review materials


Crystengcomm
Journal: Crystengcomm


Ieee transactions on magnetics ( volume: 50
Journal: Ieee transactions on magnetics ( volume:


Journal of luminescence
Journal: Journal of luminescence


Acta physica polonica a
Journal: Acta physica polonica a


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Crystengcomm
Journal: Crystengcomm


Crystengcomm
Journal: Crystengcomm


Crystengcomm
Journal: Crystengcomm


Review of scientific instruments
Journal: Review of scientific instruments


Journal of molecular structure volume 1044
Journal: Journal of molecular structure volume


Nature photonics volume 7
Journal: Nature photonics volume


Journal of chemical crystallography 42
Journal: Journal of chemical crystallography


Appl. phys. lett.
Journal: Appl. phys. lett.


Phys. rev. lett.
Journal: Phys. rev. lett.


Appl. phys. lett.
Journal: Appl. phys. lett.


Advanced materials interfaces
Journal: Advanced materials interfaces


Chemistry of materials
Journal: Chemistry of materials


Scientific reports
Journal: Scientific reports


Mrs communications
Journal: Mrs communications


Sensors and actuators b: chemical
Journal: Sensors and actuators b: chemical


Talanta
Journal: Talanta


Renewable and sustainable energy reviews
Journal: Renewable and sustainable energy reviews


Sensors and actuators b: chemical
Journal: Sensors and actuators b: chemical


Journal of nanoparticle research
Journal: Journal of nanoparticle research


Rsc advances
Journal: Rsc advances


Int. res. j. pharm
Journal: Int. res. j. pharm


Optical materials
Journal: Optical materials


Rsc advances
Journal: Rsc advances


Talanta
Journal: Talanta


Physica e: low-dimensional systems and nanostructures
Journal: Physica e: low-dimensional systems and nanostructures


Chemistry of materials
Journal: Chemistry of materials


Applied physics letters
Journal: Applied physics letters


Applied physics a
Journal: Applied physics a


Journal of chemical information and modeling
Journal: Journal of chemical information and modeling


Journal of nanoparticle research
Journal: Journal of nanoparticle research


Journal of luminescence
Journal: Journal of luminescence


The journal of chemical physics
Journal: The journal of chemical physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of nanoparticle research
Journal: Journal of nanoparticle research


Journal of biomimetics
Journal: Journal of biomimetics


Applied physics a
Journal: Applied physics a


Applied physics a
Journal: Applied physics a


International journal of research in engineering and bioscience
Journal: International journal of research in engineering and bioscience


Intl. j. current microbiology appl. sci
Journal: Intl. j. current microbiology appl. sci


Chemistry of materials
Journal: Chemistry of materials


Current nanoscience
Journal: Current nanoscience


Int. j. electrochem. sci
Journal: Int. j. electrochem. sci


Advanced materials research
Journal: Advanced materials research


Indian journal of plant protection
Journal: Indian journal of plant protection


International journal research in engineering and bioscience
Journal: International journal research in engineering and bioscience


International research journal of pharmacy
Journal: International research journal of pharmacy


International journal of pharma and bio sciences
Journal: International journal of pharma and bio sciences


International journal of research in engineering and bioscience
Journal: International journal of research in engineering and bioscience


International journal of nanoscience and technology
Journal: International journal of nanoscience and technology


International journal of research in engineering and bioscience
Journal: International journal of research in engineering and bioscience


Plant disease research-ludhiana-
Journal: Plant disease research-ludhiana-


Nature communications
Journal: Nature communications


Acs energy letters
Journal: Acs energy letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature communications
Journal: Nature communications


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs energy letters
Journal: Acs energy letters


Advanced optical materials
Journal: Advanced optical materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced materials
Journal: Advanced materials


Acs photonics
Journal: Acs photonics


Light: science &applications
Journal: Light: science &applications


Science advances
Journal: Science advances


Applied physics letters
Journal: Applied physics letters


Acs energy letters
Journal: Acs energy letters


Chemsuschem
Journal: Chemsuschem


Optics express
Journal: Optics express


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs energy letters
Journal: Acs energy letters


Journal of vacuum science &technology b
Journal: Journal of vacuum science &technology b


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Advanced energy materials
Journal: Advanced energy materials


Nano letters
Journal: Nano letters


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Physical review applied
Journal: Physical review applied


Advanced functional materials
Journal: Advanced functional materials


Light
Journal: Light


Cleo: science and innovations
Journal: Cleo: science and innovations


Physical review letters
Journal: Physical review letters


Nature communications
Journal: Nature communications


Joule
Journal: Joule


Acs nano
Journal: Acs nano


Acs energy letters
Journal: Acs energy letters


Physical review letters
Journal: Physical review letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemistry of materials
Journal: Chemistry of materials


Acs nano
Journal: Acs nano


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced materials
Journal: Advanced materials


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Applied physics letters
Journal: Applied physics letters


Advanced energy materials
Journal: Advanced energy materials


Physical review b
Journal: Physical review b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review materials
Journal: Physical review materials


Crystengcomm
Journal: Crystengcomm


Physical review b
Journal: Physical review b


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced optical materials
Journal: Advanced optical materials


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemistry of materials
Journal: Chemistry of materials


Surface science
Journal: Surface science


Advanced materials
Journal: Advanced materials


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Microelectronic engineering
Journal: Microelectronic engineering


Physical review b
Journal: Physical review b


Physical review letters
Journal: Physical review letters


Nature communications
Journal: Nature communications


Joule
Journal: Joule


Acs nano
Journal: Acs nano


Acs energy letters
Journal: Acs energy letters


Physical review letters
Journal: Physical review letters


The journal of physical chemistry c

Advanced energy and sustainability research
Journal: Advanced energy and sustainability research


Inorganic chemistry
Journal: Inorganic chemistry


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


Crystengcomm
Journal: Crystengcomm


Food research international
Journal: Food research international


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


Polyhedron
Journal: Polyhedron


Chemistryselect
Journal: Chemistryselect


Journal of sol-gel science and technology
Journal: Journal of sol-gel science and technology


Materials advances
Journal: Materials advances


Spectrochimica acta part a: molecular and biomolecular spectroscopy
Journal: Spectrochimica acta part a: molecular and biomolecular spectroscopy


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


Advanced materials technologies
Journal: Advanced materials technologies


Energy technology
Journal: Energy technology


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Acs photonics
Journal: Acs photonics


Journal of the brazilian chemical society
Journal: Journal of the brazilian chemical society


Solar rrl
Journal: Solar rrl


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Photodiagnosis and photodynamic therapy
Journal: Photodiagnosis and photodynamic therapy


Acs materials letters
Journal: Acs materials letters


Advanced optical materials
Journal: Advanced optical materials


International journal of lakes and rivers
Journal: International journal of lakes and rivers


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Scientific reports
Journal: Scientific reports


New journal of chemistry
Journal: New journal of chemistry


Catalysis science &technology
Journal: Catalysis science &technology


Journal of applied physics
Journal: Journal of applied physics


Acs applied nano materials
Journal: Acs applied nano materials


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


Journal of molecular liquids
Journal: Journal of molecular liquids


Scripta materialia
Journal: Scripta materialia


Materials research express
Journal: Materials research express


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Chemistryselect
Journal: Chemistryselect


Advanced science
Journal: Advanced science


Macromolecular rapid communications
Journal: Macromolecular rapid communications


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Journal of chemical technology &biotechnology
Journal: Journal of chemical technology &biotechnology


Materials chemistry and physics
Journal: Materials chemistry and physics


Journal of applied polymer science
Journal: Journal of applied polymer science


Handbook of ecomaterials
Journal: Handbook of ecomaterials


Physica status solidi (a)
Journal: Physica status solidi (a)


Materials research bulletin
Journal: Materials research bulletin


Materials
Journal: Materials


Applied surface science
Journal: Applied surface science


Chemistryselect
Journal: Chemistryselect


Journal of environmental sciences
Journal: Journal of environmental sciences


Materials
Journal: Materials


Chemistryselect
Journal: Chemistryselect


Current nanoscience
Journal: Current nanoscience


Applied surface science
Journal: Applied surface science


Materials today communications
Journal: Materials today communications


Materials letters
Journal: Materials letters


Journal of materials science &technology
Journal: Journal of materials science &technology


Iscience
Journal: Iscience


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


한국진공학회 학술발표회초록집
Journal: 한국진공학회 학술발표회초록집


한국진공학회 학술발표회초록집
Journal: 한국진공학회 학술발표회초록집


Journal of energy chemistry
Journal: Journal of energy chemistry


Acs catalysis
Journal: Acs catalysis


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Chemistry of materials
Journal: Chemistry of materials


Acs applied nano materials
Journal: Acs applied nano materials


Chemistry of materials
Journal: Chemistry of materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Rsc advances
Journal: Rsc advances


Chemistry of materials
Journal: Chemistry of materials


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Processing and properties of advanced ceramics and composites v
Journal: Processing and properties of advanced ceramics and composites v


Journal of the australian ceramic society
Journal: Journal of the australian ceramic society


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Chemistry of materials
Journal: Chemistry of materials


Acs catal
Journal: Acs catal


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


American ceramic society bulletin
Journal: American ceramic society bulletin


Materials chemistry and physics
Journal: Materials chemistry and physics


Chemistry of materials
Journal: Chemistry of materials


Advanced energy materials
Journal: Advanced energy materials


Nano energy
Journal: Nano energy


Advanced functional materials
Journal: Advanced functional materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Advanced functional materials
Journal: Advanced functional materials


Advanced electronic materials
Journal: Advanced electronic materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Nano energy
Journal: Nano energy


Acs energy letters
Journal: Acs energy letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Solar rrl
Journal: Solar rrl


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced materials
Journal: Advanced materials


Acs applied energy materials
Journal: Acs applied energy materials


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs omega
Journal: Acs omega


Rsc advances
Journal: Rsc advances


Acs applied electronic materials
Journal: Acs applied electronic materials


Chemical society reviews
Journal: Chemical society reviews


Advanced functional materials
Journal: Advanced functional materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Emergent materials
Journal: Emergent materials


Applied physics letters
Journal: Applied physics letters


Nano energy
Journal: Nano energy


Organic electronics
Journal: Organic electronics


Advanced energy materials
Journal: Advanced energy materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Organic electronics
Journal: Organic electronics


Advanced functional materials
Journal: Advanced functional materials


Acs energy letters
Journal: Acs energy letters


International journal of molecular sciences
Journal: International journal of molecular sciences


Crystal growth &design
Journal: Crystal growth &design


Zeitschrift für kristallographie-crystalline materials
Journal: Zeitschrift für kristallographie-crystalline materials


Inorganic chemistry frontiers
Journal: Inorganic chemistry frontiers


Tetrahedron letters
Journal: Tetrahedron letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


European journal of organic chemistry
Journal: European journal of organic chemistry


Russian chemical bulletin
Journal: Russian chemical bulletin


Acs photonics
Journal: Acs photonics


New journal of chemistry
Journal: New journal of chemistry


Chemistry of heterocyclic compounds
Journal: Chemistry of heterocyclic compounds


Heteroatom chemistry
Journal: Heteroatom chemistry


Russian journal of general chemistry
Journal: Russian journal of general chemistry


Polymer science series b
Journal: Polymer science series b


Inorganic chemistry frontiers
Journal: Inorganic chemistry frontiers


Doklady chemistry
Journal: Doklady chemistry


Russian journal of general chemistry
Journal: Russian journal of general chemistry


Acs applied bio materials
Journal: Acs applied bio materials


Russian journal of general chemistry
Journal: Russian journal of general chemistry


Doklady chemistry
Journal: Doklady chemistry


Russian journal of general chemistry
Journal: Russian journal of general chemistry


Russian journal of general chemistry
Journal: Russian journal of general chemistry


European journal of organic chemistry
Journal: European journal of organic chemistry


Applied materials today
Journal: Applied materials today


Russian journal of general chemistry
Journal: Russian journal of general chemistry


Laser &photonics reviews
Journal: Laser &photonics reviews


Bulletin of the russian academy of sciences: physics
Journal: Bulletin of the russian academy of sciences: physics


International journal of molecular sciences
Journal: International journal of molecular sciences


International journal of molecular sciences
Journal: International journal of molecular sciences


Chemistryselect
Journal: Chemistryselect


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


New journal of chemistry
Journal: New journal of chemistry


Mendeleev
Journal: Mendeleev


Bulletin of the russian academy of sciences: physics
Journal: Bulletin of the russian academy of sciences: physics


Мезоскопические структуры в фундаментальных и прикладных исследованиях
Journal: Мезоскопические структуры в фундаментальных и прикладных исследованиях


Russian journal of general chemistry
Journal: Russian journal of general chemistry


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Nano energy
Journal: Nano energy


Nature communications
Journal: Nature communications


Acs energy letters
Journal: Acs energy letters


Advanced functional materials
Journal: Advanced functional materials


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Small
Journal: Small


Nature materials
Journal: Nature materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Acs energy letters
Journal: Acs energy letters


Advanced materials interfaces
Journal: Advanced materials interfaces


Organic electronics
Journal: Organic electronics


Acs applied energy materials
Journal: Acs applied energy materials


Advanced functional materials
Journal: Advanced functional materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Chemistry of materials
Journal: Chemistry of materials


Biomacromolecules
Journal: Biomacromolecules


Matter
Journal: Matter


Advanced electronic materials
Journal: Advanced electronic materials


Acs omega
Journal: Acs omega


Journal of materials chemistry b
Journal: Journal of materials chemistry b


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied bio materials
Journal: Acs applied bio materials


Journal of materials chemistry b
Journal: Journal of materials chemistry b


Advanced functional materials
Journal: Advanced functional materials


Advanced functional materials
Journal: Advanced functional materials


Advanced functional materials
Journal: Advanced functional materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Science advances
Journal: Science advances


Current medicinal chemistry
Journal: Current medicinal chemistry


Journal of magnetic resonance imaging
Journal: Journal of magnetic resonance imaging


Bioconjugate chemistry
Journal: Bioconjugate chemistry


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Advanced functional materials
Journal: Advanced functional materials


Macromolecular rapid communications
Journal: Macromolecular rapid communications


Journal of materials chemistry b
Journal: Journal of materials chemistry b


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Engineering
Journal: Engineering


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Nano energy
Journal: Nano energy


Nature communications
Journal: Nature communications


Acs energy letters
Journal: Acs energy letters


Advanced functional materials
Journal: Advanced functional materials


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Small
Journal: Small


Nature materials
Journal: Nature materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Acs energy letters
Journal: Acs energy letters


Advanced materials interfaces
Journal: Advanced materials interfaces


Organic electronics
Journal: Organic electronics


Acs applied energy materials
Journal: Acs applied energy materials


Advanced functional materials
Journal: Advanced functional materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Chemistry of materials
Journal: Chemistry of materials


Biomacromolecules
Journal: Biomacromolecules


Matter
Journal: Matter


Advanced electronic materials
Journal: Advanced electronic materials


Acs omega
Journal: Acs omega


Journal of materials chemistry b
Journal: Journal of materials chemistry b


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied bio materials
Journal: Acs applied bio materials


Journal of materials chemistry b
Journal: Journal of materials chemistry b


Advanced functional materials
Journal: Advanced functional materials


Advanced functional materials
Journal: Advanced functional materials


Advanced functional materials
Journal: Advanced functional materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Science advances
Journal: Science advances


Current medicinal chemistry
Journal: Current medicinal chemistry


Journal of magnetic resonance imaging
Journal: Journal of magnetic resonance imaging


Bioconjugate chemistry
Journal: Bioconjugate chemistry


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Advanced functional materials
Journal: Advanced functional materials


Macromolecular rapid communications
Journal: Macromolecular rapid communications


Journal of materials chemistry b
Journal: Journal of materials chemistry b


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Engineering
Journal: Engineering


Advanced materials
Journal: Advanced materials


Materials horizons
Journal: Materials horizons


Acs energy letters
Journal: Acs energy letters


Scientific reports
Journal: Scientific reports


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of chemical physics
Journal: The journal of chemical physics


Advanced energy materials
Journal: Advanced energy materials


Solar rrl
Journal: Solar rrl


Communications materials
Journal: Communications materials


Advanced electronic materials
Journal: Advanced electronic materials


Acs applied electronic materials
Journal: Acs applied electronic materials


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Frontiers in energy research
Journal: Frontiers in energy research


Advanced materials
Journal: Advanced materials


Solar rrl
Journal: Solar rrl


Acs energy letters
Journal: Acs energy letters


The journal of chemical physics
Journal: The journal of chemical physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs energy letters
Journal: Acs energy letters


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Advanced energy materials
Journal: Advanced energy materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Acs applied energy materials
Journal: Acs applied energy materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Frontiers in electronics
Journal: Frontiers in electronics


Materials horizons
Journal: Materials horizons


Acs energy letters
Journal: Acs energy letters


Scientific reports
Journal: Scientific reports


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of chemical physics
Journal: The journal of chemical physics


Advanced energy materials
Journal: Advanced energy materials


Solar rrl
Journal: Solar rrl


Communications materials
Journal: Communications materials


Advanced electronic materials
Journal: Advanced electronic materials


Acs applied electronic materials
Journal: Acs applied electronic materials


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Frontiers in energy research
Journal: Frontiers in energy research


Advanced materials
Journal: Advanced materials


Solar rrl
Journal: Solar rrl


Acs energy letters
Journal: Acs energy letters


The journal of chemical physics
Journal: The journal of chemical physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs energy letters
Journal: Acs energy letters


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Advanced energy materials
Journal: Advanced energy materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Acs applied energy materials
Journal: Acs applied energy materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Frontiers in electronics
Journal: Frontiers in electronics


Algorithms
Journal: Algorithms


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Advanced theory and simulations
Journal: Advanced theory and simulations


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters

Ieee transactions on electron devices
Journal: Ieee transactions on electron devices


Applied physics letters
Journal: Applied physics letters


Materials
Journal: Materials


Optics for solar energy
Journal: Optics for solar energy


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Solar rrl
Journal: Solar rrl


Advanced electronic materials
Journal: Advanced electronic materials


Applied physics letters
Journal: Applied physics letters


Organic electronics
Journal: Organic electronics


Organic electronics
Journal: Organic electronics


Npj flexible electronics
Journal: Npj flexible electronics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Organic electronics
Journal: Organic electronics


Synthetic metals
Journal: Synthetic metals


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Organic electronics
Journal: Organic electronics


Journal of power sources
Journal: Journal of power sources


Journal of energy chemistry
Journal: Journal of energy chemistry


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Sci. china mater
Journal: Sci. china mater


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Organic electronics
Journal: Organic electronics


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of renewable and sustainable energy
Journal: Journal of renewable and sustainable energy


Physica b: condensed matter
Journal: Physica b: condensed matter


Interdisciplinary materials
Journal: Interdisciplinary materials


Matter
Journal: Matter


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Applied physics a
Journal: Applied physics a


Energychem
Journal: Energychem


Journal of hazardous materials
Journal: Journal of hazardous materials


Nanoscale
Journal: Nanoscale


J. mater. chem
Journal: J. mater. chem


Chemical communications
Journal: Chemical communications


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Materials horizons
Journal: Materials horizons


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Rsc advances
Journal: Rsc advances


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of the society for information display
Journal: Journal of the society for information display


Faraday discussions
Journal: Faraday discussions


Nature communications
Journal: Nature communications


Nature communications
Journal: Nature communications


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Npj computational materials
Journal: Npj computational materials


Chemical communications
Journal: Chemical communications


Physical review b
Journal: Physical review b


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Molecular systems design &engineering
Journal: Molecular systems design &engineering


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced functional materials
Journal: Advanced functional materials


Advanced theory and simulations
Journal: Advanced theory and simulations


Materials advances
Journal: Materials advances


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Chemistry of materials
Journal: Chemistry of materials


Acs applied nano materials
Journal: Acs applied nano materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Npj computational materials
Journal: Npj computational materials


Acs applied energy materials
Journal: Acs applied energy materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry b
Journal: The journal of physical chemistry b


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Small methods
Journal: Small methods


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Chemical science
Journal: Chemical science


Advanced theory and simulations
Journal: Advanced theory and simulations


Journal of the american chemical society
Journal: Journal of the american chemical society


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Chemistry of materials
Journal: Chemistry of materials


Acs nano
Journal: Acs nano


Chemistry of materials
Journal: Chemistry of materials


Chemical communications
Journal: Chemical communications


Journal of materials chemistry a
Journal: Journal of materials chemistry a


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Chemistry of materials
Journal: Chemistry of materials


Journal of solid state chemistry
Journal: Journal of solid state chemistry


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemistry of materials
Journal: Chemistry of materials


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Chemical communications
Journal: Chemical communications


Applied energy
Journal: Applied energy


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Nanotechnology
Journal: Nanotechnology


Chemsuschem
Journal: Chemsuschem


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Applied energy
Journal: Applied energy


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Rsc advances
Journal: Rsc advances


Advanced functional materials
Journal: Advanced functional materials


Energy &environmental science
Journal: Energy &environmental science


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of materiomics
Journal: Journal of materiomics


Nanophotonics
Journal: Nanophotonics


Solar rrl
Journal: Solar rrl


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


New journal of chemistry
Journal: New journal of chemistry


Dalton transactions
Journal: Dalton transactions


Rsc advances
Journal: Rsc advances


Chemistryselect
Journal: Chemistryselect


Journal of energy chemistry
Journal: Journal of energy chemistry


Rsc advances
Journal: Rsc advances


Rsc advances
Journal: Rsc advances


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Materials science in semiconductor processing
Journal: Materials science in semiconductor processing


Rsc advances
Journal: Rsc advances


Rsc advances
Journal: Rsc advances


Dalton transactions
Journal: Dalton transactions


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Rsc advances
Journal: Rsc advances


Acs applied energy materials
Journal: Acs applied energy materials


Chemistry of materials
Journal: Chemistry of materials


Advanced optical materials
Journal: Advanced optical materials


Crystengcomm
Journal: Crystengcomm


Chemistry of materials
Journal: Chemistry of materials


Journal of semiconductors
Journal: Journal of semiconductors


Acs central science
Journal: Acs central science


Energy technology
Journal: Energy technology


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Rsc advances
Journal: Rsc advances


Advanced functional materials
Journal: Advanced functional materials


Energy &environmental science
Journal: Energy &environmental science


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of materiomics
Journal: Journal of materiomics


Nanophotonics
Journal: Nanophotonics


Solar rrl
Journal: Solar rrl


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


New journal of chemistry
Journal: New journal of chemistry


Dalton transactions
Journal: Dalton transactions


Rsc advances
Journal: Rsc advances


Chemistryselect
Journal: Chemistryselect


Journal of energy chemistry
Journal: Journal of energy chemistry


Rsc advances
Journal: Rsc advances


Rsc advances
Journal: Rsc advances


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Materials science in semiconductor processing
Journal: Materials science in semiconductor processing


Rsc advances
Journal: Rsc advances


Rsc advances
Journal: Rsc advances


Dalton transactions
Journal: Dalton transactions


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Rsc advances
Journal: Rsc advances


Acs applied energy materials
Journal: Acs applied energy materials


Chemistry of materials
Journal: Chemistry of materials


Advanced optical materials
Journal: Advanced optical materials


Crystengcomm
Journal: Crystengcomm


Chemistry of materials
Journal: Chemistry of materials


Journal of semiconductors
Journal: Journal of semiconductors


Acs central science
Journal: Acs central science


Energy technology
Journal: Energy technology


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Applied physics letters
Journal: Applied physics letters


Applied surface science
Journal: Applied surface science


Beilstein journal of nanotechnology
Journal: Beilstein journal of nanotechnology


Beilstein journal of nanotechnology
Journal: Beilstein journal of nanotechnology


Thin solid films
Journal: Thin solid films


Beilstein journal of nanotechnology
Journal: Beilstein journal of nanotechnology


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Applied surface science
Journal: Applied surface science


Thin solid films
Journal: Thin solid films


Vacuum
Journal: Vacuum


Macromolecular bioscience
Journal: Macromolecular bioscience


Applied surface science
Journal: Applied surface science


Journal of electrical engineering
Journal: Journal of electrical engineering


Appl. surf. sci.
Journal: Appl. surf. sci.


Phys. status solidi a
Journal: Phys. status solidi a


Physica status solidi (a)
Journal: Physica status solidi (a)


Int. j. electrochem. sci
Journal: Int. j. electrochem. sci


Applied surface science
Journal: Applied surface science


Materials
Journal: Materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Chemosensors
Journal: Chemosensors


한국진공학회 학술발표회초록집
Journal: 한국진공학회 학술발표회초록집


Acta universitatis carolinae. mathematica et physica
Journal: Acta universitatis carolinae. mathematica et physica


Nature energy
Journal: Nature energy


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Inorganic chemistry
Journal: Inorganic chemistry


Inorganic chemistry
Journal: Inorganic chemistry


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Inorganic chemistry
Journal: Inorganic chemistry


Small methods
Journal: Small methods


Materials advances
Journal: Materials advances


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


New journal of chemistry
Journal: New journal of chemistry


Inorganic chemistry frontiers
Journal: Inorganic chemistry frontiers


Polyhedron
Journal: Polyhedron


Small
Journal: Small


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Molecules
Journal: Molecules


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Polyhedron
Journal: Polyhedron


Iscience
Journal: Iscience


Spectrochimica acta part a: molecular and biomolecular spectroscopy
Journal: Spectrochimica acta part a: molecular and biomolecular spectroscopy


Journal of solid state chemistry
Journal: Journal of solid state chemistry


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs materials au
Journal: Acs materials au


Chemical communications
Journal: Chemical communications


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Rsc advances
Journal: Rsc advances


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Chemical physics letters 506 (4-6)
Journal: Chemical physics letters


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


Chemphyschem
Journal: Chemphyschem


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Nucleic acids research
Journal: Nucleic acids research


Carbon
Journal: Carbon


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


Scientific reports
Journal: Scientific reports


Journal of molecular structure
Journal: Journal of molecular structure


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Faraday discussions
Journal: Faraday discussions


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of optics
Journal: Journal of optics


Faraday discussions
Journal: Faraday discussions


Journal of luminescence
Journal: Journal of luminescence


Journal of applied physics
Journal: Journal of applied physics


Journal of biological physics
Journal: Journal of biological physics


Biophysical journal
Journal: Biophysical journal


Biophysical journal
Journal: Biophysical journal


Faraday discussions
Journal: Faraday discussions


Faraday discussions
Journal: Faraday discussions


Methods and applications in fluorescence
Journal: Methods and applications in fluorescence


Biophysical journal
Journal: Biophysical journal


Solar energy
Journal: Solar energy


Journal of applied physics
Journal: Journal of applied physics


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Solar energy
Journal: Solar energy


Journal of applied physics
Journal: Journal of applied physics


Physical review b
Journal: Physical review b


International journal in multidisciplinary studies (ijms)
Journal: International journal in multidisciplinary studies (ijms)


International journal of multidisciplinary studies
Journal: International journal of multidisciplinary studies


Journal of the national science foundation of sri lanka
Journal: Journal of the national science foundation of sri lanka


Nature energy
Journal: Nature energy


J. am. chem. soc
Journal: J. am. chem. soc


Journal of the american chemical society
Journal: Journal of the american chemical society


Angewandte chemie international edition
Journal: Angewandte chemie international edition


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Phys. rev. b
Journal: Phys. rev. b


Chemical science
Journal: Chemical science


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Green chemistry
Journal: Green chemistry


Chemical science
Journal: Chemical science


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Phys. rev. materials
Journal: Phys. rev. materials


Physical review b
Journal: Physical review b


Chemical science
Journal: Chemical science


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Physical review b
Journal: Physical review b


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Physical review b
Journal: Physical review b


Acs energy letters
Journal: Acs energy letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


The journal of chemical physics
Journal: The journal of chemical physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry a
Journal: The journal of physical chemistry a


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of physics: energy
Journal: Journal of physics: energy


Frontiers in chemistry
Journal: Frontiers in chemistry


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of the american chemical society
Journal: Journal of the american chemical society


The european physical journal d
Journal: The european physical journal d


Nature energy
Journal: Nature energy


J. am. chem. soc
Journal: J. am. chem. soc


Journal of the american chemical society
Journal: Journal of the american chemical society


Angewandte chemie international edition
Journal: Angewandte chemie international edition


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Phys. rev. b
Journal: Phys. rev. b


Chemical science
Journal: Chemical science


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Green chemistry
Journal: Green chemistry


Chemical science
Journal: Chemical science


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Phys. rev. materials
Journal: Phys. rev. materials


Physical review b
Journal: Physical review b


Chemical science
Journal: Chemical science


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Physical review b
Journal: Physical review b


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Physical review b
Journal: Physical review b


Acs energy letters
Journal: Acs energy letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


The journal of chemical physics
Journal: The journal of chemical physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry a
Journal: The journal of physical chemistry a


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of physics: energy
Journal: Journal of physics: energy


Frontiers in chemistry
Journal: Frontiers in chemistry


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of the american chemical society
Journal: Journal of the american chemical society


The european physical journal d
Journal: The european physical journal d


Scientific reports
Journal: Scientific reports


Rsc advances
Journal: Rsc advances


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering



The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Physical review b
Journal: Physical review b


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs nano
Journal: Acs nano


Journal of the american chemical society
Journal: Journal of the american chemical society


Computer physics communications
Journal: Computer physics communications


Acs energy letters
Journal: Acs energy letters


Acs nano
Journal: Acs nano


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of power sources
Journal: Journal of power sources


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of power sources
Journal: Journal of power sources


Journal of the american chemical society
Journal: Journal of the american chemical society


Electrochimica acta
Journal: Electrochimica acta


Electrochimica acta
Journal: Electrochimica acta


Materials characterization
Journal: Materials characterization


The journal of chemical physics
Journal: The journal of chemical physics


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Materials
Journal: Materials


Solar energy
Journal: Solar energy


Materials characterization
Journal: Materials characterization


Chemical science
Journal: Chemical science


The european physical journal c
Journal: The european physical journal c


Rare metals
Journal: Rare metals


Journal of materials chemistry c
Journal: Journal of materials chemistry c


北京航空航天大学学报
Journal: 北京航空航天大学学报


Rare metals
Journal: Rare metals


Advanced energy materials
Journal: Advanced energy materials


Nature energy
Journal: Nature energy


Chemical communications
Journal: Chemical communications


Acs energy letters
Journal: Acs energy letters


Zeitschrift für anorganische und allgemeine chemie
Journal: Zeitschrift für anorganische und allgemeine chemie


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Journal of photochemistry and photobiology b: biology
Journal: Journal of photochemistry and photobiology b: biology


Ceramics international
Journal: Ceramics international


Rsc advances
Journal: Rsc advances


Chemistryselect
Journal: Chemistryselect


Scientific reports
Journal: Scientific reports


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Materials science-poland
Journal: Materials science-poland


Bulletin of the chemical society of ethiopia
Journal: Bulletin of the chemical society of ethiopia


Solar rrl
Journal: Solar rrl


Rev. chim
Journal: Rev. chim


Water
Journal: Water


Australian journal of chemistry
Journal: Australian journal of chemistry


Phys. chem. chem. phys
Journal: Phys. chem. chem. phys


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Rev. chim
Journal: Rev. chim


Materials research express
Journal: Materials research express


Ceramics international
Journal: Ceramics international


Ceramics international
Journal: Ceramics international


Journal of molecular structure
Journal: Journal of molecular structure


Journal of superconductivity and novel magnetism
Journal: Journal of superconductivity and novel magnetism


Bulletin of materials science
Journal: Bulletin of materials science


Journal of superconductivity and novel magnetism
Journal: Journal of superconductivity and novel magnetism


Journal of superconductivity and novel magnetism
Journal: Journal of superconductivity and novel magnetism


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Journal of molecular structure
Journal: Journal of molecular structure


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Journal of superconductivity and novel magnetism
Journal: Journal of superconductivity and novel magnetism


International journal of hydrogen energy
Journal: International journal of hydrogen energy


Journal of superconductivity and novel magnetism
Journal: Journal of superconductivity and novel magnetism


Cumhuriyet science journal
Journal: Cumhuriyet science journal


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Journal of optoelectronics and advanced materials 15 (3-4)
Journal: Journal of optoelectronics and advanced materials


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Düzce üniversitesi bilim ve teknoloji dergisi
Journal: Düzce üniversitesi bilim ve teknoloji dergisi


Journal of thermal analysis and calorimetry
Journal: Journal of thermal analysis and calorimetry


Adıyaman university journal of science
Journal: Adıyaman university journal of science


Çukurova university journal of the faculty of engineering and architecture …
Journal: Çukurova university journal of the faculty of engineering and architecture …


Journal of superconductivity and novel magnetism
Journal: Journal of superconductivity and novel magnetism


Acs nano
Journal: Acs nano


Physical review b
Journal: Physical review b


Acs photonics
Journal: Acs photonics


New journal of physics
Journal: New journal of physics


Carbon
Journal: Carbon


Applied physics letters
Journal: Applied physics letters


Physical review letters
Journal: Physical review letters


Communications materials
Journal: Communications materials


Physical review materials
Journal: Physical review materials


Nanotechnology
Journal: Nanotechnology


Rsc advances
Journal: Rsc advances


Applied surface science
Journal: Applied surface science


Physical review b
Journal: Physical review b


Physical review materials
Journal: Physical review materials


Physical review materials
Journal: Physical review materials


Acta crystallographica a-foundation and advances 77
Journal: Acta crystallographica a-foundation and advances


Physical review materials
Journal: Physical review materials


Acs nano
Journal: Acs nano


Advanced energy materials
Journal: Advanced energy materials


Advanced materials
Journal: Advanced materials


Energy &environmental science
Journal: Energy &environmental science


Advanced functional materials
Journal: Advanced functional materials


Advanced functional materials
Journal: Advanced functional materials


Advanced functional materials
Journal: Advanced functional materials


Acs nano
Journal: Acs nano


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced functional materials
Journal: Advanced functional materials


Chemical communications
Journal: Chemical communications


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Nano energy
Journal: Nano energy


Advanced functional materials
Journal: Advanced functional materials


Advanced functional materials
Journal: Advanced functional materials


Nanoscale
Journal: Nanoscale


Rsc advances
Journal: Rsc advances


Nanoscale
Journal: Nanoscale


Vacuum
Journal: Vacuum


Advanced functional materials
Journal: Advanced functional materials


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Acs nano
Journal: Acs nano


Advanced energy materials
Journal: Advanced energy materials


Advanced materials
Journal: Advanced materials


Energy &environmental science
Journal: Energy &environmental science


Advanced functional materials
Journal: Advanced functional materials


Advanced functional materials
Journal: Advanced functional materials


Advanced functional materials
Journal: Advanced functional materials


Acs nano
Journal: Acs nano


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced functional materials
Journal: Advanced functional materials


Chemical communications
Journal: Chemical communications


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Nano energy
Journal: Nano energy


Advanced functional materials
Journal: Advanced functional materials


Advanced functional materials
Journal: Advanced functional materials


Nanoscale
Journal: Nanoscale


Rsc advances
Journal: Rsc advances


Nanoscale
Journal: Nanoscale


Vacuum
Journal: Vacuum


Advanced functional materials
Journal: Advanced functional materials


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Acs energy letters
Journal: Acs energy letters


Nanoscale
Journal: Nanoscale


Nanoscale
Journal: Nanoscale


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Nanoscale
Journal: Nanoscale


Acs materials letters
Journal: Acs materials letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nanoscale
Journal: Nanoscale


Nanoscale
Journal: Nanoscale


Acs energy letters
Journal: Acs energy letters


Dalton transactions
Journal: Dalton transactions


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of porphyrins and phthalocyanines 20 (01n04)
Journal: Journal of porphyrins and phthalocyanines


Acs photonics
Journal: Acs photonics


Acs omega
Journal: Acs omega


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Physical chemistry of semiconductor materials and interfaces xxi
Journal: Physical chemistry of semiconductor materials and interfaces xxi


Acs energy letters
Journal: Acs energy letters


Nanoscale
Journal: Nanoscale


Nanoscale
Journal: Nanoscale


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Nanoscale
Journal: Nanoscale


Acs materials letters
Journal: Acs materials letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nanoscale
Journal: Nanoscale


Nanoscale
Journal: Nanoscale


Acs energy letters
Journal: Acs energy letters


Dalton transactions
Journal: Dalton transactions


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of porphyrins and phthalocyanines 20 (01n04)
Journal: Journal of porphyrins and phthalocyanines


Acs photonics
Journal: Acs photonics


Acs omega
Journal: Acs omega


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Physical chemistry of semiconductor materials and interfaces xxi
Journal: Physical chemistry of semiconductor materials and interfaces xxi


Science
Journal: Science


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Applied physics letters
Journal: Applied physics letters


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature energy
Journal: Nature energy


Advanced energy materials
Journal: Advanced energy materials


Nature communications
Journal: Nature communications


Nature communications
Journal: Nature communications


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of chemical physics
Journal: The journal of chemical physics


Advanced functional materials
Journal: Advanced functional materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced energy materials
Journal: Advanced energy materials


Advanced materials
Journal: Advanced materials


Advanced energy materials
Journal: Advanced energy materials


Advanced energy materials
Journal: Advanced energy materials


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Advanced energy materials
Journal: Advanced energy materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Polymer chemistry
Journal: Polymer chemistry


Advanced energy materials
Journal: Advanced energy materials


Nature communications
Journal: Nature communications


Advanced functional materials
Journal: Advanced functional materials


Sensors and actuators b: chemical
Journal: Sensors and actuators b: chemical


Nanotechnology
Journal: Nanotechnology


Nanotechnology
Journal: Nanotechnology


Nanotechnology
Journal: Nanotechnology


Nano energy
Journal: Nano energy


Acs applied nano materials
Journal: Acs applied nano materials


Journal of colloid and interface science
Journal: Journal of colloid and interface science


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Journal of raman spectroscopy
Journal: Journal of raman spectroscopy


Applied physics letters
Journal: Applied physics letters


Npg asia materials
Journal: Npg asia materials


Rsc advances
Journal: Rsc advances


Sensors and actuators b: chemical
Journal: Sensors and actuators b: chemical


Npg asia materials
Journal: Npg asia materials


Advanced science letters
Journal: Advanced science letters


Sci. adv. today
Journal: Sci. adv. today


Advanced functional materials
Journal: Advanced functional materials


Angewandte chemie
Journal: Angewandte chemie


Physical review letters
Journal: Physical review letters


Physical review b
Journal: Physical review b


Advanced functional materials
Journal: Advanced functional materials


Physical review letters
Journal: Physical review letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Advanced materials
Journal: Advanced materials


Physical review letters
Journal: Physical review letters


Inorganic chemistry
Journal: Inorganic chemistry


Solid state ionics
Journal: Solid state ionics


Acs omega
Journal: Acs omega


Rsc advances
Journal: Rsc advances


Digital discovery
Journal: Digital discovery


Physical review materials
Journal: Physical review materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review b
Journal: Physical review b


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Dalton transactions
Journal: Dalton transactions


Physical review b
Journal: Physical review b


Catalysis science &technology
Journal: Catalysis science &technology


Physical review b
Journal: Physical review b


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of catalysis
Journal: Journal of catalysis


Computational materials science
Journal: Computational materials science


Chemcatchem
Journal: Chemcatchem


Organometallics
Journal: Organometallics


Physical review b
Journal: Physical review b


Inorganic chemistry
Journal: Inorganic chemistry


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Rsc advances
Journal: Rsc advances


Computational materials science
Journal: Computational materials science


Applied surface science
Journal: Applied surface science


Solid state sciences
Journal: Solid state sciences


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Journal of molecular graphics and modelling
Journal: Journal of molecular graphics and modelling


Dalton transactions
Journal: Dalton transactions


Chemical physics letters
Journal: Chemical physics letters


Ultrasonics sonochemistry
Journal: Ultrasonics sonochemistry


Ceramics international
Journal: Ceramics international


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Journal of electronic materials
Journal: Journal of electronic materials


Ceramics international
Journal: Ceramics international


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Chemical engineering journal
Journal: Chemical engineering journal


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Nanotechnology
Journal: Nanotechnology


Materials science in semiconductor processing
Journal: Materials science in semiconductor processing


Chemical engineering journal
Journal: Chemical engineering journal


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Sn applied sciences
Journal: Sn applied sciences


Ceramics international
Journal: Ceramics international


Bulletin of materials science
Journal: Bulletin of materials science


Journal of porous materials
Journal: Journal of porous materials


Colloids and surfaces b: biointerfaces
Journal: Colloids and surfaces b: biointerfaces


Materials science in semiconductor processing
Journal: Materials science in semiconductor processing


Ionics
Journal: Ionics


Journal of colloid and interface science
Journal: Journal of colloid and interface science


Applied physics a
Journal: Applied physics a


Scientific reports
Journal: Scientific reports


Small
Journal: Small


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Scientific reports
Journal: Scientific reports


Advanced sustainable systems
Journal: Advanced sustainable systems


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of the korean physical society
Journal: Journal of the korean physical society


Acs nano
Journal: Acs nano


Advanced energy materials
Journal: Advanced energy materials


Acs energy letters
Journal: Acs energy letters


Journal of the korean physical society
Journal: Journal of the korean physical society


Journal of the korean physical society
Journal: Journal of the korean physical society


Advanced energy materials
Journal: Advanced energy materials



Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Chemistry of materials
Journal: Chemistry of materials


Acs nano
Journal: Acs nano


Journal of physics: energy
Journal: Journal of physics: energy


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Frontiers in chemistry
Journal: Frontiers in chemistry


Faraday discussions
Journal: Faraday discussions


Ecs transactions
Journal: Ecs transactions


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Small
Journal: Small


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Journal of physics: energy
Journal: Journal of physics: energy


Nwo chains
Journal: Nwo chains


Small
Journal: Small


Semiconductor science and technology
Journal: Semiconductor science and technology


Physica b: condensed matter
Journal: Physica b: condensed matter


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Materials research bulletin
Journal: Materials research bulletin


Solid state sciences
Journal: Solid state sciences


Materials letters
Journal: Materials letters


Scientia
Journal: Scientia


Materials science in semiconductor processing
Journal: Materials science in semiconductor processing


Optik
Journal: Optik


Materials chemistry and physics
Journal: Materials chemistry and physics


Optical materials
Journal: Optical materials


Rational discourse
Journal: Rational discourse


Advanced energy materials
Journal: Advanced energy materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Nano letters
Journal: Nano letters


Chemistry of materials
Journal: Chemistry of materials


Energy mater
Journal: Energy mater


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


European journal of inorganic chemistry
Journal: European journal of inorganic chemistry


Chemistry of materials
Journal: Chemistry of materials


J. am. chem. soc
Journal: J. am. chem. soc


Chemistry of materials
Journal: Chemistry of materials


Journal of materials chemistry
Journal: Journal of materials chemistry


Chemistry of materials
Journal: Chemistry of materials


Advanced energy materials
Journal: Advanced energy materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Nano letters
Journal: Nano letters


Chemistry of materials
Journal: Chemistry of materials


Energy mater
Journal: Energy mater


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


European journal of inorganic chemistry
Journal: European journal of inorganic chemistry


Chemistry of materials
Journal: Chemistry of materials


J. am. chem. soc
Journal: J. am. chem. soc


Chemistry of materials
Journal: Chemistry of materials


Journal of materials chemistry
Journal: Journal of materials chemistry


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Science
Journal: Science


Science advances
Journal: Science advances


Nature communications
Journal: Nature communications


Acs nano
Journal: Acs nano


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nature communications
Journal: Nature communications


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced functional materials
Journal: Advanced functional materials


Nature materials
Journal: Nature materials


Organometallics
Journal: Organometallics


Acs nano
Journal: Acs nano


Science
Journal: Science


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Science
Journal: Science


Science advances
Journal: Science advances


Nature communications
Journal: Nature communications


Acs nano
Journal: Acs nano


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nature communications
Journal: Nature communications


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced functional materials
Journal: Advanced functional materials


Nature materials
Journal: Nature materials


Organometallics
Journal: Organometallics


Acs nano
Journal: Acs nano


Science
Journal: Science


Science
Journal: Science


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Proceedings of the national academy of sciences
Journal: Proceedings of the national academy of sciences


Acs catalysis
Journal: Acs catalysis


Advanced functional materials
Journal: Advanced functional materials


Acs applied energy materials
Journal: Acs applied energy materials


Journal of chemical theory and computation
Journal: Journal of chemical theory and computation


The journal of chemical physics
Journal: The journal of chemical physics


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of chemical theory and computation
Journal: Journal of chemical theory and computation


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Chemical science
Journal: Chemical science


Molecular systems design &engineering
Journal: Molecular systems design &engineering


Macromolecules
Journal: Macromolecules


Trac trends in analytical chemistry
Journal: Trac trends in analytical chemistry


Chemosphere
Journal: Chemosphere


Chemical research in chinese universities
Journal: Chemical research in chinese universities


Journal of materials science
Journal: Journal of materials science


Macromolecular rapid communications
Journal: Macromolecular rapid communications


International journal of polymer analysis and characterization
Journal: International journal of polymer analysis and characterization


Inorganic chemistry communications
Journal: Inorganic chemistry communications


Inorganic chemistry communications
Journal: Inorganic chemistry communications


Energy from waste: production and storage
Journal: Energy from waste: production and storage


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Physica b: condensed matter
Journal: Physica b: condensed matter


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Ceramics international
Journal: Ceramics international


Ceramics international
Journal: Ceramics international


Journal of molecular structure
Journal: Journal of molecular structure


Physica b: condensed matter
Journal: Physica b: condensed matter


Ceramics international
Journal: Ceramics international


Ceramics international
Journal: Ceramics international


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Journal of superconductivity and novel magnetism
Journal: Journal of superconductivity and novel magnetism


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Ceramics international
Journal: Ceramics international


Materials chemistry and physics
Journal: Materials chemistry and physics


Ferroelectrics
Journal: Ferroelectrics


Nano today
Journal: Nano today


Acs applied energy materials
Journal: Acs applied energy materials


Acs applied nano materials
Journal: Acs applied nano materials


Journal of physics and chemistry of solids
Journal: Journal of physics and chemistry of solids


Materials chemistry and physics
Journal: Materials chemistry and physics


Journal of nanoscience and nanotechnology
Journal: Journal of nanoscience and nanotechnology


Journal of sol-gel science and technology
Journal: Journal of sol-gel science and technology


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Ecs journal of solid state science and technology
Journal: Ecs journal of solid state science and technology


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced photonics research
Journal: Advanced photonics research


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Nano energy
Journal: Nano energy


Dyes and pigments
Journal: Dyes and pigments


Solar rrl
Journal: Solar rrl


Energy &environmental science
Journal: Energy &environmental science


Solar energy
Journal: Solar energy


Applied physics a
Journal: Applied physics a


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of power sources
Journal: Journal of power sources


Optics and spectroscopy
Journal: Optics and spectroscopy


Applied solar energy
Journal: Applied solar energy


Journal of applied spectroscopy
Journal: Journal of applied spectroscopy


Applied solar energy
Journal: Applied solar energy


Res. in environ. life sci
Journal: Res. in environ. life sci


Organic electronics
Journal: Organic electronics


Uzbekiston fizika zhurnali
Journal: Uzbekiston fizika zhurnali


Solar rrl
Journal: Solar rrl


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Science advances
Journal: Science advances


Physical review b
Journal: Physical review b


Chemistry of materials
Journal: Chemistry of materials


Journal of applied polymer science 125 (s1)
Journal: Journal of applied polymer science


Structural dynamics
Journal: Structural dynamics


Nanotechnology
Journal: Nanotechnology


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Chemphyschem
Journal: Chemphyschem


Nanotechnology (print)
Journal: Nanotechnology (print)


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Science advances
Journal: Science advances


Physical review b
Journal: Physical review b


Chemistry of materials
Journal: Chemistry of materials


Journal of applied polymer science 125 (s1)
Journal: Journal of applied polymer science


Structural dynamics
Journal: Structural dynamics


Nanotechnology
Journal: Nanotechnology


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Chemphyschem
Journal: Chemphyschem


Nanotechnology (print)
Journal: Nanotechnology (print)


Acs catalysis
Journal: Acs catalysis


Advanced functional materials
Journal: Advanced functional materials


Nature communications
Journal: Nature communications


Acs catalysis
Journal: Acs catalysis


Advanced materials interfaces
Journal: Advanced materials interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied energy materials
Journal: Acs applied energy materials


Acs applied energy materials
Journal: Acs applied energy materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Energy technology
Journal: Energy technology


Chemical society reviews
Journal: Chemical society reviews


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


Journal of the american chemical society
Journal: Journal of the american chemical society


Cell reports physical science
Journal: Cell reports physical science


Advanced materials
Journal: Advanced materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Small science
Journal: Small science


Advanced energy materials
Journal: Advanced energy materials


Nature communications
Journal: Nature communications


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemistry of materials
Journal: Chemistry of materials


Acs energy letters
Journal: Acs energy letters


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Chemical engineering science
Journal: Chemical engineering science


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs applied energy materials
Journal: Acs applied energy materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs applied nano materials
Journal: Acs applied nano materials


Acs energy letters
Journal: Acs energy letters


Acs applied energy materials
Journal: Acs applied energy materials


Acs energy letters
Journal: Acs energy letters


Chemnanomat
Journal: Chemnanomat


Npj materials degradation
Journal: Npj materials degradation


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Tribology letters
Journal: Tribology letters


Acs applied energy materials
Journal: Acs applied energy materials


Npj computational materials
Journal: Npj computational materials


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Advanced theory and simulations
Journal: Advanced theory and simulations


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Philosophical magazine letters
Journal: Philosophical magazine letters


Applied surface science
Journal: Applied surface science


Ceramics international
Journal: Ceramics international


Molecules
Journal: Molecules


Carbon
Journal: Carbon


Lille
Journal: Lille


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Separation and purification technology
Journal: Separation and purification technology


Rsc advances
Journal: Rsc advances


Chemical papers
Journal: Chemical papers


Journal of superconductivity and novel magnetism
Journal: Journal of superconductivity and novel magnetism


Polymers
Journal: Polymers


Journal of superconductivity and novel magnetism
Journal: Journal of superconductivity and novel magnetism


Solid state communications
Journal: Solid state communications


Journal of low temperature physics 209 (1-2)
Journal: Journal of low temperature physics


Membranes
Journal: Membranes


Current pharmaceutical analysis
Journal: Current pharmaceutical analysis


Journal of superconductivity and novel magnetism
Journal: Journal of superconductivity and novel magnetism


Journal of superconductivity and novel magnetism
Journal: Journal of superconductivity and novel magnetism


Journal of energy chemistry
Journal: Journal of energy chemistry


Journal of energy storage
Journal: Journal of energy storage


Chemosphere
Journal: Chemosphere


Journal of molecular structure
Journal: Journal of molecular structure


Fullerenes
Journal: Fullerenes


Advanced materials technologies
Journal: Advanced materials technologies


Acs applied energy materials
Journal: Acs applied energy materials


Ecs transactions
Journal: Ecs transactions


Journal of electrochemical science and technology
Journal: Journal of electrochemical science and technology


Brazilian journal of physics
Journal: Brazilian journal of physics


Critical reviews in analytical chemistry
Journal: Critical reviews in analytical chemistry


Ecs transactions
Journal: Ecs transactions


Advanced functional piezoelectric materials and applications
Journal: Advanced functional piezoelectric materials and applications


Physical review materials
Journal: Physical review materials


Physical review materials
Journal: Physical review materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Cardiologie tropicale
Journal: Cardiologie tropicale


Aip advances
Journal: Aip advances


Physical review materials
Journal: Physical review materials


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Journal of applied physics
Journal: Journal of applied physics


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Crystal growth &design
Journal: Crystal growth &design


Crystal growth &design
Journal: Crystal growth &design


Inorganic chemistry
Journal: Inorganic chemistry


Dalton transactions
Journal: Dalton transactions


Inorganic chemistry
Journal: Inorganic chemistry


Bioorganic chemistry
Journal: Bioorganic chemistry


Crystal growth &design
Journal: Crystal growth &design


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of molecular structure
Journal: Journal of molecular structure


Inorganic chemistry
Journal: Inorganic chemistry


Acs applied energy materials
Journal: Acs applied energy materials


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Chemistryselect
Journal: Chemistryselect


Journal of molecular structure
Journal: Journal of molecular structure


Dalton transactions
Journal: Dalton transactions


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Journal of applied physics
Journal: Journal of applied physics


Materials chemistry and physics
Journal: Materials chemistry and physics


Ceramics international
Journal: Ceramics international


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Ceramics international
Journal: Ceramics international


Ceramics international
Journal: Ceramics international


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Journal of sol-gel science and technology
Journal: Journal of sol-gel science and technology


Journal of low temperature physics 207 (1-2)
Journal: Journal of low temperature physics


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Journal of materials science: materials in electronics

Chemical engineering journal
Journal: Chemical engineering journal


Cancers
Journal: Cancers


Cells
Journal: Cells


Applied physics letters
Journal: Applied physics letters


Advanced optical materials
Journal: Advanced optical materials


Physica status solidi (a)
Journal: Physica status solidi (a)


Advanced optical materials
Journal: Advanced optical materials


Advanced optical materials
Journal: Advanced optical materials


Acs applied electronic materials
Journal: Acs applied electronic materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Advanced optical materials
Journal: Advanced optical materials


Journal of applied physics
Journal: Journal of applied physics


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of applied physics
Journal: Journal of applied physics


Thin solid films
Journal: Thin solid films


Crystal research and technology
Journal: Crystal research and technology


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Journal of applied physics
Journal: Journal of applied physics


Journal of materials research
Journal: Journal of materials research


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of catalysis
Journal: Journal of catalysis


Crystengcomm
Journal: Crystengcomm


Langmuir
Journal: Langmuir


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Journal of physics and chemistry of solids
Journal: Journal of physics and chemistry of solids


Materials research
Journal: Materials research


New journal of chemistry
Journal: New journal of chemistry


Energy &fuels
Journal: Energy &fuels


New journal of chemistry
Journal: New journal of chemistry


Interdisciplinary materials
Journal: Interdisciplinary materials


Matter
Journal: Matter


Mrs advances
Journal: Mrs advances


Physical review b
Journal: Physical review b


Physical review materials
Journal: Physical review materials


Applied surface science
Journal: Applied surface science


Surface science
Journal: Surface science


Chemcatchem
Journal: Chemcatchem


Applied surface science
Journal: Applied surface science


Applied surface science
Journal: Applied surface science


Acs omega
Journal: Acs omega


Sensors
Journal: Sensors


Applied catalysis a: general
Journal: Applied catalysis a: general


Applied surface science
Journal: Applied surface science


Advanced materials
Journal: Advanced materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Light-emitting devices
Journal: Light-emitting devices


Chemical engineering journal
Journal: Chemical engineering journal


Science
Journal: Science


Advanced materials
Journal: Advanced materials


Nature energy
Journal: Nature energy


Acs energy letters
Journal: Acs energy letters


Advanced energy materials
Journal: Advanced energy materials


Acs energy letters
Journal: Acs energy letters


Solar rrl
Journal: Solar rrl


Science
Journal: Science


Advanced materials
Journal: Advanced materials


Nature energy
Journal: Nature energy


Acs energy letters
Journal: Acs energy letters


Advanced energy materials
Journal: Advanced energy materials


Acs energy letters
Journal: Acs energy letters


Solar rrl
Journal: Solar rrl


Advanced functional materials
Journal: Advanced functional materials


Infomat
Journal: Infomat


Solar rrl
Journal: Solar rrl


Molecules
Journal: Molecules


Acs applied energy materials
Journal: Acs applied energy materials


Organic electronics
Journal: Organic electronics


Advanced optical materials
Journal: Advanced optical materials


Frontiers in materials
Journal: Frontiers in materials


Advanced functional materials
Journal: Advanced functional materials


Infomat
Journal: Infomat


Solar rrl
Journal: Solar rrl


Molecules
Journal: Molecules


Acs applied energy materials
Journal: Acs applied energy materials


Organic electronics
Journal: Organic electronics


Advanced optical materials
Journal: Advanced optical materials


Frontiers in materials
Journal: Frontiers in materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Angewandte chemie
Journal: Angewandte chemie


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced materials interfaces
Journal: Advanced materials interfaces


Chemsuschem
Journal: Chemsuschem


Inorganica chimica acta
Journal: Inorganica chimica acta


Acs catalysis
Journal: Acs catalysis


Angewandte chemie
Journal: Angewandte chemie


Tetrahedron letters
Journal: Tetrahedron letters


Journal of physical organic chemistry
Journal: Journal of physical organic chemistry


Journal of organometallic chemistry
Journal: Journal of organometallic chemistry


Results in chemistry
Journal: Results in chemistry


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Chemical communications
Journal: Chemical communications


Chemcatchem
Journal: Chemcatchem


Applied catalysis a: general
Journal: Applied catalysis a: general


Rsc advances
Journal: Rsc advances


Thermochimica acta
Journal: Thermochimica acta


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Thermochimica acta
Journal: Thermochimica acta


American ceramic society (acers) bulletin
Journal: American ceramic society (acers) bulletin


Journal of membrane science
Journal: Journal of membrane science


Journal of solid state electrochemistry
Journal: Journal of solid state electrochemistry


Journal of industrial and engineering chemistry
Journal: Journal of industrial and engineering chemistry


Organic electronics
Journal: Organic electronics


Applied physics letters
Journal: Applied physics letters


Rsc advances
Journal: Rsc advances


Acs applied energy materials
Journal: Acs applied energy materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Ionics
Journal: Ionics


Thin solid films
Journal: Thin solid films


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nature materials
Journal: Nature materials


Acs energy letters
Journal: Acs energy letters


Acs omega
Journal: Acs omega


Sustainable energy &fuels
Journal: Sustainable energy &fuels


Nature chemistry
Journal: Nature chemistry


Advanced materials
Journal: Advanced materials


Advanced functional materials
Journal: Advanced functional materials


Crystal growth &design
Journal: Crystal growth &design


Applied physics letters
Journal: Applied physics letters


Advanced functional materials
Journal: Advanced functional materials


Crystal growth &design
Journal: Crystal growth &design


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nano energy
Journal: Nano energy


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Sustainable energy &fuels
Journal: Sustainable energy &fuels


Chinese journal of chemistry
Journal: Chinese journal of chemistry


Nanomaterials
Journal: Nanomaterials


Organic electronics
Journal: Organic electronics


Journal of physics: photonics
Journal: Journal of physics: photonics


Advanced materials interfaces
Journal: Advanced materials interfaces


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Nature photonics
Journal: Nature photonics


Applied physics letters
Journal: Applied physics letters


Advanced functional materials
Journal: Advanced functional materials


Advanced optical materials
Journal: Advanced optical materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of vacuum science &technology a: vacuum
Journal: Journal of vacuum science &technology a: vacuum


Acs applied electronic materials
Journal: Acs applied electronic materials


Materials horizons
Journal: Materials horizons


Advanced functional materials
Journal: Advanced functional materials


Materials &design
Journal: Materials &design


Solar energy
Journal: Solar energy


Applied surface science
Journal: Applied surface science


Solar energy
Journal: Solar energy


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


Solar energy
Journal: Solar energy


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Acs applied energy materials
Journal: Acs applied energy materials


Applied surface science
Journal: Applied surface science


Langmuir
Journal: Langmuir


Scientific reports
Journal: Scientific reports


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Nano express
Journal: Nano express


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of materials research
Journal: Journal of materials research


Surfaces and interfaces
Journal: Surfaces and interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


European journal of organic chemistry
Journal: European journal of organic chemistry


Acs applied nano materials
Journal: Acs applied nano materials


Acs applied energy materials
Journal: Acs applied energy materials


Energy technology
Journal: Energy technology


Acs applied electronic materials
Journal: Acs applied electronic materials


Acs applied nano materials
Journal: Acs applied nano materials


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Applied physics letters
Journal: Applied physics letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Nature
Journal: Nature


Applied physics letters
Journal: Applied physics letters


Journal of applied physics
Journal: Journal of applied physics


Nature
Journal: Nature


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Journal of applied physics
Journal: Journal of applied physics


Nature
Journal: Nature


Applied physics letters
Journal: Applied physics letters


Journal of applied physics
Journal: Journal of applied physics


Nature
Journal: Nature


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Journal of applied physics
Journal: Journal of applied physics


Industrial &engineering chemistry research
Journal: Industrial &engineering chemistry research


Nanoscale advances
Journal: Nanoscale advances


Colloid and interface science communications
Journal: Colloid and interface science communications


Journal of hazardous materials
Journal: Journal of hazardous materials


Acs applied nano materials
Journal: Acs applied nano materials


Nanomaterials
Journal: Nanomaterials


Nanoscale advances
Journal: Nanoscale advances


Journal of materials chemistry a
Journal: Journal of materials chemistry a


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Joule
Journal: Joule


Journal of the american chemical society
Journal: Journal of the american chemical society


Materials advances
Journal: Materials advances


Advanced functional materials
Journal: Advanced functional materials


Advanced optical materials
Journal: Advanced optical materials


Chemical communications
Journal: Chemical communications


Advanced functional materials
Journal: Advanced functional materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Chemistry of materials
Journal: Chemistry of materials


Acs appl. mater. interfaces
Journal: Acs appl. mater. interfaces


Journal of materials chemistry c
Journal: Journal of materials chemistry c


European journal of organic chemistry
Journal: European journal of organic chemistry


Int. j. innov. res. sci. eng. technol.
Journal: Int. j. innov. res. sci. eng. technol.


Advanced materials research
Journal: Advanced materials research


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Materials advances
Journal: Materials advances


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced engineering materials
Journal: Advanced engineering materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Frontiers in energy research
Journal: Frontiers in energy research


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of vacuum science &technology b
Journal: Journal of vacuum science &technology b


Papers in physics
Journal: Papers in physics


Macromolecules
Journal: Macromolecules


Advanced optical materials
Journal: Advanced optical materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nano energy
Journal: Nano energy


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Nanomaterials
Journal: Nanomaterials


Acs applied electronic materials
Journal: Acs applied electronic materials


Advanced science
Journal: Advanced science


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Applied materials today
Journal: Applied materials today


Microporous and mesoporous materials
Journal: Microporous and mesoporous materials


Materials letters
Journal: Materials letters


Materials chemistry frontiers
Journal: Materials chemistry frontiers


Applied surface science
Journal: Applied surface science


Applied materials today
Journal: Applied materials today


Journal of luminescence
Journal: Journal of luminescence


Ceramics international
Journal: Ceramics international


Journal of molecular structure
Journal: Journal of molecular structure


Ionics
Journal: Ionics


Ecs transactions
Journal: Ecs transactions


Materials chemistry and physics
Journal: Materials chemistry and physics


Materials today communications
Journal: Materials today communications


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Dalton transactions
Journal: Dalton transactions


International journal of quantum chemistry
Journal: International journal of quantum chemistry


Materials chemistry frontiers
Journal: Materials chemistry frontiers


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of molecular modeling
Journal: Journal of molecular modeling


Materials horizons
Journal: Materials horizons


Chemistry of materials
Journal: Chemistry of materials


Nature photonics
Journal: Nature photonics


Nature photonics
Journal: Nature photonics


Nature photonics
Journal: Nature photonics


J. pharm pharm scien
Journal: J. pharm pharm scien


Energies
Journal: Energies


Current applied physics
Journal: Current applied physics


Energy technology
Journal: Energy technology


Langmuir
Journal: Langmuir


Advanced engineering materials
Journal: Advanced engineering materials


Materials advances
Journal: Materials advances


Solar
Journal: Solar


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nanoscale
Journal: Nanoscale


Matter
Journal: Matter


Crystal growth &design
Journal: Crystal growth &design


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Progress in natural science: materials international
Journal: Progress in natural science: materials international


Chemical science
Journal: Chemical science


Sensors and actuators b: chemical
Journal: Sensors and actuators b: chemical


Machine learning and knowledge extraction
Journal: Machine learning and knowledge extraction


International journal of energy research
Journal: International journal of energy research


Mrs advances
Journal: Mrs advances


Organic and hybrid sensors and bioelectronics xv
Journal: Organic and hybrid sensors and bioelectronics xv


Organic and hybrid sensors and bioelectronics xv
Journal: Organic and hybrid sensors and bioelectronics xv


Organic and hybrid sensors and bioelectronics xiv
Journal: Organic and hybrid sensors and bioelectronics xiv


Journal of applied physics
Journal: Journal of applied physics


Ceramics international
Journal: Ceramics international


Langmuir
Journal: Langmuir


Applied physics letters
Journal: Applied physics letters


Applied physics reviews
Journal: Applied physics reviews


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Materials letters
Journal: Materials letters


Nano energy
Journal: Nano energy


Rsc advances
Journal: Rsc advances


Journal of alloys and compounds
Journal: Journal of alloys and compounds


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of photonics for energy
Journal: Journal of photonics for energy


Quimica nova
Journal: Quimica nova


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemistry–a european journal
Journal: Chemistry–a european journal


Chemistry–a european journal
Journal: Chemistry–a european journal


Advanced materials
Journal: Advanced materials


Nature nanotechnology
Journal: Nature nanotechnology


Materials &design
Journal: Materials &design


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Thin solid films
Journal: Thin solid films


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Radiation physics and chemistry
Journal: Radiation physics and chemistry


Acs applied energy materials
Journal: Acs applied energy materials


Advanced materials
Journal: Advanced materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of chemical information and modeling
Journal: Journal of chemical information and modeling


Nature communications
Journal: Nature communications


Apl materials
Journal: Apl materials


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Batteries
Journal: Batteries


Nature communications
Journal: Nature communications


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced optical materials

In [43]:
df5['Source'].value_counts()

The journal of physical chemistry c                           800
Advanced materials                                            727
Applied physics letters                                       673
Acs energy letters                                            578
Physical review b                                             564
                                                             ...
Acs earth and space chemistry                                   1
Phys chem minerals                                              1
The european physical journal-applied physics                   1
Defect and impurity engineered semiconductors and devices       1
Journal of the indian botanical society                         1
Name: Source, Length: 2144, dtype: int64

Let's see the number of unique journal titles

In [45]:
df5['Title'].value_counts().count() == df5['Authors'].value_counts().count()

False

In [47]:
df5['Title'].value_counts().count()

18986

In [48]:
df5['Authors'].value_counts().count()

17490

In [49]:
df5.to_csv(r"G:\My Drive\BrainStation\BrainStationCapstone\Scripts and Notebooks\Raw Data\2023-03-03 Export\2023-03-02 Cleaning DataSet V2.2 out.csv")

---