In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r"G:\My Drive\BrainStation\BrainStationCapstone\Scripts and Notebooks\Raw Data\2023-03-03 Export\full_results_PoPCites_V1.csv",low_memory = True)

In [3]:
df.head()

,Unnamed: 0,Cites,Authors,Title,Year,Source,Publisher,ArticleURL,CitesURL,GSRank,...,EndPage,ECC,CitesPerYear,CitesPerAuthor,AuthorCount,Age,Abstract,FullTextURL,RelatedURL,query_id
0,0,206,"F Cordero, F Craciun, F Trequattrini, E Mercad...",Phase transitions and phase diagram of the fer...,2010.0,Physical Review B,NaN,NaN,https://scholar.google.com/scholar?oi=bibs&hl=...,1,...,144124.0,206,15.85,41,5,13.0,NaN,NaN,NaN,0.0
1,1,85,F Cordero,Hopping and clustering of oxygen vacancies in ...,2007.0,Physical Review B,NaN,NaN,https://scholar.google.com/scholar?oi=bibs&hl=...,2,...,172106.0,85,5.31,85,1,16.0,NaN,NaN,NaN,0.0
2,2,85,"G Cannelli, R Cantelli, F Cordero, F Trequattrini",Dynamics of oxygen and phase transitions in th...,1992.0,Superconductor Science and Technology,NaN,NaN,https://scholar.google.com/scholar?oi=bibs&hl=...,3,...,247.0,85,2.74,21,4,31.0,NaN,NaN,NaN,0.0
3,3,83,"G Cannelli, R Cantelli, F Cordero, GA Costa, M...",Phase Transformation at 240 K in YBa2Cu3O7-x b...,1988.0,Europhysics Letters,NaN,NaN,https://scholar.google.com/scholar?oi=bibs&hl=...,4,...,271.0,83,2.37,14,6,35.0,NaN,NaN,NaN,0.0
4,4,81,"G Cannelli, R Cantelli, F Cordero",New anelastic relaxation effect in Y-Ba-Cu-O a...,1988.0,Physical Review B,NaN,NaN,https://scholar.google.com/scholar?oi=bibs&hl=...,5,...,7200.0,81,2.31,27,3,35.0,NaN,NaN,NaN,0.0

In [4]:
df = df.drop(['Unnamed: 0', 'Publisher', 'ArticleURL', 'Abstract', 'FullTextURL', 'RelatedURL'], axis = 1)

In [5]:
df.head()

,Cites,Authors,Title,Year,Source,CitesURL,GSRank,QueryDate,Type,DOI,...,Volume,Issue,StartPage,EndPage,ECC,CitesPerYear,CitesPerAuthor,AuthorCount,Age,query_id
0,206,"F Cordero, F Craciun, F Trequattrini, E Mercad...",Phase transitions and phase diagram of the fer...,2010.0,Physical Review B,https://scholar.google.com/scholar?oi=bibs&hl=...,1,3/1/2023 22:10,Journal article,NaN,...,81.0,14.0,144124.0,144124.0,206,15.85,41,5,13.0,0.0
1,85,F Cordero,Hopping and clustering of oxygen vacancies in ...,2007.0,Physical Review B,https://scholar.google.com/scholar?oi=bibs&hl=...,2,3/1/2023 22:10,Journal article,NaN,...,76.0,17.0,172106.0,172106.0,85,5.31,85,1,16.0,0.0
2,85,"G Cannelli, R Cantelli, F Cordero, F Trequattrini",Dynamics of oxygen and phase transitions in th...,1992.0,Superconductor Science and Technology,https://scholar.google.com/scholar?oi=bibs&hl=...,3,3/1/2023 22:10,Journal article,NaN,...,5.0,4.0,247.0,247.0,85,2.74,21,4,31.0,0.0
3,83,"G Cannelli, R Cantelli, F Cordero, GA Costa, M...",Phase Transformation at 240 K in YBa2Cu3O7-x b...,1988.0,Europhysics Letters,https://scholar.google.com/scholar?oi=bibs&hl=...,4,3/1/2023 22:10,Journal article,NaN,...,6.0,3.0,271.0,271.0,83,2.37,14,6,35.0,0.0
4,81,"G Cannelli, R Cantelli, F Cordero",New anelastic relaxation effect in Y-Ba-Cu-O a...,1988.0,Physical Review B,https://scholar.google.com/scholar?oi=bibs&hl=...,5,3/1/2023 22:10,Journal article,NaN,...,38.0,10.0,7200.0,7200.0,81,2.31,27,3,35.0,0.0

In [6]:
num = df.isna().sum().sum()
print(f"There are {num} null values")

There are 59795 null values

In [7]:
df['Type'].value_counts()

Journal article     13054
Conference paper     1219
Book chapter          505
Patent                425
Abstract              329
Preprint              150
Book                   84
Online document         3
Name: Type, dtype: int64

In [8]:
df1 = df[df['Type'] == 'Journal article']

In [9]:
num = df1.isna().sum().sum()
print(f"There are {num} null values")

There are 30833 null values

In [10]:
df2 = df1.drop(['DOI', 'Volume', 'Issue', 'ISSN'], axis = 1)

In [11]:
num = df2.isna().sum().sum()
print(f"There are {num} null values")

There are 1850 null values

In [12]:
df2['Type'].value_counts()

Journal article    13054
Name: Type, dtype: int64

In [14]:
df2.isna().sum()

Cites               0
Authors             2
Title               0
Year                6
Source              0
CitesURL            0
GSRank              0
QueryDate           0
Type                0
CitationURL         0
StartPage         881
EndPage           955
ECC                 0
CitesPerYear        0
CitesPerAuthor      0
AuthorCount         0
Age                 6
query_id            0
dtype: int64

In [15]:
df3 = df2.drop(['StartPage', 'EndPage', 'Age'], axis = 1)

In [18]:
df3.isna().sum()

Cites             0
Authors           2
Title             0
Year              6
Source            0
CitesURL          0
GSRank            0
QueryDate         0
Type              0
CitationURL       0
ECC               0
CitesPerYear      0
CitesPerAuthor    0
AuthorCount       0
query_id          0
dtype: int64

In [16]:
num = df3.isna().sum().sum()
print(f"There are {num} null values")

There are 8 null values

In [26]:
df4 = df3.dropna(subset=['Authors', 'Year'])

In [27]:
df4.isna().sum()

Cites             0
Authors           0
Title             0
Year              0
Source            0
CitesURL          0
GSRank            0
QueryDate         0
Type              0
CitationURL       0
ECC               0
CitesPerYear      0
CitesPerAuthor    0
AuthorCount       0
query_id          0
dtype: int64

In [28]:
df4.head()

,Cites,Authors,Title,Year,Source,CitesURL,GSRank,QueryDate,Type,CitationURL,ECC,CitesPerYear,CitesPerAuthor,AuthorCount,query_id
0,206,"F Cordero, F Craciun, F Trequattrini, E Mercad...",Phase transitions and phase diagram of the fer...,2010.0,Physical Review B,https://scholar.google.com/scholar?oi=bibs&hl=...,1,3/1/2023 22:10,Journal article,https://scholar.google.com/citations?view_op=v...,206,15.85,41,5,0.0
1,85,F Cordero,Hopping and clustering of oxygen vacancies in ...,2007.0,Physical Review B,https://scholar.google.com/scholar?oi=bibs&hl=...,2,3/1/2023 22:10,Journal article,https://scholar.google.com/citations?view_op=v...,85,5.31,85,1,0.0
2,85,"G Cannelli, R Cantelli, F Cordero, F Trequattrini",Dynamics of oxygen and phase transitions in th...,1992.0,Superconductor Science and Technology,https://scholar.google.com/scholar?oi=bibs&hl=...,3,3/1/2023 22:10,Journal article,https://scholar.google.com/citations?view_op=v...,85,2.74,21,4,0.0
3,83,"G Cannelli, R Cantelli, F Cordero, GA Costa, M...",Phase Transformation at 240 K in YBa2Cu3O7-x b...,1988.0,Europhysics Letters,https://scholar.google.com/scholar?oi=bibs&hl=...,4,3/1/2023 22:10,Journal article,https://scholar.google.com/citations?view_op=v...,83,2.37,14,6,0.0
4,81,"G Cannelli, R Cantelli, F Cordero",New anelastic relaxation effect in Y-Ba-Cu-O a...,1988.0,Physical Review B,https://scholar.google.com/scholar?oi=bibs&hl=...,5,3/1/2023 22:10,Journal article,https://scholar.google.com/citations?view_op=v...,81,2.31,27,3,0.0

In [43]:
rows, cols = df4.shape
print(f'There are {rows} rows')

There are 13046 rows

In [32]:
df4['Source'].value_counts()

Advanced Materials                     468
The Journal of Physical Chemistry C    440
Physical Review B                      363
ACS Energy Letters                     356
Applied Physics Letters                321
                                      ...
Optics Express 27 (20), A1419-A          1
Photovoltaics, IEEE Journal of           1
Optics Express 19 (102), A136-A          1
Optics express 20 (102), A157-A          1
Spintronics XIII                         1
Name: Source, Length: 2014, dtype: int64

In [37]:
import re
pattern = r'^(.*?)\s+(\d+)\s+\((\d+)\),\s+(.*)$'

vals = df4['Source'].values
index = df4['Source'].index

for idx, val in enumerate(df4['Source'].values):

    # match pattern to citation
    match = re.match(pattern, val)

    if match:
        journal = match.group(1)   # 'Optics Express'
        volume = match.group(2)    # '27'
        issue = match.group(3)     # '20'
        pages = match.group(4)     # 'A1419-A'

        # print extracted values
        print(val)
        print('Journal:', journal)
        print('\n')
        
        df4.loc[index[idx], 'Source'] = journal
        
    else:
        pass

Journal of Applied Physics 117 (17), 17C
Journal: Journal of Applied Physics


Archives of Metallurgy and Materials 60 (1), 381-
Journal: Archives of Metallurgy and Materials


Biophysical Journal 100 (3), 27a
Journal: Biophysical Journal


Science Advances 7 (52), eabj
Journal: Science Advances


ECS Solid State Letters 3 (6), N
Journal: ECS Solid State Letters


Science advances 4 (10), eaat
Journal: Science advances


Journal of Physics: Condensed Matter 18 (17), R
Journal: Journal of Physics: Condensed Matter


Journal of Physics: Condensed Matter 11 (48), L
Journal: Journal of Physics: Condensed Matter


Journal of Physics C: Solid State Physics 20 (26), L
Journal: Journal of Physics C: Solid State Physics


Journal of Physics C: Solid State Physics 19 (15), L
Journal: Journal of Physics C: Solid State Physics


Physical Review-Section B-Condensed Matter 67 (2), 20101R
Journal: Physical Review-Section B-Condensed Matter


Journal of Physics: Condensed Matter 18 (42), L
Journal: Journal of Physics: Condensed Matter


Journal of Physics: Condensed Matter 17 (40), S
Journal: Journal of Physics: Condensed Matter


Physical Review B 63 (8), 5204/1-5204/
Journal: Physical Review B


Journal of Physics: Condensed Matter 18 (17), R
Journal: Journal of Physics: Condensed Matter


Science advances 5 (2), eaau
Journal: Science advances


Physical Review B 55 (4), R
Journal: Physical Review B


Physical Review B 58 (12), R
Journal: Physical Review B


Science advances 8 (1), eabj
Journal: Science advances


Physical Review B 56 (20), R
Journal: Physical Review B


Physical Review B 105 (22), L
Journal: Physical Review B


Physical Review-Section B-Condensed Matter 67 (2), 20101R
Journal: Physical Review-Section B-Condensed Matter


Physical Review-Section B-Condensed Matter 58 (12), R
Journal: Physical Review-Section B-Condensed Matter


Archives of Materials Science and Engineering 72 (2), 86-
Journal: Archives of Materials Science and Engineering


Journal of The Electrochemical Society 152 (12), A
Journal: Journal of The Electrochemical Society


Archives of Materials Science and Engineering 72 (1), 16-
Journal: Archives of Materials Science and Engineering


Journal of the Electrochemical Society 152 (12), A
Journal: Journal of the Electrochemical Society


Applied Physics Letters 103 (5), 142_
Journal: Applied Physics Letters


Applied Physics Letters 106 (17), 45_
Journal: Applied Physics Letters


Science advances 3 (9), eaao
Journal: Science advances


Journal of The Electrochemical Society 160 (2), H
Journal: Journal of The Electrochemical Society


Journal of The Electrochemical Society 166 (16), F
Journal: Journal of The Electrochemical Society


Journal of The Electrochemical Society 162 (7), D
Journal: Journal of The Electrochemical Society


Journal of The Electrochemical Society 164 (13), C
Journal: Journal of The Electrochemical Society


Optics Express 24 (6), A674-A
Journal: Optics Express


Science Advances 8 (29), eabp
Journal: Science Advances


Science Advances 8 (30), eabn
Journal: Science Advances


JOSA B 36 (2), A79-A
Journal: JOSA B


BIOPHYSICAL JOURNAL 70 (2), TU535-TU
Journal: BIOPHYSICAL JOURNAL


Journal of Physics: Condensed Matter 16 (29), R
Journal: Journal of Physics: Condensed Matter


Journal of Optics A: Pure and Applied Optics 8 (7), S
Journal: Journal of Optics A: Pure and Applied Optics


Proceedings of the National Academy of Sciences 112 (30), E3987-
Journal: Proceedings of the National Academy of Sciences


Nano Letters 18 (1), 535-539.
Journal: Nano Letters


Bulletin of the Russian Academy of Sciences: Physics 86 (1), S24-S
Journal: Bulletin of the Russian Academy of Sciences: Physics


Bulletin of the Russian Academy of Sciences: Physics 86 (1), S20-S
Journal: Bulletin of the Russian Academy of Sciences: Physics


Bulletin of the Russian Academy of Sciences: Physics 86 (1), S179-S
Journal: Bulletin of the Russian Academy of Sciences: Physics


Bulletin of the Russian Academy of Sciences: Physics 86 (1), S201-S
Journal: Bulletin of the Russian Academy of Sciences: Physics


Bulletin of the Russian Academy of Sciences: Physics 86 (1), S127-S
Journal: Bulletin of the Russian Academy of Sciences: Physics


Bulletin of the Russian Academy of Sciences: Physics 86 (1), S191-S
Journal: Bulletin of the Russian Academy of Sciences: Physics


Bulletin of the Russian Academy of Sciences: Physics 86 (1), S152-S
Journal: Bulletin of the Russian Academy of Sciences: Physics


Optics Express 23 (24), A1720-A
Journal: Optics Express


Optics Express 23 (11), A502-A
Journal: Optics Express


Optics Express 24 (14), A1083-A
Journal: Optics Express


Optics Express 24 (6), A434-A
Journal: Optics Express


Optics Express 21 (105), A883-A
Journal: Optics Express


Optics Express 22 (101), A111-A
Journal: Optics Express


Optics Express 24 (6), A460-A
Journal: Optics Express


Optics express 20 (102), A157-A
Journal: Optics express


Optics Express 19 (102), A136-A
Journal: Optics Express


Optics Express 27 (20), A1419-A
Journal: Optics Express


Optics Express 22 (102), A452-A
Journal: Optics Express


Optics Express 26 (18), A761-A
Journal: Optics Express


Journal of Applied Physics 111 (8), 089901-
Journal: Journal of Applied Physics


HUMAN GENE THERAPY 28 (12), A124-A
Journal: HUMAN GENE THERAPY


Physical Review-Section B-Condensed Matter 65 (24), 241301R
Journal: Physical Review-Section B-Condensed Matter


Science 352 (6283), aad
Journal: Science


Applied Physics Letters 103 (15), 190_
Journal: Applied Physics Letters


Physical Review B 62 (24), R
Journal: Physical Review B


Physical Review B 59 (24), R
Journal: Physical Review B


Physical Review B 61 (8), R
Journal: Physical Review B


Semiconductor science and technology 18 (10), S
Journal: Semiconductor science and technology


Physical Review-Section B-Condensed Matter 61 (8), R
Journal: Physical Review-Section B-Condensed Matter


Physical Review-Section B-Condensed Matter 62 (24), R
Journal: Physical Review-Section B-Condensed Matter


Physical Review-Section B-Condensed Matter 59 (24), R
Journal: Physical Review-Section B-Condensed Matter


Optics express 24 (22), A1454-A
Journal: Optics express


Optics express 23 (7), A391-A
Journal: Optics express


Journal of The Electrochemical Society 156 (11), H
Journal: Journal of The Electrochemical Society


Journal of The Electrochemical Society 153 (8), G
Journal: Journal of The Electrochemical Society


Journal of The Electrochemical Society 154 (1), H
Journal: Journal of The Electrochemical Society


Journal of The Electrochemical Society 154 (6), H
Journal: Journal of The Electrochemical Society


Electrochemical and solid-state letters 8 (3), G
Journal: Electrochemical and solid-state letters


Journal of The Electrochemical Society 154 (6), H
Journal: Journal of The Electrochemical Society


Current Applied Physics 10 (3), S361-S
Journal: Current Applied Physics


Journal of the Electrochemical Society 154 (6), H
Journal: Journal of the Electrochemical Society


Science advances 5 (1), eaas
Journal: Science advances


Physical Review Applied 17 (5), L
Journal: Physical Review Applied


Science Advances 6 (42), eabb
Journal: Science Advances


Science Advances 7 (50), eabi
Journal: Science Advances


Journal of Semiconductors 42 (3), 030201-
Journal: Journal of Semiconductors


Science Advances 7 (18), eabf
Journal: Science Advances


Journal of the Electrochemical Society 159 (10), F
Journal: Journal of the Electrochemical Society


Journal of the Electrochemical Society 148 (4), C
Journal: Journal of the Electrochemical Society


Journal of the Electrochemical Society 150 (9), C
Journal: Journal of the Electrochemical Society


Journal of The Electrochemical Society 149 (11), C
Journal: Journal of The Electrochemical Society


Journal of the Electrochemical Society 152 (2), C
Journal: Journal of the Electrochemical Society


Electrochemical and solid-state letters 9 (2), H
Journal: Electrochemical and solid-state letters


Journal of The Electrochemical Society 151 (1), H
Journal: Journal of The Electrochemical Society


Journal of Nanophotonics 5 (1), 051816-
Journal: Journal of Nanophotonics


Electrochemical and Solid State Letters 9 (2), H
Journal: Electrochemical and Solid State Letters


Journal of the Electrochemical Society 151 (1), H
Journal: Journal of the Electrochemical Society


Journal of the Electrochemical Society 150 (9), C
Journal: Journal of the Electrochemical Society


Journal of The Electrochemical Society 155 (2), G
Journal: Journal of The Electrochemical Society


Science Advances 4 (5), eaar
Journal: Science Advances


ECS Solid State Letters 1 (5), Q
Journal: ECS Solid State Letters


Nanotechnology 15 (4), S
Journal: Nanotechnology


Electrochemical and solid-state letters 11 (3), G
Journal: Electrochemical and solid-state letters


ECS Journal of Solid State Science and Technology 3 (2), N
Journal: ECS Journal of Solid State Science and Technology


Journal of the Anatomical Society of India 2 (65), S64-S
Journal: Journal of the Anatomical Society of India


Optics express 23 (15), A858-A
Journal: Optics express


Chinese Journal of Lasers 50 (1), 0113002-
Journal: Chinese Journal of Lasers


Science 361 (6408), eaat
Journal: Science


Science advances 3 (12), eaaq
Journal: Science advances


Biophysical Journal 100 (3), 624a
Journal: Biophysical Journal


Biophysical Journal 98 (3), 605a
Journal: Biophysical Journal


Applied Physics Letters 104 (6), 29_
Journal: Applied Physics Letters


Science advances 8 (2), eabk
Journal: Science advances


Applied Physics Letters 106 (7), 21_
Journal: Applied Physics Letters


Applied Physics Letters 102 (18), 84_
Journal: Applied Physics Letters


Applied Physics Letters 105 (22), 178_
Journal: Applied Physics Letters


Physical Review-Section B-Condensed Matter 63 (12), 121302R
Journal: Physical Review-Section B-Condensed Matter


Applied Catalysis A, General 1 (153), N3-N
Journal: Applied Catalysis A, General


Applied Catalysis A: General 143 (2), N7-N
Journal: Applied Catalysis A: General


Applied Catalysis A: General 142 (1), N
Journal: Applied Catalysis A: General


Applied Catalysis A: General 142 (1), n2-n
Journal: Applied Catalysis A: General


Applied Catalysis A: General 133 (1), n6-n
Journal: Applied Catalysis A: General


Applied Catalysis B: Environmental 1 (6), N
Journal: Applied Catalysis B: Environmental


Applied Catalysis A: General 133 (1), n4-n
Journal: Applied Catalysis A: General


Applied Catalysis A, General 1 (129), n7-n
Journal: Applied Catalysis A, General


applied catalysis A: General 112 (1), N4-N
Journal: applied catalysis A: General


APPLIED CATALYSIS A-GENERAL 81 (1), N15-N
Journal: APPLIED CATALYSIS A-GENERAL


Nanotechnology 17 (11), S
Journal: Nanotechnology


Surface science 418 (1), L8-L
Journal: Surface science


Journal of the Electrochemical Society 150 (7), G
Journal: Journal of the Electrochemical Society


Surface science 515 (1), L469-L
Journal: Surface science


Journal of the Electrochemical Society 156 (1), H
Journal: Journal of the Electrochemical Society


Science Advances 5 (8), eaaw
Journal: Science Advances


Surface science 459 (3), L475-L
Journal: Surface science


Journal of the Electrochemical Society 150 (7), G
Journal: Journal of the Electrochemical Society


Science advances 5 (12), eaay
Journal: Science advances


Science 368 (6488), eaay
Journal: Science


Applied Physics Letters 103 (24), 236_
Journal: Applied Physics Letters


Electrochemical and Solid-State Letters 8 (10), J
Journal: Electrochemical and Solid-State Letters


Applied Physics Letters 107 (7), 81_
Journal: Applied Physics Letters


Science Advances 7 (3), eabd
Journal: Science Advances


Advanced Materials 24 (23), OP159-OP
Journal: Advanced Materials


Optics express 26 (2), A66-A
Journal: Optics express


Applied Physics Letters 106 (2), 4_
Journal: Applied Physics Letters


Photonics Research 8 (10), A39-A
Journal: Photonics Research


Photonics Research 8 (9), A25-A
Journal: Photonics Research


Proceedings of the National Academy of Sciences 114 (33), E6739-
Journal: Proceedings of the National Academy of Sciences


Optics express 19 (106), A1281-A
Journal: Optics express


Optics express 19 (106), A1237-A
Journal: Optics express


Science 368 (6497), eaba
Journal: Science


Science advances 5 (4), eaav
Journal: Science advances


Photonics Research 8 (11), A56-A
Journal: Photonics Research


Science advances 3 (10), eaao
Journal: Science advances


Science 368 (6488), eaay
Journal: Science


Science Advances 7 (18), eabf
Journal: Science Advances


Applied Physics Letters 105 (18), 166_
Journal: Applied Physics Letters


Journal of Applied Physics 110 (9), 094108-
Journal: Journal of Applied Physics


Physical Review B 55 (2), R
Journal: Physical Review B


Applied Physics Letters 100 (19), 192907-
Journal: Applied Physics Letters


Journal of applied physics 101 (10), 104115-
Journal: Journal of applied physics


Applied Physics Letters 96 (24), 242902-
Journal: Applied Physics Letters


Applied Physics Letters 93 (26), 262901-
Journal: Applied Physics Letters


Applied Physics Letters 98 (7), 072907-
Journal: Applied Physics Letters


Journal of Applied Physics 112 (6), 064114-
Journal: Journal of Applied Physics


Science Advances 7 (8), eabd
Journal: Science Advances


Science Advances 6 (45), eabb
Journal: Science Advances


National Science Review 9 (7), nwac
Journal: National Science Review


National Science Review 9 (10), nwac
Journal: National Science Review


Science Advances 6 (42), eabb
Journal: Science Advances


Science Advances 8 (8), eabl
Journal: Science Advances


Applied Physics Letters 106 (11), 32_
Journal: Applied Physics Letters


Applied Physics Letters 107 (6), 79_
Journal: Applied Physics Letters


Science Advances 6 (42), eabb
Journal: Science Advances


Science 364 (6438), eaav
Journal: Science


Science 361 (6408), eaat
Journal: Science


Science 353 (6302), aac
Journal: Science


Science 373 (6555), eaaz
Journal: Science


Science Advances 6 (42), eabb
Journal: Science Advances


Science advances 6 (42), eabc
Journal: Science advances


Journal of Optics A: Pure and Applied Optics 4 (6), S
Journal: Journal of Optics A: Pure and Applied Optics


Physical Review E 62 (4), R
Journal: Physical Review E


Optics Express 18 (103), A451-A
Journal: Optics Express


Science Advances 6 (12), eaay
Journal: Science Advances


Science 367 (6482), eabb
Journal: Science

In [38]:
df4['Source'].value_counts()

Advanced Materials                                         469
The Journal of Physical Chemistry C                        440
Physical Review B                                          372
ACS Energy Letters                                         356
Applied Physics Letters                                    338
                                                          ...
Photonics for Solar Energy Systems VII                       1
Session 1P3b MS-1.9: Light Management for Photovoltaics      1
Photovoltaics, IEEE Journal of                               1
Energy Policy                                                1
Spintronics XIII                                             1
Name: Source, Length: 1853, dtype: int64

In [51]:
df5 = df4.assign(Source = df4['Source'].apply(lambda row: np.char.capitalize(str(row))))

In [52]:
df5['Source'].value_counts()

Advanced materials                                                         522
Applied physics letters                                                    462
The journal of physical chemistry c                                        444
Physical review b                                                          382
Acs energy letters                                                         375
                                                                          ...
Spie opto, 89810b-89810b                                                     1
Optical nanostructures and advanced materials for photovoltaics, pth4a.      1
Spie photonics europe, 91400g-91400g                                         1
Spie solar energy+ technology, 88240a-88240a                                 1
Spintronics xiii                                                             1
Name: Source, Length: 1615, dtype: int64

In [56]:
import re
pattern = r'^([^,]+)'

vals = df5['Source'].values
index = df5['Source'].index

for idx, val in enumerate(df5['Source'].values):

    # match pattern to citation
    match = re.match(pattern, val)

    if match:
        journal = match.group(1)
        
        # print extracted values
        print(val)
        print('Journal:', journal)
        print('\n')
        
        df5.loc[index[idx], 'Source'] = journal
        
    else:
        pass

Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Superconductor science and technology
Journal: Superconductor science and technology


Europhysics letters
Journal: Europhysics letters


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review letters
Journal: Physical review letters


Applied physics letters
Journal: Applied physics letters


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Materials
Journal: Materials


Physical review letters
Journal: Physical review letters


Physical review b
Journal: Physical review b


Measurement science and technology
Journal: Measurement science and technology


Physical review b
Journal: Physical review b


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review letters
Journal: Physical review letters


Physical review b
Journal: Physical review b


Physical review letters(usa)
Journal: Physical review letters(usa)


Measurement science and technology
Journal: Measurement science and technology


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Solid state communications
Journal: Solid state communications


Physics letters a 301 (5-6)
Journal: Physics letters a 301 (5-6)


Journal of physics f: metal physics
Journal: Journal of physics f: metal physics


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Journal of applied physics
Journal: Journal of applied physics


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The european physical journal b-condensed matter and complex systems 18 (1 …
Journal: The european physical journal b-condensed matter and complex systems 18 (1 …


Phys. status solidi (b)
Journal: Phys. status solidi (b)


Physical review b
Journal: Physical review b


Journal of applied physics
Journal: Journal of applied physics


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Solid state communications
Journal: Solid state communications


Physical review b
Journal: Physical review b


Journal of physics and chemistry of solids
Journal: Journal of physics and chemistry of solids


International journal of modern physics b
Journal: International journal of modern physics b


Physical review b
Journal: Physical review b


Journal of applied physics
Journal: Journal of applied physics


Physical review b
Journal: Physical review b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review b
Journal: Physical review b


Journal of applied physics
Journal: Journal of applied physics


Physical review b
Journal: Physical review b


Ferroelectrics
Journal: Ferroelectrics


Physical review b
Journal: Physical review b


Solid state communications
Journal: Solid state communications


Zeitschrift für physikalische chemie
Journal: Zeitschrift für physikalische chemie


Ceramics international
Journal: Ceramics international


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Journal of physics f: metal physics
Journal: Journal of physics f: metal physics


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Le journal de physique colloques 44 (c9), c9-403-c
Journal: Le journal de physique colloques 44 (c9)


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Physical review b
Journal: Physical review b


Journal of applied physics 109 (7),
Journal: Journal of applied physics 109 (7)


Solid state communications
Journal: Solid state communications


Phys. rev. b
Journal: Phys. rev. b


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Materials science and engineering: a
Journal: Materials science and engineering: a


Solid state communications
Journal: Solid state communications


Solid state communications
Journal: Solid state communications


Physical review b
Journal: Physical review b


Journal of alloys and compounds 231 (1-2)
Journal: Journal of alloys and compounds 231 (1-2)


Physical review b
Journal: Physical review b


Physica c: superconductivity
Journal: Physica c: superconductivity


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Challenges
Journal: Challenges


Phase transitions
Journal: Phase transitions


Journal of alloys and compounds 433 (1-2)
Journal: Journal of alloys and compounds 433 (1-2)


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Solid state communications
Journal: Solid state communications


Scripta metallurgica
Journal: Scripta metallurgica


International journal of modern physics b 14 (25n27)
Journal: International journal of modern physics b 14 (25n27)


International journal of modern physics b 13 (09n10)
Journal: International journal of modern physics b 13 (09n10)


Physica c: superconductivity
Journal: Physica c: superconductivity


Solid state phenomena
Journal: Solid state phenomena


Applied physics letters
Journal: Applied physics letters


Ferroelectrics
Journal: Ferroelectrics


Materials
Journal: Materials


Journal of applied physics
Journal: Journal of applied physics


Materials science and engineering: a
Journal: Materials science and engineering: a


Journal of magnetism and magnetic materials 272, e1047-
Journal: Journal of magnetism and magnetic materials 272


Journal of alloys and compounds 310 (1-2)
Journal: Journal of alloys and compounds 310 (1-2)


Ceramics
Journal: Ceramics


Materials research
Journal: Materials research


Journal of applied physics
Journal: Journal of applied physics


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Ferroelectrics
Journal: Ferroelectrics


Materials science and engineering: b
Journal: Materials science and engineering: b


Journal of alloys and compounds 310 (1-2)
Journal: Journal of alloys and compounds 310 (1-2)


Nanomaterials
Journal: Nanomaterials


Journal of alloys and compounds 438 (1-2)
Journal: Journal of alloys and compounds 438 (1-2)


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


International journal of modern physics b 17 (04n06)
Journal: International journal of modern physics b 17 (04n06)


Journal of alloys and compounds
Journal: Journal of alloys and compounds


International journal of modern physics b 14 (25n27)
Journal: International journal of modern physics b 14 (25n27)


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Le journal de physique iv 6 (c8), c8-39-c
Journal: Le journal de physique iv 6 (c8)


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Physica c: superconductivity
Journal: Physica c: superconductivity


Zeitschrift für physikalische chemie
Journal: Zeitschrift für physikalische chemie


Archives of metallurgy and materials
Journal: Archives of metallurgy and materials


Solid state phenomena
Journal: Solid state phenomena


Physical review b
Journal: Physical review b


Solid state phenomena
Journal: Solid state phenomena


Ferroelectrics
Journal: Ferroelectrics


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Le journal de physique iv 6 (c8), c8-13-c
Journal: Le journal de physique iv 6 (c8)


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Physical review letters
Journal: Physical review letters


Le journal de physique colloques 48 (c8), c8-227-c
Journal: Le journal de physique colloques 48 (c8)


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Solid state phenomena
Journal: Solid state phenomena


Physical review b
Journal: Physical review b


Journal of superconductivity
Journal: Journal of superconductivity


Measurement science and technology
Journal: Measurement science and technology


Journal of alloys and compounds 310 (1-2)
Journal: Journal of alloys and compounds 310 (1-2)


Journal of alloys and compounds 310 (1-2)
Journal: Journal of alloys and compounds 310 (1-2)


Physica status solidi (b)
Journal: Physica status solidi (b)


Physica c: superconductivity
Journal: Physica c: superconductivity


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Journal de physique(france) iv(france)
Journal: Journal de physique(france) iv(france)


Journal of advanced science 7 (3-4)
Journal: Journal of advanced science 7 (3-4)


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Solid state communications
Journal: Solid state communications


Crystals
Journal: Crystals


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Physical review research
Journal: Physical review research


Journal of alloys and compounds
Journal: Journal of alloys and compounds


International journal of materials research
Journal: International journal of materials research


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Low temperature physics
Journal: Low temperature physics


Journal of applied physics
Journal: Journal of applied physics


Journal of applied physics
Journal: Journal of applied physics


Physica. c, superconductivity
Journal: Physica. c


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Advances in science and technology
Journal: Advances in science and technology


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Physica. c, superconductivity
Journal: Physica. c


Physica c: superconductivity
Journal: Physica c: superconductivity


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Solid state communications
Journal: Solid state communications


Physical review b
Journal: Physical review b


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


International journal of modern physics b 17 (04n06)
Journal: International journal of modern physics b 17 (04n06)


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Stripes and related phenomena
Journal: Stripes and related phenomena


International journal of modern physics b 14 (29n31)
Journal: International journal of modern physics b 14 (29n31)


Solid state communications
Journal: Solid state communications


Physica c: superconductivity
Journal: Physica c: superconductivity


Physica c: superconductivity
Journal: Physica c: superconductivity


International journal of modern physics b 14 (25n27)
Journal: International journal of modern physics b 14 (25n27)


International journal of modern physics b 14 (25n27)
Journal: International journal of modern physics b 14 (25n27)


Gravitational wave detection ii
Journal: Gravitational wave detection ii


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Journal of alloys and compounds
Journal: Journal of alloys and compounds


International journal of modern physics b 13 (conf-9810174-)
Journal: International journal of modern physics b 13 (conf-9810174-)


International journal of modern physics b
Journal: International journal of modern physics b


Journal of alloys and compounds(switzerland)
Journal: Journal of alloys and compounds(switzerland)


Il nuovo cimento d
Journal: Il nuovo cimento d


Physica c
Journal: Physica c


Physica c: superconductivity
Journal: Physica c: superconductivity


Il nuovo cimento d
Journal: Il nuovo cimento d


Physica c: superconductivity and its applications
Journal: Physica c: superconductivity and its applications


Physical review, b: condensed matter
Journal: Physical review


Le journal de physique iv 6 (c8), c8-469-c
Journal: Le journal de physique iv 6 (c8)


Journal of advanced science 7 (3-4)
Journal: Journal of advanced science 7 (3-4)


Physica c: superconductivity
Journal: Physica c: superconductivity


Physica c: superconductivity
Journal: Physica c: superconductivity


Physica c: superconductivity;(netherlands)
Journal: Physica c: superconductivity;(netherlands)


Physical review, b: condensed matter;(usa)
Journal: Physical review


Phys. rev. b: condens. matter;(united states)
Journal: Phys. rev. b: condens. matter;(united states)


Physical review b
Journal: Physical review b


Journal of the less common metals
Journal: Journal of the less common metals


Journal of the less common metals
Journal: Journal of the less common metals


Jpn. j. appl. phys. 1
Journal: Jpn. j. appl. phys. 1


Japanese journal of applied physics 26 (s3-1)
Journal: Japanese journal of applied physics 26 (s3-1)


Physical review b
Journal: Physical review b


Zeitschrift für physikalische chemie 145 (1-2)
Journal: Zeitschrift für physikalische chemie 145 (1-2)


Journal of the less-common metals
Journal: Journal of the less-common metals


Energy &environmental science
Journal: Energy &environmental science


Nature photonics
Journal: Nature photonics


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


Energy &environmental science
Journal: Energy &environmental science


Acs energy letters
Journal: Acs energy letters


Organic electronics
Journal: Organic electronics


Journal of applied physics
Journal: Journal of applied physics


Matter
Journal: Matter


Http://dspace.mit.edu/handle/1721.1/
Journal: Http://dspace.mit.edu/handle/1721.1/


Joule
Journal: Joule


Physical review applied
Journal: Physical review applied


Joule
Journal: Joule


Applied physics letters
Journal: Applied physics letters


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Physical review b
Journal: Physical review b


Nature energy
Journal: Nature energy


New journal of physics
Journal: New journal of physics


Advanced materials
Journal: Advanced materials


Materials today
Journal: Materials today


Journal of materials chemistry
Journal: Journal of materials chemistry


Advanced functional materials
Journal: Advanced functional materials


Advanced materials
Journal: Advanced materials


Chemistry of materials
Journal: Chemistry of materials


Inorganic chemistry
Journal: Inorganic chemistry


Acs photonics
Journal: Acs photonics


Journal of the american chemical society
Journal: Journal of the american chemical society


Nano letters
Journal: Nano letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Advanced energy materials
Journal: Advanced energy materials


Chemistry of materials
Journal: Chemistry of materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of materials chemistry
Journal: Journal of materials chemistry


Chemistry-a european journal
Journal: Chemistry-a european journal


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Dalton transactions
Journal: Dalton transactions


Advanced energy materials
Journal: Advanced energy materials


Advanced optical materials
Journal: Advanced optical materials


Reports on progress in physics
Journal: Reports on progress in physics


Nano letters
Journal: Nano letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Dalton transactions
Journal: Dalton transactions


Acs photonics
Journal: Acs photonics


Advanced materials technologies
Journal: Advanced materials technologies


Dalton transactions
Journal: Dalton transactions


Journal of materials chemistry
Journal: Journal of materials chemistry


Journal of the society for information display
Journal: Journal of the society for information display


Nano letters
Journal: Nano letters


Ieee transactions on applied superconductivity
Journal: Ieee transactions on applied superconductivity


Advanced optical materials
Journal: Advanced optical materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Crystal growth &design
Journal: Crystal growth &design


Advanced optical materials
Journal: Advanced optical materials


Advanced optical materials
Journal: Advanced optical materials


Crystal growth &design
Journal: Crystal growth &design


Advanced functional materials
Journal: Advanced functional materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Organic electronics
Journal: Organic electronics


Journal of the society for information display
Journal: Journal of the society for information display


Dalton transactions
Journal: Dalton transactions


Journal of nanoscience and nanotechnology
Journal: Journal of nanoscience and nanotechnology


Flexible and printed electronics
Journal: Flexible and printed electronics


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Beilstein journal of organic chemistry
Journal: Beilstein journal of organic chemistry


Advanced optical materials
Journal: Advanced optical materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Advanced materials
Journal: Advanced materials


Advanced optical materials
Journal: Advanced optical materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Organic light emitting materials and devices xvi
Journal: Organic light emitting materials and devices xvi


The journal of physical chemistry b
Journal: The journal of physical chemistry b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Carbon
Journal: Carbon


Applied surface science
Journal: Applied surface science


Plant cell reports
Journal: Plant cell reports


Biosensors and bioelectronics
Journal: Biosensors and bioelectronics


International journal of hydrogen energy
Journal: International journal of hydrogen energy


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Holz als roh-und werkstoff
Journal: Holz als roh-und werkstoff


Carbon
Journal: Carbon


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics



The journal of physical chemistry c
Journal: The journal of physical chemistry c


Applied physics b
Journal: Applied physics b


Journal of applied physics
Journal: Journal of applied physics


Nanomaterials
Journal: Nanomaterials


Applied physics letters
Journal: Applied physics letters


Journal of polymers
Journal: Journal of polymers


Journal of optics a: pure and applied optics
Journal: Journal of optics a: pure and applied optics


Physical review b
Journal: Physical review b


Physica status solidi (b)
Journal: Physica status solidi (b)


Molecules
Journal: Molecules


Applied sciences
Journal: Applied sciences


Applied physics letters
Journal: Applied physics letters


Molecules
Journal: Molecules


Thin solid films
Journal: Thin solid films


Physica status solidi (c)
Journal: Physica status solidi (c)


Optical materials
Journal: Optical materials


Physical review b
Journal: Physical review b


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Molecules
Journal: Molecules


Molecules
Journal: Molecules


Journal of luminescence
Journal: Journal of luminescence


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Microelectronic engineering
Journal: Microelectronic engineering


Physical review b
Journal: Physical review b


Nanoscale
Journal: Nanoscale


Applied physics letters
Journal: Applied physics letters


Journal of luminescence
Journal: Journal of luminescence


Micron
Journal: Micron


Synthetic metals
Journal: Synthetic metals


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physica status solidi (a)
Journal: Physica status solidi (a)


Optics &laser technology
Journal: Optics &laser technology


Journal of physical chemistry b
Journal: Journal of physical chemistry b


Photonic materials, devices, and applications
Journal: Photonic materials


Brazilian journal of physics
Journal: Brazilian journal of physics


Synthetic metals
Journal: Synthetic metals


Nanomaterials
Journal: Nanomaterials


Optical materials: x
Journal: Optical materials: x


Education sciences
Journal: Education sciences


Journal of polymer science part b: polymer physics
Journal: Journal of polymer science part b: polymer physics


International scholarly research notices
Journal: International scholarly research notices


Rsc advances
Journal: Rsc advances


Applied physics letters
Journal: Applied physics letters


Physica status solidi (a)
Journal: Physica status solidi (a)


Advanced optical materials
Journal: Advanced optical materials


Nanomaterials
Journal: Nanomaterials


Biosensors
Journal: Biosensors


Nanomaterials
Journal: Nanomaterials


Current physical chemistry
Journal: Current physical chemistry


Applied physics letters
Journal: Applied physics letters


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Bioconjugate chem
Journal: Bioconjugate chem


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Physical review letters
Journal: Physical review letters


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Physica status solidi-a-applied research
Journal: Physica status solidi-a-applied research


Physica status solidi-a-applied research
Journal: Physica status solidi-a-applied research


Physica status solidi-b-basic research
Journal: Physica status solidi-b-basic research


Nano letters
Journal: Nano letters


Nature photonics
Journal: Nature photonics


Chemistry of materials
Journal: Chemistry of materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Nature materials
Journal: Nature materials


Acs nano
Journal: Acs nano


Acs applied nano materials
Journal: Acs applied nano materials


Acs nano
Journal: Acs nano


Energy &environmental science
Journal: Energy &environmental science


Journal of the american chemical society
Journal: Journal of the american chemical society


Mendeleev communications
Journal: Mendeleev communications


Nature materials
Journal: Nature materials


Nature communications
Journal: Nature communications


Nano letters
Journal: Nano letters


Science advances
Journal: Science advances


Acs nano
Journal: Acs nano


Physical review letters
Journal: Physical review letters


Acs applied nano materials
Journal: Acs applied nano materials


Acs nano
Journal: Acs nano


Advanced optical materials
Journal: Advanced optical materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs central science
Journal: Acs central science


Russian chemical reviews
Journal: Russian chemical reviews


Acs nano
Journal: Acs nano


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


Applied physics letters
Journal: Applied physics letters


Chemistry of materials
Journal: Chemistry of materials


Acs nano
Journal: Acs nano


Physics letters a
Journal: Physics letters a


Science
Journal: Science


Nano letters
Journal: Nano letters


Laser physics letters
Journal: Laser physics letters


Advanced materials interfaces
Journal: Advanced materials interfaces


Mendeleev communications
Journal: Mendeleev communications


Advanced materials
Journal: Advanced materials


Frontiers in chemistry
Journal: Frontiers in chemistry


Nano letters
Journal: Nano letters


Energy technology
Journal: Energy technology


Nature communications
Journal: Nature communications


Chemistry of materials
Journal: Chemistry of materials


Journal of russian laser research
Journal: Journal of russian laser research


Journal of materials research
Journal: Journal of materials research


Optical materials express
Journal: Optical materials express


Nano letters
Journal: Nano letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Inorganic materials
Journal: Inorganic materials


Mendeleev communications
Journal: Mendeleev communications


Advanced materials technologies
Journal: Advanced materials technologies


Semiconductors
Journal: Semiconductors


Cell reports physical science
Journal: Cell reports physical science


Acs energy letters
Journal: Acs energy letters


Optical materials express
Journal: Optical materials express


Chemistry squared
Journal: Chemistry squared


Journal of optical technology
Journal: Journal of optical technology


Nano letters
Journal: Nano letters


Superlattices and microstructures
Journal: Superlattices and microstructures


Nano letters
Journal: Nano letters


Nanoscale advances
Journal: Nanoscale advances


Jetp letters
Journal: Jetp letters


Journal of russian laser research
Journal: Journal of russian laser research


Physical review b
Journal: Physical review b


Advanced electronic materials
Journal: Advanced electronic materials


Advanced optical materials
Journal: Advanced optical materials


Journal of analytical atomic spectrometry
Journal: Journal of analytical atomic spectrometry


Advanced materials technologies
Journal: Advanced materials technologies


Advanced materials
Journal: Advanced materials


Micro and nano engineering
Journal: Micro and nano engineering


Cleo: qels_fundamental science, fth4a.
Journal: Cleo: qels_fundamental science


Organic photonics and photovoltaics
Journal: Organic photonics and photovoltaics


Advanced materials
Journal: Advanced materials


Nature materials
Journal: Nature materials


Acta crystallographica a-foundation and advances 71, s90-s
Journal: Acta crystallographica a-foundation and advances 71


Semiconductors
Journal: Semiconductors


Neorganicheskie materialy
Journal: Neorganicheskie materialy


Journal of catalysis
Journal: Journal of catalysis


Inorganic chemistry
Journal: Inorganic chemistry


Surface and coatings technology
Journal: Surface and coatings technology


Renewable energy
Journal: Renewable energy


Physical review b
Journal: Physical review b


Acta materialia
Journal: Acta materialia


Plasma processes and polymers
Journal: Plasma processes and polymers


Acta materialia
Journal: Acta materialia


Solid state sciences
Journal: Solid state sciences


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review b
Journal: Physical review b


Spin
Journal: Spin


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Surface and coatings technology
Journal: Surface and coatings technology


Acta materialia
Journal: Acta materialia


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Thin solid films
Journal: Thin solid films


Materials
Journal: Materials


Vacuum
Journal: Vacuum


Solid state sciences
Journal: Solid state sciences


Apl materials
Journal: Apl materials


Solid state sciences
Journal: Solid state sciences


Surface and coatings technology
Journal: Surface and coatings technology


Applied physics letters
Journal: Applied physics letters


Chemistry of materials
Journal: Chemistry of materials


Acta materialia
Journal: Acta materialia


Physical review b
Journal: Physical review b


Journal of electronic materials
Journal: Journal of electronic materials


Langmuir
Journal: Langmuir


Nano energy
Journal: Nano energy


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Thermochimica acta 457 (1-2)
Journal: Thermochimica acta 457 (1-2)


Acta materialia
Journal: Acta materialia


Solid state sciences
Journal: Solid state sciences


Apl materials
Journal: Apl materials


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Faraday discusions
Journal: Faraday discusions


Journal of electronic materials
Journal: Journal of electronic materials


Advanced functional materials
Journal: Advanced functional materials


Inorganic chemistry
Journal: Inorganic chemistry


Physical review letters
Journal: Physical review letters


Materials chemistry and physics
Journal: Materials chemistry and physics


Coatings
Journal: Coatings


Scientific reports
Journal: Scientific reports


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Aerosol science and technology
Journal: Aerosol science and technology


Applied physics letters
Journal: Applied physics letters


Solid state sciences
Journal: Solid state sciences


Cellulose
Journal: Cellulose


Solid state communications
Journal: Solid state communications


Journal of materials research
Journal: Journal of materials research


Physica status solidi (rrl)–rapid research letters
Journal: Physica status solidi (rrl)–rapid research letters


Journal of electronic materials
Journal: Journal of electronic materials


Applied physics letters
Journal: Applied physics letters


Aip advances
Journal: Aip advances


Inorganic chemistry
Journal: Inorganic chemistry


Journal of materials chemistry
Journal: Journal of materials chemistry


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Acta materialia
Journal: Acta materialia


Solid-solid phase transformations in inorganic material
Journal: Solid-solid phase transformations in inorganic material


Journal of nuclear materials
Journal: Journal of nuclear materials


Rare metals
Journal: Rare metals


Nano letters
Journal: Nano letters


Applied physics letters
Journal: Applied physics letters


Nanotechnology
Journal: Nanotechnology


Journal of applied physics
Journal: Journal of applied physics


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Physical review b
Journal: Physical review b


Semiconductor science and technology
Journal: Semiconductor science and technology


Journal of materials research
Journal: Journal of materials research


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Crystal research and technology
Journal: Crystal research and technology


Journal of the korean ceramic society
Journal: Journal of the korean ceramic society


Journal of applied physics
Journal: Journal of applied physics


Nanotechnology
Journal: Nanotechnology


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Electrochimica acta
Journal: Electrochimica acta


Journal of applied physics
Journal: Journal of applied physics


Entropy
Journal: Entropy


Chimia
Journal: Chimia


Physica status solidi (a)
Journal: Physica status solidi (a)


Coatings
Journal: Coatings


Zeitschrift für anorganische und allgemeine chemie
Journal: Zeitschrift für anorganische und allgemeine chemie


Journal of crystal growth
Journal: Journal of crystal growth


Crystal growth &design
Journal: Crystal growth &design


Polymer
Journal: Polymer


Applied physics letters
Journal: Applied physics letters


Materials
Journal: Materials


Angewandte chemie
Journal: Angewandte chemie


Science and technology of advanced materials
Journal: Science and technology of advanced materials


Rsc adv.
Journal: Rsc adv.


Nanotechnology
Journal: Nanotechnology


Journal of alloys and compounds 509 (supplement 1), s364-s
Journal: Journal of alloys and compounds 509 (supplement 1)


Apl materials
Journal: Apl materials


Thin solid films
Journal: Thin solid films


Phys. rev. b
Journal: Phys. rev. b


Physica status solidi@rrl doi: 10.1002/pssr.
Journal: Physica status solidi@rrl doi: 10.1002/pssr.


Mtz-motortechnische zeitschrift
Journal: Mtz-motortechnische zeitschrift


Book "advances in electronic ceramics"
Journal: Book "advances in electronic ceramics"


Superficies y vacío
Journal: Superficies y vacío


Advanced electronic materials
Journal: Advanced electronic materials


Applied physics letters
Journal: Applied physics letters


Int. j. of advanced applied physics research
Journal: Int. j. of advanced applied physics research


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Thin solid films
Journal: Thin solid films


Mtz worldwide
Journal: Mtz worldwide


Current applied physics
Journal: Current applied physics


Anales de la asociacion quimica argentina
Journal: Anales de la asociacion quimica argentina


Nanotechnology
Journal: Nanotechnology


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Frontiers in nanotechnology
Journal: Frontiers in nanotechnology


Matéria (rio de janeiro)
Journal: Matéria (rio de janeiro)


Matéria (rio de janeiro)
Journal: Matéria (rio de janeiro)


Applied physics letters
Journal: Applied physics letters


Research@ ua
Journal: Research@ ua


Catalysis today (print)
Journal: Catalysis today (print)


Journal of physics. d, applied physics
Journal: Journal of physics. d


Thermoelektrik
Journal: Thermoelektrik


Zeitschrift für anorganische und allgemeine chemie
Journal: Zeitschrift für anorganische und allgemeine chemie


Journal of applied physics
Journal: Journal of applied physics


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Inorganic chemistry
Journal: Inorganic chemistry


Solid-state chemistry of inorganic materials iv: volume 755
Journal: Solid-state chemistry of inorganic materials iv: volume 755


Journal of crystal growth 254 (3-4)
Journal: Journal of crystal growth 254 (3-4)


Solid state sciences
Journal: Solid state sciences


Solid state sciences
Journal: Solid state sciences


Revista mexicana de física
Journal: Revista mexicana de física


Advanced energy materials
Journal: Advanced energy materials


Nature materials
Journal: Nature materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced energy materials
Journal: Advanced energy materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Chemical society reviews
Journal: Chemical society reviews


Acs energy letters
Journal: Acs energy letters


Advanced materials interfaces
Journal: Advanced materials interfaces


Acs energy letters
Journal: Acs energy letters


Acs applied energy materials
Journal: Acs applied energy materials


The journal of organic chemistry
Journal: The journal of organic chemistry


Organic letters
Journal: Organic letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Macromolecules
Journal: Macromolecules


Advanced functional materials
Journal: Advanced functional materials


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Dalton transactions
Journal: Dalton transactions


Dalton transactions
Journal: Dalton transactions


Macromolecular symposia
Journal: Macromolecular symposia


Organic electronics
Journal: Organic electronics


Silicon
Journal: Silicon


Vacuum
Journal: Vacuum


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Sustainable energy &fuels
Journal: Sustainable energy &fuels


Canadian journal of chemistry
Journal: Canadian journal of chemistry


Science
Journal: Science


Nature communications
Journal: Nature communications


Nature communications
Journal: Nature communications


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Langmuir
Journal: Langmuir


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Acs catalysis
Journal: Acs catalysis


Advanced materials
Journal: Advanced materials


Nanoscale
Journal: Nanoscale


Acs catalysis
Journal: Acs catalysis


Catalysis communications
Journal: Catalysis communications


Scientific reports
Journal: Scientific reports


Catalysts
Journal: Catalysts


Catalysis communications
Journal: Catalysis communications


International journal of hydrogen energy
Journal: International journal of hydrogen energy


Electrochem
Journal: Electrochem


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of electroanalytical chemistry
Journal: Journal of electroanalytical chemistry


Electrochimica acta
Journal: Electrochimica acta


Crystengcomm
Journal: Crystengcomm


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Materials today chemistry
Journal: Materials today chemistry


International journal of hydrogen energy
Journal: International journal of hydrogen energy


International journal of hydrogen energy
Journal: International journal of hydrogen energy


Acs applied energy materials
Journal: Acs applied energy materials


Journal of the american ceramic society

Advanced optical materials
Journal: Advanced optical materials


Nanoscale
Journal: Nanoscale


Laser physics letters
Journal: Laser physics letters


Nanoscale
Journal: Nanoscale


Computational materials science
Journal: Computational materials science


Quantum electronics
Journal: Quantum electronics


Applied surface science
Journal: Applied surface science


Applied physics a
Journal: Applied physics a


Applied physics letters
Journal: Applied physics letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nanophotonics
Journal: Nanophotonics


Jetp letters
Journal: Jetp letters


Nano letters
Journal: Nano letters


Laser &photonics reviews
Journal: Laser &photonics reviews


Applied surface science
Journal: Applied surface science


Laser physics letters
Journal: Laser physics letters


Journal of experimental and theoretical physics
Journal: Journal of experimental and theoretical physics


Laser physics letters
Journal: Laser physics letters


Optics letters
Journal: Optics letters


Spectrochimica acta part b: atomic spectroscopy
Journal: Spectrochimica acta part b: atomic spectroscopy


Nano letters
Journal: Nano letters


Applied surface science
Journal: Applied surface science


Laser physics letters
Journal: Laser physics letters


Applied surface science
Journal: Applied surface science


Applied physics a
Journal: Applied physics a


Jetp letters
Journal: Jetp letters


Quantum electronics
Journal: Quantum electronics


Polymer science series ac/c of vysokomolekuliarnye soedineniia
Journal: Polymer science series ac/c of vysokomolekuliarnye soedineniia


Applied surface science
Journal: Applied surface science


Laser physics letters
Journal: Laser physics letters


Advanced optical materials
Journal: Advanced optical materials


Photonics and nanostructures-fundamentals and applications
Journal: Photonics and nanostructures-fundamentals and applications


Jetp letters
Journal: Jetp letters


Optics communications
Journal: Optics communications


Laser &photonics reviews
Journal: Laser &photonics reviews


Nano letters
Journal: Nano letters


Computational materials science
Journal: Computational materials science


Nanoscale
Journal: Nanoscale


Optics express
Journal: Optics express


Applied physics b
Journal: Applied physics b


Jetp letters
Journal: Jetp letters


Macroheterocycles
Journal: Macroheterocycles


Nanophotonics
Journal: Nanophotonics


Applied physics express
Journal: Applied physics express


Nano letters
Journal: Nano letters


Laser physics letters
Journal: Laser physics letters


Russian physics journal
Journal: Russian physics journal


Nano energy
Journal: Nano energy


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Physical review applied
Journal: Physical review applied


Optical materials express
Journal: Optical materials express


Jetp letters
Journal: Jetp letters


Jetp letters
Journal: Jetp letters


Laser physics letters
Journal: Laser physics letters


Chemical reviews
Journal: Chemical reviews


Applied physics letters
Journal: Applied physics letters


Applied surface science
Journal: Applied surface science


Jetp letters
Journal: Jetp letters


Russian physics journal
Journal: Russian physics journal


Nanomaterials
Journal: Nanomaterials


Acs nano
Journal: Acs nano


Laser &photonics reviews
Journal: Laser &photonics reviews


Optical materials express
Journal: Optical materials express


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemistry of materials
Journal: Chemistry of materials


Nanomaterials
Journal: Nanomaterials


Applied physics letters
Journal: Applied physics letters


Acs photonics
Journal: Acs photonics


Nanomaterials
Journal: Nanomaterials


Jetp letters
Journal: Jetp letters


Nanomaterials
Journal: Nanomaterials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of luminescence
Journal: Journal of luminescence


Jetp letters
Journal: Jetp letters


Surface and coatings technology
Journal: Surface and coatings technology


Laser physics letters
Journal: Laser physics letters


Bulletin of the russian academy of sciences: physics
Journal: Bulletin of the russian academy of sciences: physics


Laser &photonics reviews
Journal: Laser &photonics reviews


Advanced photonics research
Journal: Advanced photonics research


Jetp letters
Journal: Jetp letters


Quantum electronics
Journal: Quantum electronics


Russian physics journal
Journal: Russian physics journal


Nanophotonics
Journal: Nanophotonics


Acs applied nano materials
Journal: Acs applied nano materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Chinese physics b
Journal: Chinese physics b


Journal of experimental and theoretical physics
Journal: Journal of experimental and theoretical physics


Quantum electronics
Journal: Quantum electronics


Quantum electronics
Journal: Quantum electronics


Bulletin of the lebedev physics institute
Journal: Bulletin of the lebedev physics institute


Polymer science-series a
Journal: Polymer science-series a


Nano letters
Journal: Nano letters


Advanced photonics research
Journal: Advanced photonics research


Photonics research
Journal: Photonics research


Nanomaterials
Journal: Nanomaterials


Jetp letters
Journal: Jetp letters


Nanomaterials
Journal: Nanomaterials


Laser &photonics reviews
Journal: Laser &photonics reviews


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Technical physics
Journal: Technical physics


Technical physics
Journal: Technical physics


Bulletin of the russian academy of sciences: physics
Journal: Bulletin of the russian academy of sciences: physics


Nanomaterials
Journal: Nanomaterials


Acs applied bio materials
Journal: Acs applied bio materials


Applied materials today
Journal: Applied materials today


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Journal of the neurological sciences
Journal: Journal of the neurological sciences


Acs photonics
Journal: Acs photonics


Bulletin of the russian academy of sciences: physics
Journal: Bulletin of the russian academy of sciences: physics


Chinese physics b
Journal: Chinese physics b


Optical materials: x
Journal: Optical materials: x


Nanomaterials
Journal: Nanomaterials


Applied materials today
Journal: Applied materials today


Semiconductors
Journal: Semiconductors


Silicon photonics and photonic integrated circuits ii
Journal: Silicon photonics and photonic integrated circuits ii


Applied surface science, doi.org/10.1016/j.apsusc.2017.07.
Journal: Applied surface science


Pharmaceutics
Journal: Pharmaceutics


Advanced optical materials
Journal: Advanced optical materials


Materials
Journal: Materials


Laser &photonics reviews
Journal: Laser &photonics reviews


Photonics and nanostructures-fundamentals and applications
Journal: Photonics and nanostructures-fundamentals and applications


Bulletin of the russian academy of sciences: physics
Journal: Bulletin of the russian academy of sciences: physics


Bulletin of the russian academy of sciences: physics
Journal: Bulletin of the russian academy of sciences: physics


Bulletin of the russian academy of sciences: physics
Journal: Bulletin of the russian academy of sciences: physics


Bulletin of the russian academy of sciences: physics
Journal: Bulletin of the russian academy of sciences: physics


Bulletin of the russian academy of sciences: physics
Journal: Bulletin of the russian academy of sciences: physics


Bulletin of the russian academy of sciences: physics
Journal: Bulletin of the russian academy of sciences: physics


Bulletin of the russian academy of sciences: physics
Journal: Bulletin of the russian academy of sciences: physics


Applied physics letters
Journal: Applied physics letters


International journal of molecular sciences
Journal: International journal of molecular sciences


Energy technology
Journal: Energy technology


Cleo: qels_fundamental science, ff1a.
Journal: Cleo: qels_fundamental science


Acs photonics
Journal: Acs photonics


Applied physics letters
Journal: Applied physics letters


Optical materials express
Journal: Optical materials express


Optical materials express
Journal: Optical materials express


Optical materials express
Journal: Optical materials express


Advances in optics and photonics
Journal: Advances in optics and photonics


Advances in optics and photonics
Journal: Advances in optics and photonics


Plasma physics and controlled fusion
Journal: Plasma physics and controlled fusion


Journal of the neurological sciences
Journal: Journal of the neurological sciences


Journal of the neurological sciences
Journal: Journal of the neurological sciences


Cleo: science and innovations, stu1c.
Journal: Cleo: science and innovations


Nonlinear optics and applications xii
Journal: Nonlinear optics and applications xii


Advanced optical materials
Journal: Advanced optical materials


Laser &photonics reviews
Journal: Laser &photonics reviews


Frontiers in optics, fth5d.
Journal: Frontiers in optics


Nonlinear photonics, npm3e.
Journal: Nonlinear photonics


9й международный семинар по волоконным лазерам
Journal: 9й международный семинар по волоконным лазерам


Nanophotonics vii
Journal: Nanophotonics vii


Fundamental bases of mechanochemical technologies
Journal: Fundamental bases of mechanochemical technologies


Pis' ma v zhurnal èksperimental'noi i teoreticheskoi fiziki
Journal: Pis' ma v zhurnal èksperimental'noi i teoreticheskoi fiziki


Quantum electronics
Journal: Quantum electronics


Polymer science-series a
Journal: Polymer science-series a


Vysokomolekuliarnye soedineniia
Journal: Vysokomolekuliarnye soedineniia


Высокомолекулярные соединения. серия а
Journal: Высокомолекулярные соединения. серия а


Žurnal tehničeskoj fiziki
Journal: Žurnal tehničeskoj fiziki


Nature energy
Journal: Nature energy


Advanced optical materials
Journal: Advanced optical materials


Science
Journal: Science


Journal of applied physics
Journal: Journal of applied physics


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Chemistry of materials
Journal: Chemistry of materials


Renewable and sustainable energy reviews
Journal: Renewable and sustainable energy reviews


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Optics express
Journal: Optics express


Applied physics reviews
Journal: Applied physics reviews


Journal of applied physics
Journal: Journal of applied physics


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Energies
Journal: Energies


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Journal of applied physics
Journal: Journal of applied physics


Journal of luminescence
Journal: Journal of luminescence


Optics express
Journal: Optics express


Physica status solidi (a)
Journal: Physica status solidi (a)


Solar rrl
Journal: Solar rrl


Physica status solidi (a)
Journal: Physica status solidi (a)


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Energy policy
Journal: Energy policy


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Optica
Journal: Optica


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Optical materials
Journal: Optical materials


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Optics express
Journal: Optics express


New journal of physics
Journal: New journal of physics


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Optics express
Journal: Optics express


Optics express
Journal: Optics express


Physical review b
Journal: Physical review b


Journal of applied physics
Journal: Journal of applied physics


Optics express
Journal: Optics express


Optics express
Journal: Optics express


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Journal of applied physics
Journal: Journal of applied physics


Optics express
Journal: Optics express


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Optics express
Journal: Optics express


Physical review b
Journal: Physical review b


Energy procedia
Journal: Energy procedia


Optics express
Journal: Optics express


Energy procedia
Journal: Energy procedia


Nature materials
Journal: Nature materials


Optics express
Journal: Optics express


Energy procedia
Journal: Energy procedia


Photovoltaics, ieee journal of
Journal: Photovoltaics


Journal of applied physics
Journal: Journal of applied physics


Energy &environmental science
Journal: Energy &environmental science


Optics express
Journal: Optics express


Optics express
Journal: Optics express


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Optics express
Journal: Optics express


Thin solid films
Journal: Thin solid films


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nature communications
Journal: Nature communications


Optics express
Journal: Optics express


Solar rrl
Journal: Solar rrl


Journal of optics
Journal: Journal of optics


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Session 1p3b ms-1.9: light management for photovoltaics
Journal: Session 1p3b ms-1.9: light management for photovoltaics


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Solar rrl
Journal: Solar rrl


Microelectronic engineering
Journal: Microelectronic engineering


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Photonics for solar energy systems vii
Journal: Photonics for solar energy systems vii


Spie photonics europe, 98851a-98851a
Journal: Spie photonics europe


Spie photonics europe, 91400h-91400h
Journal: Spie photonics europe


Journal of applied physics
Journal: Journal of applied physics


Sustainable energy &fuels
Journal: Sustainable energy &fuels


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Optical nanostructures and advanced materials for photovoltaics, pw2a.
Journal: Optical nanostructures and advanced materials for photovoltaics


Spie photonics europe, 98980a-98980a
Journal: Spie photonics europe


Spie optical systems design, 96300g-96300g
Journal: Spie optical systems design


Spie opto, 89810b-89810b
Journal: Spie opto


Optical nanostructures and advanced materials for photovoltaics, pw2b.
Journal: Optical nanostructures and advanced materials for photovoltaics


Optics express
Journal: Optics express


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Optical nanostructures and advanced materials for photovoltaics, pth4a.
Journal: Optical nanostructures and advanced materials for photovoltaics


Spie photonics europe, 91400g-91400g
Journal: Spie photonics europe


Spie solar energy+ technology, 88240a-88240a
Journal: Spie solar energy+ technology


Optical nanostructures and advanced materials for photovoltaics, ptu4b.
Journal: Optical nanostructures and advanced materials for photovoltaics


Cleo: science and innovations, sw1i.
Journal: Cleo: science and innovations


Optical nanostructures and advanced materials for photovoltaics, pt3c.
Journal: Optical nanostructures and advanced materials for photovoltaics


Energie, macht, vernunft
Journal: Energie


Optics express
Journal: Optics express


Journal of applied physics
Journal: Journal of applied physics


Surface and coatings technology
Journal: Surface and coatings technology


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Nature energy
Journal: Nature energy


Photonics for solar energy systems viii
Journal: Photonics for solar energy systems viii


Optical devices and materials for solar energy and solid-state lighting, pt1c.
Journal: Optical devices and materials for solar energy and solid-state lighting


Materials science and condensed matter physics
Journal: Materials science and condensed matter physics


Optical nanostructures and advanced materials for photovoltaics, pm4b.
Journal: Optical nanostructures and advanced materials for photovoltaics


Optical nanostructures and advanced materials for photovoltaics, pw2b.
Journal: Optical nanostructures and advanced materials for photovoltaics


Optics for solar energy, st2a.
Journal: Optics for solar energy


Optics for solar energy, st2a.
Journal: Optics for solar energy


Journal of applied physics
Journal: Journal of applied physics


Energie, macht, vernunft
Journal: Energie


Nature materials
Journal: Nature materials


Nano letters
Journal: Nano letters


Journal of materials research
Journal: Journal of materials research


Applied physics letters
Journal: Applied physics letters


Nano letters
Journal: Nano letters


Nano letters
Journal: Nano letters


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Journal of applied physics
Journal: Journal of applied physics


Journal of materials research
Journal: Journal of materials research


Nano letters
Journal: Nano letters


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Advanced energy materials
Journal: Advanced energy materials


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Applied physics letters
Journal: Applied physics letters


Advanced materials
Journal: Advanced materials


Applied physics letters
Journal: Applied physics letters


Advanced electronic materials
Journal: Advanced electronic materials


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Nano letters
Journal: Nano letters


Journal of applied physics
Journal: Journal of applied physics


Nanoscale
Journal: Nanoscale


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nano letters
Journal: Nano letters


Journal of applied physics
Journal: Journal of applied physics


Journal of applied physics
Journal: Journal of applied physics


2d materials
Journal: 2d materials


Ieee journal of selected topics in quantum electronics
Journal: Ieee journal of selected topics in quantum electronics


Applied physics letters
Journal: Applied physics letters


Physical review b
Journal: Physical review b



Chemistry of materials
Journal: Chemistry of materials


Acs energy letters
Journal: Acs energy letters


Advanced optical materials
Journal: Advanced optical materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Chemical reviews
Journal: Chemical reviews


Nano letters
Journal: Nano letters


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Nano letters
Journal: Nano letters


Nano letters
Journal: Nano letters


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Nano letters
Journal: Nano letters


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Nano letters
Journal: Nano letters


Nano letters
Journal: Nano letters


Nature communications
Journal: Nature communications


Advanced energy materials
Journal: Advanced energy materials


Nano letters
Journal: Nano letters


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


Journal of applied physics
Journal: Journal of applied physics


Acs nano
Journal: Acs nano


Nanoscale
Journal: Nanoscale


Acs energy letters
Journal: Acs energy letters


Acs nano
Journal: Acs nano


Nano letters
Journal: Nano letters


Journal of controlled release
Journal: Journal of controlled release


Acs nano
Journal: Acs nano


Nature communications
Journal: Nature communications


Acs photonics
Journal: Acs photonics


Nano letters
Journal: Nano letters


Translational cancer research
Journal: Translational cancer research


Acs nano
Journal: Acs nano


Apl materials
Journal: Apl materials


Acs photonics
Journal: Acs photonics


Journal of biophotonics
Journal: Journal of biophotonics


Acs energy letters
Journal: Acs energy letters


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced optical materials
Journal: Advanced optical materials


Angewandte chemie
Journal: Angewandte chemie


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced science
Journal: Advanced science


Advanced optical materials
Journal: Advanced optical materials


Journal of luminescence
Journal: Journal of luminescence


Acs nano
Journal: Acs nano


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nano letters
Journal: Nano letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Angewandte chemie
Journal: Angewandte chemie


Chemical communications
Journal: Chemical communications


Physica status solidi c
Journal: Physica status solidi c


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Nano letters
Journal: Nano letters


Advanced optical materials
Journal: Advanced optical materials


Advanced optical materials
Journal: Advanced optical materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Verhandlungen der deutschen physikalischen gesellschaft
Journal: Verhandlungen der deutschen physikalischen gesellschaft


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


Angewandte chemie
Journal: Angewandte chemie


Nature energy
Journal: Nature energy


Nano research
Journal: Nano research


Nature photonics
Journal: Nature photonics


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs nano
Journal: Acs nano


Applied physics reviews
Journal: Applied physics reviews


Energy &environmental science
Journal: Energy &environmental science


Advanced energy materials
Journal: Advanced energy materials


Energy &environmental science
Journal: Energy &environmental science


Acs nano
Journal: Acs nano


American chemical society
Journal: American chemical society


Journal of physical chemistry b
Journal: Journal of physical chemistry b


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Energy &environmental science
Journal: Energy &environmental science


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Nano letters
Journal: Nano letters


Journal of physical chemistry b
Journal: Journal of physical chemistry b


Nature communications
Journal: Nature communications


Acs nano
Journal: Acs nano


Nature communications
Journal: Nature communications


Nano letters
Journal: Nano letters


Applied physics letters
Journal: Applied physics letters


Materials letters
Journal: Materials letters


Journal of physical chemistry b
Journal: Journal of physical chemistry b


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs nano
Journal: Acs nano


Acs catalysis
Journal: Acs catalysis


Nature chemistry
Journal: Nature chemistry


Acs nano
Journal: Acs nano


Acs energy letters
Journal: Acs energy letters


Journal of vacuum science &technology a: vacuum, surfaces, and films 30 (5 …
Journal: Journal of vacuum science &technology a: vacuum


Acs nano
Journal: Acs nano


Chemical reviews
Journal: Chemical reviews


Acs energy letters
Journal: Acs energy letters


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Nano letters
Journal: Nano letters


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


Nature communications
Journal: Nature communications


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Energy &environmental science
Journal: Energy &environmental science


Journal of physical chemistry b
Journal: Journal of physical chemistry b


Nanoscale
Journal: Nanoscale


Nano research
Journal: Nano research


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Journal of physical chemistry c
Journal: Journal of physical chemistry c


Nanoscale horizons
Journal: Nanoscale horizons


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review b
Journal: Physical review b


Acs nano
Journal: Acs nano


Journal of photochemistry and photobiology a: chemistry 142 (2-3)
Journal: Journal of photochemistry and photobiology a: chemistry 142 (2-3)


Acs nano
Journal: Acs nano


Physical review b
Journal: Physical review b


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs nano
Journal: Acs nano


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Energy &environmental science
Journal: Energy &environmental science


Acs nano
Journal: Acs nano


Nano letters
Journal: Nano letters


Journal of alloys and compounds 454 (1-2)
Journal: Journal of alloys and compounds 454 (1-2)


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs energy letters
Journal: Acs energy letters


Advanced electronic materials
Journal: Advanced electronic materials


Acs energy letters
Journal: Acs energy letters


Science advances
Journal: Science advances


Nano energy
Journal: Nano energy


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Journal of the american chemical society
Journal: Journal of the american chemical society


Materials horizons
Journal: Materials horizons


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Review of scientific instruments
Journal: Review of scientific instruments


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Energy &environmental science
Journal: Energy &environmental science


Nanoscale
Journal: Nanoscale


Acs nano
Journal: Acs nano


Journal of vacuum science &technology b, nanotechnology and …
Journal: Journal of vacuum science &technology b


Advanced materials
Journal: Advanced materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nature photonics
Journal: Nature photonics


Dalton transactions
Journal: Dalton transactions


Applied physics letters
Journal: Applied physics letters


Advanced functional materials
Journal: Advanced functional materials


Journal of energy chemistry
Journal: Journal of energy chemistry


Acs nano
Journal: Acs nano


Acs energy letters
Journal: Acs energy letters


Advanced electronic materials
Journal: Advanced electronic materials


Journal of applied physics
Journal: Journal of applied physics


Nanoscale
Journal: Nanoscale


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nanoscale
Journal: Nanoscale


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Nanoscale
Journal: Nanoscale


Energy &environmental science
Journal: Energy &environmental science


Acs applied electronic materials
Journal: Acs applied electronic materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced functional materials
Journal: Advanced functional materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Acs photonics
Journal: Acs photonics


Nanoscale
Journal: Nanoscale


Acs nano
Journal: Acs nano


Advanced electronic materials
Journal: Advanced electronic materials


Nano letters
Journal: Nano letters


Applied physics letters
Journal: Applied physics letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of applied physics
Journal: Journal of applied physics


Materials horizons
Journal: Materials horizons


Journal of materials research
Journal: Journal of materials research


Acs applied polymer materials
Journal: Acs applied polymer materials


Acs energy letters
Journal: Acs energy letters


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


Acs applied nano materials
Journal: Acs applied nano materials


Nanoscale
Journal: Nanoscale


Physical chemistry of interfaces and nanomaterials iv
Journal: Physical chemistry of interfaces and nanomaterials iv


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of crystal growth
Journal: Journal of crystal growth


Thin solid films
Journal: Thin solid films


Nature energy
Journal: Nature energy


Nature communications
Journal: Nature communications


Journal of the american chemical society
Journal: Journal of the american chemical society


Inorganic chemistry
Journal: Inorganic chemistry


Acs nano
Journal: Acs nano


Nano letters
Journal: Nano letters


Acs energy letters
Journal: Acs energy letters


Chemistry of materials
Journal: Chemistry of materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Chemical science
Journal: Chemical science


Science advances
Journal: Science advances


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs energy letters
Journal: Acs energy letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Acs nano
Journal: Acs nano


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Communications physics
Journal: Communications physics


Acs energy letters
Journal: Acs energy letters


Crystal growth &design
Journal: Crystal growth &design


Npg asia materials
Journal: Npg asia materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Chemistry of materials
Journal: Chemistry of materials


Advanced materials
Journal: Advanced materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Chemistry–a european journal
Journal: Chemistry–a european journal


Organic letters
Journal: Organic letters


Acs materials letters
Journal: Acs materials letters


Acs nano
Journal: Acs nano


Chemistry–a european journal
Journal: Chemistry–a european journal


Advanced energy materials
Journal: Advanced energy materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced functional materials
Journal: Advanced functional materials


Advanced optical materials
Journal: Advanced optical materials


Acs materials letters
Journal: Acs materials letters


Nature communications
Journal: Nature communications


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Chemistry–a european journal
Journal: Chemistry–a european journal


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Acs energy letters
Journal: Acs energy letters


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Nanoscale horizons
Journal: Nanoscale horizons


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Advanced energy materials
Journal: Advanced energy materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Joule
Journal: Joule


Acs materials letters
Journal: Acs materials letters


Acs energy letters
Journal: Acs energy letters


Chemical communications
Journal: Chemical communications


Advanced energy materials
Journal: Advanced energy materials


Acs applied energy materials
Journal: Acs applied energy materials


Acs materials letters
Journal: Acs materials letters


The journal of chemical physics
Journal: The journal of chemical physics


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs energy letters
Journal: Acs energy letters


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Chemistry of materials
Journal: Chemistry of materials


Nature communications
Journal: Nature communications


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nature communications
Journal: Nature communications


Organic electronics
Journal: Organic electronics


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Matter
Journal: Matter


Nature communications
Journal: Nature communications


Acs materials letters
Journal: Acs materials letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced energy materials
Journal: Advanced energy materials


Apl materials
Journal: Apl materials


Small
Journal: Small


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nature communications
Journal: Nature communications


Acs energy letters
Journal: Acs energy letters


Scientific reports
Journal: Scientific reports


Advanced materials
Journal: Advanced materials


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Acs nano
Journal: Acs nano


Chem
Journal: Chem


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nature energy
Journal: Nature energy


Physica status solidi (rrl)–rapid research letters
Journal: Physica status solidi (rrl)–rapid research letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs materials letters
Journal: Acs materials letters


Journal of polymer science part a: polymer chemistry
Journal: Journal of polymer science part a: polymer chemistry


Advanced materials
Journal: Advanced materials


Energy technology
Journal: Energy technology


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature communications
Journal: Nature communications


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Rsc advances
Journal: Rsc advances


Acs materials letters
Journal: Acs materials letters


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nature communications
Journal: Nature communications


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Advanced materials
Journal: Advanced materials


Journal of materials chemistry c

Acs energy letters
Journal: Acs energy letters


Sustainable energy &fuels
Journal: Sustainable energy &fuels


Nature communications
Journal: Nature communications


Advanced energy materials, https://onlinelibrary.wiley.com/doi/10.
Journal: Advanced energy materials


Thin solid films
Journal: Thin solid films


Acs energy letters
Journal: Acs energy letters


Chemistry of materials
Journal: Chemistry of materials


Advanced functional materials
Journal: Advanced functional materials


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Acs applied energy materials
Journal: Acs applied energy materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs energy letters
Journal: Acs energy letters


Journal of applied physics
Journal: Journal of applied physics


Advanced energy materials
Journal: Advanced energy materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Physical review b
Journal: Physical review b


Apl materials
Journal: Apl materials


Nanotechnology
Journal: Nanotechnology


Journal of applied physics
Journal: Journal of applied physics


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced materials
Journal: Advanced materials


Macromolecules
Journal: Macromolecules


Chemical communications
Journal: Chemical communications


Thin solid films
Journal: Thin solid films


Chemical communications
Journal: Chemical communications


Cell reports physical science
Journal: Cell reports physical science


Synthetic metals
Journal: Synthetic metals


Solar rrl
Journal: Solar rrl


Organic photovoltaics iii
Journal: Organic photovoltaics iii


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Thin solid films
Journal: Thin solid films


Synthetic metals
Journal: Synthetic metals


Applied physics letters
Journal: Applied physics letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Applied surface science
Journal: Applied surface science


Cell reports physical science
Journal: Cell reports physical science


Journal of luminescence
Journal: Journal of luminescence


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs applied energy materials
Journal: Acs applied energy materials


Journal of applied physics
Journal: Journal of applied physics


Journal of applied physics
Journal: Journal of applied physics


Conferentie hopv
Journal: Conferentie hopv


Chem. commun.,
Journal: Chem. commun.


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Chemistry of materials
Journal: Chemistry of materials


Advanced materials
Journal: Advanced materials


Chemical science
Journal: Chemical science


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs nano
Journal: Acs nano


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs nano
Journal: Acs nano


Advanced functional materials
Journal: Advanced functional materials


Advanced functional materials
Journal: Advanced functional materials


Nanotechnology
Journal: Nanotechnology


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemistry of materials
Journal: Chemistry of materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced optical materials
Journal: Advanced optical materials


Advanced functional materials
Journal: Advanced functional materials


Nanotechnology
Journal: Nanotechnology


Nanoscale
Journal: Nanoscale


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced functional materials
Journal: Advanced functional materials


Advanced functional materials
Journal: Advanced functional materials


Angewandte chemie
Journal: Angewandte chemie


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced optical materials
Journal: Advanced optical materials


Nature communications
Journal: Nature communications


Advanced science
Journal: Advanced science


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Nano research
Journal: Nano research


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Advanced optical materials
Journal: Advanced optical materials


Nanoscale
Journal: Nanoscale


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Nano energy
Journal: Nano energy


Advanced materials
Journal: Advanced materials


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Chinese chemical letters
Journal: Chinese chemical letters


Science bulletin
Journal: Science bulletin


Langmuir
Journal: Langmuir


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Crystal growth &design
Journal: Crystal growth &design


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Light: science &applications
Journal: Light: science &applications


Advanced optical materials
Journal: Advanced optical materials


Advanced optical materials
Journal: Advanced optical materials


Advanced functional materials
Journal: Advanced functional materials


Optics express
Journal: Optics express


Nature materials
Journal: Nature materials


Advanced functional materials
Journal: Advanced functional materials


Optics express
Journal: Optics express


Physical review letters
Journal: Physical review letters


Advanced functional materials
Journal: Advanced functional materials


Chemnanomat
Journal: Chemnanomat


Nanotechnology
Journal: Nanotechnology


Advanced materials
Journal: Advanced materials


Nano research
Journal: Nano research


Journal of optics
Journal: Journal of optics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Langmuir
Journal: Langmuir


Acs photonics
Journal: Acs photonics


Nanotechnology
Journal: Nanotechnology


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nanotechnology
Journal: Nanotechnology


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Particle &particle systems characterization
Journal: Particle &particle systems characterization


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Nanoscale
Journal: Nanoscale


中国光学
Journal: 中国光学


Chemphyschem
Journal: Chemphyschem


Nanophotonics
Journal: Nanophotonics


Journal of materials chemistry
Journal: Journal of materials chemistry


Nature photonics
Journal: Nature photonics


Communications physics
Journal: Communications physics


Chinese journal of catalysis
Journal: Chinese journal of catalysis


Biosensors and bioelectronics
Journal: Biosensors and bioelectronics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced optical materials
Journal: Advanced optical materials


Optics express
Journal: Optics express


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Microchimica acta
Journal: Microchimica acta


Cell reports physical science
Journal: Cell reports physical science


Chemistry of materials
Journal: Chemistry of materials


Advanced optical materials
Journal: Advanced optical materials


Advanced materials
Journal: Advanced materials


Science bulletin
Journal: Science bulletin


Rsc advances
Journal: Rsc advances


Journal of materials chemistry
Journal: Journal of materials chemistry


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Iranian biomedical journal
Journal: Iranian biomedical journal


Chinese journal of chemistry
Journal: Chinese journal of chemistry


Advanced optical materials
Journal: Advanced optical materials


Chem
Journal: Chem


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs photonics
Journal: Acs photonics


Physica status solidi (rrl)–rapid research letters
Journal: Physica status solidi (rrl)–rapid research letters


Physica status solidi (rrl)–rapid research letters
Journal: Physica status solidi (rrl)–rapid research letters


Ieee journal of selected topics in quantum electronics
Journal: Ieee journal of selected topics in quantum electronics


Chinese optics
Journal: Chinese optics


Nanoscale
Journal: Nanoscale


Frontiers in chemistry
Journal: Frontiers in chemistry


Advanced optical materials
Journal: Advanced optical materials


Langmuir
Journal: Langmuir


Progress in chemistry
Journal: Progress in chemistry


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Advanced optical materials
Journal: Advanced optical materials


Nano letters
Journal: Nano letters


中国光学
Journal: 中国光学


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nanoscale
Journal: Nanoscale


Optics letters
Journal: Optics letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acta phys. chim. sin
Journal: Acta phys. chim. sin


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced optical materials
Journal: Advanced optical materials


Small
Journal: Small


Science china materials
Journal: Science china materials


Journal of information display
Journal: Journal of information display


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nano select
Journal: Nano select


Nature photonics
Journal: Nature photonics


Journal of physics communications
Journal: Journal of physics communications


Acs photonics
Journal: Acs photonics


Science of advanced materials
Journal: Science of advanced materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Frontiers of physics
Journal: Frontiers of physics


Advanced optical materials
Journal: Advanced optical materials


Journal of nanoscience and nanotechnology
Journal: Journal of nanoscience and nanotechnology


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nanotechnology
Journal: Nanotechnology


Israel journal of chemistry
Journal: Israel journal of chemistry


Faraday discussions
Journal: Faraday discussions


光学学报
Journal: 光学学报


Optical materials express
Journal: Optical materials express


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Synthetic metals
Journal: Synthetic metals


Applied physics letters
Journal: Applied physics letters


Journal of photonics for energy
Journal: Journal of photonics for energy


Advanced optoelectronics for energy and environment, asu1b.
Journal: Advanced optoelectronics for energy and environment


Journal of nanoscience and nanotechnology
Journal: Journal of nanoscience and nanotechnology


Nature nanotechnology
Journal: Nature nanotechnology


Biomedical materials
Journal: Biomedical materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Wuli xuebao/acta physica sinica
Journal: Wuli xuebao/acta physica sinica


Nanoscale
Journal: Nanoscale


Chinese journal of chemistry
Journal: Chinese journal of chemistry


Nano research
Journal: Nano research


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Materials research bulletin
Journal: Materials research bulletin


Optics express
Journal: Optics express


Nature communications
Journal: Nature communications


Crystal growth &design
Journal: Crystal growth &design


物理化学学报
Journal: 物理化学学报


Laser &photonics reviews
Journal: Laser &photonics reviews


Physical review b
Journal: Physical review b


中国光学 (中英文)
Journal: 中国光学 (中英文)


Chinese physics b
Journal: Chinese physics b


Applied physics letters
Journal: Applied physics letters


Journal of nanoscience and nanotechnology
Journal: Journal of nanoscience and nanotechnology


Advanced science
Journal: Advanced science


The journal of physical chemistry c
Journal: The journal of physical chemistry c


中国光学
Journal: 中国光学


Nano research
Journal: Nano research


Chinese optics letters
Journal: Chinese optics letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced materials
Journal: Advanced materials


化学通报
Journal: 化学通报


Science bulletin
Journal: Science bulletin


Nature materials
Journal: Nature materials


Chinese journal of applied chemistry
Journal: Chinese journal of applied chemistry


应用化学
Journal: 应用化学


发光学报
Journal: 发光学报


Physica status solidi (rrl)–rapid research letters
Journal: Physica status solidi (rrl)–rapid research letters


Optics express
Journal: Optics express


物理学报
Journal: 物理学报


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Chinese journal of lasers
Journal: Chinese journal of lasers


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Photonics research
Journal: Photonics research


Acs photonics
Journal: Acs photonics


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of luminescence
Journal: Journal of luminescence


Crystal growth &design
Journal: Crystal growth &design


Nature materials
Journal: Nature materials


Perovskite materials and devices
Journal: Perovskite materials and devices


Crystal growth &design
Journal: Crystal growth &design


Advanced intelligent systems
Journal: Advanced intelligent systems


发光学报
Journal: 发光学报


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Nature materials
Journal: Nature materials


Chinese optics
Journal: Chinese optics


Научный редактор
Journal: Научный редактор


Acta physica sinica
Journal: Acta physica sinica


Science china materials
Journal: Science china materials


中国科学: 材料科学 (英文版)
Journal: 中国科学: 材料科学 (英文版)


Optoelectronic devices and integration viii
Journal: Optoelectronic devices and integration viii


应用化学
Journal: 应用化学


Chinese journal of applied chemistry
Journal: Chinese journal of applied chemistry


催化学报
Journal: 催化学报


催化学报
Journal: 催化学报


科技导报
Journal: 科技导报


Advanced science
Journal: Advanced science


Journal of nanoscience and nanotechnology
Journal: Journal of nanoscience and nanotechnology


信息技术与标准化
Journal: 信息技术与标准化


Encyclopedia of nanoscience and nanotechnology
Journal: Encyclopedia of nanoscience and nanotechnology


Chemistry-peking-
Journal: Chemistry-peking-


Physical review letters
Journal: Physical review letters


Physical review b
Journal: Physical review b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nature communications
Journal: Nature communications


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review b
Journal: Physical review b


Nano letters
Journal: Nano letters


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Acs nano
Journal: Acs nano


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review letters
Journal: Physical review letters


Applied physics letters
Journal: Applied physics letters


Applied physics reviews
Journal: Applied physics reviews


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review b
Journal: Physical review b


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Applied physics letters
Journal: Applied physics letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of applied physics
Journal: Journal of applied physics


Physical review b
Journal: Physical review b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Applied physics reviews
Journal: Applied physics reviews


Journal of applied physics
Journal: Journal of applied physics


Physical review b
Journal: Physical review b


Semiconductor science and technology
Journal: Semiconductor science and technology


Journal of applied physics
Journal: Journal of applied physics


Journal of applied physics
Journal: Journal of applied physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of applied physics
Journal: Journal of applied physics


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Nature communications
Journal: Nature communications


Physical review materials
Journal: Physical review materials


Nanoscale
Journal: Nanoscale


Wiley interdisciplinary reviews: computational molecular science
Journal: Wiley interdisciplinary reviews: computational molecular science


Nanoscale
Journal: Nanoscale


Physical review b
Journal: Physical review b


Rev.: comput. mol. sci
Journal: Rev.: comput. mol. sci


The journal of physical chemistry c
Journal: The journal of physical chemistry c



Acs nano
Journal: Acs nano


Acs nano
Journal: Acs nano


Advanced functional materials
Journal: Advanced functional materials


Small
Journal: Small


Acs omega
Journal: Acs omega


Applied physics letters
Journal: Applied physics letters


Advanced materials
Journal: Advanced materials


Optics express
Journal: Optics express


Journal of the american chemical society
Journal: Journal of the american chemical society


Small
Journal: Small


Advanced materials
Journal: Advanced materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Nano energy
Journal: Nano energy


Acs nano
Journal: Acs nano


Optics express
Journal: Optics express


Advanced functional materials
Journal: Advanced functional materials


Advanced functional materials
Journal: Advanced functional materials


Nano energy
Journal: Nano energy


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Small
Journal: Small


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Applied physics letters
Journal: Applied physics letters


Nature communications
Journal: Nature communications


Acs materials letters
Journal: Acs materials letters


Small
Journal: Small


Joule
Journal: Joule


Science china materials
Journal: Science china materials


Small
Journal: Small


Advanced optical materials
Journal: Advanced optical materials


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Communications physics
Journal: Communications physics


Applied physics letters
Journal: Applied physics letters


Acta materialia
Journal: Acta materialia


Advanced materials
Journal: Advanced materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Optics express
Journal: Optics express


Nano energy
Journal: Nano energy


Frontiers in chemistry
Journal: Frontiers in chemistry


Small methods
Journal: Small methods


Nanoscale
Journal: Nanoscale


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nano energy
Journal: Nano energy


Applied physics letters
Journal: Applied physics letters


Macromolecular rapid communications
Journal: Macromolecular rapid communications


Applied physics letters
Journal: Applied physics letters


Small
Journal: Small


Materials today physics
Journal: Materials today physics


Photonics research
Journal: Photonics research


Advanced optical materials
Journal: Advanced optical materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Materials today physics
Journal: Materials today physics


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced optical materials
Journal: Advanced optical materials


Solar rrl
Journal: Solar rrl


Advanced materials interfaces
Journal: Advanced materials interfaces


Small
Journal: Small


Nano energy
Journal: Nano energy


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Applied physics letters
Journal: Applied physics letters


Journal of optics a: pure and applied optics
Journal: Journal of optics a: pure and applied optics


Rsc advances
Journal: Rsc advances


Small
Journal: Small


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Plasmonics
Journal: Plasmonics


Solar rrl
Journal: Solar rrl


Thin solid films
Journal: Thin solid films


Applied physics letters
Journal: Applied physics letters


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Advanced functional materials
Journal: Advanced functional materials


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Small
Journal: Small


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Chemnanomat
Journal: Chemnanomat


Small
Journal: Small


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Solar rrl
Journal: Solar rrl


Polymer chemistry
Journal: Polymer chemistry


Small
Journal: Small


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Small methods
Journal: Small methods


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced science
Journal: Advanced science


Nano energy
Journal: Nano energy


Applied surface science
Journal: Applied surface science


Applied mechanics reviews
Journal: Applied mechanics reviews


Nano energy
Journal: Nano energy


Advanced optical materials
Journal: Advanced optical materials


Applied physics letters
Journal: Applied physics letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced optical materials
Journal: Advanced optical materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Light: science &applications
Journal: Light: science &applications


Advanced functional materials
Journal: Advanced functional materials


Small
Journal: Small


Acs nano
Journal: Acs nano


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Nanoscale advances
Journal: Nanoscale advances


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Nanoscale
Journal: Nanoscale


Research on chemical intermediates
Journal: Research on chemical intermediates


Journal of energy chemistry
Journal: Journal of energy chemistry


Frontiers of optoelectronics
Journal: Frontiers of optoelectronics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Npj flexible electronics
Journal: Npj flexible electronics


Chemsuschem
Journal: Chemsuschem


Small
Journal: Small


Chemical engineering journal
Journal: Chemical engineering journal


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Physical review b
Journal: Physical review b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemical engineering journal
Journal: Chemical engineering journal


Solar energy
Journal: Solar energy


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nano energy
Journal: Nano energy


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of materials chemistry c
Journal: Journal of materials chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Advanced optical materials
Journal: Advanced optical materials


Optics express
Journal: Optics express


Energy &environmental materials
Journal: Energy &environmental materials


Nanotechnology
Journal: Nanotechnology


Photonics research
Journal: Photonics research


Nanomaterials
Journal: Nanomaterials


Ccs chemistry
Journal: Ccs chemistry


Nature materials
Journal: Nature materials


Small
Journal: Small


Advanced optical materials
Journal: Advanced optical materials


Chemical communications
Journal: Chemical communications


Small
Journal: Small


Dyes and pigments
Journal: Dyes and pigments


Solar rrl
Journal: Solar rrl


Advanced functional materials
Journal: Advanced functional materials


Optics express
Journal: Optics express


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nanoscale
Journal: Nanoscale


Infomat
Journal: Infomat


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Organic electronics
Journal: Organic electronics


Australian journal of chemistry
Journal: Australian journal of chemistry


Energy &environmental materials
Journal: Energy &environmental materials


Small
Journal: Small


Applied surface science
Journal: Applied surface science


Acs applied electronic materials
Journal: Acs applied electronic materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Nano select
Journal: Nano select


Solar rrl
Journal: Solar rrl


Science china chemistry
Journal: Science china chemistry


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Rsc advances
Journal: Rsc advances


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Small
Journal: Small


Nature communications
Journal: Nature communications


Small
Journal: Small


Advanced optical materials
Journal: Advanced optical materials


Advanced functional materials
Journal: Advanced functional materials


Chinese chemical letters
Journal: Chinese chemical letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of energy chemistry
Journal: Journal of energy chemistry


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Materials today advances
Journal: Materials today advances


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied electronic materials
Journal: Acs applied electronic materials


Journal of applied physics
Journal: Journal of applied physics


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Acta physica sinica
Journal: Acta physica sinica


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced functional materials
Journal: Advanced functional materials


Nature communications
Journal: Nature communications


Advanced optical materials
Journal: Advanced optical materials


Nanomaterials
Journal: Nanomaterials


Chinese journal of chemistry
Journal: Chinese journal of chemistry


Advanced optical materials
Journal: Advanced optical materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced optical materials
Journal: Advanced optical materials


Advanced optical materials
Journal: Advanced optical materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Small
Journal: Small


Advanced energy materials
Journal: Advanced energy materials


Small
Journal: Small


Advanced materials
Journal: Advanced materials


Advanced functional materials
Journal: Advanced functional materials


Applied physics letters
Journal: Applied physics letters


Acs energy letters
Journal: Acs energy letters


Chemical engineering journal
Journal: Chemical engineering journal


Chemistry–a european journal
Journal: Chemistry–a european journal


Acs energy letters
Journal: Acs energy letters


Chemical engineering journal
Journal: Chemical engineering journal


Chemical society reviews
Journal: Chemical society reviews


Advanced science
Journal: Advanced science


Solar rrl
Journal: Solar rrl


Solar rrl
Journal: Solar rrl


Chemical engineering journal
Journal: Chemical engineering journal


Chemistry of materials
Journal: Chemistry of materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced functional materials
Journal: Advanced functional materials


Small structures
Journal: Small structures


Chemical engineering journal
Journal: Chemical engineering journal


Science china chemistry
Journal: Science china chemistry


Npj flexible electronics
Journal: Npj flexible electronics


Perovskite materials and devices
Journal: Perovskite materials and devices


Chemical reviews
Journal: Chemical reviews


Advanced engineering materials
Journal: Advanced engineering materials


Sustainable energy &fuels
Journal: Sustainable energy &fuels


Small
Journal: Small


Small
Journal: Small


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Science china materials
Journal: Science china materials


Science china materials
Journal: Science china materials


Chinese physical soc, po box 603, beijing 100080, peoples r china
Journal: Chinese physical soc


Science china materials
Journal: Science china materials


物理学报
Journal: 物理学报


Advanced materials
Journal: Advanced materials


Journal of molecular and engineering materials
Journal: Journal of molecular and engineering materials


Cleo: qels_fundamental science, qm3d.
Journal: Cleo: qels_fundamental science


Cleo: qels_fundamental science, qth4b.
Journal: Cleo: qels_fundamental science


Advanced optical materials
Journal: Advanced optical materials


Advanced materials (weinheim, germany)
Journal: Advanced materials (weinheim


Laser science, ltud
Journal: Laser science


Nature materials
Journal: Nature materials


Nature nanotechnology
Journal: Nature nanotechnology


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature materials
Journal: Nature materials


Nature materials
Journal: Nature materials


Advanced materials
Journal: Advanced materials


Nature materials
Journal: Nature materials


Nature materials
Journal: Nature materials


Energy &environmental science
Journal: Energy &environmental science


Energy &environmental science
Journal: Energy &environmental science


Advanced energy materials
Journal: Advanced energy materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature materials
Journal: Nature materials


Nature communications
Journal: Nature communications


Nature communications
Journal: Nature communications


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature nanotechnology
Journal: Nature nanotechnology


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


Nature communications
Journal: Nature communications


Advanced energy materials
Journal: Advanced energy materials


Advanced materials
Journal: Advanced materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced materials
Journal: Advanced materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of the american chemical society
Journal: Journal of the american chemical society


Energy &environmental science
Journal: Energy &environmental science


Energy &environmental science
Journal: Energy &environmental science


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Nature
Journal: Nature


Advanced materials
Journal: Advanced materials


Chemical communications
Journal: Chemical communications


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Thin solid films
Journal: Thin solid films


Acs energy letters
Journal: Acs energy letters


Advanced materials
Journal: Advanced materials


Advanced energy materials
Journal: Advanced energy materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Joule
Journal: Joule


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Chemical reviews
Journal: Chemical reviews


Advanced materials
Journal: Advanced materials


Joule
Journal: Joule


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Macromolecules
Journal: Macromolecules


Advanced science
Journal: Advanced science


Advanced functional materials
Journal: Advanced functional materials


Nature communications
Journal: Nature communications


Nano letters
Journal: Nano letters


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Acs nano
Journal: Acs nano


Science advances
Journal: Science advances


Acs energy letters
Journal: Acs energy letters


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Thin solid films
Journal: Thin solid films


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of catalysis
Journal: Journal of catalysis


Nature materials
Journal: Nature materials


Advanced materials
Journal: Advanced materials


Advanced functional materials
Journal: Advanced functional materials


Advanced energy materials
Journal: Advanced energy materials


Nature photonics
Journal: Nature photonics


Joule
Journal: Joule


Advanced materials
Journal: Advanced materials


Journal of applied physics
Journal: Journal of applied physics


Nature communications
Journal: Nature communications


Acs energy letters
Journal: Acs energy letters


Advanced materials
Journal: Advanced materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced materials
Journal: Advanced materials


Applied organometallic chemistry
Journal: Applied organometallic chemistry


Advanced energy materials
Journal: Advanced energy materials


Nanoscale
Journal: Nanoscale


Physica status solidi (rrl)–rapid research letters
Journal: Physica status solidi (rrl)–rapid research letters


Advanced energy materials
Journal: Advanced energy materials


Advanced science
Journal: Advanced science


Advanced functional materials
Journal: Advanced functional materials


Acs nano
Journal: Acs nano


Acs nano
Journal: Acs nano


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Materials horizons
Journal: Materials horizons


Advanced materials
Journal: Advanced materials


Proceedings of the national academy of sciences
Journal: Proceedings of the national academy of sciences


Journal of applied physics
Journal: Journal of applied physics


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Advanced electronic materials
Journal: Advanced electronic materials


Advanced energy materials
Journal: Advanced energy materials


Advanced functional materials
Journal: Advanced functional materials


Applied surface science
Journal: Applied surface science


Journal of materials chemistry
Journal: Journal of materials chemistry


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced energy materials
Journal: Advanced energy materials


Small
Journal: Small


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced functional materials
Journal: Advanced functional materials


Advanced materials (deerfield beach, fla.)
Journal: Advanced materials (deerfield beach


Nature communications
Journal: Nature communications


Thin solid films
Journal: Thin solid films


Applied physics letters
Journal: Applied physics letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nano energy
Journal: Nano energy


Acs applied materials &interfaces

Nature communications
Journal: Nature communications


Applied physics letters
Journal: Applied physics letters


Energy &environmental science
Journal: Energy &environmental science


Acs energy letters
Journal: Acs energy letters


Advanced functional materials
Journal: Advanced functional materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Solar rrl
Journal: Solar rrl


Advanced materials
Journal: Advanced materials


Applied physics letters
Journal: Applied physics letters


Science
Journal: Science


Science advances
Journal: Science advances


Nature communications
Journal: Nature communications


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Organic electronics
Journal: Organic electronics


Nature communications
Journal: Nature communications


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Applied physics letters
Journal: Applied physics letters


Science
Journal: Science


National science review
Journal: National science review


Physical review applied
Journal: Physical review applied


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Nature photonics
Journal: Nature photonics


Cell reports physical science
Journal: Cell reports physical science


Trends in chemistry
Journal: Trends in chemistry


Science china chemistry
Journal: Science china chemistry


Advanced materials interfaces
Journal: Advanced materials interfaces


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Organic electronics
Journal: Organic electronics


Joule
Journal: Joule


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Small structures
Journal: Small structures


Applied physics letters
Journal: Applied physics letters


Solid state communications
Journal: Solid state communications


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Israel journal of chemistry
Journal: Israel journal of chemistry


Journal of applied physics
Journal: Journal of applied physics


Materials science and engineering: b
Journal: Materials science and engineering: b


Science bulletin
Journal: Science bulletin


Acs photonics
Journal: Acs photonics


Small
Journal: Small


Advanced materials
Journal: Advanced materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of applied physics
Journal: Journal of applied physics


Nature communications
Journal: Nature communications


Advanced functional materials
Journal: Advanced functional materials


Chemical science
Journal: Chemical science


Solar rrl
Journal: Solar rrl


Applied physics letters
Journal: Applied physics letters


Advanced materials
Journal: Advanced materials


Acs photonics
Journal: Acs photonics


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Small
Journal: Small


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Solar rrl
Journal: Solar rrl


Small
Journal: Small


Journal of applied physics
Journal: Journal of applied physics


Applied physics a
Journal: Applied physics a


Matter
Journal: Matter


Advanced functional materials
Journal: Advanced functional materials


Nano energy
Journal: Nano energy


Small methods
Journal: Small methods


Chemistry of materials
Journal: Chemistry of materials


Thin solid films
Journal: Thin solid films


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced optical materials
Journal: Advanced optical materials


Chemical science
Journal: Chemical science


Materials chemistry frontiers
Journal: Materials chemistry frontiers


Journal of electroceramics
Journal: Journal of electroceramics


Joule
Journal: Joule


Adv. energy mater
Journal: Adv. energy mater


Journal of applied physics
Journal: Journal of applied physics


Nature communications
Journal: Nature communications


Acs energy letters
Journal: Acs energy letters


Science china chemistry
Journal: Science china chemistry


Aggregate
Journal: Aggregate


Solar rrl
Journal: Solar rrl


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of energy chemistry
Journal: Journal of energy chemistry


Chemical communications
Journal: Chemical communications


Rsc advances
Journal: Rsc advances


Advanced energy materials
Journal: Advanced energy materials


Macromolecular rapid communications
Journal: Macromolecular rapid communications


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Science china chemistry
Journal: Science china chemistry


Solar rrl
Journal: Solar rrl


Europhysics letters
Journal: Europhysics letters


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Optics express
Journal: Optics express


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nano energy
Journal: Nano energy


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced materials
Journal: Advanced materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Solar rrl
Journal: Solar rrl


Joule
Journal: Joule


Chem
Journal: Chem


Advanced optical materials
Journal: Advanced optical materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of applied physics
Journal: Journal of applied physics


Journal of nanoscience and nanotechnology
Journal: Journal of nanoscience and nanotechnology


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Advanced materials
Journal: Advanced materials


Advanced energy materials
Journal: Advanced energy materials


Organic electronics
Journal: Organic electronics


Advanced optical materials
Journal: Advanced optical materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Materials chemistry frontiers
Journal: Materials chemistry frontiers


Solar rrl
Journal: Solar rrl


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of applied physics
Journal: Journal of applied physics


Integrated ferroelectrics
Journal: Integrated ferroelectrics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Applied surface science
Journal: Applied surface science


Applied physics reviews
Journal: Applied physics reviews


Advanced energy materials
Journal: Advanced energy materials


Solar rrl
Journal: Solar rrl


National science review
Journal: National science review


Star protocols
Journal: Star protocols


Solar rrl
Journal: Solar rrl


Matter
Journal: Matter


Foundations of crystallography
Journal: Foundations of crystallography


Journal of photonics for energy
Journal: Journal of photonics for energy


Advanced energy materials
Journal: Advanced energy materials


Integrated ferroelectrics
Journal: Integrated ferroelectrics


Science
Journal: Science


Nature nanotechnology
Journal: Nature nanotechnology


Science
Journal: Science


Nature nanotechnology
Journal: Nature nanotechnology


Nature
Journal: Nature


Nature communications
Journal: Nature communications


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


Nature materials
Journal: Nature materials


Nature materials
Journal: Nature materials


Nature
Journal: Nature


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Nature
Journal: Nature


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nature energy
Journal: Nature energy


Nature nanotechnology
Journal: Nature nanotechnology


Nature materials
Journal: Nature materials


Nature chemistry
Journal: Nature chemistry


Nature photonics
Journal: Nature photonics


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


Nature energy
Journal: Nature energy


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced functional materials
Journal: Advanced functional materials


Joule
Journal: Joule


Nature
Journal: Nature


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Acs catalysis
Journal: Acs catalysis


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature photonics
Journal: Nature photonics


Nature communications
Journal: Nature communications


Nature nanotechnology
Journal: Nature nanotechnology


Nature photonics
Journal: Nature photonics


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature catalysis
Journal: Nature catalysis


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


Nature photonics
Journal: Nature photonics


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Nature
Journal: Nature


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs nano
Journal: Acs nano


Nature communications
Journal: Nature communications


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Physical review letters
Journal: Physical review letters


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced materials
Journal: Advanced materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


Nature communications
Journal: Nature communications


Nature photonics
Journal: Nature photonics


Advanced materials
Journal: Advanced materials


Nature reviews materials
Journal: Nature reviews materials


Nature communications
Journal: Nature communications


Joule
Journal: Joule


Nature materials
Journal: Nature materials


Physical review b
Journal: Physical review b


Acs nano
Journal: Acs nano


Nature energy
Journal: Nature energy


Acs energy letters
Journal: Acs energy letters


Advanced materials
Journal: Advanced materials


Physical review letters
Journal: Physical review letters


Science advances
Journal: Science advances


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Joule
Journal: Joule


Acs nano
Journal: Acs nano


Physical review b
Journal: Physical review b


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Physical review b
Journal: Physical review b


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


Nano energy
Journal: Nano energy


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Frontiers of physics
Journal: Frontiers of physics


Langmuir
Journal: Langmuir


Nature communications
Journal: Nature communications


Applied physics letters
Journal: Applied physics letters


Small
Journal: Small


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Nano letters
Journal: Nano letters


Nature communications
Journal: Nature communications


Applied surface science
Journal: Applied surface science


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature communications
Journal: Nature communications


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nano letters
Journal: Nano letters


Acs energy letters
Journal: Acs energy letters


Acs nano
Journal: Acs nano


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


Langmuir
Journal: Langmuir


Nature communications
Journal: Nature communications


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


Nano letters
Journal: Nano letters


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs photonics
Journal: Acs photonics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced materials
Journal: Advanced materials


Matter
Journal: Matter


Physical review b
Journal: Physical review b


Scientific reports
Journal: Scientific reports


Advanced energy materials
Journal: Advanced energy materials


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


The journal of chemical physics
Journal: The journal of chemical physics


Advanced materials
Journal: Advanced materials


Chemistry of materials
Journal: Chemistry of materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of laser micro/nanoengineering
Journal: Journal of laser micro/nanoengineering


Nature communications
Journal: Nature communications


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced optical materials
Journal: Advanced optical materials


Advanced functional materials
Journal: Advanced functional materials


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs materials letters
Journal: Acs materials letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of the american chemical society
Journal: Journal of the american chemical society


Nano energy
Journal: Nano energy


Chemistry of materials
Journal: Chemistry of materials


Chemistry of materials
Journal: Chemistry of materials


Acs nano
Journal: Acs nano


Nature materials
Journal: Nature materials


Communications materials
Journal: Communications materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs energy letters
Journal: Acs energy letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Chem
Journal: Chem


Joule
Journal: Joule


Chemistry squared
Journal: Chemistry squared


Acs materials letters
Journal: Acs materials letters


Rare metals
Journal: Rare metals


Acs materials letters
Journal: Acs materials letters


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Jlmn-journal of laser micro/nanoengineering
Journal: Jlmn-journal of laser micro/nanoengineering


Advanced materials
Journal: Advanced materials


Advanced optical materials
Journal: Advanced optical materials


Journal of electroanalytical chemistry
Journal: Journal of electroanalytical chemistry


Acs central science
Journal: Acs central science


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of power sources
Journal: Journal of power sources


Advanced materials
Journal: Advanced materials


Science advances
Journal: Science advances


Chemistry of materials
Journal: Chemistry of materials


Nano energy
Journal: Nano energy


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Materials today sustainability
Journal: Materials today sustainability


Patterns
Journal: Patterns


Chemistry–a european journal
Journal: Chemistry–a european journal


Chem
Journal: Chem


Journal of the american chemical society
Journal: Journal of the american chemical society


Results in materials
Journal: Results in materials


Nanomaterials
Journal: Nanomaterials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Nano energy
Journal: Nano energy


Nature photonics
Journal: Nature photonics


Nature materials
Journal: Nature materials


Optics for solar energy, rm4c.
Journal: Optics for solar energy


Next generation technologies for solar energy conversion vi
Journal: Next generation technologies for solar energy conversion vi


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Bulletin of the american physical society
Journal: Bulletin of the american physical society


Macromolecular rapid communications
Journal: Macromolecular rapid communications


Advanced functional materials
Journal: Advanced functional materials


Nature materials
Journal: Nature materials


Science
Journal: Science


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature
Journal: Nature


Nature energy
Journal: Nature energy


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Chemistry of materials
Journal: Chemistry of materials


Nature energy
Journal: Nature energy


Nature materials
Journal: Nature materials


Energy &environmental science
Journal: Energy &environmental science


Advanced materials
Journal: Advanced materials


Macromolecules
Journal: Macromolecules


Advanced materials
Journal: Advanced materials


Physical review b
Journal: Physical review b


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society



Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Angewandte chemie
Journal: Angewandte chemie


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Analytical chemistry
Journal: Analytical chemistry


Applied physics letters
Journal: Applied physics letters


Ieee communications letters
Journal: Ieee communications letters


Advanced materials
Journal: Advanced materials


Advanced functional materials
Journal: Advanced functional materials


Small
Journal: Small


Nano letters
Journal: Nano letters


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Synthetic metals
Journal: Synthetic metals


Nature communications
Journal: Nature communications


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Applied physics letters
Journal: Applied physics letters


Ieee communications letters
Journal: Ieee communications letters


Nano letters
Journal: Nano letters


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Advanced optical materials
Journal: Advanced optical materials


Nano letters
Journal: Nano letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Energy &environmental science
Journal: Energy &environmental science


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Joule
Journal: Joule


Nano letters
Journal: Nano letters


Journal of optics a: pure and applied optics
Journal: Journal of optics a: pure and applied optics


Nature communications
Journal: Nature communications


Nature communications
Journal: Nature communications


Nano letters
Journal: Nano letters


Applied physics letters
Journal: Applied physics letters


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Ieee transactions on communications
Journal: Ieee transactions on communications


Nature biomedical engineering
Journal: Nature biomedical engineering


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs energy letters
Journal: Acs energy letters


Nature communications
Journal: Nature communications


Physical review b
Journal: Physical review b


Journal of materials chemistry
Journal: Journal of materials chemistry


Applied energy
Journal: Applied energy


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs energy letters
Journal: Acs energy letters


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Nanoscale
Journal: Nanoscale


Langmuir
Journal: Langmuir


Macromolecular chemistry and physics
Journal: Macromolecular chemistry and physics


Nano letters
Journal: Nano letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Analytical chemistry
Journal: Analytical chemistry


Journal of applied physics
Journal: Journal of applied physics


Nature communications
Journal: Nature communications


Joule
Journal: Joule


Mrs communications
Journal: Mrs communications


Matter
Journal: Matter


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs energy letters
Journal: Acs energy letters


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Acs energy letters
Journal: Acs energy letters


Acs nano
Journal: Acs nano


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nano energy
Journal: Nano energy


Optical and quantum electronics
Journal: Optical and quantum electronics


Nature communications
Journal: Nature communications


Accounts of materials research
Journal: Accounts of materials research


Advanced materials
Journal: Advanced materials


Acs energy letters
Journal: Acs energy letters


Advanced materials
Journal: Advanced materials


Advanced functional materials
Journal: Advanced functional materials


Critical reviews in solid state and materials sciences
Journal: Critical reviews in solid state and materials sciences


Josa b
Journal: Josa b


Advanced materials
Journal: Advanced materials


Joule
Journal: Joule


Acs energy letters
Journal: Acs energy letters


Advanced materials
Journal: Advanced materials


Acs photonics
Journal: Acs photonics


Ieee transactions on communications
Journal: Ieee transactions on communications


Advanced materials
Journal: Advanced materials


Nature chemistry
Journal: Nature chemistry


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


Journal of vacuum science &technology b: microelectronics and nanometer …
Journal: Journal of vacuum science &technology b: microelectronics and nanometer …


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Nature communications
Journal: Nature communications


Nature communications
Journal: Nature communications


Nano letters
Journal: Nano letters


Advanced optical materials
Journal: Advanced optical materials


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Ieee journal on selected areas in communications
Journal: Ieee journal on selected areas in communications


Applied physics letters
Journal: Applied physics letters


Science advances
Journal: Science advances


Acs nano
Journal: Acs nano


Journal of materials science
Journal: Journal of materials science


Physical review e
Journal: Physical review e


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nature nanotechnology
Journal: Nature nanotechnology


Nature communications
Journal: Nature communications


Solar rrl
Journal: Solar rrl


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs photonics
Journal: Acs photonics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemistry of materials
Journal: Chemistry of materials


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Ieee transactions on communications
Journal: Ieee transactions on communications


Journal of applied physics
Journal: Journal of applied physics


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


Nature communications
Journal: Nature communications


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Biotechnology and bioengineering
Journal: Biotechnology and bioengineering


Applied physics letters
Journal: Applied physics letters


Scientific reports
Journal: Scientific reports


Materials today
Journal: Materials today


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Ieee journal of selected topics in quantum electronics
Journal: Ieee journal of selected topics in quantum electronics


Ieee transactions on communications
Journal: Ieee transactions on communications


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs energy letters
Journal: Acs energy letters


Nano letters
Journal: Nano letters


Small
Journal: Small


Physical review b
Journal: Physical review b


Chemistry of materials
Journal: Chemistry of materials


Ieee communications letters
Journal: Ieee communications letters


Journal of applied physics
Journal: Journal of applied physics


Nature energy
Journal: Nature energy


Acs energy letters
Journal: Acs energy letters


Matter
Journal: Matter


Optics express
Journal: Optics express


Advanced functional materials
Journal: Advanced functional materials


Journal of vacuum science &technology b: microelectronics and nanometer …
Journal: Journal of vacuum science &technology b: microelectronics and nanometer …


Nature biomedical engineering
Journal: Nature biomedical engineering


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced energy materials
Journal: Advanced energy materials


Advanced materials
Journal: Advanced materials


Applied physics letters
Journal: Applied physics letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nano letters
Journal: Nano letters


Applied physics letters
Journal: Applied physics letters


Applied optics
Journal: Applied optics


Advanced materials
Journal: Advanced materials


Scientific reports
Journal: Scientific reports


Acs energy letters
Journal: Acs energy letters


Nature materials
Journal: Nature materials


Nature nanotechnology
Journal: Nature nanotechnology


Ieee journal of selected topics in quantum electronics
Journal: Ieee journal of selected topics in quantum electronics


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


Acs applied energy materials
Journal: Acs applied energy materials


Acs nano
Journal: Acs nano


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Nature communications
Journal: Nature communications


Lab on a chip
Journal: Lab on a chip


Josa b
Journal: Josa b


Nature catalysis
Journal: Nature catalysis


Advanced materials
Journal: Advanced materials


Advanced functional materials
Journal: Advanced functional materials


Angewandte chemie
Journal: Angewandte chemie


Acs nano
Journal: Acs nano


Nanoscale
Journal: Nanoscale


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Acs energy letters
Journal: Acs energy letters


Nano energy
Journal: Nano energy


Lab on a chip
Journal: Lab on a chip


Nature communications
Journal: Nature communications


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Acs applied energy materials
Journal: Acs applied energy materials


Lab on a chip
Journal: Lab on a chip


Nature
Journal: Nature


Nature communications
Journal: Nature communications


Optics express
Journal: Optics express


Science advances
Journal: Science advances


Nature communications
Journal: Nature communications


Applied physics letters
Journal: Applied physics letters


Ieee journal of quantum electronics
Journal: Ieee journal of quantum electronics


Solid-state electronics
Journal: Solid-state electronics


Nature communications
Journal: Nature communications


Acs energy letters
Journal: Acs energy letters


Cell reports physical science
Journal: Cell reports physical science


Acs nano
Journal: Acs nano


Advanced functional materials
Journal: Advanced functional materials


Acs energy letters
Journal: Acs energy letters


Applied physics letters
Journal: Applied physics letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nature communications
Journal: Nature communications


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of applied physics
Journal: Journal of applied physics


Ieee journal of quantum electronics
Journal: Ieee journal of quantum electronics


Joule
Journal: Joule


Advanced energy materials
Journal: Advanced energy materials


Advanced science
Journal: Advanced science


Advanced optical materials
Journal: Advanced optical materials


Acs catalysis
Journal: Acs catalysis


Acs energy letters
Journal: Acs energy letters


Nano letters
Journal: Nano letters


Ieee journal of quantum electronics
Journal: Ieee journal of quantum electronics


Ieee journal of quantum electronics
Journal: Ieee journal of quantum electronics


Ieee journal of quantum electronics
Journal: Ieee journal of quantum electronics


Applied physics letters
Journal: Applied physics letters


Ieee journal of quantum electronics
Journal: Ieee journal of quantum electronics


The journal of chemical physics
Journal: The journal of chemical physics


Nature reviews materials
Journal: Nature reviews materials


Advanced science
Journal: Advanced science


Advanced materials
Journal: Advanced materials


Infrared physics &technology
Journal: Infrared physics &technology


Advanced energy materials
Journal: Advanced energy materials


Acs sensors
Journal: Acs sensors


Ieee journal of quantum electronics
Journal: Ieee journal of quantum electronics


Nanotechnology
Journal: Nanotechnology


Ieee journal of quantum electronics
Journal: Ieee journal of quantum electronics


Nano letters
Journal: Nano letters


Acs energy letters
Journal: Acs energy letters


Advanced science
Journal: Advanced science


Journal of experimental nanoscience
Journal: Journal of experimental nanoscience


Journal of dispersion science and technology
Journal: Journal of dispersion science and technology


Nature sustainability
Journal: Nature sustainability


Joule
Journal: Joule


Nature catalysis
Journal: Nature catalysis


Light: science &applications
Journal: Light: science &applications


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nanoscale
Journal: Nanoscale


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Applied physics letters
Journal: Applied physics letters


Acs energy letters
Journal: Acs energy letters


Accounts of chemical research
Journal: Accounts of chemical research


Acs materials letters
Journal: Acs materials letters


Chemistry of materials
Journal: Chemistry of materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of modern optics 51 (16-18)
Journal: Journal of modern optics 51 (16-18)


Ieee journal of quantum electronics
Journal: Ieee journal of quantum electronics


International journal of high speed electronics and systems
Journal: International journal of high speed electronics and systems


Journal of physics: energy
Journal: Journal of physics: energy


Advanced functional materials
Journal: Advanced functional materials


Nano letters
Journal: Nano letters


Acs materials letters
Journal: Acs materials letters


Acs nano
Journal: Acs nano


Nano energy
Journal: Nano energy


Thin solid films
Journal: Thin solid films


Surface science
Journal: Surface science


Handbook of organic-inorganic hibrid materials and nanocomposites
Journal: Handbook of organic-inorganic hibrid materials and nanocomposites


Solid-state electronics
Journal: Solid-state electronics


Ieee photonics technology letters
Journal: Ieee photonics technology letters


Journal of lightwave technology
Journal: Journal of lightwave technology


Applied physics letters
Journal: Applied physics letters


Acs applied energy materials
Journal: Acs applied energy materials


Advanced energy materials
Journal: Advanced energy materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs sensors
Journal: Acs sensors


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Chemistry of materials
Journal: Chemistry of materials


Ieee spectrum
Journal: Ieee spectrum


Ieee journal of quantum electronics
Journal: Ieee journal of quantum electronics


Advanced functional materials
Journal: Advanced functional materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced materials
Journal: Advanced materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced energy materials
Journal: Advanced energy materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Physical review e
Journal: Physical review e


Applied physics letters
Journal: Applied physics letters


Surface science
Journal: Surface science


Optical and quantum electronics
Journal: Optical and quantum electronics


Chemistry of materials
Journal: Chemistry of materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs nano
Journal: Acs nano


Advanced optical materials
Journal: Advanced optical materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Optics express
Journal: Optics express


Applied physics letters
Journal: Applied physics letters


Nature communications
Journal: Nature communications


Acs nano
Journal: Acs nano


Nature communications
Journal: Nature communications


Chimia
Journal: Chimia


Advanced functional materials
Journal: Advanced functional materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Lab on a chip
Journal: Lab on a chip


International journal of thermophysics
Journal: International journal of thermophysics


Acs energy letters
Journal: Acs energy letters


Adv. healthcare mater
Journal: Adv. healthcare mater


Ijcsns 6 (7b)
Journal: Ijcsns 6 (7b)


Infomat
Journal: Infomat


Advanced materials
Journal: Advanced materials


Nature biomedical engineering
Journal: Nature biomedical engineering


Journal of power sources
Journal: Journal of power sources


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied energy materials
Journal: Acs applied energy materials


Chemistry squared
Journal: Chemistry squared


Nature electronics
Journal: Nature electronics


Advanced science
Journal: Advanced science


Chem catalysis
Journal: Chem catalysis


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced materials
Journal: Advanced materials


Acs energy letters
Journal: Acs energy letters


Nature electronics
Journal: Nature electronics


Physics and simulation of optoelectronic devices xxv
Journal: Physics and simulation of optoelectronic devices xxv


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Matter
Journal: Matter


Nature chemistry
Journal: Nature chemistry


Industrial &engineering chemistry research
Journal: Industrial &engineering chemistry research


Advanced materials
Journal: Advanced materials


Journal of lightwave technology
Journal: Journal of lightwave technology


Ieee journal of quantum electronics
Journal: Ieee journal of quantum electronics


Journal of applied physics
Journal: Journal of applied physics


Nature reviews materials
Journal: Nature reviews materials


Acs applied materials &interfaces

In [57]:
df5['Source'].value_counts()

Advanced materials                                                         523
Applied physics letters                                                    462
The journal of physical chemistry c                                        444
Physical review b                                                          382
Acs energy letters                                                         375
                                                                          ...
Photonics for solar energy systems viii                                      1
Optical devices and materials for solar energy and solid-state lighting      1
Materials science and condensed matter physics                               1
Journal of magnetism and magnetic materials 272                              1
Spintronics xiii                                                             1
Name: Source, Length: 1507, dtype: int64

In [58]:
import re
pattern = r'^([^\d]+)'

vals = df5['Source'].values
index = df5['Source'].index

for idx, val in enumerate(df5['Source'].values):

    # match pattern to citation
    match = re.match(pattern, val)

    if match:
        journal = match.group(1)
        
        # print extracted values
        print(val)
        print('Journal:', journal)
        print('\n')
        
        df5.loc[index[idx], 'Source'] = journal
        
    else:
        pass

Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Superconductor science and technology
Journal: Superconductor science and technology


Europhysics letters
Journal: Europhysics letters


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review letters
Journal: Physical review letters


Applied physics letters
Journal: Applied physics letters


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Materials
Journal: Materials


Physical review letters
Journal: Physical review letters


Physical review b
Journal: Physical review b


Measurement science and technology
Journal: Measurement science and technology


Physical review b
Journal: Physical review b


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review letters
Journal: Physical review letters


Physical review b
Journal: Physical review b


Physical review letters(usa)
Journal: Physical review letters(usa)


Measurement science and technology
Journal: Measurement science and technology


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Solid state communications
Journal: Solid state communications


Physics letters a 301 (5-6)
Journal: Physics letters a


Journal of physics f: metal physics
Journal: Journal of physics f: metal physics


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Journal of applied physics
Journal: Journal of applied physics


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The european physical journal b-condensed matter and complex systems 18 (1 …
Journal: The european physical journal b-condensed matter and complex systems


Phys. status solidi (b)
Journal: Phys. status solidi (b)


Physical review b
Journal: Physical review b


Journal of applied physics
Journal: Journal of applied physics


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Solid state communications
Journal: Solid state communications


Physical review b
Journal: Physical review b


Journal of physics and chemistry of solids
Journal: Journal of physics and chemistry of solids


International journal of modern physics b
Journal: International journal of modern physics b


Physical review b
Journal: Physical review b


Journal of applied physics
Journal: Journal of applied physics


Physical review b
Journal: Physical review b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review b
Journal: Physical review b


Journal of applied physics
Journal: Journal of applied physics


Physical review b
Journal: Physical review b


Ferroelectrics
Journal: Ferroelectrics


Physical review b
Journal: Physical review b


Solid state communications
Journal: Solid state communications


Zeitschrift für physikalische chemie
Journal: Zeitschrift für physikalische chemie


Ceramics international
Journal: Ceramics international


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Journal of physics f: metal physics
Journal: Journal of physics f: metal physics


Physical review b
Journal: Physical review b


Physical review b
Journal: Physical review b


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Le journal de physique colloques 44 (c9)
Journal: Le journal de physique colloques


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Physical review b
Journal: Physical review b


Journal of applied physics 109 (7)
Journal: Journal of applied physics


Solid state communications
Journal: Solid state communications


Phys. rev. b
Journal: Phys. rev. b


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Materials science and engineering: a
Journal: Materials science and engineering: a


Solid state communications
Journal: Solid state communications


Solid state communications
Journal: Solid state communications


Physical review b
Journal: Physical review b


Journal of alloys and compounds 231 (1-2)
Journal: Journal of alloys and compounds


Physical review b
Journal: Physical review b


Physica c: superconductivity
Journal: Physica c: superconductivity


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Challenges
Journal: Challenges


Phase transitions
Journal: Phase transitions


Journal of alloys and compounds 433 (1-2)
Journal: Journal of alloys and compounds


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Solid state communications
Journal: Solid state communications


Scripta metallurgica
Journal: Scripta metallurgica


International journal of modern physics b 14 (25n27)
Journal: International journal of modern physics b


International journal of modern physics b 13 (09n10)
Journal: International journal of modern physics b


Physica c: superconductivity
Journal: Physica c: superconductivity


Solid state phenomena
Journal: Solid state phenomena


Applied physics letters
Journal: Applied physics letters


Ferroelectrics
Journal: Ferroelectrics


Materials
Journal: Materials


Journal of applied physics
Journal: Journal of applied physics


Materials science and engineering: a
Journal: Materials science and engineering: a


Journal of magnetism and magnetic materials 272
Journal: Journal of magnetism and magnetic materials


Journal of alloys and compounds 310 (1-2)
Journal: Journal of alloys and compounds


Ceramics
Journal: Ceramics


Materials research
Journal: Materials research


Journal of applied physics
Journal: Journal of applied physics


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Ferroelectrics
Journal: Ferroelectrics


Materials science and engineering: b
Journal: Materials science and engineering: b


Journal of alloys and compounds 310 (1-2)
Journal: Journal of alloys and compounds


Nanomaterials
Journal: Nanomaterials


Journal of alloys and compounds 438 (1-2)
Journal: Journal of alloys and compounds


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


International journal of modern physics b 17 (04n06)
Journal: International journal of modern physics b


Journal of alloys and compounds
Journal: Journal of alloys and compounds


International journal of modern physics b 14 (25n27)
Journal: International journal of modern physics b


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Le journal de physique iv 6 (c8)
Journal: Le journal de physique iv


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Physica c: superconductivity
Journal: Physica c: superconductivity


Zeitschrift für physikalische chemie
Journal: Zeitschrift für physikalische chemie


Archives of metallurgy and materials
Journal: Archives of metallurgy and materials


Solid state phenomena
Journal: Solid state phenomena


Physical review b
Journal: Physical review b


Solid state phenomena
Journal: Solid state phenomena


Ferroelectrics
Journal: Ferroelectrics


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Le journal de physique iv 6 (c8)
Journal: Le journal de physique iv


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Physical review letters
Journal: Physical review letters


Le journal de physique colloques 48 (c8)
Journal: Le journal de physique colloques


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Solid state phenomena
Journal: Solid state phenomena


Physical review b
Journal: Physical review b


Journal of superconductivity
Journal: Journal of superconductivity


Measurement science and technology
Journal: Measurement science and technology


Journal of alloys and compounds 310 (1-2)
Journal: Journal of alloys and compounds


Journal of alloys and compounds 310 (1-2)
Journal: Journal of alloys and compounds


Physica status solidi (b)
Journal: Physica status solidi (b)


Physica c: superconductivity
Journal: Physica c: superconductivity


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Journal de physique(france) iv(france)
Journal: Journal de physique(france) iv(france)


Journal of advanced science 7 (3-4)
Journal: Journal of advanced science


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Solid state communications
Journal: Solid state communications


Crystals
Journal: Crystals


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Physical review research
Journal: Physical review research


Journal of alloys and compounds
Journal: Journal of alloys and compounds


International journal of materials research
Journal: International journal of materials research


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Low temperature physics
Journal: Low temperature physics


Journal of applied physics
Journal: Journal of applied physics


Journal of applied physics
Journal: Journal of applied physics


Physica. c
Journal: Physica. c


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Advances in science and technology
Journal: Advances in science and technology


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Physica. c
Journal: Physica. c


Physica c: superconductivity
Journal: Physica c: superconductivity


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


Solid state communications
Journal: Solid state communications


Physical review b
Journal: Physical review b


Journal of magnetism and magnetic materials
Journal: Journal of magnetism and magnetic materials


International journal of modern physics b 17 (04n06)
Journal: International journal of modern physics b


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Stripes and related phenomena
Journal: Stripes and related phenomena


International journal of modern physics b 14 (29n31)
Journal: International journal of modern physics b


Solid state communications
Journal: Solid state communications


Physica c: superconductivity
Journal: Physica c: superconductivity


Physica c: superconductivity
Journal: Physica c: superconductivity


International journal of modern physics b 14 (25n27)
Journal: International journal of modern physics b


International journal of modern physics b 14 (25n27)
Journal: International journal of modern physics b


Gravitational wave detection ii
Journal: Gravitational wave detection ii


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Journal of alloys and compounds
Journal: Journal of alloys and compounds


International journal of modern physics b 13 (conf-9810174-)
Journal: International journal of modern physics b


International journal of modern physics b
Journal: International journal of modern physics b


Journal of alloys and compounds(switzerland)
Journal: Journal of alloys and compounds(switzerland)


Il nuovo cimento d
Journal: Il nuovo cimento d


Physica c
Journal: Physica c


Physica c: superconductivity
Journal: Physica c: superconductivity


Il nuovo cimento d
Journal: Il nuovo cimento d


Physica c: superconductivity and its applications
Journal: Physica c: superconductivity and its applications


Physical review
Journal: Physical review


Le journal de physique iv 6 (c8)
Journal: Le journal de physique iv


Journal of advanced science 7 (3-4)
Journal: Journal of advanced science


Physica c: superconductivity
Journal: Physica c: superconductivity


Physica c: superconductivity
Journal: Physica c: superconductivity


Physica c: superconductivity;(netherlands)
Journal: Physica c: superconductivity;(netherlands)


Physical review
Journal: Physical review


Phys. rev. b: condens. matter;(united states)
Journal: Phys. rev. b: condens. matter;(united states)


Physical review b
Journal: Physical review b


Journal of the less common metals
Journal: Journal of the less common metals


Journal of the less common metals
Journal: Journal of the less common metals


Jpn. j. appl. phys. 1
Journal: Jpn. j. appl. phys.


Japanese journal of applied physics 26 (s3-1)
Journal: Japanese journal of applied physics


Physical review b
Journal: Physical review b


Zeitschrift für physikalische chemie 145 (1-2)
Journal: Zeitschrift für physikalische chemie


Journal of the less-common metals
Journal: Journal of the less-common metals


Energy &environmental science
Journal: Energy &environmental science


Nature photonics
Journal: Nature photonics


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


Energy &environmental science
Journal: Energy &environmental science


Acs energy letters
Journal: Acs energy letters


Organic electronics
Journal: Organic electronics


Journal of applied physics
Journal: Journal of applied physics


Matter
Journal: Matter


Http://dspace.mit.edu/handle/1721.1/
Journal: Http://dspace.mit.edu/handle/


Joule
Journal: Joule


Physical review applied
Journal: Physical review applied


Joule
Journal: Joule


Applied physics letters
Journal: Applied physics letters


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Physical review b
Journal: Physical review b


Nature energy
Journal: Nature energy


New journal of physics
Journal: New journal of physics


Advanced materials
Journal: Advanced materials


Materials today
Journal: Materials today


Journal of materials chemistry
Journal: Journal of materials chemistry


Advanced functional materials
Journal: Advanced functional materials


Advanced materials
Journal: Advanced materials


Chemistry of materials
Journal: Chemistry of materials


Inorganic chemistry
Journal: Inorganic chemistry


Acs photonics
Journal: Acs photonics


Journal of the american chemical society
Journal: Journal of the american chemical society


Nano letters
Journal: Nano letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Advanced energy materials
Journal: Advanced energy materials


Chemistry of materials
Journal: Chemistry of materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of materials chemistry
Journal: Journal of materials chemistry


Chemistry-a european journal
Journal: Chemistry-a european journal


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Dalton transactions
Journal: Dalton transactions


Advanced energy materials
Journal: Advanced energy materials


Advanced optical materials
Journal: Advanced optical materials


Reports on progress in physics
Journal: Reports on progress in physics


Nano letters
Journal: Nano letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Dalton transactions
Journal: Dalton transactions


Acs photonics
Journal: Acs photonics


Advanced materials technologies
Journal: Advanced materials technologies


Dalton transactions
Journal: Dalton transactions


Journal of materials chemistry
Journal: Journal of materials chemistry


Journal of the society for information display
Journal: Journal of the society for information display


Nano letters
Journal: Nano letters


Ieee transactions on applied superconductivity
Journal: Ieee transactions on applied superconductivity


Advanced optical materials
Journal: Advanced optical materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Crystal growth &design
Journal: Crystal growth &design


Advanced optical materials
Journal: Advanced optical materials


Advanced optical materials
Journal: Advanced optical materials


Crystal growth &design
Journal: Crystal growth &design


Advanced functional materials
Journal: Advanced functional materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Organic electronics
Journal: Organic electronics


Journal of the society for information display
Journal: Journal of the society for information display


Dalton transactions
Journal: Dalton transactions


Journal of nanoscience and nanotechnology
Journal: Journal of nanoscience and nanotechnology


Flexible and printed electronics
Journal: Flexible and printed electronics


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Beilstein journal of organic chemistry
Journal: Beilstein journal of organic chemistry


Advanced optical materials
Journal: Advanced optical materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Advanced materials
Journal: Advanced materials


Advanced optical materials
Journal: Advanced optical materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Organic light emitting materials and devices xvi
Journal: Organic light emitting materials and devices xvi


The journal of physical chemistry b
Journal: The journal of physical chemistry b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Carbon
Journal: Carbon


Applied surface science
Journal: Applied surface science


Plant cell reports
Journal: Plant cell reports


Biosensors and bioelectronics
Journal: Biosensors and bioelectronics


International journal of hydrogen energy
Journal: International journal of hydrogen energy


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Holz als roh-und werkstoff
Journal: Holz als roh-und werkstoff


Carbon
Journal: Carbon


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Physica e: low-dimensional systems and nanostructures
Journal: Physica e: low-dimensional systems and nanostructures


Journal of nanoscience and nanotechnology
Journal: Journal of nanoscience and nanotechnology


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of crystal growth
Journal: Journal of crystal growth



Advanced materials
Journal: Advanced materials


Journal of applied physics
Journal: Journal of applied physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Applied surface science
Journal: Applied surface science


The journal of physical chemistry a
Journal: The journal of physical chemistry a


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Synthetic metals
Journal: Synthetic metals


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Optical materials
Journal: Optical materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Applied physics b
Journal: Applied physics b


Journal of applied physics
Journal: Journal of applied physics


Nanomaterials
Journal: Nanomaterials


Applied physics letters
Journal: Applied physics letters


Journal of polymers
Journal: Journal of polymers


Journal of optics a: pure and applied optics
Journal: Journal of optics a: pure and applied optics


Physical review b
Journal: Physical review b


Physica status solidi (b)
Journal: Physica status solidi (b)


Molecules
Journal: Molecules


Applied sciences
Journal: Applied sciences


Applied physics letters
Journal: Applied physics letters


Molecules
Journal: Molecules


Thin solid films
Journal: Thin solid films


Physica status solidi (c)
Journal: Physica status solidi (c)


Optical materials
Journal: Optical materials


Physical review b
Journal: Physical review b


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Molecules
Journal: Molecules


Molecules
Journal: Molecules


Journal of luminescence
Journal: Journal of luminescence


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Microelectronic engineering
Journal: Microelectronic engineering


Physical review b
Journal: Physical review b


Nanoscale
Journal: Nanoscale


Applied physics letters
Journal: Applied physics letters


Journal of luminescence
Journal: Journal of luminescence


Micron
Journal: Micron


Synthetic metals
Journal: Synthetic metals


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physica status solidi (a)
Journal: Physica status solidi (a)


Optics &laser technology
Journal: Optics &laser technology


Journal of physical chemistry b
Journal: Journal of physical chemistry b


Photonic materials
Journal: Photonic materials


Brazilian journal of physics
Journal: Brazilian journal of physics


Synthetic metals
Journal: Synthetic metals


Nanomaterials
Journal: Nanomaterials


Optical materials: x
Journal: Optical materials: x


Education sciences
Journal: Education sciences


Journal of polymer science part b: polymer physics
Journal: Journal of polymer science part b: polymer physics


International scholarly research notices
Journal: International scholarly research notices


Rsc advances
Journal: Rsc advances


Applied physics letters
Journal: Applied physics letters


Physica status solidi (a)
Journal: Physica status solidi (a)


Advanced optical materials
Journal: Advanced optical materials


Nanomaterials
Journal: Nanomaterials


Biosensors
Journal: Biosensors


Nanomaterials
Journal: Nanomaterials


Current physical chemistry
Journal: Current physical chemistry


Applied physics letters
Journal: Applied physics letters


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Bioconjugate chem
Journal: Bioconjugate chem


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Physical review letters
Journal: Physical review letters


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Physica status solidi-a-applied research
Journal: Physica status solidi-a-applied research


Physica status solidi-a-applied research
Journal: Physica status solidi-a-applied research


Physica status solidi-b-basic research
Journal: Physica status solidi-b-basic research


Nano letters
Journal: Nano letters


Nature photonics
Journal: Nature photonics


Chemistry of materials
Journal: Chemistry of materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Nature materials
Journal: Nature materials


Acs nano
Journal: Acs nano


Acs applied nano materials
Journal: Acs applied nano materials


Acs nano
Journal: Acs nano


Energy &environmental science
Journal: Energy &environmental science


Journal of the american chemical society
Journal: Journal of the american chemical society


Mendeleev communications
Journal: Mendeleev communications


Nature materials
Journal: Nature materials


Nature communications
Journal: Nature communications


Nano letters
Journal: Nano letters


Science advances
Journal: Science advances


Acs nano
Journal: Acs nano


Physical review letters
Journal: Physical review letters


Acs applied nano materials
Journal: Acs applied nano materials


Acs nano
Journal: Acs nano


Advanced optical materials
Journal: Advanced optical materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs central science
Journal: Acs central science


Russian chemical reviews
Journal: Russian chemical reviews


Acs nano
Journal: Acs nano


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


Applied physics letters
Journal: Applied physics letters


Chemistry of materials
Journal: Chemistry of materials


Acs nano
Journal: Acs nano


Physics letters a
Journal: Physics letters a


Science
Journal: Science


Nano letters
Journal: Nano letters


Laser physics letters
Journal: Laser physics letters


Advanced materials interfaces
Journal: Advanced materials interfaces


Mendeleev communications
Journal: Mendeleev communications


Advanced materials
Journal: Advanced materials


Frontiers in chemistry
Journal: Frontiers in chemistry


Nano letters
Journal: Nano letters


Energy technology
Journal: Energy technology


Nature communications
Journal: Nature communications


Chemistry of materials
Journal: Chemistry of materials


Journal of russian laser research
Journal: Journal of russian laser research


Journal of materials research
Journal: Journal of materials research


Optical materials express
Journal: Optical materials express


Nano letters
Journal: Nano letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Inorganic materials
Journal: Inorganic materials


Mendeleev communications
Journal: Mendeleev communications


Advanced materials technologies
Journal: Advanced materials technologies


Semiconductors
Journal: Semiconductors


Cell reports physical science
Journal: Cell reports physical science


Acs energy letters
Journal: Acs energy letters


Optical materials express
Journal: Optical materials express


Chemistry squared
Journal: Chemistry squared


Journal of optical technology
Journal: Journal of optical technology


Nano letters
Journal: Nano letters


Superlattices and microstructures
Journal: Superlattices and microstructures


Nano letters
Journal: Nano letters


Nanoscale advances
Journal: Nanoscale advances


Jetp letters
Journal: Jetp letters


Journal of russian laser research
Journal: Journal of russian laser research


Physical review b
Journal: Physical review b


Advanced electronic materials
Journal: Advanced electronic materials


Advanced optical materials
Journal: Advanced optical materials


Journal of analytical atomic spectrometry
Journal: Journal of analytical atomic spectrometry


Advanced materials technologies
Journal: Advanced materials technologies


Advanced materials
Journal: Advanced materials


Micro and nano engineering
Journal: Micro and nano engineering


Cleo: qels_fundamental science
Journal: Cleo: qels_fundamental science


Organic photonics and photovoltaics
Journal: Organic photonics and photovoltaics


Advanced materials
Journal: Advanced materials


Nature materials
Journal: Nature materials


Acta crystallographica a-foundation and advances 71
Journal: Acta crystallographica a-foundation and advances


Semiconductors
Journal: Semiconductors


Neorganicheskie materialy
Journal: Neorganicheskie materialy


Journal of catalysis
Journal: Journal of catalysis


Inorganic chemistry
Journal: Inorganic chemistry


Surface and coatings technology
Journal: Surface and coatings technology


Renewable energy
Journal: Renewable energy


Physical review b
Journal: Physical review b


Acta materialia
Journal: Acta materialia


Plasma processes and polymers
Journal: Plasma processes and polymers


Acta materialia
Journal: Acta materialia


Solid state sciences
Journal: Solid state sciences


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review b
Journal: Physical review b


Spin
Journal: Spin


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Surface and coatings technology
Journal: Surface and coatings technology


Acta materialia
Journal: Acta materialia


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Thin solid films
Journal: Thin solid films


Materials
Journal: Materials


Vacuum
Journal: Vacuum


Solid state sciences
Journal: Solid state sciences


Apl materials
Journal: Apl materials


Solid state sciences
Journal: Solid state sciences


Surface and coatings technology
Journal: Surface and coatings technology


Applied physics letters
Journal: Applied physics letters


Chemistry of materials
Journal: Chemistry of materials


Acta materialia
Journal: Acta materialia


Physical review b
Journal: Physical review b


Journal of electronic materials
Journal: Journal of electronic materials


Langmuir
Journal: Langmuir


Nano energy
Journal: Nano energy


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Thermochimica acta 457 (1-2)
Journal: Thermochimica acta


Acta materialia
Journal: Acta materialia


Solid state sciences
Journal: Solid state sciences


Apl materials
Journal: Apl materials


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Faraday discusions
Journal: Faraday discusions


Journal of electronic materials
Journal: Journal of electronic materials


Advanced functional materials
Journal: Advanced functional materials


Inorganic chemistry
Journal: Inorganic chemistry


Physical review letters
Journal: Physical review letters


Materials chemistry and physics
Journal: Materials chemistry and physics


Coatings
Journal: Coatings


Scientific reports
Journal: Scientific reports


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Aerosol science and technology
Journal: Aerosol science and technology


Applied physics letters
Journal: Applied physics letters


Solid state sciences
Journal: Solid state sciences


Cellulose
Journal: Cellulose


Solid state communications
Journal: Solid state communications


Journal of materials research
Journal: Journal of materials research


Physica status solidi (rrl)–rapid research letters
Journal: Physica status solidi (rrl)–rapid research letters


Journal of electronic materials
Journal: Journal of electronic materials


Applied physics letters
Journal: Applied physics letters


Aip advances
Journal: Aip advances


Inorganic chemistry
Journal: Inorganic chemistry


Journal of materials chemistry
Journal: Journal of materials chemistry


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Acta materialia
Journal: Acta materialia


Solid-solid phase transformations in inorganic material
Journal: Solid-solid phase transformations in inorganic material


Journal of nuclear materials
Journal: Journal of nuclear materials


Rare metals
Journal: Rare metals


Nano letters
Journal: Nano letters


Applied physics letters
Journal: Applied physics letters


Nanotechnology
Journal: Nanotechnology


Journal of applied physics
Journal: Journal of applied physics


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Physical review b
Journal: Physical review b


Semiconductor science and technology
Journal: Semiconductor science and technology


Journal of materials research
Journal: Journal of materials research


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Crystal research and technology
Journal: Crystal research and technology


Journal of the korean ceramic society
Journal: Journal of the korean ceramic society


Journal of applied physics
Journal: Journal of applied physics


Nanotechnology
Journal: Nanotechnology


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Electrochimica acta
Journal: Electrochimica acta


Journal of applied physics
Journal: Journal of applied physics


Entropy
Journal: Entropy


Chimia
Journal: Chimia


Physica status solidi (a)
Journal: Physica status solidi (a)


Coatings
Journal: Coatings


Zeitschrift für anorganische und allgemeine chemie
Journal: Zeitschrift für anorganische und allgemeine chemie


Journal of crystal growth
Journal: Journal of crystal growth


Crystal growth &design
Journal: Crystal growth &design


Polymer
Journal: Polymer


Applied physics letters
Journal: Applied physics letters


Materials
Journal: Materials


Angewandte chemie
Journal: Angewandte chemie


Science and technology of advanced materials
Journal: Science and technology of advanced materials


Rsc adv.
Journal: Rsc adv.


Nanotechnology
Journal: Nanotechnology


Journal of alloys and compounds 509 (supplement 1)
Journal: Journal of alloys and compounds


Apl materials
Journal: Apl materials


Thin solid films
Journal: Thin solid films


Phys. rev. b
Journal: Phys. rev. b


Physica status solidi@rrl doi: 10.1002/pssr.
Journal: Physica status solidi@rrl doi:


Mtz-motortechnische zeitschrift
Journal: Mtz-motortechnische zeitschrift


Book "advances in electronic ceramics"
Journal: Book "advances in electronic ceramics"


Superficies y vacío
Journal: Superficies y vacío


Advanced electronic materials
Journal: Advanced electronic materials


Applied physics letters
Journal: Applied physics letters


Int. j. of advanced applied physics research
Journal: Int. j. of advanced applied physics research


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Thin solid films
Journal: Thin solid films


Mtz worldwide
Journal: Mtz worldwide


Current applied physics
Journal: Current applied physics


Anales de la asociacion quimica argentina
Journal: Anales de la asociacion quimica argentina


Nanotechnology
Journal: Nanotechnology


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Frontiers in nanotechnology
Journal: Frontiers in nanotechnology


Matéria (rio de janeiro)
Journal: Matéria (rio de janeiro)


Matéria (rio de janeiro)
Journal: Matéria (rio de janeiro)


Applied physics letters
Journal: Applied physics letters


Research@ ua
Journal: Research@ ua


Catalysis today (print)
Journal: Catalysis today (print)


Journal of physics. d
Journal: Journal of physics. d


Thermoelektrik
Journal: Thermoelektrik


Zeitschrift für anorganische und allgemeine chemie
Journal: Zeitschrift für anorganische und allgemeine chemie


Journal of applied physics
Journal: Journal of applied physics


Journal of solid state chemistry
Journal: Journal of solid state chemistry


Inorganic chemistry
Journal: Inorganic chemistry


Solid-state chemistry of inorganic materials iv: volume 755
Journal: Solid-state chemistry of inorganic materials iv: volume


Journal of crystal growth 254 (3-4)
Journal: Journal of crystal growth


Solid state sciences
Journal: Solid state sciences


Solid state sciences
Journal: Solid state sciences


Revista mexicana de física
Journal: Revista mexicana de física


Advanced energy materials
Journal: Advanced energy materials


Nature materials
Journal: Nature materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced energy materials
Journal: Advanced energy materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Chemical society reviews
Journal: Chemical society reviews


Acs energy letters
Journal: Acs energy letters


Advanced materials interfaces
Journal: Advanced materials interfaces


Acs energy letters
Journal: Acs energy letters


Acs applied energy materials
Journal: Acs applied energy materials


The journal of organic chemistry
Journal: The journal of organic chemistry


Organic letters
Journal: Organic letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Macromolecules
Journal: Macromolecules


Advanced functional materials
Journal: Advanced functional materials


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Dalton transactions
Journal: Dalton transactions


Dalton transactions
Journal: Dalton transactions


Macromolecular symposia
Journal: Macromolecular symposia


Organic electronics
Journal: Organic electronics


Silicon
Journal: Silicon


Vacuum
Journal: Vacuum


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Sustainable energy &fuels
Journal: Sustainable energy &fuels


Canadian journal of chemistry
Journal: Canadian journal of chemistry


Science
Journal: Science


Nature communications
Journal: Nature communications


Nature communications
Journal: Nature communications


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Langmuir
Journal: Langmuir


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Acs catalysis
Journal: Acs catalysis


Advanced materials
Journal: Advanced materials


Nanoscale
Journal: Nanoscale


Acs catalysis
Journal: Acs catalysis


Catalysis communications
Journal: Catalysis communications


Scientific reports
Journal: Scientific reports


Catalysts
Journal: Catalysts


Catalysis communications
Journal: Catalysis communications


International journal of hydrogen energy
Journal: International journal of hydrogen energy


Electrochem
Journal: Electrochem


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of electroanalytical chemistry
Journal: Journal of electroanalytical chemistry


Electrochimica acta
Journal: Electrochimica acta


Crystengcomm
Journal: Crystengcomm



Applied physics reviews
Journal: Applied physics reviews


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Solar rrl
Journal: Solar rrl


International journal of hydrogen energy
Journal: International journal of hydrogen energy


Energy &fuels
Journal: Energy &fuels


International journal of energy research
Journal: International journal of energy research


Small
Journal: Small


Solar rrl
Journal: Solar rrl


Journal of materials science &technology
Journal: Journal of materials science &technology


Journal of materials science &technology
Journal: Journal of materials science &technology


Journal of power sources
Journal: Journal of power sources


International journal of hydrogen energy
Journal: International journal of hydrogen energy


Materials today energy
Journal: Materials today energy


Journal of power sources
Journal: Journal of power sources


Energy &environmental materials
Journal: Energy &environmental materials


Small
Journal: Small


Chemsuschem
Journal: Chemsuschem


Renewable and sustainable energy reviews
Journal: Renewable and sustainable energy reviews


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


International journal of energy research
Journal: International journal of energy research


Environmental science &technology
Journal: Environmental science &technology


Journal of colloid and interface science
Journal: Journal of colloid and interface science


Energy &fuels
Journal: Energy &fuels


Applied surface science
Journal: Applied surface science


Energy &fuels
Journal: Energy &fuels


Energy &fuels
Journal: Energy &fuels


Journal of power sources
Journal: Journal of power sources


Chemical engineering journal
Journal: Chemical engineering journal


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Aiche journal
Journal: Aiche journal


International journal of hydrogen energy
Journal: International journal of hydrogen energy


Journal of power sources
Journal: Journal of power sources


International journal of hydrogen energy
Journal: International journal of hydrogen energy


International journal of energy research
Journal: International journal of energy research


Journal of power sources
Journal: Journal of power sources


Industrial &engineering chemistry research
Journal: Industrial &engineering chemistry research


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Asia‐pacific journal of chemical engineering
Journal: Asia‐pacific journal of chemical engineering


International journal of hydrogen energy
Journal: International journal of hydrogen energy


Fuel cells
Journal: Fuel cells


Angewandte chemie
Journal: Angewandte chemie


Journal of materials science &technology
Journal: Journal of materials science &technology


Nanomaterials
Journal: Nanomaterials


Energy procedia
Journal: Energy procedia


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Membranes
Journal: Membranes


Advanced functional materials
Journal: Advanced functional materials


Journal of power sources
Journal: Journal of power sources


Nano-micro letters
Journal: Nano-micro letters


Current opinion in green and sustainable chemistry
Journal: Current opinion in green and sustainable chemistry


Nanomaterials
Journal: Nanomaterials


Energy &fuels
Journal: Energy &fuels


Energy technology
Journal: Energy technology


Hydrogen
Journal: Hydrogen


Chinese chemical letters
Journal: Chinese chemical letters


Advanced energy materials
Journal: Advanced energy materials


Small
Journal: Small


Batteries &supercaps
Journal: Batteries &supercaps


Chemsuschem
Journal: Chemsuschem


Science
Journal: Science


Science
Journal: Science


Energy &environmental science
Journal: Energy &environmental science


Nature materials
Journal: Nature materials


Materials horizons
Journal: Materials horizons


Accounts of chemical research
Journal: Accounts of chemical research


Nano letters
Journal: Nano letters


Nature communications
Journal: Nature communications


Acs energy letters
Journal: Acs energy letters


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Nature communications
Journal: Nature communications


Nano letters
Journal: Nano letters


Joule
Journal: Joule


Physical review letters
Journal: Physical review letters


Advanced energy materials
Journal: Advanced energy materials


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Philosophical magazine
Journal: Philosophical magazine


Applied physics letters
Journal: Applied physics letters


Phys. rev. lett.
Journal: Phys. rev. lett.


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs energy letters
Journal: Acs energy letters


Applied physics letters
Journal: Applied physics letters


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs nano
Journal: Acs nano


Cell reports physical science
Journal: Cell reports physical science


Acs photonics
Journal: Acs photonics


The journal of chemical physics
Journal: The journal of chemical physics


Advanced energy materials
Journal: Advanced energy materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Physical review b
Journal: Physical review b


Applied physics letters
Journal: Applied physics letters


Advanced electronic materials
Journal: Advanced electronic materials


Acs applied electronic materials
Journal: Acs applied electronic materials


Advanced functional materials
Journal: Advanced functional materials


Materials horizons
Journal: Materials horizons


Acs energy letters
Journal: Acs energy letters


Nanoscale
Journal: Nanoscale


Acs nano
Journal: Acs nano


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced materials
Journal: Advanced materials


Acs applied energy materials
Journal: Acs applied energy materials


Advanced energy materials
Journal: Advanced energy materials


Journal of photonics for energy
Journal: Journal of photonics for energy


Acs energy letters
Journal: Acs energy letters


Matter
Journal: Matter


Review of scientific instruments
Journal: Review of scientific instruments


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Iscience
Journal: Iscience


Acs energy letters
Journal: Acs energy letters


The journal of chemical physics
Journal: The journal of chemical physics


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of chemical physics
Journal: The journal of chemical physics


Thin solid films
Journal: Thin solid films


Acs energy letters
Journal: Acs energy letters


Small (weinheim an der bergstrasse
Journal: Small (weinheim an der bergstrasse


Advanced materials
Journal: Advanced materials


Nanoscale advances
Journal: Nanoscale advances


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs applied energy materials
Journal: Acs applied energy materials


Joule
Journal: Joule


Acs applied energy materials
Journal: Acs applied energy materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Acs photonics
Journal: Acs photonics


Matter
Journal: Matter


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nanoscale advances
Journal: Nanoscale advances


Acs energy letters
Journal: Acs energy letters


Nature communications
Journal: Nature communications


Physical review letters
Journal: Physical review letters


Nature communications
Journal: Nature communications


Nature
Journal: Nature


Physical review letters
Journal: Physical review letters


Science
Journal: Science


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review letters
Journal: Physical review letters


Physical review letters
Journal: Physical review letters


Physical review a
Journal: Physical review a


Physical review letters
Journal: Physical review letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Scientific reports
Journal: Scientific reports


Accounts of chemical research
Journal: Accounts of chemical research


Adv. mater
Journal: Adv. mater


Science
Journal: Science


Physical review a
Journal: Physical review a


Physical review letters
Journal: Physical review letters


Physical review letters
Journal: Physical review letters


Advanced materials
Journal: Advanced materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Advanced optical materials
Journal: Advanced optical materials


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Physical review letters
Journal: Physical review letters


Advanced functional materials
Journal: Advanced functional materials


Advanced functional materials
Journal: Advanced functional materials


Chemphyschem
Journal: Chemphyschem


Physical review letters
Journal: Physical review letters


Nanotechnology
Journal: Nanotechnology


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced optical materials
Journal: Advanced optical materials


Acs nano
Journal: Acs nano


Acs nano
Journal: Acs nano


Acs energy letters
Journal: Acs energy letters


Scientific reports
Journal: Scientific reports


Advanced optical materials
Journal: Advanced optical materials


Advanced materials interfaces
Journal: Advanced materials interfaces


Physical review b
Journal: Physical review b


Acs nano
Journal: Acs nano


Advanced optical materials
Journal: Advanced optical materials


Advanced functional materials
Journal: Advanced functional materials


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Scientific reports
Journal: Scientific reports


Journal of materials chemistry c
Journal: Journal of materials chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Physical review b
Journal: Physical review b


Advanced optical materials
Journal: Advanced optical materials


Science
Journal: Science


Chemistry–a european journal
Journal: Chemistry–a european journal


Advanced materials
Journal: Advanced materials


Chemistry of materials
Journal: Chemistry of materials


Advanced materials
Journal: Advanced materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Journal of materials chemistry b
Journal: Journal of materials chemistry b


Nanoscale
Journal: Nanoscale


Chempluschem
Journal: Chempluschem


Acs applied nano materials
Journal: Acs applied nano materials


Advanced functional materials
Journal: Advanced functional materials


Scientific reports
Journal: Scientific reports


Acs energy letters
Journal: Acs energy letters


Dalton transactions
Journal: Dalton transactions


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Ecomat
Journal: Ecomat


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced optical materials
Journal: Advanced optical materials


Langmuir
Journal: Langmuir


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Physica status solidi (b)
Journal: Physica status solidi (b)


Physical review b
Journal: Physical review b


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Acs applied nano materials
Journal: Acs applied nano materials


Crystal growth &design
Journal: Crystal growth &design


Macromolecular symposia
Journal: Macromolecular symposia


Physica status solidi (a)
Journal: Physica status solidi (a)


The european physical journal b
Journal: The european physical journal b


Semiconductor science and technology
Journal: Semiconductor science and technology


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Beilstein journal of nanotechnology
Journal: Beilstein journal of nanotechnology


Physica status solidi (a)
Journal: Physica status solidi (a)


Journal of modern optics 49 (14-15)
Journal: Journal of modern optics


Physica status solidi (a)
Journal: Physica status solidi (a)


Rsc advances
Journal: Rsc advances


Energy &environmental science
Journal: Energy &environmental science


Nature
Journal: Nature


Mrs advances
Journal: Mrs advances


Chemistry–a european journal
Journal: Chemistry–a european journal


Physica status solidi (b)
Journal: Physica status solidi (b)


Comptes rendus de l'académie des sciences-series iv-physics
Journal: Comptes rendus de l'académie des sciences-series iv-physics


Advanced optical materials
Journal: Advanced optical materials


Physica status solidi (b)
Journal: Physica status solidi (b)


Nature
Journal: Nature


Acs nano
Journal: Acs nano


Cell reports physical science
Journal: Cell reports physical science


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


European journal of physics
Journal: European journal of physics


Journal of materials chemistry c
Journal: Journal of materials chemistry c


J. mater. chem
Journal: J. mater. chem


Psst
Journal: Psst


Nature
Journal: Nature


Nanofibers–production
Journal: Nanofibers–production


Physical review letters
Journal: Physical review letters


Physical review letters
Journal: Physical review letters


Physical review letters
Journal: Physical review letters


Frontiers in optics
Journal: Frontiers in optics


Physica status solidi-a-applied research
Journal: Physica status solidi-a-applied research


Comptes rendus de l'academie des sciences series iv physics
Journal: Comptes rendus de l'academie des sciences series iv physics


Physica status solidi (b)
Journal: Physica status solidi (b)


Physica status solidi (b)
Journal: Physica status solidi (b)


Physica status solidi (a)
Journal: Physica status solidi (a)


Physica status solidi-b-basic research
Journal: Physica status solidi-b-basic research


Physica status solidi-a-applied research
Journal: Physica status solidi-a-applied research


Physica status solidi-b-basic research
Journal: Physica status solidi-b-basic research


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Physica status solidi-a-applied research
Journal: Physica status solidi-a-applied research


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Nano letters
Journal: Nano letters


Nature communications
Journal: Nature communications


Acs nano
Journal: Acs nano


Nature
Journal: Nature


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs nano
Journal: Acs nano


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs nano
Journal: Acs nano


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Structural dynamics
Journal: Structural dynamics


Nano letters
Journal: Nano letters


Nano letters
Journal: Nano letters


Advanced optical materials
Journal: Advanced optical materials


Applied physics letters
Journal: Applied physics letters


Chemistry of materials
Journal: Chemistry of materials


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


Advanced energy materials
Journal: Advanced energy materials


Energy &environmental science
Journal: Energy &environmental science


Advanced energy materials
Journal: Advanced energy materials


Advanced materials
Journal: Advanced materials


Chemistry of materials
Journal: Chemistry of materials


Science
Journal: Science


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Advanced energy materials
Journal: Advanced energy materials


Energy &environmental science
Journal: Energy &environmental science


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Nano energy
Journal: Nano energy


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced functional materials
Journal: Advanced functional materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Ieee electron device letters
Journal: Ieee electron device letters


Materials science and engineering: r: reports
Journal: Materials science and engineering: r: reports


Energy technology
Journal: Energy technology


Advanced energy materials
Journal: Advanced energy materials


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Optics express
Journal: Optics express


Acs energy letters
Journal: Acs energy letters


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced energy materials
Journal: Advanced energy materials


Advanced functional materials
Journal: Advanced functional materials


Advances in optoelectronics
Journal: Advances in optoelectronics


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Nature
Journal: Nature


Applied physics letters
Journal: Applied physics letters


Progress in photovoltaics: research and applications
Journal: Progress in photovoltaics: research and applications


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Applied physics letters
Journal: Applied physics letters


Ieee journal of photovoltaics
Journal: Ieee journal of photovoltaics


Applied physics a
Journal: Applied physics a


Optics express
Journal: Optics express


Journal of applied physics
Journal: Journal of applied physics


Ecs transactions
Journal: Ecs transactions


Journal of telecommunications and information technology
Journal: Journal of telecommunications and information technology


Ecs transactions
Journal: Ecs transactions


Advanced materials technologies
Journal: Advanced materials technologies


Infomat
Journal: Infomat


Integrated photonics research
Journal: Integrated photonics research


Advanced science
Journal: Advanced science


Cleo: science and innovations
Journal: Cleo: science and innovations


Pamm
Journal: Pamm


Small science
Journal: Small science


Cleo: science and innovations
Journal: Cleo: science and innovations


Dissertation
Journal: Dissertation


Dissertation
Journal: Dissertation


Ecs transactions
Journal: Ecs transactions


Solid state electronics
Journal: Solid state electronics


Ieee transactions on electron devices
Journal: Ieee transactions on electron devices


Journal of nano research
Journal: Journal of nano research


Applied surface science
Journal: Applied surface science


Solid-state electronics
Journal: Solid-state electronics


Wodim
Journal: Wodim


Journal of vacuum science &technology. b
Journal: Journal of vacuum science &technology. b


Journal of vacuum science and technology-section b
Journal: Journal of vacuum science and technology-section b


Journal of vacuum science and technology-section b
Journal: Journal of vacuum science and technology-section b


Energy &environmental science
Journal: Energy &environmental science


Science
Journal: Science


Acs nano
Journal: Acs nano


Energy &environmental science
Journal: Energy &environmental science


Energy &environmental science
Journal: Energy &environmental science


Nature energy
Journal: Nature energy


Nature energy
Journal: Nature energy


Energy &environmental science
Journal: Energy &environmental science


Energy &environmental science
Journal: Energy &environmental science


Advanced materials
Journal: Advanced materials


Advanced energy materials
Journal: Advanced energy materials


Advanced materials
Journal: Advanced materials


Nature energy
Journal: Nature energy


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced energy materials
Journal: Advanced energy materials


Organic electronics
Journal: Organic electronics


Chemsuschem
Journal: Chemsuschem


Advanced energy materials
Journal: Advanced energy materials


Sci
Journal: Sci


Chemsuschem
Journal: Chemsuschem


Advanced materials
Journal: Advanced materials


Ceramics international
Journal: Ceramics international


Chimia
Journal: Chimia


Energy &environmental science
Journal: Energy &environmental science


Chemsuschem
Journal: Chemsuschem


Science
Journal: Science


Nature
Journal: Nature


Nature materials
Journal: Nature materials


Nature materials
Journal: Nature materials


Nature communications
Journal: Nature communications


Acs nano
Journal: Acs nano


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Apl materials
Journal: Apl materials


Nature communications
Journal: Nature communications


Acs nano
Journal: Acs nano


Extreme mechanics letters
Journal: Extreme mechanics letters


Scientific reports
Journal: Scientific reports


Advanced energy materials
Journal: Advanced energy materials


Electrochemistry communications
Journal: Electrochemistry communications


Electroanalysis: an international journal devoted to fundamental and …
Journal: Electroanalysis: an international journal devoted to fundamental and …


Electroanalysis: an international journal devoted to fundamental and …
Journal: Electroanalysis: an international journal devoted to fundamental and …


International journal of non-linear mechanics
Journal: International journal of non-linear mechanics


Chemistry of materials
Journal: Chemistry of materials


Scientific reports
Journal: Scientific reports


Applied materials today
Journal: Applied materials today


Electrochemistry communications
Journal: Electrochemistry communications


The internet journal of gynaecology and obstetrics
Journal: The internet journal of gynaecology and obstetrics


Advanced functional materials
Journal: Advanced functional materials


Chemical communications
Journal: Chemical communications


Acs nano
Journal: Acs nano


Biosensors and bioelectronics
Journal: Biosensors and bioelectronics


Macromolecules
Journal: Macromolecules


Electrochimica acta
Journal: Electrochimica acta


Acs nano
Journal: Acs nano


Advanced energy materials
Journal: Advanced energy materials


Acs applied nano materials
Journal: Acs applied nano materials


C
Journal: C


Materials today
Journal: Materials today


Advanced materials
Journal: Advanced materials


Powder technology
Journal: Powder technology


Acs nano
Journal: Acs nano


Science advances
Journal: Science advances


Langmuir
Journal: Langmuir


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Physical review b
Journal: Physical review b


Progress in additive manufacturing
Journal: Progress in additive manufacturing


Physical review applied
Journal: Physical review applied


International journal of hydrogen energy
Journal: International journal of hydrogen energy


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Acs nano
Journal: Acs nano


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Additive manufacturing
Journal: Additive manufacturing


Journal of applied physics
Journal: Journal of applied physics


Npj 2d materials and applications
Journal: Npj


Chemnanomat
Journal: Chemnanomat


Nanoscale
Journal: Nanoscale


Applied physics letters
Journal: Applied physics letters


Scandinavian journal of immunology
Journal: Scandinavian journal of immunology


Advanced science
Journal: Advanced science


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Surface and coatings technology
Journal: Surface and coatings technology


Journal of non-newtonian fluid mechanics
Journal: Journal of non-newtonian fluid mechanics


Particulate science and technology
Journal: Particulate science and technology


Smart materials and structures
Journal: Smart materials and structures


Advanced optical materials
Journal: Advanced optical materials


Acs nano
Journal: Acs nano


Rapid prototyping journal
Journal: Rapid prototyping journal


Acs nano
Journal: Acs nano


Physica status solidi (a)
Journal: Physica status solidi (a)


Electroanalysis
Journal: Electroanalysis


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Biointerphases
Journal: Biointerphases


Journal of surgical research
Journal: Journal of surgical research


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nanotechnology
Journal: Nanotechnology


Lupus
Journal: Lupus


Inorganic chemistry
Journal: Inorganic chemistry


Rsc advances
Journal: Rsc advances


Materials and manufacturing processes
Journal: Materials and manufacturing processes


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Haryana vet
Journal: Haryana vet


Environmental science: water research &technology
Journal: Environmental science: water research &technology


Applied materials today
Journal: Applied materials today


Int. j. health sci. res
Journal: Int. j. health sci. res


Smart materials and structures
Journal: Smart materials and structures


Ieee sensors journal
Journal: Ieee sensors journal


Smart materials and structures
Journal: Smart materials and structures


Haryana veterinarian
Journal: Haryana veterinarian


Journal of personality and clinical studies
Journal: Journal of personality and clinical studies


Rsc advances
Journal: Rsc advances


Inorganica chimica acta
Journal: Inorganica chimica acta


Buff bull
Journal: Buff bull


Micro-and nanotechnology sensors
Journal: Micro-and nanotechnology sensors


Ecs journal of solid state science and technology
Journal: Ecs journal of solid state science and technology


Haryana vet
Journal: Haryana vet


Manufacturing letters
Journal: Manufacturing letters


Applied materials today
Journal: Applied materials today


Ecs transactions
Journal: Ecs transactions


Manuscript under review
Journal: Manuscript under review


Cytokine
Journal: Cytokine


J. chem. phys
Journal: J. chem. phys


Indian journal of clinical psychology
Journal: Indian journal of clinical psychology


Biointerphases
Journal: Biointerphases


Bmj supportive &palliative care 13 (suppl 1)
Journal: Bmj supportive &palliative care


Journal of pharmaceutical sciences and research
Journal: Journal of pharmaceutical sciences and research


Rsc advances
Journal: Rsc advances


New journal of chemistry
Journal: New journal of chemistry


Rsc advances
Journal: Rsc advances


Npj 2d materials and applications
Journal: Npj


American journal of respiratory and critical care medicine
Journal: American journal of respiratory and critical care medicine


J anal pharm res
Journal: J anal pharm res


Journal of the anatomical society of india
Journal: Journal of the anatomical society of india


Structural health monitoring
Journal: Structural health monitoring


Advanced optical materials
Journal: Advanced optical materials


Advances in structural health management and composite structures
Journal: Advances in structural health management and composite structures


Manual on membrane lipids
Journal: Manual on membrane lipids


Cytokine
Journal: Cytokine


Year book of dermatology and dermatological surgery 2012
Journal: Year book of dermatology and dermatological surgery


Haryana veterinarian
Journal: Haryana veterinarian


Intensive care medicine
Journal: Intensive care medicine


Journal of immunology and immunopathology 6 (supp1)
Journal: Journal of immunology and immunopathology


Journal of immunology and immunopathology 6 (supp1)
Journal: Journal of immunology and immunopathology


Chemosphere
Journal: Chemosphere


Antec 92--shaping the future.
Journal: Antec


Journal of personality and clinical studies
Journal: Journal of personality and clinical studies


Journal of all india institute of speech and hearing
Journal: Journal of all india institute of speech and hearing


Gastroenterology
Journal: Gastroenterology


Gastroenterology
Journal: Gastroenterology


Nature
Journal: Nature


Journal of the american chemical society
Journal: Journal of the american chemical society


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Nature materials
Journal: Nature materials


Chemistry of materials
Journal: Chemistry of materials


Chemical physics letters 287 (1-2)
Journal: Chemical physics letters


Nature materials
Journal: Nature materials


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Joule
Journal: Joule


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of the american chemical society
Journal: Journal of the american chemical society


Chemical communications
Journal: Chemical communications


Advanced energy materials
Journal: Advanced energy materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature nanotechnology
Journal: Nature nanotechnology


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Thin solid films
Journal: Thin solid films


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs energy letters
Journal: Acs energy letters


Nature communications
Journal: Nature communications


Angewandte chemie
Journal: Angewandte chemie


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review b
Journal: Physical review b


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced energy materials
Journal: Advanced energy materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced functional materials
Journal: Advanced functional materials


Zeitschrift für physikalische chemie
Journal: Zeitschrift für physikalische chemie


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature communications
Journal: Nature communications


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of applied physics
Journal: Journal of applied physics


Advanced energy materials
Journal: Advanced energy materials


Acs nano
Journal: Acs nano


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Chemistry of materials
Journal: Chemistry of materials


Aip advances
Journal: Aip advances


Acs omega
Journal: Acs omega


Advanced materials
Journal: Advanced materials


The journal of physical chemistry b
Journal: The journal of physical chemistry b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry b
Journal: The journal of physical chemistry b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of materials chemistry
Journal: Journal of materials chemistry


Physical review b
Journal: Physical review b


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Advanced materials
Journal: Advanced materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs energy letters
Journal: Acs energy letters


Advanced materials
Journal: Advanced materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Chemical physics letters 461 (1-3)
Journal: Chemical physics letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of photochemistry and photobiology a: chemistry 148 (1-3)
Journal: Journal of photochemistry and photobiology a: chemistry


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nano letters
Journal: Nano letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Polymer chemistry
Journal: Polymer chemistry


Physical review b
Journal: Physical review b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Journal of applied physics
Journal: Journal of applied physics


Journal of applied physics
Journal: Journal of applied physics


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Journal of photochemistry and photobiology a: chemistry 217 (2-3)
Journal: Journal of photochemistry and photobiology a: chemistry


Physical review b
Journal: Physical review b


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Chemical physics letters 244 (5-6)
Journal: Chemical physics letters


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


The journal of chemical physics
Journal: The journal of chemical physics


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs energy letters
Journal: Acs energy letters


Sustainable energy &fuels
Journal: Sustainable energy &fuels


Nature communications
Journal: Nature communications


Advanced energy materials
Journal: Advanced energy materials


Thin solid films
Journal: Thin solid films


Acs energy letters
Journal: Acs energy letters


Chemistry of materials
Journal: Chemistry of materials


Advanced functional materials
Journal: Advanced functional materials


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Acs applied energy materials
Journal: Acs applied energy materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs energy letters
Journal: Acs energy letters


Journal of applied physics
Journal: Journal of applied physics


Advanced energy materials
Journal: Advanced energy materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Physical review b
Journal: Physical review b


Apl materials
Journal: Apl materials


Nanotechnology
Journal: Nanotechnology


Journal of applied physics
Journal: Journal of applied physics


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced materials
Journal: Advanced materials


Macromolecules
Journal: Macromolecules


Chemical communications
Journal: Chemical communications


Thin solid films
Journal: Thin solid films


Chemical communications
Journal: Chemical communications


Cell reports physical science
Journal: Cell reports physical science


Synthetic metals
Journal: Synthetic metals


Solar rrl
Journal: Solar rrl


Organic photovoltaics iii
Journal: Organic photovoltaics iii


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Thin solid films
Journal: Thin solid films


Synthetic metals
Journal: Synthetic metals


Applied physics letters
Journal: Applied physics letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Applied surface science
Journal: Applied surface science


Cell reports physical science
Journal: Cell reports physical science


Journal of luminescence
Journal: Journal of luminescence


The journal of physical chemistry letters

The journal of physical chemistry b
Journal: The journal of physical chemistry b


The journal of chemical physics
Journal: The journal of chemical physics


Chemphyschem
Journal: Chemphyschem


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced energy materials
Journal: Advanced energy materials


Physical review b
Journal: Physical review b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Organic electronics
Journal: Organic electronics


Journal of electroanalytical chemistry
Journal: Journal of electroanalytical chemistry


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of solid state electrochemistry
Journal: Journal of solid state electrochemistry


Journal of applied physics
Journal: Journal of applied physics


Journal of electroanalytical chemistry 508 (1-2)
Journal: Journal of electroanalytical chemistry


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Physical review b
Journal: Physical review b


Organic electronics
Journal: Organic electronics


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Advanced energy materials
Journal: Advanced energy materials


Advanced energy materials
Journal: Advanced energy materials


Journal of electroanalytical chemistry 614 (1-2)
Journal: Journal of electroanalytical chemistry


Electrochemistry communications
Journal: Electrochemistry communications


Chemical reviews
Journal: Chemical reviews


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of power sources
Journal: Journal of power sources


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Russian journal of electrochemistry
Journal: Russian journal of electrochemistry


Applied physics letters
Journal: Applied physics letters


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of applied physics
Journal: Journal of applied physics


Advanced functional materials
Journal: Advanced functional materials


Solid-state electronics
Journal: Solid-state electronics


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Nanoscale
Journal: Nanoscale


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Advanced energy materials
Journal: Advanced energy materials


Physica status solidi (a)
Journal: Physica status solidi (a)


Advanced functional materials
Journal: Advanced functional materials


Chemsuschem: chemistry &sustainability energy &materials
Journal: Chemsuschem: chemistry &sustainability energy &materials


Chemical communications
Journal: Chemical communications


Organic electronics
Journal: Organic electronics


Applied physics letters
Journal: Applied physics letters


Solid-state electronics
Journal: Solid-state electronics


Revista cubana de fisica
Journal: Revista cubana de fisica


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Electrochimica acta
Journal: Electrochimica acta


Journal of applied physics
Journal: Journal of applied physics


Electrochimica acta
Journal: Electrochimica acta


Thin solid films
Journal: Thin solid films


Electrochimica acta
Journal: Electrochimica acta


Unconventional thin film photovoltaics: rsc energy and environment series
Journal: Unconventional thin film photovoltaics: rsc energy and environment series


Journal of electroanalytical chemistry
Journal: Journal of electroanalytical chemistry


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Thin solid films
Journal: Thin solid films


Journal of non-crystalline solids 324 (1-2)
Journal: Journal of non-crystalline solids


Chemelectrochem
Journal: Chemelectrochem


Current applied physics
Journal: Current applied physics


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


J phys chem b
Journal: J phys chem b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physica status solidi (a)
Journal: Physica status solidi (a)


Ionics
Journal: Ionics


American journal of physics
Journal: American journal of physics


Nano energy
Journal: Nano energy


Solar energy
Journal: Solar energy


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Chemical physics letters 455 (4-6)
Journal: Chemical physics letters


Advanced electronic materials
Journal: Advanced electronic materials


Journal of molecular structure
Journal: Journal of molecular structure


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


European journal of organic chemistry
Journal: European journal of organic chemistry


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical review b
Journal: Physical review b


Materials science and engineering: b
Journal: Materials science and engineering: b


Journal of applied physics
Journal: Journal of applied physics


The journal of chemical physics
Journal: The journal of chemical physics


Applied physics letters
Journal: Applied physics letters


Electrochemical and solid-state letters
Journal: Electrochemical and solid-state letters


Electronics letters
Journal: Electronics letters


Journal of materials science
Journal: Journal of materials science


Organic optoelectronics and photonics ii
Journal: Organic optoelectronics and photonics ii


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


The journal of chemical physics
Journal: The journal of chemical physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Applied physics letters
Journal: Applied physics letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Advanced materials interfaces
Journal: Advanced materials interfaces


Organic light-emitting materials and devices viii
Journal: Organic light-emitting materials and devices viii


Journal of non-crystalline solids
Journal: Journal of non-crystalline solids


Applied physics letters
Journal: Applied physics letters


Acs energy letters
Journal: Acs energy letters


Electrochimica acta
Journal: Electrochimica acta


Journal of applied physics
Journal: Journal of applied physics


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Solid-state electronics
Journal: Solid-state electronics


Thin solid films
Journal: Thin solid films


Journal of materials science
Journal: Journal of materials science


Journal of applied physics
Journal: Journal of applied physics


Journal of non-crystalline solids
Journal: Journal of non-crystalline solids


Ieee transactions on education
Journal: Ieee transactions on education


Journal of non-crystalline solids 260 (1-2)
Journal: Journal of non-crystalline solids


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


The journal of chemical physics
Journal: The journal of chemical physics


Ieee transactions on dielectrics and electrical insulation
Journal: Ieee transactions on dielectrics and electrical insulation


Chemistry of materials
Journal: Chemistry of materials


Cultural studies of science education
Journal: Cultural studies of science education


Ieee transactions on dielectrics and electrical insulation
Journal: Ieee transactions on dielectrics and electrical insulation


International ceramics journal(testo stampato)
Journal: International ceramics journal(testo stampato)


Applied signal processing
Journal: Applied signal processing


Ionics
Journal: Ionics


Physica status solidi (rrl)–rapid research letters
Journal: Physica status solidi (rrl)–rapid research letters


Solar rrl
Journal: Solar rrl


Advanced photonics research
Journal: Advanced photonics research


Revista cubana de física
Journal: Revista cubana de física


Organic photovoltaics xvi
Journal: Organic photovoltaics xvi


Organic optoelectronics and photonics iii
Journal: Organic optoelectronics and photonics iii


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Verhandlungen der deutschen physikalischen gesellschaft
Journal: Verhandlungen der deutschen physikalischen gesellschaft


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Macromolecular symposia
Journal: Macromolecular symposia


Journal of the electrochemical society
Journal: Journal of the electrochemical society


Journal of physical chemistry b-condensed phase
Journal: Journal of physical chemistry b-condensed phase


Journal of non-crystalline solids
Journal: Journal of non-crystalline solids


Journal of electroanalytical chemistry
Journal: Journal of electroanalytical chemistry


Boletín de la sociedad española de cerámica y vidrio
Journal: Boletín de la sociedad española de cerámica y vidrio


Boletin de la sociedad espanola de ceramica y vidrio
Journal: Boletin de la sociedad espanola de ceramica y vidrio


Boletín de la sociedad española de cerámica y vidrio
Journal: Boletín de la sociedad española de cerámica y vidrio


Am. j. phys
Journal: Am. j. phys


Science
Journal: Science


Nature materials
Journal: Nature materials


Nature photonics
Journal: Nature photonics


Energy &environmental science
Journal: Energy &environmental science


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature communications
Journal: Nature communications


Optics express
Journal: Optics express


Science
Journal: Science


Advanced functional materials
Journal: Advanced functional materials


Nature photonics
Journal: Nature photonics


Nature energy
Journal: Nature energy


Nature energy
Journal: Nature energy


Advanced energy materials
Journal: Advanced energy materials


Energy &environmental science
Journal: Energy &environmental science


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Chem
Journal: Chem


Small
Journal: Small


Nano letters
Journal: Nano letters


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Nature communications
Journal: Nature communications


Accounts of chemical research
Journal: Accounts of chemical research


Nature communications
Journal: Nature communications


Advanced functional materials
Journal: Advanced functional materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs nano
Journal: Acs nano


Carbon
Journal: Carbon


Advanced energy materials
Journal: Advanced energy materials


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Nano letters
Journal: Nano letters


Science bulletin
Journal: Science bulletin


Crystal growth &design
Journal: Crystal growth &design


Macromolecules
Journal: Macromolecules


Nano materials science
Journal: Nano materials science


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Nanotechnology
Journal: Nanotechnology


Solar rrl
Journal: Solar rrl


Advanced functional materials
Journal: Advanced functional materials


Science advances
Journal: Science advances


Advanced materials
Journal: Advanced materials


Energy &environmental science
Journal: Energy &environmental science


Advanced optical materials
Journal: Advanced optical materials


Nanoscale
Journal: Nanoscale


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced materials
Journal: Advanced materials


Energy &environmental materials
Journal: Energy &environmental materials


Physical review b
Journal: Physical review b


Polymer chemistry
Journal: Polymer chemistry


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Advanced energy materials
Journal: Advanced energy materials


Acs nano
Journal: Acs nano


Acs nano
Journal: Acs nano


Advanced functional materials
Journal: Advanced functional materials


Small
Journal: Small


Acs omega
Journal: Acs omega


Applied physics letters
Journal: Applied physics letters


Advanced materials
Journal: Advanced materials


Optics express
Journal: Optics express


Journal of the american chemical society
Journal: Journal of the american chemical society


Small
Journal: Small


Advanced materials
Journal: Advanced materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Nano energy
Journal: Nano energy


Acs nano
Journal: Acs nano


Optics express
Journal: Optics express


Advanced functional materials
Journal: Advanced functional materials


Advanced functional materials
Journal: Advanced functional materials


Nano energy
Journal: Nano energy


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Small
Journal: Small


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Applied physics letters
Journal: Applied physics letters


Nature communications
Journal: Nature communications


Acs materials letters
Journal: Acs materials letters


Small
Journal: Small


Joule
Journal: Joule


Science china materials
Journal: Science china materials


Small
Journal: Small


Advanced optical materials
Journal: Advanced optical materials


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Communications physics
Journal: Communications physics


Applied physics letters
Journal: Applied physics letters


Acta materialia
Journal: Acta materialia


Advanced materials
Journal: Advanced materials


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Optics express
Journal: Optics express


Nano energy
Journal: Nano energy


Frontiers in chemistry
Journal: Frontiers in chemistry


Small methods
Journal: Small methods


Nanoscale
Journal: Nanoscale


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nano energy
Journal: Nano energy


Applied physics letters
Journal: Applied physics letters


Macromolecular rapid communications
Journal: Macromolecular rapid communications


Applied physics letters
Journal: Applied physics letters


Small
Journal: Small


Materials today physics
Journal: Materials today physics


Photonics research
Journal: Photonics research


Advanced optical materials
Journal: Advanced optical materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Materials today physics
Journal: Materials today physics


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced optical materials
Journal: Advanced optical materials


Solar rrl
Journal: Solar rrl


Advanced materials interfaces
Journal: Advanced materials interfaces


Small
Journal: Small


Nano energy
Journal: Nano energy


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Applied physics letters
Journal: Applied physics letters


Journal of optics a: pure and applied optics
Journal: Journal of optics a: pure and applied optics


Rsc advances
Journal: Rsc advances


Small
Journal: Small


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Plasmonics
Journal: Plasmonics


Solar rrl
Journal: Solar rrl


Thin solid films
Journal: Thin solid films


Applied physics letters
Journal: Applied physics letters


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Advanced functional materials
Journal: Advanced functional materials


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Applied catalysis b: environmental
Journal: Applied catalysis b: environmental


Small
Journal: Small


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Chemnanomat
Journal: Chemnanomat


Small
Journal: Small


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Solar rrl
Journal: Solar rrl


Polymer chemistry
Journal: Polymer chemistry


Small
Journal: Small


Journal of alloys and compounds
Journal: Journal of alloys and compounds


Small methods
Journal: Small methods


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced science
Journal: Advanced science


Nano energy
Journal: Nano energy


Applied surface science
Journal: Applied surface science


Applied mechanics reviews
Journal: Applied mechanics reviews


Nano energy
Journal: Nano energy


Advanced optical materials
Journal: Advanced optical materials


Applied physics letters
Journal: Applied physics letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Advanced optical materials
Journal: Advanced optical materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Light: science &applications
Journal: Light: science &applications


Advanced functional materials
Journal: Advanced functional materials


Small
Journal: Small


Acs nano
Journal: Acs nano


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Nanoscale advances
Journal: Nanoscale advances


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Nanoscale
Journal: Nanoscale


Research on chemical intermediates
Journal: Research on chemical intermediates


Journal of energy chemistry
Journal: Journal of energy chemistry


Frontiers of optoelectronics
Journal: Frontiers of optoelectronics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Npj flexible electronics
Journal: Npj flexible electronics


Chemsuschem
Journal: Chemsuschem


Small
Journal: Small


Chemical engineering journal
Journal: Chemical engineering journal


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Physical review b
Journal: Physical review b


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Chemical engineering journal
Journal: Chemical engineering journal


Solar energy

Advanced energy materials
Journal: Advanced energy materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Advanced materials
Journal: Advanced materials


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nanoscale
Journal: Nanoscale


Journal of applied physics
Journal: Journal of applied physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physica status solidi (a)
Journal: Physica status solidi (a)


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Nature communications
Journal: Nature communications


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Electrochimica acta
Journal: Electrochimica acta


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Joule
Journal: Joule


Nature sustainability
Journal: Nature sustainability


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry b
Journal: The journal of physical chemistry b


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Electrochimica acta
Journal: Electrochimica acta


Small
Journal: Small


Apl materials
Journal: Apl materials


Physical review b
Journal: Physical review b


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Chemsuschem
Journal: Chemsuschem


Science advances
Journal: Science advances


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Advanced materials
Journal: Advanced materials


Materials today
Journal: Materials today


Journal of applied physics
Journal: Journal of applied physics


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Chemical communications
Journal: Chemical communications


Journal of applied physics
Journal: Journal of applied physics


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Thin solid films
Journal: Thin solid films


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Solar rrl
Journal: Solar rrl


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs energy letters
Journal: Acs energy letters


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of applied physics
Journal: Journal of applied physics


Apl materials
Journal: Apl materials


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Joule
Journal: Joule


Iscience
Journal: Iscience


The journal of physical chemistry c
Journal: The journal of physical chemistry c


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of materials chemistry
Journal: Journal of materials chemistry


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nanoscale
Journal: Nanoscale


Nanoscale
Journal: Nanoscale


Nano letters
Journal: Nano letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Electrochimica acta
Journal: Electrochimica acta


Electrochimica acta
Journal: Electrochimica acta


Journal of applied physics
Journal: Journal of applied physics


Trends in chemistry
Journal: Trends in chemistry


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Current opinion in electrochemistry
Journal: Current opinion in electrochemistry


Nanoscale
Journal: Nanoscale


Joule
Journal: Joule


Nature energy
Journal: Nature energy


Advanced functional materials
Journal: Advanced functional materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Materials chemistry and physics
Journal: Materials chemistry and physics


Advanced energy materials
Journal: Advanced energy materials


Nanoscale advances
Journal: Nanoscale advances


Sustainable energy &fuels
Journal: Sustainable energy &fuels


Journal of crystal growth
Journal: Journal of crystal growth


Nanoscale
Journal: Nanoscale


Chemical communications
Journal: Chemical communications


Electrochimica acta
Journal: Electrochimica acta


Journal of crystal growth 262 (1-4)
Journal: Journal of crystal growth


Advanced optical materials
Journal: Advanced optical materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Advanced materials interfaces
Journal: Advanced materials interfaces


Solar rrl
Journal: Solar rrl


Acs energy letters
Journal: Acs energy letters


Journal of luminescence
Journal: Journal of luminescence


Chemistry–a european journal
Journal: Chemistry–a european journal


Unconventional thin film photovoltaics: rsc energy and environment series
Journal: Unconventional thin film photovoltaics: rsc energy and environment series


Electrochimica acta
Journal: Electrochimica acta


Journal of electroanalytical chemistry
Journal: Journal of electroanalytical chemistry


Physica status solidi (b)
Journal: Physica status solidi (b)


Advanced energy and sustainability research
Journal: Advanced energy and sustainability research


Nano research
Journal: Nano research


Nano energy
Journal: Nano energy


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs applied energy materials
Journal: Acs applied energy materials


Acs energy letters
Journal: Acs energy letters


Chempluschem
Journal: Chempluschem


Journal of photochemistry and photobiology a: chemistry
Journal: Journal of photochemistry and photobiology a: chemistry


The journal of physical chemistry b
Journal: The journal of physical chemistry b


Advanced energy materials
Journal: Advanced energy materials


Acs photonics
Journal: Acs photonics


Acs applied electronic materials
Journal: Acs applied electronic materials


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Organic photovoltaics iv
Journal: Organic photovoltaics iv


Journal of crystal growth 257 (1-2)
Journal: Journal of crystal growth


Acs omega
Journal: Acs omega


Acs applied energy materials
Journal: Acs applied energy materials


Journal of luminescence
Journal: Journal of luminescence


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Applied physics letters
Journal: Applied physics letters


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Physica status solidi (b)
Journal: Physica status solidi (b)


Nanoscale
Journal: Nanoscale


Chemistry of materials
Journal: Chemistry of materials


Apl materials
Journal: Apl materials


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Advanced optical materials
Journal: Advanced optical materials


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Acta materialia
Journal: Acta materialia


Nanomaterials
Journal: Nanomaterials


Nanotechnology
Journal: Nanotechnology


Advanced optical materials
Journal: Advanced optical materials


Physical review applied
Journal: Physical review applied


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Journal of optoelectronics and advanced materials
Journal: Journal of optoelectronics and advanced materials


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Chemsuschem
Journal: Chemsuschem


Advanced optical materials
Journal: Advanced optical materials


Acs applied nano materials
Journal: Acs applied nano materials


Nanomaterials
Journal: Nanomaterials


Nano
Journal: Nano


Journal of crystal growth 240 (1-2)
Journal: Journal of crystal growth


Advanced materials technologies
Journal: Advanced materials technologies


Resources policy
Journal: Resources policy


Nature energy
Journal: Nature energy


Thin solid films
Journal: Thin solid films


Acs applied energy materials
Journal: Acs applied energy materials


Advanced optical materials
Journal: Advanced optical materials


Advanced optical materials
Journal: Advanced optical materials


Low-dimensional materials and devices 2021
Journal: Low-dimensional materials and devices


Chemistry of materials
Journal: Chemistry of materials


Nanomaterials
Journal: Nanomaterials


Frontiers in materials
Journal: Frontiers in materials


Ecs transactions
Journal: Ecs transactions


Journal of crystal growth
Journal: Journal of crystal growth


Advanced optical materials
Journal: Advanced optical materials


Chemistry of materials
Journal: Chemistry of materials


Solar rrl
Journal: Solar rrl


Applied surface science
Journal: Applied surface science


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Nanoscale
Journal: Nanoscale


Energy technology
Journal: Energy technology


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Solar rrl
Journal: Solar rrl


Advanced functional materials
Journal: Advanced functional materials


Catalysts
Journal: Catalysts


Electrochimica acta
Journal: Electrochimica acta


Nanomaterials
Journal: Nanomaterials


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Solar rrl
Journal: Solar rrl


Acs applied energy materials
Journal: Acs applied energy materials


Nano letters
Journal: Nano letters


Integrated photonics research
Journal: Integrated photonics research


Rsc advances
Journal: Rsc advances


Phys. chem. chem. phys
Journal: Phys. chem. chem. phys


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Acs energy letters
Journal: Acs energy letters


Advanced functional materials
Journal: Advanced functional materials


Verhandlungen der deutschen physikalischen gesellschaft
Journal: Verhandlungen der deutschen physikalischen gesellschaft


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Reports on progress in physics
Journal: Reports on progress in physics


Journal of applied physics
Journal: Journal of applied physics


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Applied physics letters
Journal: Applied physics letters


Journal of electroceramics
Journal: Journal of electroceramics


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Journal of applied physics
Journal: Journal of applied physics


Applied physics letters
Journal: Applied physics letters


Current opinion in solid state and materials science
Journal: Current opinion in solid state and materials science


Journal of applied physics
Journal: Journal of applied physics


Journal of applied physics
Journal: Journal of applied physics


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Advanced materials
Journal: Advanced materials


Journal of physics: condensed matter
Journal: Journal of physics: condensed matter


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Journal of physics d: applied physics
Journal: Journal of physics d: applied physics


Functional materials letters
Journal: Functional materials letters


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Nature materials
Journal: Nature materials


Physical review b
Journal: Physical review b


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Nature communications
Journal: Nature communications


Journal of applied physics
Journal: Journal of applied physics


Physical review b
Journal: Physical review b


Advanced functional materials
Journal: Advanced functional materials


Journal of applied physics
Journal: Journal of applied physics


Journal of electroceramics
Journal: Journal of electroceramics


Nature materials
Journal: Nature materials


Journal of applied physics
Journal: Journal of applied physics


Applied physics letters
Journal: Applied physics letters


Journal of the european ceramic society 27 (13-15)
Journal: Journal of the european ceramic society


Journal of applied physics
Journal: Journal of applied physics


Journal of intelligent material systems and structures
Journal: Journal of intelligent material systems and structures


Journal of applied physics
Journal: Journal of applied physics


Applied physics letters
Journal: Applied physics letters


Ieee transactions on ultrasonics
Journal: Ieee transactions on ultrasonics


Physical review b
Journal: Physical review b


Nature materials
Journal: Nature materials


Applied physics letters
Journal: Applied physics letters


Journal of applied physics
Journal: Journal of applied physics


Physical review b
Journal: Physical review b


Applied physics letters
Journal: Applied physics letters


Journal of applied physics
Journal: Journal of applied physics


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Journal of applied physics
Journal: Journal of applied physics


Journal of applied physics
Journal: Journal of applied physics


Journal of applied physics
Journal: Journal of applied physics


Applied physics letters
Journal: Applied physics letters


Advanced materials
Journal: Advanced materials


Journal of applied physics
Journal: Journal of applied physics


American ceramic society bulletin
Journal: American ceramic society bulletin


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Ieee sensors journal
Journal: Ieee sensors journal


Physical review b
Journal: Physical review b


Proceedings of the national academy of sciences
Journal: Proceedings of the national academy of sciences


Applied physics letters
Journal: Applied physics letters


Physical review letters
Journal: Physical review letters


Journal of applied physics
Journal: Journal of applied physics


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Applied physics letters
Journal: Applied physics letters


Journal of applied physics
Journal: Journal of applied physics


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Frontiers of ferroelectricity: a special issue of the journal of materials …
Journal: Frontiers of ferroelectricity: a special issue of the journal of materials …


Applied physics letters
Journal: Applied physics letters


Physical review b
Journal: Physical review b


Applied physics letters
Journal: Applied physics letters


Journal of applied physics
Journal: Journal of applied physics


Journal of applied physics
Journal: Journal of applied physics


Sensors and actuators: physical
Journal: Sensors and actuators: physical


Scientific reports
Journal: Scientific reports


Journal of applied physics
Journal: Journal of applied physics


Applied physics letters
Journal: Applied physics letters


Nature materials
Journal: Nature materials


Journal of materials science
Journal: Journal of materials science


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Advanced functional materials
Journal: Advanced functional materials


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Journal of applied physics
Journal: Journal of applied physics


Applied physics letters
Journal: Applied physics letters


Journal of the european ceramic society
Journal: Journal of the european ceramic society


Physical review b
Journal: Physical review b


Annales de chimie science des materiaux
Journal: Annales de chimie science des materiaux


Nature communications
Journal: Nature communications


Physical review-section b-condensed matter
Journal: Physical review-section b-condensed matter


Journal of applied physics
Journal: Journal of applied physics


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Science
Journal: Science


Journal of applied physics
Journal: Journal of applied physics


Applied physics letters
Journal: Applied physics letters


Ieee transactions on ultrasonics
Journal: Ieee transactions on ultrasonics


Journal of applied physics
Journal: Journal of applied physics


Physical review b
Journal: Physical review b


Applied physics letters
Journal: Applied physics letters


Journal of polymer science part b: polymer physics
Journal: Journal of polymer science part b: polymer physics


Journal of applied physics
Journal: Journal of applied physics


Journal of applied physics
Journal: Journal of applied physics


Journal of applied physics
Journal: Journal of applied physics


Journal of materials science
Journal: Journal of materials science


Physical review letters
Journal: Physical review letters


Physical review b
Journal: Physical review b


Journal of applied physics
Journal: Journal of applied physics


Journal of applied physics
Journal: Journal of applied physics


Physical review b
Journal: Physical review b


Applied physics letters
Journal: Applied physics letters


Journal of the european ceramic society 19 (6-7)
Journal: Journal of the european ceramic society


Journal of applied physics
Journal: Journal of applied physics


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Acta materialia
Journal: Acta materialia


Applied physics letters
Journal: Applied physics letters


Journal of applied physics
Journal: Journal of applied physics


Journal of applied physics
Journal: Journal of applied physics


Journal of the american ceramic society
Journal: Journal of the american ceramic society


Materials letters
Journal: Materials letters


Journal of materials research
Journal: Journal of materials research


Applied physics letters
Journal: Applied physics letters


Physical review b
Journal: Physical review b


Journal of applied physics
Journal: Journal of applied physics


Journal of applied physics
Journal: Journal of applied physics


Nature communications
Journal: Nature communications


Acta materialia
Journal: Acta materialia


Journal of applied physics
Journal: Journal of applied physics



Crystal growth &design
Journal: Crystal growth &design


Energy technology
Journal: Energy technology


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Materials advances
Journal: Materials advances


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Phys. chem. chem. phys
Journal: Phys. chem. chem. phys


Acs nano
Journal: Acs nano


Physica status solidi (rrl)–rapid research letters
Journal: Physica status solidi (rrl)–rapid research letters


Frontiers in electronics
Journal: Frontiers in electronics


Emerging photovoltaic materials
Journal: Emerging photovoltaic materials


Science
Journal: Science


Advanced energy materials
Journal: Advanced energy materials


Communications materials
Journal: Communications materials


Acs energy letters
Journal: Acs energy letters


Acs applied energy materials
Journal: Acs applied energy materials


Energy technology
Journal: Energy technology


Chemistry–a european journal
Journal: Chemistry–a european journal


Materials advances
Journal: Materials advances


Angewandte chemie
Journal: Angewandte chemie


Advanced optical materials
Journal: Advanced optical materials


Advanced optical materials
Journal: Advanced optical materials


Chemistry–a european journal
Journal: Chemistry–a european journal


Angew. chem. int. ed
Journal: Angew. chem. int. ed


Acs nano
Journal: Acs nano


J. mater. chem
Journal: J. mater. chem


Science
Journal: Science


Science
Journal: Science


Environmental science
Journal: Environmental science


Technologies
Journal: Technologies


Dalton trans
Journal: Dalton trans


Acta crystallographica
Journal: Acta crystallographica


Acta crystallographica
Journal: Acta crystallographica


Science
Journal: Science


Energy &environmental science
Journal: Energy &environmental science


Advanced materials
Journal: Advanced materials


Science
Journal: Science


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Energy &environmental science
Journal: Energy &environmental science


Advanced functional materials
Journal: Advanced functional materials


Science
Journal: Science


Nature communications
Journal: Nature communications


Nature communications
Journal: Nature communications


Journal of materials chemistry a
Journal: Journal of materials chemistry a


Advanced energy materials
Journal: Advanced energy materials


Nano letters
Journal: Nano letters


Science
Journal: Science


Advanced energy materials
Journal: Advanced energy materials


Nature communications
Journal: Nature communications


Nature communications
Journal: Nature communications


Advanced functional materials
Journal: Advanced functional materials


Nature communications
Journal: Nature communications


Nature energy
Journal: Nature energy


Energy &environmental science
Journal: Energy &environmental science


Acs nano
Journal: Acs nano


Acs nano
Journal: Acs nano


Acs nano
Journal: Acs nano


Energy &environmental science
Journal: Energy &environmental science


Nano letters
Journal: Nano letters


Chemistry of materials
Journal: Chemistry of materials


Materials horizons
Journal: Materials horizons


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced materials
Journal: Advanced materials


Nature reviews chemistry
Journal: Nature reviews chemistry


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Joule
Journal: Joule


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs energy letters
Journal: Acs energy letters


Advanced energy materials
Journal: Advanced energy materials


Applied physics letters
Journal: Applied physics letters


Physical chemistry chemical physics
Journal: Physical chemistry chemical physics


Advanced energy materials
Journal: Advanced energy materials


Nature energy
Journal: Nature energy


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Sustainable energy &fuels
Journal: Sustainable energy &fuels


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Materials horizons
Journal: Materials horizons


Energy &environmental science
Journal: Energy &environmental science


Advanced functional materials
Journal: Advanced functional materials


Energy &environmental science
Journal: Energy &environmental science


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Science
Journal: Science


Acs energy letters
Journal: Acs energy letters


Acs nano
Journal: Acs nano


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Advanced materials interfaces
Journal: Advanced materials interfaces


Applied energy
Journal: Applied energy


Applied physics letters
Journal: Applied physics letters


Acs applied energy materials
Journal: Acs applied energy materials


Acs energy letters
Journal: Acs energy letters


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Journal of the american chemical society
Journal: Journal of the american chemical society


J. mater. chem. a
Journal: J. mater. chem. a


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Applied energy
Journal: Applied energy


The embo journal
Journal: The embo journal


Chemistry of materials
Journal: Chemistry of materials


Nanoscale
Journal: Nanoscale


Chemistry of materials
Journal: Chemistry of materials


Applied physics letters
Journal: Applied physics letters


Nano energy
Journal: Nano energy


Acs energy letters
Journal: Acs energy letters


Acs applied energy materials
Journal: Acs applied energy materials


Advanced materials
Journal: Advanced materials


Nature energy
Journal: Nature energy


Chemistry of materials
Journal: Chemistry of materials


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Acs energy letters
Journal: Acs energy letters


Advanced energy materials
Journal: Advanced energy materials


Quarterly journal of the royal meteorological society
Journal: Quarterly journal of the royal meteorological society


Applied physics letters
Journal: Applied physics letters


Solar energy materials and solar cells
Journal: Solar energy materials and solar cells


Acs energy letters
Journal: Acs energy letters


Science
Journal: Science


Nature
Journal: Nature


Nature materials
Journal: Nature materials


Science
Journal: Science


Nature
Journal: Nature


Nature nanotechnology
Journal: Nature nanotechnology


Science
Journal: Science


Nature materials
Journal: Nature materials


Nature photonics
Journal: Nature photonics


Nature nanotechnology
Journal: Nature nanotechnology


Science
Journal: Science


Nature nanotechnology
Journal: Nature nanotechnology


Nature
Journal: Nature


Science
Journal: Science


Nature
Journal: Nature


Nature communications
Journal: Nature communications


Journal of the american chemical society
Journal: Journal of the american chemical society


Science
Journal: Science


Chemical reviews
Journal: Chemical reviews


Nature
Journal: Nature


Nature reviews materials
Journal: Nature reviews materials


Science
Journal: Science


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Joule
Journal: Joule


Nature energy
Journal: Nature energy


Nature photonics
Journal: Nature photonics


Nature photonics
Journal: Nature photonics


Nano letters
Journal: Nano letters


Nature communications
Journal: Nature communications


Nature communications
Journal: Nature communications


Journal of the american chemical society
Journal: Journal of the american chemical society


Chemical reviews
Journal: Chemical reviews


Science
Journal: Science


Nature catalysis
Journal: Nature catalysis


Science
Journal: Science


Nature energy
Journal: Nature energy


Nature catalysis
Journal: Nature catalysis


Nature materials
Journal: Nature materials


Nature chemistry
Journal: Nature chemistry


Nature materials
Journal: Nature materials


Nature nanotechnology
Journal: Nature nanotechnology


Nature
Journal: Nature


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Chemical reviews
Journal: Chemical reviews


Advanced materials
Journal: Advanced materials


Chemical reviews
Journal: Chemical reviews


Applied physics letters
Journal: Applied physics letters


Nature communications
Journal: Nature communications


Nature
Journal: Nature


Acs applied materials &interfaces
Journal: Acs applied materials &interfaces


Nature
Journal: Nature


Nature energy
Journal: Nature energy


Nature photonics
Journal: Nature photonics


Nature photonics
Journal: Nature photonics


Nature catalysis
Journal: Nature catalysis


Science
Journal: Science


Nature photonics
Journal: Nature photonics


Nature nanotechnology
Journal: Nature nanotechnology


Nature materials
Journal: Nature materials


Nature chemistry
Journal: Nature chemistry


Nature nanotechnology
Journal: Nature nanotechnology


Acs nano
Journal: Acs nano


Acs nano
Journal: Acs nano


Ieee communications magazine
Journal: Ieee communications magazine


Nature photonics
Journal: Nature photonics


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


Nature materials
Journal: Nature materials


Chemistry of materials
Journal: Chemistry of materials


Nature energy
Journal: Nature energy


Acs nano
Journal: Acs nano


Nature nanotechnology
Journal: Nature nanotechnology


Advanced materials
Journal: Advanced materials


Science
Journal: Science


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Nature energy
Journal: Nature energy


Journal of the american chemical society
Journal: Journal of the american chemical society


Applied physics letters
Journal: Applied physics letters


Advanced functional materials
Journal: Advanced functional materials


Chemistry of materials
Journal: Chemistry of materials


Joule
Journal: Joule


Nature materials
Journal: Nature materials


Nature materials
Journal: Nature materials


Science
Journal: Science


Nature
Journal: Nature


Advanced materials
Journal: Advanced materials


Energy &environmental science
Journal: Energy &environmental science


Advanced materials
Journal: Advanced materials


Acs photonics
Journal: Acs photonics


Nature energy
Journal: Nature energy


Advanced materials
Journal: Advanced materials


Nano letters
Journal: Nano letters


Nature materials
Journal: Nature materials


Acs nano
Journal: Acs nano


Nature reviews materials
Journal: Nature reviews materials


Nano letters
Journal: Nano letters


Nature communications
Journal: Nature communications


Nature catalysis
Journal: Nature catalysis


Reviews of modern physics
Journal: Reviews of modern physics


Acs catalysis
Journal: Acs catalysis


Nature catalysis
Journal: Nature catalysis


Journal of the american chemical society
Journal: Journal of the american chemical society


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced materials
Journal: Advanced materials


Nature photonics
Journal: Nature photonics


Nature communications
Journal: Nature communications


Acs nano
Journal: Acs nano


Applied physics letters
Journal: Applied physics letters


Nature nanotechnology
Journal: Nature nanotechnology


Nature materials
Journal: Nature materials


Ieee network
Journal: Ieee network


Nature photonics
Journal: Nature photonics


Joule
Journal: Joule


Nature energy
Journal: Nature energy


Nature nanotechnology
Journal: Nature nanotechnology


Journal of the american chemical society
Journal: Journal of the american chemical society


Science
Journal: Science


Nature catalysis
Journal: Nature catalysis


Nature catalysis
Journal: Nature catalysis


Nature chemistry
Journal: Nature chemistry


Acs nano
Journal: Acs nano


Nano letters
Journal: Nano letters


Acs nano
Journal: Acs nano


Nano letters
Journal: Nano letters


Nano letters
Journal: Nano letters


Nature
Journal: Nature


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Advanced materials
Journal: Advanced materials


Applied physics letters
Journal: Applied physics letters


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Optics express
Journal: Optics express


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature communications
Journal: Nature communications


Nature chemistry
Journal: Nature chemistry


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


Nature photonics
Journal: Nature photonics


Nature communications
Journal: Nature communications


Nature nanotechnology
Journal: Nature nanotechnology


Energy &environmental science
Journal: Energy &environmental science


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Applied physics letters
Journal: Applied physics letters


Nature chemistry
Journal: Nature chemistry


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Nature
Journal: Nature


Nano letters
Journal: Nano letters


Journal of materials chemistry c
Journal: Journal of materials chemistry c


Acs energy letters
Journal: Acs energy letters


Joule
Journal: Joule


Nature nanotechnology
Journal: Nature nanotechnology


Applied physics letters
Journal: Applied physics letters


Nano letters
Journal: Nano letters


Applied physics letters
Journal: Applied physics letters


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


Nature
Journal: Nature


Advanced materials
Journal: Advanced materials


Nature biomedical engineering
Journal: Nature biomedical engineering


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


Applied physics letters
Journal: Applied physics letters


Advanced materials
Journal: Advanced materials


Applied physics letters
Journal: Applied physics letters


Acs nano
Journal: Acs nano


Journal of the american chemical society
Journal: Journal of the american chemical society


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Advanced functional materials
Journal: Advanced functional materials


Nature communications
Journal: Nature communications


Nature
Journal: Nature


Nano letters
Journal: Nano letters


Langmuir
Journal: Langmuir


Advanced materials
Journal: Advanced materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Nano letters
Journal: Nano letters


Acs energy letters
Journal: Acs energy letters


Angewandte chemie
Journal: Angewandte chemie


Advanced materials
Journal: Advanced materials


Acs energy letters
Journal: Acs energy letters


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Journal of materials science: materials in electronics
Journal: Journal of materials science: materials in electronics


Nature catalysis
Journal: Nature catalysis


Infrared physics &technology
Journal: Infrared physics &technology


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Advanced materials
Journal: Advanced materials


Applied physics letters
Journal: Applied physics letters


Applied physics letters
Journal: Applied physics letters


Journal of the american chemical society
Journal: Journal of the american chemical society


Advanced materials
Journal: Advanced materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Acs nano
Journal: Acs nano


Analytical chemistry
Journal: Analytical chemistry


Ieee journal of quantum electronics
Journal: Ieee journal of quantum electronics


Nature catalysis
Journal: Nature catalysis


Nano letters
Journal: Nano letters


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Acs nano
Journal: Acs nano


Journal of the american chemical society
Journal: Journal of the american chemical society


Applied physics letters
Journal: Applied physics letters


Journal of lightwave technology
Journal: Journal of lightwave technology


Advanced materials
Journal: Advanced materials


Acs sustainable chemistry &engineering
Journal: Acs sustainable chemistry &engineering


Small
Journal: Small


Advanced energy materials
Journal: Advanced energy materials


Nature communications
Journal: Nature communications


Nano letters
Journal: Nano letters


Advanced materials
Journal: Advanced materials


The journal of physical chemistry letters
Journal: The journal of physical chemistry letters


Advanced functional materials
Journal: Advanced functional materials


Science
Journal: Science


Advanced materials
Journal: Advanced materials


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Applied physics letters
Journal: Applied physics letters


Nature energy
Journal: Nature energy


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Advanced materials
Journal: Advanced materials


Nature communications
Journal: Nature communications


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Journal of the american chemical society
Journal: Journal of the american chemical society


Applied physics letters
Journal: Applied physics letters


Advanced materials
Journal: Advanced materials


Nature energy
Journal: Nature energy


Accounts of chemical research
Journal: Accounts of chemical research


Angewandte chemie international edition
Journal: Angewandte chemie international edition


Acs nano
Journal: Acs nano


Nature communications
Journal: Nature communications


Journal of the american chemical society
Journal: Journal of the american chemical society


Acs energy letters
Journal: Acs energy letters


Nano letters
Journal: Nano letters


Nature energy
Journal: Nature energy


Energy &environmental science
Journal: Energy &environmental science


Nature photonics
Journal: Nature photonics


Advanced science
Journal: Advanced science


Advanced materials
Journal: Advanced materials


Nature reviews materials
Journal: Nature reviews materials


Angewandte chemie
Journal: Angewandte chemie


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature communications
Journal: Nature communications


Joule
Journal: Joule


Langmuir
Journal: Langmuir


Nature communications
Journal: Nature communications


Optics letters
Journal: Optics letters


The journal of physical chemistry c
Journal: The journal of physical chemistry c


Journal of the american chemical society
Journal: Journal of the american chemical society


Nature
Journal: Nature


Acs nano
Journal: Acs nano


Advanced materials
Journal: Advanced materials


Advanced materials
Journal: Advanced materials


Nature materials
Journal: Nature materials


Acs nano
Journal: Acs nano


Lab on a chip
Journal: Lab on a chip


Acs energy letters
Journal: Acs energy letters


Nature energy
Journal: Nature energy


Acs energy letters
Journal: Acs energy letters


Applied physics letters
Journal: Applied physics letters


Scientific reports
Journal: Scientific reports



In [59]:
df5['Source'].value_counts()

Advanced materials                                                   523
Applied physics letters                                              462
The journal of physical chemistry c                                  444
Physical review b                                                    382
Acs energy letters                                                   375
                                                                    ...
Indian journal of animal sciences (india)                              1
Nanosci. nanotechnol                                                   1
Phys. stat. sol. (a)                                                   1
Frontiers in biological detection: from nanosensors to systems iv      1
Spintronics xiii                                                       1
Name: Source, Length: 1411, dtype: int64

In [60]:
df5.to_csv(r"G:\My Drive\BrainStation\BrainStationCapstone\Scripts and Notebooks\Raw Data\2023-03-03 Export\2023-03-02 Cleaning DataSet V1 out.csv")

---