# NB4

In [1]:
import numpy as np
import pandas as pd

Previous Notebook: `\Cleaned Data\2023-03-04 Joining DFs`

Import the csv containing the citaions as `papers_df` and the data frame containing the query author information as `query_df`

In [2]:
papers_df = pd.read_pickle('2023-03-23_NB3_papers_df.pkl')
query_df = pd.read_csv(r"G:\My Drive\BrainStation\BrainStationCapstone\Scripts and Notebooks\Raw Data\2023-03-03 Export\author_PoPMetrics_V2.2.csv", low_memory = True)

Here is `papers_df`

In [3]:
papers_df.head(3)

,Cites,Authors,ManuscriptTitle,Year,GSRank,ECC,CitesPerYear,CitesPerAuthor,AuthorCount,query_id,PubTitle,PubType,SJR,H index,Country,Region
0,4186,"D Shi, V Adinolfi, R Comin, M Yuan, E Alarousu...",Low trap-state density and long carrier diffus...,2015,1,4186,523.25,523,8,0,science,journal,14.589,1229.0,United States,Northern America
1,1951,"H Tan, A Jain, O Voznyy, X Lan, FP García de A...",Efficient and stable solution-processed planar...,2017,4,1951,325.17,279,7,0,science,journal,14.589,1229.0,United States,Northern America
2,1756,"B Zhang, X Zheng, O Voznyy, R Comin, M Bajdich...",Homogeneously dispersed multimetal oxygen-evol...,2016,7,1756,250.86,251,7,0,science,journal,14.589,1229.0,United States,Northern America

Here is `query_df`

In [4]:
query_df.head(3)

,id,Query,Source,Papers,Citations,Years,Cites_Year,Cites_Paper,Cites_Author,Papers_Author,...,g_coverage,star_count,year_first,year_last,ECC,acc1,acc2,acc5,acc20,hA
0,0,Edward Sargent - University of Toronto,Google Scholar Profile,1000,119190,27,4414.44,119.19,22989.19,225.13,...,88.1,383,1996,2023,119190,751,665,517,247,69
1,1,Norbert Koch - Institut für Physik &IRIS Adler...,Google Scholar Profile,560,26197,26,1007.58,46.78,5580.69,106.68,...,83.4,76,1997,2023,26197,337,285,166,30,24
2,2,"Dieter Neher - University of Potsdam, Institut...",Google Scholar Profile,559,36923,87,424.40,66.05,7764.41,115.04,...,86.3,122,1936,2023,36923,329,274,183,65,31

## Part 1: Expanding `Authors` into columns

In [5]:
papers_df['Authors'] = papers_df['Authors'].str.strip()
papers_df['Authors'] = papers_df['Authors'].str.rsplit(',')

In [6]:
auth_df = pd.DataFrame([np.asarray(i) for i in papers_df['Authors'].values])
display(auth_df)

,0,1,2,3,4,5,6,7,8,9,10,11
0,D Shi,V Adinolfi,R Comin,M Yuan,E Alarousu,A Buin,Y Chen,...,None,None,None,None
1,H Tan,A Jain,O Voznyy,X Lan,FP García de Arquer,JZ Fan,...,None,None,None,None,None
2,B Zhang,X Zheng,O Voznyy,R Comin,M Bajdich,M García-Melchor,...,None,None,None,None,None
3,CT Dinh,T Burdyny,MG Kibria,A Seifitokaldani,CM Gabardo,...,None,None,None,None,None,None
4,P De Luna,C Hahn,D Higgins,SA Jaffer,TF Jaramillo,EH Sargent,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...
17623,SB Brichkin,MG Spirin,EG Mart’yanova,DA Kozhukhina,VV Trepalin,...,None,None,None,None,None,None
17624,S Lin,C Chen,L Zhao,M Wang,J Wang,H Zhou,C Zhao,None,None,None,None,None
17625,SP Padi,MQ Khokhar,S Chowdhury,EC Cho,J Yi,None,None,None,None,None,None,None
17626,NR Gunawan,M Tessman,AC Schreiman,R Simkovsky,AA Samoylov,...,None,None,None,None,None,None
17627,A Heiden,D Preninger,L Lehner,M Baumgartner,M Drack,E Woritzka,...,None,None,None,None,None

We're only gonna use the first three authors, so we'll drop the other columns and add column headings.

In [7]:
auth_df = auth_df.iloc[:, :3]
auth_df.columns = ['first_auth', 'second_auth', 'third_auth']

In [8]:
display(auth_df)

        first_auth   second_auth       third_auth
0            D Shi    V Adinolfi          R Comin
1            H Tan        A Jain         O Voznyy
2          B Zhang       X Zheng         O Voznyy
3          CT Dinh     T Burdyny        MG Kibria
4        P De Luna        C Hahn        D Higgins
...            ...           ...              ...
17623  SB Brichkin     MG Spirin   EG Mart’yanova
17624        S Lin        C Chen           L Zhao
17625      SP Padi    MQ Khokhar      S Chowdhury
17626   NR Gunawan     M Tessman     AC Schreiman
17627     A Heiden   D Preninger         L Lehner

[17628 rows x 3 columns]

Let's append this data frame to `papers_df` and drop the `Authors` column.

In [9]:
papers_df = pd.concat([auth_df, papers_df.drop('Authors', axis = 1)], axis = 1)

Here is the new `papers_df` let's save it as a pickle.

In [10]:
papers_df.sample(5)

,first_auth,second_auth,third_auth,Cites,ManuscriptTitle,Year,GSRank,ECC,CitesPerYear,CitesPerAuthor,AuthorCount,query_id,PubTitle,PubType,SJR,H index,Country,Region
9345,F Zu,M Roß,L Frohloff,1,Illumination‐Driven Energy Level Realignment a...,2022,397,1,1.00,0,7,1,solar rrl,journal,2.078,50.0,Germany,Western Europe
12104,M Porz,F Paulus,S Höfle,29,TIPS‐Tetracene‐and TIPS‐Pentacene‐Annulated Po...,2013,24,29,2.90,4,7,174,macromolecular rapid communications,journal,1.103,159.0,Germany,Western Europe
14157,S Dayneko,D Lypenko,P Linkov,25,Application of CdSe/ZnS/CdS/ZnS core–multishel...,2016,4,25,3.57,4,6,261,materials today proceedings,conference and proceedings,0.355,56.0,United Kingdom,Western Europe
13835,KE Aidala,MJ Panzer,PO Anikeeva,2,Morphology of contact printed colloidal quantu...,2011,65,2,0.17,0,6,108,physica status solidi c current topics in soli...,journal,0.210,49.0,Germany,Western Europe
1555,J Liu,GH Kim,Y Xue,120,Graphene oxide nanoribbon as hole extraction l...,2014,38,120,13.33,17,7,24,advanced materials,journal,8.663,563.0,United States,Northern America

In [11]:
papers_df.to_pickle('2023-03-23_NB4_papers_df_part1')

## Part 2: Apply Name Formatting

Let's first edit the names in `Query` so that they match the format given to the author names in `paper_df`. Assigning those values to the new column `query_author`.

In [12]:
import re

def edit_names(name):
    # remove any non-UTF-8 characters using encode method
    name = name.encode('ascii', 'ignore').decode('ascii')
    
    # remove any parenthess, hyphans and periodsusing regenx
    name = re.sub(r'[\(\)-\.,]', '', name).strip()
    
    # remove double spaces
    name = re.sub(r'  ', '', name).strip()
    
    # Use re to remove commas and anything after them
    name = re.sub(r'\,.*', '', name).strip()
    
    # Use re to remove title: Dr
    name = re.sub(r'^Dr\.?\s*', '', name).strip()
    
    # Use re to remove title: phd
    name = re.sub(r'^PhD\s*', '', name).strip()
    
    # Use re to remove phd
    name = re.sub(r'Ph\.?D\.?.*', '', name).strip()
    
    # Use re to remove title: Proff.
    name = re.sub(r'^PROFF\.?\s*', '', name).strip()
    
    # Remove the title: 'jr'
    name = re.sub(r'jr\.?s*', '', name).strip()
    
    # Rmove the title 'Junior'
    name = re.sub(r'junior', '', name).strip()
    
    # Remove 'equal contribution'
    name = re.sub(r'equal contribution', '', name).strip()
    
    # Remove 'ltslmw'
    name = re.sub(r'lts', '', name).strip()
    
    # Remove 'lmw'
    name = re.sub(r'lmw', '', name).strip()
    
    # Remove 'orcid'
    name = re.sub(r'ORCID:0000000160401920', '', name)
    
    # Join last names with `van` in them 
    if 'van' in name:
        new_split = name.rsplit(' ')
        if len(new_split) > 2:
            name = new_split[0] + ' ' + ''.join(new_split[1:])
        else:
            pass
    
    # Join last names with articles in them
    elif 'de' in name or 'dos' or 'da' in name or 'do' in name:
        new_split = name.rsplit(' ')
        if 'del' in new_split:
            article = 'del'
        elif 'dos' in new_split:
            article = 'dos'
        elif 'da' in new_split:
            article = 'da'
        elif 'do' in new_split:
            article = 'do'
        elif 'de' in new_split:
            article = 'de'
        else:
            article = 'none'
        if len(new_split) > 2:
            new_split = np.asarray(new_split)
            de_idx, = np.where(new_split == article) # where the article is
            if len(de_idx) != 0:
                first = ' '.join(new_split[:de_idx[0]]) # first is the name up to the article
                last = ''.join(new_split[de_idx[0]:]) # last is the name from the article onward
                name = ' '.join([first, last])
            
    # makes sure the name is in lower case, do a final strip
    return name.lower().strip()

In [13]:
def firstlast_names(input_name):
    
    if isinstance(input_name, str):
        
        # Pass name into primary format editor
        name = edit_names(input_name)
        
        if name != '':
            # split the string into a list
            split_col = [i.strip() for i in name.rsplit(' ') if isinstance(i, str)]

            if len(split_col) == 1:
                split_col = [edit_names(i) for i in input_name.rsplit('.') if isinstance(i, str) and edit_names(i) != '']

            if len(split_col) == 1:
                # still 1, just return the name
                return name

            if len(split_col[0]) == 1:
                # Example: 
                # >> split_col = ['k', 'yokuda']
                # >> first_mid_initial = ['k']
                first_mid_initial = split_col[0]

            # Check if the first inital actually contains a middle inital in the form of a string with length = 2
            # (string with length > 2 could mean a full first name is written out)

            #If the first inital has actually two letters
            elif len(split_col[0]) == 2 and len(split_col) < 3: 
                # Example: 
                # >> split_col = ['km', 'yokuda']
                # >> first_mid_initial = ['km']
                first_mid_initial = split_col[0][:2]

            else:
                # If there is a middle name
                if len(split_col) >= 4: 

                    if [i for i in split_col[0]] == [split_col[1][0], split_col[2][0], split_col[3][0]]:
                        # Example: 
                        # >> split_col = ['kmy', 'kelly', 'marie', 'yokuda'] 
                        # >> first_mid_initial = 'km'
                        first_mid_initial = split_col[1][0] + split_col[2][0]

                    else:
                        # Example:
                        # >> split_col = ['kelly', 'maire', 'yoshi', 'yokuda']
                        # >> first_mid_initial = 'kmy'
                        first_mid_initial = split_col[0][0] + split_col[1][0] + split_col[2][0]

                elif len(split_col) == 3:
                    # Example:
                    # >> split_col = ['kelly', 'maire', 'yokuda']
                    # >> first_mid_initial = 'km'
                    first_mid_initial = split_col[0][0] + split_col[1][0]

                elif len(split_col) == 2:
                    # To help give more spicific identiy to asian names

                    # Option 1:
                    # split_col = ['jingying', 'liu']
                    # first_mid_initial = 'jy'
                    match = re.match(r'(.ing)(.ing)', split_col[0])
                    if match:
                        first_mid_initial = match.group(1)[0] + match.group(2)[0]
                    elif match == None:
                        # Option 2:
                        # >> split_col = ['jingjin' 'dong']
                        # >> first_mid_initial = jj
                        match = re.match(r'(.ing)(.in)', split_col[0])
                        if match:
                            first_mid_initial = match.group(1)[0] + match.group(2)[0]
                        elif match == None:
                            # Option 3:
                            # >> split_col = ['zhongyao', 'jiang']
                            # >> first_mid_initial = zy
                            match = re.match(r'(..ong)(.ao)', split_col[0])
                            if match:
                                first_mid_initial = match.group(1)[0] + match.group(2)[0]
                            # Option 4:
                            # >> split_col = ['xuemei', 'li']
                            # >> first_mid_initial = 'xuemei'
                            if (split_col[0][0] == 'x' or split_col[0][0] == 'y') and (split_col[1][0] == 'z' or split_col[1][0] == 'l'):
                                first_mid_initial = split_col[0]
                            elif match == None:
                                # No middle name
                                # Example:
                                # >> split_col = ['kelly', 'yokuda']
                                # >> first_mid_initial = 'k'
                                first_mid_initial = split_col[0][0]


            last_name = split_col[-1]
            return ' '.join([first_mid_initial, last_name]).strip()
    
    else:
        return None

In [14]:
def edit_papers_names(row):
    return [firstlast_names(i) for i in row]

def edit_query_names(row):
    split_col = [i.strip() for i in row['Query'].rsplit(' - ')]
    name = split_col[0]
    ret_val = firstlast_names(name)
    return ret_val

In [15]:
query_df = query_df.assign(query_author = query_df.apply(edit_query_names, axis = 1))

In [16]:
query_df.sample(3)

,id,Query,Source,Papers,Citations,Years,Cites_Year,Cites_Paper,Cites_Author,Papers_Author,...,star_count,year_first,year_last,ECC,acc1,acc2,acc5,acc20,hA,query_author
496,496,"Ming Li - Postdoctoral associate, University o...",Google Scholar Profile,11,145,5,29.00,13.18,26.69,2.42,...,3,2018,2023,145,7,7,4,0,5,m li
234,234,Claudia Caddeo - Consiglio Nazionale delle Ric...,Google Scholar Profile,38,1064,14,76.00,28.00,244.16,9.05,...,6,2009,2022,1064,30,26,15,0,8,c caddeo
331,331,Juliane Borchert - Group Leader Fraunhofer ISE...,Google Scholar Profile,24,705,9,78.33,29.38,110.38,5.44,...,8,2014,2022,705,13,12,11,2,9,j borchert

In [17]:
result = query_df['query_author'].value_counts().sum() == query_df['Query'].value_counts().sum()
print('Are the number of unqiue Queries maintained?\t', result)

Are the number of unqiue Queries maintained?	 True

Make a `sub_query_df`

In [18]:
sub_query_df = query_df.loc[:, ['id', 'query_author']]

In [19]:
sub_query_df.head()

   id query_author
0   0    e sargent
1   1       n koch
2   2      d neher
3   3     d duprez
4   4    s makarov

Perform the same name formatting process of the names in the `first_auth`, `second_auth` and `third_auth` columns in `papers_df`.

In [20]:
papers_df.loc[:, ['first_auth', 'second_auth', 'third_auth']] = papers_df.loc[:, ['first_auth', 'second_auth', 'third_auth']].apply(edit_papers_names)

In [21]:
papers_df.loc[:, ['first_auth', 'second_auth', 'third_auth']].sample(3)

     first_auth   second_auth  third_auth
3055  jd butson  pr narangari  m lysevych
2789   s mandal         s pal    ak kundu
9268    a seong         j kim      o kwon

Make a `sub_papers_df`

In [22]:
sub_papers_df = papers_df.loc[:, ['query_id', 'ManuscriptTitle', 'first_auth', 'second_auth', 'third_auth']]

In [23]:
sub_papers_df.sample(3)

,query_id,ManuscriptTitle,first_auth,second_auth,third_auth
7275,17,Cation effect on excitons in perovskite nanocr...,l liu,f pevere,f zhang
6589,329,Hole transfer dynamics from photoexcited cesiu...,a de,n mondal,a samanta
12100,24,A First Approach to White Organic Electrolumin...,m heo,j kim,jy kim

Join the data frames using inner join

In [24]:
join_df = pd.merge(left = sub_papers_df, right = sub_query_df, left_on = 'query_id', right_on = 'id').drop('id', axis = 1)
join_df.head()

,query_id,ManuscriptTitle,first_auth,second_auth,third_auth,query_author
0,0,Low trap-state density and long carrier diffus...,d shi,v adinolfi,r comin,e sargent
1,0,Efficient and stable solution-processed planar...,h tan,a jain,o voznyy,e sargent
2,0,Homogeneously dispersed multimetal oxygen-evol...,b zhang,x zheng,o voznyy,e sargent
3,0,CO2 electroreduction to ethylene via hydroxide...,ct dinh,t burdyny,mg kibria,e sargent
4,0,What would it take for renewably powered elect...,p luna,c hahn,d higgins,e sargent

In [25]:
result = papers_df.shape[0] == join_df.shape[0]
print('Are the number of rows maintained?\t', result)

Are the number of rows maintained?	 True

Let's check the number of unique authors.

In [26]:
def get_unique_auth(df):
    
    author_list = np.concatenate(df.loc[:, ['first_auth', 'second_auth', 'third_auth']].values)
    auth_ser = pd.Series(author_list)
    
    og_names = auth_ser.unique().shape[0]
    print(f"There are {og_names} unique author names")

In [27]:
get_unique_auth(join_df)

There are 16654 unique author names

In [28]:
from difflib import SequenceMatcher

def all_same(itemlist):
    '''
    Dermines if all the elements in a list are the same.
    
    '''
    return all(x == itemlist[0] for x in itemlist)

def pull_name3(row, v, col = None):
    
    '''
    For each title in the data set, check if there is more than one citation. If there is, check
    if the first authors names are formatted in the same way. If not, print the variation of the 
    name that is the longest.
    '''
    if v == 'v1':
        og_vals = row
    elif v == 'v2':
        og_vals = row[col].values
    
    #print(og_vals)
    new_vals = np.unique([i for i in og_vals if isinstance(i, str)])
    
    if len(new_vals) > 1:
        replace_dic = {}
        if all_same(new_vals) == False:
            last_names = set([i.rsplit(' ')[-1] for i in new_vals]) # make a list of the last names
            first_initial = set([i.rsplit(' ')[0] for i in new_vals]) # make a list of the first initial
            if len(last_names) == 1 and len(first_initial) == 1: # Check if the last names are all the same.
                print(new_vals)
                top_length = 0
                top_name = ''
                for i in new_vals:
                    if isinstance(i, str):
                        # Checking the series of value counts
                        name, cts = auth_val[auth_val.index == i].index, auth_val[auth_val.index == i].values
                        print(name)
                        length = len(name[0])
                        if length > top_length:
                            top_length = length
                            top_name = name
                    else:
                        pass
                for i in new_vals:
                    if isinstance(i, str):
                        replace_dic[i] = top_name[0]
                    else:
                        pass
                    
            else: # if the last names aren't the same
                for i in range(0, len(new_vals)):
                    for j in range(i+1, len(new_vals)):
                        a = new_vals[i]
                        b = new_vals[j]

                        pass_letters =  ['x', 'y', 'z']
                        ## These are letters that many asian names that would be considered > 80% similar by the seqeunce matcher would start with, but the names are meant to be different

                        if a != b and a[0] == b[0] and a[0] not in pass_letters and b[0] not in pass_letters: # the names aren't the same, but they start with the same letter
                            r = SequenceMatcher(None, a, b).ratio()

                            if r > 0.80: # if the names are at least 85% similar
                                name = [a,b]
                                name.sort(reverse = False, key = len)
                                replace_dic.update({name[0] : name[1]})
                
            if len(replace_dic) != 0: #if replace_dic is not empty
                return replace_dic
            else:
                return False
        else:
            return False
    else:
        return False

First apply on groups by `Title`

In [29]:
## Initiate Replacement dictionary
replace_dic = {}

# Loop over each author column
for i in ['first_auth', 'second_auth', 'third_auth', 'query_author']:
    return_vals = join_df.groupby('ManuscriptTitle').apply(pull_name3, v = 'v2', col = i).values
    for k in return_vals[return_vals != False]:
        replace_dic.update(k) 

replace_dic

{}

Let's replace the `join_df` with these values.

In [30]:
join_df = join_df.replace(replace_dic)
get_unique_auth(join_df)

There are 16654 unique author names

Now let's group by row of `first_auth`, `second_auth` and `third_auth`

In [31]:
## Initiate Replacement dictionary
replace_dic = {}

for i in range(join_df.shape[0]):
    vals = join_df.loc[i, 'first_auth':].values
    return_vals = pull_name3(vals, v = 'v1')
    if return_vals != False:
        replace_dic.update(return_vals)

replace_dic

{'e sargent': 'eh sargent',
 'a kiani': 'ar kirmani',
 's mahshid': 'ss mahshid',
 'o bakr': 'om bakr',
 'a de': 'a dey',
 'd lidzey': 'dg lidzey',
 't wu': 'tz wu',
 'e aydil': 'es aydil',
 'g xing': 'gc xing',
 'g ding': 'g xing',
 'j berry': 'jj berry',
 'j gong': 'j tong',
 'k weber': 'kj weber',
 'l wan': 'l wang',
 'j kim': 'jy kim',
 's lee': 'sj lee',
 'jw kim': 'jy kim',
 'h kim': 'hb kim',
 'h cho': 'h choi',
 'jr kim': 'jy kim',
 'j luther': 'jm luther',
 'm saba': 'mi saba',
 'm bodnarchuk': 'mi bodnarchuk',
 'd dirin': 'dn dirin',
 'g eperon': 'ge eperon',
 'ej jurezprez': 'ej juarezperez',
 'b rosen': 'ba rosen',
 'j lee': 'jh lee',
 'n marco': 'nd marco',
 'e wong': 'el wong',
 'c soe': 'cmm soe',
 'j snaider': 'jm snaider',
 'pg fernndez': 'pg fernandez',
 'p fernndez': 'pg fernandez',
 'p fernandez': 'pg fernandez',
 'tj savenije': 'tj savenjie',
 't savenije': 'tj savenije',
 'a mclaughlin': 'ac mclaughlin',
 'q ou': 'qd ou',
 'j tang': 'j yang',
 'd stein': 'dm stein',
 'm lemme': 'mc lemme',
 'h zhong': 'hz zhong',
 'f grozema': 'fc grozema',
 'a kandada': 'ars kandada',
 'as kandada': 'ars kandada',
 'd wu': 'di wu',
 'm otoniar': 'm otonicar',
 'b kamino': 'ba kamino',
 'j dong': 'jj dong',
 'w mao': 'wx mao',
 'c clark': 'cp clark',
 'l lehner': 'le lehner',
 'a tarasov': 'ab tarasov',
 'h liu': 'hc liu',
 'j blackburn': 'jl blackburn',
 's yakunin': 'sv yakunin',
 'k guo': 'kp guo',
 'r sabatini': 'rp sabatini',
 'j hao': 'ji hao',
 'g nfrdi': 'g nafradi',
 'i moraser': 'i morasero',
 't pauport': 't pauporte',
 's ovsyannikov': 'sv ovsyannikov',
 'a aslandukov': 'aa aslandukova',
 'h ahin': 'h sahin',
 'j yin': 'j yin#',
 'm saidaminov': 'mi saidaminov',
 'r patterson': 'rj patterson',
 'b larson': 'bw larson',
 'i park': 'ih park',
 't macdonald': 'tj macdonald',
 'a urban': 'as urban',
 'h tahini': 'ha tahini',
 'c lin': 'ch lin',
 'm hu': 'my hu',
 'm crane': 'mj crane',
 'm li': 'mx li',
 'd yang': 'dw yang',
 'l sheng': 'l zheng',
 'r kennard': 'rm kennard',
 'a delaguila': 'ag delguila',
 'a delguila': 'ag delguila',
 'r zhang': 'rc zhang',
 'j park': 'jm park',
 'c alexander': 'ct alexander',
 'b finkenauer': 'bp finkenauer',
 'j lim': 'jwm lim',
 'd hung': 'dl hung',
 'b martngarca': 'b martingarcia',
 'g miguel': 'g demiguel',
 'n miao': 'nh miao',
 'p groszewicz': 'pb groszewicz',
 'e popczun': 'ej popczun',
 'a krause': 'ar krause',
 'h geng': 'hf geng',
 'r scheidt': 'ra scheidt',
 'l buizza': 'lrv buizza',
 't hu': 'te hu',
 's cuthriell': 'sa cuthriell',
 'p huang': 'pj huang',
 's makarov': 'sv makarov',
 'mi petrov': 'mi petrova',
 'jm pastor': 'jpm pastor',
 'j pastor': 'jpm pastor',
 'e gaulding': 'ea gaulding',
 'e tiguntseva': 'ey tiguntseva',
 'l maral': 'lab maral',
 'j mao': 'j mao#',
 'b zhang': 'bo zhang',
 'j liu': 'jy liu',
 'e sandars': 'e sanders',
 's sharma': 'sn sharma',
 'p maity': 'p maity#',
 'i koutselas': 'ib koutselas',
 'r rodriguez': 'rg rodriguez',
 'm nellikkal': 'man nellikkal',
 'k zanoni': 'kps zanoni',
 'q dong': 'qi dong',
 'b tredi': 'b turedi',
 'mar preciado': 'ma ruizpreciado',
 'v nair': 'vm nair',
 'l fernndezizquierdo': 'l fernandezizquierdo',
 'k armadorou': 'kk armadorou',
 'k vansant': 'kt vansant',
 'j howard': 'jm howard',
 'h dang': 'hx dang',
 'm aguirre': 'mh aguirre',
 'mh aguire': 'mh aguirre',
 'mh aguirre': 'ml aguirre',
 't kasel': 'tw kasel',
 'w geerts': 'wj geerts',
 'g weng': 'ge weng',
 'e patterson': 'ea patterson',
 'c deer': 'c deger',
 'p bagul': 'pm bagul',
 'd kang': 'dw kang',
 'j popovi': 'j popovic',
 'f dong': 'ff dong',
 'd gangadharan': 'dt gangadharan',
 's svanstrm': 's svanstrom',
 'e zheng': 'ej zheng',
 'f pearsall': 'fa pearsall',
 'a vrez': 'a varez',
 'l martin': 'los martin',
 'p linkov': 'pa linkov',
 'b charles': 'bl charles',
 'b sorenson': 'ba sorenson',
 'c watts': 'cl watts',
 'k babu': 'kj babu',
 'e welch': 'ew welch',
 'r beal': 'ra beal',
 'a franciscolpez': 'a franciscolopez',
 's chin': 'sh chin',
 'ms holanda': 'm deholanda',
 'a mohapatra': 'aa mohapatra',
 't sheehan': 'tj sheehan',
 'a garcafernndez': 'a garciafernandez',
 'r parmee': 'rj parmee',
 'w hsu': 'wj hsu',
 'g aalbers': 'gjw aalbers',
 'ls oliveira': 'ls deoliveira',
 's khandy': 'sa khandy',
 'v shukla': 'vk shukla',
 'b madhukar': 'bs madhukar',
 'g aka': 'g akca',
 'ca vasilescu': 'cas vasilescu',
 'a bhogra': 'aa bhogra',
 'j igartua': 'jm igartua',
 'j li': 'j liu',
 'p price': 'pm price',
 't david': 'tw david',
 's kumavat': 'sr kumavat',
 'a fonseca': 'afv dafonseca',
 'a dafonseca': 'afv dafonseca',
 'av dafonseca': 'afv dafonseca',
 'm vruini': 'm vrucinic',
 'h adl': 'hp adl',
 'j aramburu': 'ja aramburu',
 'ae bocrnea': 'ae bocirnea',
 'a bocrnea': 'ae bocirnea',
 'a bocirnea': 'ae bocirnea',
 's jambure': 'sb jambure',
 'm alhadidi': 'ms alhadidi',
 's jaffri': 'sb jaffri',
 'am silva': 'am dasilva',
 's surezvzquez': 'si surezvzquez',
 'd panemangalore': 'db panemangalore',
 'f bachraoui': 'fe bachraoui',
 'i koryakina': 'igk koriakina',
 'ig koryakina': 'igk koriakina',
 'p sghy': 'p saghy'}

Let's replace the `join_df` with these values.

In [32]:
join_df = join_df.replace(replace_dic)
get_unique_auth(join_df)

There are 16512 unique author names

We end up with 16,254 unique authors from the original 16,397.

In [33]:
print('Thats {:0.3g} of unqiue authors introduced per papers!'.format(papers_df.shape[0]/16254))

Thats 1.08 of unqiue authors introduced per papers!

In [34]:
join_df.head()

,query_id,ManuscriptTitle,first_auth,second_auth,third_auth,query_author
0,0,Low trap-state density and long carrier diffus...,d shi,v adinolfi,r comin,eh sargent
1,0,Efficient and stable solution-processed planar...,h tan,a jain,o voznyy,eh sargent
2,0,Homogeneously dispersed multimetal oxygen-evol...,bo zhang,x zheng,o voznyy,eh sargent
3,0,CO2 electroreduction to ethylene via hydroxide...,ct dinh,t burdyny,mg kibria,eh sargent
4,0,What would it take for renewably powered elect...,p luna,c hahn,d higgins,eh sargent

Let's overwrite the `first_auth`, `second_auth`, `third_auth` columns `papers_df` with `join_df` with the addition of the `query_author` column.

In [35]:
papers_df.loc[:, ['first_auth', 'second_auth', 'third_auth']] = join_df.loc[:, ['first_auth', 'second_auth', 'third_auth']]
papers_df = pd.concat([papers_df, join_df.loc[:, 'query_author']], axis = 1)

In [36]:
papers_df.head()

,first_auth,second_auth,third_auth,Cites,ManuscriptTitle,Year,GSRank,ECC,CitesPerYear,CitesPerAuthor,AuthorCount,query_id,PubTitle,PubType,SJR,H index,Country,Region,query_author
0,d shi,v adinolfi,r comin,4186,Low trap-state density and long carrier diffus...,2015,1,4186,523.25,523,8,0,science,journal,14.589,1229.0,United States,Northern America,eh sargent
1,h tan,a jain,o voznyy,1951,Efficient and stable solution-processed planar...,2017,4,1951,325.17,279,7,0,science,journal,14.589,1229.0,United States,Northern America,eh sargent
2,bo zhang,x zheng,o voznyy,1756,Homogeneously dispersed multimetal oxygen-evol...,2016,7,1756,250.86,251,7,0,science,journal,14.589,1229.0,United States,Northern America,eh sargent
3,ct dinh,t burdyny,mg kibria,1343,CO2 electroreduction to ethylene via hydroxide...,2018,11,1343,268.60,224,6,0,science,journal,14.589,1229.0,United States,Northern America,eh sargent
4,p luna,c hahn,d higgins,1168,What would it take for renewably powered elect...,2019,14,1168,292.00,195,6,0,science,journal,14.589,1229.0,United States,Northern America,eh sargent

Save the new data frames

## Part 3

Let's look to see if there are any null values.

In [37]:
num = papers_df.isna().sum().sum()
print(f'There are {num} null values in the data set')
get_unique_auth(papers_df)

There are 1050 null values in the data set
There are 16512 unique author names

In [38]:
(papers_df.isna().sum()/papers_df.isna().count()).sort_values(ascending=False)

third_auth         0.049864
second_auth        0.009644
first_auth         0.000057
query_id           0.000000
Region             0.000000
Country            0.000000
H index            0.000000
SJR                0.000000
PubType            0.000000
PubTitle           0.000000
CitesPerAuthor     0.000000
AuthorCount        0.000000
CitesPerYear       0.000000
ECC                0.000000
GSRank             0.000000
Year               0.000000
ManuscriptTitle    0.000000
Cites              0.000000
query_author       0.000000
dtype: float64

The remaining null values are for `third_auth`. Initially, I wanted to keep the rows with null `third_auth` columns, but since it only contains about 5% of the data, let's remove those rows for completeness.

In [39]:
papers_df = papers_df.dropna(subset = 'third_auth')

In [40]:
num = papers_df.isna().sum().sum()
print(f'There are {num} null values in the data set')
get_unique_auth(papers_df)

There are 0 null values in the data set
There are 16402 unique author names

All the null values are removed!

Let's remove the duplicated citations.

First, let's remove some special characters from the titles incase that increases the number of duplicate citations.

In [41]:
import re

def replace_char(row):
    print(row['ManuscriptTitle'])
    return re.sub(r'[\!\:\-\,]', '', row['ManuscriptTitle'])

In [42]:
papers_df = papers_df.assign(ManuscriptTitle = papers_df.apply(replace_char, axis = 1))

Low trap-state density and long carrier diffusion in organolead trihalide perovskite single crystals
Efficient and stable solution-processed planar perovskite solar cells via contact passivation
Homogeneously dispersed multimetal oxygen-evolving catalysts
CO2 electroreduction to ethylene via hydroxide-mediated copper catalysis at an abrupt interface
What would it take for renewably powered electrosynthesis to displace petrochemical processes?
Challenges for commercializing perovskite solar cells
Building devices from colloidal quantum dots
Colloidal quantum-dot photodetectors exploiting multiexciton generation
CO2 electrolysis to multicarbon products at activities greater than 1 A cm−2
Efficient tandem solar cells with solution-processed perovskite on textured crystalline silicon
Thermal unequilibrium of strained black CsPbI3 thin films
Semiconductor quantum dots: Technological progress and future challenges
CO2 electrolysis to multicarbon products in strong acid
Chloride-mediated selective electrosynthesis of ethylene and propylene oxides at high current density
Erratum: What would it take for renewably powered electrosynthesis to displace petrochemical processes?(Science
Rational design of Lewis base molecules for stable and efficient inverted perovskite solar cells
What would it take for renewably powered electrosynthesis to displace petrochemical processes?(vol 364, eaav3506, 2019)
Monolithic perovskite/silicon tandem solar cell with> 29% efficiency by enhanced hole extraction
Electromechanical properties of an ultrathin layer of directionally aligned helical polypeptides
Powering up perovskite photoresponse
Photon-mediated hybridization of Frenkel excitons in organic semiconductor microcavities
Gas chromatography–mass spectrometry analyses of encapsulated stable perovskite solar cells
Hot-electron transfer from semiconductor nanocrystals
Stable ordering in Langmuir-Blodgett films
Getting Moore from solar cells
Long-range balanced electron-and hole-transport lengths in organic-inorganic CH3NH3PbI3
Stabilizing black-phase formamidinium perovskite formation at room temperature and high humidity
Triple-halide wide–band gap perovskites with suppressed phase segregation for efficient tandems
Efficient, stable silicon tandem cells enabled by anion-engineered wide-bandgap perovskites
Chiral-induced spin selectivity enables a room-temperature spin light-emitting diode
Metastable Dion-Jacobson 2D structure enables efficient and stable perovskite solar cells
Comment on “Light-induced lattice expansion leads to high-efficiency perovskite solar cells”
Compositional texture engineering for highly stable wide-bandgap perovskite solar cells
A piperidinium salt stabilizes efficient metal-halide perovskite solar cells
Band structure engineering in organic semiconductors
Accelerated aging of all-inorganic, interface-stabilized perovskite solar cells
Ion-modulated radical doping of spiro-OMeTAD for more efficient and stable perovskite solar cells
Control of polarization in bulk ferroelectrics by mechanical dislocation imprint
Induced giant piezoelectricity in centrosymmetric oxides
Efficient tandem polymer solar cells fabricated by all-solution processing
Conformal quantum dot–SnO2 layers as electron transporters for efficient perovskite solar cells
Incorporation of rubidium cations into perovskite solar cells improves photovoltaic performance
Promises and challenges of perovskite solar cells
Highly efficient pin perovskite solar cells that endure temperature variations
About The Cover
Terawatt-scale photovoltaics: Transform global energy
Quantum dot–induced phase stabilization of α-CsPbI3 perovskite for high-efficiency photovoltaics
Peak external photocurrent quantum efficiency exceeding 100% via MEG in a quantum dot solar cell
Cooling Bose-Einstein condensates below 500 picokelvin
Light scattering to determine the relative phase of two Bose-Einstein condensates
Continuous measurement of the relative phase of two Bose-Einstein condensates using light scattering
Properties and potential optoelectronic applications of lead halide perovskite nanocrystals
Controlling the nucleation and growth kinetics of lead halide perovskite quantum dots
DNA origami with complex curvatures in three-dimensional space
Electron-hole diffusion lengths exceeding 1 micrometer in an organometal trihalide perovskite absorber
A mixed-cation lead mixed-halide perovskite absorber for tandem solar cells
Impact of microstructure on local carrier lifetime in perovskite solar cells
Photovoltaic materials: Present efficiencies and future challenges
Photon recycling in lead iodide perovskite solar cells
Ionic liquid–mediated selective conversion of CO2 to CO at low overpotentials
Homogenized halides and alkali cation segregation in alloyed organic-inorganic perovskites
A generic interface to reduce the efficiency-stability-cost gap of perovskite solar cells
Scalable processing for realizing 21.7%-efficient all-perovskite tandem solar modules
Cooperative carbon capture and steam regeneration with tetraamine-appended metal–organic frameworks
Single-mode laser by parity-time symmetry breaking
An ultrathin invisibility skin cloak for visible light
Phase mismatch–free nonlinear propagation in optical zero-index materials
Impact of Microstructure on Local Carrier Lifetime in Perovskite Solar Cells
Damp heat–stable perovskite solar cells with tailored-dimensionality 2D/3D heterojunctions
Efficient and stable perovskite-silicon tandem solar cells through contact displacement by MgFx
A. u. Rehman, C.-L. Wang, TD Anthopoulos, U. Schwingenschlögl, MD Bastiani, E. Aydin and SD Wolf
Stability of Perovskite Solar Cells: A Prospective on the Substitution of the A Cation and X Anion
Directly visualizing the momentum-forbidden dark excitons and their dynamics in atomically thin semiconductors
Extremely efficient internal exciton dissociation through edge states in layered 2D perovskites
Atomic-scale microstructure of metal halide perovskite
Comment on “Resolving spatial and energetic distributions of trap states in metal halide perovskite solar cells”
Long-range hot-carrier transport in hybrid perovskites visualized by ultrafast microscopy
Deterministic fabrication of 3D/2D perovskite bilayer stacks for durable and efficient solar cells
High-performance light-emitting diodes based on carbene-metal-amides
Terahertz field–induced ferroelectricity in quantum paraelectric SrTiO3
Liquid-phase sintering of lead halide perovskites and metal-organic framework glasses
An ingestible bacterial-electronic system to monitor gastrointestinal health
Engineering spin-orbit synthetic Hamiltonians in liquid-crystal optical cavities
Efficient, stable solar cells by using inherent bandgap of α-phase formamidinium lead iodide
Impact of strain relaxation on performance of α-formamidinium lead iodide perovskite solar cells
Perovskite light-emitting diodes with external quantum efficiency exceeding 20 per cent
Ultrasensitive solution-cast quantum dot photodetectors
Enhanced electrocatalytic CO2 reduction via field-induced reagent concentration
Materials interface engineering for solution-processed photovoltaics
Efficient and stable emission of warm-white light from lead-free halide double perovskites
Accelerated discovery of CO2 electrocatalysts using active machine learning
Quantum-dot-in-perovskite solids
Molecular tuning of CO2-to-ethylene conversion
Continuous-wave lasing in colloidal quantum dot solids enabled by facet-selective epitaxy
All-perovskite tandem solar cells with improved grain surface passivation
Photovoltage field-effect transistors
Lattice anchoring stabilizes solution-processed semiconductors
Distribution control enables efficient reduced-dimensional perovskite LEDs
Use machine learning to find energy materials
Renewables need a grand-challenge strategy
Regulating surface potential maximizes voltage in all-perovskite tandems
Synthesis-on-substrate of quantum dot solids
CORRECTIONS &AMENDMENTS
Improving the performance of doped π-conjugated polymers for use in organic light-emitting diodes
Perovskite–organic tandem solar cells with indium oxide interconnect
All-inorganic perovskite nanocrystal scintillators
Strong exciton–photon coupling in an organic semiconductor microcavity
Electroluminescence in polymer films
High-κ perovskite membranes as insulators for two-dimensional transistors
Mechanism of hydrogen-induced crystallization of amorphous silicon
Persistent sourcing of coherent spins for multifunctional semiconductor spintronics
On-device lead sequestration for perovskite solar cells
Surface reaction for efficient and stable inverted perovskite solar cells
Centimetre-scale perovskite solar cells with fill factors of more than 86 per cent
Planar perovskite solar cells with long-term stability using ionic liquid additives
The role of charge recombination to triplet excitons in organic solar cells
Atomically engineered interfaces yield extraordinary electrostriction
Observation of room-temperature polar skyrmions
Spatially resolved steady-state negative capacitance
Pseudo-halide anion engineering for α-FAPbI3 perovskite solar cells
The effect of illumination on the formation of metal halide perovskite films
High-efficiency two-dimensional Ruddlesden–Popper perovskite solar cells
An exciting boost for solar cells
High-temperature ultrafast polariton parametric amplification in semiconductor microcavities
Rule-breaking perovskites
NEWS &VIEWS RESEARCH
Maximizing and stabilizing luminescence from halide perovskites with potassium passivation
Quasicrystalline order in self-assembled binary nanoparticle superlattices
Superfluorescence from lead halide perovskite quantum dot superlattices
Perovskite-type superlattices from lead halide perovskite nanocubes
Negative lattice expansion from the superconductivity–antiferromagnetism crossover in ruthenium copper oxides
Correction: Negative lattice expansion from the superconductivity–antiferromagnetism crossover in ruthenium copper oxides
Topological polaritons and photonic magic angles in twisted α-MoO3 bilayers
Sensitization of silicon by singlet exciton fission in tetracene
In-plane anisotropic and ultra-low-loss polaritons in a natural van der Waals crystal
Bright triplet excitons in caesium lead halide perovskites
Performance-limiting nanoscale trap clusters at grain junctions in halide perovskites
Approaching the Schottky–Mott limit in van der Waals metal–semiconductor junctions
Approaching the intrinsic exciton physics limit in two-dimensional semiconductor diodes
Local nanoscale phase impurities are degradation sites in halide perovskites
Two-dimensional halide perovskite lateral epitaxial heterostructures
The advent of crystalline organic electronics
Crystalline order offers access to high speeds for organic transistors
Highly efficient and stable InP/ZnSe/ZnS quantum dot light-emitting diodes
Perovskite solar cells with atomically coherent interlayers on SnO2 electrodes
Ligand-engineered bandgap stability in mixed-halide perovskite LEDs
Perovskite oxides for visible-light-absorbing ferroelectric and photovoltaic materials
G.; Gallo, EM; Akbashev, ER; Davies, PK; Spanier, JE; Rappe, AM
Solution-processed PbS quantum dot infrared photodetectors and photovoltaics
Colloidal-quantum-dot photovoltaics using atomic-ligand passivation
Air-stable n-type colloidal quantum dot solids
Hybrid organic–inorganic inks flatten the energy landscape in colloidal quantum dot solids
Electron–phonon interaction in efficient perovskite blue emitters
A general phase-transfer protocol for metal ions and its application in nanocrystal synthesis
Charge-extraction strategies for colloidal quantum dot photovoltaics
Molecular enhancement of heterogeneous CO2 reduction
Photovoltaic concepts inspired by coherence effects in photosynthetic systems
Crystal symmetry breaking and vacancies in colloidal lead chalcogenide quantum dots
Multi-cation perovskites prevent carrier reflection from grain surfaces
Boosting plant biology
Erratum: A general phase-transfer protocol for metal ions and its application in nanocrystal synthesis (Nature Materials (2009) 8 (683-689))
Orientation-dependent ionization energies and interface dipoles in ordered molecular assemblies
Towards understanding the doping mechanism of organic semiconductors by Lewis acids
Beating the thermodynamic limit with photo-activation of n-doping in organic semiconductors
Band gap engineering in blended organic semiconductor films based on dielectric interactions
Efficient charge generation by relaxed charge-transfer states at organic interfaces
Novel approaches to polymer blends based on polymer nanoparticles
From anisotropic photo-fluidity towards nanomanipulation in the optical near-field
Emissive and charge-generating donor–acceptor interfaces for organic optoelectronics with low voltage losses
Perovskite solar cells: Shedding light on film crystallization
Polariton-mediated energy transfer between organic dyes in a strongly coupled optical microcavity
Correlating structure with fluorescence emission in phase-separated conjugated-polymer blends
Integrating graphene into semiconductor fabrication lines
Low-temperature solution-processed wavelength-tunable perovskites for lasing
Room-temperature epitaxial welding of 3D and 2D perovskites
Reducing the efficiency–stability–cost gap of organic photovoltaics with highly efficient and stable small molecule acceptor ternary solar cells
A molecular interaction–diffusion framework for predicting organic solar cell stability
Thermally activated delayed fluorescence (TADF) organic molecules for efficient X-ray scintillation and imaging
Author Correction: Thermally activated delayed fluorescence (TADF) organic molecules for efficient X-ray scintillation and imaging
Thermally activated delayed fluorescence (TADF) organic molecules for efficient X-ray scintillation and imaging (vol 21, pg 210, 2022)
Organic solar cells based on non-fullerene acceptors
Design rules for minimizing voltage losses in high-efficiency organic solar cells
Metal halide perovskites for light-emitting diodes
The negative piezoelectric effect of the ferroelectric polymer poly (vinylidene fluoride)
Domain-wall conduction in ferroelectric BiFeO3 controlled by accumulation of charged defects
Breaking of macroscopic centric symmetry in paraelectric phases of ferroelectric materials and implications for flexoelectricity
Long-range symmetry breaking in embedded ferroelectrics
Phase coexistence and electric-field control of toroidal order in oxide superlattices
Local negative permittivity and topological phase transition in polar skyrmions
Local negative permittivity and topological phase transition in polar skyrmions (vol 20, pg 194, 2021)
Efficiency enhancement in low-bandgap polymer solar cells by processing with alkane dithiols
Multiscale hierarchical structures from a nanocluster mesophase
Selected Publications
Phase-engineered low-resistance contacts for ultrathin MoS2 transistors
The role of electronic coupling between substrate and 2D MoS2 nanosheets in electrocatalytic production of hydrogen
Towards high charge-carrier mobilities by rational design of the shape and periphery of discotics
Direct–indirect character of the bandgap in methylammonium lead iodide perovskite
From window to solar cell and back
Localized surface plasmon resonances arising from free carriers in doped quantum dots
Electron-pinned defect-dipoles for high-performance colossal permittivity materials
Dopant compensation in alloyed CH3NH3PbBr3−xClx perovskite single crystals for gamma-ray spectroscopy
Direct-indirect character of the bandgap in methylammonium lead iodide perovskite
Dirac fermions and flat bands in the ideal kagome metal FeSn
High-resolution remote thermometry and thermography using luminescent low-dimensional tin-halide perovskites
The ground exciton state of formamidinium lead bromide perovskite nanocrystals is a singlet dark state
High oxide ion and proton conductivity in a disordered hexagonal perovskite
Synthesis and patterning of tunable multiscale materials with engineered cells
Resonant energy transfer of triplet excitons from pentacene to PbSe nanocrystals
Phonon coherences reveal the polaronic character of excitons in two-dimensional lead halide perovskites
Ferroelectric-field-effect-enhanced electroresistance in metal/ferroelectric/semiconductor tunnel junctions
Electrocalorics hit the top
Fully textured monolithic perovskite/silicon tandem solar cells with 25.2% power conversion efficiency
Thiol-free self-assembled oligoethylene glycols enable robust air-stable molecular electronics
Visualization of dynamic polaronic strain fields in hybrid lead halide perovskites
Dielectric control of reverse intersystem crossing in thermally activated delayed fluorescence emitters
Ferroelectrically tunable magnetic skyrmions in ultrathin oxide heterostructures
Light-induced reversal of ion segregation in mixed-halide perovskites
Intrinsic ferroelectricity in Y-doped HfO2 thin films
Formation of aligned periodic patterns during the crystallization of organic semiconductor thin films
Enhanced photocatalytic hydrogen evolution from organic semiconductor heterojunction nanoparticles
Resilient yet entirely degradable gelatin-based biogels for soft robots and electronics
Perovskite energy funnels for efficient light-emitting diodes
Hybrid passivated colloidal quantum dot solids
Nanostructured materials for photon detection
Fast, sensitive and spectrally tuneable colloidal-quantum-dot photodetectors
Bipolar-shell resurfacing for blue LEDs based on strongly confined perovskite quantum dots
Programming the detection limits of biosensors through controlled nanostructuring
Advancing the speed, sensitivity and accuracy of biomolecular detection using multi-length-scale engineering
2D matrix engineering for homogeneous quantum dot coupling in photovoltaic solids
DNA-based programming of quantum dot valency, self-assembly and luminescence
One-step DNA-programmed growth of luminescent and biofunctionalized nanocrystals
Tracking the dynamics of circulating tumour cell phenotypes using nanoparticle-mediated magnetic ranking
Regioselective magnetization in semiconducting nanorods
A sensitive pair
Industry outlook of perovskite quantum dots for display applications
Large negative differential conductance in single-molecule break junctions
The promise and challenge of nanostructured solar cells
Unity quantum yield of photogenerated charges and band-like transport in quantum-dot solids
Strategic advantages of reactive polyiodide melts for scalable perovskite photovoltaics
Strong underwater adhesives made by self-assembling multi-protein nanofibres
Observation of piezoelectricity in free-standing monolayer MoS 2
Migrating photon avalanche in different emitters at the nanoscale enables 46th-order optical nonlinearity
Improved air stability of perovskite solar cells via solution-processed metal oxide transport layers
Imaging the motion of electrons across semiconductor heterojunctions
Light-activated interlayer contraction in two-dimensional perovskites for high-efficiency solar cells
Deterministic fabrication of arbitrary vertical heterostructures of two-dimensional Ruddlesden–Popper halide perovskites
Perovskite photonic sources
Thin-film Sb2Se3 photovoltaics with oriented one-dimensional ribbons and benign grain boundaries
Sensitive solution-processed visible-wavelength photodetectors
Tandem colloidal quantum dot solar cells employing a graded recombination layer
Infrared photovoltaics made by solution processing
Highly efficient quantum dot near-infrared light-emitting diodes
Bright colloidal quantum dot light-emitting diodes enabled by efficient chlorination
Spin control in reduced-dimensional chiral perovskites
Bright high-colour-purity deep-blue carbon dot light-emitting diodes via efficient edge amination
Efficient near-infrared light-emitting diodes based on quantum dots in layered perovskite

White Light‐Emitting Diodes: High Color‐Rendering Index and Stable White Light‐Emitting Diodes by Assembling Two Broadband Emissive Self‐Trapped Excitons (Adv. Mater. 2/2021)
ITO Top‐Electrodes via Industrial‐Scale PLD for Efficient Buffer‐Layer‐Free Semitransparent Perovskite Solar Cells
A Wide Bandgap Halide Perovskite Based Self‐Powered Blue Photodetector with 84.9% of External Quantum Efficiency (Adv. Mater. 51/2022)
A Wide Bandgap Halide Perovskite Based Self‐Powered Blue Photodetector with 84.9% of External Quantum Efficiency
High‐performance ternary perovskite–organic solar cells
Defect Engineering Stabilized AgSbTe2 with High Thermoelectric Performance
Enhancing Molecular n‐Type Doping of Donor–Acceptor Copolymers by Tailoring Side Chains
N‐Type Organic Thermoelectrics of Donor–Acceptor Copolymers: Improved Power Factor by Molecular Tailoring of the Density of States
Amphipathic Side Chain of a Conjugated Polymer Optimizes Dopant Location toward Efficient N‐Type Organic Thermoelectrics
Enhancing the performance of the half tin and half lead perovskite solar cells by suppression of the bulk and interfacial charge recombination
Role of the Processing Solvent on the Electrical Conductivity of PEDOT: PSS
Solar Cells: Enhancing the Performance of the Half Tin and Half Lead Perovskite Solar Cells by Suppression of the Bulk and Interfacial Charge Recombination (Adv. Mater. 35/2018)
A Universal Perovskite Nanocrystal Ink for High‐Performance Optoelectronic Devices
ZnO Nanowire Arrays for Enhanced Photocurrent in PbS Quantum Dot Solar Cells
ZnO Nanowire Arrays for Enhanced Photocurrent in PbS Quantum Dot Solar Cells (Adv. Mater. 20/2013)
Anti‐solvent derived non‐stacked reduced graphene oxide for high performance supercapacitors
An electrolyte‐free flexible electrochromic device using electrostatically strong graphene quantum dot–viologen nanocomposites
Voltage‐controlled nonvolatile molecular memory of an azobenzene monolayer through solution‐processed reduced graphene oxide contacts
Thermoreversible Self‐Assembly of Perfluorinated Core‐Coronas Cellulose‐Nanoparticles in Dry State
New Approaches to Produce Large‐Area Single Crystal Thin Films
Thermodynamic properties and molecular packing explain performance and processing procedures of three D18: NFA organic solar cells
Efficient energy funneling in quasi‐2D perovskites: from light emission to lasing
H‐Shaped Oligofluorenes for Highly Air‐Stable and Low‐Threshold Non‐Doped Deep Blue Lasing
Enhancement of upconversion for photovoltaics with β-NaYF4: Er3+ and concentrating integrated optics
Progress towards enhancing the performance of c-si photovoltaic devices via up-and down-conversion
Unbroken perovskite: interplay of morphology, electro‐optical properties, and ionic movement
High temperature‐stable perovskite solar cell based on low‐cost carbon nanotube hole contact
Metal‐halide perovskites for gate dielectrics in field‐effect transistors and photodetectors enabled by PMMA lift‐off process
Self-rectifying threshold resistive switching based non-volatile memory of CBD/CBD grown vertical n-ZnO nanowire/p-Si heterojunction diodes
Improved outcoupling efficiency and stability of perovskite light‐emitting diodes using thin emitting layers
Thermal management enables bright and stable perovskite light‐emitting diodes
Mixed Lead–Tin Halide Perovskites for Efficient and Wavelength‐Tunable Near‐Infrared Light‐Emitting Diodes
Nanosecond‐Pulsed Perovskite Light‐Emitting Diodes at High Current Density
Hot‐Casting‐Assisted Liquid Additive Engineering for Efficient and Stable Perovskite Solar Cells
Highly efficient organic hole transporting materials for perovskite and organic solar cells with long‐term stability
External Quantum Efficiency Exceeding 24% with CIEy Value of 0.08 using a Novel Carbene‐Based Iridium Complex in Deep‐Blue Phosphorescent Organic Light …
Solar Cells: Highly Efficient Organic Hole Transporting Materials for Perovskite and Organic Solar Cells with Long‐Term Stability (Adv. Mater. 4/2016)
Impact of Solvent Additive on Carrier Transport in Polymer: Fullerene Bulk Heterojunction Photovoltaic Cells
Directional Polarized Light Emission from Thin‐Film Light‐Emitting Diodes
Chiral Phonons and Giant Magneto‐Optical Effect in CrBr3 2D Magnet
Composition‐Graded Cesium Lead Halide Perovskite Nanowires with Tunable Dual‐Color Lasing Performance
Investigation of adsorption of copper, zinc and cadmium metals by polymeric coagulant polyaluminum chloride based on density functional theory
Recent progress in materials and devices toward printable and flexible sensors
Steric impediment of ion migration contributes to improved operational stability of perovskite solar cells
Electrohydrodynamically assisted deposition of efficient perovskite photovoltaics
Single-Crystal Perovskite Solar Cells Exhibit Close to Half A Millimeter Electron-Diffusion Length
Stable light‐emitting diodes using phase‐pure Ruddlesden–Popper layered perovskites
The impact of atmosphere on the local luminescence properties of metal halide perovskite grains
High‐Pressure‐Induced Comminution and Recrystallization of CH3NH3PbBr3 Nanocrystals as Large Thin Nanoplates
Tailored amphiphilic molecular mitigators for stable perovskite solar cells with 23.5% efficiency
Understanding detrimental and beneficial grain boundary effects in halide perovskites
Electrical Stress Influences the Efficiency of CH3NH3PbI3 Perovskite Light Emitting Devices
Efficient and Spectrally Stable Blue Perovskite Light‐Emitting Diodes Employing a Cationic π‐Conjugated Polymer
Toward All Room‐Temperature, Solution‐Processed, High‐Performance Planar Perovskite Solar Cells: A New Scheme of Pyridine‐Promoted Perovskite Formation
Photoexcitation Dynamics and Long‐Lived Excitons in Strain‐Engineered Transition Metal Dichalcogenides
A Comparison of Charge Carrier Dynamics in Organic and Perovskite Solar Cells
Diverging Expressions of Anharmonicity in Halide Perovskites
An electronically driven improper ferroelectric: tungsten bronzes as microstructural analogs for the hexagonal manganites
Improper Ferroelectricity: An Electronically Driven Improper Ferroelectric: Tungsten Bronzes as Microstructural Analogs for the Hexagonal Manganites (Adv. Mater. 40/2019)
Doping and Switchable Photovoltaic Effect in Lead‐Free Perovskites Enabled by Metal Cation Transmutation
Cubic NaSbS2 as an Ionic–Electronic Coupled Semiconductor for Switchable Photovoltaic and Neuromorphic Device Applications
Retina‐inspired carbon nitride‐based photonic synapses for selective detection of UV light
A 2D Titanium Carbide MXene Flexible Electrode for High‐Efficiency Light‐Emitting Diodes
Water Passivation of Perovskite Nanocrystals Enables Air‐Stable Intrinsically Stretchable Color‐Conversion Layers for Stretchable Displays
Graphene‐Based Intrinsically Stretchable 2D‐Contact Electrodes for Highly Efficient Organic Light‐Emitting Diodes
Overcoming the Limitations of MXene Electrodes for Solution-Processed Optoelectronic Devices
Photonic Synapses: Retina‐Inspired Carbon Nitride‐Based Photonic Synapses for Selective Detection of UV Light (Adv. Mater. 11/2020)
Advancements in Electronic Materials and Devices for Stretchable Displays
Progress and Prospects of Nanoscale Emitter Technology for AR/VR Displays
Overcoming the Limitations of MXene Electrodes for Solution-Processed Optoelectronic Devices (Adv. Mater. 41/2022)
Graphene‐Based Intrinsically Stretchable 2D‐Contact Electrodes for Highly Efficient Organic Light‐Emitting Diodes (Adv. Mater. 31/2022)
Influence of Nickel Oxide Additive on the Properties of Sol-Gel Prepared Aluminum Borate Whisker
Toward High‐Performance Triboelectric Nanogenerators by Engineering Interfaces at the Nanoscale: Looking into the Future Research Roadmap
Monolithic All‐Perovskite Tandem Solar Cells with Minimized Optical and Energetic Losses
Monolithic All‐Perovskite Tandem Solar Cells with Minimized Optical and Energetic Losses (Adv. Mater. 11/2022)
Detrimental Effect of Unreacted PbI2 on the Long‐Term Stability of Perovskite Solar Cells
Few‐layer GeAs field‐effect transistors and infrared photodetectors
Surface‐2D/bulk‐3D heterophased perovskite nanograins for long‐term‐stable light‐emitting diodes
Monolithic Organic/Colloidal Quantum Dot Hybrid Tandem Solar Cells via Buffer Engineering
Polarons and Charge Localization in Metal‐Halide Semiconductors for Photovoltaic and Light‐Emitting Devices
Efficient Electron Transport Layer Free Small‐Molecule Organic Solar Cells with Superior Device Stability
Controlling the growth kinetics and optoelectronic properties of 2D/3D lead–tin perovskite heterojunctions
Halide Remixing under Device Operation Imparts Stability on Mixed‐Cation Mixed‐Halide Perovskite Solar Cells
Extraordinary Mass Transport and Self‐Assembly: A Pathway to Fabricate Luminescent CsPbBr3 and Light‐Emitting Diodes by Vapor‐Phase Deposition
Direct visualization of the solid electrolyte interphase and its effects on silicon electrochemical performance
Multifunctional conjugated ligand engineering for stable and efficient perovskite solar cells
Quantifying Anionic Diffusion in 2D Halide Perovskite Lateral Heterostructures
Fabric‐based wearable self‐powered asymmetric supercapacitor comprising lead‐free perovskite piezoelectrodes
Simple Visualization of Universal Ferroelastic Domain Walls in Lead Halide Perovskites
Color‐selective printed organic photodiodes for filterless multichannel visible light communication
In‐Plane Anisotropic Thermal Conductivity of Few‐Layered Transition Metal Dichalcogenide Td‐WTe2
Visualizing the Anomalous Charge Density Wave States in Graphene/NbSe2 Heterostructures
White‐Light‐Driven Resonant Emission from a Monolayer Semiconductor
Nanostructured A2 (RE, B) O6 (A= Ba, Sr; RE= Rare-Earth; B= Sb, Zr) Perovskite Ceramics and their Potential Applications in Microwave and Superconducting Electronics
Quantifying Anionic Diffusion in Two‐Dimensional Halide Perovskites Lateral Heterostructures
High‐efficiency photovoltaic devices using trap‐controlled quantum‐dot ink prepared via phase‐transfer exchange
A Demulsification-Crystallization Model for High-Quality Perovskite Nanocrystals
Flexible, Printable Soft‐X‐Ray Detectors Based on All‐Inorganic Perovskite Quantum Dots
Shape‐Tuned Multiphoton‐Emitting InP Nanotetrapods
Ambient Air Stability of Hybrid Perovskite Thin‐Film Transistors by Ambient Air Processing
Stretchable, Breathable, and Stable Lead‐Free Perovskite/Polymer Nanofiber Composite for Hybrid Triboelectric and Piezoelectric Energy Harvesting
In situ grazing‐incidence wide‐angle scattering reveals mechanisms for phase distribution and disorientation in 2D halide perovskite films
Nonequilibrium Lattice Dynamics in Photoexcited 2D Perovskites
Enhanced electrocatalysts fabricated via quenched ultrafast sintering: physicochemical properties and water oxidation applications
Cesium Lead Bromide (CsPbBr3) Thin‐Film‐Based Solid‐State Neutron Detector Developed by a Solution‐Free Sublimation Process
3D Microstructured Inorganic Perovskite Materials for Thermal Neutron Detection
Neutron Detectors: Cesium Lead Bromide (CsPbBr3) Thin‐Film‐Based Solid‐State Neutron Detector Developed by a Solution‐Free Sublimation Process (Adv …
Chirality‐Dependent Circular Photogalvanic Effect in Enantiomorphic 2D Organic–Inorganic Hybrid Perovskites
Inorganic‐Cation Pseudohalide 2D Cs2Pb(SCN)2Br2 Perovskite Single Crystal
Surface Interactions of Oxygen Suffice to P‐Dope the Halide Perovskites
Ion Exchange Lithography: Localized Ion Exchange Reactions for Spatial Patterning of Perovskite Semiconductors and Insulators
Functionalized BODIPYs as Tailor‐Made and Universal Interlayers for Efficient and Stable Organic and Perovskite Solar Cells
Quantum Cutting down Conversion by Cooperative Energy Transfer from Tb3+ to Yb3+ in CeF3 Nanophosphors
Memory Seeds Enable High Structural Phase Purity in 2D Perovskite Films for High‐Efficiency Devices
Defect activity in lead halide perovskites
Hybrid perovskite nanoparticles for high‐performance resistive random access memory devices: control of operational parameters through chloride doping
Multidimensional Perovskites for High Detectivity Photodiodes
Effect of Cobalt Concentration on Bi0. 95Ba0. 05Fe1-xCoxO3
Increasing the Strength, Hardness, and Survivability of Semiconducting Polymers by Crosslinking
From Heterostructures to Solid‐Solutions: Structural Tunability in Mixed Halide Perovskites
Structured perovskite light absorbers for efficient and stable photovoltaics
Elucidating the Origins of High Preferential Crystal Orientation in Quasi‐2D Perovskite Solar Cells
What should we make with CO2 and how can we make it?
Sulfur-modulated tin sites enable highly selective electrochemical reduction of CO2 to formate
Continuous carbon dioxide electroreduction to concentrated multi-carbon products using a membrane electrode assembly
Quantum dots supply bulk-and surface-passivation agents for efficient and stable perovskite solar cells
Monolayer perovskite bridges enable strong quantum dot coupling for efficient solar cells
Quantum-dot-derived catalysts for CO2 reduction reaction
A multi-functional molecular modifier enabling efficient large-area perovskite light-emitting diodes
Cascade CO2 electroreduction enables efficient carbonate-free production of ethylene
Electrocatalytic rate alignment enhances syngas generation
Solvent-solute coordination engineering for efficient perovskite luminescent solar concentrators
Boosting the single-pass conversion for renewable chemical electrosynthesis
Electroosmotic flow steers neutral products and enables concentrated ethanol electroproduction from CO2
A microchanneled solid electrolyte for carbon-efficient CO2 electrolysis
Influence of charge transport layers on open-circuit voltage and hysteresis in perovskite solar cells
Measuring aging stability of perovskite solar cells
28.2%-efficient, outdoor-stable perovskite/silicon tandem solar cell
Stimuli-responsive switchable halide perovskites: Taking advantage of instability
Soft perovskites stabilized by robust heterojunctions
Molecular order control of non-fullerene acceptors for high-efficiency polymer solar cells
Tin perovskite solar cells with> 1,300 h of operational stability in N2 through a synergistic chemical engineering approach
Decarbonization of the chemical industry through electrification: Barriers and opportunities
An equivalent circuit for perovskite solar cell bridging sensitized to thin film architectures
How do perovskite solar cells work?
Origins and influences of metallic lead in perovskite solar cells
Enabling flexible all-perovskite tandem solar cells
Bimolecular additives improve wide-band-gap perovskites for efficient tandem solar cells with CIGS
Overcoming redox reactions at perovskite-nickel oxide interfaces to boost voltages in perovskite solar cells
Self-seeding growth for perovskite solar cells with enhanced stability
Efficient and stable graded CsPbI3− xBrx perovskite solar cells and submodules by orthogonal processable spray coating
3D/2D passivation as a secret to success for polycrystalline thin-film solar cells
Surface engineering with oxidized Ti3C2Tx MXene enables efficient and stable pin-structured CsPbI3 perovskite solar cells
Phase transition control for high-performance blade-coated perovskite solar cells
Multi-cation synergy suppresses phase segregation in mixed-halide perovskites
Scalable ambient fabrication of high-performance CsPbI2Br solar cells
Fine-tuning energy levels via asymmetric end groups enables polymer solar cells with efficiencies over 17%
16% efficiency all-polymer organic solar cells enabled by a finely tuned morphology via the design of ternary blend
Critical role of additive-induced molecular interaction on the operational stability of perovskite light-emitting diodes
Decoupling the effects of defects on efficiency and stability through phosphonates in stable halide perovskite solar cells
Accurate photovoltaic measurement of organic cells for indoor applications
A new acceptor for highly efficient organic solar cells
Interface-assisted cation exchange enables high-performance perovskiteLEDs with tunable near-infrared emissions
Methylammonium chloride induces intermediate phase stabilization for efficient perovskite solar cells
Reversible, full-color luminescence by post-treatment of perovskite nanocrystals
Photoprotection in metal halide perovskites by ionic defect formation
Black and stable: A path to all-inorganic halide perovskite solar cells
Metal halide perovskites in quantum dot solar cells: progress and prospects
Countdown to perovskite space launch: Guidelines to performing relevant radiation-hardness experiments
Highly efficient thermally co-evaporated perovskite solar cells and mini-modules
Metal halide perovskite polycrystalline films exhibiting properties of single crystals
Self-assembled triple-conducting nanocomposite as a superior protonic ceramic fuel cell cathode
Improving efficiency and stability of perovskite solar cells enabled by a near-infrared-absorbing moisture barrier
The role of halide oxidation in perovskite halide phase separation
The influence of strain on phase stability in mixed-halide perovskites
Phosphorene nanoribbons for next-generation energy devices
Probing semiconductor properties with optical scanning tunneling microscopy
Reverse manufacturing enables perovskite photovoltaics to reach the carbon footprint limit of a glass substrate
Rational design of halide double perovskites for optoelectronic applications
Accelerating photovoltaic market entry with module replacement
Economically sustainable growth of perovskite photovoltaics manufacturing
Assessing the regulatory requirements of lead-based perovskite photovoltaics
III-V-on-Si tandem solar cells
Unveiling the influence of pH on the crystallization of hybrid perovskites, delivering low voltage loss photovoltaics
Oxidative passivation of metal halide perovskites
Concurrent cationic and anionic perovskite defect passivation enables 27.4% perovskite/silicon tandems with suppression of halide segregation
Machine learning for perovskites' reap-rest-recovery cycle
Layer-by-layer degradation of methylammonium lead tri-iodide perovskite microplates
Surface engineering of ambient-air-processed cesium lead triiodide layers for efficient solar cells
Relaxation of externally strained halide perovskite thin layers with neutral ligands
Monolithic all-perovskite tandem solar cells with 24.8% efficiency exploiting comproportionation to suppress Sn(ii) oxidation in precursor ink
Suppression of atomic vacancies via incorporation of isovalent small ions to increase the stability of halide perovskite solar cells in ambient air
Multi-site electrocatalysts for hydrogen evolution in neutral media by destabilization of water molecules
All-perovskite tandem solar cells with 24.2% certified efficiency and area over 1 cm2 using surface-anchoring zwitterionic antioxidant
Colloidal quantum dot solids for solution-processed solar cells
Efficient electrically powered CO2-to-ethanol via suppression of deoxygenation
Efficient bifacial monolithic perovskite/silicon tandem solar cells via bandgap engineering
Ultrafast narrowband exciton routing within layered perovskite nanoplatelets enables low-loss luminescent solar concentrators
Designing anion exchange membranes for CO2 electrolysers
Gas diffusion electrodes, reactor designs and key metrics of low-temperature CO2 electrolysers
Electrochemical upgrade of CO2 from amine capture solution
Efficient electrosynthesis of n-propanol from carbon monoxide using a Ag–Ru–Cu catalyst
Large guanidinium cation mixed with methylammonium in lead iodide perovskites for 19% efficient solar cells
Intrinsic non-radiative voltage losses in fullerene-based organic solar cells
High-throughput analysis of the ideality factor to evaluate the outdoor performance of perovskite solar minimodules

A review of thin-film crystalline silicon for solar cell applications. Part 1: Native substrates
Silicon heterojunction solar cells with electron selective TiOx contact
A review of thin-film crystalline silicon for solar cell applications. Part 2: Foreign substrates
Flexible silicon solar cells
Light and elevated temperature induced degradation (LeTID) in perovskite solar cells and development of stable semi-transparent cells
Full day simulations of anti-reflection coatings for flat plate silicon photovoltaics
Modeling of static concentrator modules incorporating lambertian or v-groove rear reflectors
Damage-free ultraviolet nanosecond laser ablation for high efficiency back contact solar cell fabrication
Sliver cells in thermophotovoltaic systems
The influence of drift fields in thin silicon solar cells
Passivated contacts to laser doped p+ and n+ regions
Photon management of combining nanostructural antireflection and perovskite down-shifting composite films for improving the efficiency of silicon solar cells
Electrochemical design of ZnO hierarchical structures for dye-sensitized solar cells
Light management in highly-textured perovskite solar cells: From full-device ellipsometry characterization to optical modelling for quantum efficiency optimization
The effect of dislocations on the efficiency of InGaN/GaN solar cells
The effect of introducing a buffer layer to polymer solar cells on cell efficiency
Optical and surface probe investigation of secondary phases in Cu2ZnSnS4 films grown by electrochemical deposition
A simultaneous achievement of high performance and extended thermal stability of bulk-heterojunction polymer solar cells using a polythiophene–fullerene block copolymer
Pyrrolo [3, 2-b] pyrrole based small molecules as donor materials for OPVs
Syntheses and solar cell applications of conjugated copolymers consisting of 3, 3′-dicarboximide and benzodithiophene units with thiophene and bithiophene linkage
Large grain size with reduced non-radiative recombination in potassium incorporated methylammonium-free perovskite solar cells
Increasing the efficiency of fluorescent concentrator systems
Record efficient upconverter solar cell devices with optimized bifacial silicon solar cells and monocrystalline BaY 2 F 8: 30% Er 3+ upconverter
Absolute upconversion quantum yield of β-NaYF 4 doped with Er 3+ and external quantum efficiency of upconverter solar cell devices under broad-band excitation considering …
Experimental analysis of upconversion with both coherent monochromatic irradiation and broad spectrum illumination
Bifacial n-type silicon solar cells for upconversion applications
Light trapping, a new approach to spectrum splitting
Enhanced energy conversion of up-conversion solar cells by the integration of compound parabolic concentrating optics
The photonic light trap—Improved light trapping in solar cells by angularly selective filters
Efficiency increase of crystalline silicon solar cells with nanoimprinted rear side gratings for enhanced light trapping
Angular confinement and concentration in photovoltaic converters
Rear side sphere gratings for improved light trapping in crystalline silicon single junction and silicon-based tandem solar cells
Spectral splitting module geometry that utilizes light trapping
Comparative analysis of upconversion efficiencies in fluoride materials for photovoltaic application
Systematic analysis of diffuse rear reflectors for enhanced light trapping in silicon solar cells
Plated copper electrodes for two-terminal perovskite/silicon tandem solar cells
Slot-die coated methylammonium-free perovskite solar cells with 18% efficiency
Effect of humidity on structure and electrochromic properties of sol–gel-derived tungsten oxide films
Ligand-dependent transient absorption studies of hybrid polymer: CdSe quantum dot composites
Contactless determination of the efficiency of interfacial charge separation in a TiO2/phenylene vinylene polymer junction
Triplet exciton diffusion and delayed interfacial charge separation in a TiO2/PdTPPC bilayer: Monte Carlo simulations
Photo-induced charge separation and electron diffusion in MDMO–PPV: PCBM bulk heterojunctions
Nanoparticles as a high-temperature anticorrosion additive to molten nitrate salts for concentrated solar power
Infrared emissivity of copper-alloyed spinel black coatings for concentrated solar power systems
Modelling of hot carrier solar cell absorbers
Hot carrier solar cell absorber prerequisites and candidate material systems
Phonon lifetimes in model quantum dot superlattice systems with applications to the hot carrier solar cell
Hot carrier dynamics in HfN and ZrN measured by transient absorption spectroscopy
Effects of ITO precursor thickness on transparent conductive Al doped ZnO film for solar cell applications
Recent progress on cesium lead/tin halide-based inorganic perovskites for stable and efficient solar cells: A review
Al2O3 antireflection layer between glass and transparent conducting oxide for enhanced light trapping in microcrystalline silicon thin film solar cells
Effect of textured glass substrates coated with LPCVD-deposited SnO2: F on amorphous silicon solar cells
Highly conductive GaN anti-reflection layer at transparent conducting oxide/Si interface for silicon thin film solar cells
Light management of a-SiOx: H thin film solar cells with hydrogen-reduced p+ buffer at TiO2/p-layer interface
Free-standing, colored, polymer film with composite opal photonic crystal structure for efficient passive daytime radiative cooling
Radiation stability of mixed tin–lead halide perovskites: Implications for space applications
Reduction of moisture sensitivity of PbS quantum dot solar cells by incorporation of reduced graphene oxide
Thermochromic VO2− SiO2 nanocomposite smart window coatings with narrow phase transition hysteresis and transition gradient width
An extensible and tunable full-opaque cascade smart electrochromic device
Improving the efficiency of Sb2Se3 thin-film solar cells by post annealing treatment in vacuum condition
Investigation of electronic transport mechanisms in Sb2Se3 thin-film solar cells
Investigation of electrically-active defects in Sb2Se3 thin-film solar cells with up to 5.91% efficiency via admittance spectroscopy
Electroluminescence imaging of laser induced defect formation in Cu (In, Ga) Se2 solar cell
Accessing externally induced spatially-resolved strain in GaAs thin-film solar cells by electroluminescence imaging
Increased homogeneity and open-circuit voltage of Cu (In, Ga) Se2 solar cells due to higher deposition temperature
Analysis of Cu(In,Ga)(S,Se)2 thin-film solar cells by means of electron microscopy
Tapered aluminum-doped vertical zinc oxide nanorod arrays as light coupling layer for solar energy applications
Electronic properties of grain boundaries in Cu (In, Ga) Se2 thin films with various Ga-contents
Spray pyrolysis of barrier layers for flexible thin film solar cells on steel
Examination of growth kinetics of copper rich Cu (In, Ga) Se2-films using synchrotron energy dispersive X-ray diffractometry
Buffer-free Cu (In, Ga) Se2-solar cells by near-surface ion implantation
Efficiency and stability enhancement of laser-crystallized polycrystalline silicon thin-film solar cells by laser firing of the absorber contacts
Rear-side All-by-Laser Point-contact Scheme for liquid-phase-crystallized silicon on glass solar cells
Laser-induced local phase transformation of CIGSe for monolithic serial interconnection: Analysis of the material properties
Spray coated high-conductivity PEDOT: PSS transparent electrodes for stretchable and mechanically-robust organic solar cells
Electrical properties of patterned photoactive layers in organic photovoltaic modules
Study of ethoxyethane deposition time and Co (III) complex doping on the performance of mesoscopic perovskite based solar cells
Role of cation-mediated recombination in perovskite solar cells
Enhancement of photovoltaic performance of perovskite solar cells by modification of the interface between the perovskite and mesoporous TiO2 film
Improvement of photovoltaic performance of perovskite solar cells with a ZnO/Zn2SnO4 composite compact layer
Amorphous nanoporous WOx modification for stability enhancement and hysteresis reduction in TiO2-based perovskite solar cells
Impedance spectroscopy analysis of small molecule solution processed organic solar cell
Evolution with annealing of solar cell parameters modeling the S-shape of the current–voltage characteristic
Corrosion of novel reactive silver ink and commercial silver-based metallizations in diluted acetic acid
Achieving high open circuit voltage for hole transport layer free ambient perovskite solar cells utilizing electric double layer effect
Anti-solvent treatment time approach to high efficiency perovskite solar cells with temperature of coating environmental
Corrosion of alloys in a chloride molten salt (NaCl-LiCl) for solar thermal technologies
Corrosion resistance of alumina-forming alloys against molten chlorides for energy production. I: Pre-oxidation treatment and isothermal corrosion tests
Corrosion resistance of alumina forming alloys against molten chlorides for energy production. II: Electrochemical impedance spectroscopy under thermal cycling conditions
> 85% indium reduction for high-efficiency silicon heterojunction solar cells with aluminum-doped zinc oxide contacts
The role of metastability and concentration on the performance of CIGS solar cells under Low-Intensity-Low-Temperature conditions
Radiation tolerance of GaAs1-xSbx solar cells
Band-edges of bismuth-based ternary halide perovskites (A3Bi2I9) through scanning tunneling spectroscopy vis-à-vis impact of defects in limiting the performance of solar cells
Development of an organic photovoltaic energy harvesting system for wireless sensor networks; application to autonomous building information management systems and optimisation …
FAPbBr3 perovskite quantum dots as a multifunctional luminescent-downshifting passivation layer for GaAs solar cells
Velocity valleys enable efficient capture and spatial sorting of nanoparticle-bound cancer cells
Self-assembled nanoparticle-stabilized photocatalytic reactors
Ligand cleavage enables formation of 1, 2-ethanedithiol capped colloidal quantum dot solids
Modulating the luminance of organic light-emitting diodes via optical stimulation of a photochromic molecular monolayer at transparent oxide electrode
Morphology-controlled MoS 2 by low-temperature atomic layer deposition
Resonant Raman scattering from silicon nanoparticles enhanced by magnetic response
Laser fabrication of crystalline silicon nanoresonators from an amorphous film for low-loss all-dielectric nanophotonics
Laser printing of resonant plasmonic nanovoids
Resonant silicon nanoparticles for enhancement of light absorption and photoluminescence from hybrid perovskite films and metasurfaces
Self-adjusted all-dielectric metasurfaces for deep ultraviolet femtosecond pulse generation
Purcell effect in active diamond nanoantennas
Beyond quantum confinement: excitonic nonlocality in halide perovskite nanoparticles with Mie resonances
Plasmonic nanosponges filled with silicon for enhanced white light emission
Resonant silicon nanoparticles with controllable crystalline states and nonlinear optical responses
Si 1− x Ge x nanoantennas with a tailored raman response and light-to-heat conversion for advanced sensing applications
Optical cooling of lead halide perovskite nanoparticles enhanced by Mie resonances
A general mechanism for intracellular toxicity of metal-containing nanoparticles
Coexistence of plasmonic and magnetic properties in Au 89 Fe 11 nanoalloys
Atomically monodisperse nickel nanoclusters as highly active electrocatalysts for water oxidation
Direct versus ligand-exchange synthesis of [PtAg 28 (BDT) 12 (TPP) 4] 4− nanoclusters: effect of a single-atom dopant on the optoelectronic and chemical properties
Ultrafast static and diffusion-controlled electron transfer at Ag 29 nanocluster/molecular acceptor interfaces
Gram-scale fractionation of nanodiamonds by density gradient ultracentrifugation
Size-controlled fluorescent nanodiamonds: a facile method of fabrication and color-center counting
Investigation of high contrast and reversible luminescence thermochromism of the quantum confined Cs 4 PbBr 6 perovskite solid
Phosphatidylcholine-mediated regulation of growth kinetics for colloidal synthesis of cesium tin halide nanocrystals
Investigation of high contrast and reversible luminescence thermochromism of the quantum confined Cs4PbBr6 perovskite solid (vol 11, pg 5754, 2019)
www. rsc. org/nanoscale
Large area nanopatterning of alkylphosphonate self-assembled monolayers on titanium oxide surfaces by interferometric lithography
Enhancing the photocatalytic properties of PbS QD solids: the ligand exchange approach
Ultrathin Cu 2 O as an efficient inorganic hole transporting material for perovskite solar cells
Oxide nanowires for spintronics: materials and devices
Ultra-sensitive and wide-dynamic-range sensors based on dense arrays of carbon nanotube tips
Nanoscale semiconductor–insulator–metal core/shell heterostructures: facile synthesis and light emission
Anisotropic surface strain in single crystalline cobalt nanowires and its impact on the diameter-dependent Young's modulus
Resistive graphene humidity sensors with rapid and direct electrical readout
Bilayer insulator tunnel barriers for graphene-based vertical hot-electron transistors
Flexible hybrid graphene/a-Si: H multispectral photodetectors
Self-organized growth of graphene nanomesh with increased gas sensitivity
Lead-free double perovskites Cs 2 InCuCl 6 and (CH 3 NH 3) 2 InCuCl 6: electronic, optical, and electrical properties
High reduction of interfacial charge recombination in colloidal quantum dot solar cells by metal oxide surface passivation
All solution processed low turn-on voltage near infrared LEDs based on core–shell PbS–CdS quantum dots with inverted device structure
Ligand &band gap engineering: Tailoring the protocol synthesis for achieving high-quality CsPbI 3 quantum dots
Recombination reduction on lead halide perovskite solar cells based on low temperature synthesized hierarchical TiO 2 nanorods
White light emission from lead-free mixed-cation doped Cs 2 SnCl 6 nanocrystals
Carbon nanotubes as an efficient hole collector for high voltage methylammonium lead bromide perovskite solar cells
Cation exchange synthesis of uniform PbSe/PbS core/shell tetra-pods and their use as near-infrared photodetectors
Hot electron–hole plasma dynamics and amplified spontaneous emission in ZnTe nanowires
Low-dimensional phase suppression and defect passivation of quasi-2D perovskites for efficient electroluminescence and low-threshold amplified spontaneous emission
Double-layered ZnO nanostructures for efficient perovskite solar cells
Core–shell heterostructured metal oxide arrays enable superior light-harvesting and hysteresis-free mesoscopic perovskite solar cells
Integration of CuInS2-based nanocrystals for high efficiency and high colour rendering white light-emitting diodes
Poly (vinylpyrrolidone) supported copper nanoclusters: glutathione enhanced blue photoluminescence for application in phosphor converted light emitting devices
A detour strategy for colloidally stable block-copolymer grafted MAPbBr 3 quantum dots in water with long photoluminescence lifetime
Highly luminescent red emissive perovskite quantum dots-embedded composite films: ligands capping and caesium doping-controlled crystallization process
Growth of CdS nanotubes and their strong optical microcavity effects
Micropore filling fabrication of high resolution patterned PQDs with a pixel size less than 5 μm
PdO/PdO 2 functionalized ZnO: Pd films for lower operating temperature H 2 gas sensing
Blue perovskite light-emitting diodes: progress, challenges and future directions
Impacts of core–shell structures on properties of lanthanide-based nanocrystals: crystal phase, lattice strain, downconversion, upconversion and energy transfer
Energy transfer study between Ce3+ and Tb3+ ions in doped and core-shell sodium yttrium fluoride nanocrystals
An overview on the current understanding of the photophysical properties of metal nanoclusters and their potential applications
An efficient charge separation and photocurrent generation in the carbon dot–zinc oxide nanoparticle composite
A study into the role of surface capping on energy transfer in metal cluster–semiconductor nanocomposites
Functionalized dye encapsulated polymer nanoparticles attached with a BSA scaffold as efficient antenna materials for artificial light harvesting
Correction: An efficient charge separation and photocurrent generation in the carbon dot–zinc oxide nanoparticle composite
Mixed solvents for the optimization of morphology in solution-processed, inverted-type perovskite/fullerene hybrid solar cells
Recent progress in indoor organic photovoltaics
Fabrication of gold dot, ring, and corpuscle arrays from block copolymer templates via a simple modification of surface energy
Size tailoring of aqueous germanium nanoparticle dispersions
Origin of the luminescence spectra width in perovskite nanocrystals with surface passivation
Radio-frequency-transmitting hexagonal boron nitride-based anti-and de-icing heating system
Ultralow surface energy self-assembled monolayers of iodo-perfluorinated alkanes on silica driven by halogen bonding
Carrier photogeneration, drift and recombination in a semiconducting carbon nanotube network
Charge transfer in crystalline germanium/monolayer MoS 2 heterostructures prepared by chemical vapor deposition
A gate-tunable single-molecule diode
Controlling the morphology, composition and crystal structure in gold-seeded GaAs 1− x Sb x nanowires
Ultrathin Ta 2 O 5 electron-selective contacts for high efficiency InP solar cells
Spinel Co 3 O 4 nanomaterials for efficient and stable large area carbon-based printed perovskite solar cells
Self-assembly of a robust hydrogen-bonded octylphosphonate network on cesium lead bromide perovskite nanocrystals for light-emitting diodes
Charge separation in Pt-decorated CdSe@ CdS octapod nanocrystals
Strong dichroic emission in the pseudo one dimensional material ZrS 3
Engineering excitonic dynamics and environmental stability of post-transition metal chalcogenides by pyridine functionalization technique
Interface-dependent phononic and optical properties of GeO/MoSO heterostructures
Amplified spontaneous emission in thin films of quasi-2D BA 3 MA 3 Pb 5 Br 16 lead halide perovskites
Precision printing and optical modeling of ultrathin SWCNT/C 60 heterojunction solar cells
Effect of nanotube coupling on exciton transport in polymer-free monochiral semiconducting carbon nanotube networks
Extracellular electron transfer across bio-nano interfaces for CO 2 electroreduction
Disentangling oxygen and water vapor effects on optoelectronic properties of monolayer tungsten disulfide
On the optical anisotropy in 2D metal-halide perovskites
Suppression of exciton dephasing in sidewall-functionalized carbon nanotubes embedded into metallo-dielectric antennas
Interplay between microstructure, defect states, and mobile charge generation in transition metal dichalcogenide heterojunctions
Colloidal BiF 3 nanocrystals: a bottom-up approach to conversion-type Li-ion cathodes
Solvent dipole modulation of conduction band edge shift and charge recombination in robust dye-sensitized solar cells
Free charges versus excitons: photoluminescence investigation of InGaN/GaN multiple quantum well nanorods and their planar counterparts
Difference in hot carrier cooling rate between Langmuir–Blodgett and drop cast PbS QD films due to strong electron–phonon coupling
Water-resistant PEDOT: PSS hole transport layers by incorporating a photo-crosslinking agent for high-performance perovskite and polymer solar cells

Piezo-phototronic effect in highly stable CsPbI3-PVDF composite for self-powered nanogenerator and photodetector
Improved energy harvesting ability of C3H7NH3PbI3 decorated PVDF nanofiber based flexible nanogenerator
Highly efficient, stable and hysteresis‒less planar perovskite solar cell based on chemical bath treated Zn2SnO4 electron transport layer
Pre-and post-treatments free nanocomposite based hole transport layer for high performance organic solar cells with considerably enhanced reproducibility
Fabrication of piezoresistive Si nanorod-based pressure sensor arrays: A promising candidate for portable breath monitoring devices
High-performance all-polymer solar cells based on fluorinated naphthalene diimide acceptor polymers with fine-tuned crystallinity and enhanced dielectric constants
Hammer throw-liked hybrid cyclic and alkyl chains: A new side chain engineering for over 18% efficiency organic solar cells
An inverted BiI3/PCBM binary quasi-bulk heterojunction solar cell with a power conversion efficiency of 1.50%
Self-reconstructed interlayer derived by in-situ Mn diffusion from La0. 5Sr0. 5MnO3 via atomic layer deposition for an efficient bi-functional electrocatalyst
Edge-selective decoration with ruthenium at graphitic nanoplatelets for efficient hydrogen production at universal pH
Indirect surpassing CO2 utilization in membrane-free CO2 battery
Highly efficient air-stable colloidal quantum dot solar cells by improved surface trap passivation
Solution-processed colloidal quantum dot/organic hybrid tandem photovoltaic devices with 8.3% efficiency
Enhancing the stability of organic photovoltaics through machine learning
The selection strategy of ammonium-group organic salts in vapor deposited perovskites: From dimension regulation to passivation
Piezo-phototronic effect in highly stable lead-free double perovskite Cs2SnI6-PVDF nanocomposite: Possibility for strain modulated optical sensor
A carbon-doped tantalum dioxyfluoride as a superior electron transport material for high performance organic optoelectronics
Chalcogenide perovskite BaZrS3 thin-film electronic and optoelectronic devices by low temperature processing
Critical review of machine learning applications in perovskite solar research
Characterization of internal order of colloidal crystals by optical diffraction
The photonic analogue of the graded heterostructure: analysis using the envelope approximation
Optical and electrical properties of biocompatible and novel (CS–GO) polymer nanocomposites
Electrical scanning probe microscopy: Investigating the inner workings of electronic and optoelectronic devices
Performance degradation and mitigation strategies of silver nanowire networks: a review
Interfacial engineering revolutionizers: perovskite nanocrystals and quantum dots accentuated performance enhancement in perovskite solar cells
Two-dimensional profiling of carriers in a buried heterostructure multi-quantum-well laser: Calibrated scanning spreading resistance microscopy and scanning capacitance microscopy
Two-dimensional transverse cross-section nanopotentiometry of actively driven buried-heterostructure multiple-quantum-well lasers
Focused-ion beam patterning of organolead trihalide perovskite for subwavelength grating nanophotonic applications
Large scale ultraviolet-based nanoimprint lithography
Precision material modification and patterning with He ions
Gd silicate: A high- dielectric compatible with high temperature annealing
Leakage current effects on  plots of high- metal-oxide-semiconductor capacitors
Nanowire fin field effect transistors via UV-based nanoimprint lithography
Complementary metal oxide semiconductor integration of epitaxial
Fabrication of 12 nm electrically variable shallow junction metal–oxide–semiconductor field effect transistors on silicon on insulator substrates
Megasonic-assisted development of nanostructures
Scalable gate first process for silicon on insulator metal oxide semiconductor field effect transistors with epitaxial high- dielectrics
Impact of supercritical  drying on roughness of hydrogen silsesquioxane e-beam resist
Papers from the 50th International Conference on Electron, Ion, and Photon Beam Technology and Nanofabrication-Nanoimprint Lithography-Nanowire fin field effect transistors via …
Papers from the 47th International Conference on Electron, Ion, and Photon Beam Technology and Nanofabrication-Nanoimprint Lithography-Large scale ultraviolet-based nanoimprint …
Papers from the 47th International Conference on Electron, Ion, and Photon Beam Technology and Nanofabrication-Nano-and Microfabrication-Fabrication of 12 nm electrically …
Investigation of low temperature SiO2 plasma enhanced chemical vapor deposition
Ammonia plasma passivation of GaAs in downstream microwave and radio‐frequency parallel plate plasma reactors
Hydrogen etching and cutting of multiwall carbon nanotubes
Formation and removal of composite halogenated silicon oxide and fluorocarbon films deposited on chamber walls during plasma etching of multiple film stacks
Real time in situ monitoring of surfaces during glow discharge processing: NH3 and H2 plasma passivation of GaAs
Hydrogen in  bond center and platelet-like defect configurations in amorphous hydrogenated silicon
Molecular dynamics study of the interactions of small thermal and energetic silicon clusters with crystalline and amorphous silicon surfaces
Planar metal–insulator–metal diodes based on the Nb/Nb2O5/X material system
Modulation-doped ZnSe/(Zn, Cd, Mn) Se quantum wells and superlattices
Growth and characterization of MnAs/ZnSe ferromagnet/semiconductor hybrid heterostructures
Papers from the 19th North American Conference on Molecular Beam Epitaxy-Novel Materials-Growth and characterization of MnAs/ZnSe ferromagnet/semiconductor hybrid heterostructures
Papers from the 18th North American Conference on Molecular Beam Epitaxy-Novel Materials I-Modulation-doped ZnSe/(Zn, Cd, Mn) Se quantum wells and superlattices
Wavelength dependence of the magneto‐optical properties of the interfaces of a Au sandwiched (001) Fe film
Synthesis, characterization, and investigation of a conformationally immobile calix [6] arene as a negative electron beam resist
Thin films of carbon nanotubes via ultrasonic spraying of suspensions in N-methyl-2-pyrrolidone and N-cyclohexyl-2-pyrrolidone
Optical studies of molecular beam epitaxy grown  single quantum well structures
Sol-gel synthesized indium tin oxide as a transparent conducting oxide with solution-processed black phosphorus for its integration into solar-cells
Spectroscopic ellipsometry study of FAxMA1−xPbI3 hybrid perovskite single crystals
Spongy TiO2 layers deposited by gig-lox sputtering processes: Contact angle measurements
Separating resource reservations from service requests to improve the performance of optical burst-switching networks
Third-order optical nonlinearity and figure of merit of CdS nanocrystals chemically stabilized in spin-processable polymeric films
Impedance spectroscopy studies of orthorhombic FeNbO4
Structural and electrical conductivity studies on rutile solid solutions [FexTi1-2xMxO2 (M= Nb, Ta)]
Hole transporting materials for perovskite solar cells: molecular versus polymeric carbazole-based derivatives
The effect of processing conditions on the morphology, thermomechanical, dielectric, and piezoelectric properties of P(VDF-TrFE)/BaTiO3 composites
Effect of silane coupling agent on the morphology, structure, and properties of poly(vinylidene fluoride–trifluoroethylene)/BaTiO3 composites
Textured BaTiO3 by templated grain growth and electrophoretic deposition
Balancing hyperbole and impact in research communications related to lead-free piezoelectric materials
Preparation and characterization of ammonium-functionalized polysulfone/Al2O3 composite membranes
Electrode characteristics of Li2Ti3O7-ramsdellite processed by mechanical grinding
Synthesis, growth and structural perfection of nonlinear optical material of glycine hydrofluoride (GHF)
Rh/CeO2 catalyst preparation and characterization for hydrogen production from ethanol partial oxidation
Abrupt change from moderate positive to colossal negative thermal expansion caused by imidazolate composite formation
Spectroscopic studies, molecular structure optimization and investigation of structural and electrical properties of novel and biodegradable Chitosan-GO polymer nanocomposites
Annealing temperature effects on BiFeO3 nanoparticles towards photodegradation of Eosin B dye
Grain boundary phase transformations in PtAu and relevance to thermal stabilization of bulk nanocrystalline metals
Theoretical study of the strain influence on lead-free bismuth-based halide perovskites
Surface-enhanced Raman scattering on sandwiched structures with gallium telluride
Light-induced enhancement of memory effect in self-assembled pyrene nanostructures
Strain engineering of piezoelectric properties of strontium titanate thin films
Silk fibroin protein as dual mode picric acid sensor and UV photoactive material
Towards high-performance hybrid hydrophilic membranes: chemical anchoring of hydroxyl-rich nanoparticles on PVDF membranes via a silane coupling agent
Solution‐Processed In2O3/ZnO Heterojunction Electron Transport Layers for Efficient Organic Bulk Heterojunction and Inorganic Colloidal Quantum‐Dot Solar Cells
Alkali Salts as Interface Modifiers in n‐i‐p Hybrid Perovskite Solar Cells
Illumination‐Driven Energy Level Realignment at Buried Interfaces between Organic Charge Transport Layers and a Lead Halide Perovskite
Efficiency Potential and Voltage Loss of Inorganic CsPbI2Br Perovskite Solar Cells
25.1% high‐efficiency monolithic perovskite silicon tandem solar cell with a high bandgap perovskite absorber
27.9% efficient monolithic perovskite/silicon tandem solar cells on industry compatible bottom cells
Decoding charge recombination through charge generation in organic solar cells
Putting order into PM6: Y6 solar cells to reduce the Langevin recombination in 400 nm thick junction
Pathways toward 30% efficient single‐junction perovskite solar cells and the role of mobile ions
Quantifying Quasi‐Fermi Level Splitting and Open‐Circuit Voltage Losses in Highly Efficient Nonfullerene Organic Solar Cells
Quantification of efficiency losses due to mobile ions in perovskite solar cells via fast hysteresis measurements
Managing Phase Purities and Crystal Orientation for High‐Performance and Photostable Cesium Lead Halide Perovskite Solar Cells
Correlating Three‐dimensional Morphology With Function in PBDB‐T: IT‐M Non‐Fullerene Organic Solar Cells
Low‐Temperature, Scalable, Reactive Deposition of Tin Oxide for Perovskite Solar Cells
Plasmonic‐enhanced light harvesting and perovskite solar cell performance using Au biometric dimers with broadband structural darkness
Optimization of the Selenization Pressure Enabling Efficient Cu2ZnSn(S,Se)4 Solar Cells
Analysis of the UV–Ozone‐Treated SnO2 Electron Transporting Layer in Planar Perovskite Solar Cells for High Performance and Reduced Hysteresis
A perspective on the commercial viability of perovskite solar cells
Switchable All Inorganic Halide Perovskite Nanocrystalline Photoelectrodes for Solar‐Driven Organic Transformations
Application of Halide Perovskite Nanocrystals in Solar‐Driven Photo (electro) Catalysis
Photonic Processing of MAPbI3 Films by Flash Annealing and Rapid Growth for High‐Performance Perovskite Solar Cells
One‐step inkjet printed perovskite in air for efficient light harvesting
All Green Solvents for Fabrication of CsPbBr3 Films for Efficient Solar Cells Guided by the Hansen Solubility Theory
One‐Step Inkjet Printed Perovskite in Air for Efficient Light Harvesting (Solar RRL 2∕ 2018)
Efficient and Stable Perovskite Solar Cells by Fluorinated Ionic Liquid–Induced Component Interaction
[(C8H17)4N]4[SiW12O40] (TASiW‐12)‐Modified SnO2 Electron Transport Layer for Efficient and Stable Perovskite Solar Cells
Suppressed Phase Segregation in High‐Humidity‐Processed Dion–Jacobson Perovskite Solar Cells Toward High Efficiency and Stability
Blade Coating High‐Quality Formamidinium–Cesium Lead Halide Perovskites with Green Solvent for Efficient and Stable Solar Cells
Interfacial Engineering for High‐Performance PTAA‐Based Inverted 3D Perovskite Solar Cells
Enhancing charge transport of 2D perovskite passivation agent for wide‐bandgap perovskite solar cells beyond 21%
Designing modules to prevent reverse bias degradation in perovskite solar cells when partial shading occurs
Bismuth‐Based Perovskite‐Inspired Solar Cells: In Situ Diagnostics Reveal Similarities and Differences in the Film Formation of Bismuth‐and Lead‐Based Films
Novel Bimodal Silver Nanowire Network as Top Electrodes for Reproducible and High‐Efficiency Semitransparent Organic Photovoltaics
Efficient Hybrid Mixed‐Ion Perovskite Photovoltaics: In Situ Diagnostics of the Roles of Cesium and Potassium Alkali Cation Addition
Wide and Tunable Bandgap MAPbBr3−xClx Hybrid Perovskites with Enhanced Phase Stability: In Situ Investigation and Photovoltaic Devices
Sequential formation of tunable‐bandgap mixed‐Halide lead‐based perovskites: In situ investigation and photovoltaic devices
Observation of Long‐Term Stable Response in MAPbBr3 Single Crystals Monitored through Displacement Currents under Varying Illumination
A Step‐by‐Step Optimization of the c‐Si Bottom Cell in Monolithic Perovskite/c‐Si Tandem Devices
30% enhancement of efficiency in layered 2D perovskites absorbers by employing homo‐tandem structures
Above 23% efficiency by binary surface passivation of perovskite solar cells using guanidinium and octylammonium spacer cations
Anion Exchange‐Induced Crystal Engineering via Hot‐Pressing Sublimation Affording Highly Efficient and Stable Perovskite Solar Cells
Contactless and Spatially Resolved Determination of Current− Voltage Curves in Perovskite Solar Cells via Photoluminescence
Unraveling the role of energy band alignment and mobile ions on interfacial recombination in perovskite solar cells
Impact of Halide Anions in CsX (X = I, Br, Cl) on the Microstructure and Photovoltaic Performance of FAPbI3‐Based Perovskite Solar Cells
The stabilization of formamidinium lead tri‐iodide perovskite through a methylammonium‐based additive for high‐efficiency solar cells
A coadditive strategy for blocking ionic mobility in methylammonium‐free perovskite solar cells and high‐stability achievement
Lead‐Less Halide Perovskite Solar Cells
Surface chlorination of ZnO for perovskite solar cells with enhanced efficiency and stability
Two compatible polymer donors enabling ternary organic solar cells with a small nonradiative energy loss and broad composition tolerance
Optimizing the charge carrier and light management of nonfullerene acceptors for efficient organic solar cells with small nonradiative energy losses
Enhancing the Photovoltaic Performance of Triplet Acceptors Enabled by Side‐Chain Engineering
Thermally Activated Reverse Electron Transfer Limits Carrier Generation Efficiency in PM6: Y6 Non‐Fullerene Organic Solar Cells
Blueshifting the Absorption of a Small‐Molecule Donor and Using it as the Third Component to Achieve High‐Efficiency Ternary Organic Solar Cells
Diluted Organic Semiconductors in Photovoltaics
On the Device Physics of High‐Efficiency Ternary Solar Cells
Natural Product Betulin‐Based Insulating Polymer Filler in Organic Solar Cells
Dichroic Sb2O3/Ag/Sb2O3 Electrodes for Colorful Semitransparent Organic Solar Cells
Influence of the crystalline nature of small donors molecules on the efficiency and stability of organic photovoltaic devices
Exploiting Ternary Blends to Accurately Control the Coloration of Semitransparent, Non‐Fullerene, Organic Solar Cells
Planar Organic Bilayer Heterojunctions Fabricated on Water with Ultrafast Donor‐to‐Acceptor Charge Transfer
Robust inorganic hole transport materials for organic and perovskite solar cells: insights into materials electronic properties and device performance
Perovskite Single‐Crystal Solar Cells: Advances and Challenges
Charge Photogeneration and Transport in AgBiS2 Nanocrystal Films for Photovoltaics
Perovskite Solar Cells: Stable under Space Conditions
25.1% High‐Efficiency Monolithic Perovskite Silicon Tandem Solar Cell with a High Bandgap Perovskite Absorber
High‐Efficiency Monolithic Photosupercapacitors: Smart Integration of a Perovskite Solar Cell with a Mesoporous Carbon Double‐Layer Capacitor
Electroplated Copper Metal Contacts on Perovskite Solar Cells
Low‐Temperature Atomic Layer Deposited Electron Transport Layers for Co‐Evaporated Perovskite Solar Cells
Advances and Potentials of NiO x  Surface Treatments for p−i−n Perovskite Solar Cells
Perovskite Solar Modules
Postripening Fabrication and Self‐Driven Narrowband Photoresponse of Large‐Grain, Phase‐Pure CsPbBr3 Films
Rational Design of LaNiO3/Carbon Composites as Outstanding Platinum‐Free Photocathodes in Dye‐Sensitized Solar Cells With Enhanced Catalysis for the …
Improving Moisture/Thermal Stability and Efficiency of CH3NH3PbI3‐Based Perovskite Solar Cells via Gentle Butyl Acrylate Additive Strategy
An Intrinsically Conductive Phosphorus‐Doped Perovskite Oxide as a New Cathode for High‐Performance Dye‐Sensitized Solar Cells by Providing Internal Conducting Pathways
PbSe quantum dot passivated via mixed halide perovskite nanocrystals for solar cells with over 9% efficiency
Understanding the Interplay of Transport‐Morphology‐Performance in PBDB‐T‐Based Polymer Solar Cells
Structure, Morphology, and Photovoltaic Implications of Halide Alloying in Lead‐Free Cs3Sb2ClxI9–x 2D‐Layered Perovskites
Highly Efficient and Industrially Feasible Interdigitated Back‐Contact Perovskite Solar Cells with Front Carrier Transport Layers Selected Using 2D Simulation
Metal Chalcohalides: Next Generation Photovoltaic Materials?
Insight into the Role of Guanidinium and Cesium in Triple Cation Lead Halide Perovskites
Double‐side‐passivated perovskite solar cells with ultra‐low potential loss
Silicon Heterojunction Solar Cells and p‐type Crystalline Silicon Wafers: A Historical Perspective
A Hybrid Perovskite Solar Cell Modified with Copper Indium Sulfide Nanocrystals to Enhance Hole Transport and Moisture Stability
Discovery of a New Intermediate Enables One‐Step Deposition of High‐Quality Perovskite Films via Solvent Engineering
Improvement in the performance of inverted 3D/2D perovskite solar cells by ambient exposure
Customizing a Coordinative Crab Molecule BCP‐3N with Multifunctionality for High‐Performance Inverted Perovskite Solar Cells
N‐Heteroacenes as a New Class of Non‐Fullerene Electron Acceptors for Organic Bulk‐Heterojunction Photovoltaic Devices
Facile physical modifications of polymer hole transporting layers for efficient and reproducible perovskite solar cells with fill factor exceeding 80%
Nontoxic and Less Toxic Hybrid Perovskites: a Synergistic Strategy for Sustainable Photovoltaic Devices
Perovskite Photovoltaic Devices with Carbon‐Based Electrodes Withstanding Reverse‐Bias Voltages up to–9 V and Surpassing IEC 61215: 2016 International Standard
A 2D Model for Interfacial Recombination in Mesoscopic Perovskite Solar Cells with Printed Back Contact
Fill Factor Assessment in Hole Selective Layer Free Carbon Electrode‐Based Perovskite Solar Cells with 15.5% Certified Power Conversion Efficiency
Intrinsic Organic Semiconductors as Hole Transport Layers in p–i–n Perovskite Solar Cells
Functionality of non‐fullerene electron acceptors in ternary organic solar cells
Pathways toward 30% Efficient Single‐Junction Perovskite Solar Cells and the Role of Mobile Ions
Predicting Low Toxicity and Scalable Solvent Systems for High‐Speed Roll‐to‐Roll Perovskite Manufacturing
A Theoretical Perspective on the Thermodynamic Stability of Polymer Blends for Solar Cells: From Experiments to Predictive Modeling
Unraveling the Key Relationship Between Perovskite Capacitive Memory, Long Timescale Cooperative Relaxation Phenomena, and Anomalous J–V Hysteresis

Sub-100 nanometer transverse gratings written by femtosecond laser pulses on a titanium surface
Nanoscale surface boiling in sub-threshold damage and above-threshold spallation of bulk aluminum and gold by single femtosecond laser pulses
Enhanced relativistic laser–plasma coupling utilizing laser-induced micromodified target
Nonlinear optical dynamics during femtosecond laser nanostructuring of a silicon surface
Femtosecond laser modification of titanium surfaces: direct imprinting of hydroxylapatite nanopowder and wettability tuning via surface microstructuring
Pulse-width-dependent surface ablation of copper and silver by ultrashort laser pulses
Superhydrophylic textures fabricated by femtosecond laser pulses on sub-micro-and nano-crystalline titanium surfaces
Ultrafast femtosecond laser ablation of graphite
Imaging of QDs-labeled tumors in small animals by fluorescence diffuse tomography
Selfaction effects of femtosecond laser pulses in dye-doped 5CB liquid crystal
Sign inversion of the optical torque on the nematic director enhanced by anthraquinone dye dopants stable to the light action
Dewetting mechanisms and their exploitation for the large-scale fabrication of advanced nanophotonic systems
All-dielectric thermonanophotonics
All-dielectric thermonanophotonics (vol 13, pg 643, 2021)
All-dielectric thermonanophotonics: publisher’s note
Silicon as a virtual plasmonic material: Acquisition of its transient optical constants and the ultrafast surface plasmon-polariton excitation
Formation of nanobumps and nanoholes in thin metal films by strongly focused nanosecond laser pulses
Reflection of a probe pulse and thermal emission of electrons produced by an aluminum film heated by a femtosecond laser pulse
Fabrication of superhydrophobic coating on stainless steel surface by femtosecond laser texturing and chemisorption of an hydrophobic agent
Hole mobility and trapping in PVK films doped with CdSe/CdS and CdSe quantum dots
Optical properties of 3D photonic crystals filled with CdSe/CdS quantum dots
Atomistic simulation of Si-Au melt crystallization with novel interatomic potential
Optimized interatomic potential for study of structure and phase transitions in Si-Au and Si-Al systems
Stable single layer structures of aluminum oxide: Vibrational and electronic characterization of magnetic phases
Effects of electron-correlation, spin-orbit coupling, and modified Becke-Johnson potential in double perovskites SrLaBB′ O6 (B= Ni, Fe; B′= Os, Ru)
Electronic band gaps of ternary corundum solid solutions from Fe2O3–Cr2O3–Al2O3 system for photocatalytic applications: A theoretical study
B3LYP investigation of response properties of alkali halides on external static electric fields
How well do implicit solvation models represent intermolecular binding energies in organic-inorganic solutions?
INTERACTION OF LASER RADIATION WITH MATTER: Formation of quasi-periodic nano-and microstructures on silicon surface under IR and UV femtosecond laser pulses
Specific features of single-pulse femtosecond laser micron and submicron ablation of a thin silver film coated with a micron-thick photoresist layer
Photofragmentation of colloidal solutions of gold nanoparticles under femtosecond laser pulses in IR and visible ranges
Local field enhancement on metallic periodic surface structures produced by femtosecond laser pulses
On the possibility of increasing lifetime of a neutron generator target through laser-induced nanorelief generation at the film–substrate interface
ABC-model analysis of gain-switched pulse characteristics in low-dimensional semiconductor lasers
Laser ablation of polished and nanostructured titanium surfaces by nanosecond laser pulses
Optical apertureless fiber microprobe for surface laser modification of metal films with sub-100 nm resolution
Continuous-wave dual-wavelength operation at 1062 and 1338 nm in Nd3+: YAl3 (BO3) 4 and observation of yellow laser light generation at 592 nm by their self-sum-frequency-mixing
Optical isolation via one-dimensional magneto-photonic crystals containing nonlinear defect layer
Nanostructured plasmas for enhanced gamma emission at relativistic laser interaction with solids
Mode-locking of neodymium lasers by glasses doped with PbS nanocrystals
Infrared analysis of nano organic particles produced in laminar flames
Time-resolved fluorescence polarization anisotropy of multimodal samples: the asphaltene case
Diffusivity in water and fluorescence properties of organic nanoparticles produced in flames
MAPLE-deposited PFO films: influence of the laser fluence and repetition rate on the film emission and morphology
First water-soluble µ-nitrido dimer of iron phthalocyanine
Single-step direct laser writing of halide perovskite microlasers
Effect of thermal-convection-induced defects on the performance of perovskite solar cells
Novel application of MgF2 as a back reflector in a-SiOx: H thin-film solar cells
Semitransparent perovskite solar cells with exceptional efficiency and transmittance
Highly stable fluorine-passivated In–Ga–Zn–O thin-film transistors under positive gate bias and temperature stress
High-temperature plastic deformation and acoustic emission of aluminum in a low-stability state
Macroscopic correlation of elementary deformation events in a low-stability crystal lattice of FCC-metals
Acoustic wave correlation of elementary deformation events in a low-stability crystal lattice of FCC-metals
Giant enhancement of radiative recombination in perovskite light-emitting diodes with plasmonic core-shell nanoparticles
Hybrid perovskite terahertz photoconductive antenna
Suppression of electric field-induced segregation in sky-blue perovskite light-emitting electrochemical cells
Manipulation technique for precise transfer of single perovskite nanoparticles
Recrystallization of CsPbBr3 Nanoparticles in Fluoropolymer Nonwoven Mats for Down- and Up-Conversion of Light
Light-trapping electrode for the efficiency enhancement of bifacial perovskite solar cells
Femtosecond Laser-Assisted Formation of Hybrid Nanoparticles from Bi-Layer Gold–Silicon Films for Microscale White-Light Source
Organic Solar Cells Improved by Optically Resonant Silicon Nanoparticles
Charge transport in trap-sensitized infrared PbS quantum-dot-based photoconductors: Pros and cons
Ligand-Length Modification in CsPbBr3 Perovskite Nanocrystals and Bilayers with PbS Quantum Dots for Improved Photodetection Performance
Optical Amplification in Hollow-Core Negative-Curvature Fibers Doped with Perovskite CsPbBr3 Nanocrystals
Two-dimensional indium selenide for sulphur vapour sensing applications
Enhanced Spontaneous Emission of CsPbI3 Perovskite Nanocrystals Using a Hyperbolic Metamaterial Modified by Dielectric Nanoantenna
Reconfigurable THz plasmonic antenna based on few-layer graphene with high radiation efficiency
Structural and Electrical Investigation of Cobalt-Doped NiOx/Perovskite Interface for Efficient Inverted Solar Cells
Photo-Induced Black Phase Stabilization of CsPbI3 QDs Films
Understanding the impact of Cu-In-Ga-S nanoparticles compactness on holes transfer of perovskite solar cells
Efficient Quasi-2D Perovskite Light-Emitting Diodes Enabled by Regulating Phase Distribution with a Fluorinated Organic Cation
Effects of 5-ammonium valeric acid iodide as additive on methyl ammonium lead iodide perovskite solar cells
Structural Transitions and Stability of FAPbI3 and MAPbI3: The Role of Interstitial Water
Self-Assembled Metal Nanoclusters: Driving Forces and Structural Correlation with Optical Properties
Reduction of Grain Boundary Resistance of La0.5Li0.5TiO3 by the Addition of Organic Polymers
Polymer-II-VI nanocrystals blends: basic physics and device applications to lasers and LEDs
Local Morphology Effects on the Photoluminescence Properties of Thin CsPbBr3 Nanocrystal Films
Light emission properties of thermally evaporated CH3NH3PbBr3 perovskite from nano-to macro-scale: Role of free and localized excitons
Temperature-Dependent Amplified Spontaneous Emission in CsPbBr3 Thin Films Deposited by Single-Step RF-Magnetron Sputtering
Special Issue “II-VI Semiconductor Nanocrystals and Hybrid Polymer–Nanocrystal Systems”
Recent advances in nanostructured inorganic hole-transporting materials for perovskite solar cells
Monovalent Copper Cation Doping Enables High-Performance CsPbIBr2-Based All-Inorganic Perovskite Solar Cells
Charge Transport in Trap-Sensitized Infrared PbS Quantum-Dot-Based Photoconductors: Pros and Cons
Improving of the Photovoltaic Characteristics of Dye-Sensitized Solar Cells Using a Photoelectrode with Electrospun Porous TiO2 Nanofibers
Growth Temperature Influence on Atomic-Layer-Deposited In2O3 Thin Films and Their Application in Inorganic Perovskite Solar Cells
Room-Temperature Solution-Processed 0D/1D Bilayer Electrodes for Translucent CsPbBr3 Perovskite Photovoltaics
Structural Disorder in Layered Hybrid Halide Perovskites: Types of Stacking Faults, Influence on Optical Properties and Their Suppression by Crystallization Engineering
Butanediammonium Salt Additives for Increasing Functional and Operando Stability of Light-Harvesting Materials in Perovskite Solar Cells
Binder-free electrode based on ZnO nanorods directly grown on aluminum substrate for high performance supercapacitors
NiO Nanofibers as a Candidate for a Nanophotocathode
Quantum dot sensitized photoelectrodes
Electrospun composites of polycaprolactone and porous silicon nanoparticles for the tunable delivery of small therapeutic molecules
Carboxylic Acid Functionalization at the Meso-Position of the Bodipy Core and Its Influence on Photovoltaic Performance
Single-Walled Carbon Nanotube-Assisted Antibiotic Delivery and Imaging in S. epidermidis Strains Addressing Antibiotic Resistance
Automated Approach to In Vitro Image-Guided Photothermal Therapy with Top-Down and Bottom-Up-Synthesized Graphene Quantum Dots
Sodium-Ion Conductivity and Humidity-Sensing Properties of Na2O-MoO3-P2O5 Glass-Ceramics
Improving the Stability of Ball-Milled Lead Halide Perovskites via Ethanol/Water-Induced Phase Transition
Ferroelectricity in Si-doped hafnia: probing challenges in absence of screening charges
Acknowledgement to Reviewers of Nanomaterials in 2019
Iron oxide colloidal nanoclusters as theranostic vehicles and their interactions at the cellular level
Laser-assisted fabrication for metal halide perovskite-2D nanoconjugates: Control on the nanocrystal density and morphology
Laser-Induced Morphological and Structural Changes of Cesium Lead Bromide Nanocrystals
Perovskite Nanostructures: From Material Design to Applications
Ligand-length modification in CsPbBr3 perovskite nanocrystals and bilayers with PbS quantum dots for improved photodetection performance
Conjugates of Ultrasmall Quantum Dots and Acridine Derivatives as Prospective Nanoprobes for Intracellular Investigations
Towards Highly Efficient TADF Yellow-Red OLEDs Fabricated by Solution Deposition Methods: Critical Influence of the Active Layer Morphology
Effect of the host on deep-blue organic light-emitting diodes based on a TADF emitter for roll-off suppressing
Nanostructured perovskite solar cells
First proof-of-principle of inorganic lead halide perovskites deposition by magnetron-sputtering
Large-Area nanocrystalline caesium lead chloride thin films: A focus on the exciton recombination dynamics
Electrical and Optical Characterization of CsPbCl3 Films around the High-Temperature Phase Transitions
Polypyrrole and Graphene Nanoplatelets Inks as Electrodes for Flexible Solid-State Supercapacitor
Tantalum Oxide as an Efficient Alternative Electron Transporting Layer for Perovskite Solar Cells
Influence of Sintering Strategy on the Characteristics of Sol-Gel Ba1−xCexTi1−x/4O3 Ceramics
Exploring the structural competition between the black and the yellow phase of cspbi3
Controllable synthesis of 2D perovskite on different substrates and its application as photodetector
Polarization dependent excitation and high harmonic generation from intense mid-IR laser pulses in ZnO
Tunable low crystallinity carbon nanotubes/silicon Schottky junction arrays and their potential application for gas sensing
Enhanced Visible Light-Driven Photoelectrocatalytic Degradation of Paracetamol at a Ternary z-Scheme Heterojunction of Bi2WO6 with Carbon Nanoparticles and TiO2 Nanotube Arrays …
Hybrid Organic–Inorganic Perovskite Superstructures for Ultrapure Green Emissions
Carbon Nanodots as Electron Transport Materials in Organic Light Emitting Diodes and Solar Cells
Nanomaterial-Based CO2 Sensors
Strain Engineering: A Pathway for Tunable Functionalities of Perovskite Metal Oxide Films
Defective States in Micro-Crystalline CsPbBr3 and Their Role on Photoconductivity
Laser post-processing of halide perovskites for enhanced photoluminescence and absorbance
Single-stage fabrication of low-loss dielectric nanoresonators from high-loss material
Laser printing of Au/Si core-shell nanoparticles
Control of spontaneous emission rate in luminescent resonant diamond particles
Coating of Au nanoparticle by Si shell for enhanced local heating
Electric field-induced segregation in a sky-blue perovskite light-emitting diode based on CsPbBr2Cl: PEO composite
Cesium lead mixed-halide perovskites in polymer matrix
Manipulating fano resonance via fs-laser melting of hybrid oligomers at nanoscale
Direct femtosecond laser writing of optical nanoresonators
Synthesis of perovskite nanoparticles in microfluidic chips
Mixed halide perovskite light emitting solar cell
Femtosecond laser nanostructuring of reinforcement bars surface for improvement of its interaction with concrete
Multi wall carbon nanotubes as a top electrode for perovskite light-emitting electrochemical cells
Ultrafast laser heating of non-plasmonic nanocylinders
ITO-free Perovskite Light-Emitting Electrochemical Cell
Water-stable halide perovskite nanocrystals in biological environment
Mesoporous perovskite solar cells with Al-and Zn-based metal-organic frameworks
Optical modes in perovskite nanowire with shallow bi-periodic grating
Perovskite solar cell improvement by gold nanoparticles prepared by laser ablation in liquid
Rapid synthesis and optical properties of CsPbBr2Cl perovskite nanolasers
Nonlinear optical properties of Sponge Si/Au nanoparticle
Memristive properties of solar cells based on perovskite and polymer composite
Resonant silicon nanoparticles for efficiency and stability enhancement of perovskite solar cells
Fabrication of spherical GeSbTe nanoparticles by laser printing technique
Optical tuning of near and far fields form hybrid dimer nanoantennas via laser-induced melting
Optical sensing of organic solvents vapor with lead halide perovskite nanowire lasers on one-dimensional polymer nanograting
Encapsulation of Recrystallized Inorganic Perovskite Quantum Dots in Nonwoven Fluoropolymer Fibers
Study of nonlinear optical phenomena in silicon nanowires
Processing and characterization of GaP nanowires encapsulated into a PDMS large-scale membrane for flexible optoelectronics
Study of nonlinear optical phenomena in silicone films encapsulated with SiO2 and Si/SiO2 spherical particles
Control of spontaneous emission rate in lead halide perovskite film on hyperbolic metamaterial
Theoretical study of perovskite nanowires optical response to hydrogen halides vapor exposure
Theoretical study of surface states excitation in one-dimensional photonic crystal by halide perovskite microstructures
Anion Exchange Reaction in Halide Perovskite Single Crystals Structured by Laser Pulses
Upconversion photoluminescence of perovskite nanoparticles encapsulated in porous sub-micron spheres supporting Mie resonances.
Silicon nanowire/polymer membrane for infrared visualization via third-harmonic generation
Switchable Purcell enhancement of photoluminescence by GST film
Continuous-Flow Synthesis of Perovskite Particles for Optical Application
Semitransparent visualizers of infrared lasers based on perovskite quantum dots
2D Perovskite Micro-optics Enabled by Direct Femtosecond-Laser Projection Lithography
Optical heating of doped semiconductor nanocylinders supporting quasi-BIC modes
Fabrication of halide-perovskite resonant microcylinders by nanoimprint lithography
Light induced temperature decrease of semiconductor nanoparticle
Doping of resonant silicon nanodisks for efficient optical heating in the near-infrared range
Semiconductor resonant all-optical temperature sensor and thermal release trigger of encapsulated anti-cancer drugs for in vitro studies
Investigation of the electrical and optical properties of nickel oxide films produced by RF magnetron sputtering method
Numerical study of optical properties of sphere-gap-cone hybrid nanoantenna
Optical properties of spatially dispersive Mie-resonant halide perovskite nanoparticles
Emission rate studying through nanodiamonds with embedded nitrogen vacancy centers
Photoluminescence spectral position shift governed by optical heating of perovskite resonant nanoparticles
Laser deposition of resonant silicon nanoparticles on perovskite for photoluminescence enhancement
Laser-Induced Periodical Structures Fabrication for Third Harmonic Generation
Application of low-voltage backscattered electron imaging to the mapping of organic photovoltaic blend morphologies
Emission properties of single InAs/GaAs quantum dot pairs and molecules grown in GaAs nanoholes
Thermal activated carrier transfer between InAs quantum dots in very low density samples
An insight into the local Oh→ Td instability in BaF2: Mn2+
High-pressure thermopower technique and its application
Pressure-driven Phase Transition in CaFeAsF at 40 and 300 K
Thermopower and phase transition in YbPd2Si2 under ultra high pressure
Colloidal synthesis and characterization of Bi2S3 nanoparticles for photovoltaic applications
Atom optics with Bose–Einstein condensates: quantum reflection and interferometry
Thermoelectric effect in nano-scaled lanthanides doped ZnO
Characterization of single crystalline ZnTe and ZnSe grown by vapor phase transport
Ground state study of electronic and magnetic properties of Co2MnZ (Z= Ge, Sn) type Heusler compounds: A first principle study
Study of Bulk modulus, Volume, Energy, lattice parameters and magnetic moments in rare earth hexaborides using density functional theory
Study of 4f electron based compound Sm1-xGdxAlO3, a thermoelectric (TE) material: FP-LAPW method
Investigation of doped Perovskite systems RAIO3 using density functional theory based electronic structure and thermoelectric studies
Preparation of catalytic nano-particles and growth of aligned CNTs with HF-CVD
Neutron scattering study of strain behaviour of porous rocks subjected to heating and unconfined uniaxial compression
Crystal violet: study of the photo-fading of an early synthetic dye in aqueous solution and on paper with HPLC-PDA, LC-MS and FORS
Investigation of Deep-level Defects in CuGaSe2 Thin-film Solar Cells by Transient Photo-capacitance Spectroscopy
Emission characteristics of high-gain GaN-based Vertical-Cavity Surface-Emitting Lasers
Bi2212 double pancakes for HTS critical current measurement
FP-LAPW calculations on electronic and thermoelectric properties of Mn2CoCr Heusler compound
Microstructural investigation of strontium titanate films grown by interval pulsed laser deposition
Effect of magnetic field on thermal conductivity of the cobalt ferrite magnetic nanofluids
Radiation interaction properties of verious polymers, satureted and unsaturated fatty acids: A comparative investigation of Monte carlo simulation and NISTXCOM
Micromagnetic simulation of nanomagnets with geometry-tuned domain wall nucleation
XXII International Conference on Integrable Systems and Quantum Symmetries (ISQS-22)
Ultrasmall Quantum Dots: A Tool for in Vitro and in Vivo Fluorescence Imaging
Mechanism of the free charge carrier generation in the dielectric breakdown
Synthesis and characterization of silver-aqueous polymer (Cts/Dx) nanocomposite

Microfluidic device for hydroxyapatite crystals growth process study
Nanoscale investigation of organic–inorganic halide perovskites
Lithium implanted into diamond: Regular trends and anomalies
Needle grass array of nanostructured nickel cobalt sulfide electrode for clean energy generation
Design and performance of AlTiN and TiAlCrN PVD coatings for machining of hard to cut materials
Multi-functional nano-multilayered AlTiN/Cu PVD coating for machining of Inconel 718 superalloy
Significant role of substrate temperature on the morphology, electronic structure and thermoelectric properties of SrTiO3 films deposited by pulsed laser deposition
Ultrafast electron dynamics of material surfaces under the action of femtosecond laser pulses
Nanoand microstructuring of materials’ surfaces using femtosecond laser pulses
Plasmon–polariton assisted formation of nanotip arrays on surfaces of bulk aluminum upon femtosecond laser irradiation
Optical absorption of composite systems with silver nanoparticles dispersed in arabinogalactan and arabinogalactan-g-polypyrrole block copolymer matrices
Effect of fluence and ambient environment on the surface and structural modification of femtosecond laser irradiated Ti
Sputtered gold nanoparticles enhanced quantum dot light-emitting diodes
Band-gap engineering of La1− xNdxAlO3 (x= 0, 0.25, 0.50, 0.75, 1) perovskite using density functional theory: A modified Becke Johnson potential study
Band-gap engineering of La1-x Nd x AlO3 (x = 0, 0.25, 0.50, 0.75, 1) perovskite using density functional theory: A modified Becke Johnson potential study
Influence of barrier thickness on the structural and optical properties of InGaN/GaN multiple quantum wells
First principles study of stability, mechanical, and electronic properties of chromium silicides
Improved performance of polymer solar cells by using inorganic, organic, and doped cathode buffer layers
Pure blue and white light electroluminescence in a multilayer organic light-emitting diode using a new blue emitter
Reliability of organic light-emitting diodes in low-temperature environment
Quantum density functional theory studies of structural, elastic, and opto-electronic properties of ZMoO3 (Z= Ba and Sr) under pressure
Recent progress on photoluminescence from plasmonic nanostructures: Phenomenon, mechanism, and application
Control over hysteresis curves and thresholds of optical bistability in different semiconductor double quantum wells
Nanocomposites based on globular photonic crystals grown by laser ablation using femtosecond laser pulses
Modifying light-matter interactions with perovskite nanocrystals inside anti-resonant photonic crystal fiber
CsPbBr3 perovskite quantum-dot paper exhibiting a highest 3  dB bandwidth and realizing a flexible white-light system for visible-light communication
Detour-phased perovskite ultrathin planar lens using direct femtosecond laser writing
Superior single-mode lasing in a self-assembly CsPbX3 microcavity over an ultrawide pumping wavelength range
Defects and solarization in YAG transparent ceramics
Peculiarities of magnetron sputtering of nickel oxide thin films for use in perovskite solar cells
Effect of processing by femtosecond pulsed laser on mechanical properties of submicrocrystalline titanium
Incorporation of Perovskite Nanocrystals into Polymer Matrix for Enhanced Stability in Biological Media: In Vitro and In Vivo Studies
Physicochemical tools: toward a detailed understanding of the architecture of targeted radiotherapy nanoparticles
Development of an aptamer-conjugated polyrotaxane-based biodegradable magnetic resonance contrast agent for tumor-targeted imaging
De Novo Designed Hexadecapeptides Synergize Glycopeptide Antibiotics Vancomycin and Teicoplanin against Pathogenic Klebsiella pneumoniae via Disruption …
Seed power: natural seed and electrospun Poly (vinyl difluoride)(PVDF) nanofiber based triboelectric nanogenerators with high output power density
Inkjet assisted patterning of Bragg grating towards multiple color imaging
Structural color image augmented by inkjet printed perovskite patterning
Architectural modification coupled with MAI passivation of MAPbI3–MAPbI3 interface for fabrication of highly-responsive broadband bifacial perovskite photodetectors
Bismuth telluride topological insulator synthesized using liquid metal alloys: Test of NO2 selective sensing
Large-area hysteresis-free perovskite solar cells via temperature controlled doctor blading under ambient environment
Millimeter-scale gate-tunable graphene nanoribbon devices as a platform for mid-infrared and bio sensing applications
Small molecule crystals with 1D water wires modulate electronic properties of surface water networks
Oxidized impurity in transition metal nitride for improving the hydrogen evolution efficiency of transition metal nitride-based catalyst
Room temperature light emitting diode based on 2D hybrid organic-inorganic low dimensional perovskite semiconductor
Polystyrene based perovskite light emitting diode
5.91%-efficient Sb2Se3 solar cells with a radio-frequency magnetron-sputtered CdS buffer layer
A photo-capacitive sensor operational from 6 K to 350 K with a solution printable, thermally-robust hexagonal boron nitride (h-BN) dielectric and conductive graphene electrodes
Synergistically enhanced electric field in inhomogeneous nanocavities for the application of recyclable SERS sensing
Roadmap on perovskite nanophotonics
Investigation of carrier dynamics of QDs using kinetic model and ultrafast spectroscopy
Amplified Spontaneous Emission in low dimensional lead halide perovskites: An overview
Femtosecond Laser-Induced Periodical Nanomodification of Surface Composition
On the Power Factor of Bismuth-Telluride-Based Alloys near Topological Phase Transitions at High Pressures
A DFT study of BeX (X = S, Se, Te) semiconductor: Modified Becke Johnson (mBJ) potential
Photo-and electroluminescence from semiconductor colloidal quantum dots in organic matrices: QD-OLED
The Impact of Backbone Fluorination and Side-Chain Position in Thiophene-Benzothiadiazole-Based Hole-Transport Materials on the Performance and Stability of Perovskite Solar Cells
Crystallization Pathways of FABr-PbBr2-DMF and FABr-PbBr2-DMSO Systems: The Comprehensive Picture of Formamidinium-Based Low-Dimensional Perovskite-Related Phases and …
Combined Fluorescence Fluctuation and Spectrofluorometric Measurements Reveal a Red-Shifted, Near-IR Emissive Photo-Isomerized Form of Cyanine 5
1, 2, 4-Oxadiazole/2-Imidazoline hybrids: Multi-target-directed compounds for the treatment of infectious diseases and cancer
Structure-Directing Interplay between Tetrel and Halogen Bonding in Co-Crystal of Lead (II) Diethyldithiocarbamate with Tetraiodoethylene
Spontaneous Transformation of Biomedical Polymeric Silver Salt into a Nanocomposite: Physical–Chemical and Antimicrobial Properties Dramatically Depend on the Initial …
Ionic Liquid Gating in Perovskite Solar Cells with Fullerene/Carbon Nanotube Collectors
Interface Engineering in Perovskite Solar Cells by Low Concentration of Phenylethyl Ammonium Iodide Solution in the Antisolvent Step
Impact of residual lead iodide on photophysical properties of lead triiodide perovskite solar cells
Identifying the cause of voltage and fill factor losses in perovskite solar cells by using luminescence measurements
High‐Throughput Aging System for Parallel Maximum Power Point Tracking of Perovskite Solar Cells
Procedure Based on External Quantum Efficiency for Reliable Characterization of Perovskite Solar Cells
Mechanochemical synthesis of Sn (II) and Sn (IV) iodide perovskites and study of their structural, chemical, thermal, optical, and electrical properties
Four‐terminal perovskite on silicon tandem solar cells optimal measurement schemes
Improved Quality Absorber Layer of I–III–VI2 Compound Semiconductors: Purification Process Revisited
Zincophilic Laser‐Scribed Graphene Interlayer for Homogeneous Zinc Deposition and Stable Zinc‐Ion Batteries
Recent advances in the development of anode materials for solid oxide fuel cells utilizing liquid oxygenated hydrocarbon fuels: a mini review
A Computational Approach toward the Enhanced Performance of Graphene–Perovskite Schottky Solar Cells
Low Temperature, Vacuum‐Processed Bismuth Triiodide Solar Cells with Organic Small‐Molecule Hole Transport Bilayer
1D pyrrolidinium lead iodide for efficient and stable perovskite solar cells
Improved Electrical Performance of Perovskite Photovoltaic Mini‐Modules through Controlled PbI2 Formation Using Nanosecond Laser Pulses for P3 Patterning
Decoupling of Implied and External V OC Due to Ionic Movement Explaining Transient V OC Overshoot in Perovskite Solar Cells
Al2O3‐Atomic Layer Deposited Films on CH3NH3PbI3: Intrinsic Defects and Passivation Mechanisms
Toward general rules for the design of battery electrodes based on titanium oxides and free of conductive additives
Thiocyanate‐and Thiol‐Functionalized p‐Doped Quantum Dot Colloids for the Development of Bulk Homojunction Solar Cells
γ‐Valerolactone: A Nontoxic Green Solvent for Highly Stable Printed Mesoporous Perovskite Solar Cells
Enhanced Thermal Stability of Low‐Temperature Processed Carbon‐Based Perovskite Solar Cells by a Combined Antisolvent/Polymer Deposition Method
Efficiency and Stability Analysis of 2D/3D Perovskite Solar Cells Using Machine Learning
Alloying nanoparticles by discharges in liquids: a quest for metastability
A study of the surface plasmon resonance of silver nanoparticles by the discrete dipole approximation method: effect of shape, size, structure, and assembly
Polarimetric plasmonic sensing with bowtie nanoantenna arrays
Resonant aluminum nanodisk array for enhanced tunable broadband light trapping in ultrathin bulk heterojunction organic photovoltaic devices
Linear and nonlinear absorption properties of diamond-like carbon doped with Cu nanoparticles
Enhanced nonlinear optical response of resonantly coupled silver nanoparticle–organic dye complexes
Routes to tin chalcogenide materials as thin films or nanoparticles: a potentially important class of semiconductor for sustainable solar energy conversion
Raman and optical characteristics of van der Waals heterostructures of single layers of GaP and GaSe: a first-principles study
Highly efficient and stable CsPbBr 3 perovskite quantum dots by encapsulation in dual-shell hollow silica spheres for WLEDs
Electron belt-to-σ-hole switch of noncovalently bound iodine (I) atoms in dithiocarbamate metal complexes
Inorganic–organic {d z2-M II S 4}⋯ π-hole stacking in reverse sandwich structures: the case of cocrystals of group 10 metal dithiocarbamates with electron-deficient arenes
Pressure-induced reversible framework rearrangement and increased polarization in the polar [NH 4][Cd (HCOO) 3] hybrid perovskite
pH-Induced Surface Modification of Atomically Precise Silver Nanoclusters: An Approach for Tunable Optical and Electronic Properties
Surfactant media to grow new crystalline cobalt 1, 3, 5-benzenetricarboxylate metal–organic frameworks
Surfactant-thermal syntheses, structures, and magnetic properties of Mn–Ge–sulfides/selenides
Origin of the exotic blue color of copper-containing historical pigments
Origin of the Zero-Field Splitting in Mononuclear Octahedral MnIV Complexes: A Combined Experimental and Theoretical Investigation
Cu2+ in Layered Compounds: Origin of the Compressed Geometry in the Model System K2ZnF4:Cu2+
Origin of Small Barriers in Jahn–Teller Systems: Quantifying the Role of 3d–4s Hybridization in the Model System NaCl:Ni+
Quantifying Local and Cooperative Components in the Ferroelectric Distortion of BaTiO3: Learning from the Off-Center Motion in the MnCl65– Complex Formed in KCl:Mn …
Large differences in the optical spectrum associated with the same complex: the effect of the anisotropy of the embedding lattice
Role of Ligand on Photophysical Properties of Nanoclusters with fcc Kernel: A Case Study of Ag14(SC6H4X)12(PPh3)8 (X = F, Cl, Br)
Effect of Stacking Interactions on the Translation of Structurally Related Bis (thiosemicarbazonato) nickel (II) HER Catalysts to Modified Electrode Surfaces
Multiphase Transformations Controlled by Ostwald’s Rule in Nanostructured Ce0.5Zr0.5O2 Powders Prepared by a Modified Pechini Route
Structural and Magnetic Transitions in CaCo3V4O12 Perovskite at Extreme Conditions
Structural Diversity of Magnetite and Products of Its Decomposition at Extreme Conditions
Synthesis of Ilmenite-type ε-Mn2O3 and Its Properties
Structural Stability and Properties of Marokite-Type γ-Mn3O4
Lead-Free MA2CuClxBr4–x Hybrid Perovskites
A zero-dimensional mixed-anion hybrid halogenobismuthate (III) semiconductor: Structural, optical, and photovoltaic properties
Understanding the Structure and Ground State of the Prototype CuF2 Compound Not Due to the Jahn–Teller Effect
Ground State and Optical Excitations in Compounds with Tetragonal CuF64– Units: Insight into KAlCuF6 and CuFAsF6
CaMn1−x NbxO3 (x ≤ 0.08) Perovskite-Type Phases As Promising New High-Temperature n-Type Thermoelectric Materials
New Materials Derived from Ybco:  CrSr2RECu2O8 (RE = La, Pr, Nd, Eu, Gd, Tb, Dy, Y, Ho, Er, Lu)
Synthesis, Crystal Structure, and Microstructure Analysis of Perovskite-Type Compounds LnCo0.95Ni0.05O3 (Ln = La, Pr, Nd, Sm, Gd, and Dy)
New materials derived from Ybco: CrSr2RECu2O8 (Re
High-Pressure Synthesis, Crystal Structures, and Magnetic Properties of 5d Double-Perovskite Oxides Ca2MgOsO6 and Sr2MgOsO6
Electrical and Structural Characterization of Ba3Mo1–x Nb1+ x O8. 5–x/2: The Relationship between Mixed Coordination, Polyhedral Distortion and the Ionic Conductivity of …
Relationship between the Crystal Structure and Electrical Properties of Oxide Ion Conducting Ba3W1.2Nb0.8O8.6
Absence of Colossal Magnetoresistance in the Oxypnictide PrMnAsO0.95F0.05
Variable Temperature Neutron Diffraction Study of the Oxide Ion Conductor Ba3VWO8.5
Investigation of the Crystal Structure and Ionic Pathways of the Hexagonal Perovskite Derivative Ba3–xVMoO8.5–x
The Crystal Structure of Ba3Nb2O8 Revisited: A Neutron Diffraction and Solid-State NMR Study
Magnetic Phase Separation in the Oxypnictide Sr2Cr1.85Mn1.15As2O2
Localized Spin Dimers and Structural Distortions in the Hexagonal Perovskite Ba3CaMo2O9
Luminescent and photoconductive layered lead halide perovskite compounds comprising mixtures of cesium and guanidinium cations
Design and synthesis of heteroleptic iridium (III) phosphors for efficient organic light-emitting devices
Metallocyclodextrins as building blocks in noncovalent assemblies of photoactive units for the study of photoinduced intercomponent processes
Tripyridinophane platform containing three acetate pendant arms: An attractive structural entry for the development of neutral Eu (III) and Tb (III) complexes in aqueous solution
Decorating Poly (alkyl aryl-ether) Dendrimers with Metallacarboranes
Zero-dimensional hybrid organic–inorganic lead halides and their post-synthesis reversible transformation into three-dimensional perovskites
Synthesis, Crystal Structure, and Broadband Emission of (CH3)3SSnCl3
Cation-selective and anion-controlled fluorogenic behaviors of a benzothiazole-attached macrocycle that correlate with structural coordination modes
Ligand-induced formation of copper (I) iodide clusters: exocyclic coordination polymers with bis-dithiamacrocycle isomers
Cooperative Effect of Anion and Mole Ratio on the Coordination Modes of an NO2S3-Donor Macrocycle
Hard and Soft Metal Complexes of Calix[4]-bis-monothiacrown-5: X-ray and NMR Studies of Discrete Homodinuclear Complexes and a Heteromultinuclear Network
Regioisomer-dependent endo-and exocyclic coordination of bis-dithiamacrocycles
Group 12 Metal Complexes of an 18-Membered N2O2S2 Macrocycle Incorporating Two Pyridines: First Examples of an Infinite Mercury(I) Complex and a …
Influence of Anion and Mole Ratio on the Coordination Behavior of an NO2S3-Macrocycle: The Formation of a Dumbbell-Shaped Macrocyclic Cadmium(II) Iodide …
Endo- and Exocyclic Coordination of a 20-Membered N2O2S2-Macrocycle and Cascade Complexation of a 40-Membered N4O4S4-Macrocycle
Pillar[5]-bis-trithiacrown: Influence of Host–Guest Interactions on the Formation of Coordination Networks
Construction of 2D Interdigitated Polyrotaxane Layers and their Transformation to a 3D Polyrotaxane by a Photocycloaddition Reaction between Wheels
Unexpected Solvent-Dependent Self-Assembly of Alkali Metal Complexes of Calix[6]-mono-crown-4: Dinuclear Bowls, a Pseudo-Capsule, and a One-Dimensional …
Metallosupramolecules of Pillar [5] arene with Two Flexible Thiopyridyl Arms: A Heterochiral Cyclic Dimer and Organic Guest-Assisted Homochiral Poly-Pseudo-Rotaxanes
Highly stable tetrahydrothiophene 1-oxide caged copper bromide and chloride clusters with deep-red to near-IR emission
Synergy of the LaVO4/h-BN Nanocomposite: A Highly Active Electrocatalyst for the Rapid Analysis of Carbendazim
Well-designed construction of yttrium orthovanadate confined on graphitic carbon nitride sheets: electrochemical investigation of dimetridazole
Toward the Development of Disposable Electrodes Based on Holmium Orthovanadate/f-Boron Nitride: Impacts and Electrochemical Performances of Emerging …
Surfactant-assisted synthesis of praseodymium orthovanadate nanofiber-supported nife-layered double hydroxide bifunctional catalyst: the electrochemical detection and …
In Situ Synthesis of a Bismuth Vanadate/Molybdenum Disulfide Composite: An Electrochemical Tool for 3-Nitro-l-Tyrosine Analysis
A 3D Oxalate-Based Network as a Precursor for the CoMn2O4 Spinel: Synthesis and Structural and Magnetic Studies
Single-Step Preparation of the Mixed BaII–NbV Oxides from a Heteropolynuclear Oxalate Complex
Ba4Ta2O9 Oxide Prepared from an Oxalate-Based Molecular PrecursorCharacterization and Properties
Effect of the Cation Distribution and Microstructure on the Magnetic Behavior of the CoMn2O4 Oxide
Magnetoelectric Coupling Springing Up in Molecular Ferroelectric: [N(C2H5)3CH3][FeCl4]
Mixed-Metal Imidazolates Containing Alkali and Alkaline Earth Metals: Mechanochemical Synthesis and Crystal Structure of AMgIm3 (A = Na or K)
Stress Evolution during Ge Nanoparticles Growth in a SiO2 Matrix
Pressure-Induced Destabilization and Anomalous Lattice Distortion in TcO2
Highly Luminescent Half-Lantern Cyclometalated Platinum (II) Complex: Synthesis, Structure, Luminescence Studies, and Reactivity.
Controlled synthesis of a novel heteropolymetallic complex with selectively incorporated lanthanide (III) ions
Sustainable Capture of Aromatic Volatile Organic Compounds by a Pyrene-Based Metal–Organic Framework under Humid Conditions
Achievement of Excellent Thermoelectric Properties in Cu–Se–S Compounds via In Situ Phase Separation
Visible-Light-Responsive Photocatalytic Activity Significantly Enhanced by Active [VZn+VO+] Defects in Self-Assembled ZnO Nanoparticles
Lead-Free Antimony Halide Perovskite with Heterovalent Mn2+ Doping
Blue-green iridium (III) emitter and comprehensive photophysical elucidation of heteroleptic cyclometalated iridium (III) complexes
Photophysical properties of Ir (III) complexes immobilized in MCM-41 via templated synthesis
Introducing a Large Polar Tetragonal Distortion into Ba-Doped BiFeO3 by Low-Temperature Fluorination
Topochemical Fluorination of La2NiO4+d: Unprecedented Ordering of Oxide and Fluoride Ions in La2NiO3F2
Phase Transition, Dielectric Properties, and Ionic Transport in the [(CH3)2NH2]PbI3 Organic–Inorganic Hybrid with 2H-Hexagonal Perovskite Structure
Diimidazolium Halobismuthates [Dim]2[Bi2X10] (X = Cl–, Br–, or I–): A New Class of Thermochromic and Photoluminescent Materials
[(CH3)2NH2]7Pb4X15 (X = Cl– and Br–), 2D-Perovskite Related Hybrids with Dielectric Transitions and Broadband Photoluminiscent Emission
Two-Dimensional and Emission-Tunable: An Unusual Perovskite Constructed from Lindqvist-Type [Pb6Br19]7– Nanoclusters

Insight into the role of copper in the promoted photocatalytic removal of NO using Zn2-xCuxCr-CO3 layered double hydroxide
Use of LDH-chromate adsorption co-product as an air purification photocatalyst
Reline deep eutectic solvent mediated synthesis of lanthanum titanate for heavy metal remediation and photocatalytic degradation
Eutectic solvent mediated synthesis of carbonated CoFe-LDH nanorods: The effect of interlayer anion (Cl−, SO42−, CO32−) variants for comparing the bifunctional electrochemical …
VS2 wrapped Si nanowires as core-shell heterostructure photocathode for highly efficient photoelectrochemical water reduction performance
Two dimensional MXenes as emerging paradigm for adsorptive removal of toxic metallic pollutants from wastewater
UV–vis spectroscopic method for detection and removal of heavy metal ions in water using Ag doped ZnO nanoparticles
Changes in heavy metal mobility and availability from contaminated wetland soil remediated with combined biochar-compost
The application of FTO-Cu2O/Ag3PO4 heterojunction in the photoelectrochemical degradation of emerging pharmaceutical pollutant under visible light irradiation
Electrochemical detection of nicotine at a carbon Nanofiber-Poly (amidoamine) dendrimer modified glassy carbon electrode
Mechanism of charge transport in self-organizing organic materials
Synthesis of regioisomerically pure 1, 7-dibromoperylene-3, 4, 9, 10-tetracarboxylic acid derivatives
Highly sensitive water-soluble fluorescent pH sensors based on the 7-amino-1-methylquinolinium chromophore
Perylene bisimide dyes with up to five independently introduced substituents: Controlling the functionalization pattern and photophysical properties using regiospecific bay …
Photoinduced Electron Transfer to C60 across Extended 3- and 11-Bond Hydrocarbon Bridges:  Creation of a Long-Lived Charge-Separated State
Halogenated symmetrical tetraazapentacenes: Synthesis, structures, and properties
Liquid triarylamines: the scope and limitations of piers–rubinsztajn conditions for obtaining triarylamine–siloxane hybrid materials
Electrical properties and mechanical stability of anchoring groups for single-molecule electronics
Synergic combination of the sol–gel method with dip coating for plasmonic devices
Green fabrication of lanthanide-doped hydroxide-based phosphors: Y (OH) 3: Eu3+ nanoparticles for white light generation
α-Silicene as oxidation-resistant ultra-thin coating material
Adsorption and diffusion characteristics of lithium on hydrogenated α-and β-silicene
Orthogonal chemical functionalization of patterned gold on silica surfaces
Self-assembled anchor layers/polysaccharide coatings on titanium surfaces: a study of functionalization and stability
Gas-sensing behaviour of ZnO/diamond nanostructures
Study of the surface properties of ZnO nanocolumns used for thin-film solar cells
Self-assembly and semiconductivity of an oligothiophene supergelator
Structural effects of meso-halogenation on porphyrins
Two novel blue phosphorescent host materials containing phenothiazine-5, 5-dioxide structure derivatives
Ionic multiresonant thermally activated delayed fluorescence emitters for light emitting electrochemical cells
Protonation and deprotonation induced organo/hydrogelation: Bile acid derived gelators containing a basic side chain
Novel derivatives of 1, 6, 7, 12-tetrachloroperylene-3, 4, 9, 10-tetracarboxylic acid: synthesis, electrochemical and optical properties
Charge transport along phenylenevinylene molecular wires
Effect of Structural Defects and Impurities on the Excited State Dynamics of 2D BA2PbI4 Perovskite
Time‐Resolved Thermodynamic Profile upon Photoexcitation of a Nitrospiropyran in Cycloalkanes and of the Corresponding Merocyanine in Aqueous Solutions
Synthesis of 1, 2-biphenylethane based single-molecule diodes
Photoinduced charge separation in a donor–acceptor functionalized 2, 3-diphenylbutadiene: charge transport over a doubly bifurcated π-spacer
Solvation-14-Quantum Mechanical-Molecular Mechanical Calculations of (Hyper-) Polarizabilities with the Direct Reaction Field Approach
Catching two European birds with one renewable stone: Mitigating climate change and Eurozone crisis by an energy transition
Two-dimensional Dion-Jacobson halide perovskites as new-generation light absorbers for perovskite solar cells
A comparative analysis on performances of flat plate photovoltaic/thermal collectors in view of operating media, structural designs, and climate conditions
Limits and possible solutions in quantum dot organic solar cells
An overview of the decompositions in organo-metal halide perovskites and shielding with 2-dimensional perovskites
Recent improvements in dye sensitized solar cells: A review
A top-down analysis: Determining photovoltaics R&D investments from patent analysis and R&D headcount
Development of new feedstock formulation based on high density polyethylene for MIM of M2 high speed steels
Modified metal injection moulding process of 316L stainless steel powders using thermosetting binder
Processing of Mn–Zn ferrites using mould casting with acrylic thermosetting binder
Powder extrusion moulding of 430L stainless steel thin tubes for porous metal supported SOFCs
Porous Ni-YSZ planar anodes by powder extrusion moulding employing PMMA as pore former
Magnetic properties of Mg-ferrite after milling process
Metal injection moulding of HS12-1-5-5 high-speed steel using a PW-HDPE based binder
Comparison of structure and properties of the HS12-1-5-5 type high-speed steel fabricated using the pressureless forming and PIM methods
Fabrication methods and heat treatment conditions effect on tribological properties of high speed steels
Structure and mechanical properties of HSS HS6-5-2-and HS12-1-5-5-type steel produced by modified powder injection moulding process
Processing of P/M M2 high speed steels by mould casting using thermosetting binders
Mechanical properties and pitting corrosion behaviour of 316L stainless steel parts obtained by a modified metal injection moulding process
Structure and reaction with lithium of tetragonal pyrochlore-like compound Sm2Ti2O7
Thermal and mechanical characterization of injection moulded high density polyethylene/paraffin wax blends as phase change materials
Development of thermoelectric oxides for renewable energy conversion technologies
Biomimetic [MoO3@ ZnO] semiconducting nanocomposites: Chemo-proportional fabrication, characterization and energy storage potential exploration
Tailoring triple charge conduction in BaCo0. 2Fe0. 1Ce0. 2Tm0. 1Zr0. 3Y0. 1O3− δ semiconductor electrolyte for boosting solid oxide fuel cell performance
Span80/Tween80 stabilized bio-oil-in-diesel microemulsion: Formation and combustion
Synthesis and characterization of novel hybrid polysulfone/silica membranes doped with phosphomolybdic acid for fuel cell applications
Nanocomposite proton exchange membranes based on Nafion containing Fe2TiO5 nanoparticles in water and alcohol environments for PEMFC
High temperature membranes based on PBI/sulfonated polyimide and doped-perovskite nanoparticles for PEM fuel cells
Cobalt-free niobium-doped barium ferrite as potential materials of dense ceramic membranes for oxygen separation
Efficient and CO2-tolerant oxygen transport membranes prepared from high-valence B-site substituted cobalt-free SrFeO3− δ
Understanding the doping effect toward the design of CO2-tolerant perovskite membranes with enhanced oxygen permeability
New perovskite membrane with improved sintering and self-reconstructed surface for efficient hydrogen permeation
Electrochemical and cycling performances of novel nonafluorobutanesulfonate (nonaflate) ionic liquid based ternary gel polymer electrolyte membranes for rechargeable lithium …
Optimization of the Processing of 8‐YSZ Powder by Powder Injection Molding for SOFC Electrolytes
Production of alumina microparts by powder injection molding
Electrochemical and structural characterization of sulfonated polysulfone
Printer orientation effects and performance of novel 3-D printable acrylonitrile butadiene styrene (ABS) composite filaments for thermal enhancement
Microstructure, mechanical and electrical properties of Ni-YSZ anode supported solid oxide fuel cells
Surface modification of a duplex stainless steel for plastic-metal hybrid parts
Synthesis and characterization of anion-exchange membranes with various functional groups
Development of a feedstock formulation based on PP for MIM of carbides reinforced M2
Structure and properties of HS6-5-2 type HSS manufactured by different P/M methods
Application of powder injection moulding and extrusion process to manufacturing of Ni-YSZ anodes
Characterization of 430L porous supports obtained by powder extrusion moulding for their application in solid oxide fuel cells
Elaborating the phases and mechanical properties of multiphase alloy: Experimental two-dimensional mapping combined with theoretical calculations
Effects of strontium-containing fluorophosphate glasses for enhancing bioactivity and enamel remineralization
Low cycle fatigue behavior of AlSi10Mg (Cu) alloy at high temperature
Temperature-dependent cyclic response and microstructure of AlSi10Mg (Cu) alloy
Electrical and optical properties of NdAlO3 synthesized by an optimized combustion process
Tunable capacitor-varistor response of CaCu3Ti4O12/CaTiO3 ceramic composites with SnO2 addition
Effect of the composition and structure on the optical properties of Ba1-xLaxTi1-xFexO3 (0≤ x≤ 1) solid solution: Correlation study using Rietveld refinement
Humidity Related Low Temperature Conductivity Hysteresis of Ce1–xZrxO2 (0 ≤ x ≤ 1) Ceramics. Structural Disorder Relationship
Electrochemical performance of a Ni and YSZ composite synthesised by ultrasonic spray pyrolysis as an anode for SOFCs
The influence of conductive additives and inter‐particle voids in carbon EDLC electrodes
Effect of the A cation size disorder on the properties of an iron perovskite series for their use as cathodes for SOFCs
Engineering the electrical and optical properties of graphene oxide via simultaneous alkali metal doping and thermal annealing
Photocatalytic degradation of reactive anionic dyes RB5, RR198 and RY145 via rare earth element (REE) lanthanum substituted CaTiO3 perovskite catalysts
Structural investigation of Cu doped calcium ferrite (Ca1-xCuxFe2O4; x= 0, 0.2, 0.4, 0.6, 0.8, 1) nanomaterials prepared by co-precipitation method
Unveiling the photosensitive and magnetic properties of amorphous iron nanoparticles with its application towards decontamination of water and cancer treatment
Cubic garnet solid polymer electrolyte for room temperature operable all-solid-state-battery
Green synthesis of LaCrO3 powder mediated by the extract of the Amazon rainforest native plant Himatanthus drasticus (Mart.) Plumel and their photocatalytic activity
Effect of the amapá-latex chelating agent contents on the microstructure and photocatalytic properties of ZnO nanoparticles
Structural, functional properties and enhanced thermal stability of bulk graded (Ba, Sr) TiO3 structures obtained by spark plasma sintering
Aqueous and non-aqueous Li+/H+ ion exchange in Li0. 44La0. 52TiO3 perovskite
Synthesis and physical properties of nanopowder and electrical properties of bulk samples of ZnFe2-xNixO4 (x: 0, 0.05, 0.10)
Synthesis and characterization of novel anion exchange membranes based on semi-interpenetrating networks of functionalized polysulfone: effect of ionic crosslinking
Sulfonated Polysulfone/TiO2(B) Nanowires Composite Membranes as Polymer Electrolytes in Fuel Cells
Using Metal-Organic Framework HKUST-1 for the Preparation of High-Conductive Hybrid Membranes Based on Multiblock Copolymers for Fuel Cells
Melamine foams decorated with in-situ synthesized gold and palladium nanoparticles
Copper metallopolymer catalyst for the electrocatalytic hydrogen evolution reaction (HER)
Efficient Inverted Solar Cells Using Benzotriazole-Based Small Molecule and Polymers
Development of Bisphenol-A-Glycidyl-Methacrylate-and Trimethylolpropane-Triacrylate-Based Stereolithography 3D Printing Materials
Analysis of Fuel Alternative Products Obtained by the Pyrolysis of Diverse Types of Plastic Materials Isolated from a Dumpsite Origin in Pakistan
Novel copper photoredox catalysts for polymerization: an in situ synthesis of metal nanoparticles
Investigations of Fused Deposition Modeling for Perovskite Active Solar Cells
Trade-off analysis of C12A7: e− deposition techniques applied to Low Work Function Tethers
Station-keeping of a high-altitude balloon with electric propulsion and wireless power transmission: A concept study
Polymer electrolytes based on POE and Na-TFS salt for all-solid-state batteries
Effect of tungsten content on glass forming ability and microhardness of Ni-Cr-BW metallic glasses
Layer Shape LiFePO4 Obtained by Powder Extrusion Molding as Solid Boosters for Ferro/Ferricyanide Catholyte in Semisolid Redox Flow Battery: Effect of Porosity …
Recent advances in metal‐organic framework derivatives as oxygen catalysts for zinc‐air batteries
Cover Feature: Recent Advances in Metal‐Organic Framework Derivatives as Oxygen Catalysts for Zinc‐Air Batteries (Batteries &Supercaps 4/2019)
Laser Patterning of High‐Mass‐Loading Graphite Anodes for High‐Performance Li‐Ion Batteries
CdS/TiO2 photoanodes via solution ion transfer method for highly efficient solar hydrogen generation
Understanding the role of facets and twin defects in the optical performance of GaAs nanowires for laser applications
Lead-free, stable, high-efficiency (52%) blue luminescent FA 3 Bi 2 Br 9 perovskite quantum dots
Nanoscale Mapping of Hydrogen Evolution on Metallic and Semiconducting MoS2 Nanosheets.
“Ion sliding” on graphene: a novel concept to boost supercapacitor performance
Tunable Phase Transitions and High Photovoltaic Performance of Two-Dimensional In2Ge2Te6 Semiconductors
Plasmonic Protein Electricity Generator
Horizons Community Board collection: solar energy conversion
Conjugated polyelectrolyte nano field emission adlayers
Anderson-like localization in ultrathin nanocomposite alloy films on polymeric substrates
Nitrogen doped cuprous oxide as low cost hole-transporting material for perovskite solar cells
Effect of grain size on the fracture behavior of organic-inorganic halide perovskite thin films for solar cells
Electron-beam-induced cracking in organic-inorganic halide perovskite thin films
Exploring accurate structure, composition and thermophysical properties of η carbides in 17.90 wt% W-4.15 wt% Cr-1.10 wt% V-0.69 wt% C steel
Ferroelastic tetragonal-monoclinic phase transition and anisotropic thermal expansion of LuNbO4 ceramics
Interaction between ceramic powder and molten calcia-magnesia-alumino-silicate (CMAS) glass, and its implication on CMAS-resistant thermal barrier coatings
The influence of grain boundary area on the complexion time-temperature-transformation diagram of Eu-doped magnesium aluminate spinel
Calculating the grain boundary inclination of voxelated grain structures using a smoothing algorithm
Thermoelectric properties of p-Bi2 − x Sb x Te3 solid solutions under pressure
Electrical properties of (PbS)0.59TiS2 crystals at high pressure up to 20 GPa
Thermoelectric properties of hydrogen ion-irradiated silicon crystals under ultrahigh pressures of up to 20 GPa
High-pressure thermopower of sulfur
Thermoelectric properties of the Pr0.8Na0.2MnO3 manganite at ultrahigh pressures of up to 20 GPa.
Phase transitions in titanium diselenide intercalated with cobaltocene at high pressures of up to 20 GPa.
High-pressure high-temperature synthesis of Cr2O3 and Ga2O3
A Raman study of high-pressure phases of lead chalcogenides PbX (X= S, Se, Te)
Phase transitions from mechanical contraction: direct observation of phase-transition-related volumetric effects in ZnO, GaAs, CaCO3, and CeNi under compression up to 25 GPa
Transport properties of Fe3O4 magnetite at high pressure up to 24 GPa: a search for crossovers
Is it possible to use Charge Transfer Bands to Measure Impurity-Ligand Distances? Experimental and Theoretical Results on Cu 2+ Doped (C 2 H 5 NH 3) 2 CdCl 4
Crystal structure and thermal expansion of Mn1− xFexGe
Search for Pnma materials with high-temperature structural phase transitions
Crystal growth and twinned crystal structure of Sr2CaWO6
Mode-crystallography analysis and magnetic structures of SrLnFeRuO6 (Ln= La, Pr, Nd) disordered perovskites
Cation distribution in Cu2ZnSnSe4, Cu2FeSnS4 and Cu2ZnSiSe4 by multiple-edge anomalous diffraction
Structural properties of defective (CH3NH3) 2Cu (Cl1–xBrx) 4 compounds
Octahedral tilting in the polar hexagonal tungsten bronzes RbNbW2O9 and KNbW2O9
Effect of Fe doping on structure and magnetotransport properties of perovskite manganite
Electronic structure, magnetic, mechanical and thermo-physical behavior of double perovskite Ba2MgOsO6
Insight into pressure tunable structural, electronic and optical properties of [see pdf] via DFT calculations
A complete DFT description on structural, electronic, elastic, mechanical and thermodynamic properties of some intermetallic AuX2 (X = Al, Ga, In) compounds
Quantum mechanical calculations on mechanical and elastic properties of cubic SrCeO3 perovskite
Insight into pressure tunable structural, electronic and optical properties of [inline-graphic not available: see fulltext] via DFT calculations
Ab initio study on half-metallic, electronic and thermodynamic attributes of LaFeO3
Fast neutron bombardment induced semiconductor-metal electron transition in lead selenide
Ultra high pressure application to organic conductors
Ferro-to Paramagnetic Phase Transition in La0. 90Pr0. 10Mn0. 8Co0. 2O3 Perovskite
Critical Behavior and Magnetocaloric Effect Simulation in NiMnGaTb Heusler Alloy
Sol–Gel Synthesis and Characterizations for La0.7Ca0.15Pb0.15CoO3 Perovskite Cobaltite for Optical and Magnetic Applications
Negative Magnetization Effect in Distorted Honeycomb Ni4Nb2O9 Ceramics
High-pressure, High-temperature Synthesis and Properties of the Monoclinic Phase of Y2O3
Clustering-triggered emission of nonaromatic polymers with multitype heteroatoms and effective hydrogen bonding
THERMOELECTRIC POWER OF COMPENSATED Si1-xGex SAMPLES AT HIGH PRESSURE
Phase stability of boron relative to beta-boron at high pressure and high temperature
Synthesis of 13C-diamonds in CaCO3-C system
A (2) FeSbO (6)(A= Sr, Ca) double perovskites oxides: Crystal structures, phase's transitions and Fe-57 Mossbauer spectroscopy study
Solving Crystal Structures Using Symmetry-Mode Collective Coordinates
Structural study of SrPrMRuO6 double perovskites by symmetry-mode analysis
Crystal structures and high-temperature phase transition of Sr2MSbO6 (M= Sc, Cr, Fe) double perovskites
PHASE TRANSITIONS IN SrLaCuRuO6 AND SrLaNiRuO6 DOUBLE PEROVSKITES
Exploring crystal structure, size and stoichiometry of lead chalcogenidc QDs by x-ray total scattering and the Debye scattering equation
CRYSTAL STRUCTURE OF A FERROMAGNETIC SUPERCONDUCTOR
Crystal structure analysis using integrated X-ray powder diffraction software suite PDXL.
An anomalous diffraction study of Cu2Zn (Ge, Si) Se-4
COMBINATION OF EXAFS AND XRD FOR STUDIES OF THE ORTHORHOMBIC-TETRAGONAL PHASE TRANSFORMATION IN MAPBI (3-X) CL (X) PEROVSKITES
X-ray Absorption spectroscopy options for crystallographic research at BESSY II
PDXL Structure Analysis Wizard
DESIGN OF MODULAR CRYSTALLOGRAPHIC LECTURES WITH XML BASED TECHNOLOGIES
Structural properties of AFeO (3-delta) perovskites. Effect of A-site parameters
A Group-theoretical Approach to Enumerating Magnetoelectric and Multiferroic Couplings in Perovskites
In situ imaging of ferroelastic domain dynamics in CsPbBr3 perovskite nanowires by nanofocused scanning X-ray diffraction
Melting dynamics of ices by time-resolved light scattering
Physicochemical evolution of nascent soot particles in a laminar premixed flame: from nucleation to early growth

Experimental data on the characterization of hydroxyapatite produced from a novel mixture of biowastes
The impact of kaolin dehydroxylation on the porosity and mechanical integrity of kaolin based ceramics using different pore formers
A comparative study of the mechanical integrity of natural hydroxyapatite scaffolds prepared from two biogenic sources using a low compaction pressure method
Pressureless sintering and gas flux properties of porous ceramic membranes for gas applications
Nanostructured stannic oxide: Synthesis and characterisation for potential energy storage applications
DFT investigations on the electronic structure, magnetism, thermodynamic and elastic properties of newly predicted cobalt based antiperovskites: Co3XN (X= Pd, Pt &Rh)
Electronic structure and optical anisotropy in Sr1− x BaxFBiS2 (x= 0, 0.25, 0.5, 0.75, 1) based solar cell materials
Extraction of bio-oil during pyrolysis of locally sourced palm kernel shells: Effect of process parameters
Mechanical, spectroscopic and micro-structural characterization of banana particulate reinforced PVC composite as piping material
Suitability of Recycled Polyethylene/Palm Kernel Shell-Iron Filings Composite for Automobile Application
An assessment on the production of abrasive sandpaper from locally sourced materials
Effect of mechanical activation on mullite formation in an alumina-silica ceramics system at lower temperature
Waste to wealth: “A case study of empty water sachet conversion into composite material for automobile application.
The Impact of Gasoline and Synthesized Ethanol Blends on the Emissions of a Spark Ignition Engine
Effects of Electrode Type on the Mechanical Properties of Weldments of Some Steel Samples Produced in Nigeria
Modelling and finite element analysis of turning tables of micro-controller based versatile machine tools desktop learning module
Ensemble learning prediction of transmittance at different wavenumbers in natural hydroxyapatite
Trends in the Development of Hydroxyapatite from Natural Sources for Biomedical Applications
Exploring the Constructive Alignment of Pedagogical Practices in Science and Engineering Education in Sub-Saharan African Universities: A Nigerian Case Study.
Utilization of sawdust as a pore-former in the fabrication of ceramic adsorbents for water purification
Re-Examination of the Structure of Sr2 (MgTe) O6 Double Perovskite
Dielectric properties of nanocomposite based on bismuth copper titanate
Dielectric and magnetic properties of BaFe11.7Ni0.3O19 (BHNF) ceramic synthesized by chemical route
Mixture optimization of synthesized zeolites 4A and 13X for solar adsorption refrigeration application
Abatement of oil residues from produced water using a thermocatalytic packed bed reactor
Construction of novel 3D ZnO hierarchical structure with Fe3O4 assist and its enhanced visible light photocatalytic performance
Probing dynamical symmetry breaking using quantum-entangled photons
The Photophysics of Polythiophene Nanoparticles for Biological Applications
Functionalizing nanocrystalline metal oxide electrodes with robust synthetic redox proteins
Ambient air synthesis of multi-layer CVD graphene films for low-cost, efficient counter electrode material in dye-sensitized solar cells
Impact of water-soluble 2D CdSe/CdS nanoplatelets on seed germination and early growth in Vigna radiata
Rational use of ligand to shift the UV–vis spectrum of Ru-complex sensitiser dyes for DSSC applications
Quantitative analysis of Cu XANES spectra using linear combination fitting of binary mixtures simulated by FEFF9
Optical and structural properties of Eu3+ doped MgO–Li2O–Na2O–BaO–B2O3 glasses for scintillating glass applications
Hydrogen Bonding in the Water Stabilized Structure of the Modified Unsymmetrically Substituted Viologen Chromophore, N-ethyl-N′-(2-phosphonoethyl)-4,4 …
Intracrystalline Equilibrium Reaction in a Protonic Conductor (Proceedings of the 1st International Symposium on Advanced Science Research (ASR-2000), Advances in Neutron …
Graphene quantum dot formulation for cancer imaging and redox-based drug delivery
New MRI contrast agents based on silicon nanotubes loaded with superparamagnetic iron oxide nanoparticles
Fabrication and characterization of Ni-decorated h-BN powders with ChCl-EG ionic liquid as addition by electroless deposition
Investigation of the photoluminescent properties, scintillation behaviour and toxicological profile of various magnesium tungstate nanoscale motifs
Terpyridine-metal complexes: effects of different substituents on their physico-chemical properties and density functional theory studies
Photonics and optoelectronics using nano-structured hybrid perovskite media and their optical cavities
Recent progress in the fabrication of SERS substrates based on the arrays of polystyrene nanospheres
Spectrophotometric determination of hydrazine
Spectrophotometric determination of iodine species in table salt and pharmaceutical preparations
Revealing the effect of multidimensional ZnO@ CNTs/RGO composite for enhanced electrochemical detection of flufenamic acid
Rational incorporation of strontium pyrophosphate/hexagonal boron nitride composite for trace level electrochemical sensing of dopamine
Facile synthesis of magnetite nanocubes using deep eutectic solvent: an insight to anticancer and photo-Fenton efficacy
Effect of fluoride coatings on the corrosion behavior of Mg–Zn–Er alloys
Influence of surfactant-assisted synthesis and different operational parameters on photocatalytic performance of Cu2FeSnS4 particles
The effect of spacer cations on optoelectronic properties of two-dimensional perovskite based on first-principles calculations
Composition-dependent photocatalytic activity and high-mobility carrier gas in NaTaO3/BaBiO3 heterojunctions
ZnO nanostructures based piezo-photocatalytic degradation enhancement of steroid hormones
Chemiresistive La-doped BaTiO3 microspheres for ambient-temperature formaldehyde gas sensing
1: 1 and 1: 2 Complexes of Mercury (II) Halides with 1, 3-Thiazolidine-2-thione. Spectral, Thermal, and Crystal Structure Studies
Strengthening mechanism of aluminum on elastic properties of NbVTiZr high-entropy alloys
Local-ordering mediated configuration stability and elastic properties of aluminum-containing high entropy alloys
Thermodynamic evaluation and optimization of the (Na + X) binary systems (X = Ag, Ca, In, Sn, Zn) using combined Calphad and first-principles methods of calculation
Structural, electronic and magnetic properties of new full Heusler alloys Rh2CrZ (Z= Al, Ga, In): first-principles calculations
Temperature and pressure dependent electronic, mechanical and thermal properties of f-electron based ferromagnetic barium neptunate
Elucidating DFT study on structural, electronic, thermal and elastic properties of SrTcO3 by using GGA and mBJ approach
Enlightening the stable ferromagnetic phase of SrAO3 (A= Cr, Fe and Co) compounds using spin polarized quantum mechanical approach
Pressure induced band-gap tuning in KNbO3 for piezoelectric applications: Quantum DFT-GGA approach
Electronic structure, mechanical and thermodynamic properties of BaPaO3 under pressure
Investigation of electronic, magnetic, elastic, mechanical, thermodynamic, and thermoelectronic properties of Mn2PtV Heusler alloy: ab initio study
High pressure and high temperature investigation of metallic perovskite SnTaO3
Exploring the potential of iron to replace ruthenium in photosensitizers: a computational study
Membrane composition of jetted lipid vesicles: a Raman spectroscopy study
Enhanced salt removal performance of flow electrode capacitive deionization with high cell operational potential
Transport of salicylic acid through supported liquid membrane based on ionic liquids
Removal of Cd (II) by MEUF-FF with anionic-nonionic mixture at low concentration
Nitrogen Doped Carbon Nanosheets Coupled Nickel–Carbon Pyramid Arrays Toward Efficient Evolution of Hydrogen
Bandgap Engineering in Novel Fluorite‐Type Rare Earth High‐Entropy Oxides (RE‐HEOs) with Computational and Experimental Validation for Photocatalytic Water Splitting Applications
A Highly Active Perovskite Cathode for Low‐Temperature Solid Oxide Fuel Cells: BaCo0.7Fe0.22Sc0.08O3–δ
Highly Efficient UV–Visible Photocatalyst from Monolithic 3D Titania/Graphene Quantum Dot Heterostructure Linked by Aminosilane
Temperature dependence of emission properties of self-assembled InGaN quantum dots
Effect of In Diffusion on the Property of Blue Light-Emitting Diodes
Computational Prediction of a Novel Superhard sp 3 Trigonal Carbon Allotrope with Bandgap Larger than Diamond
Resistive Effects on the Spatially Resolved Absolute Electroluminescence of Thin-Film Cu(In, Ga)Se2 Solar Cells Studied by a Distributed Two-Diode Model
Diagnosis of perovskite solar cells through absolute electroluminescence-efficiency measurements
Vein detection with near‐infrared organic photodetectors for biometric authentication
Integration of large-area optical imagers for biometric recognition and touch in displays
Photoconductive zinc oxide-composite paper by pilot paper machine manufacturing
A DFT investigation of CsMgX3 (X= Cl, Br) halide perovskites: electronic, thermoelectric and optical properties
Alkali metal doped nickel oxide clusters: A density functional study
Phonon stability, electronic structure results, mechanical and thermodynamic properties of RbSbO3 and CsSbO3 perovskite oxides: Ab initio investigation
A DFT investigation on electronic structure, charge density, mechanical stability and thermodynamic properties of XAl3 (X= Sc, Yb and Lu) intermetallic compounds
First-principles study of structural, electronic, magnetic, thermodynamic and mechanical properties of ferromagnetic Mn2MoAl Heuslar alloy
Hybrid density functional based study on the band structure of trioctahedral mica and its dependence on the variation of Fe2+ content
An efficient and stable lead-free organic–inorganic tin iodide perovskite for photovoltaic device: Progress and challenges
Ultra-broadband thermal radiator for daytime passive radiative cooling based on single dielectric SiO2 on metal Ag
Luminescent Copper (I) complexes as promising materials for the next generation of energy-saving OLED devices
Cathodes for Mg batteries: A condensed review
First-principles study for physical properties and stability of Li based chalcopyrite semiconductors: Reliable for green energy sources
Colloidal Synthesis of ZnS, CdS and Zn x Cd1−x S Nanoparticles from Zinc and Cadmium Thiobiuret Complexes
Physical Vapor Deposited [Co:Cd-(dtc)2]/SnO2 Dual Semiconductor Systems: Synthesis, Characterization and Photo-Electrochemistry
PVA/Gd2O3@ Zno Nanocomposite Films as New Uv-Blockers: Structure and Optical Revelations
Structural, Magnetic and Optical Properties Study of Tellurium-Based Perovskites: Sr3−xPbxFe2TeO9 (0 ≤ x ≤ 2.25)
Characterization of Cu2ZnSnSe4 Thin Films Selenized with Cu2-xSe/SnSe2/ZnSe and Cu/SnSe2/ZnSe Stacks
Effect of conductive additive amount on electrochemical performances of organic supercapacitors
Effects of the Mixing of an Active Material and a Conductive Additive on the Electric Double Layer Capacitor Performance in Organic Electrolyte
Halide perovskite materials as chemical playground
Experimental verification of optically optimized CuGaSe2 top cell for improving chalcopyrite tandems
Recrystallized thin-film silicon solar cell on graphite substrate with laser single side contact and hydrogen passivation
Solar cell fabricated on welded thin flexible silicon
Investigation on microstructures and thermo-physical properties of ferroelastic (Y1-xDyx) TaO4 ceramics
Anomalous thermal conductivity in amorphous niobium pentoxide thin films: A correlation study between structure and thermal properties
Mechanical property enhancements and amorphous thermal transports of ordered weberite-type RE3Nb/TaO7 high-entropy oxides
Efficiency enhancement in DIBSQ:PC71BM organic photovoltaic cells by using Liq-doped Bphen as a cathode buffer layer
Electrochemical and spectroelectrochemical characterization of different mesoporous TiO 2 film electrodes for the immobilization of Cytochrome c
High-brightness blue organic light emitting diodes with different types of guest-host systems
Multifunctional cantilevers as working elements in solid-state cooling devices
Impact of single pMOSFET dielectric degradation on NAND circuit performance
Biomimetic detoxifier Prunus cerasifera Ehrh. silver nanoparticles: innate green bullets for morbific pathogens and persistent pollutants
Congruously designed eco-curative integrated farming model designing and employment for sustainable encompassments
Evaluation of the catalytic oxidation of soot by CeOX-LaMnO3 at different O2 pressures synthesized by ultrasonic-assisted hydrothermal method
Magnetic nanoferromanganese oxides modified biochar derived from pine sawdust for adsorption of tetracycline hydrochloride
A novel strategy for water disinfection with a AgNPs/gelatin sponge filter
Growth and properties of hydrothermally derived crystalline ZnSe quantum dots
Foliar-mediated Ag: ZnO nanophotocatalysts: green synthesis, characterization, pollutants degradation, and in vitro biocidal activity
Phytofunctionalized silver nanoparticles: green biomaterial for biomedical and environmental applications
Systematic review elucidating the generations and classifications of solar cells contributing towards environmental sustainability integration
Sustainability consolidation via employment of biomimetic ecomaterials with an accentuated photo-catalytic potential: emerging progressions
Innovatory role of nanomaterials as bio-tools for treatment of cancer
Newfangled progressions in the charge transport layers impacting the stability and efficiency of perovskite solar cells
Synergistic mycoflora–natural farming mediated biofertilization and heavy metals decontamination of lithospheric compartment in a sustainable mode via Helianthus annuus
Lithosphere-stationed fate and eco-detoxification investigation of fungicidal agent Zoxamide possessing chlorinated benzamidic genesis
Carpogenic ZnO nanoparticles: amplified nanophotocatalytic and antimicrobial action
Physical vapor deposition of SnS: PbS-dithiocarbamate chalcogenide semiconductor thin films: elucidation of optoelectronic and electrochemical features
Influence of ZrO2 on the Physicochemical Properties of Phosphate-Based Glasses and Glass Ceramics
An efficient copper-catalyzed synthesis of 2-mercaptobenzothiazole through S-arylation/heterocyclization of 2-haloaniline with potassium xanthate
Helianthus annuus based biodiesel production from seed oil garnered from a phytoremediated terrain
Determining the adsorption and desorption behavior of thiabendazole fungicide for five different agricultural soils.
Role of renewable energy and nanotechnology in sustainable desalination of water: mini review
Multi-functional bio-sorbents triggered sustainable detoxification of eco-contaminants besmirched hydrospheric swatches
Biotechnological tools based lithospheric management of toxic Pyrethroid pesticides: a critical evaluation
Semi-conducting Ni/Zn nano-hybrids’ driven efficient electro-catalytic performance: fabrication, characterization, and electrochemical features’ elucidation
Doped antimony chalcogenide semiconductor thin films fabrication by physical vapour deposition: elucidation of optoelectronic and electrochemical features
Soft optical metamaterials
X-ray generation using carbon nanotubes
Modern coin debasement discovered by combined portable X‐ray fluorescence and atomic absorption spectroscopy in Peruvian cent coins (1950–1965)
Understanding the endocrine disruptor and determination of bisphenol A by functional Cu-BTABB-MOF/rGO composite as facile rapid electrochemical sensor: an experimental and DFT …
Microperoxidase-11 modified mesoporous SnO 2 film electrodes for the detection of antimalarial drug artemisinin
Simultaneous determination of trace Cd 2+ and Pb 2+ using GR/l-cysteine/Bi modified screen-printed electrodes
Effect of temperature on energy consumption and recovery rate of the reverse osmosis brackish systems in a different arrangement
Stability assessment of pin perovskite photovoltaic mini-modules utilizing different top metal electrodes
Structural Colors on Al Surface via Capped Cu-Si3N4 Bilayer Structure
Increasing depth penetration in biological tissue imaging using 808-nm excited Nd3+/Yb3+/Er3+-doped upconverting nanoparticles
Drug quantification in turbid media by fluorescence imaging combined with light-absorption correction using white Monte Carlo simulations
Solvation dynamics in room temperature ionic liquids: Dynamic Stokes shift studies of fluorescence of dipolar molecules
Monogalactopyranosides of fluorescein and fluorescein methyl ester:< i> S</i> ynthesis, enzymatic hydrolysis by biotinylated β-galactosidase and determination of translational …
A novel classification of prostate specific antigen (PSA) biosensors based on transducing elements
Compositional engineering of VOPcPhO-TiO2 nano-composite to reduce the absolute threshold value of humidity sensors
Application of chemometrics for detection and modeling of adulteration of fresh cow milk with reconstituted skim milk powder using voltammetric fingerpriting on a graphite/SiO2 …
Employment of electrochemically synthesized TGA–CdSe quantum dots for Cr3+ determination in vitamin supplements
Adsorption and preconcentration of divalent metal ions in fossil fuels and biofuels: Gasoline, diesel, biodiesel, diesel-like and ethanol by using chitosan microspheres and …
Improving data and prediction quality of high-throughput perovskite synthesis with model fusion
Topology Automated Force-Field Interactions (TAFFI): A Framework for Developing Transferable Force Fields
Nano-based PSA biosensors: an early detection technique of prostate cancer
A short analysis on the morphological characterization of colloidal quantum dots for photovoltaic applications
Graphitic Carbon Nitride-based Photocatalysts for Environmental Remediation of Organic Pollutants
Silver and palladium nanoparticle embedded poly(n-isopropylacrylamide-co-2-acrylamido-2-methylpropane sulfonic acid) hybrid microgel catalyst with pH and …
Carbonized waste milk powders as cathodes for stable lithium–sulfur batteries with ultra-large capacity and high initial coulombic efficiency
Impact of the structural parameters on the photoresponse of terahertz blocked-impurity-band detectors with planar structure
Interfacial electron transfer on cytochrome-c sensitised conformally coated mesoporous TiO2 films
Multipurpose, Fully Integrated 128  128 Event-Driven MD-SiPM With 512 16-Bit TDCs With 45-ps LSB and 20-ns Gating in 40-nm CMOS Technology
Updates from the SPADnet project (fully digital, scalable and networked photonic component for Time-of-Flight PET applications)
Bismuth and antimony-based oxyhalides and chalcohalides as potential optoelectronic materials
The origin of uniaxial negative thermal expansion in layered perovskites
EPIC STAR: a reliable and efficient approach for phonon-and impurity-limited charge transport calculations
A molecular roadmap towards organic donor-acceptor complexes with high-performance thermoelectric response
Ultralow lattice thermal conductivity of chalcogenide perovskite CaZrSe3 contributes to high thermoelectric figure of merit
Colloidal magnetic nanocrystal clusters: Variable length-scale interaction mechanisms, synergetic functionalities and technological advantages
Highly stable metal halide perovskite microcube anodes for lithium-air batteries
Novel magneto-electric multiferroics from first-principles calculations
Magneto-electric multiferroics: Designing new materials from first-principles calculations
Supramolecular approach in energy conversion devices
Photocatalytic Performance of Ta2O5/BiVO4 Heterojunction for Hydrogen Production and Methylene Blue Photodegradation

In [43]:
num = papers_df.duplicated('ManuscriptTitle').sum()
print(f'There are {num} duplicated citations')
print('Thats {:.2%} of the citations'.format(num/papers_df.shape[0]))

There are 1 duplicated citations
Thats 0.01% of the citations

Let's drop the duplicated papers.

In [44]:
papers_df = papers_df.drop_duplicates('ManuscriptTitle')

In [45]:
num = papers_df.duplicated('ManuscriptTitle').sum()
print(f'There are {num} duplicated citations')
print('Thats {:.2%} of the citations'.format(num/papers_df.shape[0]))

There are 0 duplicated citations
Thats 0.00% of the citations

We can also check if there are duplicated citations with the same `Year` `Cites` `query_ids` and authors

In [46]:
num = papers_df.duplicated(subset = ['Year','Cites','first_auth', 'second_auth', 'third_auth', 'PubTitle', 'query_id']).sum()
print(f'There are {num} duplicated citations')
print('Thats {:.2%} of the citations'.format(num/papers_df.shape[0]))

There are 10 duplicated citations
Thats 0.06% of the citations

Let's drop those duplicates.

In [47]:
papers_df = papers_df.drop_duplicates(['Year','Cites','first_auth', 'second_auth', 'third_auth', 'PubTitle', 'query_id'])

In [48]:
num = papers_df.duplicated(['Year','Cites','first_auth', 'second_auth', 'third_auth', 'PubTitle', 'query_id']).sum()
print(f'There are {num} duplicated citations')
print('Thats {:.2%} of the citations'.format(num/papers_df.shape[0]))

There are 0 duplicated citations
Thats 0.00% of the citations

Another thing we can check for is if there are additional duplicated papers based on the author list, that is, we can check if the titles in the `Title` column that are formatted differently.

In [49]:
# Find where a group of author names have more than one citation
def group_papers(group):
    if group['ManuscriptTitle'].count() > 1:
        print(group['ManuscriptTitle'])
        return  group['ManuscriptTitle'].count()
    else:
        return 0

j = 0 
for group_name, group in papers_df.groupby(['first_auth', 'second_auth', 'third_auth']):
    i = group_papers(group)
    j += i

3577    Carrier diffusion lengths in hybrid perovskite...
3609    Pyrochlore to Fluorite Transition The Y2(Ti1–x...
Name: ManuscriptTitle, dtype: object
13895    Role of surface texturization on the gassensin...
13898    Role of surface passivating ligand and growth ...
Name: ManuscriptTitle, dtype: object
6185    Controlled Mixed Violet–Blue–Red Electrolumine...
6210    Resonance energy transfer from rhodamine 6G to...
Name: ManuscriptTitle, dtype: object
6199    Surface DefectRelated Luminescence Properties ...
6212    Metal conjugated semiconductor hybrid nanopart...
Name: ManuscriptTitle, dtype: object
15121    Coaxial nanofibers outperform uniaxial nanofib...
15125    New Ideas for Understanding the Structure and ...
Name: ManuscriptTitle, dtype: object
14419    Reducing the interfacial voltage loss in tin h...
14453    Interface characterization of allperovskite ox...
Name: ManuscriptTitle, dtype: object
14421    Highly symmetric Lewis base coordinated with S...
14422    Halogen engineering of 2D/3D tin halide perovs...
14424    Stabilizing CsPbBr3 perovskite quantum dots on...
14430    Effects of Fe3+ substitution on ZnAl layered d...
14439    Excellent disinfection and fluoride removal us...
14440    Semitransparent organic solar cells with light...
14442    An efficient and durable perovskite electrocat...
14444    Highly efficient layerbylayer deposition solar...
14445    Optical enhancement of nonstoichiometryinduced...
14446    Review on recent progress in hydrothermally sy...
14451    Microfluidic synthesis of metalorganic framewo...
Name: ManuscriptTitle, dtype: object
14429    Superhydrophobic high impact polystyrene (HIPS...
14447    Achieving direct electrophoretically deposited...
Name: ManuscriptTitle, dtype: object
14431    Aqueous miscible organic solvent treated NiTi ...
14437    Lasing operation in the CsPbBr3 perovskite mic...
14443    Evaluation of the production of biohydrogen du...
Name: ManuscriptTitle, dtype: object
14423    Recent promise of leadfree halide perovskites ...
14441    On the surface passivating principle of functi...
Name: ManuscriptTitle, dtype: object
12582    Chlorides other Halides and Pseudo‐Halides as ...
12596    Design of C3N4‐Based Hybrid Heterojunctions fo...
Name: ManuscriptTitle, dtype: object
14789    A novel way to characterize metalinsulatormeta...
14790    Using amorphous ZincTin Oxide alloys in the em...
Name: ManuscriptTitle, dtype: object
6990    Electron degeneracy and intrinsic magnetic pro...
7005    Microstrain sensitivity of orbital and electro...
Name: ManuscriptTitle, dtype: object
8565    Examination of growth kinetics of copper rich ...
8577    Impedance spectroscopy analysis of small molec...
Name: ManuscriptTitle, dtype: object
8537    Photoinduced charge separation and electron di...
8567    Efficiency and stability enhancement of laserc...
Name: ManuscriptTitle, dtype: object
8507    Photon management of combining nanostructural ...
8571    Electrical properties of patterned photoactive...
Name: ManuscriptTitle, dtype: object
8566    Bufferfree Cu (In Ga) Se2solar cells by nearsu...
8575    Improvement of photovoltaic performance of per...
Name: ManuscriptTitle, dtype: object
6537    Understanding the helical wrapping of poly (3h...
6538    Appealing perspectives of hybrid lead–iodide p...
Name: ManuscriptTitle, dtype: object
12289    Highly luminescent columnar ZnO films grown di...
12365    Hybridstructured indium tin oxide with Ag nano...
Name: ManuscriptTitle, dtype: object
10932    Local structure and excitations in systems wit...
10937    Mechanical properties of monolayer sulphides a...
Name: ManuscriptTitle, dtype: object
8194    Structural and oxygentransport studies of doub...
8261    Reliability of 3D Cs 2 M+ M 3+ X 6 type absorb...
8293    Photonic crystal‐driven spectral concentration...
Name: ManuscriptTitle, dtype: object
8208    A facile way for scalable fabrication of silve...
8241    Identifying the electrocatalytic active sites ...
Name: ManuscriptTitle, dtype: object
12719    Morphological and structural changes in reduci...
12723    Evidence of Plasmonic Induced Photocatalytic H...
Name: ManuscriptTitle, dtype: object
17352    Effect of conductive additive amount on electr...
17356    Recrystallized thinfilm silicon solar cell on ...
17358    Investigation on microstructures and thermophy...
Name: ManuscriptTitle, dtype: object
11921    An Xray scattering and electron microscopy stu...
11989    Microscopic and spectroscopic investigation of...
Name: ManuscriptTitle, dtype: object
15590    Atomicscale understanding of dichlorobenzeneas...
15591    Indole moiety induced biological potency in ps...
Name: ManuscriptTitle, dtype: object
4408    Peroptronic devices perovskitebased lightemitt...
4409    Machine learningassisted development of organi...
Name: ManuscriptTitle, dtype: object
12612    Coupled Near‐and Far‐Field Scattering in Silve...
12614    Broadband‐Emitting 2 D Hybrid Organic–Inorgani...
Name: ManuscriptTitle, dtype: object
15620    Synthesis single crystal Xray DFT spectroscopi...
15623    Investigation of electronic structure magnetic...
Name: ManuscriptTitle, dtype: object
15617    Structural spectral magnetic and dielectric pr...
15619    Syntheses crystal structures topology and dual...
Name: ManuscriptTitle, dtype: object
5934    Exploring the Limiting Open‐Circuit Voltage an...
5940    Hole Transporting Materials Development of Dop...
Name: ManuscriptTitle, dtype: object
11453    Etching of high aspect ratio structures in Si ...
12659    Graphene quantum dots/NiTi layered double hydr...
Name: ManuscriptTitle, dtype: object
5684    Exchange‐Coupled Bimagnetic Wüstite/Metal Ferr...
5710    Interfacing BiVO4 with Reduced Graphene Oxide ...
Name: ManuscriptTitle, dtype: object
13343    An insight into the local Oh→ Td instability i...
13345    Pressuredriven Phase Transition in CaFeAsF at ...
Name: ManuscriptTitle, dtype: object
13340    Application of lowvoltage backscattered electr...
13342    Thermal activated carrier transfer between InA...
Name: ManuscriptTitle, dtype: object
11923    Electromechanical tuning of nanoscale MIM diod...
11984    Effect of boron on formation of interstitial‐r...
11985    PbS nanocrystals in hybrid systems for solar c...
Name: ManuscriptTitle, dtype: object
3545    Formation of unsaturated hydrocarbons and hydr...
3548    Fabrication and postmodification of nanoporous...
Name: ManuscriptTitle, dtype: object
8076    Anisotropic ionic conductivity in fluorinated ...
8114    Enhanced performance via partial lead replacem...
8120    Hexagonal perovskite related oxide ion conduct...
8123    Temporal and spatial pinhole constraints in sm...
8145    Photoinduced degradation of methylammonium lea...
Name: ManuscriptTitle, dtype: object
11667    Partial inverse spinel structure of manganesed...
11697    Studying the role of CdS on the TiO2 surface p...
Name: ManuscriptTitle, dtype: object
8694    Difference in hot carrier cooling rate between...
8723    Selective fluorescence functionalization of dy...
Name: ManuscriptTitle, dtype: object
8706    Infrared emitting quantum dots DNA conjugation...
8710    Washinduced multicolor tuning of carbon nanodo...
Name: ManuscriptTitle, dtype: object
11870       Sevenlayered 2D hybrid lead iodide perovskites
11955    The effect of reducing dimensionality on the e...
11972    Memristive devices based on solution‐processed...
11974    Effect of nanoscale confinement on fluorescenc...
Name: ManuscriptTitle, dtype: object
15725    Electroluminescence and fluorescence emission ...
15730    Nexus approach to solar technology for energy ...
Name: ManuscriptTitle, dtype: object
16445    Structural Volume Changes upon Photoisomerizat...
16446    Transient absorption of copper selenide nanowi...
16457    Spectral properties of organosilicon polymer/S...
Name: ManuscriptTitle, dtype: object
6687    Highly UV Resistant Inch‐Scale Hybrid Perovski...
6690    Stacking Polymorphism in PtSe2 Drastically Aff...
Name: ManuscriptTitle, dtype: object
8505    The influence of drift fields in thin silicon ...
8506    Passivated contacts to laser doped p+ and n+ r...
8562    Tapered aluminumdoped vertical zinc oxide nano...
Name: ManuscriptTitle, dtype: object
16451     Photophysics of poly (pphenylene vinylene) films
16458    Correlation of Degradation of P3HT PCBM And P3...
Name: ManuscriptTitle, dtype: object
8004    Solvent vapour annealing of methylammonium lea...
8019    Emerging polyanionic and organic compounds for...
Name: ManuscriptTitle, dtype: object
16541    Porous NiYSZ planar anodes by powder extrusion...
16547    Processing of P/M M2 high speed steels by moul...
16551    Development of thermoelectric oxides for renew...
Name: ManuscriptTitle, dtype: object
15362    Nonfused medium bandgap electron acceptors for...
15369    Dimensionality regulation in tin halide perovs...
Name: ManuscriptTitle, dtype: object
3974    Hexagonal boron nitride selflaunches hyperboli...
3992    Nanoscale Architecture of Polymer–Organolead H...
Name: ManuscriptTitle, dtype: object
17600    FtIr And Computational Study Of Di2Pyridyl Ket...
17603    Photoluminescent and photocatalytic behaviour ...
Name: ManuscriptTitle, dtype: object
17602    A highly effective superfluid film breaker for...
17605    Rheology of fumed silica/polydimethylsiloxane ...
Name: ManuscriptTitle, dtype: object
10828    Correction Interface structure precursor rheol...
10882    Germanium coating boosts lithium uptake in Si ...
Name: ManuscriptTitle, dtype: object
14001    Generalised single particle models for highrat...
14068    The anomalous quasi isotropic [g] tensor found...
14069    Optical properties due to Cr4+ in oxides Densi...
14071    Magnetic properties of R3Rh2 compounds with R=...
Name: ManuscriptTitle, dtype: object
11838    Magneto‐optical Properties of Iron Oxide Nanoc...
11847    Dielectric and Raman spectroscopy measurements...
11930    Nanostructured Nbsubstituted CaMnO3 ntype ther...
Name: ManuscriptTitle, dtype: object
12021    Ionic Liquid‐Mediated α‐Fe2O3 Shape‐Controlled...
12035    Characterization of Charge States in Conductin...
Name: ManuscriptTitle, dtype: object
12000    InGaP//GaAs//CIGS 3‐junction spectrum‐splittin...
12003    Effect of inverted‐pyramid shape on light extr...
Name: ManuscriptTitle, dtype: object
11999    Excitonic and Free Carrier Recombination in In...
12002    Photoluminescence characteristics of organic m...
Name: ManuscriptTitle, dtype: object
10923    Excited state dynamics of BODIPYbased acceptor...
10929    Low electronpolar optical phonon scattering as...
Name: ManuscriptTitle, dtype: object
10323    Design of dendritic core carbazolebased hole t...
10328    Acidfunctionalized fullerenes used as interfac...
10363    Selfhealable electrochromic ion gels for low p...
10374    A simple engineering strategy with side chain ...
Name: ManuscriptTitle, dtype: object
5740    Low‐temperature‐processed colloidal quantum do...
5743    Editorial for the special issue Dimensionality...
Name: ManuscriptTitle, dtype: object
14584    Dry and wet etch processes for NiMnSb Heusler ...
14599    (Ln0. 5M0. 5) FeO3− δ Perovskites as Cathode f...
Name: ManuscriptTitle, dtype: object
10524    Charge injection and trapping at perovskite in...
10546    Rareearth quantum cutting in metal halide pero...
Name: ManuscriptTitle, dtype: object
4254    Pattern Formation of Silver Nanoparticles in 1...
4268    Switched‐On Progress Challenges and Opportunit...
4294    Hybrid Silicon‐Polymer Photodetector Engineere...
Name: ManuscriptTitle, dtype: object
13939    Green lightemitting diodes based on hybrid per...
13940             Plasmonic communications light on a wire
Name: ManuscriptTitle, dtype: object
13950    Ultrafast characterization of the electron inj...
13951    αFAPbI3 powder presynthesized by microwave irr...
Name: ManuscriptTitle, dtype: object
16158    Perovskite/polyethylene oxide composites Towar...
16163    Preparation sintering and electrochemical perf...
16166    The rattler effect of phonon propagation in de...
Name: ManuscriptTitle, dtype: object
674    Charge separation in type II tunneling multila...
702    Triazatruxenebased Hole Transporting Materials...
Name: ManuscriptTitle, dtype: object
13777    Yttrium (Y) doped ZnO nanowire/pSi heterojunct...
13781    Defectinduced magnetism in undoped wide band g...
13828    Magnetic and electronic properties of transiti...
13863    Environmentinduced reversible modulation of op...
Name: ManuscriptTitle, dtype: object
15718    Light induced damage and repair in nucleic aci...
15723    Improved power conversion efficiency for bulk ...
Name: ManuscriptTitle, dtype: object
8053    Lightinduced degradation of fullerenes in orga...
8084    Investigation of the photocorrosion of nGaP ph...
Name: ManuscriptTitle, dtype: object
14121                       Lithium insertion in La2MiO4+y
14133    An advance towards the synthesis of Ag nanorod...
Name: ManuscriptTitle, dtype: object
4968     TlP 5 an unexplored direct band gap 2D semicon...
16962    Synthesis characterization and optoelectronic ...
Name: ManuscriptTitle, dtype: object
5011    Porosity induced rigidochromism in platinum (i...
5058    Cadmium deoxycholate a new and efficient precu...
Name: ManuscriptTitle, dtype: object
4970     Novel IV–V–VI semiconductors with ultralow lat...
16963    Various coordination modes in mercury (II) com...
Name: ManuscriptTitle, dtype: object
16301    A comparative study on the performance of hybr...
16320    ZnO Nanoparticles Photosensitization Using Rut...
Name: ManuscriptTitle, dtype: object
16325    Electronic and magnetic properties of X2YZ and...
16326    Compensated half metallicity in osmium double ...
Name: ManuscriptTitle, dtype: object
10081    Timeresolved luminescence in conducting polyme...
10082    Production of nanometersize GaAs nanocristals ...
10092    Recent advances on the optical properties of E...
Name: ManuscriptTitle, dtype: object
15436    Perovskitelike ceramic hole transport material...
15453    Multifunctional highly efficient bipolar 9 9di...
Name: ManuscriptTitle, dtype: object
15431    Highperformance CsPbI3 perovskite solar cells ...
15489    Crystal Structures and PhaseTransitions Analys...
Name: ManuscriptTitle, dtype: object
15459    Interpenetrated Double PillaredLayer CoII MOFs...
15460    Endocyclic and Endo–Exocyclic Silver (i) Compl...
Name: ManuscriptTitle, dtype: object
12996    A nonvolatile memory device consisting of grap...
13003    Magnetic separation of colloidal nanoparticle ...
13006    Atomefficient synthesis of a benchmark electro...
13007    Core–shell structured TiO2@ polydopamine for h...
Name: ManuscriptTitle, dtype: object
8903    PLASMAS AND ELECTRICAL DISCHARGES (PACS 5152)M...
8904    Impedance spectroscopy of thinfilm CdTe/CdS so...
Name: ManuscriptTitle, dtype: object
1736    Defect Engineering Stabilized AgSbTe2 with Hig...
9354    Managing Phase Purities and Crystal Orientatio...
Name: ManuscriptTitle, dtype: object
16591    Cubic garnet solid polymer electrolyte for roo...
16596    Synthesis and physical properties of nanopowde...
Name: ManuscriptTitle, dtype: object
836     High Gravimetric and Volumetric Ammonia Capaci...
1023    Band engineering in core/shell ZnTe/CdSe for p...
Name: ManuscriptTitle, dtype: object
16104    Structural Chemistry of a New 10H Hexagonal Pe...
16113    Transition metal impurities in fluorides Role ...
16127    Optoelectronic properties of graphene quantum ...
Name: ManuscriptTitle, dtype: object
16136    Compatibility of DFT+ U with noncollinear magn...
16137    Efficacious symmetryadapted atomic displacemen...
Name: ManuscriptTitle, dtype: object
16106    Squeezing resulting from a fourthorder interac...
16114    Halide anions driven selfassembly of haloperfl...
Name: ManuscriptTitle, dtype: object
16078    Carrier signal injection alternatives for sens...
16107    Squeezing enhancement by competing nonlinearit...
Name: ManuscriptTitle, dtype: object
16546    Structure and mechanical properties of HSS HS6...
16549    Structure and reaction with lithium of tetrago...
16550    Thermal and mechanical characterization of inj...
Name: ManuscriptTitle, dtype: object
16542    Magnetic properties of Mgferrite after milling...
16548    Mechanical properties and pitting corrosion be...
Name: ManuscriptTitle, dtype: object
14692    Microplasmas technologies for engineering of s...
14701    Metal ion enhanced charge transfer in a terpyr...
Name: ManuscriptTitle, dtype: object
11493    Atomic layer deposition of germaniumseleniumte...
11575    Structural evolution of molybdenum disulfide p...
Name: ManuscriptTitle, dtype: object
11536    Determination of Carrier Diffusion Length Usin...
11578    Förster Resonance Energy Transfer Mediated Ch...
Name: ManuscriptTitle, dtype: object
11474    Tin dioxide as an alternative window layer for...
11476    Preface for the special topic collection comme...
11478                             Sixty years of diversity
11488    Atomic layer deposition of molybdenum disulfid...
11537            Ferromagnetism in 57Fe‐doped cupric oxide
11539              Nanowire–quantum‐dot–polymer solar cell
11542    Ab initio study of structural electronic elast...
11544    Dynamically Switching the Electronic and Elect...
11547    Inhomogeneous Broadening of Photoluminescence ...
11549    Graphene Membranes for Hall Sensors and Microp...
11554    Facile Deposition of Nb2O5 Thin Film as an Ele...
11555    Nitrogendoped graphene oxide electrocatalysts ...
11557    Heteroleptic NIREmitting YbIII/AnilateBased Ne...
11558    ColorTunable AllInorganic CsPbBr3 Perovskites ...
11561    Surface Functionalization of CsPbBr3 Νanocryst...
11649    Study of the La1/2+ 1/2xLi1/21/2xTi1xAlxO3 (0≤...
11651    Structural characterization and EXAFS wavelet ...
11661    Controlled synthesis of zerodimensional phasep...
Name: ManuscriptTitle, dtype: object
6551    Uncovering the SelfOrganized Nanowires on AuMo...
6608    Phase diagram of methylammonium/formamidinium ...
Name: ManuscriptTitle, dtype: object
17294        Spectrophotometric determination of hydrazine
17312    Elucidating DFT study on structural electronic...
Name: ManuscriptTitle, dtype: object
1192    Tracking photoexcited carriers in hybrid perov...
8822    Longitudinal carrier density profiling in semi...
Name: ManuscriptTitle, dtype: object

5227    Solvents for Processing Stable Tin Halide Pero...
5233    SizeDependent Lattice Structure and Confinemen...
Name: ManuscriptTitle, dtype: object
5184    Impact of layer thickness on the charge carrie...
5185    Degradation of highly alloyed metal halide per...
Name: ManuscriptTitle, dtype: object
5209    Improved morphology and efficiency of n–i–p pl...
5235    Suppressing cation migration in triplecation l...
Name: ManuscriptTitle, dtype: object
5219    Tailoring phase purity in the 2D/3D perovskite...
5220    Efficient exciton diffusion in organic bilayer...
Name: ManuscriptTitle, dtype: object
5226    Mesoporous electronselective contacts enhance ...
5234    Enhanced OpenCircuit Voltage of WideBandgap Pe...
Name: ManuscriptTitle, dtype: object
10645    Sputtered Zn (O S) for junction formation in c...
10646    Unambiguous Determination of Local Orientation...
10647    Facile Synthesis of NaBiS2 Nanoribbons as a Pr...
Name: ManuscriptTitle, dtype: object
5880    Effect of precursor solution aging on the crys...
5891    New Generation Hole Transporting Materials for...
Name: ManuscriptTitle, dtype: object
6000    A Smooth CH3NH3PbI3 Film via a New Approach fo...
6002    Exciton and Charge Carrier Dynamics in Highly ...
Name: ManuscriptTitle, dtype: object
13085    Disorder and polymorphism in Cu (ii)polyoxomet...
13088    Molecular crystals of 2amino1 3 4thiadiazole w...
Name: ManuscriptTitle, dtype: object
13272    First proofofprinciple of inorganic lead halid...
13274    Electrical and Optical Characterization of CsP...
Name: ManuscriptTitle, dtype: object
4170    Single component organic solar cells based on ...
4175    Epitaxial Metal Halide Perovskites by Inkjet‐P...
Name: ManuscriptTitle, dtype: object
5108     Halide segregation versus interfacial recombin...
11107    Efficient bandgap widening in coevaporated MAP...
Name: ManuscriptTitle, dtype: object
1461    Perovskite Solar Cells Low‐Dimensional Perovsk...
1470    Choose your own adventure fabrication of monol...
Name: ManuscriptTitle, dtype: object
5434     Synthesis and optical properties of thiolstabi...
10035    Photocatalytic Production of Vanillin over CeO...
Name: ManuscriptTitle, dtype: object
12527    The effects of hydroxyl by water addition on t...
12533    AFM studies on formation of new phase responsi...
Name: ManuscriptTitle, dtype: object
12529    Ultraviolet upconversion luminescence enhancem...
12534    Lightemitting diodes based on quaternary CdZnS...
Name: ManuscriptTitle, dtype: object
12525    Tenfold increase in efficiency from a referenc...
12538    Thermally activated delayed fluorescence of bi...
Name: ManuscriptTitle, dtype: object
448     Tuning structural isomers of phenylenediammoni...
8818    Luminescent properties and electronic structur...
Name: ManuscriptTitle, dtype: object
762     “Magnetinthesemiconductor” FePt− PbS and FePt−...
1045    Hightemperature–shorttime annealing process fo...
Name: ManuscriptTitle, dtype: object
7265    Analysis of diamond nanocrystal formation from...
7296    Benchmark study for the application of density...
Name: ManuscriptTitle, dtype: object
1798    Photonic Synapses Retina‐Inspired Carbon Nitri...
1900    Photoprotection in metal halide perovskites by...
Name: ManuscriptTitle, dtype: object
245    Industry outlook of perovskite quantum dots fo...
286    Colloidal quantumdot lightemitting diodes with...
Name: ManuscriptTitle, dtype: object
6101     Chlorineassisted sizecontrolled synthesis and ...
13111    Broadband antireflection with halide perovskit...
Name: ManuscriptTitle, dtype: object
522      Giant tunnelling electroresistance in metal/fe...
13113    Reconfigurable Near‐field Enhancement with Hyb...
Name: ManuscriptTitle, dtype: object
242      Tracking the dynamics of circulating tumour ce...
13110    All‐Optical Nanoscale Heating and Thermometry ...
Name: ManuscriptTitle, dtype: object
13129    Nanoscale hydrodynamic instability in a molten...
13130    Surface ablation оf aluminum and silicon by ul...
Name: ManuscriptTitle, dtype: object
6143     Opencircuit voltage limitation in lowbandgap d...
13112    Direct Imprinting of Laser Field on Halide Per...
Name: ManuscriptTitle, dtype: object
3915     Nonequilibrium thermodynamics of charge separa...
13115    Optically Reconfigurable Spherical Ge‐Sb‐Te Na...
Name: ManuscriptTitle, dtype: object
6222     Energy transfer between confined dye and surfa...
13131    Ultrafast electron dynamics on the silicon sur...
Name: ManuscriptTitle, dtype: object
1200     Unusual activity of rationally designed cobalt...
12939    Synthesis of Cu 2 ZnSnS 4 thin films directly ...
Name: ManuscriptTitle, dtype: object
11418    Noninvasive Subsurface Electrical Probe for En...
11529    Coupling with the Jahn‐Teller mode for triplet...
Name: ManuscriptTitle, dtype: object
12275    New polymer matrix system for phosphorescent o...
12375    Detailed simulation of the role of functionali...
Name: ManuscriptTitle, dtype: object
8497    Silicon heterojunction solar cells with electr...
8499                         Flexible silicon solar cells
9706    Strong blue photoluminescence from singlecryst...
Name: ManuscriptTitle, dtype: object
2499    Twodimensional  photonic crystal membrane lase...
9817    Advances and challenges in tin halide perovski...
Name: ManuscriptTitle, dtype: object
2517    Polymer defect states modulate opencircuit vol...
6962    Giant optical polarization rotation induced by...
Name: ManuscriptTitle, dtype: object
8465    Dynamic modeling of combined concentrating sol...
9694    Oxygen vacancy dynamics in Pt/TiOx/TaOy/Pt mem...
Name: ManuscriptTitle, dtype: object
8463    Effective Ca2+doping in Sr1xCaxFeO3δ oxygen ca...
9693    Surface deformations as a necessary requiremen...
Name: ManuscriptTitle, dtype: object
11943    Toward high volume solution based rolltoroll p...
11977    Fluorescence quenching in porous silicon/conju...
12042    Thermoelectric oxide modules (TOMs) for the di...
Name: ManuscriptTitle, dtype: object
15131    Copolymers Comprising 2 7‐Carbazole and Bis‐be...
15135    Frontispiece Lights and Shadows of DMSO as Sol...
Name: ManuscriptTitle, dtype: object
1951    Perovskite ink with wide processing window for...
2088    Comparing multiple exciton generation in quant...
Name: ManuscriptTitle, dtype: object
2021         LightEmitting Halide Perovskite Nanoantennas
2138    Phonon interaction and phase transition in sin...
Name: ManuscriptTitle, dtype: object
16573    Structure and properties of HS652 type HSS man...
16601    Copper metallopolymer catalyst for the electro...
16607    Tradeoff analysis of C12A7 e− deposition techn...
Name: ManuscriptTitle, dtype: object
16566    Electrochemical and structural characterizatio...
16599    Using MetalOrganic Framework HKUST1 for the Pr...
Name: ManuscriptTitle, dtype: object
16597    Synthesis and characterization of novel anion ...
16600    Melamine foams decorated with insitu synthesiz...
16608    Stationkeeping of a highaltitude balloon with ...
Name: ManuscriptTitle, dtype: object
10615    Preparation and photophysical properties of na...
10616    Toward the stabilization of perovskite phase a...
Name: ManuscriptTitle, dtype: object
13595    KINETICS; ATMOSPHERIC AND ENVIRONMENTAL PHYSIC...
13602    MOLECULAR STRUCTURE BONDING QUANTUM CHEMISTRY ...
13603    MOLECULAR STRUCTURE BONDING QUANTUM CHEMISTRY ...
Name: ManuscriptTitle, dtype: object
12008    Template‐Free Macro‐Mesoporous TiO2/Carbon Nit...
12030    Investigation of Activated‐Carbon‐Supported Co...
Name: ManuscriptTitle, dtype: object
13367    Ultrasmall Quantum Dots A Tool for in Vitro an...
13370    A Study on the Emergence of PType Behaviour in...
Name: ManuscriptTitle, dtype: object
10732    Interfacial degradation in organic optoelectro...
10755    A radiation sensitive hybrid polymer based on ...
Name: ManuscriptTitle, dtype: object
16654    Phase transitions in titanium diselenide inter...
16661    Search for Pnma materials with hightemperature...
Name: ManuscriptTitle, dtype: object
16655    Highpressure hightemperature synthesis of Cr2O...
16660    Crystal structure and thermal expansion of Mn1...
16662    Crystal growth and twinned crystal structure o...
16663    Modecrystallography analysis and magnetic stru...
16664    Cation distribution in Cu2ZnSnSe4 Cu2FeSnS4 an...
16667    Effect of Fe doping on structure and magnetotr...
16668    Electronic structure magnetic mechanical and t...
16672    Insight into pressure tunable structural elect...
Name: ManuscriptTitle, dtype: object
7102    Molecularmediated assembly of silver nanoparti...
7103    Formation of complex nanostructures driven by ...
Name: ManuscriptTitle, dtype: object
6955    Deaging and asymmetric energy landscapes in el...
6956    Individual Barkhausen pulses of ferroelastic n...
Name: ManuscriptTitle, dtype: object
8891    Infrared detection of hydrogengenerated free c...
8909    Bandgap engineering of layered monochalcogenid...
Name: ManuscriptTitle, dtype: object
2066    Fermi Level of Surface States in TiO2 Nanopart...
2071    Lowthreshold blue quasi2D perovskite laser thr...
Name: ManuscriptTitle, dtype: object
1122     MicrocarrierAssisted inorganic shelling of lea...
13464    Thiocyanate‐and Thiol‐Functionalized p‐Doped Q...
Name: ManuscriptTitle, dtype: object
1211    Effect of Electron–Hole Overlap and Exchange I...
8823    UV∕ ozone treated Au for airstable low hole in...
Name: ManuscriptTitle, dtype: object
5930    A universal interface layer based on an amine‐...
5941    Determining Structure‐Activity Relationships i...
Name: ManuscriptTitle, dtype: object
6535    Revealing structure reactivity relationships i...
6615    Automatic prediction of surface phase diagrams...
Name: ManuscriptTitle, dtype: object
1590    Perovskite Solar Cells Surface Ligand Manageme...
1596    Controlling the interaction of light with poly...
Name: ManuscriptTitle, dtype: object
17268    Exploring the Constructive Alignment of Pedago...
17270    ReExamination of the Structure of Sr2 (MgTe) O...
Name: ManuscriptTitle, dtype: object
4511    kSpace Hyperspectral Imaging by a Birefringent...
4528    Spectralstable blue emission from moisturetrea...
Name: ManuscriptTitle, dtype: object
7080     Electrically tunable Berry curvature and stron...
7082     Vitality surveillance at distance using thinfi...
13916    Device performance and light characteristics s...
Name: ManuscriptTitle, dtype: object

3072    Turning Detrimental Effect into Benefits Enhan...
3164    Tuning the Optoelectronic Properties of Hybrid...
Name: ManuscriptTitle, dtype: object
4359     Bifunctional interfaces by poly (ionic liquid)...
17175    First example of the formation of a Si–C bond ...
Name: ManuscriptTitle, dtype: object
16265    Role of dopant cations in the gelation behavio...
16276    Highly sensitive detection and removal of merc...
Name: ManuscriptTitle, dtype: object
16266                   Solgel preparation of silica glass
16268    Study of energy bands and magnetic properties ...
Name: ManuscriptTitle, dtype: object
10450    Specific heat and thermodynamic functions for ...
10488    Graphenebased technologies for energy applicat...
Name: ManuscriptTitle, dtype: object
174    Efficient charge generation by relaxed charget...
218    Phonon coherences reveal the polaronic charact...
Name: ManuscriptTitle, dtype: object
1172      Single Trap States in Single CdSe Nanoplatelets
8757    A protected excitationenergy reservoir for eff...
Name: ManuscriptTitle, dtype: object
1135    Anticorrelation between local photoluminescenc...
8747    Morphological and chemical transformations of ...
Name: ManuscriptTitle, dtype: object
1987    Highefficiency colloidal quantum dot photovolt...
2027    Stimulated Raman scattering from Mieresonant s...
Name: ManuscriptTitle, dtype: object
8937    Thermal stability and interfacial properties o...
8938    Ferroelectric thin films Review of materials p...
Name: ManuscriptTitle, dtype: object
8621     Large area nanopatterning of alkylphosphonate ...
14266    Detailed chemical mechanism of the phase trans...
Name: ManuscriptTitle, dtype: object
8067    Molecular aggregation method for perovskite–fu...
8111    Lowcost coenzyme Q10 as an efficient electron ...
Name: ManuscriptTitle, dtype: object
2821    Optically excited multiband conduction in LaAl...
2837    Switchable and tunable film bulk acoustic reso...
Name: ManuscriptTitle, dtype: object
992    Singlemode lasing from imprinted halideperovsk...
994    Gallium phosphide nanowires in a freestanding ...
Name: ManuscriptTitle, dtype: object
4945    Luminance efficiency rolloff mechanism in CsPb...
4947    Mechanochemical synthesis of onedimensional (1...
Name: ManuscriptTitle, dtype: object
14148    Fabrication and Characterization of Dye sensit...
14180    Hydrothermal treatment for the marked structur...
14190    Deposition of iron sulfide thin films by AACVD...
Name: ManuscriptTitle, dtype: object
14016    Influence of impurities on the luminescence of...
14074    Electronic and optical properties of double pe...
Name: ManuscriptTitle, dtype: object
16503    Highly sensitive watersoluble fluorescent pH s...
16504    Perylene bisimide dyes with up to five indepen...
Name: ManuscriptTitle, dtype: object
14661    Structural modifications induced in silicate g...
14667      The mechanism of glass foaming with water glass
Name: ManuscriptTitle, dtype: object
10195    Solvent free synthesis of nanocrystalline hexa...
10257              Inkjet printing of 2D layered materials
Name: ManuscriptTitle, dtype: object
4042    Tuning the Work Function of Polar Zinc Oxide S...
4043    Correlated Donor/Acceptor Crystal Orientation ...
Name: ManuscriptTitle, dtype: object
10443    Xray powder diffraction results for the phase ...
10445    Highpressure Raman study of the Sr2CaWO6 doubl...
Name: ManuscriptTitle, dtype: object
6158     Transition from Photoconductivity to Photovolt...
13442    Procedure Based on External Quantum Efficiency...
Name: ManuscriptTitle, dtype: object
10738    Aggregation and structural study of the monola...
10739    Synthesis and photophysical studies of an indi...
10743    Effects of bovine serum albumin on light activ...
10746    Passivation by pyridineinduced PbI 2 in methyl...
Name: ManuscriptTitle, dtype: object
15401    Modeling and simulation of bifacial perovskite...
15467    Self‐assembly Behavior of Metal Halide Perovsk...
Name: ManuscriptTitle, dtype: object
7407    Origin of the different color of ruby and emerald
7421    Internal electric fields and color shift in Cr...
Name: ManuscriptTitle, dtype: object
7577     CHEMICAL CONTROL OF HOLEDOPED SUPERCONDUCTIVIT...
15641    Characterization of recombination properties a...
Name: ManuscriptTitle, dtype: object
2328    Organic molecular films on gold versus conduct...
2330    Correlation between interface energetics and o...
Name: ManuscriptTitle, dtype: object
8081    Thermal annealing reduces geminate recombinati...
8094    Fundamentals of tin iodide perovskites a promi...
8124    Facile preparation of nitrogendoped nanostruct...
Name: ManuscriptTitle, dtype: object
10651    Stability issues of the next generation solar ...
10652    The Role of Potassium in the Segregation of MA...
Name: ManuscriptTitle, dtype: object
15447    Design of donoracceptor small molecules based ...
15452    Diketopyrrolopyrrole pigment core@ multilayer ...
Name: ManuscriptTitle, dtype: object
9971    2Methylimidazole as an interlayer for the enha...
9976    High mass loading additivefree LiFePO4 cathode...
Name: ManuscriptTitle, dtype: object
9968    Properties of zirconia thin layers elaborated ...
9969    Graphene quantum dots decorated TiO2 mesoporou...
Name: ManuscriptTitle, dtype: object
3803    Crystal Orientation and Grain Size Do They Det...
3807    Crystal orientation drives the interface physi...
Name: ManuscriptTitle, dtype: object
10141    Theoretical study of the magnetic anisotropy a...
10176    Polarizationdependence in multiquantum well la...
Name: ManuscriptTitle, dtype: object
5608    Catalyzed microwaveassisted preparation of car...
5611    Effect of Various Deep Eutectic Solvents on th...
Name: ManuscriptTitle, dtype: object
15905    Electric‐field‐induced domain switching and do...
15910    Piezoelectric softening by Nb substitution in ...
Name: ManuscriptTitle, dtype: object
12348    Ab initio calculation of electronic transport ...
12380    Constraints in postsynthesis ligand exchange f...
Name: ManuscriptTitle, dtype: object
17157    Fabricating SnO2 and Cu2O anchored on gC3N4 na...
17160    High ensemble concentration of photostable NV ...
17162    Chemical targets to deactivate biological and ...
Name: ManuscriptTitle, dtype: object
15271          Grainsizeinduced ferroelectricity in NaNbO3
15278    Revealing the impact of acceptor dopant type o...
Name: ManuscriptTitle, dtype: object
12093    Phenylenevinylene Block Copolymers via Ring‐Op...
12143    Synthesis and electroluminescence properties o...
Name: ManuscriptTitle, dtype: object
14517    Elastic and dielectric measurements of the str...
14530    Characterization of laserdoped localized pn ju...
Name: ManuscriptTitle, dtype: object
16068    Electric field induced relaxor behavior in ani...
16072    A study on the control design of nonisolated c...
Name: ManuscriptTitle, dtype: object
15376    Enhancing the stability of planar perovskite s...
15377    Achieving exceptional activity and durability ...
Name: ManuscriptTitle, dtype: object
2734    Design of highperformance memristor cell using...
2759    Temperaturedependent leakage current character...
Name: ManuscriptTitle, dtype: object
4563    Impact of photon recycling grain boundaries an...
4566    Plasmonmodulated photoluminescence of single g...
Name: ManuscriptTitle, dtype: object
12411    Aggregation of anthraquinone dye molecules in ...
12414    Synthesis of highly conductive titanium suboxi...
Name: ManuscriptTitle, dtype: object
16382     Renaissance of tin halide perovskite solar cells
16390    Influence of lignite fly ash on the structural...
Name: ManuscriptTitle, dtype: object
763     Threedimensional nanocrystal superlattices gro...
5502    Silicon nanoparticles a new and enhanced opera...
5507    RF magnetron sputtering processed transparent ...
5508    Influence of Li doping on structural electrica...
Name: ManuscriptTitle, dtype: object
15143    Red shift in optical excitations on layered co...
15144       The Weak 3D Topological Insulator Bi12Rh3Sn3I9
Name: ManuscriptTitle, dtype: object
1970     Perovskite solar cells Different facets of per...
16039    Pseudo Jahn–Teller origin of ferroelectric ins...
Name: ManuscriptTitle, dtype: object
6970    Cannelli Cantelli and Cordero replyPower laws ...
6971    Magnetism and correlations in fractionally fil...
Name: ManuscriptTitle, dtype: object
2425       Optical characterization of disordered  alloys
2610    Gettering of Au to dislocations and cavities i...
Name: ManuscriptTitle, dtype: object
15865    SpectrallySelective Photonic Structures for PV...
15866    Concentrating Solar Power Advances in Geometri...
Name: ManuscriptTitle, dtype: object
11980    Electronic and Ionic Electric Field Screening ...
12009    Three‐dimensional amorphous silicon solar cell...
Name: ManuscriptTitle, dtype: object
559    Pressure driven rotational isomerism in 2D hyb...
560    Unlocking surface octahedral tilt in twodimens...
562    Orientation dependent molecular electrostatics...
Name: ManuscriptTitle, dtype: object
405    Carrier separation and transport in perovskite...
684    Importance of the donor fullerene intermolecul...
685    Molecular design of semiconducting polymers fo...
Name: ManuscriptTitle, dtype: object
3213    Highly Luminescent WS2 Quantum Dots/ZnO Hetero...
3227    Facile Strategy for Third Component Optimizati...
3233    LowTemperature TiOx Compact Layer for Planar H...
Name: ManuscriptTitle, dtype: object
3057    Bifacial colortunable semitransparent perovski...
3074    Chlorinedoped perovskite oxide a platinumfree ...
Name: ManuscriptTitle, dtype: object
7868     Luminescence of Ce3+ in Y2SiO5 nanocrystals Ro...
15059    Metal halide perovskite toxicity effects on Ar...
Name: ManuscriptTitle, dtype: object
12340    Biastemperature instability on the back gate o...
12434    Interfacial Structure Modifying Interlayers Eq...
Name: ManuscriptTitle, dtype: object
12294    Photoluminescence properties of nanocrystallin...
12385    Ligandexchange dependent properties of hybrid ...
Name: ManuscriptTitle, dtype: object
11454    Effect of  addition on surface reactions durin...
11457    Low temperature plasma deposition of silicon n...
Name: ManuscriptTitle, dtype: object
3560     Amorphous molybdenum phosphide nanoparticles f...
16009    Crack detection sensor layout and bus configur...
Name: ManuscriptTitle, dtype: object
14134    Silver oxide nanoparticles synthesized by gree...
14143    Structural optical and Raman studies of Co3O4 ...
16925    Theoretical investigation of ternary semicondu...
Name: ManuscriptTitle, dtype: object
5115    Revealing fundamental efficiency limits of mon...
6960    Class of molecular and solid state systems wit...
Name: ManuscriptTitle, dtype: object
16932    Lowtemperature solid oxide fuel cells based on...
16937    Synthesis morphology and optical properties of...
Name: ManuscriptTitle, dtype: object
5937    Resolving a critical instability in perovskite...
5939    Development of dopant‐free organic hole transp...
Name: ManuscriptTitle, dtype: object
14721    Comparison of nickel titanate (NiTiO3) powders...
14722    Hydrothermally synthesized urchinlike NiO nano...
Name: ManuscriptTitle, dtype: object
2254    Catalyst synthesis under CO2 electroreduction ...
2273    Author Correction Dopantinduced electron local...
Name: ManuscriptTitle, dtype: object
2277    Mechanically controlled quantum interference i...
2279                    A handle on charge reorganization
Name: ManuscriptTitle, dtype: object
2256    Constraining CO coverage on copper promotes hi...
2272    Reagentless biomolecular analysis using a mole...
Name: ManuscriptTitle, dtype: object
8024    Effective defect passivation with a designer i...
8177    Perovskite nanostructures for photovoltaic and...
Name: ManuscriptTitle, dtype: object
12936    Cu 2 ZnSnS 4 nanocrystal dispersions in polar ...
12937    Synthesis of singlecrystalline anatase nanorod...
Name: ManuscriptTitle, dtype: object
2436    Characteristics of ultraviolet photoluminescen...
6951    SelfOrganized Formation of Compositionally Mod...
Name: ManuscriptTitle, dtype: object
17285    Hydrogen Bonding in the Water Stabilized Struc...
17289    Fabrication and characterization of Nidecorate...
Name: ManuscriptTitle, dtype: object
12852    Reply to “Structural and magnetic behavior of ...
12902    Some unsymmetrical nickel 1 2dithiolene comple...
Name: ManuscriptTitle, dtype: object
12886    Light emitting diodes based on blends of quasi...
12906    Reinspection of formation of BiFe1xMnxO3 solid...
Name: ManuscriptTitle, dtype: object
11523    Nernst–Ettingshausen and magnetoresistance eff...
11636    Depolarization of ferroelectric materials meas...
Name: ManuscriptTitle, dtype: object
10804    Vibrational and electronic peculiarities of Ni...
10819    Temperatureinduced work function changes in Mn...
Name: ManuscriptTitle, dtype: object
10342    Realizing 17.0% external quantum efficiency in...
10354    Sidegroup engineering The influence of norborn...
Name: ManuscriptTitle, dtype: object
13266    Perovskite Nanostructures From Material Design...
13268    Conjugates of Ultrasmall Quantum Dots and Acri...
Name: ManuscriptTitle, dtype: object
14647    Introduction of crystalline highk gate dielect...
14649    Interpretation of the critical length scale de...
14656    NonDebye conductivity relaxation in the nonArr...
Name: ManuscriptTitle, dtype: object
14898    Electrical and structural functionality of CIG...
14924    Evaluating Intrinsic Defects Across CIGS Absor...
Name: ManuscriptTitle, dtype: object
12574    Efficient and robust reforming catalyst in sev...
12586    Organic linker defines the excited‐state decay...
12595    Highly Soluble Benzo [ghi] perylenetriimide De...
Name: ManuscriptTitle, dtype: object
2392    Spectral properties of resonantcavity polyfluo...
2394    Device degradation of polymer light emitting d...
Name: ManuscriptTitle, dtype: object
8046    Control by MixedChloride Additives of the Qual...
8047    Nonfullerene acceptor with low energy loss and...
8065    A thermally stable bariumstabilized αCsPbI 3 p...
Name: ManuscriptTitle, dtype: object
11538    Operation and catastrophic optical degradation...
11541    Accurate and Efficient Approximate Quasipartic...
11559    Arresting Photodegradation in Semiconducting S...
Name: ManuscriptTitle, dtype: object
17464    TemperatureDependent Crystallization Mechanism...
17468    Recovery of acetaminophen from aqueous solutio...
17469    A SelfConsistent Scheme for Understanding Part...
17470    DIELECTRIC AND PIEZOELECTRIC PROPERTIES OF (K ...
Name: ManuscriptTitle, dtype: object
7342    Strong dependence on doping of a lowactivation...
7349    Hydrogen tunneling in the perovskite ionic con...
Name: ManuscriptTitle, dtype: object
5931    Inverted Environmentally Stable Perovskite Sol...
5958    Interdot Lead Halide Excess Management in PbS ...
Name: ManuscriptTitle, dtype: object
1324    Linear Electro‐Optic Modulation in Highly Pola...
1481    Artificial chemist an autonomous quantum dot s...
Name: ManuscriptTitle, dtype: object
11521    Pressure‐induced insulator–metal transition in...
11615    Doping and defect engineering induced extremel...
Name: ManuscriptTitle, dtype: object
11621    Hopping and tunnelling of D trapped by substit...
11627    Elastic and anelastic properties of Marval 18 ...
Name: ManuscriptTitle, dtype: object
6901    Tuning the Electrical and Thermoelectric Prope...
6916    Programmable devices based on reversible solid...
6920    A thin and flexible scanner for fingerprints a...
6928    Controlling the early stages of pentacene grow...
6942    Ferromagnetism in dilute magnetic semiconducto...
6945    Tunable magnetic interaction at the atomic sca...
Name: ManuscriptTitle, dtype: object
6899    Verification of TypeA and TypeBHC Blinking Mec...
6915    Unipolar barrier photodetectors based on van d...
6918    Efficient lightemitting diodes from mixeddimen...
Name: ManuscriptTitle, dtype: object
6914    Bidirectional optical signal transmission betw...
6929    Investigating molecular charge transfer comple...
Name: ManuscriptTitle, dtype: object
6925    Intermolecular hybridization governs molecular...
6926            Band bending in conjugated polymer layers
Name: ManuscriptTitle, dtype: object
3221    Enhancing the photocatalytic performance of MX...
3232    Laurionite Competes with 2D Ruddlesden–Popper ...
Name: ManuscriptTitle, dtype: object
1386    How to quantify the efficiency potential of ne...
1395    Blue Light‐Emitting Devices Based on Novel Pol...
1463    Amplified Spontaneous Emission from CoreSeeded...
Name: ManuscriptTitle, dtype: object
1329    Controlled Crystal Plane Orientations in the Z...
1333    Solvent‐Assisted Kinetic Trapping in Quaternar...
1334    Solar Cells Overcoming the Ambient Manufactura...
Name: ManuscriptTitle, dtype: object

15863    Carbazole Electroactive Amorphous Molecular Ma...
15864    Impact of widebandgap technology on renewable ...
Name: ManuscriptTitle, dtype: object
16895    Effect of Ydoped NbB2. 5 on structural and sup...
16897    Study of Halfmetallic Properties of Co2YGe (Y ...
16903    Catalytic abatement of CO species from incompl...
Name: ManuscriptTitle, dtype: object
16874    Anomalous H/sub c/in CoCrfilms surface and bul...
16880    Effect of interdot distance on magnetic behavi...
Name: ManuscriptTitle, dtype: object
8401     Transparent Light‐Emitting Electrochemical Cells
8436    Operationally Stable Perovskite Light Emitting...
Name: ManuscriptTitle, dtype: object
6793    Formation of charged ferroelectric domain wall...
6827    Mitigation of acylhomoserine lactone (AHL) bas...
Name: ManuscriptTitle, dtype: object
6784    Anomalous exchange bias at collinear/noncollin...
6786    Longrange electronic reconstruction to a dxz y...
6798    Highperformance flexible supercapacitors obtai...
6802    Dramatic changes in thermoelectric power of ge...
6803    Author Correction Discovery of Fe7O9 a new iro...
6804    Xray scintillation in lead halide perovskite c...
6812    Deposition of topological silicene germanene a...
6814    Spatiotemporal behaviour of atomicscale triboc...
6818    Copper sulfide nanoparticles as highperformanc...
6835    Ultrafast energy transfer in ultrathin organic...
6836    Role of 2D and 3D defects on the reduction of ...
6838    Optical band gap alteration of graphene oxide ...
Name: ManuscriptTitle, dtype: object
6800    Metal halide solidstate surface treatment for ...
6806    Evidence for photoinduced charge separation be...
6825    Physicochemical properties and catalytic activ...
Name: ManuscriptTitle, dtype: object
14135    Optimized Fedoped ZnO nanoparticles for magnet...
14136    Quantitative comparison between different meth...
14150    Fabrication of perovskite solar cells in ambie...
14206    Synthesis crystal growth and characterization ...
Name: ManuscriptTitle, dtype: object
10978    Dynamic doping and degradation in sandwichtype...
10981    Ultrafast multiexponential electron injection ...
Name: ManuscriptTitle, dtype: object
9809    Colloidal quantum dot solar cell band alignmen...
9824    Perovskite Quantum Dot Solar Cells Fabricated ...
Name: ManuscriptTitle, dtype: object
4732     Turning the Tap Conformational control of quan...
13468    Alloying nanoparticles by discharges in liquid...
Name: ManuscriptTitle, dtype: object
4302    Rudorffites and Beyond Perovskite‐Inspired Sil...
4719    Thin‐Film Transformation of NH4PbI3 to CH3NH3P...
Name: ManuscriptTitle, dtype: object
14825    Boron emitters Defects at the siliconsilicon d...
14874    Structural properties of CdTe and ZnTe thin fi...
Name: ManuscriptTitle, dtype: object
14822    Introduction of negative charges in nitride fo...
14824    The thermal stability of atomic H plasma produ...
Name: ManuscriptTitle, dtype: object
14852    Optimizing carbon nanotube contacts for use in...
14889    Letidaffected cells from a utilityscale photov...
Name: ManuscriptTitle, dtype: object
14820    Investigation of lifetime degradation of RIEpr...
14845    Continuous Flash Sublimation of Inorganic Hali...
14850    Smallarea Passivated Contact monoPolyTM Silico...
Name: ManuscriptTitle, dtype: object
14830    Insitu observation of moistureinduced degradat...
14843      Perovskite PV Design for Stable Space Operation
Name: ManuscriptTitle, dtype: object
4647    Triplet Acceptors with a D‐A Structure and Twi...
4660    On the Location of Li+ Cations in the Fast Li‐...
Name: ManuscriptTitle, dtype: object
1161    Fast electron and slow hole relaxation in InPb...
8752    The role of grain boundary character in solute...
Name: ManuscriptTitle, dtype: object
10414    Is the Verwey transition in Fe3O4 magnetite dr...
12261    H2/D2 isotopic exchange A tool to characterize...
Name: ManuscriptTitle, dtype: object
6079    Enhanced photoluminescence of halide perovskit...
6140    Integer charge transfer and hybridization at a...
Name: ManuscriptTitle, dtype: object
12502    Interpretation of the photoluminescence decay ...
12514    Fluorescence quenching by charge carriers in i...
Name: ManuscriptTitle, dtype: object
14290    Simulation of a spintronic transistor A study ...
14309    A first principles study of Nd doped cubic LaA...
Name: ManuscriptTitle, dtype: object
1941    Efficient electrosynthesis of npropanol from c...
1993    HighDensity Nanosharp Microstructures Enable E...
Name: ManuscriptTitle, dtype: object
4162    Dynamic Redistribution of Mobile Ions in Perov...
4172    Photocurrent extraction efficiency near unity ...
Name: ManuscriptTitle, dtype: object
15836    Q1DPolarons in Rigid Boundary Cylindrical Wire...
15837                                 Magic gold nanotubes
15839     Confined Bipolarons in the Strong Coupling Limit
15841    Tailoring the magnetic anisotropy of cobaltgol...
15844    Pseudo jahn‐teller origin of bending distortio...
Name: ManuscriptTitle, dtype: object
10413      Thermal expansion of monogermanides of 3dmetals
12252    Impact of ceriumbased support oxides in cataly...
Name: ManuscriptTitle, dtype: object
12753    Samarium vanadate affixed sulfur self doped gC...
12754    Paper based biofuel cells Incorporating enzyma...
Name: ManuscriptTitle, dtype: object
12772    Hydrogen effects on electrochemically charged ...
12776    Thermal decomposition of titanium hydrides in ...
Name: ManuscriptTitle, dtype: object
2081    Polaron stabilization by cooperative lattice d...
2089    Quantum Dot Size Dependent J−V Characteristics...
Name: ManuscriptTitle, dtype: object
5688    Fuel Cells Infiltrated NiCo Alloy Nanoparticle...
5708    Flexible Broadband Graphene Photodetectors Enh...
Name: ManuscriptTitle, dtype: object
2047    Epitaxyenabled vapor–liquid–solid growth of ti...
2105    Selectivearea epitaxy of pure wurtzite InP nan...
2108    Polaritydriven 3fold symmetry of GaAs/AlGaAs c...
Name: ManuscriptTitle, dtype: object
12566    Effect of addition on Y2O3 in ZrO2 support on ...
12567    Hydrogenation of dimethyl adipate over bimetal...
Name: ManuscriptTitle, dtype: object
10143    Charge transfer versus molecular conductance m...
10228    6‐1 Invited Paper Measuring Health Parameters ...
Name: ManuscriptTitle, dtype: object
7135    Nanocrystalline/microcrystalline materials bas...
7152    Spinglass behaviour in the double perovskite “...
7182    Doping of C 60 (sub) monolayers by Fermilevel ...
Name: ManuscriptTitle, dtype: object
1432    Localized electrons enhanced ion transport for...
1434    Electrode engineering in halide perovskite ele...
Name: ManuscriptTitle, dtype: object
4395    Performance limitations imposed by the TCO het...
4414    Sub150 C processed mesosuperstructured perovsk...
Name: ManuscriptTitle, dtype: object
11095    Special Issue Advanced Spectroscopies of Molec...
11096    Secondary electron spectra of semicrystalline ...
Name: ManuscriptTitle, dtype: object
6082    Surface electronic structure of hybrid organo ...
6090    Bane of HydrogenBond Formation on the Photoind...
Name: ManuscriptTitle, dtype: object
5065    Mechanistic studies of CsPbBr 3 superstructure...
6483    Unravelling the role of surface traps on carri...
6949    Coherent transfer of spin through a semiconduc...
Name: ManuscriptTitle, dtype: object
3526     Robust Antiferromagnetism and Structural Disor...
13754    Surfactantinduced anion exchange and morpholog...
Name: ManuscriptTitle, dtype: object
9467    Lightemitting electrochemical cells recent pro...
9488    Microgrinding of lensed fibers by means of a s...
Name: ManuscriptTitle, dtype: object
16875    Evolution of structural and magnetic propertie...
16881    Magnetic domains of floppy disks and phone car...
16896    A firstprinciples study of the electronic mech...
Name: ManuscriptTitle, dtype: object
2054    Wide Spectral Photoresponse of Layered Platinu...
2106    Ultralow surface recombination velocity in InP...
Name: ManuscriptTitle, dtype: object
11411    Benefit from photon recycling at the maximumpo...
12658    Hydrogen production through oxidative steam re...
Name: ManuscriptTitle, dtype: object
11403    Perspectives on designer photocathodes for xra...
12657    Magnesium tuned triple conductivity and bifunc...
Name: ManuscriptTitle, dtype: object
4054    Understanding the origin of the 535 nm emissio...
4055    Correlating structure with function in thermal...
4058    Monitoring the Formation of a CH3NH3PbI3–xClx ...
Name: ManuscriptTitle, dtype: object
3972    Ultrafast Electron Injection from Photoexcited...
3977    Vibrationally assisted intersystem crossing in...
Name: ManuscriptTitle, dtype: object
4030    Direct Observation of Conductive Polymer Induc...
4052    Overcoming the Cut‐Off Charge Transfer Bandgap...
Name: ManuscriptTitle, dtype: object
10142    Progress highlights and perspectives on NiO in...
10191    Highthroughput parallelized testing of membran...
10267    Photophysical properties of Au‐CdTe hybrid nan...
Name: ManuscriptTitle, dtype: object
13983    Optimization of high potential cathode materia...
13990    Photovoltaic properties of Bi2S3 and CdS quant...
13997    Enhancing energy efficiency and longterm durab...
14010    Effect of Dy on electrochemical supercapacitiv...
14036    Enhanced photocatalysis by coupling of anatase...
14039    Preparing of highly conductive patterns on fle...
14072    Evidence of the spin Seebeck effect in NiZn fe...
14073    Ground state electronic and magnetic propertie...
14104    Efficient colloidal route to pure phase kester...
14105    Transition from CZTSe to CZTS via multicompone...
Name: ManuscriptTitle, dtype: object
13965    Electrochemical deposition of thick iron oxide...
14005    Hybrid potentiodynamic/potentiostatic electrod...
14007    The influence of water on the charge transport...
14087    First principle analysis of the structural ele...
14088    Structural magnetic magnetocaloric and critica...
14089    Effect of carrier transfer on the PL intensity...
Name: ManuscriptTitle, dtype: object
13964    Prediction of the electrodeposition process be...
14084    Electronic structure elastic mechanical thermo...
Name: ManuscriptTitle, dtype: object
13960    Oxygen reduction reaction on electrodeposited ...
13961    Electrodeposition of Cudoped ZnO nanowire arra...
13962    Some electrocatalytic properties of anodic iri...
13968    Dyesensitized solar cells based on TiO2 nanotu...
13994    Enhancement of photovoltaic performance and mo...
14002    Onepot electrochemical synthesis of CdTe quant...
14006    Morphological modulation of polypyrrole thin f...
14019    Facile synthesis of tin oxide hollow nanoflowe...
14090    Identification of hydrogen related defects in ...
14114        Mechanochemical treatment of Mgferrite powder
14116    The log (σ) vs. log (ω) derivative plot used t...
Name: ManuscriptTitle, dtype: object
13975    Opening the door to liquidfree polymer electro...
13985    Polybenzimidazole/strontium cerate nanocomposi...
13998    Fabricating CuS counter electrode for quantum ...
14022    Electrospun Networks of ZnOSnO2 Composite Nano...
14026    GaN Schottky metal–semiconductor–metal UV phot...
14078    Magnetic and structural studies of the double ...
14079    Structural and electronic properties of the na...
Name: ManuscriptTitle, dtype: object
13959         Temperature effects on ZnO electrodeposition
13987    Monolayers of choline chloride can enhance des...
Name: ManuscriptTitle, dtype: object
14037    Efficiency enhancements in Ag nanoparticlesSiO...
14052            Quantum diffusion of deuterium in GaAs Zn
Name: ManuscriptTitle, dtype: object
13979    Influence of iodine concentration on the photo...
14008    The deepDRT A deep neural network approach to ...
Name: ManuscriptTitle, dtype: object
13981    Evidence for enhancing charge collection effic...
14009    Study of oxygen electrode reactions on symmetr...
Name: ManuscriptTitle, dtype: object
14106    Strain effects on optical properties of tetrap...
14107    Modeling and analysis of HTMfree perovskite so...
Name: ManuscriptTitle, dtype: object
13993    Regulation of microstructure and composition o...
14044    Optical properties of an exciton bound to an i...
Name: ManuscriptTitle, dtype: object
5044    Efficient Perovskite LightEmitting Diodes Base...
5045    Quantifying Electrochemical Losses in Perovski...
5046    Enhanced light harvesting through Förster reso...
Name: ManuscriptTitle, dtype: object
6016    Strategic Halogen Substitution to Enable High‐...
6036    Graphene‐based electron transport layers in pe...
Name: ManuscriptTitle, dtype: object
11733    Dielectric and nonohmic properties of Ca2Cu2Ti...
11802    Development of molten nitrate salt based nanof...
11803    Optical Sensor Sensitivity Enhancement by Use ...
11804    Effects of particle hardness on shear thickeni...
Name: ManuscriptTitle, dtype: object
4973    Quantifying the composition dependency of the ...
4974    New twodimensional Ge–Sb–Te semiconductors wit...
Name: ManuscriptTitle, dtype: object
7436    Mobility and decay kinetics of charge carriers...
7448    Microscopic description of the phase separatio...
Name: ManuscriptTitle, dtype: object
7389    Ionimplantationinduced extended defect formati...
7441    Firstprinciples calculations of the thermodyna...
7450       Outofplane excitons in twodimensional crystals
7472      Anomalous Nernst effect of Fe3O4 single crystal
Name: ManuscriptTitle, dtype: object
12084    Characterization of nanostructures fabricated ...
12086    Two broad absorption bands in infrared atmosph...
Name: ManuscriptTitle, dtype: object
8601    Resonant silicon nanoparticles for enhancement...
8674    Ultrathin Ta 2 O 5 electronselective contacts ...
Name: ManuscriptTitle, dtype: object
17249    The impact of kaolin dehydroxylation on the po...
17250    A comparative study of the mechanical integrit...
Name: ManuscriptTitle, dtype: object
3896     Extent of Shallow/Deep Trap States beyond the ...
11262    Investigation of charge transport and band ali...
Name: ManuscriptTitle, dtype: object
11265    Tunable electronic and magnetic properties of ...
11269    Twodimensional XY monolayers (X= Al Ga In; Y= ...
Name: ManuscriptTitle, dtype: object
11273    Sizedependent selectivity and activity of high...
11277    Photocatalytic activity of Ndoped anatase grow...
Name: ManuscriptTitle, dtype: object
11263    Preparation of (Ba0. 5Sr0. 5) TiO3 thin films ...
11266    Adsorption of habitat and industryrelevant mol...
11267    Abinitiodriven prediction of puckered pentalik...
Name: ManuscriptTitle, dtype: object
14147    Laserbased series interconnection of chalcopyr...
14159     Optical properties of PVP/Li3GaO3 nanocomposites
14183    Growth and characterization of sodium sulfanil...
Name: ManuscriptTitle, dtype: object
851               Cu–In halide perovskite solar absorbers
5595    Quantumdot double layer polymer waveguides by ...
Name: ManuscriptTitle, dtype: object
4012    High‐Quality Photonic Crystals Infiltrated wit...
4016    Nanostructured architectures for biomolecular ...
Name: ManuscriptTitle, dtype: object
4022    High fill factor and open circuit voltage in o...
4024    Intrinsic surface dipoles control the energy l...
Name: ManuscriptTitle, dtype: object
4013    Donor–Acceptor C60‐Containing Polyferrocenylsi...
4014    Spatial collection in colloidal quantum dot so...
4038    Nongeminate recombination and charge transport...
4047    Suppression of the Keto‐Emission in Polyfluore...
Name: ManuscriptTitle, dtype: object
13474    Routes to tin chalcogenide materials as thin f...
13480    pHInduced Surface Modification of Atomically P...
Name: ManuscriptTitle, dtype: object
10197    ARS process to nanocrystalline BaMxAl12xO19δ (...
10222    P‐26 Thermally Annealed Asymmetric‐Offset Poly...
Name: ManuscriptTitle, dtype: object
6857    Theoretical prediction of twodimensional BC2X ...
6894    Photocatalytic generation of hydrogen by cores...
Name: ManuscriptTitle, dtype: object
14035    Magnetic properties of superparamagnetic nanop...
14067    Pressureinduced phase transitions in Si observ...
Name: ManuscriptTitle, dtype: object
14032    The role of intrinsic and surface states on th...
14033    Sequentially vaporgrown hybrid perovskite for ...
Name: ManuscriptTitle, dtype: object
14137    Photocatalytic degradation of Rhodamine dyes u...
14138    Mechanical measurements of pure and kaolin rei...
14140    Synthesis and characterization of sol–gel deri...
Name: ManuscriptTitle, dtype: object
14839    Solar cells based on colloidal quantum dot sol...
14871    Energy yield potential of perovskitesilicon ta...
14872    Introduction of Sb in CDTE and its effect on C...
Name: ManuscriptTitle, dtype: object
6405    Onestep microheterogeneous formation of rutile...
6407    Ternary Phase Diagrams of MAI–PbI2–DMF and MAI...
Name: ManuscriptTitle, dtype: object
826     Operational Mechanism of Conjugated Polyelectr...
5575    Protein Adsorption on Nanocrystalline TiO2 Fil...
Name: ManuscriptTitle, dtype: object
14571    The effect of LPCVD silicon nitride deposition...
14572    Characterization of the Si− SiO2 Interface Fol...
Name: ManuscriptTitle, dtype: object
6489    Effect of surface stoichiometry on blinking an...
6498    Photoluminescence Saturation in QuantumCutting...
Name: ManuscriptTitle, dtype: object
6488    Ultrafast manyparticle phenomena in lead bromi...
6581    Extending the compositional space of mixed lea...
6635    Investigating spatiotemporal correlation of mu...
Name: ManuscriptTitle, dtype: object
17533    The Influence of ginger spent loading on mecha...
17535    Graphene nanoplatelets polyvinyl alcohol nanoc...
Name: ManuscriptTitle, dtype: object
15643    Filterless spectral splitting perovskite–silic...
15645    Characterization of MAEtextured nanoporous sil...
Name: ManuscriptTitle, dtype: object
1593    A hard oxide semiconductor with a direct and n...
1594    Perovskites A Hard Oxide Semiconductor with A ...
Name: ManuscriptTitle, dtype: object
16404    A Review of 2D Perovskites and CarbonBased Nan...
16412    Variation of the structural and the magnetic p...
Name: ManuscriptTitle, dtype: object
13963    A method for electrochemical growth of homogen...
13966    Preparation of ZnO/Eu mixed films by electroch...
13967    Electrodeposition of NiO films and inverse opa...
13970    Growth of porous light scattering submicromete...
13971    Direct bioelectrocatalysis by multicopper oxid...
13976    Sodium polymer electrolytes composed of sulfon...
13977    Nonwoven polyaramid porous membranes as separa...
13980    Precise control of PbI2 excess into grain boun...
13988    Tuning the electrochemistry of homoleptic coba...
13989    Onepot synthesis of novel silverpolyanilinepol...
13991    Enhanced photovoltaic performance and stabilit...
13999    Electrochemical growth of FeS on threedimensio...
14004    In situ growth of ironnickel nitrides on carbo...
14011    Reduced hysteresis and enhanced air stability ...
14012    Near thresholdless laser operation at room tem...
14025    Micropillar electrode array from metal to diel...
14028    A defective 1D photonic crystalbased chemical ...
14038    The ion implantationinduced properties of oned...
14040    Strong localization effect and carrier relaxat...
14042    Lasing and Transport Properties of Poly [(9 9d...
14045    Energy of excitons and acceptor–exciton comple...
14046    Optical properties of acceptor–exciton complex...
14047    Low temperature mobilities of 2D electrons in ...
14053    Mobility and shortrange ordering of oxygen in ...
14056    Relation between charge ordering and local lat...
14059    Mobility of interstitial oxygen in scandium by...
14060    Influence of interstitial O on the cluster spi...
14061    Influence of nanoenvironment on luminescence o...
14062    Study of photoluminescence properties of Er3+ ...

11503    Optimization of electrochemically grown dense ...
11598    Polarization Resistance‐Free Mn3O4‐Based Elect...
Name: ManuscriptTitle, dtype: object
11565    Reverse micelle templating route to ordered mo...
11566    Colloidal Continuous Injection Synthesis of Fl...
11567    Effects of Oxygen Plasma on the Chemical Light...
11600    Probing the 3‐step Lithium Storage Mechanism i...
Name: ManuscriptTitle, dtype: object
10800    Acetonitrile based single step slotdie compati...
10802    The ultralow thermal conductivity and tunable ...
10803    Visiblelight photocatalytic activity of nitrog...
Name: ManuscriptTitle, dtype: object
3181    Siliconized triarylamines as redox mediator in...
3195    Detection of Au+ Ions During Fluorine GasAssis...
Name: ManuscriptTitle, dtype: object
9942    Influence of the InAs coverage on the phononas...
9946    Growth mechanisms and band bending in Cu and P...
Name: ManuscriptTitle, dtype: object
574     Solutionprocessed perovskite light emitting di...
4632        Piezoelectricity in two‐dimensional materials
Name: ManuscriptTitle, dtype: object
237    Programming the detection limits of biosensors...
290       Achromatic polarization control in the visible
Name: ManuscriptTitle, dtype: object
3265    ThicknessDependent Domain Relaxation Dynamics ...
3301    Controlling C60 Organization through DipoleInd...
Name: ManuscriptTitle, dtype: object
12266    Special Issue Section 2 Recent trends in C1C4 ...
12353    Effect of TiO2 antireflection layer with vario...
12418    Fullerene based electron transporting layers f...
Name: ManuscriptTitle, dtype: object
5951    MXene‐contacted silicon solar cells with 11.5%...
6034    Perovskite Solar Cells Stabilization of Precur...
Name: ManuscriptTitle, dtype: object
6373    Temperaturedependent excitonic decay and multi...
6374    Longlived charge separation at heterojunctions...
Name: ManuscriptTitle, dtype: object
2634    Colossal tuning of an energy gap in Sn2P2S6 un...
2737    Sidetoside alignment of gold nanorods with pol...
Name: ManuscriptTitle, dtype: object
9084    Organic lightemitting devices with silicon anodes
9111    Magnetic and transport characteristics of long...
Name: ManuscriptTitle, dtype: object
877    Correlating ChargeTransfer State Lifetimes wit...
880    Tailorable indirect to direct bandgap double p...
Name: ManuscriptTitle, dtype: object
577    Suppressing phase disproportionation in quasi2...
580    Bond engineering of molecular ferroelectrics r...
Name: ManuscriptTitle, dtype: object
12695    Surface mobility and reactivity of oxygen spec...
12701    Effects of dispersion and partial reduction on...
Name: ManuscriptTitle, dtype: object
4921    Dynamically controlled growth of Cu–Mo–O nanos...
4922    Correction Chlorinedoped SnO 2 hydrophobic sur...
Name: ManuscriptTitle, dtype: object
10119    Polymer Quantum DotSensitized Solar Cell Incor...
10121    Fabrication of ThreeDimensional SingleWalled C...
Name: ManuscriptTitle, dtype: object
8586    > 85% indium reduction for highefficiency sili...
8619    Investigation of high contrast and reversible ...
Name: ManuscriptTitle, dtype: object
12844    A novel ferrimagnetic iridocuprate IrSr {sub 2...
12860    A high temperature neutron diffraction study o...
12877    Phase transitions in the hexagonal tungsten br...
Name: ManuscriptTitle, dtype: object
12855    An investigation of the optical properties and...
12899                    IN SITU REDUCTION OF (100) SRTIO3
Name: ManuscriptTitle, dtype: object
3640     Charge Transfer Absorption and Emission at ZnO...
13465    γ‐Valerolactone A Nontoxic Green Solvent for H...
Name: ManuscriptTitle, dtype: object
2227    Ultrafast imaging of carrier cooling in metal ...
2231     Mixedhalide perovskites with stabilized bandgaps
Name: ManuscriptTitle, dtype: object
2906     Unraveling the elastic properties of (quasi) t...
13588    Transition Metal Complexes Coupled to Vacancie...
Name: ManuscriptTitle, dtype: object
8854    Hole injection in triarylamine containing poly...
8921    Carrier recombination losses in inverted polym...
Name: ManuscriptTitle, dtype: object
12152    LongLived Mobile Charge Carriers Formed on Pho...
12187    Nonthermal plasma synthesis of metal sulfide n...
Name: ManuscriptTitle, dtype: object
15542    Potentialassisted assembly of functionalised p...
15543    Reversible binding of molecular dioxygen to Co...
Name: ManuscriptTitle, dtype: object
12166    Aggregationinduced dual emission and unusual l...
12170    Liquid crystalline polyfluorenes for blue pola...
Name: ManuscriptTitle, dtype: object
2913     Extrinsic effects on the optical properties of...
13589    Ab initio and experimental studies of the larg...
Name: ManuscriptTitle, dtype: object
6050    The impact of local work function variations o...
6051    Unraveling the Microstructure of Molecularly D...
Name: ManuscriptTitle, dtype: object
9982    Aluminum oxide as a dualfunctional modifier of...
9988    Coking suppression in solid oxide fuel cells o...
Name: ManuscriptTitle, dtype: object
9983    Lithium and lanthanum promoted NiAl2O3 as an a...
9987    Cogeneration of electricity and syngas on prot...
Name: ManuscriptTitle, dtype: object
12133    Rigidrodlike main chain polymers with rigidly ...
12140    Enhanced electrical conductivity of molecularl...
Name: ManuscriptTitle, dtype: object
8458    Ethylene glycol as a new sustainable fuel for ...
8550    Freestanding colored polymer film with composi...
Name: ManuscriptTitle, dtype: object
8472    Grain size dependence of degradation of alumin...
8475    A regioregular head to tail thiophene based “d...
Name: ManuscriptTitle, dtype: object
9288    Large scale ultravioletbased nanoimprint litho...
9289    Precision material modification and patterning...
9321    Thirdorder optical nonlinearity and figure of ...
9323    Structural and electrical conductivity studies...
9327    Textured BaTiO3 by templated grain growth and ...
Name: ManuscriptTitle, dtype: object
9297    Impact of supercritical  drying on roughness o...
9318    Spectroscopic ellipsometry study of FAxMA1−xPb...
9340    Strain engineering of piezoelectric properties...
9341    Silk fibroin protein as dual mode picric acid ...
9342    Towards highperformance hybrid hydrophilic mem...
9343    Solution‐Processed In2O3/ZnO Heterojunction El...
Name: ManuscriptTitle, dtype: object
12748    Role of copper content and calcination tempera...
12749     Optimized CuO–CeO2 catalysts for COPROX reaction
Name: ManuscriptTitle, dtype: object
7213    Raman scattering in strongly coupled organic s...
7216    Imaging the polariton relaxation bottleneck in...
Name: ManuscriptTitle, dtype: object
9762    Bandwidth limits of luminescent solar concentr...
9764    Ultrafast and broadband photodetectors based o...
Name: ManuscriptTitle, dtype: object
14908    Illuminated outdoor luminescence imaging of ph...
14909                   Prospects for perovskites in space
Name: ManuscriptTitle, dtype: object
11193    Solventfree solidstate synthesis of high yield...
11198    Shaping Tin Nanocomposites through Transient L...
11199    Multilayered Barium and Strontium Carbonate St...
Name: ManuscriptTitle, dtype: object
280      Tunable roomtemperature singlephoton emission ...
13568    Structural Diversity in Layered Hybrid Perovsk...
Name: ManuscriptTitle, dtype: object
1041    Noninjection gramscale synthesis of monodisper...
1049    DefectInduced in Situ Atomic Doping in Transit...
Name: ManuscriptTitle, dtype: object
9979    A NiFeCu alloy anode catalyst for directmethan...
9984    A comprehensive evaluation of a Ni–Al2O3 catal...
Name: ManuscriptTitle, dtype: object
9304    Formation and removal of composite halogenated...
9309    Modulationdoped ZnSe/(Zn Cd Mn) Se quantum wel...
Name: ManuscriptTitle, dtype: object
3530    Robotaccelerated perovskite investigation and ...
3610    Flexible Composite Energy Harvesters from Ferr...
Name: ManuscriptTitle, dtype: object
2663    Tuning the interfacial charge orbital and spin...
2665              Stable halfmetallic monolayers of FeCl2
Name: ManuscriptTitle, dtype: object
17007    Synthesis and Characterization of Poly Vinyl A...
17016    Theoretical and experimental studies on microc...
Name: ManuscriptTitle, dtype: object
1238    Extrinsic and dynamic edge states of twodimens...
8772    A molecular approach to an electrocatalytic hy...
Name: ManuscriptTitle, dtype: object
5476    Direct electrochemistry and nitric oxide inter...
5477    Factors that affect protein adsorption on nano...
Name: ManuscriptTitle, dtype: object
14139    Hydroxyapatite ceramics prepared from two natu...
14165    Cu (II) ions removal from water by charcoal ob...
Name: ManuscriptTitle, dtype: object
14154    Role of precursors on photocatalytic behavior ...
14156    High quantum yield CdSe/ZnS/CdS/ZnS multishell...
Name: ManuscriptTitle, dtype: object
16186    Tailoring the magnetic hyperthermia performanc...
16198    Colossal dielectric response and relaxation pr...
16399    Comparison of Semiconducting and Metallic Carb...
Name: ManuscriptTitle, dtype: object
2540    STRUCTURAL MECHANICAL THERMODYNAMIC AND OPTICA...
2556    Domain wall pinning contribution to the nonlin...
Name: ManuscriptTitle, dtype: object
7711    Optimizing solidstate ligand exchange for coll...
7725    Impact of perovskite/silicon tandem module des...
Name: ManuscriptTitle, dtype: object
10215    62‐9 Invited Paper Hybrid Composite Films with...
10217    P‐4.2 Reducing Chromaticity Shifts of Light Em...
Name: ManuscriptTitle, dtype: object
8542     Phonon lifetimes in model quantum dot superlat...
13530    Group 12 Metal Complexes of an 18Membered N2O2...
Name: ManuscriptTitle, dtype: object
5494    Tungsten work function engineering for dual me...
5633    The impact of grain alignment of the electron ...
Name: ManuscriptTitle, dtype: object
5550    Dielectric properties of bismuth niobate films...
5732    An Air Knife–Assisted Recrystallization Method...
Name: ManuscriptTitle, dtype: object
17114    Development of poly (urethaneester) amide from...
17121    Application of multidimensional (0D 1D 2D) nan...
Name: ManuscriptTitle, dtype: object
1356    Evidence for physisorption of aluminum on the ...
1534    Shelf‐Stable Quantum‐Dot Light‐Emitting Diodes...
Name: ManuscriptTitle, dtype: object
8215    Surface modification via selfassembling large ...
8226    Roadmap and roadblocks for the band gap tunabi...
Name: ManuscriptTitle, dtype: object
16563    Optimization of the Processing of 8‐YSZ Powder...
16629    Electronbeaminduced cracking in organicinorgan...
Name: ManuscriptTitle, dtype: object
9078    Theoretical calculation of the vibrational and...
9081    Direct optical transitions at K and Hpoint of ...
Name: ManuscriptTitle, dtype: object
9059    Experimental and firstprinciples investigation...
9072    Scanning microwave microscopy and scanning cap...
Name: ManuscriptTitle, dtype: object
9109    Strain effects on magnetic characteristics of ...
9116    Symmetry dependent optoelectronic properties o...
Name: ManuscriptTitle, dtype: object
713    Mechanism of charge migration through DNA mole...
714    Effect of structural dynamics on charge transf...
Name: ManuscriptTitle, dtype: object
8394    Doubly stabilized perovskite nanocrystal lumin...
8405    Water An Influential Agent for Lanthanide‐Dope...
Name: ManuscriptTitle, dtype: object
8947    Leadfree hightemperature dielectrics with wide...
8959    Crystal structure and domain‐wall contribution...
Name: ManuscriptTitle, dtype: object
16182    Structural magnetic and magnetocaloric propert...
16183    Magnetocaloric properties of (La1− xPrx) 0.85 ...
Name: ManuscriptTitle, dtype: object
14785    Sulfurization studies of the potential thin fi...
14792    Solution deposition of amorphous IZO films by ...
Name: ManuscriptTitle, dtype: object
7858    Doubling Exponent Models for the Analysis of P...
7974         Organic laser based on thiophene derivatives
Name: ManuscriptTitle, dtype: object
11732    Charge transfer and magnetotransport propertie...
11735    Lanthanum influence on the structure dielectri...
11811    Synthesis and structural characterization of t...
11818    Magnetic behaviour of praseodymium substituted...
11821    Waspwaisted like magnetic behavior of nanocrys...
11833    Planar versus bulk heterojunction perovskite m...
Name: ManuscriptTitle, dtype: object
11773    Optical properties of GST nanoparticles fabric...
11779    Comparative Study On The Impact Of TiN And Mo ...
Name: ManuscriptTitle, dtype: object
12324    Exciton dynamics in an energy upconverting sol...
12330    Excited state dynamics of PPI dendrimers funct...
Name: ManuscriptTitle, dtype: object
1237    Observation of strong valley magnetic response...
1239    Extraordinarily Stable Aqueous Electrochromic ...
Name: ManuscriptTitle, dtype: object
3520     GreenEmitting Powders of ZeroDimensional Cs4Pb...
13173    Atomistic simulation of SiAu melt crystallizat...
Name: ManuscriptTitle, dtype: object
12950    Standardized microbial fuel cell anodes of sil...
12956    Novel amphiphilic corannulene additive for moi...
Name: ManuscriptTitle, dtype: object
976      Prismatic deflection of live tumor cells and c...
15124    Magnetic Anisotropy in “Scorpionate” First‐Row...
Name: ManuscriptTitle, dtype: object
1494    Conjugated polymer mesocrystals with structura...
1496    Solar Cells Spin‐Cast Bulk Heterojunction Sola...
Name: ManuscriptTitle, dtype: object
8541    Hot carrier solar cell absorber prerequisites ...
8543    Hot carrier dynamics in HfN and ZrN measured b...
Name: ManuscriptTitle, dtype: object
14613    Proton conductivity in mixed Bsite doped perov...
14620    Graphene transfer methods for the fabrication ...
14625    Improved understanding of metal–graphene contacts
Name: ManuscriptTitle, dtype: object
1529    Efficient nonfullerene organic solar cells wit...
1532    High‐Efficiency Flexible Solar Cells Based on ...
Name: ManuscriptTitle, dtype: object
194    Breaking of macroscopic centric symmetry in pa...
349    Eliminating the need for anodic gas separation...
Name: ManuscriptTitle, dtype: object
3770    Monitoring Charge Carrier Diffusion across a P...
3821    Free carrier generation and recombination in p...
Name: ManuscriptTitle, dtype: object
14403    Singlestrand DNAnanorod conjugates–tunable ani...
14404    Barium titanate perovskite nanoparticles as a ...
Name: ManuscriptTitle, dtype: object
9506    CMOS integration of epitaxial GdO highk gate d...
9539    Allinorganic nonperovskite copper halides for ...
Name: ManuscriptTitle, dtype: object
7708    Structural origins of lightinduced phase segre...
7709    Colloidal synthesis and charge carrier dynamic...
Name: ManuscriptTitle, dtype: object
3370    Controlled synthesis and optical properties of...
3410    Improved Photovoltaic Efficiency and Amplified...
Name: ManuscriptTitle, dtype: object
8599    Laser fabrication of crystalline silicon nanor...
8678    Charge separation in Ptdecorated CdSe@ CdS oct...
Name: ManuscriptTitle, dtype: object
89     Engineering spinorbit synthetic Hamiltonians i...
124       Observation of roomtemperature polar skyrmions
125    Spatially resolved steadystate negative capaci...
Name: ManuscriptTitle, dtype: object
5882    Effect of Co‐Solvents on the Crystallization a...
5986    Staging Unraveling the Potassium Storage Mecha...
Name: ManuscriptTitle, dtype: object
13932    Rodshaped thiocyanateinduced abnormal band gap...
13933    Synthesis and transformation of zerodimensiona...
Name: ManuscriptTitle, dtype: object
9757    Microlightemitting diodes with quantum dots in...
9760    Broadband perovskite quantum dot spectrometer ...
9761    There is plenty of room at the top generation ...
9770    Waterinduced MAPbBr3@PbBr(OH) with enhanced lu...
Name: ManuscriptTitle, dtype: object
184     Reducing the efficiency–stability–cost gap of ...
1111    Fast neutron imaging with semiconductor nanocr...
Name: ManuscriptTitle, dtype: object
1086    Tunable Multipolar Surface Plasmons in 2D Ti3C...
8731    Facile synthesis of stable water soluble dendr...
Name: ManuscriptTitle, dtype: object
3630    Biexciton resonances reveal exciton localizati...
3631    Electrooptic response in germanium halide pero...
Name: ManuscriptTitle, dtype: object
3550    Improved Photovoltaic Efficiency and Amplified...
3553    Direct Band Gap MixedValence Organic–inorganic...
3555    Design of LeadFree Antiferroelectric (1 – x)Na...
Name: ManuscriptTitle, dtype: object
2833     Strainpromoted perpendicular magnetic anisotro...
13585    Treatment of the multimode Jahn–Teller problem...
Name: ManuscriptTitle, dtype: object
12097    Sequential polymer precipitation of core–shell...
12099    Toward the realization of a practical diketopy...
12130    Relaxation of polar order in poled polymer sys...
12131    Surface structure of semicrystalline naphthale...
Name: ManuscriptTitle, dtype: object
4963    Enhanced emission efficiency in doped CsPbBr 3...
5060    Structure–property trends in a hollandite mult...
Name: ManuscriptTitle, dtype: object
16213    Powder injection moulding of premixed ferritic...
16247    Spectroscopic properties of cerium in glasses ...
Name: ManuscriptTitle, dtype: object
8617    Investigation of high contrast and reversible ...
8668    Radiofrequencytransmitting hexagonal boron nit...
Name: ManuscriptTitle, dtype: object
3562    Polymerassisted synthesis of colloidal germani...
7846    Conductivity Measurements of Electrochemically...
Name: ManuscriptTitle, dtype: object
9624    Longlived charge separation in twodimensional ...
9649    Electrical control of a laterally ordered InAs...
9650    Mapping the plasmonic response of gold nanopar...
Name: ManuscriptTitle, dtype: object
9223    Backcontact perovskite solar cell fabrication ...
9224               Semitransparent quantum dot solar cell
Name: ManuscriptTitle, dtype: object
6704    Rational Design of a Water‐Storable Hierarchic...
6763    Effect of disorder on transport properties in ...
Name: ManuscriptTitle, dtype: object
6723    Mn2+/Yb3+ Codoped CsPbCl3 Perovskite Nanocryst...
6730    Molecular Weight Tuning of Organic Semiconduct...
6768    Ionbeam assisted laser fabrication of sensing ...
Name: ManuscriptTitle, dtype: object
11171    Selfhealing selfassembly of aspectratiotunable...
11172    Growth of SingleCrystal DoubleDirectional Tell...
12751    Effect of higher alcohols on the performances ...
12752    Molecular structure and pH effects on the prod...
Name: ManuscriptTitle, dtype: object
6342    Tunable Band Gap and Rhombohedral Distortion i...
6380    In Situ Synthesis of Conducting Polymers A Nov...
Name: ManuscriptTitle, dtype: object
14831    Fabrication of flexible perovskite solar cells...
14878    Low cost spin coating fabrication of efficient...
Name: ManuscriptTitle, dtype: object
13288    Laser postprocessing of halide perovskites for...
13289    Singlestage fabrication of lowloss dielectric ...
13295    Manipulating fano resonance via fslaser meltin...
13298    Mixed halide perovskite light emitting solar cell
13316    Processing and characterization of GaP nanowir...
Name: ManuscriptTitle, dtype: object
1112    Unraveling the radiative pathways of hot carri...
8741    Optical trapping and manipulation of plasmonic...
Name: ManuscriptTitle, dtype: object
1208    Observation of the full exciton and phonon fin...
8766    Waterinduced fluorescence enhancement of leadf...
Name: ManuscriptTitle, dtype: object
8777    Resonant energy transfer in a van der Waals st...
8800    Enhancement of exciton transport in porphyrin ...
Name: ManuscriptTitle, dtype: object
4463     A mechanistic study of the dopantinduced break...
15120    Recent advances in the use of TiO 2 nanotube p...
Name: ManuscriptTitle, dtype: object
7869    Solvation Dynamics of DCM in a DPPC Vesicle En...
7935    Atomistic simulations of P (NDI2ODT2) morpholo...

13511    Variable Temperature Neutron Diffraction Study...
13520    Tripyridinophane platform containing three ace...
Name: ManuscriptTitle, dtype: object
13503    CaMn1−x NbxO3 (x ≤ 0.08) PerovskiteType Phases...
13504    New Materials Derived from Ybco  CrSr2RECu2O8 ...
Name: ManuscriptTitle, dtype: object
4402    Semicrystalline photovoltaic polymers with eff...
4404    Hot slot die coating for additivefree fabricat...
Name: ManuscriptTitle, dtype: object
2534    Prevention of oxide formation during liquid ph...
2620    Effect of ion mass on the evolution of extende...
Name: ManuscriptTitle, dtype: object
12471    A hightemperature highefficiency solar thermoe...
12474    Organic Solar Cells with Large Insensitivity t...
Name: ManuscriptTitle, dtype: object
5269    Perovskite singlecrystal solar cells going for...
5275    Solutionprocessed airstable mesoscopic seleniu...
Name: ManuscriptTitle, dtype: object
17477                       Solidstate NMR of nanocrystals
17491    Physicochemical characterization of wheat stra...
Name: ManuscriptTitle, dtype: object
6668    Spectral features and charge dynamics of lead ...
6672    Photophysics of Hybrid Lead Halide Perovskites...
6675    Quantum Dot Self‐Assembly Enables Low‐Threshol...
6745    Largearea rainbow holographic diffraction grat...
Name: ManuscriptTitle, dtype: object
5072           Tunable luminescent lead bromide complexes
5082    Highperformance perovskite singlejunction and ...
5182    Highly efficient perovskite solar modules by s...
Name: ManuscriptTitle, dtype: object
14466    Magnetic and dielectric studies of barium hexa...
15212    Electrochemical sensorbased barium zirconate o...
Name: ManuscriptTitle, dtype: object
14462                    Carbon nanotubeceramic composites
14463    Fabrication and characterization of Fe3O4/CNTs...
14476    The physics of terahertz negative photoconduct...
Name: ManuscriptTitle, dtype: object
13296    Direct femtosecond laser writing of optical na...
13297    Synthesis of perovskite nanoparticles in micro...
13299    Femtosecond laser nanostructuring of reinforce...
13300    Multi wall carbon nanotubes as a top electrode...
Name: ManuscriptTitle, dtype: object
4679    info doi/10.1002% 2Fange. 200351348 20210701 J...
4680    info doi/10.1002% 2Fange. 200250164 20210630 J...
Name: ManuscriptTitle, dtype: object
13303    Waterstable halide perovskite nanocrystals in ...
13309    Memristive properties of solar cells based on ...
13315    Study of nonlinear optical phenomena in silico...
Name: ManuscriptTitle, dtype: object
10557    Enhanced hole injection in a polymer light emi...
10558    Layer growth and desorption kinetics of a disc...
Name: ManuscriptTitle, dtype: object
16196    Modulation of magnetic ferroelectric and leaka...
17519    Synthesis and Mechanical Properties of Natural...
Name: ManuscriptTitle, dtype: object
3924    Comparison of the Performance of CoPCoated and...
7698    An ammoniumpseudohalide ion pair for synergist...
Name: ManuscriptTitle, dtype: object
1233    RealTime Observation of Exciton–Phonon Couplin...
1236    Fewlayer to multilayer germanium (II) sulfide ...
Name: ManuscriptTitle, dtype: object
2562    Raman spectroscopy of (KNa)NbO3 and (K Na)1xLi...
2565     Preisach modeling of ferroelectric pinched loops
Name: ManuscriptTitle, dtype: object
7044    Theoretical guidelines to create and tune elec...
7049    Enhanced mobility CsPbI3 quantum dot arrays fo...
Name: ManuscriptTitle, dtype: object
10664    [1] Benzothieno [3 2‐b][1] benzothiophene‐Phth...
10689    Electrophoretic deposited oxide thin films as ...
Name: ManuscriptTitle, dtype: object
11729    Modification of capacitive charge storage of T...
11731    Nanocrystals of a new complex perovskite diele...
Name: ManuscriptTitle, dtype: object
16942    Nitrogendoped simple and complex oxides for ph...
16957    A novel heterogeneous La0.8Sr0.2CoO3−δ/(La0.5S...
16960    Effect of the M3+ cation size on the structura...
16984    Phonon phase stability structural mechanical e...
16991    A tin‐incorporated multi‐phase perovskite nano...
16997    Adoption of widebandgap microcrystalline silic...
17002    Highperformance selfpowered color filterfree b...
17021    Effect of silica nanoparticle size on the stab...
Name: ManuscriptTitle, dtype: object
16964    Coordination modes of 3hydroxypicolinic acid S...
16967    Dielectric properties induced by the framework...
Name: ManuscriptTitle, dtype: object
16941    Photoinduced electron transfer between CdS and...
16945    Understanding and engineering of multiphase tr...
Name: ManuscriptTitle, dtype: object
16949    Tuning the ASite Cation Deficiency of La0.8Sr0...
16966    Unraveling the luminescence of new heterolepti...
Name: ManuscriptTitle, dtype: object
10438    Energy and mass of 3D and 2D polarons in the o...
10441    A variational study of the ground Landau level...
Name: ManuscriptTitle, dtype: object
3591    Backbone Randomization in Conjugated PolymerBa...
3592    Trioctylphosphine Oxide Acts as Alkahest for S...
Name: ManuscriptTitle, dtype: object
13759    Functional Molecular System of Bis (pyrazolyl)...
13760    Na–Ni–H Phase Formation at High Pressures and ...
Name: ManuscriptTitle, dtype: object
16560    Understanding the doping effect toward the des...
16613    Recent advances in metal‐organic framework der...
Name: ManuscriptTitle, dtype: object
980     Temperatureinduced selfcompensating defect tra...
1016    Piezoresistive Properties of Suspended Graphen...
1065    Structural optical and electrical properties o...
Name: ManuscriptTitle, dtype: object
11082    SrHf {sub 0.67} Ti {sub 0.33} O {sub 3} highk ...
11099    Carriergas assisted vapor deposition for highl...
Name: ManuscriptTitle, dtype: object
11776    Wave correlation of elementary deformation eve...
11790    Solgel silica films embedding NIRemitting Ybqu...
Name: ManuscriptTitle, dtype: object
13761    Facile Way of Making Hydrothermally Synthesize...
13763    A TwoStep Magnetron Sputtering Approach for th...
13764    Mitigating damage to hybrid perovskites using ...
Name: ManuscriptTitle, dtype: object
16649    Thermoelectric properties of pBi2 − x Sb x Te3...
16652                   Highpressure thermopower of sulfur
16666    Octahedral tilting in the polar hexagonal tung...
16673    Ab initio study on halfmetallic electronic and...
Name: ManuscriptTitle, dtype: object
16685    A (2) FeSbO (6)(A= Sr Ca) double perovskites o...
16692    Crystal structure analysis using integrated Xr...
Name: ManuscriptTitle, dtype: object
5221    Underwater organic solar cells via selective r...
5222    Ternary halide perovskites for highly efficien...
Name: ManuscriptTitle, dtype: object
3506     Facile dropletbased microfluidic synthesis of ...
12633    New bifunctional catalytic systems for sorbito...
Name: ManuscriptTitle, dtype: object
4534    Efficient optical amplification in the nanosec...
4595    Methane upgrading of acetic acid as a model co...
Name: ManuscriptTitle, dtype: object
5121    A simple ndopant derived from diquat boosts th...
5124    Low Temperature Crystallization Enables 21.9% ...
5183    Stability in perovskite photovoltaics a paradi...
Name: ManuscriptTitle, dtype: object
1273     Efficient spray‐coated colloidal quantum dot s...
1275     2D Metal Oxyhalide‐Derived Catalysts for Effic...
13147    Effect of the semiconductor quantum dot shell ...
Name: ManuscriptTitle, dtype: object
4794    Transparent organic lightemitting diodes with ...
4797       Nonlinear microscopy of lead iodide nanosheets
Name: ManuscriptTitle, dtype: object
6121    Homeopathic perovskite solar cells effect of h...
6127    Panchromatic SolartoH2 Conversion by a Hybrid ...
Name: ManuscriptTitle, dtype: object
1106    Largearea ordered superlattices from magnetic ...
1290    Effect of solvent environment on colloidal‐qua...
8738    Deep eutectic solventbased manganese molybdate...
Name: ManuscriptTitle, dtype: object
3289    Competing dissolution pathways and ligand pass...
3422    Thermochromic perovskite inks for reversible s...
Name: ManuscriptTitle, dtype: object
244                                      A sensitive pair
8809    Realizing a Highly Luminescent Perovskite Thin...
Name: ManuscriptTitle, dtype: object
207    Localized surface plasmon resonances arising f...
291    Experimental observation of the optical spin–o...
Name: ManuscriptTitle, dtype: object
6465    DualFunctional Optoelectronic and Magnetic Pyr...
6466    Longlived hot carriers in formamidinium lead i...
6467    Temperaturedependent optical properties of PbS...
Name: ManuscriptTitle, dtype: object
13942    Morphological Characterisation of Bacterial Ce...
13945    Exploring graphene quantum dots/TiO2 interface...
Name: ManuscriptTitle, dtype: object
5270     Lead halide perovskite nanocrystals in the res...
5277     Colloidal CsPbX3 (X = Cl Br I) Nanocrystals 2....
12803    Surface mobility of oxygen species on mixedoxi...
Name: ManuscriptTitle, dtype: object
1170    FourStates Multiferroic Memory Embodied Using ...
8756    Phase angle encoded upconversion luminescent n...
Name: ManuscriptTitle, dtype: object
9880    Ion bombardmentinduced enhancement of the prop...
9881    Interface engineering during plasmaenhanced ch...
Name: ManuscriptTitle, dtype: object
3356    Amorphous TiO2 Buffer Layer Boosts Efficiency ...
3402    PercolationLimited Ionic Diffusion in Li0.5xNa...
Name: ManuscriptTitle, dtype: object
3507     Microfluidic reactors provide preparative and ...
12634    Remarkable enhancement of the selective cataly...
Name: ManuscriptTitle, dtype: object
11528    Crossover from exciton to biexciton cavity pol...
11534         Polaronic exciton in a parabolic quantum dot
Name: ManuscriptTitle, dtype: object
12829    Tuning metal–carboxylate coordination in cryst...
12836    Microstructural changes in the reduction of Pr...
Name: ManuscriptTitle, dtype: object
10001    Fabrication BaZrO3/PBIbased nanocomposite as a...
10003    The effect of ethyleneamine ligands enhancing ...
Name: ManuscriptTitle, dtype: object
14752    New diagnostic method for monitoring plasma re...
14760    A combined optical and magneto‐optical measure...
Name: ManuscriptTitle, dtype: object
3502     The Future Is Blue (LEDs) Why Chemistry Is the...
12632    Preferential CO oxidation over nanosized gold ...
Name: ManuscriptTitle, dtype: object
519     The controlled disassembly of mesostructured p...
4857    A visible to nearinfrared nanocrystalline orga...
Name: ManuscriptTitle, dtype: object
15696    Discotic Liquid Crystals with Graphene Supramo...
15697    IIIIVI chalcogenide semiconductor nanocrystals...
Name: ManuscriptTitle, dtype: object
14781    Structure optimization for a high efficiency C...
14783    Challenges in deposition of wide band gap copp...
Name: ManuscriptTitle, dtype: object
254    Imaging the motion of electrons across semicon...
292    Experimental observation of the optical spinor...
Name: ManuscriptTitle, dtype: object
6075    Impact of bimolecular recombination on the fil...
6087    Access to ultrafast surface and interface carr...
6149    Molecular electronic coupling controls charge ...
6180    Luminescence of Nanostructured Eu3+/ZnO Mixed ...
6181    Effects of oxide nanoparticle size and shape o...
Name: ManuscriptTitle, dtype: object
14286    Magnetoelastic coupling in RuSr {sub 2} GdCu {...
14289    Dynamics of the nanophase separation in mangan...
Name: ManuscriptTitle, dtype: object
8490    Temperature dependence of opencircuit voltage ...
9701    Charge dissipation in ebeam lithography with N...
Name: ManuscriptTitle, dtype: object
5533    Enhancement of magnetic entropy change in La0....
5844    Revealing morphology evolution in highly effic...
Name: ManuscriptTitle, dtype: object
6721    Magnetic nanoparticle composites synergistic e...
6728    Proton Electrokinetics Electrokinetic Proton T...
Name: ManuscriptTitle, dtype: object
6716    Critical Role of Organic Spacers for Bright 2D...
6757    A fullyintegrated and automated testing device...
Name: ManuscriptTitle, dtype: object
6487    Role of ZnS segment on charge carrier dynamics...
6493    Ultralow Thermal Conductivity and Ultrahigh Th...
Name: ManuscriptTitle, dtype: object
15583    Galvanostatic synthesis of MnCo2O4 nanoflakes ...
15593    High temperature Raman spectroscopy studies of...
Name: ManuscriptTitle, dtype: object
9674    Inchsized aligned polymer nanofiber films with...
9675    A ZnO nanowire array film with stable highly w...
Name: ManuscriptTitle, dtype: object
6109    Properties of contact and bulk impedances in h...
6115    Photosensitization of TiO2 Layers with CdSe Qu...
Name: ManuscriptTitle, dtype: object
16223    Fluctuations and depinning of stripes at acous...
16225    Observation of the transition to the spinglass...
16401    Flexible Organic Photovoltaics with Colorful S...
16403    Tibased MXenes for Energy Storage Application ...
Name: ManuscriptTitle, dtype: object
9052     Interfacial ferromagnetism and atomic structur...
11384    Origin of Performance Enhancement in TiO2‐Carb...
Name: ManuscriptTitle, dtype: object
15741    Solvent free solidstate synthesis of Pr6O11/gC...
15746    Photosensitive antimony triiodide thin films b...
Name: ManuscriptTitle, dtype: object
15721    Lowenergy electroninduced chemistry of condens...
15726    Enhancing silicon solar cells with singlet fis...
15747    Photoluminescence properties of cerium oxide n...
Name: ManuscriptTitle, dtype: object
13061    Wastefree scale up synthesis of nanocrystallin...
13067    Role of alkyl chain length in diaminoalkane li...
13070    Aniondependent coordinative networking of macr...
13071    Networking of macrocycles 1D and 2D coordinati...
13072    Guesttriggered assembly of zinc (II) supramole...
Name: ManuscriptTitle, dtype: object
13060    Oxygen and Hydrogen Surface Mobility in Suppor...
13073    Cationdirected assembly of polyrotaxane and po...
Name: ManuscriptTitle, dtype: object
11867    Fine Structural Details Matter A Lesson from S...
11869              RuddlesdenPopper Perovskite Solar Cells
Name: ManuscriptTitle, dtype: object
11876    Xray standing waves reveal lack of OH terminat...
11883     perovskites Theoretical and experimental inve...
Name: ManuscriptTitle, dtype: object
6155    Synthesis of type II CdTeCdSe nanocrystal hete...
6160    Doublelayer structured WPLEDs based on three p...
Name: ManuscriptTitle, dtype: object
6074    Incorporating fluorine substitution into conju...
6089    Imaging the reduction of electron trap states ...
Name: ManuscriptTitle, dtype: object
6749     Silicon source of frequencybin entangled photons
6751    Ultraviolet C lasing at 263 nm from Ba2LaF7Yb3...
Name: ManuscriptTitle, dtype: object
6691    Toward Strong Near‐Infrared Absorption/Emissio...
6692    Pure 2D Perovskite Formation by Interfacial En...
Name: ManuscriptTitle, dtype: object
12930    Porphyrinic supramolecular daisy chains incorp...
12931    Trapping shapecontrolled nanoparticle nucleati...
Name: ManuscriptTitle, dtype: object
6068    Charge separation in PCPDTBT PCBM blends from ...
6086    Rotationally Free and Rigid Sublattices of the...
Name: ManuscriptTitle, dtype: object
382    Strong coupling between chlorosomes of photosy...
384    Single crystal hybrid perovskite fieldeffect t...
Name: ManuscriptTitle, dtype: object
14971    Collision of a long DNA molecule with an isola...
15004    Perovskite Semiconductors and Fundamental Mech...
Name: ManuscriptTitle, dtype: object
715    Supramolecular control of charge transport in ...
716    Understanding structure− mobility relations fo...
728    Ligand Locking on Quantum Dot Surfaces via a M...
Name: ManuscriptTitle, dtype: object
13845    Influence of halide choice on formation of low...
13865    Deep blue light amplification from a novel tri...
Name: ManuscriptTitle, dtype: object
11283    Impact of surface defects in electron beam eva...
11284    Work function investigations of Aldoped ZnO fo...
Name: ManuscriptTitle, dtype: object
12422    Enhanced performance in inverted organic light...
12424    The refractive index grating formation in azo ...
Name: ManuscriptTitle, dtype: object
11517    Thermoelectric power of sulphur at high pressu...
11518    Influence of P–T pre‐treatment on thermopower ...
Name: ManuscriptTitle, dtype: object
13656    Using lead chalcogenide nanocrystals as spin m...
13658    Magnetic order in a novel 3D oxalatebased coor...
Name: ManuscriptTitle, dtype: object
9546    Structure and internal dynamics of a side chai...
9561          Siesta Recent developments and applications
Name: ManuscriptTitle, dtype: object
13673    Probing magnetic interactions in metal–organic...
13674    Ir (III) complexes designed for lightemitting ...
Name: ManuscriptTitle, dtype: object
4427                Transforming energy using quantum dots
13672    Colloidal assemblies of oriented maghemite nan...
Name: ManuscriptTitle, dtype: object
10116    Vibrational spectrocopic studies of organic mo...
10160    Epitaxial growth and enhanced conductivity of ...
Name: ManuscriptTitle, dtype: object
667    Growth of Oriented SingleCrystalline Rutile Ti...
708    Asymmetric Interfacet Adatom Migration as a Mo...
Name: ManuscriptTitle, dtype: object
1708    Fast‐Response Highly Air‐Stable and Water‐Resi...
7545    Theoretical study of crossed and parallel carb...
Name: ManuscriptTitle, dtype: object
8880    Insulator–metal transition and magnetoresistan...
8881    Prediction of giant magnetoelectric effect in ...
Name: ManuscriptTitle, dtype: object
9870    Investigation of photophysical morphological a...
9876    Improved fill factors in solutionprocessed ZnO...
Name: ManuscriptTitle, dtype: object
15570    P/i interfacial engineering in semitransparent...
15573    Resistive switching functional quantumdot ligh...
Name: ManuscriptTitle, dtype: object
827      Geminate charge recombination in polymer/fulle...
15294    Semitransparent perovskite solar cells for sma...
Name: ManuscriptTitle, dtype: object
4738     Thousand‐fold Conductivity Increase in 2D Pero...
14915    Fundamentals of threeterminal tandem solar cel...
Name: ManuscriptTitle, dtype: object
15539    Practical electricity generation from a paper ...
15547    Performance optimization of PGM and PGMfree ca...
15555    A threedimensional model of CdZnTe gammaray de...
15559    Interpretation of AC conductivity of lightly d...
15562    Investigation of interface properties in oxide...
15563    Interfacial engineering for highly efficient o...
15565    Silicon nanoparticle sizedependent open circui...
Name: ManuscriptTitle, dtype: object
15549    The effect of indium doping on photovoltaic pr...
15566    2 5di (thiophen2yl) thiazolo [5 4d] thiazoleba...
Name: ManuscriptTitle, dtype: object
14906    Highly Efficient PerovskiteonSilicon Tandem So...
14907    Economically sustainable growth of smallscale ...
Name: ManuscriptTitle, dtype: object
14900    Series Interconnection of Monolithic 2Terminal...
14902    Blade coating of diketopyrrolopyrrole based or...
Name: ManuscriptTitle, dtype: object
3039    Highly Efficient Perovskite Solar Cells Based ...
3179    Revealing the Anisotropic Structural and Elect...
Name: ManuscriptTitle, dtype: object
916    The architecture of colloidal quantum dot sola...
920    Oriented Halide Perovskite Nanostructures and ...
Name: ManuscriptTitle, dtype: object
10129    Flexible encapsulation materials based on sili...
10139    The atomiclevel structure of bandgap engineere...
10169    Influence of hidden halogen mobility on local ...
Name: ManuscriptTitle, dtype: object
4474    Interfacial benzenethiol modification facilita...
6967    LowTemperature Phase Transformations of  in th...
Name: ManuscriptTitle, dtype: object
15627    Tandem Nenitzescu reaction/nucleophilic aromat...
15629    Transformations of 5Hydroxy1pyrrolines in Stro...
15636    Analysis of AC permittivity response measured ...

2234    PolarizationDependent Purcell Enhancement on a...
2363    Piezoelectricity and electrostriction of dye‐d...
Name: ManuscriptTitle, dtype: object
16392    Synthesis and Physical Properties of Asymmetri...
16396    An Unusual PseudoCoordination Polymer of Dithi...
Name: ManuscriptTitle, dtype: object
3071    Promoting the Efficiency and Stability of CsPb...
3089    SelfAssembly of CsPbBr 3 Perovskites in Microp...
3121    Statistical Paradigm for Organic Optoelectroni...
3129    Antibacterial Melamine Foams Decorated with in...
3130    Efficient photoand electroluminescence by trap...
3138    Developing the nextgeneration perovskite/Si ta...
Name: ManuscriptTitle, dtype: object
12854    A study of the crystal structures and the phas...
12856    Studies of microstructure and ruthenium valenc...
Name: ManuscriptTitle, dtype: object
17409    Employment of electrochemically synthesized TG...
17410    Adsorption and preconcentration of divalent me...
Name: ManuscriptTitle, dtype: object
14435    Scheelitetype rare earth vanadates TVO4 (T= Ho...
14448    Combat antimicrobial resistance emergence and ...
Name: ManuscriptTitle, dtype: object
8252    Temperature influence on morphological progres...
8281    Inorganic lead halide perovskite single crysta...
8282    Solution‐processed visible‐blind ultraviolet p...
Name: ManuscriptTitle, dtype: object
8189    Bulk Recrystallization for Efficient MixedCati...
8190    A low iontransfer resistance and high volumetr...
Name: ManuscriptTitle, dtype: object
12281    Photovoltaic polymers based on difluoroqinoxal...
12283    Highly efficient and stable blue‐light‐emittin...
Name: ManuscriptTitle, dtype: object
10108    CeO2–NiO Nanoflakes Assessment and Their Antic...
10111    Structural Magnetic Electrical and PhotoFenton...
10300    Allsolutionprocessed multilayer polymer/dendri...
Name: ManuscriptTitle, dtype: object
5802    Enhanced nucleation of atomic layer deposited ...
5803    Impact of Hole Transport Layer Surface Propert...
Name: ManuscriptTitle, dtype: object
8009    Synthesis of Cu 2 (Zn 1− x Co x) SnS 4 nanocry...
8036    In situ study of the film formation mechanism ...
Name: ManuscriptTitle, dtype: object
17406    A novel classification of prostate specific an...
17411    Improving data and prediction quality of hight...
Name: ManuscriptTitle, dtype: object
16486    Capacitive deionization and electrosorption fo...
16492    Use of LDHchromate adsorption coproduct as an ...
Name: ManuscriptTitle, dtype: object
11288    Titania nanoparticleloaded mesoporous silica s...
11290    Modified strain and elastic energy behavior of...
Name: ManuscriptTitle, dtype: object
5861    Efficiency exceeding 11% in tandem polymer sol...
5863    Highly Efficient and Stable Perovskite Solar C...
5864    Tin Halide Perovskite (ASnX3) Solar Cells A Co...
5865    The Role of Grain Boundaries on Ionic Defect M...
Name: ManuscriptTitle, dtype: object
6458    Infrared spectroscopic study of vibrational mo...
6461    Ionic Current Mn KEdge Xray Absorption Spectra...
Name: ManuscriptTitle, dtype: object
14628    Fabrication of monolithic bidirectional switch...
14629    Overlay accuracy limitations of soft stamp UV ...
Name: ManuscriptTitle, dtype: object
14633    Synthesis characterization and electrochemical...
14640    Sizedependent optical edge shifts and electric...
14641        Towards a roomtemperature polariton amplifier
Name: ManuscriptTitle, dtype: object
6504    Emission decay pathways sensitive to circular ...
6505    On the Molecular Origin of Photoluminescence o...
Name: ManuscriptTitle, dtype: object
14161    Crystalline Structure Study of Double Perovski...
14170    Heteroepitaxial growth of Cu2O thin film on Zn...
14191    Impact of grain boundary structures on trappin...
Name: ManuscriptTitle, dtype: object
14122    New proton conducting nanocomposite membranes ...
14125    Adams MA see AV Belushkin Adams MA see R. Hemp...
14152    ‘Kusha’(eragrostis cynosuroids) A source of ac...
14197         Sol–gel electrochromic WO3 coatings on glass
Name: ManuscriptTitle, dtype: object
14153    Structural morphological and electrical invest...
14157    Application of CdSe/ZnS/CdS/ZnS core–multishel...
14200    Timeresolved spectroscopy of Sm3+ in silica an...
14201    Study of refractive index and physical thickne...
Name: ManuscriptTitle, dtype: object
10303    Performance enhancement of diindenoperylenebas...
10304    Correlating photocurrent spectra and electrica...
Name: ManuscriptTitle, dtype: object
16976    Purified high‐sulfur coal as a fuel for direct...
16988    A comprehensive analysis on elastic mechanical...
17011    Photophysical electrochemical and electrochrom...
17020    SiO2@ Al2O3 coreshell nanoparticles based molt...
Name: ManuscriptTitle, dtype: object
10517    Synthesis crystal structure and properties of ...
17282    Rational use of ligand to shift the UV–vis spe...
Name: ManuscriptTitle, dtype: object
17331    Diagnosis of perovskite solar cells through ab...
17359    Anomalous thermal conductivity in amorphous ni...
Name: ManuscriptTitle, dtype: object
7565     Chemical control of holedoped superconductivit...
15640    Secondary electron microscopy dopant contrast ...
Name: ManuscriptTitle, dtype: object
6979    Quantum reflection from a solid surface at nor...
6998                     Chiral singlewall gold nanotubes
Name: ManuscriptTitle, dtype: object
3782    Absolute photoluminescence quantum yields of I...
3793    Sizedependent electron transfer from colloidal...
3795    Fully efficient direct YbtoEr energy transfer ...
Name: ManuscriptTitle, dtype: object
3791    Absorption Fsum rule for the exciton binding e...
3830    Exciton gating and triplet deshelving in singl...
Name: ManuscriptTitle, dtype: object
830    Synthesis and spectroscopy of silverdoped PbSe...
831    Stereoelectronic Effects on the Binding of Neu...
Name: ManuscriptTitle, dtype: object
10687    Oxide planar p–n heterojunction prepared by lo...
10698    Formamidiniumbased planar heterojunction perov...
Name: ManuscriptTitle, dtype: object
10118    Photocurrent Enhancement of CdSe QuantumDot Se...
10120    Improved Field Emission of ThreeDimensional Si...
Name: ManuscriptTitle, dtype: object
888     Formation of LongLived Color Centers for Broad...
5637    Fabry–Pérot Oscillation and Room Temperature L...
Name: ManuscriptTitle, dtype: object
10085    Synthesis of Sb2E3 (E= S Se) Nanorods with a F...
10086    Enhanced Photocurrent from Organic PolymersBas...
10286    Optical Modulation of Amplified Emission in a ...
Name: ManuscriptTitle, dtype: object
16771    A computational investigation on structural me...
16781    Structural Magnetic and Magnetocaloric Propert...
Name: ManuscriptTitle, dtype: object
16867    Cubic PbGeO3 perovskite oxide a compound with ...
16868    Putting DFT to the trial First principles pres...
Name: ManuscriptTitle, dtype: object
17344    Luminescent Copper (I) complexes as promising ...
17347    Colloidal Synthesis of ZnS CdS and Zn x Cd1−x ...
Name: ManuscriptTitle, dtype: object
2644    Lattice parameter and energy band gap of cubic...
2654    Ordenamento induzido por tensão na liga de InGaAs
Name: ManuscriptTitle, dtype: object
13198    Optical isolation via onedimensional magnetoph...
13204    MAPLEdeposited PFO films influence of the lase...
13208    Novel application of MgF2 as a back reflector ...
Name: ManuscriptTitle, dtype: object
13187    How well do implicit solvation models represen...
13202    Timeresolved fluorescence polarization anisotr...
13211    Hightemperature plastic deformation and acoust...
Name: ManuscriptTitle, dtype: object
5179    Defect tolerance in methylammonium lead triiod...
5180    Influence of Electrode Interfaces on the Stabi...
Name: ManuscriptTitle, dtype: object
11190    Semicoordination bond breaking and halogen bon...
11192    Synthesis of ultrathin perovskite nanowires vi...
Name: ManuscriptTitle, dtype: object
4669    Fluorescence imaging in vivo at wavelengths be...
4673    Perowskitoxid‐Elektroden zur leistungsstarken ...
Name: ManuscriptTitle, dtype: object
15157    Efficient photoinduced energy transfer mediate...
15158    Decoupling fluorescence and photochromism in b...
15163    A Unique Case of Oxidative Addition of Interha...
15168    Precise Control of Intramolecular Charge‐Trans...
Name: ManuscriptTitle, dtype: object
5950    Low Current Density Driving Leads to Efficient...
6015    A facile surface passivation enables thermally...
Name: ManuscriptTitle, dtype: object
5945    Advances in Quantum‐Confined Perovskite Nanocr...
5989    Dopant‐free hole transporting polymers for hig...
Name: ManuscriptTitle, dtype: object
6174    Key growth parameters for the electrodepositio...
6190    Reversible ionic polarization in metal halide ...
Name: ManuscriptTitle, dtype: object
1569    From Bulk to Surface Sodium Treatment Reduces ...
1570      Strategies toward Stable Perovskite Solar Cells
Name: ManuscriptTitle, dtype: object
15454    A rational design strategy for an extremely de...
15469    How Machine Learning Accelerates the Developme...
15497    Ab Initio High Pressure and Temperature Invest...
Name: ManuscriptTitle, dtype: object
15424    Role of CuAlO2 as an absorber layer for solar ...
15488    Influence of Group IVTe Alloying on Nanocompos...
15495    HighTemperature and HighPressure Study of Elec...
Name: ManuscriptTitle, dtype: object
16762    Spin transistors vs. conventional transistors ...
16770    Ab Initio Investigation on Electronic Magnetic...
16782    Microstructural Analysis Magnetic Properties a...
Name: ManuscriptTitle, dtype: object
12562    Cooperative effect of Pt–Rh/Ba/Al and CuZSM5 c...
12570    Electrodeposited Repromoted Ni foams as a cata...
Name: ManuscriptTitle, dtype: object
4477    Organic solar cells with nearunity charge gene...
4481    Dopantfree polymeric hole transport materials ...
Name: ManuscriptTitle, dtype: object
576    Exceptional electrocatalytic oxygen evolution ...
578    Hot carriers perspective on the nature of trap...
Name: ManuscriptTitle, dtype: object
4028    Electronic properties of the interfaces betwee...
4044    Efficient White‐Electrophosphorescent Devices ...
4053    Domain‐Size‐Dependent Residual Stress Governs ...
Name: ManuscriptTitle, dtype: object
4007    Spectroscopy of Resonant Intermediate States f...
4011    Flexible filter‐free narrowband photodetector ...
4015    Dual coordination of Ti and Pb using bilinkabl...
4039    Quantitative analysis of bulk heterojunction f...
Name: ManuscriptTitle, dtype: object
3956    Biexciton Generation and Dissociation Dynamics...
3957    Monitoring the phase formation of coevaporated...
Name: ManuscriptTitle, dtype: object
1095    Separation of empty and waterfilled singlewall...
8734    Correction Facile synthesis of stable water so...
Name: ManuscriptTitle, dtype: object
1997    Jointly tuned plasmonic–excitonic photovoltaic...
2014    Ligand exchange at a covalent surface enables ...
Name: ManuscriptTitle, dtype: object
1933    Colloidal quantum dot solids for solutionproce...
2093    Determining the internal quantum efficiency of...
2132    Coupling Perovskite Quantum Dot Pairs in Solut...
Name: ManuscriptTitle, dtype: object
273                               Quantum dots on demand
282    Detection of gamma photons using solutiongrown...
Name: ManuscriptTitle, dtype: object
9465    Carbonbased allinorganic perovskite solar cell...
9491    Effect of Cu/Ga ratio on deeplevel defects in ...
9494    Quantitative study of electron tunneling dynam...
Name: ManuscriptTitle, dtype: object
4183    Efficient and ambient‐air‐stable solar cell wi...
4193    Layered germanium hybrid perovskite bromides i...
7505    Hydrogeninduced  rehybridization in epitaxial ...
Name: ManuscriptTitle, dtype: object
11941    Engineering solar cells based on correlative X...
11944    Thermal annealing influence on structural magn...
Name: ManuscriptTitle, dtype: object
7667    Firstprinciples investigation of the structura...
7677    Nearly 100% energy transfer at the interface o...
Name: ManuscriptTitle, dtype: object
13801    Induced conductivity in solgel ZnO films by pa...
13879    Raman Spectroscopy Studies on the Barocaloric ...
Name: ManuscriptTitle, dtype: object
13802    Structural electronic and elastic properties o...
13804    Thicknessdependent magnetic and electrical tra...
Name: ManuscriptTitle, dtype: object
1372    Semiconducting polymer nanospheres in aqueous ...
1509    53% Efficient Red Emissive Carbon Quantum Dots...
Name: ManuscriptTitle, dtype: object
1969     Metal halide perovskites for energy applications
2029    Polaronenhanced polariton nonlinearity in lead...
2065    Implications of the negative capacitance obser...
Name: ManuscriptTitle, dtype: object
6775              Hybrid organicinorganic polariton laser
6834    Taguchi grey relational optimization of sol–ge...
Name: ManuscriptTitle, dtype: object
6792    Ultrabright nearinfrared perovskite lightemitt...
6809    Optical determination of ShockleyReadHall and ...
6819    Colloidal antimony sulfide nanoparticles as a ...
Name: ManuscriptTitle, dtype: object
6117    Influence of the potassium chloride concentrat...
6126    Theory of impedance spectroscopy of ambipolar ...
Name: ManuscriptTitle, dtype: object
17179    Grain size and sample size interact to determi...
17184    Activating Inert MXenes for Hydrogen Evolution...
17185    Hydrogen Evolution Reaction Unraveling the Fac...
17186    Machine learning–based charge transport comput...
17187    Impact of phosphorescent sensitizers and morph...
Name: ManuscriptTitle, dtype: object
1162    Electron–Hole Binding Governs Carrier Transpor...
8819    Nonlinear optical figures of merit of processi...
Name: ManuscriptTitle, dtype: object
1098    Direct detection of circularly polarized light...
1146    Cu2Se and Cu Nanocrystals as Local Sources of ...
1269    The in‐gap electronic state spectrum of methyl...
Name: ManuscriptTitle, dtype: object
14809    Improving electron transport in Gadoped Zn0. 7...
14811    Effect of a postdeposition anneal on Al2O3/Si ...
Name: ManuscriptTitle, dtype: object
3454    Controlled Synthesis of LeadFree and Stable Pe...
3455    Controlled synthesis of leadfree cesium tin ha...
Name: ManuscriptTitle, dtype: object
2123    Wiringup hydrogenase with singlewalled carbon ...
2124    Photogenerated free carrier dynamics in metal ...
Name: ManuscriptTitle, dtype: object
1978    Systematic investigation of the impact of oper...
2146    NanoscaleResolved SurfacetoBulk Electron Trans...
Name: ManuscriptTitle, dtype: object
16954    LeadFree Potassium Alloyed Cs2AgBiBr6 Tunable ...
16979    Enhanced dissociation of excitons and charge t...
16986    A first‐principles prediction of thermophysica...
16996    Slightly ruthenium doping enables better alloy...
Name: ManuscriptTitle, dtype: object
13076    Unusual porous crystals via catenation of 1D l...
13077    Discrete and polymeric complexes of a macrocyc...
Name: ManuscriptTitle, dtype: object
15412    Highly efficient quasicubic structured perovsk...
15512    Correction to Electronic Structure Optical and...
Name: ManuscriptTitle, dtype: object
875    Asynchronous photoexcited electronic and struc...
876    Electron Accumulation Induces Efficiency Bottl...
Name: ManuscriptTitle, dtype: object
16118    Comparison of bandfitting and Wannierbased mod...
16138    Publications RepositoryHelmholtzZentrum Dresde...
Name: ManuscriptTitle, dtype: object
16074    Variable switching frequency control of distri...
16120    FTIR ellipsometry study on RF sputtered permal...
Name: ManuscriptTitle, dtype: object
5200    SMART perovskite growth enabling a larger rang...
5237    Temperature coefficients of perovskite photovo...
Name: ManuscriptTitle, dtype: object
14456    Domain wall contributions to the properties of...
14457    Pb (Mg1/3Nb2/3)O3 and (1− x)Pb(Mg1/3Nb2/3)O3−x...
Name: ManuscriptTitle, dtype: object
17326    Highly Efficient UV–Visible Photocatalyst from...
17342    An efficient and stable leadfree organic–inorg...
Name: ManuscriptTitle, dtype: object
5734    Nanofiber‐Directed Anisotropic Self‐Assembly o...
5832    27.6% Perovskite/c‐Si Tandem Solar Cells Using...
Name: ManuscriptTitle, dtype: object
5757    Charge generation and recombination in an orga...
5759    Rationalizing the Molecular Design of Hole‐Sel...
Name: ManuscriptTitle, dtype: object
5699    1D‐2D Synergistic MXene‐Nanotubes Hybrids for ...
5707    Ultrasensitive SERS substrate integrated with ...
Name: ManuscriptTitle, dtype: object
5563    Highperformance MoSe2 homojunction infrared ph...
5569    Polymerase chain reactionfree sampletoanswer b...
Name: ManuscriptTitle, dtype: object
5547    The effect of Sr doping on structural and diel...
5666    Bridging the Interfacial Contact for Improved ...
Name: ManuscriptTitle, dtype: object
17418    Impact of the structural parameters on the pho...
17420    Multipurpose Fully Integrated 128  128 EventDr...
Name: ManuscriptTitle, dtype: object
14489    The superstructure and superconductivity of Ru...
14504    High voltage gain inverters from artificially ...
14505    A novel lowcost highefficiency micromachined s...
Name: ManuscriptTitle, dtype: object
58     Electronhole diffusion lengths exceeding 1 mic...
616       Selfassembled pbse nanowire Perovskite hybrids
Name: ManuscriptTitle, dtype: object
17267    Trends in the Development of Hydroxyapatite fr...
17272    Dielectric and magnetic properties of BaFe11.7...
Name: ManuscriptTitle, dtype: object
817     Lewis base passivation mediates charge transfe...
1036    Functional twodimensional coordination polymer...
Name: ManuscriptTitle, dtype: object
12715    Selective oxidation of fatty alcohol ethoxylat...
12716    Novel design of photocatalyst coaxial ferromag...
12725    Oxygen surface mobility and isotopic exchange ...
Name: ManuscriptTitle, dtype: object
3714    Tailoring the surface morphology and phase dis...
3716    Manipulation of Band Alignment in TwoDimension...
Name: ManuscriptTitle, dtype: object
7687    Fully airprocessed dynamic hotairassisted M Cs...
7688    Triplet sensitization by lead halide perovskit...
Name: ManuscriptTitle, dtype: object
7659      Symmetry breaking and spin lattice coupling in
7662    Origin of intense bluegreen emission in  thin ...
7686    Unleashing the power of materials science for ...
Name: ManuscriptTitle, dtype: object
8468    Colloidal quantum dot solar cell electrical pa...
8488    Superior performance of V2O5 as hole selective...
Name: ManuscriptTitle, dtype: object
17393               Xray generation using carbon nanotubes
17395    Modern coin debasement discovered by combined ...
17401    Structural Colors on Al Surface via Capped CuS...
17402    Increasing depth penetration in biological tis...
17412    Topology Automated ForceField Interactions (TA...
Name: ManuscriptTitle, dtype: object
17392                           Soft optical metamaterials
17400    Stability assessment of pin perovskite photovo...
17403    Drug quantification in turbid media by fluores...
Name: ManuscriptTitle, dtype: object
9950    Continuous broadband MWP truetime delay with P...
9951    Fabrication and characterization of highqualit...
9952    HighBandwidth organic photodetector analyzed b...
Name: ManuscriptTitle, dtype: object
10884    Hysteresis phenomena in perovskite solar cells...
10888    Ordered networks of ZnOnanowire hierarchical u...
Name: ManuscriptTitle, dtype: object
9629    Curvaturemediated surface accessibility enable...
9631    Extending roGFP emission via forstertype reson...
Name: ManuscriptTitle, dtype: object
9627    Facile and quantitative estimation of strain i...
9639    Photoluminescence waveguiding in CdSe and CdTe...
Name: ManuscriptTitle, dtype: object
10736    Fabrication and performance evaluation of new ...
10748    Anionmediated synthesis of monodisperse silver...

10117    Conductivity Properties of SingleWalled Carbon...
10122    Electric Property Change of SingleWalled Carbo...
Name: ManuscriptTitle, dtype: object
15784    Positively charged membranes for dye/salt sepa...
15789    Automated portable highpressure setup for stud...
Name: ManuscriptTitle, dtype: object
7720     Correlating Nanoscale Morphology with Device P...
11181    Multifunctional Properties of a Zn (II) Coordi...
Name: ManuscriptTitle, dtype: object
2053              A graphenebased hot electron transistor
2057    Monolithically Integrated Perovskite Semicondu...
2060    Photosensitization of ZnO nanowires with CdSe ...
Name: ManuscriptTitle, dtype: object
15255    Determination of the local environment of sili...
15258    Hightemperature thermoelectric properties of S...
Name: ManuscriptTitle, dtype: object
10424    Hyperfine interaction of the CuCl4 (NH3) 22cen...
10431    Efficient calculation of excitonic effects in ...
Name: ManuscriptTitle, dtype: object
1491    Hybrid Modulation‐Doping of Solution‐Processed...
1495    Correction High‐Performance ZnO Transistors Pr...
Name: ManuscriptTitle, dtype: object
14258    VacancyDriven Noncubic Local Structure and Mag...
14259    Integrated source of spectrally filtered corre...
Name: ManuscriptTitle, dtype: object
14268    Ultrafast transient absorption spectroscopic (...
14281    A helical salicyladoximebased manganese triang...
Name: ManuscriptTitle, dtype: object
1100    Spatially Resolved Persistent Photoconductivit...
1288    Crosslinked remote‐doped hole‐extracting conta...
Name: ManuscriptTitle, dtype: object
17099    Sensitizing effect of nanocrysrtalline TiO2 fi...
17103    Toxicity response of highly colloidal bioactiv...
Name: ManuscriptTitle, dtype: object
776    Guanidiniumformamidinium lead iodide a layered...
796    Aqueous synthesis of zinc blende CdTe/CdS magi...
Name: ManuscriptTitle, dtype: object
3538     Sodium DopingEnhanced Emission Efficiency and ...
15295    From tetragonal to cubic perovskite phase stru...
Name: ManuscriptTitle, dtype: object
6386    Slow Electron Cooling Dynamics Mediated by Ele...
6388    Exciton separation in CdS supraparticles upon ...
Name: ManuscriptTitle, dtype: object
2919    Nonvolatile multistates memories for highdensi...
2928    Enhancing the efficiency and stability of PbS ...
Name: ManuscriptTitle, dtype: object
821     2D intrinsic ferromagnets from van der Waals a...
5735    Neodymium‐sensitized nanoconstructs for near‐i...
Name: ManuscriptTitle, dtype: object
10094    Synthesis and TFT properties of fluorenyl core...
10231    54‐1 Invited Paper Development of Electrolumin...
Name: ManuscriptTitle, dtype: object
5705    Control of CH3NH3PbI3 Perovskite Nanostructure...
5709    Competitive reaction pathway for site‐selectiv...
5711    Self‐Assembled Ruddlesden–Popper/Perovskite Hy...
Name: ManuscriptTitle, dtype: object
3997     Pseudohalide (SCN–)Doped MAPbI3 Perovskites A ...
15792    Pressureinduced transition in a heavy fermion ...
Name: ManuscriptTitle, dtype: object
14091    Thermoelectric properties of Czochralskigrown ...
14093    Lightharvesting fullerenes for organic solar c...
Name: ManuscriptTitle, dtype: object
6272     Barrierless Slow Dissociation of Photogenerate...
11431    Conjugated poly (azomethine) s via simple ones...
Name: ManuscriptTitle, dtype: object
4626    Gold doping of silver nanoclusters a 26‐Fold e...
4628    Effect of Zinc‐doping on the Reduction of the ...
Name: ManuscriptTitle, dtype: object
6822    A Variable Temperature Synchrotron Xray Diffra...
6845    Optical electrochemical and photocatalytic pro...
Name: ManuscriptTitle, dtype: object
3279    Critical Coupling of Visible Light Extends Hot...
3281    Polymercontrolled growth and wrapping of perov...
3283    Controlling the Thermoelectric Properties of N...
Name: ManuscriptTitle, dtype: object
12647    Carniti P. see Gervasini A. 201 Casagrande L. ...
12648    Reactivity of steam in exhaust gas catalysis. ...
Name: ManuscriptTitle, dtype: object
14271    Evaluation of Al2O3 and ZrO2 addition to reduc...
14282    Transport and magnetic properties of La0. 8Ce0...
Name: ManuscriptTitle, dtype: object
4926    Enhanced mobility in PbS quantum dot films via...
4927    PCBMblended chlorobenzene hybrid antisolvent e...
Name: ManuscriptTitle, dtype: object
17499    Threedimensionally ordered macroporous materia...
17500    Non‐Fouling Biodegradable Poly (ϵ‐caprolactone...
17511    Efficient continuouswave nonlinear frequency c...
Name: ManuscriptTitle, dtype: object
5554    Modification of NiOx hole transport layers wit...
5556    Structural and electrical transport properties...
Name: ManuscriptTitle, dtype: object
5736    Self‐Promoting Energy Storage in Balsa Wood‐Co...
5742    Highly Passivated n‐Type Colloidal Quantum Dot...
Name: ManuscriptTitle, dtype: object
16405    Elucidating the Effect of Pressure on Structur...
16415    Enhanced Stability of Perovskite Solar Cells u...
Name: ManuscriptTitle, dtype: object
6680    Dinaphthotetrathienoacenes Synthesis Character...
6683    Gas‐assisted spray coating of perovskite solar...
Name: ManuscriptTitle, dtype: object
7086    Quantum dots in a metallopolymer host studies ...
7087    Full electronic structure across a polymer het...
Name: ManuscriptTitle, dtype: object
3751    Defect passivation for red perovskite lightemi...
3767    Modulating the Carrier Relaxation Dynamics in ...
Name: ManuscriptTitle, dtype: object
5186    Improving lowbandgap tin–lead perovskite solar...
5236    Transparent ohmic contacts for solutionprocess...
Name: ManuscriptTitle, dtype: object
3173    Ionic Liquids Modulating CsPbI3 Colloidal Quan...
3185    AllNanoTiO2 Compact Film for HighPerformance D...
Name: ManuscriptTitle, dtype: object
10825    Composition dependent optical structural and p...
10827    Interface structure precursor rheology and die...
Name: ManuscriptTitle, dtype: object
2061    Nonequilibriumplasmasynthesized ZnO nanocrysta...
2072    Formation of nanopatterned polymer blends in p...
Name: ManuscriptTitle, dtype: object
17419    Interfacial electron transfer on cytochromec s...
17421    Updates from the SPADnet project (fully digita...
Name: ManuscriptTitle, dtype: object
878    Spectroscopic investigation of the effect of m...
955    A chargeorbital balance picture of doping in c...
956    Measuring charge carrier diffusion in coupled ...
Name: ManuscriptTitle, dtype: object
16020    Preparation of (1− x%)(Na0. 5Bi0. 5) TiO3–x% S...
16021    Structural and photophysical characterization ...
16022    Novel synthetic approach to the preparation of...
Name: ManuscriptTitle, dtype: object
12560    Optically responsive delivery platforms From t...
12568    The effect of space time on Co/CeO2 catalyst d...
Name: ManuscriptTitle, dtype: object
8386    Rare‐earth metal ions doped graphene quantum d...
8445    In situ detection of soot nanoparticles by tim...
Name: ManuscriptTitle, dtype: object
17375    Systematic review elucidating the generations ...
17377    Innovatory role of nanomaterials as biotools f...
Name: ManuscriptTitle, dtype: object
11871    A bifunctional lewis base additive for microsc...
11873    High members of the 2D RuddlesdenPopper halide...
Name: ManuscriptTitle, dtype: object
9074    Nitrogen incorporation and optical studies of ...
9091    Surface electronic structure of nitrogendoped ...
Name: ManuscriptTitle, dtype: object
5259    Exciton SelfTrapping for White Emission in 100...
5260    Engineering Surface Orientations for Efficient...
Name: ManuscriptTitle, dtype: object
10102    Enhancement of photocurrent of dyesensitized s...
10105    Eucalyptus Concoction Mediated Synthesis of Go...
10110    PhotoFenton activity of magnesium substituted ...
Name: ManuscriptTitle, dtype: object
9590    Monitoring the effect of asymmetrical vertical...
9594    Sizedependent alternation of magnetoresistive ...
Name: ManuscriptTitle, dtype: object
1392    On the Question of the Need for a Built‐In Pot...
1396    Measurements of optical electric field intensi...
Name: ManuscriptTitle, dtype: object
12947    A synthetic approach to a fullerenerich dendro...
12953    Efficacious elimination of intramolecular char...
Name: ManuscriptTitle, dtype: object
17607    Electrochemical sensing of epinephrine on a ca...
17608    Desilication of low alumina to caustic liquor ...
Name: ManuscriptTitle, dtype: object
11887    Highly crystalline synthesis of tellurene shee...
11940    Stability of organic solar cells with PCDTBT d...
Name: ManuscriptTitle, dtype: object
11892    Excitonpolaron spectral structures in twodimen...
11912    Strong magnetochiral dichroism for visible lig...
Name: ManuscriptTitle, dtype: object
10910    Holetransport materials with greatlydiffering ...
10928    Precursor nonstoichiometry to enable improved ...
Name: ManuscriptTitle, dtype: object
13787    Slater halfoccupation technique revisited the ...
13788    Firstprinciples determination of bandtoband el...
Name: ManuscriptTitle, dtype: object
8554     An extensible and tunable fullopaque cascade s...
10402    Spectroscopy and control of nearsurface defect...
Name: ManuscriptTitle, dtype: object
6890    Simultaneous observation of free and defectbou...
6892    Strainenhanced dzyaloshinskii–moriya interacti...
6893           Currentdriven coherent skyrmion generation
Name: ManuscriptTitle, dtype: object
4849    Engineering Srdoping for enabling longterm sta...
4850    Deciphering the role of quantum dot size in th...
Name: ManuscriptTitle, dtype: object
5526    Optical response and structural properties of ...
5532    Investigation of the effect of sintering tempe...
Name: ManuscriptTitle, dtype: object
1949    Tailored interfaces of unencapsulated perovski...
1996    Colloidal CdSe1–xSx Nanoplatelets with Narrow ...
1998    Optimization of band structure and quantumsize...
2122    Prolonging charge separation in P3HT− SWNT com...
2128    Quantum confined electron–phonon interaction i...
Name: ManuscriptTitle, dtype: object
2003     Crosslinked C60 Polymer Breaches the Quantum Gap
2010    Programmable metal/semiconductor nanostructure...
Name: ManuscriptTitle, dtype: object
15046    Interfacial engineering of halide perovskites ...
15047    Colloidal metal oxide nanocrystals as charge t...
Name: ManuscriptTitle, dtype: object

16775    Structural Microstructural and Magnetic Studie...
16779    Magnetocaloric Properties of La0.85Ag0.15MnO3 ...
Name: ManuscriptTitle, dtype: object
15984            Aging memory and oxygen vacancies in PLZT
15985    Memory effects in dielectric and anelastic mea...
Name: ManuscriptTitle, dtype: object
11880    Thermal transport in ZnO nanocrystal networks ...
11924    Hybrid perovskite solar cells In situ investig...
Name: ManuscriptTitle, dtype: object
12004    Deep‐blue low‐threshold amplified spontaneous ...
12005    Efficient Solution‐Processed Inverted Organic ...
Name: ManuscriptTitle, dtype: object
11951    Band Alignments in InxGa1–xP/GaAs Heterostruct...
11968    Al‐Doped ZnO nanowires by electrochemical depo...
Name: ManuscriptTitle, dtype: object
12010    Formation of High‐Pressure Phase of Titanium D...
12053    InSitu NanoAuger Probe of ChlorideIons during ...
Name: ManuscriptTitle, dtype: object
7038    Direct coherent multiink printing of fabric su...
7040    Heterojunction oxide thinfilm transistors with...
Name: ManuscriptTitle, dtype: object
9307    Molecular dynamics study of the interactions o...
9329    Preparation and characterization of ammoniumfu...
Name: ManuscriptTitle, dtype: object
8770    Highly luminescent and ultrastable cesium lead...
8774    Novel silicon compatible pWS 2 2D/3D heterojun...
Name: ManuscriptTitle, dtype: object
3357    Efficient and Stable Blue and RedEmitting Pero...
3377    Electrocrystallization of epitaxial zinc oxide...
3483    Pulsed Laser Deposition of Cs2AgBiBr6 from Mec...
Name: ManuscriptTitle, dtype: object
2002    Highcurvature nanostructuring enhances probe d...
2007    Engineering directionality in quantum dot shel...
2119    Twodimensional covalent crystals by chemical c...
2126    Confirmation of KMomentum Dark Exciton Vibroni...
Name: ManuscriptTitle, dtype: object
16267    Manipulation of the exciton diffusion length o...
16275    Studies on the synthesis and characterization ...
Name: ManuscriptTitle, dtype: object
17298    Facile synthesis of magnetite nanocubes using ...
17305    1 1 and 1 2 Complexes of Mercury (II) Halides ...
Name: ManuscriptTitle, dtype: object
16818    Ab initio study of structural elastic and elec...
16820    Effect of hydrostatic pressure on the structur...
Name: ManuscriptTitle, dtype: object
7463    Theoretical study of straininduced ordering in...
7476    Monolayer honeycomb structures of groupIV elem...
Name: ManuscriptTitle, dtype: object
4133    Operating Modes of Sandwiched Light‐Emitting E...
4136    Reversible formation of gold halides in single...
Name: ManuscriptTitle, dtype: object
4551    Hot Carrier Generation and Extraction of Plasm...
4568    Fourwave mixing in perovskite photovoltaic mat...
4573    Rational design of efficient palladium catalys...
Name: ManuscriptTitle, dtype: object
1120     Random lasing with systematic threshold behavi...
11173    An unusual interweaving in a 3fold interpenetr...
Name: ManuscriptTitle, dtype: object
825     Universal Transients in Polymer and Ionic Tran...
5571    Sampletoanswer isolation and mRNA profiling of...
Name: ManuscriptTitle, dtype: object
8771     Enhancement of photodetection characteristics ...
12941    Efficient passivated phthalocyaninequantum dot...
12942    Lithiumrich sulfide/selenide cathodes for next...
Name: ManuscriptTitle, dtype: object
986     Electronic Properties of a 1D Intrinsic/pDoped...
1072    The subtle chemistry of colloidal quantumconfi...
Name: ManuscriptTitle, dtype: object
16237    Piezoelectricity from Elastic and Dielectric M...
16238    Development of geopolymers for catalyst suppor...
17321    Transport of salicylic acid through supported ...
17324    Bandgap Engineering in Novel Fluorite‐Type Rar...
17329    Computational Prediction of a Novel Superhard ...
17332    Vein detection with near‐infrared organic phot...
17333    Integration of largearea optical imagers for b...
17337    Alkali metal doped nickel oxide clusters A den...
17338    Phonon stability electronic structure results ...
17339    A DFT investigation on electronic structure ch...
17343    Ultrabroadband thermal radiator for daytime pa...
17348    Physical Vapor Deposited [CoCd(dtc)2]/SnO2 Dua...
17349    PVA/Gd2O3@ Zno Nanocomposite Films as New UvBl...
17351    Characterization of Cu2ZnSnSe4 Thin Films Sele...
17354    Halide perovskite materials as chemical playgr...
17355    Experimental verification of optically optimiz...
17366    Impact of single pMOSFET dielectric degradatio...
Name: ManuscriptTitle, dtype: object
16187    Electrical transport and specific heat propert...
16195    Structure and energetics of ZrC (100)|| cZrO2 ...
16207    Review of perovskitestructure related cathode ...
16234    Effect of cobalt doping on structural optical ...
16245    Current status and prospects on chemical struc...
16252    Interaction of alkali alkaline earth and trans...
Name: ManuscriptTitle, dtype: object
16210    Hopping and clustering of oxygen vacancies in ...
16221    An EXAFS study of RuSr {sub 2} GdCu {sub 2} O ...
16231    Oxygen ordering and mobility in ReBa sub 2 Cu ...
16248    Detection and spectroscopy of the ν1+ ν3 band ...
Name: ManuscriptTitle, dtype: object
16224    Dopinginduced enhancement of the switch rate o...
16402    Tunable Etching of CVD Graphene for Transfer P...
Name: ManuscriptTitle, dtype: object
9956    Capacitive scanning dilatometry and frequencyd...
9958    Nanocrystal quantum dot devices How the lead s...
Name: ManuscriptTitle, dtype: object
7909     Electron and hole transfer from indium phosphi...
12314    Spectroscopic properties and JuddOfelt analysi...
Name: ManuscriptTitle, dtype: object
8527    Rear side sphere gratings for improved light t...
8560    Increased homogeneity and opencircuit voltage ...
Name: ManuscriptTitle, dtype: object
1446    High Quality Inkjet Printed‐Emissive Nanocryst...
1449    Solution‐processed tin‐based perovskite for ne...
Name: ManuscriptTitle, dtype: object
15822    Impedance spectroscopy study of electrochromis...
15823    Impedance spectroscopy study of anodic growth ...
Name: ManuscriptTitle, dtype: object
2563    Position of defects with respect to domain wal...
2564    Relaxor behavior and electromechanical propert...
Name: ManuscriptTitle, dtype: object
12539    Synthesis and luminescence properties of Eu3+ ...
12547    Solidliquid phase transition activated by opti...
Name: ManuscriptTitle, dtype: object
2015    QuantumSizeEffect Tuning Enables Narrowband IR...
2048    Phase selection enabled formation of abrupt ax...
Name: ManuscriptTitle, dtype: object
8356    Perovskite excitonics primary exciton creation...
8403    Light Emission from Low‐Dimensional Pb‐Free Pe...
Name: ManuscriptTitle, dtype: object
10862    Solutionprocessed resistive switching memory d...
10873    Transformation of PbI 2 PbBr 2 and PbCl 2 salt...
Name: ManuscriptTitle, dtype: object
17233    Regioisomers of singly bridged calix [6] crown...
17234    Structural chemistry of layered lead halide pe...
Name: ManuscriptTitle, dtype: object
4317    Acoustic detection of phase transitions at the...
4329    Simultaneous improvement of charge generation ...
Name: ManuscriptTitle, dtype: object
2513    On MottSchottky analysis interpretation of cap...
9818    [Cu23(PhSe)16(Ph3P)8(H)6]·BF4 AtomicLevel Insi...
Name: ManuscriptTitle, dtype: object
2466    Dependence of negative differential resistance...
2608    Long minority carrier lifetime in Aucatalyzed ...
Name: ManuscriptTitle, dtype: object
1669    Cobalt Single‐Atom‐Intercalated Molybdenum Dis...
1687    Rapid Synthesis of Bright ShapeControlled Larg...
Name: ManuscriptTitle, dtype: object
12893    Electrochemical topotactic oxidation of nonsto...
12894                    In situ reduction of (100) SrTiO3
Name: ManuscriptTitle, dtype: object
16835    Terahertz spin currents and inverse spin Hall ...
16837    Deposition uniformity and particle size distri...
Name: ManuscriptTitle, dtype: object
16832    Evaluation of the contributions to the effecti...
16838    Synthesis of a zinc–imidazole metal–organic fr...
Name: ManuscriptTitle, dtype: object
13405    Effect of processing by femtosecond pulsed las...
13407    Physicochemical tools toward a detailed unders...
Name: ManuscriptTitle, dtype: object
15108    Surface passivation of organometal halide pero...
15110    Photoconductivity of PbS/perovskite quantum do...
15113    Photonupconverters for blue organic lightemitt...
15114    Directional quantum dot emission by softstampi...
Name: ManuscriptTitle, dtype: object
15111    Synthesis of twodimensional phenylethylamine t...
15116    Ligandfree allinorganic metal halide nanocubes...
15117    Theoretical insights into C–H bond activation ...
Name: ManuscriptTitle, dtype: object
11452    Study of surface reactions during plasma enhan...
12660    Exsolution of Realloy catalysts with enhanced ...
Name: ManuscriptTitle, dtype: object
11585    DNAmediated threedimensional assembly of hollo...
11586    Multifunctional bismuth nanoparticles as thera...
11587    Defect Passivation of Mn2+Doped CsPbCl3 Perovs...
Name: ManuscriptTitle, dtype: object
11486    Optical depth profiling of strontium titanate ...
11512    Unusual B1–B2 transition in PbSe under high pr...
Name: ManuscriptTitle, dtype: object
8323    Nonlinear Optical Properties of Colloidal CH3N...
8324    Aggregation‐Induced Emission Features of Organ...
Name: ManuscriptTitle, dtype: object
8337    Double active layers constructed with halide p...
8341    Hybrid Perovskite Degradation from an Optical ...
Name: ManuscriptTitle, dtype: object
8321    Solution Coating of Superior Large‐Area Flexib...
8325    Perovskite Quantum Dots Embedded Composite Fil...
Name: ManuscriptTitle, dtype: object
8338    Aligning Transition Dipole Moment toward Light...
8339    Chirality Induced Crystal Structural Differenc...
8340        Gallium polymorphs phase‐dependent plasmonics
Name: ManuscriptTitle, dtype: object
8327    Highly Efficient Light Emitting Diodes Based o...
8411    Negative Thermal Quenching and Size‐Dependent ...
Name: ManuscriptTitle, dtype: object
8382    Halide perovskites a progress report on photon...
8399    Hybrid Plasmonic and Pyroelectric Harvesting o...
8417    Magnetic Manipulation of Spontaneous Emission ...
Name: ManuscriptTitle, dtype: object
8331    Polarization‐Sensitive Ultraviolet Detection f...
8372    Angle and polarization selective spontaneous e...
Name: ManuscriptTitle, dtype: object
8378    A‐Site Cation Engineering in 2D Ruddlesden–Pop...
8379    Optical Gain of Lead Halide Perovskites Measur...
Name: ManuscriptTitle, dtype: object
8353    Can trihalide Lead perovskites support continu...
8359    Organic Nanofibers Extending the Lasing Wavele...
Name: ManuscriptTitle, dtype: object
8371    Flexible Electronics Broadband Light Out‐Coupl...
8441    Twophotonenhanced threephoton absorption in tr...
Name: ManuscriptTitle, dtype: object
8404    Optoelectronic Synapses Based on Photo‐Induced...
8425    The Intrinsic Photoluminescence Spectrum of Pe...
Name: ManuscriptTitle, dtype: object
8369    Illumination‐Induced Halide Segregation in Gra...
8448    Transmission properties of one dimensional fra...
Name: ManuscriptTitle, dtype: object
14813                           Sliver/spl reg/solar cells
14864    Investigation of materials for hot carrier sol...
Name: ManuscriptTitle, dtype: object
7990    Identification of the physical origin behind d...
8086    The effect of structural dimensionality on car...
Name: ManuscriptTitle, dtype: object
13280    Polarization dependent excitation and high har...
13286    Strain Engineering A Pathway for Tunable Funct...
Name: ManuscriptTitle, dtype: object
13267    Ligandlength modification in CsPbBr3 perovskit...
13271                Nanostructured perovskite solar cells
Name: ManuscriptTitle, dtype: object
13337    Photoluminescence spectral position shift gove...
13348    Atom optics with Bose–Einstein condensates qua...
Name: ManuscriptTitle, dtype: object
13327    2D Perovskite Microoptics Enabled by Direct Fe...
13346    Thermopower and phase transition in YbPd2Si2 u...
Name: ManuscriptTitle, dtype: object
2757    Temperaturedependent tunneling electroresistan...
2768    Band alignment at  heterojunctions and electro...
Name: ManuscriptTitle, dtype: object
2655    CONDENSED MATTER STRUCTURAL MECHANICAL THERMAL...
2678    Microscopic investigation of the poly (9 9dioc...
Name: ManuscriptTitle, dtype: object
11091    Energy level alignment at interfaces in organi...
11092    The interface electronic properties of organic...
11094    Observation of filled states at the Fermilevel...
Name: ManuscriptTitle, dtype: object
887     Atomistic Insights into Activation and Degrada...
1026    Ultralowthreshold twophoton pumped amplified s...
Name: ManuscriptTitle, dtype: object
3294     PacketOriented Photonic Networks (Guest Editor...
12731    Citral hydrogenation on high surface area meso...
Name: ManuscriptTitle, dtype: object
4307    Low‐Bandgap Methylammonium‐Rubidium Cation Sn‐...
6855                       Axial plane optical microscopy
Name: ManuscriptTitle, dtype: object
9607    Subnanometer glass surface dynamics induced by...
9608    Mixed halide bulk perovskite triplet sensitize...
Name: ManuscriptTitle, dtype: object
3619     Crucial Contribution of Polarity for the Bulk ...
12646    Oxygen storage capacity of La1x Formula Not Sh...
Name: ManuscriptTitle, dtype: object
1025    Rearranging lowdimensional phase distribution ...
1048    Circularly Polarized Emission from Organic–Ino...
Name: ManuscriptTitle, dtype: object
12857    Doping studies of the magnetic cobaltocuprate ...
12867    Full Heusler alloys (Co2TaSi and Co2TaGe) as p...
Name: ManuscriptTitle, dtype: object
15354    Seed‐Mediated Synthesis of Colloidal 2D Halide...
15358    Color tunable organic lightemitting diodes usi...
Name: ManuscriptTitle, dtype: object
8133    Impact of local structure on halogen ion migra...
8134    Photodecomposition and thermal decomposition i...
Name: ManuscriptTitle, dtype: object
8101    Pt/C–LiCoO 2 composites with ultralow Pt loadi...
8103    Renewable acetic acid in combination with soli...
8137    Facile synthesis of Ge–MWCNT nanocomposite ele...
Name: ManuscriptTitle, dtype: object
8049    Efficient nonfullerene organic solar cells emp...
8146    Pushing efficiency limits for semitransparent ...
Name: ManuscriptTitle, dtype: object
7516    Ultrafast carrier dynamics in core and core/sh...
7526    Semiconductors II Surfaces interfaces microstr...
Name: ManuscriptTitle, dtype: object
3033    Silicon Nanocanyon Onestep bottomup fabricatio...
3133    Borondoped silicon diatom frustules as a photo...
Name: ManuscriptTitle, dtype: object
17086    AcetamidiniumMethylammoniumBased Layered Hybri...
17088    Ultrafast charge and triplet state formation i...
Name: ManuscriptTitle, dtype: object
11875    Gap states induce soft Fermi level pinning upo...
11914    Thermal stability of nanoscale ferroelectric d...
Name: ManuscriptTitle, dtype: object
11893     speciation and energytransfer dynamics in qua...
11908    Enhancement of magnetic properties in compress...
Name: ManuscriptTitle, dtype: object
15284    Effect of the chromophores structures on the p...
15949    Resistance of 2ZrO2· Y2O3 top coat in thermal/...
Name: ManuscriptTitle, dtype: object
806    Triazole bridges as versatile linkers in elect...
822    Tunable magnetism and extraordinary sunlight a...
Name: ManuscriptTitle, dtype: object
7083     Halide perovskite nanocrystal arrays Multiplex...
11178    Influence of angular dicarboxylate ligand on t...
Name: ManuscriptTitle, dtype: object
10008    The effect of doping in the electrochemical pe...
10009    The effect of doping in the electrochemical pe...
10010    Graph theory model and mechanism analysis of c...
Name: ManuscriptTitle, dtype: object
1336    High‐Rate and Selective CO2 Electrolysis to Et...
1357    Oxygen Vacancies Allow Tuning the Work Functio...
1477    High‐performance ZnO transistors processed via...
Name: ManuscriptTitle, dtype: object
1359    Switching the Electronic Properties of ZnO Sur...
1541    Tethered Small‐Molecule Acceptors Simultaneous...
Name: ManuscriptTitle, dtype: object
1385    Substituted Rigid Rod‐Like Polymers—Building B...
1394    The role of bulk and interface recombination i...
1580    Bragg Stacks Enhancing Upconversion for Photov...
Name: ManuscriptTitle, dtype: object
1387    Direct determination of the emission zone in a...
1408            Chains of superparamagnetic nanoparticles
Name: ManuscriptTitle, dtype: object
1411    Efficient and spectrally stable blue perovskit...
1422    Enhancement of the performance of perovskite s...
1429    Halide perovskites a new era of solution‐proce...
Name: ManuscriptTitle, dtype: object
8130    Inorganic caesium lead iodide perovskite solar...
8135    Thermal degradation of formamidinium based lea...
Name: ManuscriptTitle, dtype: object
17198    Pyrene Solubilization in Aqueous Micellar Solu...
17223    Carbon nanotubes and carbon fibers in a flash ...
Name: ManuscriptTitle, dtype: object
11304    Layered SnSe nanoflakes with anharmonic phonon...
11305    Band bending at magnetic Ni/Ge (001) interface...
Name: ManuscriptTitle, dtype: object
15238    Excitation wavelength dependent fluorescence b...
15239    Natural sensitizers for DSCs improved with nan...
Name: ManuscriptTitle, dtype: object
167                               Boosting plant biology
169    Orientationdependent ionization energies and i...
Name: ManuscriptTitle, dtype: object
9121     Anomalous power dependence of upconversion emi...
11400    Ultrafast Carrier Redistribution in Single  Qu...
Name: ManuscriptTitle, dtype: object
9136    Recombination processes in passivated boronimp...
9166    Experiment Specification Capture and Laborator...
Name: ManuscriptTitle, dtype: object
7278    Logarithmic frequency dependence of the piezoe...
7285    Cation vacancies in ferroelectric PbTiO3 and P...
Name: ManuscriptTitle, dtype: object
5103    Graphene oxide shells on plasmonic nanostructu...
5163    Controlling the phase segregation in mixed hal...
Name: ManuscriptTitle, dtype: object
5155    Energy Spotlight Insights into Lithium Metal B...
5158    Tuning the SurfacePassivating Ligand Anchoring...
Name: ManuscriptTitle, dtype: object
5146    Overcoming Degradation Pathways to Achieve Sta...
5170    Boosting longterm stability of pure formamidin...
Name: ManuscriptTitle, dtype: object
3310    Revealing the Stoichiometric Tolerance of Lead...
3477    Polymerfree films of inorganic halide perovski...
Name: ManuscriptTitle, dtype: object
1497    Photovoltaics Highly Efficient Hybrid Photovol...
1525    Subtle molecular tailoring induces significant...
Name: ManuscriptTitle, dtype: object
12665    Planar heterojunction boosts solardriven photo...
12675    Influence of Mn and Fe Addition on the NO x  S...
Name: ManuscriptTitle, dtype: object

361    Impact of interfacial molecular orientation on...
371    Inversion symmetry and bulk Rashba effect in m...
Name: ManuscriptTitle, dtype: object
16627    Nitrogen doped cuprous oxide as low cost holet...
16628    Effect of grain size on the fracture behavior ...
Name: ManuscriptTitle, dtype: object
16575    Characterization of 430L porous supports obtai...
16594    Structural functional properties and enhanced ...
Name: ManuscriptTitle, dtype: object
7743    Cathode of ZnNi Layered Double Hydroxide Nanos...
7746    MultiScalable Grain Growth via PhenylC60Butyri...
Name: ManuscriptTitle, dtype: object
16256    Nonlinear optical switching and optical limiti...
16257    Unveiling photophysical and photonic phenomena...
Name: ManuscriptTitle, dtype: object
4372    Impedance spectroscopy characterisation of hig...
7794    Feasibility analysis of nanostructured planar ...
Name: ManuscriptTitle, dtype: object
8297    Ecofriendly Perovskites with Giant Self‐Defocu...
8301    Giant Bulk Photostriction and Accurate Photome...
Name: ManuscriptTitle, dtype: object
16543    Metal injection moulding of HS12155 highspeed ...
16552    Biomimetic [MoO3@ ZnO] semiconducting nanocomp...
Name: ManuscriptTitle, dtype: object
10624    Perovskite type BaSnO3reduced graphene oxide n...
15895    Niobium doping and dielectric anomalies in bis...
Name: ManuscriptTitle, dtype: object
3996    Inorganic hole conducting layers for perovskit...
4019    Band engineering via gradient molecular dopant...
4021    Controlling Electron and Hole Charge Injection...
Name: ManuscriptTitle, dtype: object
16355    Magnetic and electronic properties of halfmeta...
16357    GGA based study on electronic structure and th...
Name: ManuscriptTitle, dtype: object
1455    Micro‐and nanostructured lead halide perovskit...
1551    Alkyl side‐chain engineering in wide‐bandgap c...
Name: ManuscriptTitle, dtype: object
13423    Synergistically enhanced electric field in inh...
13433    Combined Fluorescence Fluctuation and Spectrof...
Name: ManuscriptTitle, dtype: object
7829    Sustainable fabrication of ultralong Pb (OH) B...
7831    Electrochemical synthesis of TGAcapped CdTe an...
7954    Bright and efficient blue and green lightemitt...
Name: ManuscriptTitle, dtype: object
5113    Nanoemitting heterostructures violate optical ...
6958    Interplay of couplings between antiferrodistor...
Name: ManuscriptTitle, dtype: object
8422    Ultra‐broadband Polarisers Based on Metastable...
8431    The Multiple Roles of Metal Ion Dopants in Spe...
Name: ManuscriptTitle, dtype: object
8423    Photoluminescence of Bound‐Exciton Complexes a...
8426    Shaping the emission spectral profile of quant...
Name: ManuscriptTitle, dtype: object
8381    Tuning Halide Composition Allows Low Dark Curr...
8402    Experimental Evidence of Chloride‐Induced Trap...
Name: ManuscriptTitle, dtype: object
12176    Extension of the Application of Piers‐Rubinszt...
12186    Requirements for plasma synthesis of nanocryst...
Name: ManuscriptTitle, dtype: object
7406    RAPID COMMUNICATIONSSemiconductors II Surfaces...
7410    Optical properties of  –doped oxides Different...
Name: ManuscriptTitle, dtype: object
5936    Overcoming Electrode‐Induced Losses in Organic...
5942    Requirements for beneficial electrochemical re...
5956    Efficient Thermally Evaporated γ‐CsPbI3 Perovs...
Name: ManuscriptTitle, dtype: object
15715    Functionalisation separation and solvation gen...
15716    Protein adsorption on nanoporous TiO 2 films a...
Name: ManuscriptTitle, dtype: object
15706    Influence of surface charges on the emission p...
15711    Effect of postannealing on the plasma etching ...
Name: ManuscriptTitle, dtype: object
2748    Nonlinear optical properties of benzylamine le...
2764    Polarization offsets of compositionally graded...
Name: ManuscriptTitle, dtype: object
6227    Fluorescence switching of quantum dot in quant...
6228    Ultrafast Relaxation Dynamics of Luminescent C...
6229    Design of a CdS/CdSe Heterostructure for Effic...
Name: ManuscriptTitle, dtype: object
330     The quantumconfined Stark effect in layered hy...
1126    Quasiepitaxial metalhalide perovskite ligand s...
Name: ManuscriptTitle, dtype: object
488      Abnormal band bowing effects in phase instabil...
12652    Selfassembled leadfree double perovskiteMXene ...
Name: ManuscriptTitle, dtype: object
9779    Surface passivation by rehydrogenation of sili...
9780    Reactive ion etching of dielectrics and silico...
Name: ManuscriptTitle, dtype: object
12105    Recent Progress in Polymorphs of Carbon Nitrid...
12128    Investigations of the viscoelastic properties ...
12135    COMMUNICATIONS TO THE EDITORInterplay of Therm...
Name: ManuscriptTitle, dtype: object
12061    SolGel Synthesis and Characterization of Yttri...
12109    Michael Polyaddition Approach Towards Sulfur E...
Name: ManuscriptTitle, dtype: object
12148    Novel electroluminescent polymers with fluoro ...
12149    Easily Attainable PhenothiazineBased Polymers ...
Name: ManuscriptTitle, dtype: object
12074    Nonlinear optical feedback for nanoand micropa...
12076    Halide Perovskites for Photonics and Optoelect...
Name: ManuscriptTitle, dtype: object
12114    Ordering graphoepitaxial orientation and confo...
12137    A phase diagram of the P3HT PCBM organic photo...
Name: ManuscriptTitle, dtype: object
12108    Polyethylene‐Derived Activated Carbon Material...
12134    Orientation and Dynamics of Chainlike Dipole A...
Name: ManuscriptTitle, dtype: object
12121    Preparation of oriented multilayers of poly (s...
12182    Fabrication and properties of B–N codoped ptyp...
Name: ManuscriptTitle, dtype: object
5369      A taxonomy for threeterminal tandem solar cells
5371    Understanding the PerformanceLimiting Factors ...
Name: ManuscriptTitle, dtype: object
9668    Implication of polymeric template agent on the...
9669    Hybrid nanocrystal/polymer solar cells based o...
Name: ManuscriptTitle, dtype: object
10201    Perforated Ndoped monoclinic ZnWO 4 nanorods f...
10254    An Investigation of the Photoinduced Changes o...
10289    Photoswitched Protein Adsorption on Electrosta...
Name: ManuscriptTitle, dtype: object
14233    RotaryJet spin assisted fabrication of MnO2 mi...
14245    Circularly Polarized Emission from Ensembles o...
Name: ManuscriptTitle, dtype: object
7099    Aryl amine substituted low energy gap carbazol...
7100    Localized surface plasmon resonance sensor bas...
Name: ManuscriptTitle, dtype: object
5303    14th International Conference on Hybrid and Or...
5304    Postsynthesis Transformation of Insulating Cs4...
5305    Efficient widebandgap mixedcation and mixedhal...
Name: ManuscriptTitle, dtype: object
2329    Electrodemolecular semiconductor contacts Work...
2351    Charging and excitonmediated decharging of met...
Name: ManuscriptTitle, dtype: object
5897    Characterization of the Valence and Conduction...
5920    Improved open‐circuit voltage in ZnO–PbSe quan...
Name: ManuscriptTitle, dtype: object
9691     Adjusting the Néel relaxation time of Fe3O4/Zn...
13525    Cationselective and anioncontrolled fluorogeni...
Name: ManuscriptTitle, dtype: object
2851    Suspended photonic crystal membranes in AlGaAs...
2883    Tuning the electronic structure of graphene by...
Name: ManuscriptTitle, dtype: object
14335    Magnetostatic spin wave resonance in squarepat...
14336    Tetragonal distortion induced perpendicular ma...
14337    Enhancement of dielectric and magnetic propert...
Name: ManuscriptTitle, dtype: object
234        Nanostructured materials for photon detection
283    Detection of Xray photons by solutionprocessed...
Name: ManuscriptTitle, dtype: object
12571    A K2NiF4type La2Li0. 5Al0. 5O4 catalyst for th...
12573    Design of nanocatalysts for green hydrogen pro...
12580    Nanoscale perovskite‐sensitized solar cell rev...
12597    A TiO2 Nanofiber–Carbon Nanotube‐Composite Pho...
12598    Plasmonic Gold Nanostars Incorporated into Hig...
Name: ManuscriptTitle, dtype: object
2866    Singlecell tumbling enables highresolution siz...
2955    Unravelling the photocatalytic behavior of all...
Name: ManuscriptTitle, dtype: object
15537    Pulsed electrodeposition of WO3–TiO2 composite...
15558    Implementation of a “design of experiments” me...
15564    Effects of Cu2− xS phase removal on surface po...
Name: ManuscriptTitle, dtype: object
5483    Direct evidence for percolation of immobilized...
5485    Twodimensional MOF modulated fiber nanogenerat...
Name: ManuscriptTitle, dtype: object
4714    Metal Coordination Sphere Deformation Induced ...
4715    Solution‐processed reduced graphene oxide film...
Name: ManuscriptTitle, dtype: object
9291    Leakage current effects on  plots of high meta...
9292    Nanowire fin field effect transistors via UVba...
9300    Papers from the 47th International Conference ...
9310    Growth and characterization of MnAs/ZnSe ferro...
9317    Solgel synthesized indium tin oxide as a trans...
9325    The effect of processing conditions on the mor...
9326    Effect of silane coupling agent on the morphol...
9328    Balancing hyperbole and impact in research com...
9332    Rh/CeO2 catalyst preparation and characterizat...
9337    Theoretical study of the strain influence on l...
Name: ManuscriptTitle, dtype: object
9311    Papers from the 19th North American Conference...
9330    Electrode characteristics of Li2Ti3O7ramsdelli...
Name: ManuscriptTitle, dtype: object
15033    Investigating the Role of Lewis AcidBase Inter...
15037    Formations of unexpected chlorobridged bis (ma...
Name: ManuscriptTitle, dtype: object
12071    Fabrication of Pressure Conductive Silicone Ru...
12073    Metaldielectric nanoantenna for radiation cont...
Name: ManuscriptTitle, dtype: object
6655    Fabrication pressure testing and nanopore form...
6707          Light manipulation in organic photovoltaics
Name: ManuscriptTitle, dtype: object
449     Lightactivated photocurrent degradation and se...
1157    Dilutioninduced formation of hybrid perovskite...
Name: ManuscriptTitle, dtype: object
16669    Insight into pressure tunable structural elect...
16684            Synthesis of 13Cdiamonds in CaCO3C system
Name: ManuscriptTitle, dtype: object
14732    Dependability assessment of transfer length me...
14733    A broadband active microwave monolithically in...
Name: ManuscriptTitle, dtype: object
2795    Elucidating possible crystallographic origins ...
2816                   Physics of ultrathin photovoltaics
Name: ManuscriptTitle, dtype: object
14743    Metalassisted chemical etching for very high a...
14749    Characterization of SOI MOSFETs by means of ch...
Name: ManuscriptTitle, dtype: object
3677         Advances in spraycast perovskite solar cells
3678    Lévy defects in matriximmobilized J aggregates...
Name: ManuscriptTitle, dtype: object
4297    Crystalline Mesoporous Complex Oxides Porosity...
4298    High‐Temperature Photoluminescence of CsPbX3 (...
Name: ManuscriptTitle, dtype: object
4982    Ultrasensitive turnon luminescence humidity se...
5001    Effect of density of surface defects on photol...
Name: ManuscriptTitle, dtype: object
5116    Formamidinium lead halide perovskite crystals ...
6965    Nonlinear Dynamics Fluid Dynamics Classical Op...
Name: ManuscriptTitle, dtype: object
2269    An electrochemical clamp assay for direct rapi...
2325    In situ resistance measurement of the type con...
Name: ManuscriptTitle, dtype: object
5497    Perspectives of chalcopyritebased CIGSe thinfi...
5500    Synthesis of NiO–CeO2 nanocomposite for electr...
Name: ManuscriptTitle, dtype: object
14330    Electrical transport properties and transport–...
14370    Comparison of highly conductive natural and sy...
Name: ManuscriptTitle, dtype: object
9583    Bonding in d9 complexes derived from EPR Appli...
9584    Crystalfield and charge transfer transitions d...
Name: ManuscriptTitle, dtype: object
7556    Surface physics lowdimensional systems and rel...
7566    Magnetotransport properties of doped RuSr 2 Gd...
Name: ManuscriptTitle, dtype: object
1307         Mixed lead halide passivation of quantum dots
16738    A novel Tb3+ ions doped barium strontium fluor...
Name: ManuscriptTitle, dtype: object
15223    The effect of Au on TiO2 catalyzed selective p...
15226    Impact of one step alloying on the carrier rel...
Name: ManuscriptTitle, dtype: object
14315    Magnetic and optical properties of spinel Fe {...
14316    Electronic structure magnetism and thermoelect...
Name: ManuscriptTitle, dtype: object
2633    “Smart” silicon Switching between p‐ and n‐con...
2637    Colossal enhancement of the thermoelectric pow...
Name: ManuscriptTitle, dtype: object
4004    Untying the Cesium “Not” Cesium–Iodoplumbate C...
4009    Graphdiyne an efficient hole transporter for s...
Name: ManuscriptTitle, dtype: object
4002    Quantum dot photocatalysts for organic transfo...
4010    Efficient infrared electroluminescent devices ...
Name: ManuscriptTitle, dtype: object
5619    Sustained SolarPowered Electrocatalytic H2 Pro...
5620    Teacarbon dotsreduced graphene oxide an effici...
5621    Green SolventBased Perovskite Precursor Develo...
Name: ManuscriptTitle, dtype: object
12077    Erratum Halide Perovskites for Photonics and O...
12080    Temperature dependent twophoton photoluminesce...
Name: ManuscriptTitle, dtype: object
16708    Self nitrogen and oxygenbroadening coefficient...
16709    Highresolution infrared spectroscopy of the ν2...
Name: ManuscriptTitle, dtype: object
2219    Strain effect in palladium nanostructures as n...
2230    Nanoscale back contact perovskite solar cell d...
Name: ManuscriptTitle, dtype: object
2173    Unveiling the shape evolution and halideionseg...
2185                   Optical force stamping lithography
Name: ManuscriptTitle, dtype: object
9259    Organolead halide perovskite regulated green l...
9261    Improved energy harvesting ability of C3H7NH3P...
Name: ManuscriptTitle, dtype: object
9258    Structure engineering of hierarchical layered ...
9260    Piezophototronic effect in highly stable CsPbI...
Name: ManuscriptTitle, dtype: object
3193    Electrical conductivity of doped organic semic...
3194       Molecular Doping Directed by a Neutral Radical
Name: ManuscriptTitle, dtype: object
3863    Change in tetracene polymorphism facilitates t...
3867    Ultrafast Optical Mapping of Nonlinear Plasmon...
Name: ManuscriptTitle, dtype: object
5346    Women scientists at the forefront of energy re...
5347    Leadfree dion–jacobson tin halide perovskites ...
Name: ManuscriptTitle, dtype: object
2878     Surface State Density Determines the Energy Le...
13587    Sharp Lines Due to Cr3+ and Mn2+ Impurities in...
Name: ManuscriptTitle, dtype: object
4204    Simultaneous Power Conversion Efficiency and S...
4212    Novel Method of Preparation of Gold‐Nanopartic...
Name: ManuscriptTitle, dtype: object
13252    NiO Nanofibers as a Candidate for a Nanophotoc...
13253               Quantum dot sensitized photoelectrodes
Name: ManuscriptTitle, dtype: object
12162    Atomistic investigation of the solubility of 3...
12163    Synthesis of πbridged duallydopable conjugated...
Name: ManuscriptTitle, dtype: object
372    Pure crystal orientation and anisotropic charg...
379    Electrically tunable organic–inorganic hybrid ...
380    Microcavitylike excitonpolaritons can be the p...
Name: ManuscriptTitle, dtype: object
1136    MoS2 Quantum Dot/Graphene Hybrids for Advanced...
1198    Revealing factors influencing the operational ...
Name: ManuscriptTitle, dtype: object
9282    Electrical scanning probe microscopy Investiga...
9285    Twodimensional profiling of carriers in a buri...
9286    Twodimensional transverse crosssection nanopot...
Name: ManuscriptTitle, dtype: object
9305    Real time in situ monitoring of surfaces durin...
9308    Planar metal–insulator–metal diodes based on t...
Name: ManuscriptTitle, dtype: object
9545    On the polarization of the green emission of p...
9564    PseudoJahnTeller origin of geometry and pseudo...
9567    A simple monomerbased modelHamiltonian approac...
Name: ManuscriptTitle, dtype: object
6243    Quenching of confined C480 dye in the presence...
6246    Structural Analysis and Carrier Relaxation Dyn...
Name: ManuscriptTitle, dtype: object
1817    Halide Remixing under Device Operation Imparts...
1841    Neutron Detectors Cesium Lead Bromide (CsPbBr3...
Name: ManuscriptTitle, dtype: object
14496    4Terminal Inorganic Perovskite/Organic Tandem ...
14503    0.86nm CET Gate Stacks With Epitaxial GdO High...
Name: ManuscriptTitle, dtype: object
6067    Effect of solvent additive on generation recom...
6085    Synthesis and Optical Properties of a Dithiola...
Name: ManuscriptTitle, dtype: object
4644    High‐performance perovskite light‐emitting dio...
4657    Biosupramolecular Nanowires from Chlorophyll D...
4689    Metal–organic organopolymeric hybrid framework...
Name: ManuscriptTitle, dtype: object
3064    How Deep Hole Traps Affect the Charge Dynamics...
3100    Enhanced Device Performance with Passivation o...
3118    Direct hotinjection synthesis of lead halide p...
Name: ManuscriptTitle, dtype: object
11446    Photovoltaic manufacturing Present status futu...
11470    Substrate and temperature dependence of the fo...
11569    Potassium and Rubidium Copper Halide A2CuX3 (A...
Name: ManuscriptTitle, dtype: object
13046    Molecularengineered [Ir (Fppy) 2 (Mepic)] towa...
13048    Copper (i) ionic complexes based on imidazo [4...
Name: ManuscriptTitle, dtype: object
13025    Copperzinc oxide catalysts. Part IV. Thermal t...
13026    Chimie douce synthesis and thermochemical char...
Name: ManuscriptTitle, dtype: object
13032    Scalable heterogeneous synthesis of metallic n...
13064    Structural interpretation of SnO 2 nanocrystal...
Name: ManuscriptTitle, dtype: object
3288    Conductivity Optimization of Tysonitetype La1–...
3296    Synthesis of Colloidal CuGaSe2 CuInSe2 and Cu(...
Name: ManuscriptTitle, dtype: object
6605    Oligofluorene molecular wires Synthesis and si...
6606    The photochemistry of crystalline nitromethane...
Name: ManuscriptTitle, dtype: object
10983    Atomicscale origin of piezoelectricity in wurt...
10991    Electronic optical and thermoelectric properti...
10999    Solvent Hbond accepting ability induced confor...
Name: ManuscriptTitle, dtype: object
13194    ABCmodel analysis of gainswitched pulse charac...
13210    Highly stable fluorinepassivated In–Ga–Zn–O th...
Name: ManuscriptTitle, dtype: object
6376    Manipulation of Hydrogen Binding Energy and De...
6379    Understanding acid reaction and diffusion in c...
Name: ManuscriptTitle, dtype: object
17525    Bridged phthalocyanine systems for sensitizati...
17528    Structural dielectric permittivity and optical...
17529    Structure–property relationship of biobased po...
17532    Polyurethane/soya protein isolate green compos...
Name: ManuscriptTitle, dtype: object
5353    High photovoltage of 1 V on a steadystate cert...
5381    Curtailing Perovskite Processing Limitations v...
Name: ManuscriptTitle, dtype: object
4257    Stable Light‐Emitting Electrochemical Cells Us...
4284    Constructing Polymorphic Nanodomains in BaTiO3...
4293    Working principles of perovskite photodetector...
Name: ManuscriptTitle, dtype: object
4227    Stable and Bright Pyridine Manganese Halides f...
4246    Inorganic electron transport materials in pero...
Name: ManuscriptTitle, dtype: object
4234    Magnetic Properties of Layered Hybrid OrganicI...
4260    Enhancing Resistive Switching Performance and ...
Name: ManuscriptTitle, dtype: object
10712    Single layer pbi 2 hydrogenationdriven reconst...
10733    Improved photocatalytic activity by utilizing ...
Name: ManuscriptTitle, dtype: object
3060    PerturbationInduced Seeding and Crystallizatio...
3226    Allpolymer solar cells approaching 12% efficie...
Name: ManuscriptTitle, dtype: object

In [50]:
print('Total Papers: ', papers_df.shape[0])
print('Total suspicious paper titles: ', j)

Total Papers:  16738
Total suspicious paper titles:  2920

In [51]:
for i in papers_df.index:
    title = papers_df.loc[i, 'ManuscriptTitle']
    if np.char.find(title, 'supporting information') != -1 \
        or np.char.find(title, 'reply to the comment') != -1 \
        or np.char.find(title, '{sub') != -1\
        or np.char.find(title, 'correction') != -1\
        or np.char.find(title, 'erratum') != -1:
        
        print('Dropping the paper:')
        print(title)
        papers_df = papers_df.drop(i)

Dropping the paper:
Stable halfmetallic monolayers of FeCl {sub 2}
Dropping the paper:
Optimal growth and thermal stability of crystalline Be {sub 0.25} Zn {sub 0.75} O alloy films on Al {sub 2} O {sub 3}(0001)
Dropping the paper:
Switchable and tunable film bulk acoustic resonator fabricated using barium strontium titanate active layer and Ta {sub 2} O {sub 5}/SiO {sub 2} acoustic reflector
Dropping the paper:
Electronic structure panorama of halide perovskites approximated DFT1/2 quasiparticle and relativistic corrections
Dropping the paper:
Strong dependence on doping of a lowactivationenergy relaxation process in YBa {sub 2} Cu {sub 3} O {sub 6+{ital x}} Possible polaron relaxation
Dropping the paper:
Approximate quasiparticle correction for calculations of the energy gap in twodimensional materials
Dropping the paper:
Refining the phase diagram of Pb {sub 1− x} La {sub x}(Zr {sub 0.9} Ti {sub 0.1}){sub 1− x/4} O {sub 3} ceramics by structural dielectric and anelastic spectroscopy …
Dropping the paper:
Metalinsulator transition in Nd {sub 1− x} Eu {sub x} NiO {sub 3} Entropy change and electronic delocalization
Dropping the paper:
The effect of doping in the electrochemical performance of (Ln {sub 1x} M {sub x}) FeO {sub 3{delta}} SOFC cathodes
Dropping the paper:
A {mu} SR study of the magnetoresistive ruthenocuprates RuSr {sub 2} Nd {sub 1.8x} Y {sub 0.2} Ce {sub x} Cu {sub 2} O {sub 10{delta}}(x= 0.95 and 0.80)
Dropping the paper:
Magnetic interactions on the tin sites in the tindoped ferromagnetic superconductor Ru {sub 1x} Sn {sub x} Sr {sub 2} GdCu {sub 2} O {sub 8}
Dropping the paper:
SrHf {sub 0.67} Ti {sub 0.33} O {sub 3} highk films deposited on Si by pulsed laser deposition
Dropping the paper:
Etching of high aspect ratio features in Si using SF {sub 6}/O {sub 2}/HBr and SF {sub 6}/O {sub 2}/Cl {sub 2} plasma
Dropping the paper:
Conduction and rectification in NbO {sub x}and NiObased metalinsulatormetal diodes
Dropping the paper:
EXAFS study of LaNi {sub 5} and LaNi {sub 4.5} Al {sub 0.5}
Dropping the paper:
H and D tunnelling systems in diluted Nb {sub 1x} Zr {sub x} alloys
Dropping the paper:
Study of electrical transport and magnetoresistive properties of La {sub 0.67− x} Dy {sub x} Pb {sub 0.33} MnO {sub 3}(x= 0.00 0.10 and 0.15)
Dropping the paper:
Proton conduction in oxygen deficient Ba {sub 3} In {sub 1.4} Y {sub 0.3} M {sub 0.3} ZrO {sub 8}(M= Ga {sup 3+} or Gd {sup 3+}) perovskites
Dropping the paper:
Tetragonal To Collapsed Tetragonal Phase Transition In BaFe {sub 2} As {sub 2} and CaFe {sub 2} As {sub 2}
Dropping the paper:
Magnetic Behaviour Of Bismuth Substituted Perovskites La {sub 1x} Bi {sub x} Mn {sub 0.8} Co {sub 0.2} O {sub 3}
Dropping the paper:
Tunable electroluminescence from lowthreshold voltage LED structure based on electrodeposited Zn {sub 1x} Cd {sub x} Onanorods/pGaN heterojunction
Dropping the paper:
Bright white light emission from In {sub 2} S {sub 3} Eu {sup 3+} nanoparticles
Dropping the paper:
Synthesis and transport properties of SrTiO {sub 3x} N {sub y}/SrTiO {sub 3{delta}} layered structures produced by microwaveinduced plasma nitridation
Dropping the paper:
Ethanol steam reforming over Rh/Ce {sub x} Zr {sub 1x} O {sub 2} catalysts. Impact of the COCO {sub 2}CH {sub 4} interconversion reactions on the H {sub 2} production
Dropping the paper:
Reactivity of steam in exhaust gas catalysis. Part 3. Steam and oxygen/steam conversions of propane on a Pd/Al {sub 2} O {sub 3} catalyst
Dropping the paper:
Rhombohedralcubic transition in Li {sub 0.2} Na {sub 0.3} La {sub 0.5} TiO {sub 3} perovskite
Dropping the paper:
Microstructural study of La {sub 0.5} Li {sub 0.5} TiO {sub 3}
Dropping the paper:
Stability and breakdown of Ca {sup 13} CO {sub 3} melt associated with formation of {sup 13} Cdiamond in static high pressure experiments up to 43 GPa and 3900 K
Dropping the paper:
A novel ferrimagnetic iridocuprate IrSr {sub 2} GdCu {sub 2} O {sub 8}
Dropping the paper:
Crystal structures and hightemperature phasetransitions in SrNdMRuO {sub 6}(M= Zn Co Mg Ni) new double perovskites studied by symmetrymode analysis
Dropping the paper:
A study of the crystal structures and the phase transitions of the ordered double perovskites Sr {sub 2} ScSbO {sub 6} and Ca {sub 2} ScSbO {sub 6}
Dropping the paper:
A high temperature neutron diffraction study of the double perovskite Ba {sub 2}{sup 154} SmMoO {sub 6}
Dropping the paper:
Doping studies of the magnetic cobaltocuprate CoSr {sub 2} Y {sub 2x} Ce {sub x} Cu {sub 2} O {sub 9+}/{sub {delta}}
Dropping the paper:
Studies of microstructure and ruthenium valence in the ruthenocuprates Pb {sub 2} RuSr {sub 2} Cu {sub 2} O {sub 8} Cl and (Ru M) Sr {sub 2} GdCu {sub 2} O {sub 8}(M= Sn Nb)
Dropping the paper:
Behavior of the magnetocaloric effect and critical exponents in La {sub 0.67} Sr {sub 0.33} Mn {sub 1− x} V {sub x} O {sub 3} manganite oxide
Dropping the paper:
Energy gap and bond lengths of Al {sub x} Ga {sub y} In {sub 1xy} N Al {sub x} Ga {sub y} In {sub 1xy} P and Al {sub x} Ga {sub y} In {sub 1xy} As quaternary alloys
Dropping the paper:
Variations in structural and physical properties of RuSr {sub 2} GdCu {sub 2} O {sub 8} samples submitted to annealing and deoxygenation procedures
Dropping the paper:
Magnetoelastic coupling in RuSr {sub 2} GdCu {sub 2} O {sub 8}
Dropping the paper:
Cluster spin glass phase and charge stripe fluctuations in the highT {sub c} superconductor La {sub 2x} Sr {sub x} CuO {sub 4}
Dropping the paper:
A variable field neutron study of the negative magnetoresistive ruthenocuprate RuSr {sub 2} Nd {sub 0.9} Y {sub 0.2} Ce {sub 0.9} Cu {sub 2} O {sub 10{delta}}
Dropping the paper:
Magnetic and electronic properties of vanadiumsubstituted magnetite V {sub x} Fe {sub 3}{sub x} O {sub 4} thin films
Dropping the paper:
Crystallographic and magnetic properties of solgel synthesized T {sub x} Co {sub 1}{sub x} Fe {sub 2} O {sub 4}(T= Mn and Cr) thin films
Dropping the paper:
Ferromagnetic properties of anatase Ti {sub 1}{sub x} Fe {sub x} O {sub 2}{sub {delta}} thin films grown by solgel method
Dropping the paper:
Magnetic and optical properties of spinel Fe {sub x} Co {sub 3x} O {sub 4} thin films
Dropping the paper:
The superstructure and superconductivity of Ru1222 based RuSr {sub 2} Gd {sub 2xy} Y {sub y} Ce {sub x} Cu {sub 2} O {sub 10{delta}} compounds
Dropping the paper:
Structure and microwave dielectric properties of Ca {sub 5} A {sub 4} TiO {sub 17}(A= Nb Ta) ceramics
Dropping the paper:
High pressure neutron diffraction study of the magnetoresistive 1222type ruthenocuprate RuSr {sub 2} Nd {sub 0.9} Y {sub 0.2} Ce {sub 0.9} Cu {sub 2} O {sub 10}
Dropping the paper:
An EXAFS study of RuSr {sub 2} GdCu {sub 2} O {sub 8} Evidence of magnetoelastic coupling
Dropping the paper:
A DFT Study on Structural Electronic Mechanical and Thermodynamic Properties of 5fElectron System BaAmO {sub 3}
Dropping the paper:
Studies of the Magnetocaloric and Electrical Properties of La {sub 0.7} Er {sub 0.05} Sr {sub 0.15} Ca {sub 0.1} Mn {sub 1− x} In {sub x} O {sub 3}(0≤ x≤ 0.30)
Dropping the paper:
Structural Infrared Magnetic and Electrical Properties of Ni {sub 0.6} Cd {sub 0.2} Cu {sub 0.2} Fe {sub 2} O {sub 4} Ferrites Synthesized Using SolGel Method Under …
Dropping the paper:
Hybrid density functional theory study on zinc blende GaN and diamond surfaces and interfaces Effects of size hydrogen passivation and dipole corrections
Dropping the paper:
Drug quantification in turbid media by fluorescence imaging combined with lightabsorption correction using white Monte Carlo simulations

In [52]:
j = 0 
for group_name, group in papers_df.groupby(['first_auth', 'second_auth', 'third_auth']):
    i = group_papers(group)
    j += i

3577    Carrier diffusion lengths in hybrid perovskite...
3609    Pyrochlore to Fluorite Transition The Y2(Ti1–x...
Name: ManuscriptTitle, dtype: object
13895    Role of surface texturization on the gassensin...
13898    Role of surface passivating ligand and growth ...
Name: ManuscriptTitle, dtype: object
6185    Controlled Mixed Violet–Blue–Red Electrolumine...
6210    Resonance energy transfer from rhodamine 6G to...
Name: ManuscriptTitle, dtype: object
6199    Surface DefectRelated Luminescence Properties ...
6212    Metal conjugated semiconductor hybrid nanopart...
Name: ManuscriptTitle, dtype: object
15121    Coaxial nanofibers outperform uniaxial nanofib...
15125    New Ideas for Understanding the Structure and ...
Name: ManuscriptTitle, dtype: object
14419    Reducing the interfacial voltage loss in tin h...
14453    Interface characterization of allperovskite ox...
Name: ManuscriptTitle, dtype: object
14421    Highly symmetric Lewis base coordinated with S...
14422    Halogen engineering of 2D/3D tin halide perovs...
14424    Stabilizing CsPbBr3 perovskite quantum dots on...
14430    Effects of Fe3+ substitution on ZnAl layered d...
14439    Excellent disinfection and fluoride removal us...
14440    Semitransparent organic solar cells with light...
14442    An efficient and durable perovskite electrocat...
14444    Highly efficient layerbylayer deposition solar...
14445    Optical enhancement of nonstoichiometryinduced...
14446    Review on recent progress in hydrothermally sy...
14451    Microfluidic synthesis of metalorganic framewo...
Name: ManuscriptTitle, dtype: object
14429    Superhydrophobic high impact polystyrene (HIPS...
14447    Achieving direct electrophoretically deposited...
Name: ManuscriptTitle, dtype: object
14431    Aqueous miscible organic solvent treated NiTi ...
14437    Lasing operation in the CsPbBr3 perovskite mic...
14443    Evaluation of the production of biohydrogen du...
Name: ManuscriptTitle, dtype: object
14423    Recent promise of leadfree halide perovskites ...
14441    On the surface passivating principle of functi...
Name: ManuscriptTitle, dtype: object
12582    Chlorides other Halides and Pseudo‐Halides as ...
12596    Design of C3N4‐Based Hybrid Heterojunctions fo...
Name: ManuscriptTitle, dtype: object
14789    A novel way to characterize metalinsulatormeta...
14790    Using amorphous ZincTin Oxide alloys in the em...
Name: ManuscriptTitle, dtype: object
6990    Electron degeneracy and intrinsic magnetic pro...
7005    Microstrain sensitivity of orbital and electro...
Name: ManuscriptTitle, dtype: object
8565    Examination of growth kinetics of copper rich ...
8577    Impedance spectroscopy analysis of small molec...
Name: ManuscriptTitle, dtype: object
8537    Photoinduced charge separation and electron di...
8567    Efficiency and stability enhancement of laserc...
Name: ManuscriptTitle, dtype: object
8507    Photon management of combining nanostructural ...
8571    Electrical properties of patterned photoactive...
Name: ManuscriptTitle, dtype: object
8566    Bufferfree Cu (In Ga) Se2solar cells by nearsu...
8575    Improvement of photovoltaic performance of per...
Name: ManuscriptTitle, dtype: object
6537    Understanding the helical wrapping of poly (3h...
6538    Appealing perspectives of hybrid lead–iodide p...
Name: ManuscriptTitle, dtype: object
12289    Highly luminescent columnar ZnO films grown di...
12365    Hybridstructured indium tin oxide with Ag nano...
Name: ManuscriptTitle, dtype: object
10932    Local structure and excitations in systems wit...
10937    Mechanical properties of monolayer sulphides a...
Name: ManuscriptTitle, dtype: object
8194    Structural and oxygentransport studies of doub...
8261    Reliability of 3D Cs 2 M+ M 3+ X 6 type absorb...
8293    Photonic crystal‐driven spectral concentration...
Name: ManuscriptTitle, dtype: object
8208    A facile way for scalable fabrication of silve...
8241    Identifying the electrocatalytic active sites ...
Name: ManuscriptTitle, dtype: object
12719    Morphological and structural changes in reduci...
12723    Evidence of Plasmonic Induced Photocatalytic H...
Name: ManuscriptTitle, dtype: object
17352    Effect of conductive additive amount on electr...
17356    Recrystallized thinfilm silicon solar cell on ...
17358    Investigation on microstructures and thermophy...
Name: ManuscriptTitle, dtype: object
11921    An Xray scattering and electron microscopy stu...
11989    Microscopic and spectroscopic investigation of...
Name: ManuscriptTitle, dtype: object
15590    Atomicscale understanding of dichlorobenzeneas...
15591    Indole moiety induced biological potency in ps...
Name: ManuscriptTitle, dtype: object
4408    Peroptronic devices perovskitebased lightemitt...
4409    Machine learningassisted development of organi...
Name: ManuscriptTitle, dtype: object
12612    Coupled Near‐and Far‐Field Scattering in Silve...
12614    Broadband‐Emitting 2 D Hybrid Organic–Inorgani...
Name: ManuscriptTitle, dtype: object
15620    Synthesis single crystal Xray DFT spectroscopi...
15623    Investigation of electronic structure magnetic...
Name: ManuscriptTitle, dtype: object
15617    Structural spectral magnetic and dielectric pr...
15619    Syntheses crystal structures topology and dual...
Name: ManuscriptTitle, dtype: object
5934    Exploring the Limiting Open‐Circuit Voltage an...
5940    Hole Transporting Materials Development of Dop...
Name: ManuscriptTitle, dtype: object
11453    Etching of high aspect ratio structures in Si ...
12659    Graphene quantum dots/NiTi layered double hydr...
Name: ManuscriptTitle, dtype: object
5684    Exchange‐Coupled Bimagnetic Wüstite/Metal Ferr...
5710    Interfacing BiVO4 with Reduced Graphene Oxide ...
Name: ManuscriptTitle, dtype: object
13343    An insight into the local Oh→ Td instability i...
13345    Pressuredriven Phase Transition in CaFeAsF at ...
Name: ManuscriptTitle, dtype: object
13340    Application of lowvoltage backscattered electr...
13342    Thermal activated carrier transfer between InA...
Name: ManuscriptTitle, dtype: object
11923    Electromechanical tuning of nanoscale MIM diod...
11984    Effect of boron on formation of interstitial‐r...
11985    PbS nanocrystals in hybrid systems for solar c...
Name: ManuscriptTitle, dtype: object
3545    Formation of unsaturated hydrocarbons and hydr...
3548    Fabrication and postmodification of nanoporous...
Name: ManuscriptTitle, dtype: object
8076    Anisotropic ionic conductivity in fluorinated ...
8114    Enhanced performance via partial lead replacem...
8120    Hexagonal perovskite related oxide ion conduct...
8123    Temporal and spatial pinhole constraints in sm...
8145    Photoinduced degradation of methylammonium lea...
Name: ManuscriptTitle, dtype: object
11667    Partial inverse spinel structure of manganesed...
11697    Studying the role of CdS on the TiO2 surface p...
Name: ManuscriptTitle, dtype: object
8694    Difference in hot carrier cooling rate between...
8723    Selective fluorescence functionalization of dy...
Name: ManuscriptTitle, dtype: object
8706    Infrared emitting quantum dots DNA conjugation...
8710    Washinduced multicolor tuning of carbon nanodo...
Name: ManuscriptTitle, dtype: object
11870       Sevenlayered 2D hybrid lead iodide perovskites
11955    The effect of reducing dimensionality on the e...
11972    Memristive devices based on solution‐processed...
11974    Effect of nanoscale confinement on fluorescenc...
Name: ManuscriptTitle, dtype: object
15725    Electroluminescence and fluorescence emission ...
15730    Nexus approach to solar technology for energy ...
Name: ManuscriptTitle, dtype: object
16445    Structural Volume Changes upon Photoisomerizat...
16446    Transient absorption of copper selenide nanowi...
16457    Spectral properties of organosilicon polymer/S...
Name: ManuscriptTitle, dtype: object
6687    Highly UV Resistant Inch‐Scale Hybrid Perovski...
6690    Stacking Polymorphism in PtSe2 Drastically Aff...
Name: ManuscriptTitle, dtype: object
8505    The influence of drift fields in thin silicon ...
8506    Passivated contacts to laser doped p+ and n+ r...
8562    Tapered aluminumdoped vertical zinc oxide nano...
Name: ManuscriptTitle, dtype: object
16451     Photophysics of poly (pphenylene vinylene) films
16458    Correlation of Degradation of P3HT PCBM And P3...
Name: ManuscriptTitle, dtype: object
8004    Solvent vapour annealing of methylammonium lea...
8019    Emerging polyanionic and organic compounds for...
Name: ManuscriptTitle, dtype: object
16541    Porous NiYSZ planar anodes by powder extrusion...
16547    Processing of P/M M2 high speed steels by moul...
16551    Development of thermoelectric oxides for renew...
Name: ManuscriptTitle, dtype: object
15362    Nonfused medium bandgap electron acceptors for...
15369    Dimensionality regulation in tin halide perovs...
Name: ManuscriptTitle, dtype: object
3974    Hexagonal boron nitride selflaunches hyperboli...
3992    Nanoscale Architecture of Polymer–Organolead H...
Name: ManuscriptTitle, dtype: object
17600    FtIr And Computational Study Of Di2Pyridyl Ket...
17603    Photoluminescent and photocatalytic behaviour ...
Name: ManuscriptTitle, dtype: object
17602    A highly effective superfluid film breaker for...
17605    Rheology of fumed silica/polydimethylsiloxane ...
Name: ManuscriptTitle, dtype: object
10828    Correction Interface structure precursor rheol...
10882    Germanium coating boosts lithium uptake in Si ...
Name: ManuscriptTitle, dtype: object
14001    Generalised single particle models for highrat...
14068    The anomalous quasi isotropic [g] tensor found...
14069    Optical properties due to Cr4+ in oxides Densi...
14071    Magnetic properties of R3Rh2 compounds with R=...
Name: ManuscriptTitle, dtype: object
11838    Magneto‐optical Properties of Iron Oxide Nanoc...
11847    Dielectric and Raman spectroscopy measurements...
11930    Nanostructured Nbsubstituted CaMnO3 ntype ther...
Name: ManuscriptTitle, dtype: object
12021    Ionic Liquid‐Mediated α‐Fe2O3 Shape‐Controlled...
12035    Characterization of Charge States in Conductin...
Name: ManuscriptTitle, dtype: object
12000    InGaP//GaAs//CIGS 3‐junction spectrum‐splittin...
12003    Effect of inverted‐pyramid shape on light extr...
Name: ManuscriptTitle, dtype: object
11999    Excitonic and Free Carrier Recombination in In...
12002    Photoluminescence characteristics of organic m...
Name: ManuscriptTitle, dtype: object
10923    Excited state dynamics of BODIPYbased acceptor...
10929    Low electronpolar optical phonon scattering as...
Name: ManuscriptTitle, dtype: object
10323    Design of dendritic core carbazolebased hole t...
10328    Acidfunctionalized fullerenes used as interfac...
10363    Selfhealable electrochromic ion gels for low p...
10374    A simple engineering strategy with side chain ...
Name: ManuscriptTitle, dtype: object
5740    Low‐temperature‐processed colloidal quantum do...
5743    Editorial for the special issue Dimensionality...
Name: ManuscriptTitle, dtype: object
14584    Dry and wet etch processes for NiMnSb Heusler ...
14599    (Ln0. 5M0. 5) FeO3− δ Perovskites as Cathode f...
Name: ManuscriptTitle, dtype: object
10524    Charge injection and trapping at perovskite in...
10546    Rareearth quantum cutting in metal halide pero...
Name: ManuscriptTitle, dtype: object
4254    Pattern Formation of Silver Nanoparticles in 1...
4268    Switched‐On Progress Challenges and Opportunit...
4294    Hybrid Silicon‐Polymer Photodetector Engineere...
Name: ManuscriptTitle, dtype: object
13939    Green lightemitting diodes based on hybrid per...
13940             Plasmonic communications light on a wire
Name: ManuscriptTitle, dtype: object
13950    Ultrafast characterization of the electron inj...
13951    αFAPbI3 powder presynthesized by microwave irr...
Name: ManuscriptTitle, dtype: object
16158    Perovskite/polyethylene oxide composites Towar...
16163    Preparation sintering and electrochemical perf...
16166    The rattler effect of phonon propagation in de...
Name: ManuscriptTitle, dtype: object
674    Charge separation in type II tunneling multila...
702    Triazatruxenebased Hole Transporting Materials...
Name: ManuscriptTitle, dtype: object
13777    Yttrium (Y) doped ZnO nanowire/pSi heterojunct...
13781    Defectinduced magnetism in undoped wide band g...
13828    Magnetic and electronic properties of transiti...
13863    Environmentinduced reversible modulation of op...
Name: ManuscriptTitle, dtype: object
15718    Light induced damage and repair in nucleic aci...
15723    Improved power conversion efficiency for bulk ...
Name: ManuscriptTitle, dtype: object
8053    Lightinduced degradation of fullerenes in orga...
8084    Investigation of the photocorrosion of nGaP ph...
Name: ManuscriptTitle, dtype: object
14121                       Lithium insertion in La2MiO4+y
14133    An advance towards the synthesis of Ag nanorod...
Name: ManuscriptTitle, dtype: object
4968     TlP 5 an unexplored direct band gap 2D semicon...
16962    Synthesis characterization and optoelectronic ...
Name: ManuscriptTitle, dtype: object
5011    Porosity induced rigidochromism in platinum (i...
5058    Cadmium deoxycholate a new and efficient precu...
Name: ManuscriptTitle, dtype: object
4970     Novel IV–V–VI semiconductors with ultralow lat...
16963    Various coordination modes in mercury (II) com...
Name: ManuscriptTitle, dtype: object
16301    A comparative study on the performance of hybr...
16320    ZnO Nanoparticles Photosensitization Using Rut...
Name: ManuscriptTitle, dtype: object
16325    Electronic and magnetic properties of X2YZ and...
16326    Compensated half metallicity in osmium double ...
Name: ManuscriptTitle, dtype: object
10081    Timeresolved luminescence in conducting polyme...
10082    Production of nanometersize GaAs nanocristals ...
10092    Recent advances on the optical properties of E...
Name: ManuscriptTitle, dtype: object
15436    Perovskitelike ceramic hole transport material...
15453    Multifunctional highly efficient bipolar 9 9di...
Name: ManuscriptTitle, dtype: object
15431    Highperformance CsPbI3 perovskite solar cells ...
15489    Crystal Structures and PhaseTransitions Analys...
Name: ManuscriptTitle, dtype: object
15459    Interpenetrated Double PillaredLayer CoII MOFs...
15460    Endocyclic and Endo–Exocyclic Silver (i) Compl...
Name: ManuscriptTitle, dtype: object
12996    A nonvolatile memory device consisting of grap...
13003    Magnetic separation of colloidal nanoparticle ...
13006    Atomefficient synthesis of a benchmark electro...
13007    Core–shell structured TiO2@ polydopamine for h...
Name: ManuscriptTitle, dtype: object
8903    PLASMAS AND ELECTRICAL DISCHARGES (PACS 5152)M...
8904    Impedance spectroscopy of thinfilm CdTe/CdS so...
Name: ManuscriptTitle, dtype: object
1736    Defect Engineering Stabilized AgSbTe2 with Hig...
9354    Managing Phase Purities and Crystal Orientatio...
Name: ManuscriptTitle, dtype: object
16591    Cubic garnet solid polymer electrolyte for roo...
16596    Synthesis and physical properties of nanopowde...
Name: ManuscriptTitle, dtype: object
836     High Gravimetric and Volumetric Ammonia Capaci...
1023    Band engineering in core/shell ZnTe/CdSe for p...
Name: ManuscriptTitle, dtype: object
16104    Structural Chemistry of a New 10H Hexagonal Pe...
16113    Transition metal impurities in fluorides Role ...
16127    Optoelectronic properties of graphene quantum ...
Name: ManuscriptTitle, dtype: object
16136    Compatibility of DFT+ U with noncollinear magn...
16137    Efficacious symmetryadapted atomic displacemen...
Name: ManuscriptTitle, dtype: object
16106    Squeezing resulting from a fourthorder interac...
16114    Halide anions driven selfassembly of haloperfl...
Name: ManuscriptTitle, dtype: object
16078    Carrier signal injection alternatives for sens...
16107    Squeezing enhancement by competing nonlinearit...
Name: ManuscriptTitle, dtype: object
16546    Structure and mechanical properties of HSS HS6...
16549    Structure and reaction with lithium of tetrago...
16550    Thermal and mechanical characterization of inj...
Name: ManuscriptTitle, dtype: object
16542    Magnetic properties of Mgferrite after milling...
16548    Mechanical properties and pitting corrosion be...
Name: ManuscriptTitle, dtype: object
14692    Microplasmas technologies for engineering of s...
14701    Metal ion enhanced charge transfer in a terpyr...
Name: ManuscriptTitle, dtype: object
11493    Atomic layer deposition of germaniumseleniumte...
11575    Structural evolution of molybdenum disulfide p...
Name: ManuscriptTitle, dtype: object
11536    Determination of Carrier Diffusion Length Usin...
11578    Förster Resonance Energy Transfer Mediated Ch...
Name: ManuscriptTitle, dtype: object
11474    Tin dioxide as an alternative window layer for...
11476    Preface for the special topic collection comme...
11478                             Sixty years of diversity
11488    Atomic layer deposition of molybdenum disulfid...
11537            Ferromagnetism in 57Fe‐doped cupric oxide
11539              Nanowire–quantum‐dot–polymer solar cell
11542    Ab initio study of structural electronic elast...
11544    Dynamically Switching the Electronic and Elect...
11547    Inhomogeneous Broadening of Photoluminescence ...
11549    Graphene Membranes for Hall Sensors and Microp...
11554    Facile Deposition of Nb2O5 Thin Film as an Ele...
11555    Nitrogendoped graphene oxide electrocatalysts ...
11557    Heteroleptic NIREmitting YbIII/AnilateBased Ne...
11558    ColorTunable AllInorganic CsPbBr3 Perovskites ...
11561    Surface Functionalization of CsPbBr3 Νanocryst...
11649    Study of the La1/2+ 1/2xLi1/21/2xTi1xAlxO3 (0≤...
11651    Structural characterization and EXAFS wavelet ...
11661    Controlled synthesis of zerodimensional phasep...
Name: ManuscriptTitle, dtype: object
6551    Uncovering the SelfOrganized Nanowires on AuMo...
6608    Phase diagram of methylammonium/formamidinium ...
Name: ManuscriptTitle, dtype: object
17294        Spectrophotometric determination of hydrazine
17312    Elucidating DFT study on structural electronic...
Name: ManuscriptTitle, dtype: object
1192    Tracking photoexcited carriers in hybrid perov...
8822    Longitudinal carrier density profiling in semi...
Name: ManuscriptTitle, dtype: object

5227    Solvents for Processing Stable Tin Halide Pero...
5233    SizeDependent Lattice Structure and Confinemen...
Name: ManuscriptTitle, dtype: object
5184    Impact of layer thickness on the charge carrie...
5185    Degradation of highly alloyed metal halide per...
Name: ManuscriptTitle, dtype: object
5209    Improved morphology and efficiency of n–i–p pl...
5235    Suppressing cation migration in triplecation l...
Name: ManuscriptTitle, dtype: object
5219    Tailoring phase purity in the 2D/3D perovskite...
5220    Efficient exciton diffusion in organic bilayer...
Name: ManuscriptTitle, dtype: object
5226    Mesoporous electronselective contacts enhance ...
5234    Enhanced OpenCircuit Voltage of WideBandgap Pe...
Name: ManuscriptTitle, dtype: object
10645    Sputtered Zn (O S) for junction formation in c...
10646    Unambiguous Determination of Local Orientation...
10647    Facile Synthesis of NaBiS2 Nanoribbons as a Pr...
Name: ManuscriptTitle, dtype: object
5880    Effect of precursor solution aging on the crys...
5891    New Generation Hole Transporting Materials for...
Name: ManuscriptTitle, dtype: object
6000    A Smooth CH3NH3PbI3 Film via a New Approach fo...
6002    Exciton and Charge Carrier Dynamics in Highly ...
Name: ManuscriptTitle, dtype: object
13085    Disorder and polymorphism in Cu (ii)polyoxomet...
13088    Molecular crystals of 2amino1 3 4thiadiazole w...
Name: ManuscriptTitle, dtype: object
13272    First proofofprinciple of inorganic lead halid...
13274    Electrical and Optical Characterization of CsP...
Name: ManuscriptTitle, dtype: object
4170    Single component organic solar cells based on ...
4175    Epitaxial Metal Halide Perovskites by Inkjet‐P...
Name: ManuscriptTitle, dtype: object
5108     Halide segregation versus interfacial recombin...
11107    Efficient bandgap widening in coevaporated MAP...
Name: ManuscriptTitle, dtype: object
1461    Perovskite Solar Cells Low‐Dimensional Perovsk...
1470    Choose your own adventure fabrication of monol...
Name: ManuscriptTitle, dtype: object
5434     Synthesis and optical properties of thiolstabi...
10035    Photocatalytic Production of Vanillin over CeO...
Name: ManuscriptTitle, dtype: object
12527    The effects of hydroxyl by water addition on t...
12533    AFM studies on formation of new phase responsi...
Name: ManuscriptTitle, dtype: object
12529    Ultraviolet upconversion luminescence enhancem...
12534    Lightemitting diodes based on quaternary CdZnS...
Name: ManuscriptTitle, dtype: object
12525    Tenfold increase in efficiency from a referenc...
12538    Thermally activated delayed fluorescence of bi...
Name: ManuscriptTitle, dtype: object
448     Tuning structural isomers of phenylenediammoni...
8818    Luminescent properties and electronic structur...
Name: ManuscriptTitle, dtype: object
762     “Magnetinthesemiconductor” FePt− PbS and FePt−...
1045    Hightemperature–shorttime annealing process fo...
Name: ManuscriptTitle, dtype: object
7265    Analysis of diamond nanocrystal formation from...
7296    Benchmark study for the application of density...
Name: ManuscriptTitle, dtype: object
1798    Photonic Synapses Retina‐Inspired Carbon Nitri...
1900    Photoprotection in metal halide perovskites by...
Name: ManuscriptTitle, dtype: object
245    Industry outlook of perovskite quantum dots fo...
286    Colloidal quantumdot lightemitting diodes with...
Name: ManuscriptTitle, dtype: object
6101     Chlorineassisted sizecontrolled synthesis and ...
13111    Broadband antireflection with halide perovskit...
Name: ManuscriptTitle, dtype: object
522      Giant tunnelling electroresistance in metal/fe...
13113    Reconfigurable Near‐field Enhancement with Hyb...
Name: ManuscriptTitle, dtype: object
242      Tracking the dynamics of circulating tumour ce...
13110    All‐Optical Nanoscale Heating and Thermometry ...
Name: ManuscriptTitle, dtype: object
13129    Nanoscale hydrodynamic instability in a molten...
13130    Surface ablation оf aluminum and silicon by ul...
Name: ManuscriptTitle, dtype: object
6143     Opencircuit voltage limitation in lowbandgap d...
13112    Direct Imprinting of Laser Field on Halide Per...
Name: ManuscriptTitle, dtype: object
3915     Nonequilibrium thermodynamics of charge separa...
13115    Optically Reconfigurable Spherical Ge‐Sb‐Te Na...
Name: ManuscriptTitle, dtype: object
6222     Energy transfer between confined dye and surfa...
13131    Ultrafast electron dynamics on the silicon sur...
Name: ManuscriptTitle, dtype: object
1200     Unusual activity of rationally designed cobalt...
12939    Synthesis of Cu 2 ZnSnS 4 thin films directly ...
Name: ManuscriptTitle, dtype: object
11418    Noninvasive Subsurface Electrical Probe for En...
11529    Coupling with the Jahn‐Teller mode for triplet...
Name: ManuscriptTitle, dtype: object
12275    New polymer matrix system for phosphorescent o...
12375    Detailed simulation of the role of functionali...
Name: ManuscriptTitle, dtype: object
8497    Silicon heterojunction solar cells with electr...
8499                         Flexible silicon solar cells
9706    Strong blue photoluminescence from singlecryst...
Name: ManuscriptTitle, dtype: object
2499    Twodimensional  photonic crystal membrane lase...
9817    Advances and challenges in tin halide perovski...
Name: ManuscriptTitle, dtype: object
2517    Polymer defect states modulate opencircuit vol...
6962    Giant optical polarization rotation induced by...
Name: ManuscriptTitle, dtype: object
8465    Dynamic modeling of combined concentrating sol...
9694    Oxygen vacancy dynamics in Pt/TiOx/TaOy/Pt mem...
Name: ManuscriptTitle, dtype: object
8463    Effective Ca2+doping in Sr1xCaxFeO3δ oxygen ca...
9693    Surface deformations as a necessary requiremen...
Name: ManuscriptTitle, dtype: object
11943    Toward high volume solution based rolltoroll p...
11977    Fluorescence quenching in porous silicon/conju...
12042    Thermoelectric oxide modules (TOMs) for the di...
Name: ManuscriptTitle, dtype: object
15131    Copolymers Comprising 2 7‐Carbazole and Bis‐be...
15135    Frontispiece Lights and Shadows of DMSO as Sol...
Name: ManuscriptTitle, dtype: object
1951    Perovskite ink with wide processing window for...
2088    Comparing multiple exciton generation in quant...
Name: ManuscriptTitle, dtype: object
2021         LightEmitting Halide Perovskite Nanoantennas
2138    Phonon interaction and phase transition in sin...
Name: ManuscriptTitle, dtype: object
16573    Structure and properties of HS652 type HSS man...
16601    Copper metallopolymer catalyst for the electro...
16607    Tradeoff analysis of C12A7 e− deposition techn...
Name: ManuscriptTitle, dtype: object
16566    Electrochemical and structural characterizatio...
16599    Using MetalOrganic Framework HKUST1 for the Pr...
Name: ManuscriptTitle, dtype: object
16597    Synthesis and characterization of novel anion ...
16600    Melamine foams decorated with insitu synthesiz...
16608    Stationkeeping of a highaltitude balloon with ...
Name: ManuscriptTitle, dtype: object
10615    Preparation and photophysical properties of na...
10616    Toward the stabilization of perovskite phase a...
Name: ManuscriptTitle, dtype: object
13595    KINETICS; ATMOSPHERIC AND ENVIRONMENTAL PHYSIC...
13602    MOLECULAR STRUCTURE BONDING QUANTUM CHEMISTRY ...
13603    MOLECULAR STRUCTURE BONDING QUANTUM CHEMISTRY ...
Name: ManuscriptTitle, dtype: object
12008    Template‐Free Macro‐Mesoporous TiO2/Carbon Nit...
12030    Investigation of Activated‐Carbon‐Supported Co...
Name: ManuscriptTitle, dtype: object
13367    Ultrasmall Quantum Dots A Tool for in Vitro an...
13370    A Study on the Emergence of PType Behaviour in...
Name: ManuscriptTitle, dtype: object
10732    Interfacial degradation in organic optoelectro...
10755    A radiation sensitive hybrid polymer based on ...
Name: ManuscriptTitle, dtype: object
16654    Phase transitions in titanium diselenide inter...
16661    Search for Pnma materials with hightemperature...
Name: ManuscriptTitle, dtype: object
16655    Highpressure hightemperature synthesis of Cr2O...
16660    Crystal structure and thermal expansion of Mn1...
16662    Crystal growth and twinned crystal structure o...
16663    Modecrystallography analysis and magnetic stru...
16664    Cation distribution in Cu2ZnSnSe4 Cu2FeSnS4 an...
16667    Effect of Fe doping on structure and magnetotr...
16668    Electronic structure magnetic mechanical and t...
16672    Insight into pressure tunable structural elect...
Name: ManuscriptTitle, dtype: object
7102    Molecularmediated assembly of silver nanoparti...
7103    Formation of complex nanostructures driven by ...
Name: ManuscriptTitle, dtype: object
6955    Deaging and asymmetric energy landscapes in el...
6956    Individual Barkhausen pulses of ferroelastic n...
Name: ManuscriptTitle, dtype: object

8891    Infrared detection of hydrogengenerated free c...
8909    Bandgap engineering of layered monochalcogenid...
Name: ManuscriptTitle, dtype: object
2066    Fermi Level of Surface States in TiO2 Nanopart...
2071    Lowthreshold blue quasi2D perovskite laser thr...
Name: ManuscriptTitle, dtype: object
1122     MicrocarrierAssisted inorganic shelling of lea...
13464    Thiocyanate‐and Thiol‐Functionalized p‐Doped Q...
Name: ManuscriptTitle, dtype: object
1211    Effect of Electron–Hole Overlap and Exchange I...
8823    UV∕ ozone treated Au for airstable low hole in...
Name: ManuscriptTitle, dtype: object
5930    A universal interface layer based on an amine‐...
5941    Determining Structure‐Activity Relationships i...
Name: ManuscriptTitle, dtype: object
6535    Revealing structure reactivity relationships i...
6615    Automatic prediction of surface phase diagrams...
Name: ManuscriptTitle, dtype: object
1590    Perovskite Solar Cells Surface Ligand Manageme...
1596    Controlling the interaction of light with poly...
Name: ManuscriptTitle, dtype: object
17268    Exploring the Constructive Alignment of Pedago...
17270    ReExamination of the Structure of Sr2 (MgTe) O...
Name: ManuscriptTitle, dtype: object
4511    kSpace Hyperspectral Imaging by a Birefringent...
4528    Spectralstable blue emission from moisturetrea...
Name: ManuscriptTitle, dtype: object
7080     Electrically tunable Berry curvature and stron...
7082     Vitality surveillance at distance using thinfi...
13916    Device performance and light characteristics s...
Name: ManuscriptTitle, dtype: object
3072    Turning Detrimental Effect into Benefits Enhan...
3164    Tuning the Optoelectronic Properties of Hybrid...
Name: ManuscriptTitle, dtype: object
4359     Bifunctional interfaces by poly (ionic liquid)...
17175    First example of the formation of a Si–C bond ...
Name: ManuscriptTitle, dtype: object
16265    Role of dopant cations in the gelation behavio...
16276    Highly sensitive detection and removal of merc...
Name: ManuscriptTitle, dtype: object
16266                   Solgel preparation of silica glass
16268    Study of energy bands and magnetic properties ...
Name: ManuscriptTitle, dtype: object
10450    Specific heat and thermodynamic functions for ...
10488    Graphenebased technologies for energy applicat...
Name: ManuscriptTitle, dtype: object
174    Efficient charge generation by relaxed charget...
218    Phonon coherences reveal the polaronic charact...
Name: ManuscriptTitle, dtype: object
1172      Single Trap States in Single CdSe Nanoplatelets
8757    A protected excitationenergy reservoir for eff...
Name: ManuscriptTitle, dtype: object
1135    Anticorrelation between local photoluminescenc...
8747    Morphological and chemical transformations of ...
Name: ManuscriptTitle, dtype: object
1987    Highefficiency colloidal quantum dot photovolt...
2027    Stimulated Raman scattering from Mieresonant s...
Name: ManuscriptTitle, dtype: object
8937    Thermal stability and interfacial properties o...
8938    Ferroelectric thin films Review of materials p...
Name: ManuscriptTitle, dtype: object
8621     Large area nanopatterning of alkylphosphonate ...
14266    Detailed chemical mechanism of the phase trans...
Name: ManuscriptTitle, dtype: object
8067    Molecular aggregation method for perovskite–fu...
8111    Lowcost coenzyme Q10 as an efficient electron ...
Name: ManuscriptTitle, dtype: object
2821    Optically excited multiband conduction in LaAl...
2837    Switchable and tunable film bulk acoustic reso...
Name: ManuscriptTitle, dtype: object
992    Singlemode lasing from imprinted halideperovsk...
994    Gallium phosphide nanowires in a freestanding ...
Name: ManuscriptTitle, dtype: object
4945    Luminance efficiency rolloff mechanism in CsPb...
4947    Mechanochemical synthesis of onedimensional (1...
Name: ManuscriptTitle, dtype: object
14148    Fabrication and Characterization of Dye sensit...
14180    Hydrothermal treatment for the marked structur...
14190    Deposition of iron sulfide thin films by AACVD...
Name: ManuscriptTitle, dtype: object
14016    Influence of impurities on the luminescence of...
14074    Electronic and optical properties of double pe...
Name: ManuscriptTitle, dtype: object
16503    Highly sensitive watersoluble fluorescent pH s...
16504    Perylene bisimide dyes with up to five indepen...
Name: ManuscriptTitle, dtype: object
14661    Structural modifications induced in silicate g...
14667      The mechanism of glass foaming with water glass
Name: ManuscriptTitle, dtype: object
10195    Solvent free synthesis of nanocrystalline hexa...
10257              Inkjet printing of 2D layered materials
Name: ManuscriptTitle, dtype: object
4042    Tuning the Work Function of Polar Zinc Oxide S...
4043    Correlated Donor/Acceptor Crystal Orientation ...
Name: ManuscriptTitle, dtype: object
10443    Xray powder diffraction results for the phase ...
10445    Highpressure Raman study of the Sr2CaWO6 doubl...
Name: ManuscriptTitle, dtype: object
6158     Transition from Photoconductivity to Photovolt...
13442    Procedure Based on External Quantum Efficiency...
Name: ManuscriptTitle, dtype: object
10738    Aggregation and structural study of the monola...
10739    Synthesis and photophysical studies of an indi...
10743    Effects of bovine serum albumin on light activ...
10746    Passivation by pyridineinduced PbI 2 in methyl...
Name: ManuscriptTitle, dtype: object
15401    Modeling and simulation of bifacial perovskite...
15467    Self‐assembly Behavior of Metal Halide Perovsk...
Name: ManuscriptTitle, dtype: object
7407    Origin of the different color of ruby and emerald
7421    Internal electric fields and color shift in Cr...
Name: ManuscriptTitle, dtype: object
7577     CHEMICAL CONTROL OF HOLEDOPED SUPERCONDUCTIVIT...
15641    Characterization of recombination properties a...
Name: ManuscriptTitle, dtype: object
2328    Organic molecular films on gold versus conduct...
2330    Correlation between interface energetics and o...
Name: ManuscriptTitle, dtype: object
8081    Thermal annealing reduces geminate recombinati...
8094    Fundamentals of tin iodide perovskites a promi...
8124    Facile preparation of nitrogendoped nanostruct...
Name: ManuscriptTitle, dtype: object
10651    Stability issues of the next generation solar ...
10652    The Role of Potassium in the Segregation of MA...
Name: ManuscriptTitle, dtype: object
15447    Design of donoracceptor small molecules based ...
15452    Diketopyrrolopyrrole pigment core@ multilayer ...
Name: ManuscriptTitle, dtype: object
9971    2Methylimidazole as an interlayer for the enha...
9976    High mass loading additivefree LiFePO4 cathode...
Name: ManuscriptTitle, dtype: object
9968    Properties of zirconia thin layers elaborated ...
9969    Graphene quantum dots decorated TiO2 mesoporou...
Name: ManuscriptTitle, dtype: object
3803    Crystal Orientation and Grain Size Do They Det...
3807    Crystal orientation drives the interface physi...
Name: ManuscriptTitle, dtype: object
10141    Theoretical study of the magnetic anisotropy a...
10176    Polarizationdependence in multiquantum well la...
Name: ManuscriptTitle, dtype: object
5608    Catalyzed microwaveassisted preparation of car...
5611    Effect of Various Deep Eutectic Solvents on th...
Name: ManuscriptTitle, dtype: object
15905    Electric‐field‐induced domain switching and do...
15910    Piezoelectric softening by Nb substitution in ...
Name: ManuscriptTitle, dtype: object
12348    Ab initio calculation of electronic transport ...
12380    Constraints in postsynthesis ligand exchange f...
Name: ManuscriptTitle, dtype: object
17157    Fabricating SnO2 and Cu2O anchored on gC3N4 na...
17160    High ensemble concentration of photostable NV ...
17162    Chemical targets to deactivate biological and ...
Name: ManuscriptTitle, dtype: object
15271          Grainsizeinduced ferroelectricity in NaNbO3
15278    Revealing the impact of acceptor dopant type o...
Name: ManuscriptTitle, dtype: object
12093    Phenylenevinylene Block Copolymers via Ring‐Op...
12143    Synthesis and electroluminescence properties o...
Name: ManuscriptTitle, dtype: object
14517    Elastic and dielectric measurements of the str...
14530    Characterization of laserdoped localized pn ju...
Name: ManuscriptTitle, dtype: object
16068    Electric field induced relaxor behavior in ani...
16072    A study on the control design of nonisolated c...
Name: ManuscriptTitle, dtype: object
15376    Enhancing the stability of planar perovskite s...
15377    Achieving exceptional activity and durability ...
Name: ManuscriptTitle, dtype: object
2734    Design of highperformance memristor cell using...
2759    Temperaturedependent leakage current character...
Name: ManuscriptTitle, dtype: object
4563    Impact of photon recycling grain boundaries an...
4566    Plasmonmodulated photoluminescence of single g...
Name: ManuscriptTitle, dtype: object
12411    Aggregation of anthraquinone dye molecules in ...
12414    Synthesis of highly conductive titanium suboxi...
Name: ManuscriptTitle, dtype: object
16382     Renaissance of tin halide perovskite solar cells
16390    Influence of lignite fly ash on the structural...
Name: ManuscriptTitle, dtype: object
763     Threedimensional nanocrystal superlattices gro...
5502    Silicon nanoparticles a new and enhanced opera...
5507    RF magnetron sputtering processed transparent ...
5508    Influence of Li doping on structural electrica...
Name: ManuscriptTitle, dtype: object
15143    Red shift in optical excitations on layered co...
15144       The Weak 3D Topological Insulator Bi12Rh3Sn3I9
Name: ManuscriptTitle, dtype: object
1970     Perovskite solar cells Different facets of per...
16039    Pseudo Jahn–Teller origin of ferroelectric ins...
Name: ManuscriptTitle, dtype: object
6970    Cannelli Cantelli and Cordero replyPower laws ...
6971    Magnetism and correlations in fractionally fil...
Name: ManuscriptTitle, dtype: object
2425       Optical characterization of disordered  alloys
2610    Gettering of Au to dislocations and cavities i...
Name: ManuscriptTitle, dtype: object
15865    SpectrallySelective Photonic Structures for PV...
15866    Concentrating Solar Power Advances in Geometri...
Name: ManuscriptTitle, dtype: object
11980    Electronic and Ionic Electric Field Screening ...
12009    Three‐dimensional amorphous silicon solar cell...
Name: ManuscriptTitle, dtype: object
559    Pressure driven rotational isomerism in 2D hyb...
560    Unlocking surface octahedral tilt in twodimens...
562    Orientation dependent molecular electrostatics...
Name: ManuscriptTitle, dtype: object
405    Carrier separation and transport in perovskite...
684    Importance of the donor fullerene intermolecul...
685    Molecular design of semiconducting polymers fo...
Name: ManuscriptTitle, dtype: object
3213    Highly Luminescent WS2 Quantum Dots/ZnO Hetero...
3227    Facile Strategy for Third Component Optimizati...
3233    LowTemperature TiOx Compact Layer for Planar H...
Name: ManuscriptTitle, dtype: object
3057    Bifacial colortunable semitransparent perovski...
3074    Chlorinedoped perovskite oxide a platinumfree ...
Name: ManuscriptTitle, dtype: object
7868     Luminescence of Ce3+ in Y2SiO5 nanocrystals Ro...
15059    Metal halide perovskite toxicity effects on Ar...
Name: ManuscriptTitle, dtype: object
12340    Biastemperature instability on the back gate o...
12434    Interfacial Structure Modifying Interlayers Eq...
Name: ManuscriptTitle, dtype: object
12294    Photoluminescence properties of nanocrystallin...
12385    Ligandexchange dependent properties of hybrid ...
Name: ManuscriptTitle, dtype: object
11454    Effect of  addition on surface reactions durin...
11457    Low temperature plasma deposition of silicon n...
Name: ManuscriptTitle, dtype: object
3560     Amorphous molybdenum phosphide nanoparticles f...
16009    Crack detection sensor layout and bus configur...
Name: ManuscriptTitle, dtype: object
14134    Silver oxide nanoparticles synthesized by gree...
14143    Structural optical and Raman studies of Co3O4 ...
16925    Theoretical investigation of ternary semicondu...
Name: ManuscriptTitle, dtype: object
5115    Revealing fundamental efficiency limits of mon...
6960    Class of molecular and solid state systems wit...
Name: ManuscriptTitle, dtype: object
16932    Lowtemperature solid oxide fuel cells based on...
16937    Synthesis morphology and optical properties of...
Name: ManuscriptTitle, dtype: object
5937    Resolving a critical instability in perovskite...
5939    Development of dopant‐free organic hole transp...
Name: ManuscriptTitle, dtype: object
14721    Comparison of nickel titanate (NiTiO3) powders...
14722    Hydrothermally synthesized urchinlike NiO nano...
Name: ManuscriptTitle, dtype: object
2254    Catalyst synthesis under CO2 electroreduction ...
2273    Author Correction Dopantinduced electron local...
Name: ManuscriptTitle, dtype: object
2277    Mechanically controlled quantum interference i...
2279                    A handle on charge reorganization
Name: ManuscriptTitle, dtype: object
2256    Constraining CO coverage on copper promotes hi...
2272    Reagentless biomolecular analysis using a mole...
Name: ManuscriptTitle, dtype: object
8024    Effective defect passivation with a designer i...
8177    Perovskite nanostructures for photovoltaic and...
Name: ManuscriptTitle, dtype: object
12936    Cu 2 ZnSnS 4 nanocrystal dispersions in polar ...
12937    Synthesis of singlecrystalline anatase nanorod...
Name: ManuscriptTitle, dtype: object
2436    Characteristics of ultraviolet photoluminescen...
6951    SelfOrganized Formation of Compositionally Mod...
Name: ManuscriptTitle, dtype: object
17285    Hydrogen Bonding in the Water Stabilized Struc...
17289    Fabrication and characterization of Nidecorate...
Name: ManuscriptTitle, dtype: object
12852    Reply to “Structural and magnetic behavior of ...
12902    Some unsymmetrical nickel 1 2dithiolene comple...
Name: ManuscriptTitle, dtype: object
12886    Light emitting diodes based on blends of quasi...
12906    Reinspection of formation of BiFe1xMnxO3 solid...
Name: ManuscriptTitle, dtype: object
11523    Nernst–Ettingshausen and magnetoresistance eff...
11636    Depolarization of ferroelectric materials meas...
Name: ManuscriptTitle, dtype: object
10804    Vibrational and electronic peculiarities of Ni...
10819    Temperatureinduced work function changes in Mn...
Name: ManuscriptTitle, dtype: object
10342    Realizing 17.0% external quantum efficiency in...
10354    Sidegroup engineering The influence of norborn...
Name: ManuscriptTitle, dtype: object
13266    Perovskite Nanostructures From Material Design...
13268    Conjugates of Ultrasmall Quantum Dots and Acri...
Name: ManuscriptTitle, dtype: object
14647    Introduction of crystalline highk gate dielect...
14649    Interpretation of the critical length scale de...
14656    NonDebye conductivity relaxation in the nonArr...
Name: ManuscriptTitle, dtype: object
14898    Electrical and structural functionality of CIG...
14924    Evaluating Intrinsic Defects Across CIGS Absor...
Name: ManuscriptTitle, dtype: object
12574    Efficient and robust reforming catalyst in sev...
12586    Organic linker defines the excited‐state decay...
12595    Highly Soluble Benzo [ghi] perylenetriimide De...
Name: ManuscriptTitle, dtype: object
2392    Spectral properties of resonantcavity polyfluo...
2394    Device degradation of polymer light emitting d...
Name: ManuscriptTitle, dtype: object
8046    Control by MixedChloride Additives of the Qual...
8047    Nonfullerene acceptor with low energy loss and...
8065    A thermally stable bariumstabilized αCsPbI 3 p...
Name: ManuscriptTitle, dtype: object
11538    Operation and catastrophic optical degradation...
11541    Accurate and Efficient Approximate Quasipartic...
11559    Arresting Photodegradation in Semiconducting S...
Name: ManuscriptTitle, dtype: object
17464    TemperatureDependent Crystallization Mechanism...
17468    Recovery of acetaminophen from aqueous solutio...
17469    A SelfConsistent Scheme for Understanding Part...
17470    DIELECTRIC AND PIEZOELECTRIC PROPERTIES OF (K ...
Name: ManuscriptTitle, dtype: object
7342    Strong dependence on doping of a lowactivation...
7349    Hydrogen tunneling in the perovskite ionic con...
Name: ManuscriptTitle, dtype: object
5931    Inverted Environmentally Stable Perovskite Sol...
5958    Interdot Lead Halide Excess Management in PbS ...
Name: ManuscriptTitle, dtype: object
1324    Linear Electro‐Optic Modulation in Highly Pola...
1481    Artificial chemist an autonomous quantum dot s...
Name: ManuscriptTitle, dtype: object
11521    Pressure‐induced insulator–metal transition in...
11615    Doping and defect engineering induced extremel...
Name: ManuscriptTitle, dtype: object
11621    Hopping and tunnelling of D trapped by substit...
11627    Elastic and anelastic properties of Marval 18 ...
Name: ManuscriptTitle, dtype: object
6901    Tuning the Electrical and Thermoelectric Prope...
6916    Programmable devices based on reversible solid...
6920    A thin and flexible scanner for fingerprints a...
6928    Controlling the early stages of pentacene grow...
6942    Ferromagnetism in dilute magnetic semiconducto...
6945    Tunable magnetic interaction at the atomic sca...
Name: ManuscriptTitle, dtype: object
6899    Verification of TypeA and TypeBHC Blinking Mec...
6915    Unipolar barrier photodetectors based on van d...
6918    Efficient lightemitting diodes from mixeddimen...
Name: ManuscriptTitle, dtype: object
6914    Bidirectional optical signal transmission betw...
6929    Investigating molecular charge transfer comple...
Name: ManuscriptTitle, dtype: object
6925    Intermolecular hybridization governs molecular...
6926            Band bending in conjugated polymer layers
Name: ManuscriptTitle, dtype: object
3221    Enhancing the photocatalytic performance of MX...
3232    Laurionite Competes with 2D Ruddlesden–Popper ...
Name: ManuscriptTitle, dtype: object
1386    How to quantify the efficiency potential of ne...
1395    Blue Light‐Emitting Devices Based on Novel Pol...
1463    Amplified Spontaneous Emission from CoreSeeded...
Name: ManuscriptTitle, dtype: object
1329    Controlled Crystal Plane Orientations in the Z...
1333    Solvent‐Assisted Kinetic Trapping in Quaternar...
1334    Solar Cells Overcoming the Ambient Manufactura...
Name: ManuscriptTitle, dtype: object
15863    Carbazole Electroactive Amorphous Molecular Ma...
15864    Impact of widebandgap technology on renewable ...
Name: ManuscriptTitle, dtype: object
16895    Effect of Ydoped NbB2. 5 on structural and sup...
16897    Study of Halfmetallic Properties of Co2YGe (Y ...
16903    Catalytic abatement of CO species from incompl...
Name: ManuscriptTitle, dtype: object
16874    Anomalous H/sub c/in CoCrfilms surface and bul...
16880    Effect of interdot distance on magnetic behavi...
Name: ManuscriptTitle, dtype: object
8401     Transparent Light‐Emitting Electrochemical Cells
8436    Operationally Stable Perovskite Light Emitting...
Name: ManuscriptTitle, dtype: object
6793    Formation of charged ferroelectric domain wall...
6827    Mitigation of acylhomoserine lactone (AHL) bas...
Name: ManuscriptTitle, dtype: object
6784    Anomalous exchange bias at collinear/noncollin...
6786    Longrange electronic reconstruction to a dxz y...
6798    Highperformance flexible supercapacitors obtai...
6802    Dramatic changes in thermoelectric power of ge...
6803    Author Correction Discovery of Fe7O9 a new iro...
6804    Xray scintillation in lead halide perovskite c...
6812    Deposition of topological silicene germanene a...
6814    Spatiotemporal behaviour of atomicscale triboc...
6818    Copper sulfide nanoparticles as highperformanc...
6835    Ultrafast energy transfer in ultrathin organic...

851               Cu–In halide perovskite solar absorbers
5595    Quantumdot double layer polymer waveguides by ...
Name: ManuscriptTitle, dtype: object
4012    High‐Quality Photonic Crystals Infiltrated wit...
4016    Nanostructured architectures for biomolecular ...
Name: ManuscriptTitle, dtype: object
4022    High fill factor and open circuit voltage in o...
4024    Intrinsic surface dipoles control the energy l...
Name: ManuscriptTitle, dtype: object
4013    Donor–Acceptor C60‐Containing Polyferrocenylsi...
4014    Spatial collection in colloidal quantum dot so...
4038    Nongeminate recombination and charge transport...
4047    Suppression of the Keto‐Emission in Polyfluore...
Name: ManuscriptTitle, dtype: object
13474    Routes to tin chalcogenide materials as thin f...
13480    pHInduced Surface Modification of Atomically P...
Name: ManuscriptTitle, dtype: object
10197    ARS process to nanocrystalline BaMxAl12xO19δ (...
10222    P‐26 Thermally Annealed Asymmetric‐Offset Poly...
Name: ManuscriptTitle, dtype: object
6857    Theoretical prediction of twodimensional BC2X ...
6894    Photocatalytic generation of hydrogen by cores...
Name: ManuscriptTitle, dtype: object
14035    Magnetic properties of superparamagnetic nanop...
14067    Pressureinduced phase transitions in Si observ...
Name: ManuscriptTitle, dtype: object
14032    The role of intrinsic and surface states on th...
14033    Sequentially vaporgrown hybrid perovskite for ...
Name: ManuscriptTitle, dtype: object
14137    Photocatalytic degradation of Rhodamine dyes u...
14138    Mechanical measurements of pure and kaolin rei...
14140    Synthesis and characterization of sol–gel deri...
Name: ManuscriptTitle, dtype: object
14839    Solar cells based on colloidal quantum dot sol...
14871    Energy yield potential of perovskitesilicon ta...
14872    Introduction of Sb in CDTE and its effect on C...
Name: ManuscriptTitle, dtype: object
6405    Onestep microheterogeneous formation of rutile...
6407    Ternary Phase Diagrams of MAI–PbI2–DMF and MAI...
Name: ManuscriptTitle, dtype: object
826     Operational Mechanism of Conjugated Polyelectr...
5575    Protein Adsorption on Nanocrystalline TiO2 Fil...
Name: ManuscriptTitle, dtype: object
14571    The effect of LPCVD silicon nitride deposition...
14572    Characterization of the Si− SiO2 Interface Fol...
Name: ManuscriptTitle, dtype: object
6489    Effect of surface stoichiometry on blinking an...
6498    Photoluminescence Saturation in QuantumCutting...
Name: ManuscriptTitle, dtype: object
6488    Ultrafast manyparticle phenomena in lead bromi...
6581    Extending the compositional space of mixed lea...
6635    Investigating spatiotemporal correlation of mu...
Name: ManuscriptTitle, dtype: object
17533    The Influence of ginger spent loading on mecha...
17535    Graphene nanoplatelets polyvinyl alcohol nanoc...
Name: ManuscriptTitle, dtype: object
15643    Filterless spectral splitting perovskite–silic...
15645    Characterization of MAEtextured nanoporous sil...
Name: ManuscriptTitle, dtype: object
1593    A hard oxide semiconductor with a direct and n...
1594    Perovskites A Hard Oxide Semiconductor with A ...
Name: ManuscriptTitle, dtype: object
16404    A Review of 2D Perovskites and CarbonBased Nan...
16412    Variation of the structural and the magnetic p...
Name: ManuscriptTitle, dtype: object
13963    A method for electrochemical growth of homogen...
13966    Preparation of ZnO/Eu mixed films by electroch...
13967    Electrodeposition of NiO films and inverse opa...
13970    Growth of porous light scattering submicromete...
13971    Direct bioelectrocatalysis by multicopper oxid...
13976    Sodium polymer electrolytes composed of sulfon...
13977    Nonwoven polyaramid porous membranes as separa...
13980    Precise control of PbI2 excess into grain boun...
13988    Tuning the electrochemistry of homoleptic coba...
13989    Onepot synthesis of novel silverpolyanilinepol...
13991    Enhanced photovoltaic performance and stabilit...
13999    Electrochemical growth of FeS on threedimensio...
14004    In situ growth of ironnickel nitrides on carbo...
14011    Reduced hysteresis and enhanced air stability ...
14012    Near thresholdless laser operation at room tem...
14025    Micropillar electrode array from metal to diel...
14028    A defective 1D photonic crystalbased chemical ...
14038    The ion implantationinduced properties of oned...
14040    Strong localization effect and carrier relaxat...
14042    Lasing and Transport Properties of Poly [(9 9d...
14045    Energy of excitons and acceptor–exciton comple...
14046    Optical properties of acceptor–exciton complex...
14047    Low temperature mobilities of 2D electrons in ...
14053    Mobility and shortrange ordering of oxygen in ...
14056    Relation between charge ordering and local lat...
14059    Mobility of interstitial oxygen in scandium by...
14060    Influence of interstitial O on the cluster spi...
14061    Influence of nanoenvironment on luminescence o...
14062    Study of photoluminescence properties of Er3+ ...
14065    Thermoelectric power magnetoresistance of lead...
14075    Strong coupling characterisation of quasi1D po...
14080    Optical investigation of chargetransfer transi...
14081    Mechanical properties and electronic structure...
14085    Temperatureinduced magnetization reversal and ...
14094    Resistive switching of Pt/ZrO2/YBa2Cu3O7 sandw...
14099    Effects of Plasma Pretreatment on ZnO Depositi...
14100    Localization in highly strained In0. 35Ga0. 65...
14102    Belstein Journal of Nanotechnology Vol. 7 pp. ...
14109    Rectifying characteristics of a FeSrTiO3/NbSrT...
14111    Properties of silicon integrated photonic lens...
14112    Scanning probe microscopy applied to the study...
Name: ManuscriptTitle, dtype: object
13984    Improving photovoltaic performance of CsPbBr3 ...
14041    Enhanced Light Emission due to Formation of Se...
14082    Pursuit of stability electronic and thermoelec...
Name: ManuscriptTitle, dtype: object
14757    Development and application of an instrument f...
14758    Stoichiometric analysis of compositionally gra...
Name: ManuscriptTitle, dtype: object
8914    Growth of vacuum evaporated ultraporous silico...
8916    Dynamics of ion bombardmentinduced modificatio...
Name: ManuscriptTitle, dtype: object
8848    DIELECTRICS AND FERROELECTRICITY (PACS 77)Inve...
8871    Transmission properties at microwave frequenci...
8906    Determination of limiting factors of photovolt...
Name: ManuscriptTitle, dtype: object
10678    Facile laserassisted synthesis of inorganic na...
10688    Ligandstabilized CdSe nanoplatelet hybrid stru...
Name: ManuscriptTitle, dtype: object
10663    Tetracarboxylate Bis‐Bipyridine Ruthenium Dyes...
10682    Larger πextended anti/synaroylenediimidazole p...
Name: ManuscriptTitle, dtype: object
11728    Structural magnetic and dielectric properties ...
11730    Optimization of citrate complex combustion for...
Name: ManuscriptTitle, dtype: object
11675    Strain engineering of electronic structure pho...
11814    Ferromagnetism in halfmetallic EuGaO3 perovski...
Name: ManuscriptTitle, dtype: object
11911    Double perovskites overtaking the single perov...
12032    Electronic properties and degradation upon VUV...
Name: ManuscriptTitle, dtype: object
5587    Multiplescales analysis of photonic crystal wa...
5599    CoreSize Dependent Fluorescent Gold Nanocluste...
Name: ManuscriptTitle, dtype: object
15471    DNA Directed Self‐Assembly of Fluorescent Coll...
15472    Cover Picture DNA Directed Self‐Assembly of Fl...
15474    A Triethyleneglycol C60 Mono‐adduct Derivative...
15491    Impact of Ni IonDoping on Structural Optoelect...
Name: ManuscriptTitle, dtype: object
15727    Numerical analysis of invertedstructure perovs...
15734    The length controllable synthesis and nearinfr...
15748    Dielectric and nonohmic analysis of Sr2+ influ...
Name: ManuscriptTitle, dtype: object
16262      Upconversion emission of BaTiO3 Er nanocrystals
16269    Electronic structure thermoelectric mechanical...
Name: ManuscriptTitle, dtype: object
3573     Ligand Engineering for Mn2+ Doping Control in ...
3578     Unraveling the Role of Triiodides in Halide Pr...
16010    Feasibility study of thermal energy harvesting...
Name: ManuscriptTitle, dtype: object
5565    Distinct junction transformations of pixelarra...
5769    On the Interplay between CT and Singlet Excito...
Name: ManuscriptTitle, dtype: object
5977    Organic Solar Cells High‐Performance Tandem Or...
5988    Enhanced efficiency of hot‐cast large‐area pla...
Name: ManuscriptTitle, dtype: object
819     Imaging excited orbitals of quantum dots exper...
5558    Improved performance and reproducibility of pe...
Name: ManuscriptTitle, dtype: object
15499    Probing the Structural Electronic Mechanical S...
15513    Development of porous manganese oxide/polyanil...
Name: ManuscriptTitle, dtype: object
15468    Rapid growth of halide perovskite single cryst...
15514    Comparative Dielectric and Ferroelectric Chara...
Name: ManuscriptTitle, dtype: object
1249             Lasing in TwoDimensional Tin Perovskites
8780    Flexible photodetectors based on reticulated S...
Name: ManuscriptTitle, dtype: object
10335    Investigating charge generation in polymer non...
10401    Excitonic complexes in GaN/(Al Ga) N quantum dots
Name: ManuscriptTitle, dtype: object
10332    On the correlation between morphology and Ampl...
10381    Layerbylayer solutionprocess enables higher cr...
Name: ManuscriptTitle, dtype: object
9844    Highly luminescent violetand blueemitting stab...
9851    Sizetunable infrared (1000–1600 nm) electrolum...
Name: ManuscriptTitle, dtype: object
3061    Impact of the Hole Transport Layer on the Char...
3114    Superior magnetoresistance performance of hybr...
3131    Role of Hot Singlet Excited States in Charge G...
3139    2D–3D Mixed Organic–Inorganic Perovskite Layer...
3223    Tunable Conductance of MoS2 and WS2 Quantum Do...
Name: ManuscriptTitle, dtype: object
9215    Improving energy level alignment by adenine fo...
9220    Inorganic narrow bandgap CsPb0. 4Sn0. 6I2. 4Br...
Name: ManuscriptTitle, dtype: object
9210    Perovskite quantum dot solar cells mapping int...
9211    Highly uniform InGaAs/InP quantum well nanowir...
Name: ManuscriptTitle, dtype: object

8231    Carbazole linked phenylquinolinebased fulleren...
8233    Lowtemperature solutiondeposited metal chalcog...
Name: ManuscriptTitle, dtype: object
16724                         Perovskite Solar MiniModules
16725    Nanostructured porous silicon as functionalize...
Name: ManuscriptTitle, dtype: object
16717    Surface modification of 6xxx Series aluminum a...
16718    Mitigating CMAS Attack in Model YAlO3 Environm...
16719    Chemical Solution Deposition of LaSubstituted ...
16720    ITO/SiO2/ITO Structure on a Sapphire Substrate...
Name: ManuscriptTitle, dtype: object
7064    Strain propagation in layered twodimensional h...
7069    Polymermodified halide perovskite films for ef...
Name: ManuscriptTitle, dtype: object
4000    Solutionprocessed bismuth halide perovskite th...
4008    Amine‐free synthesis of cesium lead halide per...
Name: ManuscriptTitle, dtype: object
12977    Cucurbiturilmediated quantum dot aggregates fo...
12978    Colloidal atomic layer deposition growth of Pb...
Name: ManuscriptTitle, dtype: object
2302    PbS quantum dot electroabsorption modulation a...
2313    Measurement of the phase shift upon reflection...
Name: ManuscriptTitle, dtype: object
2191    Switchable Plasmonic Metasurfaces with High Ch...
2241    Longterm stability and optoelectronic performa...
Name: ManuscriptTitle, dtype: object
3763     Role of structural distortion in stabilizing e...
3779     Photogeneration and mobility of charge carrier...
13371    Carbon at the Ti site in strontium titanate fr...
Name: ManuscriptTitle, dtype: object
4308    Self‐Assembled Quasi‐3D Nanocomposite A Novel ...
4724    Engineering of CH3NH3PbI3 Perovskite Crystals ...
Name: ManuscriptTitle, dtype: object
14318    Robust stability halfmetallic ferrimagnetism a...
14332    Tuning magnetic properties of noncollinear mag...
Name: ManuscriptTitle, dtype: object
14366    Fully printable perovskite solar cells with hi...
14367    On the Relation between Chemical Composition a...
Name: ManuscriptTitle, dtype: object
1441           Graphene‐based microwave circuits a review
1444    AFM‐Based Hamaker Constant Determination with ...
1445    Toward efficient carbon nitride photoelectroch...
Name: ManuscriptTitle, dtype: object
1207    A photonic crystal laser from solution based o...
1279    Efficient infrared‐emitting PbS quantum dots g...
8765    Selftrapped exciton emission in an Sn (II)dope...
Name: ManuscriptTitle, dtype: object
1144    Xray Lithography on Perovskite Nanocrystals Fi...
8748    Surface band bending and carrier dynamics in c...
Name: ManuscriptTitle, dtype: object
11503    Optimization of electrochemically grown dense ...
11598    Polarization Resistance‐Free Mn3O4‐Based Elect...
Name: ManuscriptTitle, dtype: object
11565    Reverse micelle templating route to ordered mo...
11566    Colloidal Continuous Injection Synthesis of Fl...
11567    Effects of Oxygen Plasma on the Chemical Light...
11600    Probing the 3‐step Lithium Storage Mechanism i...
Name: ManuscriptTitle, dtype: object
10800    Acetonitrile based single step slotdie compati...
10802    The ultralow thermal conductivity and tunable ...
10803    Visiblelight photocatalytic activity of nitrog...
Name: ManuscriptTitle, dtype: object
3181    Siliconized triarylamines as redox mediator in...
3195    Detection of Au+ Ions During Fluorine GasAssis...
Name: ManuscriptTitle, dtype: object
9942    Influence of the InAs coverage on the phononas...
9946    Growth mechanisms and band bending in Cu and P...
Name: ManuscriptTitle, dtype: object
574     Solutionprocessed perovskite light emitting di...
4632        Piezoelectricity in two‐dimensional materials
Name: ManuscriptTitle, dtype: object
237    Programming the detection limits of biosensors...
290       Achromatic polarization control in the visible
Name: ManuscriptTitle, dtype: object
3265    ThicknessDependent Domain Relaxation Dynamics ...
3301    Controlling C60 Organization through DipoleInd...
Name: ManuscriptTitle, dtype: object
12266    Special Issue Section 2 Recent trends in C1C4 ...
12353    Effect of TiO2 antireflection layer with vario...
12418    Fullerene based electron transporting layers f...
Name: ManuscriptTitle, dtype: object
5951    MXene‐contacted silicon solar cells with 11.5%...
6034    Perovskite Solar Cells Stabilization of Precur...
Name: ManuscriptTitle, dtype: object
6373    Temperaturedependent excitonic decay and multi...
6374    Longlived charge separation at heterojunctions...
Name: ManuscriptTitle, dtype: object
2634    Colossal tuning of an energy gap in Sn2P2S6 un...
2737    Sidetoside alignment of gold nanorods with pol...
Name: ManuscriptTitle, dtype: object
9084    Organic lightemitting devices with silicon anodes
9111    Magnetic and transport characteristics of long...
Name: ManuscriptTitle, dtype: object
877    Correlating ChargeTransfer State Lifetimes wit...
880    Tailorable indirect to direct bandgap double p...
Name: ManuscriptTitle, dtype: object
577    Suppressing phase disproportionation in quasi2...
580    Bond engineering of molecular ferroelectrics r...
Name: ManuscriptTitle, dtype: object
12695    Surface mobility and reactivity of oxygen spec...
12701    Effects of dispersion and partial reduction on...
Name: ManuscriptTitle, dtype: object
4921    Dynamically controlled growth of Cu–Mo–O nanos...
4922    Correction Chlorinedoped SnO 2 hydrophobic sur...
Name: ManuscriptTitle, dtype: object
10119    Polymer Quantum DotSensitized Solar Cell Incor...
10121    Fabrication of ThreeDimensional SingleWalled C...
Name: ManuscriptTitle, dtype: object
8586    > 85% indium reduction for highefficiency sili...
8619    Investigation of high contrast and reversible ...
Name: ManuscriptTitle, dtype: object
12860    A high temperature neutron diffraction study o...
12877    Phase transitions in the hexagonal tungsten br...
Name: ManuscriptTitle, dtype: object
12855    An investigation of the optical properties and...
12899                    IN SITU REDUCTION OF (100) SRTIO3
Name: ManuscriptTitle, dtype: object
3640     Charge Transfer Absorption and Emission at ZnO...
13465    γ‐Valerolactone A Nontoxic Green Solvent for H...
Name: ManuscriptTitle, dtype: object
2227    Ultrafast imaging of carrier cooling in metal ...
2231     Mixedhalide perovskites with stabilized bandgaps
Name: ManuscriptTitle, dtype: object
2906     Unraveling the elastic properties of (quasi) t...
13588    Transition Metal Complexes Coupled to Vacancie...
Name: ManuscriptTitle, dtype: object
8854    Hole injection in triarylamine containing poly...
8921    Carrier recombination losses in inverted polym...
Name: ManuscriptTitle, dtype: object
12152    LongLived Mobile Charge Carriers Formed on Pho...
12187    Nonthermal plasma synthesis of metal sulfide n...
Name: ManuscriptTitle, dtype: object
15542    Potentialassisted assembly of functionalised p...
15543    Reversible binding of molecular dioxygen to Co...
Name: ManuscriptTitle, dtype: object
12166    Aggregationinduced dual emission and unusual l...
12170    Liquid crystalline polyfluorenes for blue pola...
Name: ManuscriptTitle, dtype: object
2913     Extrinsic effects on the optical properties of...
13589    Ab initio and experimental studies of the larg...
Name: ManuscriptTitle, dtype: object
6050    The impact of local work function variations o...
6051    Unraveling the Microstructure of Molecularly D...
Name: ManuscriptTitle, dtype: object
9982    Aluminum oxide as a dualfunctional modifier of...
9988    Coking suppression in solid oxide fuel cells o...
Name: ManuscriptTitle, dtype: object
9983    Lithium and lanthanum promoted NiAl2O3 as an a...
9987    Cogeneration of electricity and syngas on prot...
Name: ManuscriptTitle, dtype: object
12133    Rigidrodlike main chain polymers with rigidly ...
12140    Enhanced electrical conductivity of molecularl...
Name: ManuscriptTitle, dtype: object
8458    Ethylene glycol as a new sustainable fuel for ...
8550    Freestanding colored polymer film with composi...
Name: ManuscriptTitle, dtype: object
8472    Grain size dependence of degradation of alumin...
8475    A regioregular head to tail thiophene based “d...
Name: ManuscriptTitle, dtype: object
9288    Large scale ultravioletbased nanoimprint litho...
9289    Precision material modification and patterning...
9321    Thirdorder optical nonlinearity and figure of ...
9323    Structural and electrical conductivity studies...
9327    Textured BaTiO3 by templated grain growth and ...
Name: ManuscriptTitle, dtype: object
9297    Impact of supercritical  drying on roughness o...
9318    Spectroscopic ellipsometry study of FAxMA1−xPb...
9340    Strain engineering of piezoelectric properties...
9341    Silk fibroin protein as dual mode picric acid ...
9342    Towards highperformance hybrid hydrophilic mem...
9343    Solution‐Processed In2O3/ZnO Heterojunction El...
Name: ManuscriptTitle, dtype: object
12748    Role of copper content and calcination tempera...
12749     Optimized CuO–CeO2 catalysts for COPROX reaction
Name: ManuscriptTitle, dtype: object
7213    Raman scattering in strongly coupled organic s...
7216    Imaging the polariton relaxation bottleneck in...
Name: ManuscriptTitle, dtype: object
9762    Bandwidth limits of luminescent solar concentr...
9764    Ultrafast and broadband photodetectors based o...
Name: ManuscriptTitle, dtype: object
14908    Illuminated outdoor luminescence imaging of ph...
14909                   Prospects for perovskites in space
Name: ManuscriptTitle, dtype: object
11193    Solventfree solidstate synthesis of high yield...
11198    Shaping Tin Nanocomposites through Transient L...
11199    Multilayered Barium and Strontium Carbonate St...
Name: ManuscriptTitle, dtype: object
280      Tunable roomtemperature singlephoton emission ...
13568    Structural Diversity in Layered Hybrid Perovsk...
Name: ManuscriptTitle, dtype: object
1041    Noninjection gramscale synthesis of monodisper...
1049    DefectInduced in Situ Atomic Doping in Transit...
Name: ManuscriptTitle, dtype: object
9979    A NiFeCu alloy anode catalyst for directmethan...
9984    A comprehensive evaluation of a Ni–Al2O3 catal...
Name: ManuscriptTitle, dtype: object
9304    Formation and removal of composite halogenated...
9309    Modulationdoped ZnSe/(Zn Cd Mn) Se quantum wel...
Name: ManuscriptTitle, dtype: object
3530    Robotaccelerated perovskite investigation and ...
3610    Flexible Composite Energy Harvesters from Ferr...
Name: ManuscriptTitle, dtype: object
2663    Tuning the interfacial charge orbital and spin...
2665              Stable halfmetallic monolayers of FeCl2
Name: ManuscriptTitle, dtype: object
17007    Synthesis and Characterization of Poly Vinyl A...
17016    Theoretical and experimental studies on microc...
Name: ManuscriptTitle, dtype: object
1238    Extrinsic and dynamic edge states of twodimens...
8772    A molecular approach to an electrocatalytic hy...
Name: ManuscriptTitle, dtype: object
5476    Direct electrochemistry and nitric oxide inter...
5477    Factors that affect protein adsorption on nano...
Name: ManuscriptTitle, dtype: object
14139    Hydroxyapatite ceramics prepared from two natu...
14165    Cu (II) ions removal from water by charcoal ob...
Name: ManuscriptTitle, dtype: object
14154    Role of precursors on photocatalytic behavior ...
14156    High quantum yield CdSe/ZnS/CdS/ZnS multishell...
Name: ManuscriptTitle, dtype: object
16186    Tailoring the magnetic hyperthermia performanc...
16198    Colossal dielectric response and relaxation pr...
16399    Comparison of Semiconducting and Metallic Carb...
Name: ManuscriptTitle, dtype: object
2540    STRUCTURAL MECHANICAL THERMODYNAMIC AND OPTICA...
2556    Domain wall pinning contribution to the nonlin...
Name: ManuscriptTitle, dtype: object
7711    Optimizing solidstate ligand exchange for coll...
7725    Impact of perovskite/silicon tandem module des...
Name: ManuscriptTitle, dtype: object
10215    62‐9 Invited Paper Hybrid Composite Films with...
10217    P‐4.2 Reducing Chromaticity Shifts of Light Em...
Name: ManuscriptTitle, dtype: object
8542     Phonon lifetimes in model quantum dot superlat...
13530    Group 12 Metal Complexes of an 18Membered N2O2...
Name: ManuscriptTitle, dtype: object
5494    Tungsten work function engineering for dual me...
5633    The impact of grain alignment of the electron ...
Name: ManuscriptTitle, dtype: object
5550    Dielectric properties of bismuth niobate films...
5732    An Air Knife–Assisted Recrystallization Method...
Name: ManuscriptTitle, dtype: object
17114    Development of poly (urethaneester) amide from...
17121    Application of multidimensional (0D 1D 2D) nan...
Name: ManuscriptTitle, dtype: object
1356    Evidence for physisorption of aluminum on the ...
1534    Shelf‐Stable Quantum‐Dot Light‐Emitting Diodes...
Name: ManuscriptTitle, dtype: object
8215    Surface modification via selfassembling large ...
8226    Roadmap and roadblocks for the band gap tunabi...
Name: ManuscriptTitle, dtype: object
16563    Optimization of the Processing of 8‐YSZ Powder...
16629    Electronbeaminduced cracking in organicinorgan...
Name: ManuscriptTitle, dtype: object
9078    Theoretical calculation of the vibrational and...
9081    Direct optical transitions at K and Hpoint of ...
Name: ManuscriptTitle, dtype: object
9059    Experimental and firstprinciples investigation...
9072    Scanning microwave microscopy and scanning cap...
Name: ManuscriptTitle, dtype: object
9109    Strain effects on magnetic characteristics of ...
9116    Symmetry dependent optoelectronic properties o...
Name: ManuscriptTitle, dtype: object
713    Mechanism of charge migration through DNA mole...
714    Effect of structural dynamics on charge transf...
Name: ManuscriptTitle, dtype: object
8394    Doubly stabilized perovskite nanocrystal lumin...
8405    Water An Influential Agent for Lanthanide‐Dope...
Name: ManuscriptTitle, dtype: object
8947    Leadfree hightemperature dielectrics with wide...
8959    Crystal structure and domain‐wall contribution...
Name: ManuscriptTitle, dtype: object
16182    Structural magnetic and magnetocaloric propert...
16183    Magnetocaloric properties of (La1− xPrx) 0.85 ...
Name: ManuscriptTitle, dtype: object
14785    Sulfurization studies of the potential thin fi...
14792    Solution deposition of amorphous IZO films by ...
Name: ManuscriptTitle, dtype: object
7858    Doubling Exponent Models for the Analysis of P...
7974         Organic laser based on thiophene derivatives
Name: ManuscriptTitle, dtype: object
11732    Charge transfer and magnetotransport propertie...
11735    Lanthanum influence on the structure dielectri...
11811    Synthesis and structural characterization of t...
11818    Magnetic behaviour of praseodymium substituted...
11821    Waspwaisted like magnetic behavior of nanocrys...
11833    Planar versus bulk heterojunction perovskite m...
Name: ManuscriptTitle, dtype: object
11773    Optical properties of GST nanoparticles fabric...
11779    Comparative Study On The Impact Of TiN And Mo ...
Name: ManuscriptTitle, dtype: object
12324    Exciton dynamics in an energy upconverting sol...
12330    Excited state dynamics of PPI dendrimers funct...
Name: ManuscriptTitle, dtype: object
1237    Observation of strong valley magnetic response...
1239    Extraordinarily Stable Aqueous Electrochromic ...
Name: ManuscriptTitle, dtype: object
3520     GreenEmitting Powders of ZeroDimensional Cs4Pb...
13173    Atomistic simulation of SiAu melt crystallizat...
Name: ManuscriptTitle, dtype: object
12950    Standardized microbial fuel cell anodes of sil...
12956    Novel amphiphilic corannulene additive for moi...
Name: ManuscriptTitle, dtype: object
976      Prismatic deflection of live tumor cells and c...
15124    Magnetic Anisotropy in “Scorpionate” First‐Row...
Name: ManuscriptTitle, dtype: object
1494    Conjugated polymer mesocrystals with structura...
1496    Solar Cells Spin‐Cast Bulk Heterojunction Sola...
Name: ManuscriptTitle, dtype: object
8541    Hot carrier solar cell absorber prerequisites ...
8543    Hot carrier dynamics in HfN and ZrN measured b...
Name: ManuscriptTitle, dtype: object
14613    Proton conductivity in mixed Bsite doped perov...
14620    Graphene transfer methods for the fabrication ...
14625    Improved understanding of metal–graphene contacts
Name: ManuscriptTitle, dtype: object
1529    Efficient nonfullerene organic solar cells wit...
1532    High‐Efficiency Flexible Solar Cells Based on ...
Name: ManuscriptTitle, dtype: object
194    Breaking of macroscopic centric symmetry in pa...
349    Eliminating the need for anodic gas separation...
Name: ManuscriptTitle, dtype: object
3770    Monitoring Charge Carrier Diffusion across a P...
3821    Free carrier generation and recombination in p...
Name: ManuscriptTitle, dtype: object
14403    Singlestrand DNAnanorod conjugates–tunable ani...
14404    Barium titanate perovskite nanoparticles as a ...
Name: ManuscriptTitle, dtype: object
9506    CMOS integration of epitaxial GdO highk gate d...
9539    Allinorganic nonperovskite copper halides for ...
Name: ManuscriptTitle, dtype: object
7708    Structural origins of lightinduced phase segre...
7709    Colloidal synthesis and charge carrier dynamic...
Name: ManuscriptTitle, dtype: object
3370    Controlled synthesis and optical properties of...
3410    Improved Photovoltaic Efficiency and Amplified...
Name: ManuscriptTitle, dtype: object
8599    Laser fabrication of crystalline silicon nanor...
8678    Charge separation in Ptdecorated CdSe@ CdS oct...
Name: ManuscriptTitle, dtype: object
89     Engineering spinorbit synthetic Hamiltonians i...
124       Observation of roomtemperature polar skyrmions
125    Spatially resolved steadystate negative capaci...
Name: ManuscriptTitle, dtype: object
5882    Effect of Co‐Solvents on the Crystallization a...
5986    Staging Unraveling the Potassium Storage Mecha...
Name: ManuscriptTitle, dtype: object
13932    Rodshaped thiocyanateinduced abnormal band gap...
13933    Synthesis and transformation of zerodimensiona...
Name: ManuscriptTitle, dtype: object
9757    Microlightemitting diodes with quantum dots in...
9760    Broadband perovskite quantum dot spectrometer ...
9761    There is plenty of room at the top generation ...
9770    Waterinduced MAPbBr3@PbBr(OH) with enhanced lu...
Name: ManuscriptTitle, dtype: object
184     Reducing the efficiency–stability–cost gap of ...
1111    Fast neutron imaging with semiconductor nanocr...
Name: ManuscriptTitle, dtype: object
1086    Tunable Multipolar Surface Plasmons in 2D Ti3C...
8731    Facile synthesis of stable water soluble dendr...
Name: ManuscriptTitle, dtype: object
3630    Biexciton resonances reveal exciton localizati...
3631    Electrooptic response in germanium halide pero...
Name: ManuscriptTitle, dtype: object
3550    Improved Photovoltaic Efficiency and Amplified...
3553    Direct Band Gap MixedValence Organic–inorganic...
3555    Design of LeadFree Antiferroelectric (1 – x)Na...
Name: ManuscriptTitle, dtype: object
2833     Strainpromoted perpendicular magnetic anisotro...
13585    Treatment of the multimode Jahn–Teller problem...
Name: ManuscriptTitle, dtype: object
12097    Sequential polymer precipitation of core–shell...
12099    Toward the realization of a practical diketopy...
12130    Relaxation of polar order in poled polymer sys...
12131    Surface structure of semicrystalline naphthale...
Name: ManuscriptTitle, dtype: object
4963    Enhanced emission efficiency in doped CsPbBr 3...
5060    Structure–property trends in a hollandite mult...
Name: ManuscriptTitle, dtype: object
16213    Powder injection moulding of premixed ferritic...
16247    Spectroscopic properties of cerium in glasses ...
Name: ManuscriptTitle, dtype: object
8617    Investigation of high contrast and reversible ...
8668    Radiofrequencytransmitting hexagonal boron nit...
Name: ManuscriptTitle, dtype: object

1106    Largearea ordered superlattices from magnetic ...
1290    Effect of solvent environment on colloidal‐qua...
8738    Deep eutectic solventbased manganese molybdate...
Name: ManuscriptTitle, dtype: object
3289    Competing dissolution pathways and ligand pass...
3422    Thermochromic perovskite inks for reversible s...
Name: ManuscriptTitle, dtype: object
244                                      A sensitive pair
8809    Realizing a Highly Luminescent Perovskite Thin...
Name: ManuscriptTitle, dtype: object
207    Localized surface plasmon resonances arising f...
291    Experimental observation of the optical spin–o...
Name: ManuscriptTitle, dtype: object
6465    DualFunctional Optoelectronic and Magnetic Pyr...
6466    Longlived hot carriers in formamidinium lead i...
6467    Temperaturedependent optical properties of PbS...
Name: ManuscriptTitle, dtype: object
13942    Morphological Characterisation of Bacterial Ce...
13945    Exploring graphene quantum dots/TiO2 interface...
Name: ManuscriptTitle, dtype: object
5270     Lead halide perovskite nanocrystals in the res...
5277     Colloidal CsPbX3 (X = Cl Br I) Nanocrystals 2....
12803    Surface mobility of oxygen species on mixedoxi...
Name: ManuscriptTitle, dtype: object
1170    FourStates Multiferroic Memory Embodied Using ...
8756    Phase angle encoded upconversion luminescent n...
Name: ManuscriptTitle, dtype: object
9880    Ion bombardmentinduced enhancement of the prop...
9881    Interface engineering during plasmaenhanced ch...
Name: ManuscriptTitle, dtype: object
3356    Amorphous TiO2 Buffer Layer Boosts Efficiency ...
3402    PercolationLimited Ionic Diffusion in Li0.5xNa...
Name: ManuscriptTitle, dtype: object
3507     Microfluidic reactors provide preparative and ...
12634    Remarkable enhancement of the selective cataly...
Name: ManuscriptTitle, dtype: object
11528    Crossover from exciton to biexciton cavity pol...
11534         Polaronic exciton in a parabolic quantum dot
Name: ManuscriptTitle, dtype: object
12829    Tuning metal–carboxylate coordination in cryst...
12836    Microstructural changes in the reduction of Pr...
Name: ManuscriptTitle, dtype: object
10001    Fabrication BaZrO3/PBIbased nanocomposite as a...
10003    The effect of ethyleneamine ligands enhancing ...
Name: ManuscriptTitle, dtype: object
14752    New diagnostic method for monitoring plasma re...
14760    A combined optical and magneto‐optical measure...
Name: ManuscriptTitle, dtype: object
3502     The Future Is Blue (LEDs) Why Chemistry Is the...
12632    Preferential CO oxidation over nanosized gold ...
Name: ManuscriptTitle, dtype: object
519     The controlled disassembly of mesostructured p...
4857    A visible to nearinfrared nanocrystalline orga...
Name: ManuscriptTitle, dtype: object
15696    Discotic Liquid Crystals with Graphene Supramo...
15697    IIIIVI chalcogenide semiconductor nanocrystals...
Name: ManuscriptTitle, dtype: object
14781    Structure optimization for a high efficiency C...
14783    Challenges in deposition of wide band gap copp...
Name: ManuscriptTitle, dtype: object
254    Imaging the motion of electrons across semicon...
292    Experimental observation of the optical spinor...
Name: ManuscriptTitle, dtype: object
6075    Impact of bimolecular recombination on the fil...
6087    Access to ultrafast surface and interface carr...
6149    Molecular electronic coupling controls charge ...
6180    Luminescence of Nanostructured Eu3+/ZnO Mixed ...
6181    Effects of oxide nanoparticle size and shape o...
Name: ManuscriptTitle, dtype: object
8490    Temperature dependence of opencircuit voltage ...
9701    Charge dissipation in ebeam lithography with N...
Name: ManuscriptTitle, dtype: object
5533    Enhancement of magnetic entropy change in La0....
5844    Revealing morphology evolution in highly effic...
Name: ManuscriptTitle, dtype: object
6721    Magnetic nanoparticle composites synergistic e...
6728    Proton Electrokinetics Electrokinetic Proton T...
Name: ManuscriptTitle, dtype: object
6716    Critical Role of Organic Spacers for Bright 2D...
6757    A fullyintegrated and automated testing device...
Name: ManuscriptTitle, dtype: object
6487    Role of ZnS segment on charge carrier dynamics...
6493    Ultralow Thermal Conductivity and Ultrahigh Th...
Name: ManuscriptTitle, dtype: object
15583    Galvanostatic synthesis of MnCo2O4 nanoflakes ...
15593    High temperature Raman spectroscopy studies of...
Name: ManuscriptTitle, dtype: object
9674    Inchsized aligned polymer nanofiber films with...
9675    A ZnO nanowire array film with stable highly w...
Name: ManuscriptTitle, dtype: object
6109    Properties of contact and bulk impedances in h...
6115    Photosensitization of TiO2 Layers with CdSe Qu...
Name: ManuscriptTitle, dtype: object
16223    Fluctuations and depinning of stripes at acous...
16225    Observation of the transition to the spinglass...
16401    Flexible Organic Photovoltaics with Colorful S...
16403    Tibased MXenes for Energy Storage Application ...
Name: ManuscriptTitle, dtype: object
9052     Interfacial ferromagnetism and atomic structur...
11384    Origin of Performance Enhancement in TiO2‐Carb...
Name: ManuscriptTitle, dtype: object
15741    Solvent free solidstate synthesis of Pr6O11/gC...
15746    Photosensitive antimony triiodide thin films b...
Name: ManuscriptTitle, dtype: object
15721    Lowenergy electroninduced chemistry of condens...
15726    Enhancing silicon solar cells with singlet fis...
15747    Photoluminescence properties of cerium oxide n...
Name: ManuscriptTitle, dtype: object
13061    Wastefree scale up synthesis of nanocrystallin...
13067    Role of alkyl chain length in diaminoalkane li...
13070    Aniondependent coordinative networking of macr...
13071    Networking of macrocycles 1D and 2D coordinati...
13072    Guesttriggered assembly of zinc (II) supramole...
Name: ManuscriptTitle, dtype: object
13060    Oxygen and Hydrogen Surface Mobility in Suppor...
13073    Cationdirected assembly of polyrotaxane and po...
Name: ManuscriptTitle, dtype: object
11867    Fine Structural Details Matter A Lesson from S...
11869              RuddlesdenPopper Perovskite Solar Cells
Name: ManuscriptTitle, dtype: object
11876    Xray standing waves reveal lack of OH terminat...
11883     perovskites Theoretical and experimental inve...
Name: ManuscriptTitle, dtype: object
6155    Synthesis of type II CdTeCdSe nanocrystal hete...
6160    Doublelayer structured WPLEDs based on three p...
Name: ManuscriptTitle, dtype: object
6074    Incorporating fluorine substitution into conju...
6089    Imaging the reduction of electron trap states ...
Name: ManuscriptTitle, dtype: object
6749     Silicon source of frequencybin entangled photons
6751    Ultraviolet C lasing at 263 nm from Ba2LaF7Yb3...
Name: ManuscriptTitle, dtype: object
6691    Toward Strong Near‐Infrared Absorption/Emissio...
6692    Pure 2D Perovskite Formation by Interfacial En...
Name: ManuscriptTitle, dtype: object
12930    Porphyrinic supramolecular daisy chains incorp...
12931    Trapping shapecontrolled nanoparticle nucleati...
Name: ManuscriptTitle, dtype: object
6068    Charge separation in PCPDTBT PCBM blends from ...
6086    Rotationally Free and Rigid Sublattices of the...
Name: ManuscriptTitle, dtype: object
382    Strong coupling between chlorosomes of photosy...
384    Single crystal hybrid perovskite fieldeffect t...
Name: ManuscriptTitle, dtype: object
14971    Collision of a long DNA molecule with an isola...
15004    Perovskite Semiconductors and Fundamental Mech...
Name: ManuscriptTitle, dtype: object
715    Supramolecular control of charge transport in ...
716    Understanding structure− mobility relations fo...
728    Ligand Locking on Quantum Dot Surfaces via a M...
Name: ManuscriptTitle, dtype: object
13845    Influence of halide choice on formation of low...
13865    Deep blue light amplification from a novel tri...
Name: ManuscriptTitle, dtype: object
11283    Impact of surface defects in electron beam eva...
11284    Work function investigations of Aldoped ZnO fo...
Name: ManuscriptTitle, dtype: object
12422    Enhanced performance in inverted organic light...
12424    The refractive index grating formation in azo ...
Name: ManuscriptTitle, dtype: object
11517    Thermoelectric power of sulphur at high pressu...
11518    Influence of P–T pre‐treatment on thermopower ...
Name: ManuscriptTitle, dtype: object
13656    Using lead chalcogenide nanocrystals as spin m...
13658    Magnetic order in a novel 3D oxalatebased coor...
Name: ManuscriptTitle, dtype: object
9546    Structure and internal dynamics of a side chai...
9561          Siesta Recent developments and applications
Name: ManuscriptTitle, dtype: object
13673    Probing magnetic interactions in metal–organic...
13674    Ir (III) complexes designed for lightemitting ...
Name: ManuscriptTitle, dtype: object
4427                Transforming energy using quantum dots
13672    Colloidal assemblies of oriented maghemite nan...
Name: ManuscriptTitle, dtype: object
10116    Vibrational spectrocopic studies of organic mo...
10160    Epitaxial growth and enhanced conductivity of ...
Name: ManuscriptTitle, dtype: object
667    Growth of Oriented SingleCrystalline Rutile Ti...
708    Asymmetric Interfacet Adatom Migration as a Mo...
Name: ManuscriptTitle, dtype: object
1708    Fast‐Response Highly Air‐Stable and Water‐Resi...
7545    Theoretical study of crossed and parallel carb...
Name: ManuscriptTitle, dtype: object
8880    Insulator–metal transition and magnetoresistan...
8881    Prediction of giant magnetoelectric effect in ...
Name: ManuscriptTitle, dtype: object
9870    Investigation of photophysical morphological a...
9876    Improved fill factors in solutionprocessed ZnO...
Name: ManuscriptTitle, dtype: object
15570    P/i interfacial engineering in semitransparent...
15573    Resistive switching functional quantumdot ligh...
Name: ManuscriptTitle, dtype: object
827      Geminate charge recombination in polymer/fulle...
15294    Semitransparent perovskite solar cells for sma...
Name: ManuscriptTitle, dtype: object

4738     Thousand‐fold Conductivity Increase in 2D Pero...
14915    Fundamentals of threeterminal tandem solar cel...
Name: ManuscriptTitle, dtype: object
15539    Practical electricity generation from a paper ...
15547    Performance optimization of PGM and PGMfree ca...
15555    A threedimensional model of CdZnTe gammaray de...
15559    Interpretation of AC conductivity of lightly d...
15562    Investigation of interface properties in oxide...
15563    Interfacial engineering for highly efficient o...
15565    Silicon nanoparticle sizedependent open circui...
Name: ManuscriptTitle, dtype: object
15549    The effect of indium doping on photovoltaic pr...
15566    2 5di (thiophen2yl) thiazolo [5 4d] thiazoleba...
Name: ManuscriptTitle, dtype: object
14906    Highly Efficient PerovskiteonSilicon Tandem So...
14907    Economically sustainable growth of smallscale ...
Name: ManuscriptTitle, dtype: object
14900    Series Interconnection of Monolithic 2Terminal...
14902    Blade coating of diketopyrrolopyrrole based or...
Name: ManuscriptTitle, dtype: object
3039    Highly Efficient Perovskite Solar Cells Based ...
3179    Revealing the Anisotropic Structural and Elect...
Name: ManuscriptTitle, dtype: object
916    The architecture of colloidal quantum dot sola...
920    Oriented Halide Perovskite Nanostructures and ...
Name: ManuscriptTitle, dtype: object
10129    Flexible encapsulation materials based on sili...
10139    The atomiclevel structure of bandgap engineere...
10169    Influence of hidden halogen mobility on local ...
Name: ManuscriptTitle, dtype: object
4474    Interfacial benzenethiol modification facilita...
6967    LowTemperature Phase Transformations of  in th...
Name: ManuscriptTitle, dtype: object
15627    Tandem Nenitzescu reaction/nucleophilic aromat...
15629    Transformations of 5Hydroxy1pyrrolines in Stro...
15636    Analysis of AC permittivity response measured ...
Name: ManuscriptTitle, dtype: object
15633    Complex plane analysis of pn junction forwardv...
15634    The role of instrumentation in the process of ...
Name: ManuscriptTitle, dtype: object
15253    Phase field simulations of ferroelastic toughe...
15260    Magnetic influence on thermoelectric propertie...
Name: ManuscriptTitle, dtype: object
15256    Hightemperature stability structure and thermo...
15268    Dynamic control of ferroionic states in ferroe...
Name: ManuscriptTitle, dtype: object
10567    The impact of Au doping on the charge carrier ...
10606    Photoinduced unidirectional electron transfer ...
10609    Fast transient absorption spectroscopy of the ...
10610    Graphene quantum dots/Au hybrid nanoparticles ...
Name: ManuscriptTitle, dtype: object
10154    Surface radiomineralisation mediates chelatefr...
10155    Identification of dipole disorder in low tempe...
10161    Selfassembled molecular nanowires on prepatter...
Name: ManuscriptTitle, dtype: object
15588    Onestep methylammonium lead bromide films Effe...
15596    High temperature induced phase transitions in ...
Name: ManuscriptTitle, dtype: object
4077    Enhancing resistive switching performance and ...
4104    Recent Progress in Perovskite‐Based Reversible...
6436    Efficient and rapid photocatalytic reduction o...
Name: ManuscriptTitle, dtype: object
8556    Investigation of electronic transport mechanis...
8559    Accessing externally induced spatiallyresolved...
Name: ManuscriptTitle, dtype: object
4241    Charge Generation at Polymer/Metal Oxide Inter...
4267    In‐Situ Switching from Barrier‐Limited to Ohmi...
Name: ManuscriptTitle, dtype: object
1296    Pseudohalide‐exchanged quantum dot solids achi...
1298    A new approach to hybrid polymer–metal and pol...
Name: ManuscriptTitle, dtype: object
16453    Triphenylamino or 9phenyl carbazolylsubstitute...
16454    Molybdenum rods assembled with nanosheets a hi...
Name: ManuscriptTitle, dtype: object
10131    Effects of Hole and Electron Transporting Inte...
10133    Enhanced photocatalytic properties of nanostru...
10144    Tunable and highly efficient lightharvesting a...
10207    62‐8 Invited Paper High Color Gamut QDot™ LCD ...
Name: ManuscriptTitle, dtype: object
6688    Quantum dot passivation of halide perovskite f...
6761    Broadband solar absorption enhancement via per...
Name: ManuscriptTitle, dtype: object
13716    Nonfullerene acceptor fibrils enable efficient...
13726    Semicrystalline photovoltaic polymers with sil...
Name: ManuscriptTitle, dtype: object
6412    Photoinduced interactions in a pyrenecalix [4]...
6413    Zinc 5101520mesoTetraferrocenylporphyrin as an...
Name: ManuscriptTitle, dtype: object
7456    Combined LDA and LDA1/2 method to obtain defec...
7480    Structures of fluorinated graphene and their s...
Name: ManuscriptTitle, dtype: object
2772    The glasslike thermal conductivity in ZrO2Dy3T...
2777    Erratum “Twodimensional porous graphitic carbo...
Name: ManuscriptTitle, dtype: object
10987    Electronic and optical properties of twodimens...
10988    Twodimensional FeTe 2 and predicted Janus FeXS...
Name: ManuscriptTitle, dtype: object
9829    In Situ Methylammonium ChlorideAssisted Perovs...
9831    Underappreciated role of lowenergy facets in n...
Name: ManuscriptTitle, dtype: object
9670    A facile route to synthesize chalcopyrite CuIn...
9683    InxGa1− xAs nanowires with uniform composition...
Name: ManuscriptTitle, dtype: object
9663      Quantum confinement in few layer SnS nanosheets
9667    Boosting the performance of ZnO microrod metal...
Name: ManuscriptTitle, dtype: object
5297    Perovskite/colloidal quantum dot tandem solar ...
5301    Online meetings in times of global crisis Towa...
Name: ManuscriptTitle, dtype: object
4737    Fluorescence Blinking Beyond Nanoconfinement S...
4792    Time resolved fluorescence polarization anisot...
Name: ManuscriptTitle, dtype: object
15500    Improving the power conversion efficiency and ...
15501    Structural and Electrochemical Properties of K...
Name: ManuscriptTitle, dtype: object
6069    CsxFA1–xPb(I1–yBry)3 Perovskite Compositions t...
6088    Intriguing Ultrafast Charge Carrier Dynamics i...
Name: ManuscriptTitle, dtype: object
12676    Study of the oxygen diffusion on threeway cata...
12691    In Situ fourier transform infrared study of th...
Name: ManuscriptTitle, dtype: object
15099    Ultrasonically sprayed Cs3Bi2I9 thin film base...
15100    Effect of Nd3+ ions on structural spectral mag...
Name: ManuscriptTitle, dtype: object
1258                       Perovskites for light emission
6172    Electrodeposited mesoporous ZnO thin films as ...
Name: ManuscriptTitle, dtype: object
14144    Structural and magnetic behavior in nanocrysta...
14169    Epitaxial growth of ZnO nanowires on aand cpla...
14172    MOCVD growth of CdTe on glass analysis of in s...
14173    Influence of twinned structure on the morpholo...
14195    AgBi2I7 layers with controlled surface morphol...
14202    Preparation and characterization of Al and B c...
Name: ManuscriptTitle, dtype: object
10439    On the stability of Fröhlich bipolarons in sph...
10440    Path integral description of lowdimensional po...
Name: ManuscriptTitle, dtype: object
6150    Removing instabilitycaused lowfrequency featur...
6159    Synthesis and cathodoluminescence of morpholog...
Name: ManuscriptTitle, dtype: object
5253    Thermally Activated SecondOrder Recombination ...
5254    Comparing the calculated fermi level splitting...
Name: ManuscriptTitle, dtype: object
444    Efficient photosynthesis of carbon monoxide fr...
446    Spectral splitting photovoltaics using perovsk...
Name: ManuscriptTitle, dtype: object
14145    Structural and Raman studies of MnO2 and Mn2O3...
14151    Investigations on partially exfoliated graphit...
Name: ManuscriptTitle, dtype: object
14124    Structural aspects of the dehydration of αZr (...
14176    Epitaxial lateral overgrowth of Si on (1 0 0) ...
14181    Impurity effects in ZnO and nitrogendoped ZnO ...
14188    Sol–gel preparation and optical characterizati...
Name: ManuscriptTitle, dtype: object
14129    Morphological and dynamical evolution of lanth...
14132    Exploring the thermochemical heat storage capa...
Name: ManuscriptTitle, dtype: object
14167    Effect of sourcesubstrate distance on the tran...
14174    Numerical study of the growth conditions in an...
Name: ManuscriptTitle, dtype: object
15581    An electrochemical study of copper diffusion i...
15582    Novel nanocomposite membranes based on polyben...
15597    Xray diffraction and Raman spectroscopy studie...
Name: ManuscriptTitle, dtype: object
11152    Interrelation between substrate roughness and ...
11153    Synthesis and Characterization of Branched fcc...
Name: ManuscriptTitle, dtype: object
10545    Quantification of ion migration in CH 3 NH 3 P...
10552                        Dislocationtoughened ceramics
Name: ManuscriptTitle, dtype: object
2507    Molecular beam epitaxy of MnAs/ZnSe hybrid fer...
2617    Electrical characterization of the threshold f...
Name: ManuscriptTitle, dtype: object
6169    Role of aspect ratio in the photoluminescence ...
6177    Insights into the hole blocking layer effect o...
Name: ManuscriptTitle, dtype: object
16098    1D heterometallic oxalate compounds as precurs...
16121    Ab initio study of oxygen vacancy effects on e...
16130    Ab Initio study of the crystal structure and t...
16133    Spectral shifts upon halide segregation in per...
16143    Enhanced magnetooptical activity of multilayer...
Name: ManuscriptTitle, dtype: object
9523    Balancing crop production and energy harvestin...
9524    Perovskite Quantum Dots Exhibiting Strong Hole...
Name: ManuscriptTitle, dtype: object
11837    Rietveld refinement and electrical properties ...
11950    Exciton Recombination in Self‐Assembled InAs/G...
Name: ManuscriptTitle, dtype: object
6815    Unusual dimensionality effects and surface cha...
6816    Amplified spontaneous emission threshold reduc...
Name: ManuscriptTitle, dtype: object
10312    Optimising the efficiency of carbazole copolym...
10317    Solution deposited NiO thinfilms as hole trans...
10348    Highly efficient and foldable topemission orga...
10408    Structural stability of a golden semiconductin...
Name: ManuscriptTitle, dtype: object
10337    The doping effect of cesiumbased compounds on ...
10371    Critical light instability in CB/DIO processed...
Name: ManuscriptTitle, dtype: object
10313    Organic photovoltaic devices incorporating a m...
10397    The effect of morphology on the temperaturedep...
Name: ManuscriptTitle, dtype: object
936     ChargeCarrier Recombination in Halide Perovski...
5718    Quasi‐Continuous Wave Near‐Infrared Excitation...
Name: ManuscriptTitle, dtype: object
4121    Heterogeneous nucleation promotes carrier tran...
4149    One‐Step Polymeric Melt Encapsulation Method t...
Name: ManuscriptTitle, dtype: object
1140    Planar aperiodic arrays as metasurfaces for op...
8813    Photo‐cross‐linkable poly(p‐phenylene)s. Synth...
Name: ManuscriptTitle, dtype: object
9167    The expanding world of hybrid perovskites mate...
9168    Hybrid tandem solar cells with depletedheteroj...
Name: ManuscriptTitle, dtype: object
7728    Using Monovalentto TrivalentCation Hybrid Pero...
7729    Dithienogermolebased nonfullerene acceptors ro...
Name: ManuscriptTitle, dtype: object
528      Sub1.4 eV bandgap inorganic perovskite solar c...
13114    Efficient Emission Outcoupling from Perovskite...
Name: ManuscriptTitle, dtype: object
9964    Study of exciton hopping transport in PbS coll...
9965    Ultrastable allinorganic silver bismuth sulfid...
Name: ManuscriptTitle, dtype: object
3067    RealSpace Mapping of SurfaceOxygen Defect Stat...
3073    A Direct nButane Solid Oxide Fuel Cell Using B...
3093    Scalable PbS quantum dot solar cell production...
3096    On the colloidal stability of PbS quantum dots...
3116    Multifunctional silver nanoparticle interlayer...
3145    SolutionProcessed Red Green and Blue Quantum R...
Name: ManuscriptTitle, dtype: object
1004    Hotspotinduced transformation of surfaceenhanc...
1005    Nitrogendoped nanoporous carbon membranes with...
Name: ManuscriptTitle, dtype: object
2234    PolarizationDependent Purcell Enhancement on a...
2363    Piezoelectricity and electrostriction of dye‐d...
Name: ManuscriptTitle, dtype: object
16392    Synthesis and Physical Properties of Asymmetri...
16396    An Unusual PseudoCoordination Polymer of Dithi...
Name: ManuscriptTitle, dtype: object
3071    Promoting the Efficiency and Stability of CsPb...
3089    SelfAssembly of CsPbBr 3 Perovskites in Microp...
3121    Statistical Paradigm for Organic Optoelectroni...
3129    Antibacterial Melamine Foams Decorated with in...
3130    Efficient photoand electroluminescence by trap...
3138    Developing the nextgeneration perovskite/Si ta...
Name: ManuscriptTitle, dtype: object
17409    Employment of electrochemically synthesized TG...
17410    Adsorption and preconcentration of divalent me...
Name: ManuscriptTitle, dtype: object
14435    Scheelitetype rare earth vanadates TVO4 (T= Ho...
14448    Combat antimicrobial resistance emergence and ...
Name: ManuscriptTitle, dtype: object
8252    Temperature influence on morphological progres...
8281    Inorganic lead halide perovskite single crysta...
8282    Solution‐processed visible‐blind ultraviolet p...
Name: ManuscriptTitle, dtype: object
8189    Bulk Recrystallization for Efficient MixedCati...
8190    A low iontransfer resistance and high volumetr...
Name: ManuscriptTitle, dtype: object
12281    Photovoltaic polymers based on difluoroqinoxal...
12283    Highly efficient and stable blue‐light‐emittin...
Name: ManuscriptTitle, dtype: object
10108    CeO2–NiO Nanoflakes Assessment and Their Antic...
10111    Structural Magnetic Electrical and PhotoFenton...
10300    Allsolutionprocessed multilayer polymer/dendri...
Name: ManuscriptTitle, dtype: object
5802    Enhanced nucleation of atomic layer deposited ...
5803    Impact of Hole Transport Layer Surface Propert...
Name: ManuscriptTitle, dtype: object
8009    Synthesis of Cu 2 (Zn 1− x Co x) SnS 4 nanocry...
8036    In situ study of the film formation mechanism ...
Name: ManuscriptTitle, dtype: object
17406    A novel classification of prostate specific an...
17411    Improving data and prediction quality of hight...
Name: ManuscriptTitle, dtype: object
16486    Capacitive deionization and electrosorption fo...
16492    Use of LDHchromate adsorption coproduct as an ...
Name: ManuscriptTitle, dtype: object
11288    Titania nanoparticleloaded mesoporous silica s...
11290    Modified strain and elastic energy behavior of...
Name: ManuscriptTitle, dtype: object
5861    Efficiency exceeding 11% in tandem polymer sol...
5863    Highly Efficient and Stable Perovskite Solar C...
5864    Tin Halide Perovskite (ASnX3) Solar Cells A Co...
5865    The Role of Grain Boundaries on Ionic Defect M...
Name: ManuscriptTitle, dtype: object
6458    Infrared spectroscopic study of vibrational mo...
6461    Ionic Current Mn KEdge Xray Absorption Spectra...
Name: ManuscriptTitle, dtype: object
14628    Fabrication of monolithic bidirectional switch...
14629    Overlay accuracy limitations of soft stamp UV ...
Name: ManuscriptTitle, dtype: object
14633    Synthesis characterization and electrochemical...
14640    Sizedependent optical edge shifts and electric...
14641        Towards a roomtemperature polariton amplifier
Name: ManuscriptTitle, dtype: object
6504    Emission decay pathways sensitive to circular ...
6505    On the Molecular Origin of Photoluminescence o...
Name: ManuscriptTitle, dtype: object
14161    Crystalline Structure Study of Double Perovski...
14170    Heteroepitaxial growth of Cu2O thin film on Zn...
14191    Impact of grain boundary structures on trappin...
Name: ManuscriptTitle, dtype: object
14122    New proton conducting nanocomposite membranes ...
14125    Adams MA see AV Belushkin Adams MA see R. Hemp...
14152    ‘Kusha’(eragrostis cynosuroids) A source of ac...
14197         Sol–gel electrochromic WO3 coatings on glass
Name: ManuscriptTitle, dtype: object
14153    Structural morphological and electrical invest...
14157    Application of CdSe/ZnS/CdS/ZnS core–multishel...
14200    Timeresolved spectroscopy of Sm3+ in silica an...
14201    Study of refractive index and physical thickne...
Name: ManuscriptTitle, dtype: object
10303    Performance enhancement of diindenoperylenebas...
10304    Correlating photocurrent spectra and electrica...
Name: ManuscriptTitle, dtype: object
16976    Purified high‐sulfur coal as a fuel for direct...
16988    A comprehensive analysis on elastic mechanical...
17011    Photophysical electrochemical and electrochrom...
17020    SiO2@ Al2O3 coreshell nanoparticles based molt...
Name: ManuscriptTitle, dtype: object
10517    Synthesis crystal structure and properties of ...
17282    Rational use of ligand to shift the UV–vis spe...
Name: ManuscriptTitle, dtype: object
17331    Diagnosis of perovskite solar cells through ab...
17359    Anomalous thermal conductivity in amorphous ni...
Name: ManuscriptTitle, dtype: object
7565     Chemical control of holedoped superconductivit...
15640    Secondary electron microscopy dopant contrast ...
Name: ManuscriptTitle, dtype: object
6979    Quantum reflection from a solid surface at nor...
6998                     Chiral singlewall gold nanotubes
Name: ManuscriptTitle, dtype: object
3782    Absolute photoluminescence quantum yields of I...
3793    Sizedependent electron transfer from colloidal...
3795    Fully efficient direct YbtoEr energy transfer ...
Name: ManuscriptTitle, dtype: object
3791    Absorption Fsum rule for the exciton binding e...
3830    Exciton gating and triplet deshelving in singl...
Name: ManuscriptTitle, dtype: object
830    Synthesis and spectroscopy of silverdoped PbSe...
831    Stereoelectronic Effects on the Binding of Neu...
Name: ManuscriptTitle, dtype: object
10687    Oxide planar p–n heterojunction prepared by lo...
10698    Formamidiniumbased planar heterojunction perov...
Name: ManuscriptTitle, dtype: object
10118    Photocurrent Enhancement of CdSe QuantumDot Se...
10120    Improved Field Emission of ThreeDimensional Si...
Name: ManuscriptTitle, dtype: object
888     Formation of LongLived Color Centers for Broad...
5637    Fabry–Pérot Oscillation and Room Temperature L...
Name: ManuscriptTitle, dtype: object
10085    Synthesis of Sb2E3 (E= S Se) Nanorods with a F...
10086    Enhanced Photocurrent from Organic PolymersBas...
10286    Optical Modulation of Amplified Emission in a ...
Name: ManuscriptTitle, dtype: object
16771    A computational investigation on structural me...
16781    Structural Magnetic and Magnetocaloric Propert...
Name: ManuscriptTitle, dtype: object
16867    Cubic PbGeO3 perovskite oxide a compound with ...
16868    Putting DFT to the trial First principles pres...
Name: ManuscriptTitle, dtype: object
17344    Luminescent Copper (I) complexes as promising ...
17347    Colloidal Synthesis of ZnS CdS and Zn x Cd1−x ...
Name: ManuscriptTitle, dtype: object
2644    Lattice parameter and energy band gap of cubic...
2654    Ordenamento induzido por tensão na liga de InGaAs
Name: ManuscriptTitle, dtype: object
13198    Optical isolation via onedimensional magnetoph...
13204    MAPLEdeposited PFO films influence of the lase...
13208    Novel application of MgF2 as a back reflector ...
Name: ManuscriptTitle, dtype: object
13187    How well do implicit solvation models represen...
13202    Timeresolved fluorescence polarization anisotr...
13211    Hightemperature plastic deformation and acoust...
Name: ManuscriptTitle, dtype: object
5179    Defect tolerance in methylammonium lead triiod...
5180    Influence of Electrode Interfaces on the Stabi...
Name: ManuscriptTitle, dtype: object
11190    Semicoordination bond breaking and halogen bon...
11192    Synthesis of ultrathin perovskite nanowires vi...
Name: ManuscriptTitle, dtype: object

2704    Increased efficiency in pnjunction PbS QD sola...
2750    Surface effects of electrodedependent switchin...
Name: ManuscriptTitle, dtype: object
8428    Deterministic and Scalable Generation of Excit...
8443    Enhanced upconversion via plasmonic nearfield ...
Name: ManuscriptTitle, dtype: object
8342    Water‐Induced and Wavelength‐Dependent Light A...
8368    Simultaneously Enhancing Color Spatial Uniform...
Name: ManuscriptTitle, dtype: object
7050    Lowenergy roomtemperature optical switching in...
7059    Momentummatching and bandalignment van der Waa...
Name: ManuscriptTitle, dtype: object
3629    Multiple SelfTrapped Emissions in the LeadFree...
3632    Dimensional mixing increases the efficiency of...
Name: ManuscriptTitle, dtype: object
16579    Temperaturedependent cyclic response and micro...
16583    Humidity Related Low Temperature Conductivity ...
Name: ManuscriptTitle, dtype: object
8060    Engineering the morphology via processing addi...
8062    Greensolvent processable semiconducting polyme...
Name: ManuscriptTitle, dtype: object
7991    Bandaligned C 3 N 4− x S 3x/2 stabilizes CdS/C...
7998    Selenophene vs. thiophene in benzothiadiazoleb...
8034    Ambient blade coating of mixed cation mixed ha...
8091    Synthesis crystal structure and properties of ...
8115    Twostep growth of CsPbI 3− X Br X films employ...
Name: ManuscriptTitle, dtype: object
8069    The introduction of a perovskite seed layer fo...
8110    Metal oxide alternatives for efficient electro...
Name: ManuscriptTitle, dtype: object
8090    Interplay between humidity temperature and ele...
8092    Facile synthesis of a hole transporting materi...
8174    Fundamental physics behind highefficiency orga...
Name: ManuscriptTitle, dtype: object
8016    Influence of the substrate on the bulk propert...
8031    Efficient inverted bulkheterojunction solar ce...
Name: ManuscriptTitle, dtype: object
8163    Lowtemperature growth of polyethylene glycoldo...
8172    Preserving the stoichiometry of triplecation p...
Name: ManuscriptTitle, dtype: object
7486    Mechanical properties of monolayer GaS and GaS...
7498    Tuning the magnetic anisotropy in singlelayer ...
Name: ManuscriptTitle, dtype: object
14031    Fluorescence relaxation kinetics of poly (meth...
14051    Fast oxygen mobility in tetragonal YBa2Cu3O7x ...
Name: ManuscriptTitle, dtype: object
14380    Spectroscopic and electrochemical study of hyb...
14410    Graphene induced structure and doping level tu...
Name: ManuscriptTitle, dtype: object
17180    Device design of doping‐controlled homojunctio...
17181    Electrocatalytic Reduction of Carbon Dioxide t...
Name: ManuscriptTitle, dtype: object
16871    An Investigation on Drilling of Epoxy Composit...
16876    Engineering the Switching Behavior of Nanomagn...
16878    Exposed Surface and Confinement Effects on the...
16882    Structure and Magnetism of IronSubstituted Nic...
16894    Ab initio calculations of the elastic vibratio...
Name: ManuscriptTitle, dtype: object
11502    Electronic structure and optical properties of...
11508    Excitation relaxation in copper selenide nanow...
11511    Thermoelectric properties and phase transition...
Name: ManuscriptTitle, dtype: object
5005    N N′Dihydrotetraazapentacenes (DHTA) in thin f...
5049    Ultrafast lightinduced symmetry changes in sin...
Name: ManuscriptTitle, dtype: object
4990    Flexible electroluminescent fiber fabricated f...
5048    Additive engineering to improve the efficiency...
Name: ManuscriptTitle, dtype: object
4995    Optical absorption by design in a ferroelectri...
5022    Exploring high temperature templating in nonpl...
Name: ManuscriptTitle, dtype: object
4966     Effects of ambient exposure on photoluminescen...
16961    Synthesis characterization and use of highly s...
Name: ManuscriptTitle, dtype: object
4958    Polarization anisotropy losses due to morpholo...
4977    Pulsedcurrent versus constantvoltage lightemit...
Name: ManuscriptTitle, dtype: object
4976    Host–guest blue lightemitting electrochemical ...
4978    Large area perovskite lightemitting diodes by ...
Name: ManuscriptTitle, dtype: object
4941    Evolution of CsPbBr 3 nanocrystals upon postsy...
4984    Selective excitation of Eu 3+ in the core of s...
4986    The competition between mechanical stability a...
5013    Solutionprocessed broadband photodetectors wit...
Name: ManuscriptTitle, dtype: object
4959    Optoelectronics of PbS quantum dot and narrow ...
5047    Crystalline rubrene via a novel process and re...
Name: ManuscriptTitle, dtype: object
4930    The role of charge generation layers in the op...
4964    Phase control for quasi2D blue emitters by spa...
4987    Mode coupling between nonpolar and polar phono...
5004    Thermally evaporated methylammoniumfree perovs...
Name: ManuscriptTitle, dtype: object
937    Solutionprocessed semiconductors for nextgener...
944       Scalable fabrication of perovskite solar cells
966    Role of bond adaptability in the passivation o...
971    Quantum dotplasmon lasing with controlled pola...
Name: ManuscriptTitle, dtype: object
11906    Decoupling exchange bias and coercivity enhanc...
11939    Roomtemperature optically detected magnetic re...
11945    Compressioninduced charge disproportionation i...
Name: ManuscriptTitle, dtype: object
13086    Lidocaine barbiturate a promising material for...
13100    Nature du dépôt formé au cours de l’oxydation ...
Name: ManuscriptTitle, dtype: object
2177        Nanoparticles heat through light localization
2184    Controlled nanometric phase transitions of pho...
Name: ManuscriptTitle, dtype: object
4     What would it take for renewably powered elect...
14    Erratum What would it take for renewably power...
16    What would it take for renewably powered elect...
Name: ManuscriptTitle, dtype: object
1166    Highly deformable origami paper photodetector ...
8753    Balancing power density based quantum yield ch...
Name: ManuscriptTitle, dtype: object
12932    Anthracenebased donor–acceptor low band gap po...
12943    Electric fieldinduced hole transport in copper...
12946    Surface motifs regulated aggregation induced e...
Name: ManuscriptTitle, dtype: object
14587    Geometric Design Optimisations Towards Improve...
14596    A Biocompatible Design of KappaCarrageenan/Fun...
Name: ManuscriptTitle, dtype: object
14690    Negativebias with illumination stress induced ...
14691    Drain Bias Effect on the Instability of Amorph...
Name: ManuscriptTitle, dtype: object
6566    Probing ultrafast charge separation in CZTS/Cd...
6570    Influence of thermal processing protocol upon ...
6616    AmineThiol/Selenol Chemistry for Efficient and...
Name: ManuscriptTitle, dtype: object
6575    Photophysical Processes Occurring in a Znphtha...
6647    Thermodynamic Studies of Bromide Incorporation...
Name: ManuscriptTitle, dtype: object
972     Proximal bacterial lysis and detection in nano...
3796    Population saturation in trivalent erbium sens...
Name: ManuscriptTitle, dtype: object
12920    Efficient Photocatalytic CO2 Reduction with MI...
12925    Photoelectrochemical Degradation of Organic Po...
Name: ManuscriptTitle, dtype: object
14586    Degradation of indigo carmine in alkaline dyem...
14594    Effect of pulse ontime and peak current densit...
Name: ManuscriptTitle, dtype: object
17188    The role of electrostatic interaction between ...
17189    Conducting Polymers The Role of Electrostatic ...
Name: ManuscriptTitle, dtype: object
7552     Dynamics of phononic dissipation at the atomic...
15639    Surface Passivation of BoronDiffused pType Sil...
Name: ManuscriptTitle, dtype: object
9446    Optical properties and modeling of 2D perovski...
9463    Discovering superior basal plane active twodim...
Name: ManuscriptTitle, dtype: object
15672    Closing the celltomodule efficiency gap a full...
15674    Elucidating PID degradation mechanisms and in ...
Name: ManuscriptTitle, dtype: object
11562    InGaN nanohole arrays coated by lead halide pe...
11568    Defect Variants Based on the 2D Hybrid Organic...
Name: ManuscriptTitle, dtype: object
11574    Graphitic Carbon Nitride−γGallium Oxide (GCNγG...
11577    EthylenediamineAssisted High Yield Exfoliation...
Name: ManuscriptTitle, dtype: object
11458    Measurement of absolute radical densities in a...
11510    Semiconductor–metal transitions in lead chalco...
Name: ManuscriptTitle, dtype: object
11459    Structure and chemical composition of fluorina...
11597    Niobium‐Doped Titanium Dioxide with High Dopan...
11604    Tungsten‐Nitride‐Coated Carbon Nanospheres as ...
Name: ManuscriptTitle, dtype: object
15609    Metal based triazole compounds Their synthesis...
15611    Ferrocenylaniline based amide analogs of metho...
Name: ManuscriptTitle, dtype: object
16342    Lightinduced effects on crystal size and photo...
16344    Mesoporous GOTiO2 nanocomposites for flexible ...
Name: ManuscriptTitle, dtype: object
4952    SWCNT photocathodes sensitised with InP/ZnS co...
4953    A synergistic Cs 2 CO 3 ETL treatment to incor...
Name: ManuscriptTitle, dtype: object
4955     Challenges progress and prospects in solid sta...
4979     Semitransparent nearinfrared Sn–Pb hybrid pero...
16946    Advances in ceramic thin films fabricated by p...
Name: ManuscriptTitle, dtype: object
4996     Highpressure synthesis spinglass behaviour and...
16992    Solvothermal synthesis of Fe doped MnSnO3 An a...
Name: ManuscriptTitle, dtype: object
11347    Ultrabroadband Photodetector Based on Ferromag...
11349    All‐Solid‐State Flexible Asymmetric Supercapac...
Name: ManuscriptTitle, dtype: object
11352    Energy consumption estimation of organic nonvo...
11355    Phenylquinoline Derivatives as Efficient Inter...
Name: ManuscriptTitle, dtype: object
10943    Ultrathin structures of manganese fluorides co...
10944    Rhodiumbased halfHeusler alloys as thermoelect...
10946    Recent developments in the photophysics of sin...
Name: ManuscriptTitle, dtype: object
7538    Traplimited carrier recombination in singlewal...
7539    Optical properties of confined polaronic excit...
Name: ManuscriptTitle, dtype: object
11691    Towards singlemolecule detection A novel hybri...
11770    Enhancement of second harmonic generation in c...
Name: ManuscriptTitle, dtype: object
16346    Perovskite methylammonium lead bromide incorpo...
16353    Study of DOS and energy band structures in ber...
Name: ManuscriptTitle, dtype: object
14927    Insight Into Metastable Defects in Flexible  M...
14929    Paving the Way to BuildingIntegrated Transluce...
Name: ManuscriptTitle, dtype: object
403    Facile fabrication of largegrain CH3NH3PbI3−xB...
693    Theoretical procedure for optimizing dyesensit...
Name: ManuscriptTitle, dtype: object
8645    Lowdimensional phase suppression and defect pa...
8712    Transfer printing gold nanoparticle arrays by ...
Name: ManuscriptTitle, dtype: object
9185    Limitations and solutions for achieving highpe...
9200    Organic nanocrystals induced surface passivati...
Name: ManuscriptTitle, dtype: object
5298    The potential of singlet fission photon multip...
5300    Realistic Efficiency Limits for SingletFission...
Name: ManuscriptTitle, dtype: object
4378    Advances in twodimensional organic–inorganic h...
4393    Interface passivation using ultrathin polymer–...
Name: ManuscriptTitle, dtype: object
885     Highly Absorbing LeadFree Semiconductor Cu2AgB...
5631    Enhanced Optoelectronic Performance of a Passi...
Name: ManuscriptTitle, dtype: object
5766    Explaining the fill‐factor and photocurrent lo...
5770    Metal Halide Perovskites for Solar‐to‐Chemical...
Name: ManuscriptTitle, dtype: object
275    Synergistic strain engineering of perovskite s...
296    Hybrid Perovskite Films Approaching the Radiat...
Name: ManuscriptTitle, dtype: object
5296    Modeling the performance limitations and prosp...
5299    Lattice compression increases the activation b...
5323    Nonradiative energy transfer between thickness...
Name: ManuscriptTitle, dtype: object
5271    Rationalizing and controlling the surface stru...
5278    LowTemperature Crystallization Enables 21.9% E...
Name: ManuscriptTitle, dtype: object
13445    Improved Quality Absorber Layer of I–III–VI2 C...
13446    Zincophilic Laser‐Scribed Graphene Interlayer ...
Name: ManuscriptTitle, dtype: object
16494    Eutectic solvent mediated synthesis of carbona...
16497    UV–vis spectroscopic method for detection and ...
Name: ManuscriptTitle, dtype: object
4745    Focus Issue Organic lightemitting diodes–statu...
4747    Optothermally controlled beam steering in nonl...
Name: ManuscriptTitle, dtype: object
6778    Hybrid organicinorganic polariton laser (vol 7...
6780    Alloptical fiber Hanbury Brown &Twiss interfer...
Name: ManuscriptTitle, dtype: object
1225    PinholeFree and SurfaceNanostructured NiOx Fil...
8769    Allinorganic lead halide perovskite nanohexago...
Name: ManuscriptTitle, dtype: object
4741     Dead zones in colloidal quantum dot photovolta...
7723     Effect of pristine graphene on methylammonium ...
13471    Resonant aluminum nanodisk array for enhanced ...
Name: ManuscriptTitle, dtype: object
15885    Charge driven metalinsulator transitions in La...
15886    Polar P63cm phase as a marginally stable groun...
Name: ManuscriptTitle, dtype: object
15768    A new catalyst Ti doped CdO thin film for none...
15769    Interaction of Langmuir–Blodgett and spincoate...
15771    Labelfree glucose detection over a wide dynami...
Name: ManuscriptTitle, dtype: object
505     Probing femtosecond lattice displacement upon ...
6447    Nanoparticle silver catalysts that show enhanc...
Name: ManuscriptTitle, dtype: object
14616    Highperformance coreshell structured SiOx@ Sis...
14621    Highly selective HBr etch process for fabricat...
Name: ManuscriptTitle, dtype: object

3088    Simultaneous passivation of bulk and interface...
3157    Oxygen Electrocatalysis at MnIII–Ox–C Hybrid H...
Name: ManuscriptTitle, dtype: object
3605    A “tips and tricks” practical guide to the syn...
8228    Understanding the stability of mixed Acation l...
Name: ManuscriptTitle, dtype: object
3641    Photogeneration and recombination in P3HT/PCBM...
3683    Short Photoluminescence Lifetimes in VacuumDep...
Name: ManuscriptTitle, dtype: object
6118    Effect of Different Sensitization Technique on...
6128    Co3O4 Based AllOxide PV A Numerical Simulation...
Name: ManuscriptTitle, dtype: object
6076    Charge generation and mobilitylimited performa...
6092    Silicon nanocrystals produced by nanosecond la...
Name: ManuscriptTitle, dtype: object
8349    Quasi‐2D Hybrid Perovskite Formation Using Ben...
8390    Spontaneous Formation of Nanocrystals in Amorp...
8391    Enhanced Light Emission Performance of Mixed C...
8392    Preferential Orientation of Crystals Induced b...
Name: ManuscriptTitle, dtype: object
4868    Highly flexible organometal halide perovskite ...
4873    Colloidal metal halide perovskite nanocrystals...
Name: ManuscriptTitle, dtype: object
2454    Evolution of magnetic bubble domains in mangan...
2609    Mechanical deformation of InP and GaAs by sphe...
Name: ManuscriptTitle, dtype: object
10858    Effect of fullerene acceptor on the performanc...
10879    A graphene–Mo 2 C heterostructure for a highly...
Name: ManuscriptTitle, dtype: object
5671    Special Issue on the 40th Anniversary of Unive...
5682    Inverted Polymer Solar Cells with Annealing‐Fr...
Name: ManuscriptTitle, dtype: object
12512    Luminescence rise time in selfactivated PbWO4 ...
13689    Structural variations in (001)oriented layered...
Name: ManuscriptTitle, dtype: object
8346    Ion motion determines multiphase performance d...
8348    Plasmonics Hybrid Graphene–Giant Nanocrystal Q...
Name: ManuscriptTitle, dtype: object
7867    Red to blue tunable upconversion in Tm3+doped ...
7949    Photoconductivity in Langmuir—Blodgett multila...
Name: ManuscriptTitle, dtype: object
17612    Balancing the thickness of sensitizing and ine...
17613    Scar prevention through topical delivery of ge...
Name: ManuscriptTitle, dtype: object
15074    Sizeand shapecontrolled synthesis and properti...
15090    Search for halfmetallicity in new ferrimagneti...
Name: ManuscriptTitle, dtype: object
16980    Designing of potential materials for solar‐hyd...
17014    Photovoltaic Performance Optimization of Natur...
Name: ManuscriptTitle, dtype: object
16081    Rotor and flux position estimation in deltacon...
16103    New Variants of (110)‐Oriented Layered Lead Br...
16116    Structures and structurerelated electronic pro...
16135    Perovskitebased sensing scheme for detecting v...
Name: ManuscriptTitle, dtype: object
16076    RealTime Measurement of LiIon Battery Cells Us...
16095    The role of C–H··· H–B interactions in establi...
16096    A Thiacalix Basket and its Anion‐Dependent 2‐D...
16097    Hierarchical hydroxyapatite microspheres compo...
16101    Magnetic Properties of the Ordered Double Pero...
16141    An insert for anelastic spectroscopy measureme...
Name: ManuscriptTitle, dtype: object
5322    Identifying and reducing interfacial losses to...
5326    Control Over Ligand Exchange Reactivity in Hol...
Name: ManuscriptTitle, dtype: object
11331    Dead Ends Limit Charge Carrier Extraction from...
11337    Size‐and temperature‐dependent suppression of ...
Name: ManuscriptTitle, dtype: object
6628    CsPbBr3 MAPbBr3 and FAPbBr3 Bromide Perovskite...
6629    InSitu Degradation Pathway Analyses on Hybrid ...
Name: ManuscriptTitle, dtype: object
9785    Modelling a monolithically integrated vertical...
9788    Effect of phosphorus diffusion to the recombin...
9800    Junction formation by Zn (O S) sputtering yiel...
Name: ManuscriptTitle, dtype: object
2495    Enhanced tunability of the multiphoton absorpt...
2496    Stimulated emission of CdS nanowires grown by ...
Name: ManuscriptTitle, dtype: object
1353    Highly Efficient Color‐Stable Deep‐Blue Multil...
1480    Hybrid perovskite thin‐film photovoltaics in s...
Name: ManuscriptTitle, dtype: object
4218    Oligothia dendrimers for the formation of gold...
4219    Beyond PCBM Understanding the Photovoltaic Per...
Name: ManuscriptTitle, dtype: object
4202    An Aqueous Mg2+‐Based Dual‐Ion Battery with Hi...
4217    Photothermal Catalysis Efficient Visible‐Light...
Name: ManuscriptTitle, dtype: object
16330    3D printing of shape memory polymer (SMP)/carb...
16350    Creation of uniformly dispersed nitrogenvacanc...
Name: ManuscriptTitle, dtype: object
10117    Conductivity Properties of SingleWalled Carbon...
10122    Electric Property Change of SingleWalled Carbo...
Name: ManuscriptTitle, dtype: object
15784    Positively charged membranes for dye/salt sepa...
15789    Automated portable highpressure setup for stud...
Name: ManuscriptTitle, dtype: object
7720     Correlating Nanoscale Morphology with Device P...
11181    Multifunctional Properties of a Zn (II) Coordi...
Name: ManuscriptTitle, dtype: object
2053              A graphenebased hot electron transistor
2057    Monolithically Integrated Perovskite Semicondu...
2060    Photosensitization of ZnO nanowires with CdSe ...
Name: ManuscriptTitle, dtype: object
15255    Determination of the local environment of sili...
15258    Hightemperature thermoelectric properties of S...
Name: ManuscriptTitle, dtype: object
10424    Hyperfine interaction of the CuCl4 (NH3) 22cen...
10431    Efficient calculation of excitonic effects in ...
Name: ManuscriptTitle, dtype: object
1491    Hybrid Modulation‐Doping of Solution‐Processed...
1495    Correction High‐Performance ZnO Transistors Pr...
Name: ManuscriptTitle, dtype: object
14258    VacancyDriven Noncubic Local Structure and Mag...
14259    Integrated source of spectrally filtered corre...
Name: ManuscriptTitle, dtype: object
14268    Ultrafast transient absorption spectroscopic (...
14281    A helical salicyladoximebased manganese triang...
Name: ManuscriptTitle, dtype: object
1100    Spatially Resolved Persistent Photoconductivit...
1288    Crosslinked remote‐doped hole‐extracting conta...
Name: ManuscriptTitle, dtype: object
17099    Sensitizing effect of nanocrysrtalline TiO2 fi...
17103    Toxicity response of highly colloidal bioactiv...
Name: ManuscriptTitle, dtype: object
776    Guanidiniumformamidinium lead iodide a layered...
796    Aqueous synthesis of zinc blende CdTe/CdS magi...
Name: ManuscriptTitle, dtype: object
3538     Sodium DopingEnhanced Emission Efficiency and ...
15295    From tetragonal to cubic perovskite phase stru...
Name: ManuscriptTitle, dtype: object
6386    Slow Electron Cooling Dynamics Mediated by Ele...
6388    Exciton separation in CdS supraparticles upon ...
Name: ManuscriptTitle, dtype: object
2919    Nonvolatile multistates memories for highdensi...
2928    Enhancing the efficiency and stability of PbS ...
Name: ManuscriptTitle, dtype: object
821     2D intrinsic ferromagnets from van der Waals a...
5735    Neodymium‐sensitized nanoconstructs for near‐i...
Name: ManuscriptTitle, dtype: object
10094    Synthesis and TFT properties of fluorenyl core...
10231    54‐1 Invited Paper Development of Electrolumin...
Name: ManuscriptTitle, dtype: object
5705    Control of CH3NH3PbI3 Perovskite Nanostructure...
5709    Competitive reaction pathway for site‐selectiv...
5711    Self‐Assembled Ruddlesden–Popper/Perovskite Hy...
Name: ManuscriptTitle, dtype: object
3997     Pseudohalide (SCN–)Doped MAPbI3 Perovskites A ...
15792    Pressureinduced transition in a heavy fermion ...
Name: ManuscriptTitle, dtype: object
14091    Thermoelectric properties of Czochralskigrown ...
14093    Lightharvesting fullerenes for organic solar c...
Name: ManuscriptTitle, dtype: object
6272     Barrierless Slow Dissociation of Photogenerate...
11431    Conjugated poly (azomethine) s via simple ones...
Name: ManuscriptTitle, dtype: object
4626    Gold doping of silver nanoclusters a 26‐Fold e...
4628    Effect of Zinc‐doping on the Reduction of the ...
Name: ManuscriptTitle, dtype: object
6822    A Variable Temperature Synchrotron Xray Diffra...
6845    Optical electrochemical and photocatalytic pro...
Name: ManuscriptTitle, dtype: object
3279    Critical Coupling of Visible Light Extends Hot...
3281    Polymercontrolled growth and wrapping of perov...
3283    Controlling the Thermoelectric Properties of N...
Name: ManuscriptTitle, dtype: object
14271    Evaluation of Al2O3 and ZrO2 addition to reduc...
14282    Transport and magnetic properties of La0. 8Ce0...
Name: ManuscriptTitle, dtype: object
4926    Enhanced mobility in PbS quantum dot films via...
4927    PCBMblended chlorobenzene hybrid antisolvent e...
Name: ManuscriptTitle, dtype: object
17499    Threedimensionally ordered macroporous materia...
17500    Non‐Fouling Biodegradable Poly (ϵ‐caprolactone...
17511    Efficient continuouswave nonlinear frequency c...
Name: ManuscriptTitle, dtype: object
5554    Modification of NiOx hole transport layers wit...
5556    Structural and electrical transport properties...
Name: ManuscriptTitle, dtype: object
5736    Self‐Promoting Energy Storage in Balsa Wood‐Co...
5742    Highly Passivated n‐Type Colloidal Quantum Dot...
Name: ManuscriptTitle, dtype: object
16405    Elucidating the Effect of Pressure on Structur...
16415    Enhanced Stability of Perovskite Solar Cells u...
Name: ManuscriptTitle, dtype: object
6680    Dinaphthotetrathienoacenes Synthesis Character...
6683    Gas‐assisted spray coating of perovskite solar...
Name: ManuscriptTitle, dtype: object
7086    Quantum dots in a metallopolymer host studies ...
7087    Full electronic structure across a polymer het...
Name: ManuscriptTitle, dtype: object
3751    Defect passivation for red perovskite lightemi...
3767    Modulating the Carrier Relaxation Dynamics in ...
Name: ManuscriptTitle, dtype: object
5186    Improving lowbandgap tin–lead perovskite solar...
5236    Transparent ohmic contacts for solutionprocess...
Name: ManuscriptTitle, dtype: object
3173    Ionic Liquids Modulating CsPbI3 Colloidal Quan...
3185    AllNanoTiO2 Compact Film for HighPerformance D...
Name: ManuscriptTitle, dtype: object
10825    Composition dependent optical structural and p...
10827    Interface structure precursor rheology and die...
Name: ManuscriptTitle, dtype: object
2061    Nonequilibriumplasmasynthesized ZnO nanocrysta...
2072    Formation of nanopatterned polymer blends in p...
Name: ManuscriptTitle, dtype: object
17419    Interfacial electron transfer on cytochromec s...
17421    Updates from the SPADnet project (fully digita...
Name: ManuscriptTitle, dtype: object
878    Spectroscopic investigation of the effect of m...
955    A chargeorbital balance picture of doping in c...
956    Measuring charge carrier diffusion in coupled ...
Name: ManuscriptTitle, dtype: object
16020    Preparation of (1− x%)(Na0. 5Bi0. 5) TiO3–x% S...
16021    Structural and photophysical characterization ...
16022    Novel synthetic approach to the preparation of...
Name: ManuscriptTitle, dtype: object
12560    Optically responsive delivery platforms From t...
12568    The effect of space time on Co/CeO2 catalyst d...
Name: ManuscriptTitle, dtype: object
8386    Rare‐earth metal ions doped graphene quantum d...
8445    In situ detection of soot nanoparticles by tim...
Name: ManuscriptTitle, dtype: object
17375    Systematic review elucidating the generations ...
17377    Innovatory role of nanomaterials as biotools f...
Name: ManuscriptTitle, dtype: object
11871    A bifunctional lewis base additive for microsc...
11873    High members of the 2D RuddlesdenPopper halide...
Name: ManuscriptTitle, dtype: object
9074    Nitrogen incorporation and optical studies of ...
9091    Surface electronic structure of nitrogendoped ...
Name: ManuscriptTitle, dtype: object
5259    Exciton SelfTrapping for White Emission in 100...
5260    Engineering Surface Orientations for Efficient...
Name: ManuscriptTitle, dtype: object
10102    Enhancement of photocurrent of dyesensitized s...
10105    Eucalyptus Concoction Mediated Synthesis of Go...
10110    PhotoFenton activity of magnesium substituted ...
Name: ManuscriptTitle, dtype: object
9590    Monitoring the effect of asymmetrical vertical...
9594    Sizedependent alternation of magnetoresistive ...
Name: ManuscriptTitle, dtype: object
1392    On the Question of the Need for a Built‐In Pot...
1396    Measurements of optical electric field intensi...
Name: ManuscriptTitle, dtype: object
12947    A synthetic approach to a fullerenerich dendro...
12953    Efficacious elimination of intramolecular char...
Name: ManuscriptTitle, dtype: object
17607    Electrochemical sensing of epinephrine on a ca...
17608    Desilication of low alumina to caustic liquor ...
Name: ManuscriptTitle, dtype: object
11887    Highly crystalline synthesis of tellurene shee...
11940    Stability of organic solar cells with PCDTBT d...
Name: ManuscriptTitle, dtype: object
11892    Excitonpolaron spectral structures in twodimen...
11912    Strong magnetochiral dichroism for visible lig...
Name: ManuscriptTitle, dtype: object
10910    Holetransport materials with greatlydiffering ...
10928    Precursor nonstoichiometry to enable improved ...
Name: ManuscriptTitle, dtype: object
13787    Slater halfoccupation technique revisited the ...
13788    Firstprinciples determination of bandtoband el...
Name: ManuscriptTitle, dtype: object
8554     An extensible and tunable fullopaque cascade s...
10402    Spectroscopy and control of nearsurface defect...
Name: ManuscriptTitle, dtype: object
6890    Simultaneous observation of free and defectbou...
6892    Strainenhanced dzyaloshinskii–moriya interacti...
6893           Currentdriven coherent skyrmion generation
Name: ManuscriptTitle, dtype: object
4849    Engineering Srdoping for enabling longterm sta...
4850    Deciphering the role of quantum dot size in th...
Name: ManuscriptTitle, dtype: object
5526    Optical response and structural properties of ...
5532    Investigation of the effect of sintering tempe...
Name: ManuscriptTitle, dtype: object
1949    Tailored interfaces of unencapsulated perovski...
1996    Colloidal CdSe1–xSx Nanoplatelets with Narrow ...
1998    Optimization of band structure and quantumsize...
2122    Prolonging charge separation in P3HT− SWNT com...
2128    Quantum confined electron–phonon interaction i...
Name: ManuscriptTitle, dtype: object
2003     Crosslinked C60 Polymer Breaches the Quantum Gap
2010    Programmable metal/semiconductor nanostructure...
Name: ManuscriptTitle, dtype: object
15046    Interfacial engineering of halide perovskites ...
15047    Colloidal metal oxide nanocrystals as charge t...
Name: ManuscriptTitle, dtype: object
16775    Structural Microstructural and Magnetic Studie...
16779    Magnetocaloric Properties of La0.85Ag0.15MnO3 ...
Name: ManuscriptTitle, dtype: object
15984            Aging memory and oxygen vacancies in PLZT
15985    Memory effects in dielectric and anelastic mea...
Name: ManuscriptTitle, dtype: object
11880    Thermal transport in ZnO nanocrystal networks ...
11924    Hybrid perovskite solar cells In situ investig...
Name: ManuscriptTitle, dtype: object
12004    Deep‐blue low‐threshold amplified spontaneous ...
12005    Efficient Solution‐Processed Inverted Organic ...
Name: ManuscriptTitle, dtype: object
11951    Band Alignments in InxGa1–xP/GaAs Heterostruct...
11968    Al‐Doped ZnO nanowires by electrochemical depo...
Name: ManuscriptTitle, dtype: object
12010    Formation of High‐Pressure Phase of Titanium D...
12053    InSitu NanoAuger Probe of ChlorideIons during ...
Name: ManuscriptTitle, dtype: object
7038    Direct coherent multiink printing of fabric su...
7040    Heterojunction oxide thinfilm transistors with...
Name: ManuscriptTitle, dtype: object
9307    Molecular dynamics study of the interactions o...
9329    Preparation and characterization of ammoniumfu...
Name: ManuscriptTitle, dtype: object
8770    Highly luminescent and ultrastable cesium lead...
8774    Novel silicon compatible pWS 2 2D/3D heterojun...
Name: ManuscriptTitle, dtype: object
3357    Efficient and Stable Blue and RedEmitting Pero...
3377    Electrocrystallization of epitaxial zinc oxide...
3483    Pulsed Laser Deposition of Cs2AgBiBr6 from Mec...
Name: ManuscriptTitle, dtype: object
2002    Highcurvature nanostructuring enhances probe d...
2007    Engineering directionality in quantum dot shel...
2119    Twodimensional covalent crystals by chemical c...
2126    Confirmation of KMomentum Dark Exciton Vibroni...
Name: ManuscriptTitle, dtype: object
16267    Manipulation of the exciton diffusion length o...
16275    Studies on the synthesis and characterization ...
Name: ManuscriptTitle, dtype: object
17298    Facile synthesis of magnetite nanocubes using ...
17305    1 1 and 1 2 Complexes of Mercury (II) Halides ...
Name: ManuscriptTitle, dtype: object
16818    Ab initio study of structural elastic and elec...
16820    Effect of hydrostatic pressure on the structur...
Name: ManuscriptTitle, dtype: object
7463    Theoretical study of straininduced ordering in...
7476    Monolayer honeycomb structures of groupIV elem...
Name: ManuscriptTitle, dtype: object
4133    Operating Modes of Sandwiched Light‐Emitting E...
4136    Reversible formation of gold halides in single...
Name: ManuscriptTitle, dtype: object
4551    Hot Carrier Generation and Extraction of Plasm...
4568    Fourwave mixing in perovskite photovoltaic mat...
4573    Rational design of efficient palladium catalys...
Name: ManuscriptTitle, dtype: object
1120     Random lasing with systematic threshold behavi...
11173    An unusual interweaving in a 3fold interpenetr...
Name: ManuscriptTitle, dtype: object
825     Universal Transients in Polymer and Ionic Tran...
5571    Sampletoanswer isolation and mRNA profiling of...
Name: ManuscriptTitle, dtype: object
8771     Enhancement of photodetection characteristics ...
12941    Efficient passivated phthalocyaninequantum dot...
12942    Lithiumrich sulfide/selenide cathodes for next...
Name: ManuscriptTitle, dtype: object
986     Electronic Properties of a 1D Intrinsic/pDoped...
1072    The subtle chemistry of colloidal quantumconfi...
Name: ManuscriptTitle, dtype: object
16237    Piezoelectricity from Elastic and Dielectric M...
16238    Development of geopolymers for catalyst suppor...
17321    Transport of salicylic acid through supported ...
17324    Bandgap Engineering in Novel Fluorite‐Type Rar...
17329    Computational Prediction of a Novel Superhard ...
17332    Vein detection with near‐infrared organic phot...
17333    Integration of largearea optical imagers for b...
17337    Alkali metal doped nickel oxide clusters A den...
17338    Phonon stability electronic structure results ...
17339    A DFT investigation on electronic structure ch...
17343    Ultrabroadband thermal radiator for daytime pa...
17348    Physical Vapor Deposited [CoCd(dtc)2]/SnO2 Dua...
17349    PVA/Gd2O3@ Zno Nanocomposite Films as New UvBl...
17351    Characterization of Cu2ZnSnSe4 Thin Films Sele...
17354    Halide perovskite materials as chemical playgr...
17355    Experimental verification of optically optimiz...
17366    Impact of single pMOSFET dielectric degradatio...
Name: ManuscriptTitle, dtype: object
16187    Electrical transport and specific heat propert...
16195    Structure and energetics of ZrC (100)|| cZrO2 ...
16207    Review of perovskitestructure related cathode ...
16234    Effect of cobalt doping on structural optical ...
16245    Current status and prospects on chemical struc...
16252    Interaction of alkali alkaline earth and trans...
Name: ManuscriptTitle, dtype: object
16210    Hopping and clustering of oxygen vacancies in ...
16231    Oxygen ordering and mobility in ReBa sub 2 Cu ...
16248    Detection and spectroscopy of the ν1+ ν3 band ...

12893    Electrochemical topotactic oxidation of nonsto...
12894                    In situ reduction of (100) SrTiO3
Name: ManuscriptTitle, dtype: object
16835    Terahertz spin currents and inverse spin Hall ...
16837    Deposition uniformity and particle size distri...
Name: ManuscriptTitle, dtype: object
16832    Evaluation of the contributions to the effecti...
16838    Synthesis of a zinc–imidazole metal–organic fr...
Name: ManuscriptTitle, dtype: object
13405    Effect of processing by femtosecond pulsed las...
13407    Physicochemical tools toward a detailed unders...
Name: ManuscriptTitle, dtype: object
15108    Surface passivation of organometal halide pero...
15110    Photoconductivity of PbS/perovskite quantum do...
15113    Photonupconverters for blue organic lightemitt...
15114    Directional quantum dot emission by softstampi...
Name: ManuscriptTitle, dtype: object
15111    Synthesis of twodimensional phenylethylamine t...
15116    Ligandfree allinorganic metal halide nanocubes...
15117    Theoretical insights into C–H bond activation ...
Name: ManuscriptTitle, dtype: object
11452    Study of surface reactions during plasma enhan...
12660    Exsolution of Realloy catalysts with enhanced ...
Name: ManuscriptTitle, dtype: object
11585    DNAmediated threedimensional assembly of hollo...
11586    Multifunctional bismuth nanoparticles as thera...
11587    Defect Passivation of Mn2+Doped CsPbCl3 Perovs...
Name: ManuscriptTitle, dtype: object
11486    Optical depth profiling of strontium titanate ...
11512    Unusual B1–B2 transition in PbSe under high pr...
Name: ManuscriptTitle, dtype: object
8323    Nonlinear Optical Properties of Colloidal CH3N...
8324    Aggregation‐Induced Emission Features of Organ...
Name: ManuscriptTitle, dtype: object
8337    Double active layers constructed with halide p...
8341    Hybrid Perovskite Degradation from an Optical ...
Name: ManuscriptTitle, dtype: object
8321    Solution Coating of Superior Large‐Area Flexib...
8325    Perovskite Quantum Dots Embedded Composite Fil...
Name: ManuscriptTitle, dtype: object
8338    Aligning Transition Dipole Moment toward Light...
8339    Chirality Induced Crystal Structural Differenc...
8340        Gallium polymorphs phase‐dependent plasmonics
Name: ManuscriptTitle, dtype: object
8327    Highly Efficient Light Emitting Diodes Based o...
8411    Negative Thermal Quenching and Size‐Dependent ...
Name: ManuscriptTitle, dtype: object
8382    Halide perovskites a progress report on photon...
8399    Hybrid Plasmonic and Pyroelectric Harvesting o...
8417    Magnetic Manipulation of Spontaneous Emission ...
Name: ManuscriptTitle, dtype: object
8331    Polarization‐Sensitive Ultraviolet Detection f...
8372    Angle and polarization selective spontaneous e...
Name: ManuscriptTitle, dtype: object
8378    A‐Site Cation Engineering in 2D Ruddlesden–Pop...
8379    Optical Gain of Lead Halide Perovskites Measur...
Name: ManuscriptTitle, dtype: object
8353    Can trihalide Lead perovskites support continu...
8359    Organic Nanofibers Extending the Lasing Wavele...
Name: ManuscriptTitle, dtype: object
8371    Flexible Electronics Broadband Light Out‐Coupl...
8441    Twophotonenhanced threephoton absorption in tr...
Name: ManuscriptTitle, dtype: object
8404    Optoelectronic Synapses Based on Photo‐Induced...
8425    The Intrinsic Photoluminescence Spectrum of Pe...
Name: ManuscriptTitle, dtype: object
8369    Illumination‐Induced Halide Segregation in Gra...
8448    Transmission properties of one dimensional fra...
Name: ManuscriptTitle, dtype: object
14813                           Sliver/spl reg/solar cells
14864    Investigation of materials for hot carrier sol...
Name: ManuscriptTitle, dtype: object
7990    Identification of the physical origin behind d...
8086    The effect of structural dimensionality on car...
Name: ManuscriptTitle, dtype: object
13280    Polarization dependent excitation and high har...
13286    Strain Engineering A Pathway for Tunable Funct...
Name: ManuscriptTitle, dtype: object
13267    Ligandlength modification in CsPbBr3 perovskit...
13271                Nanostructured perovskite solar cells
Name: ManuscriptTitle, dtype: object
13337    Photoluminescence spectral position shift gove...
13348    Atom optics with Bose–Einstein condensates qua...
Name: ManuscriptTitle, dtype: object
13327    2D Perovskite Microoptics Enabled by Direct Fe...
13346    Thermopower and phase transition in YbPd2Si2 u...
Name: ManuscriptTitle, dtype: object
2757    Temperaturedependent tunneling electroresistan...
2768    Band alignment at  heterojunctions and electro...
Name: ManuscriptTitle, dtype: object
2655    CONDENSED MATTER STRUCTURAL MECHANICAL THERMAL...
2678    Microscopic investigation of the poly (9 9dioc...
Name: ManuscriptTitle, dtype: object
11091    Energy level alignment at interfaces in organi...
11092    The interface electronic properties of organic...
11094    Observation of filled states at the Fermilevel...
Name: ManuscriptTitle, dtype: object
887     Atomistic Insights into Activation and Degrada...
1026    Ultralowthreshold twophoton pumped amplified s...
Name: ManuscriptTitle, dtype: object
3294     PacketOriented Photonic Networks (Guest Editor...
12731    Citral hydrogenation on high surface area meso...
Name: ManuscriptTitle, dtype: object
4307    Low‐Bandgap Methylammonium‐Rubidium Cation Sn‐...
6855                       Axial plane optical microscopy
Name: ManuscriptTitle, dtype: object
9607    Subnanometer glass surface dynamics induced by...
9608    Mixed halide bulk perovskite triplet sensitize...
Name: ManuscriptTitle, dtype: object
3619     Crucial Contribution of Polarity for the Bulk ...
12646    Oxygen storage capacity of La1x Formula Not Sh...
Name: ManuscriptTitle, dtype: object
1025    Rearranging lowdimensional phase distribution ...
1048    Circularly Polarized Emission from Organic–Ino...
Name: ManuscriptTitle, dtype: object
12857    Doping studies of the magnetic cobaltocuprate ...
12867    Full Heusler alloys (Co2TaSi and Co2TaGe) as p...
Name: ManuscriptTitle, dtype: object
15354    Seed‐Mediated Synthesis of Colloidal 2D Halide...
15358    Color tunable organic lightemitting diodes usi...
Name: ManuscriptTitle, dtype: object
8133    Impact of local structure on halogen ion migra...
8134    Photodecomposition and thermal decomposition i...
Name: ManuscriptTitle, dtype: object
8101    Pt/C–LiCoO 2 composites with ultralow Pt loadi...
8103    Renewable acetic acid in combination with soli...
8137    Facile synthesis of Ge–MWCNT nanocomposite ele...
Name: ManuscriptTitle, dtype: object
8049    Efficient nonfullerene organic solar cells emp...
8146    Pushing efficiency limits for semitransparent ...
Name: ManuscriptTitle, dtype: object
7516    Ultrafast carrier dynamics in core and core/sh...
7526    Semiconductors II Surfaces interfaces microstr...
Name: ManuscriptTitle, dtype: object
3033    Silicon Nanocanyon Onestep bottomup fabricatio...
3133    Borondoped silicon diatom frustules as a photo...
Name: ManuscriptTitle, dtype: object
17086    AcetamidiniumMethylammoniumBased Layered Hybri...
17088    Ultrafast charge and triplet state formation i...
Name: ManuscriptTitle, dtype: object
11875    Gap states induce soft Fermi level pinning upo...
11914    Thermal stability of nanoscale ferroelectric d...
Name: ManuscriptTitle, dtype: object
11893     speciation and energytransfer dynamics in qua...
11908    Enhancement of magnetic properties in compress...
Name: ManuscriptTitle, dtype: object
15284    Effect of the chromophores structures on the p...
15949    Resistance of 2ZrO2· Y2O3 top coat in thermal/...
Name: ManuscriptTitle, dtype: object
806    Triazole bridges as versatile linkers in elect...
822    Tunable magnetism and extraordinary sunlight a...
Name: ManuscriptTitle, dtype: object
7083     Halide perovskite nanocrystal arrays Multiplex...
11178    Influence of angular dicarboxylate ligand on t...
Name: ManuscriptTitle, dtype: object
10008    The effect of doping in the electrochemical pe...
10010    Graph theory model and mechanism analysis of c...
Name: ManuscriptTitle, dtype: object
1336    High‐Rate and Selective CO2 Electrolysis to Et...
1357    Oxygen Vacancies Allow Tuning the Work Functio...
1477    High‐performance ZnO transistors processed via...
Name: ManuscriptTitle, dtype: object
1359    Switching the Electronic Properties of ZnO Sur...
1541    Tethered Small‐Molecule Acceptors Simultaneous...
Name: ManuscriptTitle, dtype: object
1385    Substituted Rigid Rod‐Like Polymers—Building B...
1394    The role of bulk and interface recombination i...
1580    Bragg Stacks Enhancing Upconversion for Photov...
Name: ManuscriptTitle, dtype: object
1387    Direct determination of the emission zone in a...
1408            Chains of superparamagnetic nanoparticles
Name: ManuscriptTitle, dtype: object
1411    Efficient and spectrally stable blue perovskit...
1422    Enhancement of the performance of perovskite s...
1429    Halide perovskites a new era of solution‐proce...
Name: ManuscriptTitle, dtype: object
8130    Inorganic caesium lead iodide perovskite solar...
8135    Thermal degradation of formamidinium based lea...
Name: ManuscriptTitle, dtype: object
17198    Pyrene Solubilization in Aqueous Micellar Solu...
17223    Carbon nanotubes and carbon fibers in a flash ...
Name: ManuscriptTitle, dtype: object
11304    Layered SnSe nanoflakes with anharmonic phonon...
11305    Band bending at magnetic Ni/Ge (001) interface...
Name: ManuscriptTitle, dtype: object
15238    Excitation wavelength dependent fluorescence b...
15239    Natural sensitizers for DSCs improved with nan...
Name: ManuscriptTitle, dtype: object

167                               Boosting plant biology
169    Orientationdependent ionization energies and i...
Name: ManuscriptTitle, dtype: object
9121     Anomalous power dependence of upconversion emi...
11400    Ultrafast Carrier Redistribution in Single  Qu...
Name: ManuscriptTitle, dtype: object
9136    Recombination processes in passivated boronimp...
9166    Experiment Specification Capture and Laborator...
Name: ManuscriptTitle, dtype: object
7278    Logarithmic frequency dependence of the piezoe...
7285    Cation vacancies in ferroelectric PbTiO3 and P...
Name: ManuscriptTitle, dtype: object
5103    Graphene oxide shells on plasmonic nanostructu...
5163    Controlling the phase segregation in mixed hal...
Name: ManuscriptTitle, dtype: object
5155    Energy Spotlight Insights into Lithium Metal B...
5158    Tuning the SurfacePassivating Ligand Anchoring...
Name: ManuscriptTitle, dtype: object
5146    Overcoming Degradation Pathways to Achieve Sta...
5170    Boosting longterm stability of pure formamidin...
Name: ManuscriptTitle, dtype: object
3310    Revealing the Stoichiometric Tolerance of Lead...
3477    Polymerfree films of inorganic halide perovski...
Name: ManuscriptTitle, dtype: object
1497    Photovoltaics Highly Efficient Hybrid Photovol...
1525    Subtle molecular tailoring induces significant...
Name: ManuscriptTitle, dtype: object
12665    Planar heterojunction boosts solardriven photo...
12675    Influence of Mn and Fe Addition on the NO x  S...
Name: ManuscriptTitle, dtype: object
361    Impact of interfacial molecular orientation on...
371    Inversion symmetry and bulk Rashba effect in m...
Name: ManuscriptTitle, dtype: object
16627    Nitrogen doped cuprous oxide as low cost holet...
16628    Effect of grain size on the fracture behavior ...
Name: ManuscriptTitle, dtype: object
16575    Characterization of 430L porous supports obtai...
16594    Structural functional properties and enhanced ...
Name: ManuscriptTitle, dtype: object
7743    Cathode of ZnNi Layered Double Hydroxide Nanos...
7746    MultiScalable Grain Growth via PhenylC60Butyri...
Name: ManuscriptTitle, dtype: object
16256    Nonlinear optical switching and optical limiti...
16257    Unveiling photophysical and photonic phenomena...
Name: ManuscriptTitle, dtype: object
4372    Impedance spectroscopy characterisation of hig...
7794    Feasibility analysis of nanostructured planar ...
Name: ManuscriptTitle, dtype: object
8297    Ecofriendly Perovskites with Giant Self‐Defocu...
8301    Giant Bulk Photostriction and Accurate Photome...
Name: ManuscriptTitle, dtype: object
16543    Metal injection moulding of HS12155 highspeed ...
16552    Biomimetic [MoO3@ ZnO] semiconducting nanocomp...
Name: ManuscriptTitle, dtype: object
10624    Perovskite type BaSnO3reduced graphene oxide n...
15895    Niobium doping and dielectric anomalies in bis...
Name: ManuscriptTitle, dtype: object
3996    Inorganic hole conducting layers for perovskit...
4019    Band engineering via gradient molecular dopant...
4021    Controlling Electron and Hole Charge Injection...
Name: ManuscriptTitle, dtype: object
16355    Magnetic and electronic properties of halfmeta...
16357    GGA based study on electronic structure and th...
Name: ManuscriptTitle, dtype: object
1455    Micro‐and nanostructured lead halide perovskit...
1551    Alkyl side‐chain engineering in wide‐bandgap c...
Name: ManuscriptTitle, dtype: object
13423    Synergistically enhanced electric field in inh...
13433    Combined Fluorescence Fluctuation and Spectrof...
Name: ManuscriptTitle, dtype: object
7829    Sustainable fabrication of ultralong Pb (OH) B...
7831    Electrochemical synthesis of TGAcapped CdTe an...
7954    Bright and efficient blue and green lightemitt...
Name: ManuscriptTitle, dtype: object
5113    Nanoemitting heterostructures violate optical ...
6958    Interplay of couplings between antiferrodistor...
Name: ManuscriptTitle, dtype: object
8422    Ultra‐broadband Polarisers Based on Metastable...
8431    The Multiple Roles of Metal Ion Dopants in Spe...
Name: ManuscriptTitle, dtype: object
8423    Photoluminescence of Bound‐Exciton Complexes a...
8426    Shaping the emission spectral profile of quant...
Name: ManuscriptTitle, dtype: object
8381    Tuning Halide Composition Allows Low Dark Curr...
8402    Experimental Evidence of Chloride‐Induced Trap...
Name: ManuscriptTitle, dtype: object
12176    Extension of the Application of Piers‐Rubinszt...
12186    Requirements for plasma synthesis of nanocryst...
Name: ManuscriptTitle, dtype: object
7406    RAPID COMMUNICATIONSSemiconductors II Surfaces...
7410    Optical properties of  –doped oxides Different...
Name: ManuscriptTitle, dtype: object
5936    Overcoming Electrode‐Induced Losses in Organic...
5942    Requirements for beneficial electrochemical re...
5956    Efficient Thermally Evaporated γ‐CsPbI3 Perovs...
Name: ManuscriptTitle, dtype: object
15715    Functionalisation separation and solvation gen...
15716    Protein adsorption on nanoporous TiO 2 films a...
Name: ManuscriptTitle, dtype: object
15706    Influence of surface charges on the emission p...
15711    Effect of postannealing on the plasma etching ...
Name: ManuscriptTitle, dtype: object
2748    Nonlinear optical properties of benzylamine le...
2764    Polarization offsets of compositionally graded...
Name: ManuscriptTitle, dtype: object
6227    Fluorescence switching of quantum dot in quant...
6228    Ultrafast Relaxation Dynamics of Luminescent C...
6229    Design of a CdS/CdSe Heterostructure for Effic...
Name: ManuscriptTitle, dtype: object
330     The quantumconfined Stark effect in layered hy...
1126    Quasiepitaxial metalhalide perovskite ligand s...
Name: ManuscriptTitle, dtype: object
488      Abnormal band bowing effects in phase instabil...
12652    Selfassembled leadfree double perovskiteMXene ...
Name: ManuscriptTitle, dtype: object
9779    Surface passivation by rehydrogenation of sili...
9780    Reactive ion etching of dielectrics and silico...
Name: ManuscriptTitle, dtype: object
12105    Recent Progress in Polymorphs of Carbon Nitrid...
12128    Investigations of the viscoelastic properties ...
12135    COMMUNICATIONS TO THE EDITORInterplay of Therm...
Name: ManuscriptTitle, dtype: object
12061    SolGel Synthesis and Characterization of Yttri...
12109    Michael Polyaddition Approach Towards Sulfur E...
Name: ManuscriptTitle, dtype: object
12148    Novel electroluminescent polymers with fluoro ...
12149    Easily Attainable PhenothiazineBased Polymers ...
Name: ManuscriptTitle, dtype: object
12074    Nonlinear optical feedback for nanoand micropa...
12076    Halide Perovskites for Photonics and Optoelect...
Name: ManuscriptTitle, dtype: object
12114    Ordering graphoepitaxial orientation and confo...
12137    A phase diagram of the P3HT PCBM organic photo...
Name: ManuscriptTitle, dtype: object
12108    Polyethylene‐Derived Activated Carbon Material...
12134    Orientation and Dynamics of Chainlike Dipole A...
Name: ManuscriptTitle, dtype: object
12121    Preparation of oriented multilayers of poly (s...
12182    Fabrication and properties of B–N codoped ptyp...
Name: ManuscriptTitle, dtype: object
5369      A taxonomy for threeterminal tandem solar cells
5371    Understanding the PerformanceLimiting Factors ...
Name: ManuscriptTitle, dtype: object
9668    Implication of polymeric template agent on the...
9669    Hybrid nanocrystal/polymer solar cells based o...
Name: ManuscriptTitle, dtype: object
10201    Perforated Ndoped monoclinic ZnWO 4 nanorods f...
10254    An Investigation of the Photoinduced Changes o...
10289    Photoswitched Protein Adsorption on Electrosta...
Name: ManuscriptTitle, dtype: object
14233    RotaryJet spin assisted fabrication of MnO2 mi...
14245    Circularly Polarized Emission from Ensembles o...
Name: ManuscriptTitle, dtype: object
7099    Aryl amine substituted low energy gap carbazol...
7100    Localized surface plasmon resonance sensor bas...
Name: ManuscriptTitle, dtype: object
5303    14th International Conference on Hybrid and Or...
5304    Postsynthesis Transformation of Insulating Cs4...
5305    Efficient widebandgap mixedcation and mixedhal...
Name: ManuscriptTitle, dtype: object
2329    Electrodemolecular semiconductor contacts Work...
2351    Charging and excitonmediated decharging of met...
Name: ManuscriptTitle, dtype: object
5897    Characterization of the Valence and Conduction...
5920    Improved open‐circuit voltage in ZnO–PbSe quan...
Name: ManuscriptTitle, dtype: object
9691     Adjusting the Néel relaxation time of Fe3O4/Zn...
13525    Cationselective and anioncontrolled fluorogeni...
Name: ManuscriptTitle, dtype: object
2851    Suspended photonic crystal membranes in AlGaAs...
2883    Tuning the electronic structure of graphene by...
Name: ManuscriptTitle, dtype: object
14335    Magnetostatic spin wave resonance in squarepat...
14336    Tetragonal distortion induced perpendicular ma...
14337    Enhancement of dielectric and magnetic propert...
Name: ManuscriptTitle, dtype: object
234        Nanostructured materials for photon detection
283    Detection of Xray photons by solutionprocessed...
Name: ManuscriptTitle, dtype: object
12571    A K2NiF4type La2Li0. 5Al0. 5O4 catalyst for th...
12573    Design of nanocatalysts for green hydrogen pro...
12580    Nanoscale perovskite‐sensitized solar cell rev...
12597    A TiO2 Nanofiber–Carbon Nanotube‐Composite Pho...
12598    Plasmonic Gold Nanostars Incorporated into Hig...
Name: ManuscriptTitle, dtype: object
2866    Singlecell tumbling enables highresolution siz...
2955    Unravelling the photocatalytic behavior of all...
Name: ManuscriptTitle, dtype: object
15537    Pulsed electrodeposition of WO3–TiO2 composite...
15558    Implementation of a “design of experiments” me...
15564    Effects of Cu2− xS phase removal on surface po...
Name: ManuscriptTitle, dtype: object
5483    Direct evidence for percolation of immobilized...
5485    Twodimensional MOF modulated fiber nanogenerat...
Name: ManuscriptTitle, dtype: object
4714    Metal Coordination Sphere Deformation Induced ...
4715    Solution‐processed reduced graphene oxide film...
Name: ManuscriptTitle, dtype: object
9291    Leakage current effects on  plots of high meta...
9292    Nanowire fin field effect transistors via UVba...
9300    Papers from the 47th International Conference ...
9310    Growth and characterization of MnAs/ZnSe ferro...
9317    Solgel synthesized indium tin oxide as a trans...
9325    The effect of processing conditions on the mor...
9326    Effect of silane coupling agent on the morphol...
9328    Balancing hyperbole and impact in research com...
9332    Rh/CeO2 catalyst preparation and characterizat...
9337    Theoretical study of the strain influence on l...
Name: ManuscriptTitle, dtype: object
9311    Papers from the 19th North American Conference...
9330    Electrode characteristics of Li2Ti3O7ramsdelli...
Name: ManuscriptTitle, dtype: object
15033    Investigating the Role of Lewis AcidBase Inter...
15037    Formations of unexpected chlorobridged bis (ma...
Name: ManuscriptTitle, dtype: object
12071    Fabrication of Pressure Conductive Silicone Ru...
12073    Metaldielectric nanoantenna for radiation cont...
Name: ManuscriptTitle, dtype: object
6655    Fabrication pressure testing and nanopore form...
6707          Light manipulation in organic photovoltaics
Name: ManuscriptTitle, dtype: object
449     Lightactivated photocurrent degradation and se...
1157    Dilutioninduced formation of hybrid perovskite...
Name: ManuscriptTitle, dtype: object
16669    Insight into pressure tunable structural elect...
16684            Synthesis of 13Cdiamonds in CaCO3C system
Name: ManuscriptTitle, dtype: object
14732    Dependability assessment of transfer length me...
14733    A broadband active microwave monolithically in...
Name: ManuscriptTitle, dtype: object
2795    Elucidating possible crystallographic origins ...
2816                   Physics of ultrathin photovoltaics
Name: ManuscriptTitle, dtype: object
14743    Metalassisted chemical etching for very high a...
14749    Characterization of SOI MOSFETs by means of ch...
Name: ManuscriptTitle, dtype: object
3677         Advances in spraycast perovskite solar cells
3678    Lévy defects in matriximmobilized J aggregates...
Name: ManuscriptTitle, dtype: object
4297    Crystalline Mesoporous Complex Oxides Porosity...
4298    High‐Temperature Photoluminescence of CsPbX3 (...
Name: ManuscriptTitle, dtype: object
4982    Ultrasensitive turnon luminescence humidity se...
5001    Effect of density of surface defects on photol...
Name: ManuscriptTitle, dtype: object
5116    Formamidinium lead halide perovskite crystals ...
6965    Nonlinear Dynamics Fluid Dynamics Classical Op...
Name: ManuscriptTitle, dtype: object
2269    An electrochemical clamp assay for direct rapi...
2325    In situ resistance measurement of the type con...
Name: ManuscriptTitle, dtype: object
5497    Perspectives of chalcopyritebased CIGSe thinfi...
5500    Synthesis of NiO–CeO2 nanocomposite for electr...
Name: ManuscriptTitle, dtype: object
14330    Electrical transport properties and transport–...
14370    Comparison of highly conductive natural and sy...
Name: ManuscriptTitle, dtype: object
9583    Bonding in d9 complexes derived from EPR Appli...
9584    Crystalfield and charge transfer transitions d...
Name: ManuscriptTitle, dtype: object
7556    Surface physics lowdimensional systems and rel...
7566    Magnetotransport properties of doped RuSr 2 Gd...
Name: ManuscriptTitle, dtype: object
1307         Mixed lead halide passivation of quantum dots
16738    A novel Tb3+ ions doped barium strontium fluor...
Name: ManuscriptTitle, dtype: object
15223    The effect of Au on TiO2 catalyzed selective p...
15226    Impact of one step alloying on the carrier rel...
Name: ManuscriptTitle, dtype: object
2633    “Smart” silicon Switching between p‐ and n‐con...
2637    Colossal enhancement of the thermoelectric pow...
Name: ManuscriptTitle, dtype: object
4004    Untying the Cesium “Not” Cesium–Iodoplumbate C...
4009    Graphdiyne an efficient hole transporter for s...
Name: ManuscriptTitle, dtype: object
4002    Quantum dot photocatalysts for organic transfo...
4010    Efficient infrared electroluminescent devices ...
Name: ManuscriptTitle, dtype: object
5619    Sustained SolarPowered Electrocatalytic H2 Pro...
5620    Teacarbon dotsreduced graphene oxide an effici...
5621    Green SolventBased Perovskite Precursor Develo...
Name: ManuscriptTitle, dtype: object
12077    Erratum Halide Perovskites for Photonics and O...
12080    Temperature dependent twophoton photoluminesce...
Name: ManuscriptTitle, dtype: object
16708    Self nitrogen and oxygenbroadening coefficient...
16709    Highresolution infrared spectroscopy of the ν2...
Name: ManuscriptTitle, dtype: object
2219    Strain effect in palladium nanostructures as n...
2230    Nanoscale back contact perovskite solar cell d...
Name: ManuscriptTitle, dtype: object
2173    Unveiling the shape evolution and halideionseg...
2185                   Optical force stamping lithography
Name: ManuscriptTitle, dtype: object
9259    Organolead halide perovskite regulated green l...
9261    Improved energy harvesting ability of C3H7NH3P...
Name: ManuscriptTitle, dtype: object
9258    Structure engineering of hierarchical layered ...
9260    Piezophototronic effect in highly stable CsPbI...
Name: ManuscriptTitle, dtype: object
3193    Electrical conductivity of doped organic semic...
3194       Molecular Doping Directed by a Neutral Radical
Name: ManuscriptTitle, dtype: object
3863    Change in tetracene polymorphism facilitates t...
3867    Ultrafast Optical Mapping of Nonlinear Plasmon...
Name: ManuscriptTitle, dtype: object
5346    Women scientists at the forefront of energy re...
5347    Leadfree dion–jacobson tin halide perovskites ...
Name: ManuscriptTitle, dtype: object
2878     Surface State Density Determines the Energy Le...
13587    Sharp Lines Due to Cr3+ and Mn2+ Impurities in...
Name: ManuscriptTitle, dtype: object
4204    Simultaneous Power Conversion Efficiency and S...
4212    Novel Method of Preparation of Gold‐Nanopartic...
Name: ManuscriptTitle, dtype: object
13252    NiO Nanofibers as a Candidate for a Nanophotoc...
13253               Quantum dot sensitized photoelectrodes
Name: ManuscriptTitle, dtype: object
12162    Atomistic investigation of the solubility of 3...
12163    Synthesis of πbridged duallydopable conjugated...
Name: ManuscriptTitle, dtype: object
372    Pure crystal orientation and anisotropic charg...
379    Electrically tunable organic–inorganic hybrid ...
380    Microcavitylike excitonpolaritons can be the p...
Name: ManuscriptTitle, dtype: object
1136    MoS2 Quantum Dot/Graphene Hybrids for Advanced...
1198    Revealing factors influencing the operational ...
Name: ManuscriptTitle, dtype: object
9282    Electrical scanning probe microscopy Investiga...
9285    Twodimensional profiling of carriers in a buri...
9286    Twodimensional transverse crosssection nanopot...
Name: ManuscriptTitle, dtype: object
9305    Real time in situ monitoring of surfaces durin...
9308    Planar metal–insulator–metal diodes based on t...
Name: ManuscriptTitle, dtype: object
9545    On the polarization of the green emission of p...
9564    PseudoJahnTeller origin of geometry and pseudo...
9567    A simple monomerbased modelHamiltonian approac...
Name: ManuscriptTitle, dtype: object
6243    Quenching of confined C480 dye in the presence...
6246    Structural Analysis and Carrier Relaxation Dyn...
Name: ManuscriptTitle, dtype: object
1817    Halide Remixing under Device Operation Imparts...
1841    Neutron Detectors Cesium Lead Bromide (CsPbBr3...
Name: ManuscriptTitle, dtype: object
14496    4Terminal Inorganic Perovskite/Organic Tandem ...
14503    0.86nm CET Gate Stacks With Epitaxial GdO High...
Name: ManuscriptTitle, dtype: object
6067    Effect of solvent additive on generation recom...
6085    Synthesis and Optical Properties of a Dithiola...
Name: ManuscriptTitle, dtype: object
4644    High‐performance perovskite light‐emitting dio...
4657    Biosupramolecular Nanowires from Chlorophyll D...
4689    Metal–organic organopolymeric hybrid framework...
Name: ManuscriptTitle, dtype: object
3064    How Deep Hole Traps Affect the Charge Dynamics...
3100    Enhanced Device Performance with Passivation o...
3118    Direct hotinjection synthesis of lead halide p...
Name: ManuscriptTitle, dtype: object
11446    Photovoltaic manufacturing Present status futu...
11470    Substrate and temperature dependence of the fo...
11569    Potassium and Rubidium Copper Halide A2CuX3 (A...
Name: ManuscriptTitle, dtype: object
13046    Molecularengineered [Ir (Fppy) 2 (Mepic)] towa...
13048    Copper (i) ionic complexes based on imidazo [4...
Name: ManuscriptTitle, dtype: object
13025    Copperzinc oxide catalysts. Part IV. Thermal t...
13026    Chimie douce synthesis and thermochemical char...
Name: ManuscriptTitle, dtype: object
13032    Scalable heterogeneous synthesis of metallic n...
13064    Structural interpretation of SnO 2 nanocrystal...
Name: ManuscriptTitle, dtype: object
3288    Conductivity Optimization of Tysonitetype La1–...
3296    Synthesis of Colloidal CuGaSe2 CuInSe2 and Cu(...
Name: ManuscriptTitle, dtype: object
6605    Oligofluorene molecular wires Synthesis and si...
6606    The photochemistry of crystalline nitromethane...
Name: ManuscriptTitle, dtype: object
10983    Atomicscale origin of piezoelectricity in wurt...
10991    Electronic optical and thermoelectric properti...
10999    Solvent Hbond accepting ability induced confor...
Name: ManuscriptTitle, dtype: object
13194    ABCmodel analysis of gainswitched pulse charac...
13210    Highly stable fluorinepassivated In–Ga–Zn–O th...
Name: ManuscriptTitle, dtype: object
6376    Manipulation of Hydrogen Binding Energy and De...

In [53]:
print('Total Papers: ', papers_df.shape[0])
print('Total suspicious paper titles: ', j)

Total Papers:  16685
Total suspicious paper titles:  2899

In [54]:
from langdetect import detect
import re

# Find where a group of author names have more than one citation
def group_papers(group):
    if group['ManuscriptTitle'].count() > 1:
        for i in group['ManuscriptTitle'].values:
            string = ''.join(re.findall(r"[a-zA-Z ]", i))
            
            # Looks for titles in German, searching for 'non-English' was giving too many English results
            # Specifically ignoring 'quantum diffusion of deuterium in gaas zn' since its in english but it determined to be german
            if detect(string) == 'de' and string != 'quantum diffusion of deuterium in gaas zn':
                return True
    else:
        return False
                
results = papers_df.groupby(['first_auth', 'second_auth', 'third_auth']).apply(group_papers)

In [55]:
for auth in results[results == True].index:
    f, s, t = auth
    test_df = papers_df[(papers_df['first_auth'] == f) & (papers_df['second_auth'] == s) & (papers_df['third_auth'] == t)]
    for i in test_df.index:
        if detect(test_df.loc[i, 'ManuscriptTitle']) == 'de':
            print('Dropping the paper:')
            print(test_df.loc[i, 'ManuscriptTitle'])
            papers_df = papers_df.drop(i)

Dropping the paper:
DIELECTRIC AND PIEZOELECTRIC PROPERTIES OF (K Na) NbO3BASED PIEZOELECTRIC CERAMICS
Dropping the paper:
Quantum diffusion of deuterium in GaAs Zn
Dropping the paper:
info doi/10.1002% 2Fange. 200351348 20210701 JJ 10.1002 J 10.1002 143 Angewandte ChemieAngew. Chem. 004482491521375711523Lutz H. GadeChristian H. GalkaRené M …
Dropping the paper:
info doi/10.1002% 2Fange. 200250164 20210630 JJ 10.1002 J 10.1002 143 Angewandte ChemieAngew. Chem. 004482491521375711516Johanna M. HaiderRené M. WilliamsLuisaDe …
Dropping the paper:
Adams MA see AV Belushkin Adams MA see R. Hempelmann Aldebert P. see S. Escribano Aldinger F. see GW Schafer
Dropping the paper:
Perowskitoxid‐Elektroden zur leistungsstarken photoelektrochemischen Wasserspaltung

In [59]:
# Find where a group of author names have more than one citation
def group_papers(group):
    if group['ManuscriptTitle'].count() > 1:
        print(group['ManuscriptTitle'].str.rstrip(' '))
        return group['ManuscriptTitle'].count()
    else:
        return 0
j = 0 
for group_name, group in papers_df.groupby(['first_auth', 'second_auth', 'third_auth']):
    i = group_papers(group)
    j += i

3577    Carrier diffusion lengths in hybrid perovskite...
3609    Pyrochlore to Fluorite Transition The Y2(Ti1–x...
Name: ManuscriptTitle, dtype: object
13895    Role of surface texturization on the gassensin...
13898    Role of surface passivating ligand and growth ...
Name: ManuscriptTitle, dtype: object
6185    Controlled Mixed Violet–Blue–Red Electrolumine...
6210    Resonance energy transfer from rhodamine 6G to...
Name: ManuscriptTitle, dtype: object
6199    Surface DefectRelated Luminescence Properties ...
6212    Metal conjugated semiconductor hybrid nanopart...
Name: ManuscriptTitle, dtype: object
15121    Coaxial nanofibers outperform uniaxial nanofib...
15125    New Ideas for Understanding the Structure and ...
Name: ManuscriptTitle, dtype: object
14419    Reducing the interfacial voltage loss in tin h...
14453    Interface characterization of allperovskite ox...
Name: ManuscriptTitle, dtype: object
14421    Highly symmetric Lewis base coordinated with S...
14422    Halogen engineering of 2D/3D tin halide perovs...
14424    Stabilizing CsPbBr3 perovskite quantum dots on...
14430    Effects of Fe3+ substitution on ZnAl layered d...
14439    Excellent disinfection and fluoride removal us...
14440    Semitransparent organic solar cells with light...
14442    An efficient and durable perovskite electrocat...
14444    Highly efficient layerbylayer deposition solar...
14445    Optical enhancement of nonstoichiometryinduced...
14446    Review on recent progress in hydrothermally sy...
14451    Microfluidic synthesis of metalorganic framewo...
Name: ManuscriptTitle, dtype: object
14429    Superhydrophobic high impact polystyrene (HIPS...
14447    Achieving direct electrophoretically deposited...
Name: ManuscriptTitle, dtype: object
14431    Aqueous miscible organic solvent treated NiTi ...
14437    Lasing operation in the CsPbBr3 perovskite mic...
14443    Evaluation of the production of biohydrogen du...
Name: ManuscriptTitle, dtype: object
14423    Recent promise of leadfree halide perovskites ...
14441    On the surface passivating principle of functi...
Name: ManuscriptTitle, dtype: object
12582    Chlorides other Halides and Pseudo‐Halides as ...
12596    Design of C3N4‐Based Hybrid Heterojunctions fo...
Name: ManuscriptTitle, dtype: object
14789    A novel way to characterize metalinsulatormeta...
14790    Using amorphous ZincTin Oxide alloys in the em...
Name: ManuscriptTitle, dtype: object
6990    Electron degeneracy and intrinsic magnetic pro...
7005    Microstrain sensitivity of orbital and electro...
Name: ManuscriptTitle, dtype: object
8565    Examination of growth kinetics of copper rich ...
8577    Impedance spectroscopy analysis of small molec...
Name: ManuscriptTitle, dtype: object
8537    Photoinduced charge separation and electron di...
8567    Efficiency and stability enhancement of laserc...
Name: ManuscriptTitle, dtype: object
8507    Photon management of combining nanostructural ...
8571    Electrical properties of patterned photoactive...
Name: ManuscriptTitle, dtype: object
8566    Bufferfree Cu (In Ga) Se2solar cells by nearsu...
8575    Improvement of photovoltaic performance of per...
Name: ManuscriptTitle, dtype: object
6537    Understanding the helical wrapping of poly (3h...
6538    Appealing perspectives of hybrid lead–iodide p...
Name: ManuscriptTitle, dtype: object
12289    Highly luminescent columnar ZnO films grown di...
12365    Hybridstructured indium tin oxide with Ag nano...
Name: ManuscriptTitle, dtype: object
10932    Local structure and excitations in systems wit...
10937    Mechanical properties of monolayer sulphides a...
Name: ManuscriptTitle, dtype: object
8194    Structural and oxygentransport studies of doub...
8261    Reliability of 3D Cs 2 M+ M 3+ X 6 type absorb...
8293    Photonic crystal‐driven spectral concentration...
Name: ManuscriptTitle, dtype: object
8208    A facile way for scalable fabrication of silve...
8241    Identifying the electrocatalytic active sites ...
Name: ManuscriptTitle, dtype: object
12719    Morphological and structural changes in reduci...
12723    Evidence of Plasmonic Induced Photocatalytic H...
Name: ManuscriptTitle, dtype: object
17352    Effect of conductive additive amount on electr...
17356    Recrystallized thinfilm silicon solar cell on ...
17358    Investigation on microstructures and thermophy...
Name: ManuscriptTitle, dtype: object
11921    An Xray scattering and electron microscopy stu...
11989    Microscopic and spectroscopic investigation of...
Name: ManuscriptTitle, dtype: object
15590    Atomicscale understanding of dichlorobenzeneas...
15591    Indole moiety induced biological potency in ps...
Name: ManuscriptTitle, dtype: object
4408    Peroptronic devices perovskitebased lightemitt...
4409    Machine learningassisted development of organi...
Name: ManuscriptTitle, dtype: object
12612    Coupled Near‐and Far‐Field Scattering in Silve...
12614    Broadband‐Emitting 2 D Hybrid Organic–Inorgani...
Name: ManuscriptTitle, dtype: object
15620    Synthesis single crystal Xray DFT spectroscopi...
15623    Investigation of electronic structure magnetic...
Name: ManuscriptTitle, dtype: object
15617    Structural spectral magnetic and dielectric pr...
15619    Syntheses crystal structures topology and dual...
Name: ManuscriptTitle, dtype: object
5934    Exploring the Limiting Open‐Circuit Voltage an...
5940    Hole Transporting Materials Development of Dop...
Name: ManuscriptTitle, dtype: object
11453    Etching of high aspect ratio structures in Si ...
12659    Graphene quantum dots/NiTi layered double hydr...
Name: ManuscriptTitle, dtype: object
5684    Exchange‐Coupled Bimagnetic Wüstite/Metal Ferr...
5710    Interfacing BiVO4 with Reduced Graphene Oxide ...
Name: ManuscriptTitle, dtype: object
13343    An insight into the local Oh→ Td instability i...
13345    Pressuredriven Phase Transition in CaFeAsF at ...
Name: ManuscriptTitle, dtype: object
13340    Application of lowvoltage backscattered electr...
13342    Thermal activated carrier transfer between InA...
Name: ManuscriptTitle, dtype: object
11923    Electromechanical tuning of nanoscale MIM diod...
11984    Effect of boron on formation of interstitial‐r...
11985    PbS nanocrystals in hybrid systems for solar c...
Name: ManuscriptTitle, dtype: object
3545    Formation of unsaturated hydrocarbons and hydr...
3548    Fabrication and postmodification of nanoporous...
Name: ManuscriptTitle, dtype: object
8076    Anisotropic ionic conductivity in fluorinated ...
8114    Enhanced performance via partial lead replacem...
8120    Hexagonal perovskite related oxide ion conduct...
8123    Temporal and spatial pinhole constraints in sm...
8145    Photoinduced degradation of methylammonium lea...
Name: ManuscriptTitle, dtype: object
11667    Partial inverse spinel structure of manganesed...
11697    Studying the role of CdS on the TiO2 surface p...
Name: ManuscriptTitle, dtype: object
8694    Difference in hot carrier cooling rate between...
8723    Selective fluorescence functionalization of dy...
Name: ManuscriptTitle, dtype: object
8706    Infrared emitting quantum dots DNA conjugation...
8710    Washinduced multicolor tuning of carbon nanodo...
Name: ManuscriptTitle, dtype: object
11870       Sevenlayered 2D hybrid lead iodide perovskites
11955    The effect of reducing dimensionality on the e...
11972    Memristive devices based on solution‐processed...
11974    Effect of nanoscale confinement on fluorescenc...
Name: ManuscriptTitle, dtype: object
15725    Electroluminescence and fluorescence emission ...
15730    Nexus approach to solar technology for energy ...
Name: ManuscriptTitle, dtype: object
16445    Structural Volume Changes upon Photoisomerizat...
16446    Transient absorption of copper selenide nanowi...
16457    Spectral properties of organosilicon polymer/S...
Name: ManuscriptTitle, dtype: object
6687    Highly UV Resistant Inch‐Scale Hybrid Perovski...
6690    Stacking Polymorphism in PtSe2 Drastically Aff...
Name: ManuscriptTitle, dtype: object
8505    The influence of drift fields in thin silicon ...
8506    Passivated contacts to laser doped p+ and n+ r...
8562    Tapered aluminumdoped vertical zinc oxide nano...
Name: ManuscriptTitle, dtype: object
16451     Photophysics of poly (pphenylene vinylene) films
16458    Correlation of Degradation of P3HT PCBM And P3...
Name: ManuscriptTitle, dtype: object
8004    Solvent vapour annealing of methylammonium lea...
8019    Emerging polyanionic and organic compounds for...
Name: ManuscriptTitle, dtype: object
16541    Porous NiYSZ planar anodes by powder extrusion...
16547    Processing of P/M M2 high speed steels by moul...
16551    Development of thermoelectric oxides for renew...
Name: ManuscriptTitle, dtype: object
15362    Nonfused medium bandgap electron acceptors for...
15369    Dimensionality regulation in tin halide perovs...
Name: ManuscriptTitle, dtype: object
3974    Hexagonal boron nitride selflaunches hyperboli...
3992    Nanoscale Architecture of Polymer–Organolead H...
Name: ManuscriptTitle, dtype: object
17600    FtIr And Computational Study Of Di2Pyridyl Ket...
17603    Photoluminescent and photocatalytic behaviour ...
Name: ManuscriptTitle, dtype: object
17602    A highly effective superfluid film breaker for...
17605    Rheology of fumed silica/polydimethylsiloxane ...
Name: ManuscriptTitle, dtype: object
10828    Correction Interface structure precursor rheol...
10882    Germanium coating boosts lithium uptake in Si ...
Name: ManuscriptTitle, dtype: object
14001    Generalised single particle models for highrat...
14068    The anomalous quasi isotropic [g] tensor found...
14069    Optical properties due to Cr4+ in oxides Densi...
14071    Magnetic properties of R3Rh2 compounds with R=...
Name: ManuscriptTitle, dtype: object
11838    Magneto‐optical Properties of Iron Oxide Nanoc...
11847    Dielectric and Raman spectroscopy measurements...
11930    Nanostructured Nbsubstituted CaMnO3 ntype ther...
Name: ManuscriptTitle, dtype: object
12021    Ionic Liquid‐Mediated α‐Fe2O3 Shape‐Controlled...
12035    Characterization of Charge States in Conductin...
Name: ManuscriptTitle, dtype: object
12000    InGaP//GaAs//CIGS 3‐junction spectrum‐splittin...
12003    Effect of inverted‐pyramid shape on light extr...
Name: ManuscriptTitle, dtype: object
11999    Excitonic and Free Carrier Recombination in In...
12002    Photoluminescence characteristics of organic m...
Name: ManuscriptTitle, dtype: object
10923    Excited state dynamics of BODIPYbased acceptor...
10929    Low electronpolar optical phonon scattering as...
Name: ManuscriptTitle, dtype: object
10323    Design of dendritic core carbazolebased hole t...
10328    Acidfunctionalized fullerenes used as interfac...
10363    Selfhealable electrochromic ion gels for low p...
10374    A simple engineering strategy with side chain ...
Name: ManuscriptTitle, dtype: object
5740    Low‐temperature‐processed colloidal quantum do...
5743    Editorial for the special issue Dimensionality...
Name: ManuscriptTitle, dtype: object
14584    Dry and wet etch processes for NiMnSb Heusler ...
14599    (Ln0. 5M0. 5) FeO3− δ Perovskites as Cathode f...
Name: ManuscriptTitle, dtype: object
10524    Charge injection and trapping at perovskite in...
10546    Rareearth quantum cutting in metal halide pero...
Name: ManuscriptTitle, dtype: object
4254    Pattern Formation of Silver Nanoparticles in 1...
4268    Switched‐On Progress Challenges and Opportunit...
4294    Hybrid Silicon‐Polymer Photodetector Engineere...
Name: ManuscriptTitle, dtype: object
13939    Green lightemitting diodes based on hybrid per...
13940             Plasmonic communications light on a wire
Name: ManuscriptTitle, dtype: object
13950    Ultrafast characterization of the electron inj...
13951    αFAPbI3 powder presynthesized by microwave irr...
Name: ManuscriptTitle, dtype: object
16158    Perovskite/polyethylene oxide composites Towar...
16163    Preparation sintering and electrochemical perf...
16166    The rattler effect of phonon propagation in de...
Name: ManuscriptTitle, dtype: object
674    Charge separation in type II tunneling multila...
702    Triazatruxenebased Hole Transporting Materials...
Name: ManuscriptTitle, dtype: object
13777    Yttrium (Y) doped ZnO nanowire/pSi heterojunct...
13781    Defectinduced magnetism in undoped wide band g...
13828    Magnetic and electronic properties of transiti...
13863    Environmentinduced reversible modulation of op...
Name: ManuscriptTitle, dtype: object
15718    Light induced damage and repair in nucleic aci...
15723    Improved power conversion efficiency for bulk ...
Name: ManuscriptTitle, dtype: object
8053    Lightinduced degradation of fullerenes in orga...
8084    Investigation of the photocorrosion of nGaP ph...
Name: ManuscriptTitle, dtype: object
14121                       Lithium insertion in La2MiO4+y
14133    An advance towards the synthesis of Ag nanorod...
Name: ManuscriptTitle, dtype: object
4968     TlP 5 an unexplored direct band gap 2D semicon...
16962    Synthesis characterization and optoelectronic ...
Name: ManuscriptTitle, dtype: object
5011    Porosity induced rigidochromism in platinum (i...
5058    Cadmium deoxycholate a new and efficient precu...
Name: ManuscriptTitle, dtype: object
4970     Novel IV–V–VI semiconductors with ultralow lat...
16963    Various coordination modes in mercury (II) com...
Name: ManuscriptTitle, dtype: object
16301    A comparative study on the performance of hybr...
16320    ZnO Nanoparticles Photosensitization Using Rut...
Name: ManuscriptTitle, dtype: object
16325    Electronic and magnetic properties of X2YZ and...
16326    Compensated half metallicity in osmium double ...
Name: ManuscriptTitle, dtype: object
10081    Timeresolved luminescence in conducting polyme...
10082    Production of nanometersize GaAs nanocristals ...
10092    Recent advances on the optical properties of E...
Name: ManuscriptTitle, dtype: object
15436    Perovskitelike ceramic hole transport material...
15453    Multifunctional highly efficient bipolar 9 9di...
Name: ManuscriptTitle, dtype: object
15431    Highperformance CsPbI3 perovskite solar cells ...
15489    Crystal Structures and PhaseTransitions Analys...
Name: ManuscriptTitle, dtype: object
15459    Interpenetrated Double PillaredLayer CoII MOFs...
15460    Endocyclic and Endo–Exocyclic Silver (i) Compl...
Name: ManuscriptTitle, dtype: object
12996    A nonvolatile memory device consisting of grap...
13003    Magnetic separation of colloidal nanoparticle ...
13006    Atomefficient synthesis of a benchmark electro...
13007    Core–shell structured TiO2@ polydopamine for h...
Name: ManuscriptTitle, dtype: object
8903    PLASMAS AND ELECTRICAL DISCHARGES (PACS 5152)M...
8904    Impedance spectroscopy of thinfilm CdTe/CdS so...
Name: ManuscriptTitle, dtype: object
1736    Defect Engineering Stabilized AgSbTe2 with Hig...
9354    Managing Phase Purities and Crystal Orientatio...
Name: ManuscriptTitle, dtype: object
16591    Cubic garnet solid polymer electrolyte for roo...
16596    Synthesis and physical properties of nanopowde...
Name: ManuscriptTitle, dtype: object
836     High Gravimetric and Volumetric Ammonia Capaci...
1023    Band engineering in core/shell ZnTe/CdSe for p...
Name: ManuscriptTitle, dtype: object
16104    Structural Chemistry of a New 10H Hexagonal Pe...
16113    Transition metal impurities in fluorides Role ...
16127    Optoelectronic properties of graphene quantum ...
Name: ManuscriptTitle, dtype: object
16136    Compatibility of DFT+ U with noncollinear magn...
16137    Efficacious symmetryadapted atomic displacemen...
Name: ManuscriptTitle, dtype: object
16106    Squeezing resulting from a fourthorder interac...
16114    Halide anions driven selfassembly of haloperfl...
Name: ManuscriptTitle, dtype: object
16078    Carrier signal injection alternatives for sens...
16107    Squeezing enhancement by competing nonlinearit...
Name: ManuscriptTitle, dtype: object
16546    Structure and mechanical properties of HSS HS6...
16549    Structure and reaction with lithium of tetrago...
16550    Thermal and mechanical characterization of inj...
Name: ManuscriptTitle, dtype: object
16542    Magnetic properties of Mgferrite after milling...
16548    Mechanical properties and pitting corrosion be...
Name: ManuscriptTitle, dtype: object
14692    Microplasmas technologies for engineering of s...
14701    Metal ion enhanced charge transfer in a terpyr...
Name: ManuscriptTitle, dtype: object
11493    Atomic layer deposition of germaniumseleniumte...
11575    Structural evolution of molybdenum disulfide p...
Name: ManuscriptTitle, dtype: object
11536    Determination of Carrier Diffusion Length Usin...
11578    Förster Resonance Energy Transfer Mediated Ch...
Name: ManuscriptTitle, dtype: object
11474    Tin dioxide as an alternative window layer for...
11476    Preface for the special topic collection comme...
11478                             Sixty years of diversity
11488    Atomic layer deposition of molybdenum disulfid...
11537            Ferromagnetism in 57Fe‐doped cupric oxide
11539              Nanowire–quantum‐dot–polymer solar cell
11542    Ab initio study of structural electronic elast...
11544    Dynamically Switching the Electronic and Elect...
11547    Inhomogeneous Broadening of Photoluminescence ...
11549    Graphene Membranes for Hall Sensors and Microp...
11554    Facile Deposition of Nb2O5 Thin Film as an Ele...
11555    Nitrogendoped graphene oxide electrocatalysts ...
11557    Heteroleptic NIREmitting YbIII/AnilateBased Ne...
11558    ColorTunable AllInorganic CsPbBr3 Perovskites ...
11561    Surface Functionalization of CsPbBr3 Νanocryst...
11649    Study of the La1/2+ 1/2xLi1/21/2xTi1xAlxO3 (0≤...
11651    Structural characterization and EXAFS wavelet ...
11661    Controlled synthesis of zerodimensional phasep...
Name: ManuscriptTitle, dtype: object
6551    Uncovering the SelfOrganized Nanowires on AuMo...
6608    Phase diagram of methylammonium/formamidinium ...
Name: ManuscriptTitle, dtype: object
17294        Spectrophotometric determination of hydrazine
17312    Elucidating DFT study on structural electronic...
Name: ManuscriptTitle, dtype: object
1192    Tracking photoexcited carriers in hybrid perov...
8822    Longitudinal carrier density profiling in semi...
Name: ManuscriptTitle, dtype: object
5227    Solvents for Processing Stable Tin Halide Pero...
5233    SizeDependent Lattice Structure and Confinemen...
Name: ManuscriptTitle, dtype: object
5184    Impact of layer thickness on the charge carrie...
5185    Degradation of highly alloyed metal halide per...
Name: ManuscriptTitle, dtype: object
5209    Improved morphology and efficiency of n–i–p pl...
5235    Suppressing cation migration in triplecation l...
Name: ManuscriptTitle, dtype: object
5219    Tailoring phase purity in the 2D/3D perovskite...
5220    Efficient exciton diffusion in organic bilayer...
Name: ManuscriptTitle, dtype: object
5226    Mesoporous electronselective contacts enhance ...
5234    Enhanced OpenCircuit Voltage of WideBandgap Pe...
Name: ManuscriptTitle, dtype: object
10645    Sputtered Zn (O S) for junction formation in c...
10646    Unambiguous Determination of Local Orientation...
10647    Facile Synthesis of NaBiS2 Nanoribbons as a Pr...
Name: ManuscriptTitle, dtype: object
5880    Effect of precursor solution aging on the crys...
5891    New Generation Hole Transporting Materials for...
Name: ManuscriptTitle, dtype: object
6000    A Smooth CH3NH3PbI3 Film via a New Approach fo...
6002    Exciton and Charge Carrier Dynamics in Highly ...
Name: ManuscriptTitle, dtype: object
13085    Disorder and polymorphism in Cu (ii)polyoxomet...
13088    Molecular crystals of 2amino1 3 4thiadiazole w...
Name: ManuscriptTitle, dtype: object
13272    First proofofprinciple of inorganic lead halid...
13274    Electrical and Optical Characterization of CsP...

1324    Linear Electro‐Optic Modulation in Highly Pola...
1481    Artificial chemist an autonomous quantum dot s...
Name: ManuscriptTitle, dtype: object
11521    Pressure‐induced insulator–metal transition in...
11615    Doping and defect engineering induced extremel...
Name: ManuscriptTitle, dtype: object
11621    Hopping and tunnelling of D trapped by substit...
11627    Elastic and anelastic properties of Marval 18 ...
Name: ManuscriptTitle, dtype: object
6901    Tuning the Electrical and Thermoelectric Prope...
6916    Programmable devices based on reversible solid...
6920    A thin and flexible scanner for fingerprints a...
6928    Controlling the early stages of pentacene grow...
6942    Ferromagnetism in dilute magnetic semiconducto...
6945    Tunable magnetic interaction at the atomic sca...
Name: ManuscriptTitle, dtype: object
6899    Verification of TypeA and TypeBHC Blinking Mec...
6915    Unipolar barrier photodetectors based on van d...
6918    Efficient lightemitting diodes from mixeddimen...
Name: ManuscriptTitle, dtype: object
6914    Bidirectional optical signal transmission betw...
6929    Investigating molecular charge transfer comple...
Name: ManuscriptTitle, dtype: object
6925    Intermolecular hybridization governs molecular...
6926            Band bending in conjugated polymer layers
Name: ManuscriptTitle, dtype: object
3221    Enhancing the photocatalytic performance of MX...
3232    Laurionite Competes with 2D Ruddlesden–Popper ...
Name: ManuscriptTitle, dtype: object
1386    How to quantify the efficiency potential of ne...
1395    Blue Light‐Emitting Devices Based on Novel Pol...
1463    Amplified Spontaneous Emission from CoreSeeded...
Name: ManuscriptTitle, dtype: object
1329    Controlled Crystal Plane Orientations in the Z...
1333    Solvent‐Assisted Kinetic Trapping in Quaternar...
1334    Solar Cells Overcoming the Ambient Manufactura...
Name: ManuscriptTitle, dtype: object
15863    Carbazole Electroactive Amorphous Molecular Ma...
15864    Impact of widebandgap technology on renewable ...
Name: ManuscriptTitle, dtype: object
16895    Effect of Ydoped NbB2. 5 on structural and sup...
16897    Study of Halfmetallic Properties of Co2YGe (Y ...
16903    Catalytic abatement of CO species from incompl...
Name: ManuscriptTitle, dtype: object
16874    Anomalous H/sub c/in CoCrfilms surface and bul...
16880    Effect of interdot distance on magnetic behavi...
Name: ManuscriptTitle, dtype: object
8401     Transparent Light‐Emitting Electrochemical Cells
8436    Operationally Stable Perovskite Light Emitting...
Name: ManuscriptTitle, dtype: object
6793    Formation of charged ferroelectric domain wall...
6827    Mitigation of acylhomoserine lactone (AHL) bas...
Name: ManuscriptTitle, dtype: object
6784    Anomalous exchange bias at collinear/noncollin...
6786    Longrange electronic reconstruction to a dxz y...
6798    Highperformance flexible supercapacitors obtai...
6802    Dramatic changes in thermoelectric power of ge...
6803    Author Correction Discovery of Fe7O9 a new iro...
6804    Xray scintillation in lead halide perovskite c...
6812    Deposition of topological silicene germanene a...
6814    Spatiotemporal behaviour of atomicscale triboc...
6818    Copper sulfide nanoparticles as highperformanc...
6835    Ultrafast energy transfer in ultrathin organic...
6836    Role of 2D and 3D defects on the reduction of ...
6838    Optical band gap alteration of graphene oxide ...
Name: ManuscriptTitle, dtype: object
6800    Metal halide solidstate surface treatment for ...
6806    Evidence for photoinduced charge separation be...
6825    Physicochemical properties and catalytic activ...
Name: ManuscriptTitle, dtype: object
14135    Optimized Fedoped ZnO nanoparticles for magnet...
14136    Quantitative comparison between different meth...
14150    Fabrication of perovskite solar cells in ambie...
14206    Synthesis crystal growth and characterization ...
Name: ManuscriptTitle, dtype: object
10978    Dynamic doping and degradation in sandwichtype...
10981    Ultrafast multiexponential electron injection ...
Name: ManuscriptTitle, dtype: object
9809    Colloidal quantum dot solar cell band alignmen...
9824    Perovskite Quantum Dot Solar Cells Fabricated ...
Name: ManuscriptTitle, dtype: object
4732     Turning the Tap Conformational control of quan...
13468    Alloying nanoparticles by discharges in liquid...
Name: ManuscriptTitle, dtype: object
4302    Rudorffites and Beyond Perovskite‐Inspired Sil...
4719    Thin‐Film Transformation of NH4PbI3 to CH3NH3P...
Name: ManuscriptTitle, dtype: object
14825    Boron emitters Defects at the siliconsilicon d...
14874    Structural properties of CdTe and ZnTe thin fi...
Name: ManuscriptTitle, dtype: object
14822    Introduction of negative charges in nitride fo...
14824    The thermal stability of atomic H plasma produ...
Name: ManuscriptTitle, dtype: object
14852    Optimizing carbon nanotube contacts for use in...
14889    Letidaffected cells from a utilityscale photov...
Name: ManuscriptTitle, dtype: object
14820    Investigation of lifetime degradation of RIEpr...
14845    Continuous Flash Sublimation of Inorganic Hali...
14850    Smallarea Passivated Contact monoPolyTM Silico...
Name: ManuscriptTitle, dtype: object
14830    Insitu observation of moistureinduced degradat...
14843      Perovskite PV Design for Stable Space Operation
Name: ManuscriptTitle, dtype: object
4647    Triplet Acceptors with a D‐A Structure and Twi...
4660    On the Location of Li+ Cations in the Fast Li‐...
Name: ManuscriptTitle, dtype: object
1161    Fast electron and slow hole relaxation in InPb...
8752    The role of grain boundary character in solute...
Name: ManuscriptTitle, dtype: object
10414    Is the Verwey transition in Fe3O4 magnetite dr...
12261    H2/D2 isotopic exchange A tool to characterize...
Name: ManuscriptTitle, dtype: object
6079    Enhanced photoluminescence of halide perovskit...
6140    Integer charge transfer and hybridization at a...
Name: ManuscriptTitle, dtype: object
12502    Interpretation of the photoluminescence decay ...
12514    Fluorescence quenching by charge carriers in i...
Name: ManuscriptTitle, dtype: object
14290    Simulation of a spintronic transistor A study ...
14309    A first principles study of Nd doped cubic LaA...
Name: ManuscriptTitle, dtype: object
1941    Efficient electrosynthesis of npropanol from c...
1993    HighDensity Nanosharp Microstructures Enable E...
Name: ManuscriptTitle, dtype: object
4162    Dynamic Redistribution of Mobile Ions in Perov...
4172    Photocurrent extraction efficiency near unity ...
Name: ManuscriptTitle, dtype: object
15836    Q1DPolarons in Rigid Boundary Cylindrical Wire...
15837                                 Magic gold nanotubes
15839     Confined Bipolarons in the Strong Coupling Limit
15841    Tailoring the magnetic anisotropy of cobaltgol...
15844    Pseudo jahn‐teller origin of bending distortio...
Name: ManuscriptTitle, dtype: object
10413      Thermal expansion of monogermanides of 3dmetals
12252    Impact of ceriumbased support oxides in cataly...
Name: ManuscriptTitle, dtype: object
12753    Samarium vanadate affixed sulfur self doped gC...
12754    Paper based biofuel cells Incorporating enzyma...
Name: ManuscriptTitle, dtype: object
12772    Hydrogen effects on electrochemically charged ...
12776    Thermal decomposition of titanium hydrides in ...
Name: ManuscriptTitle, dtype: object
2081    Polaron stabilization by cooperative lattice d...
2089    Quantum Dot Size Dependent J−V Characteristics...
Name: ManuscriptTitle, dtype: object
5688    Fuel Cells Infiltrated NiCo Alloy Nanoparticle...
5708    Flexible Broadband Graphene Photodetectors Enh...
Name: ManuscriptTitle, dtype: object
2047    Epitaxyenabled vapor–liquid–solid growth of ti...
2105    Selectivearea epitaxy of pure wurtzite InP nan...
2108    Polaritydriven 3fold symmetry of GaAs/AlGaAs c...
Name: ManuscriptTitle, dtype: object
12566    Effect of addition on Y2O3 in ZrO2 support on ...
12567    Hydrogenation of dimethyl adipate over bimetal...
Name: ManuscriptTitle, dtype: object
10143    Charge transfer versus molecular conductance m...
10228    6‐1 Invited Paper Measuring Health Parameters ...
Name: ManuscriptTitle, dtype: object
7135    Nanocrystalline/microcrystalline materials bas...
7152    Spinglass behaviour in the double perovskite “...
7182    Doping of C 60 (sub) monolayers by Fermilevel ...
Name: ManuscriptTitle, dtype: object
1432    Localized electrons enhanced ion transport for...
1434    Electrode engineering in halide perovskite ele...
Name: ManuscriptTitle, dtype: object
4395    Performance limitations imposed by the TCO het...
4414    Sub150 C processed mesosuperstructured perovsk...
Name: ManuscriptTitle, dtype: object
11095    Special Issue Advanced Spectroscopies of Molec...
11096    Secondary electron spectra of semicrystalline ...
Name: ManuscriptTitle, dtype: object
6082    Surface electronic structure of hybrid organo ...
6090    Bane of HydrogenBond Formation on the Photoind...
Name: ManuscriptTitle, dtype: object
5065    Mechanistic studies of CsPbBr 3 superstructure...
6483    Unravelling the role of surface traps on carri...
6949    Coherent transfer of spin through a semiconduc...
Name: ManuscriptTitle, dtype: object
3526     Robust Antiferromagnetism and Structural Disor...
13754    Surfactantinduced anion exchange and morpholog...
Name: ManuscriptTitle, dtype: object
9467    Lightemitting electrochemical cells recent pro...
9488    Microgrinding of lensed fibers by means of a s...
Name: ManuscriptTitle, dtype: object
16875    Evolution of structural and magnetic propertie...
16881    Magnetic domains of floppy disks and phone car...
16896    A firstprinciples study of the electronic mech...
Name: ManuscriptTitle, dtype: object
2054    Wide Spectral Photoresponse of Layered Platinu...
2106    Ultralow surface recombination velocity in InP...
Name: ManuscriptTitle, dtype: object
11411    Benefit from photon recycling at the maximumpo...
12658    Hydrogen production through oxidative steam re...
Name: ManuscriptTitle, dtype: object
11403    Perspectives on designer photocathodes for xra...
12657    Magnesium tuned triple conductivity and bifunc...
Name: ManuscriptTitle, dtype: object
4054    Understanding the origin of the 535 nm emissio...
4055    Correlating structure with function in thermal...
4058    Monitoring the Formation of a CH3NH3PbI3–xClx ...
Name: ManuscriptTitle, dtype: object
3972    Ultrafast Electron Injection from Photoexcited...
3977    Vibrationally assisted intersystem crossing in...
Name: ManuscriptTitle, dtype: object
4030    Direct Observation of Conductive Polymer Induc...
4052    Overcoming the Cut‐Off Charge Transfer Bandgap...
Name: ManuscriptTitle, dtype: object
10142    Progress highlights and perspectives on NiO in...
10191    Highthroughput parallelized testing of membran...
10267    Photophysical properties of Au‐CdTe hybrid nan...
Name: ManuscriptTitle, dtype: object
13983    Optimization of high potential cathode materia...
13990    Photovoltaic properties of Bi2S3 and CdS quant...
13997    Enhancing energy efficiency and longterm durab...
14010    Effect of Dy on electrochemical supercapacitiv...
14036    Enhanced photocatalysis by coupling of anatase...
14039    Preparing of highly conductive patterns on fle...
14072    Evidence of the spin Seebeck effect in NiZn fe...
14073    Ground state electronic and magnetic propertie...
14104    Efficient colloidal route to pure phase kester...
14105    Transition from CZTSe to CZTS via multicompone...
Name: ManuscriptTitle, dtype: object
13965    Electrochemical deposition of thick iron oxide...
14005    Hybrid potentiodynamic/potentiostatic electrod...
14007    The influence of water on the charge transport...
14087    First principle analysis of the structural ele...
14088    Structural magnetic magnetocaloric and critica...
14089    Effect of carrier transfer on the PL intensity...
Name: ManuscriptTitle, dtype: object
13964    Prediction of the electrodeposition process be...
14084    Electronic structure elastic mechanical thermo...
Name: ManuscriptTitle, dtype: object
13960    Oxygen reduction reaction on electrodeposited ...
13961    Electrodeposition of Cudoped ZnO nanowire arra...
13962    Some electrocatalytic properties of anodic iri...
13968    Dyesensitized solar cells based on TiO2 nanotu...
13994    Enhancement of photovoltaic performance and mo...
14002    Onepot electrochemical synthesis of CdTe quant...
14006    Morphological modulation of polypyrrole thin f...
14019    Facile synthesis of tin oxide hollow nanoflowe...
14090    Identification of hydrogen related defects in ...
14114        Mechanochemical treatment of Mgferrite powder
14116    The log (σ) vs. log (ω) derivative plot used t...
Name: ManuscriptTitle, dtype: object
13975    Opening the door to liquidfree polymer electro...
13985    Polybenzimidazole/strontium cerate nanocomposi...
13998    Fabricating CuS counter electrode for quantum ...
14022    Electrospun Networks of ZnOSnO2 Composite Nano...
14026    GaN Schottky metal–semiconductor–metal UV phot...
14078    Magnetic and structural studies of the double ...
14079    Structural and electronic properties of the na...
Name: ManuscriptTitle, dtype: object
13959         Temperature effects on ZnO electrodeposition
13987    Monolayers of choline chloride can enhance des...
Name: ManuscriptTitle, dtype: object
13979    Influence of iodine concentration on the photo...
14008    The deepDRT A deep neural network approach to ...
Name: ManuscriptTitle, dtype: object
13981    Evidence for enhancing charge collection effic...
14009    Study of oxygen electrode reactions on symmetr...
Name: ManuscriptTitle, dtype: object
14106    Strain effects on optical properties of tetrap...
14107    Modeling and analysis of HTMfree perovskite so...
Name: ManuscriptTitle, dtype: object
13993    Regulation of microstructure and composition o...
14044    Optical properties of an exciton bound to an i...
Name: ManuscriptTitle, dtype: object
5044    Efficient Perovskite LightEmitting Diodes Base...
5045    Quantifying Electrochemical Losses in Perovski...
5046    Enhanced light harvesting through Förster reso...
Name: ManuscriptTitle, dtype: object
6016    Strategic Halogen Substitution to Enable High‐...
6036    Graphene‐based electron transport layers in pe...
Name: ManuscriptTitle, dtype: object
11733    Dielectric and nonohmic properties of Ca2Cu2Ti...
11802    Development of molten nitrate salt based nanof...
11803    Optical Sensor Sensitivity Enhancement by Use ...
11804    Effects of particle hardness on shear thickeni...
Name: ManuscriptTitle, dtype: object
4973    Quantifying the composition dependency of the ...
4974    New twodimensional Ge–Sb–Te semiconductors wit...
Name: ManuscriptTitle, dtype: object
7436    Mobility and decay kinetics of charge carriers...
7448    Microscopic description of the phase separatio...
Name: ManuscriptTitle, dtype: object
7389    Ionimplantationinduced extended defect formati...
7441    Firstprinciples calculations of the thermodyna...
7450       Outofplane excitons in twodimensional crystals
7472      Anomalous Nernst effect of Fe3O4 single crystal
Name: ManuscriptTitle, dtype: object
12084    Characterization of nanostructures fabricated ...
12086    Two broad absorption bands in infrared atmosph...
Name: ManuscriptTitle, dtype: object
8601    Resonant silicon nanoparticles for enhancement...
8674    Ultrathin Ta 2 O 5 electronselective contacts ...
Name: ManuscriptTitle, dtype: object
17249    The impact of kaolin dehydroxylation on the po...
17250    A comparative study of the mechanical integrit...
Name: ManuscriptTitle, dtype: object
3896     Extent of Shallow/Deep Trap States beyond the ...
11262    Investigation of charge transport and band ali...
Name: ManuscriptTitle, dtype: object
11265    Tunable electronic and magnetic properties of ...
11269    Twodimensional XY monolayers (X= Al Ga In; Y= ...
Name: ManuscriptTitle, dtype: object
11273    Sizedependent selectivity and activity of high...
11277    Photocatalytic activity of Ndoped anatase grow...
Name: ManuscriptTitle, dtype: object
11263    Preparation of (Ba0. 5Sr0. 5) TiO3 thin films ...
11266    Adsorption of habitat and industryrelevant mol...
11267    Abinitiodriven prediction of puckered pentalik...
Name: ManuscriptTitle, dtype: object
14147    Laserbased series interconnection of chalcopyr...
14159     Optical properties of PVP/Li3GaO3 nanocomposites
14183    Growth and characterization of sodium sulfanil...
Name: ManuscriptTitle, dtype: object
851               Cu–In halide perovskite solar absorbers
5595    Quantumdot double layer polymer waveguides by ...
Name: ManuscriptTitle, dtype: object
4012    High‐Quality Photonic Crystals Infiltrated wit...
4016    Nanostructured architectures for biomolecular ...
Name: ManuscriptTitle, dtype: object
4022    High fill factor and open circuit voltage in o...
4024    Intrinsic surface dipoles control the energy l...
Name: ManuscriptTitle, dtype: object
4013    Donor–Acceptor C60‐Containing Polyferrocenylsi...
4014    Spatial collection in colloidal quantum dot so...
4038    Nongeminate recombination and charge transport...
4047    Suppression of the Keto‐Emission in Polyfluore...
Name: ManuscriptTitle, dtype: object
13474    Routes to tin chalcogenide materials as thin f...
13480    pHInduced Surface Modification of Atomically P...
Name: ManuscriptTitle, dtype: object
10197    ARS process to nanocrystalline BaMxAl12xO19δ (...
10222    P‐26 Thermally Annealed Asymmetric‐Offset Poly...
Name: ManuscriptTitle, dtype: object
6857    Theoretical prediction of twodimensional BC2X ...
6894    Photocatalytic generation of hydrogen by cores...
Name: ManuscriptTitle, dtype: object
14035    Magnetic properties of superparamagnetic nanop...
14067    Pressureinduced phase transitions in Si observ...
Name: ManuscriptTitle, dtype: object
14032    The role of intrinsic and surface states on th...
14033    Sequentially vaporgrown hybrid perovskite for ...
Name: ManuscriptTitle, dtype: object
14137    Photocatalytic degradation of Rhodamine dyes u...
14138    Mechanical measurements of pure and kaolin rei...
14140    Synthesis and characterization of sol–gel deri...
Name: ManuscriptTitle, dtype: object
14839    Solar cells based on colloidal quantum dot sol...
14871    Energy yield potential of perovskitesilicon ta...
14872    Introduction of Sb in CDTE and its effect on C...
Name: ManuscriptTitle, dtype: object
6405    Onestep microheterogeneous formation of rutile...
6407    Ternary Phase Diagrams of MAI–PbI2–DMF and MAI...
Name: ManuscriptTitle, dtype: object
826     Operational Mechanism of Conjugated Polyelectr...
5575    Protein Adsorption on Nanocrystalline TiO2 Fil...
Name: ManuscriptTitle, dtype: object
14571    The effect of LPCVD silicon nitride deposition...
14572    Characterization of the Si− SiO2 Interface Fol...
Name: ManuscriptTitle, dtype: object
6489    Effect of surface stoichiometry on blinking an...
6498    Photoluminescence Saturation in QuantumCutting...
Name: ManuscriptTitle, dtype: object
6488    Ultrafast manyparticle phenomena in lead bromi...
6581    Extending the compositional space of mixed lea...
6635    Investigating spatiotemporal correlation of mu...
Name: ManuscriptTitle, dtype: object
17533    The Influence of ginger spent loading on mecha...
17535    Graphene nanoplatelets polyvinyl alcohol nanoc...
Name: ManuscriptTitle, dtype: object
15643    Filterless spectral splitting perovskite–silic...
15645    Characterization of MAEtextured nanoporous sil...
Name: ManuscriptTitle, dtype: object
1593    A hard oxide semiconductor with a direct and n...
1594    Perovskites A Hard Oxide Semiconductor with A ...
Name: ManuscriptTitle, dtype: object
16404    A Review of 2D Perovskites and CarbonBased Nan...

2302    PbS quantum dot electroabsorption modulation a...
2313    Measurement of the phase shift upon reflection...
Name: ManuscriptTitle, dtype: object
2191    Switchable Plasmonic Metasurfaces with High Ch...
2241    Longterm stability and optoelectronic performa...
Name: ManuscriptTitle, dtype: object
3763     Role of structural distortion in stabilizing e...
3779     Photogeneration and mobility of charge carrier...
13371    Carbon at the Ti site in strontium titanate fr...
Name: ManuscriptTitle, dtype: object
4308    Self‐Assembled Quasi‐3D Nanocomposite A Novel ...
4724    Engineering of CH3NH3PbI3 Perovskite Crystals ...
Name: ManuscriptTitle, dtype: object
14318    Robust stability halfmetallic ferrimagnetism a...
14332    Tuning magnetic properties of noncollinear mag...
Name: ManuscriptTitle, dtype: object
14366    Fully printable perovskite solar cells with hi...
14367    On the Relation between Chemical Composition a...
Name: ManuscriptTitle, dtype: object
1441           Graphene‐based microwave circuits a review
1444    AFM‐Based Hamaker Constant Determination with ...
1445    Toward efficient carbon nitride photoelectroch...
Name: ManuscriptTitle, dtype: object
1207    A photonic crystal laser from solution based o...
1279    Efficient infrared‐emitting PbS quantum dots g...
8765    Selftrapped exciton emission in an Sn (II)dope...
Name: ManuscriptTitle, dtype: object
1144    Xray Lithography on Perovskite Nanocrystals Fi...
8748    Surface band bending and carrier dynamics in c...
Name: ManuscriptTitle, dtype: object
11503    Optimization of electrochemically grown dense ...
11598    Polarization Resistance‐Free Mn3O4‐Based Elect...
Name: ManuscriptTitle, dtype: object
11565    Reverse micelle templating route to ordered mo...
11566    Colloidal Continuous Injection Synthesis of Fl...
11567    Effects of Oxygen Plasma on the Chemical Light...
11600    Probing the 3‐step Lithium Storage Mechanism i...
Name: ManuscriptTitle, dtype: object
10800    Acetonitrile based single step slotdie compati...
10802    The ultralow thermal conductivity and tunable ...
10803    Visiblelight photocatalytic activity of nitrog...
Name: ManuscriptTitle, dtype: object
3181    Siliconized triarylamines as redox mediator in...
3195    Detection of Au+ Ions During Fluorine GasAssis...
Name: ManuscriptTitle, dtype: object
9942    Influence of the InAs coverage on the phononas...
9946    Growth mechanisms and band bending in Cu and P...
Name: ManuscriptTitle, dtype: object
574     Solutionprocessed perovskite light emitting di...
4632        Piezoelectricity in two‐dimensional materials
Name: ManuscriptTitle, dtype: object
237    Programming the detection limits of biosensors...
290       Achromatic polarization control in the visible
Name: ManuscriptTitle, dtype: object
3265    ThicknessDependent Domain Relaxation Dynamics ...
3301    Controlling C60 Organization through DipoleInd...
Name: ManuscriptTitle, dtype: object
12266    Special Issue Section 2 Recent trends in C1C4 ...
12353    Effect of TiO2 antireflection layer with vario...
12418    Fullerene based electron transporting layers f...
Name: ManuscriptTitle, dtype: object
5951    MXene‐contacted silicon solar cells with 11.5%...
6034    Perovskite Solar Cells Stabilization of Precur...
Name: ManuscriptTitle, dtype: object
6373    Temperaturedependent excitonic decay and multi...
6374    Longlived charge separation at heterojunctions...
Name: ManuscriptTitle, dtype: object
2634    Colossal tuning of an energy gap in Sn2P2S6 un...
2737    Sidetoside alignment of gold nanorods with pol...
Name: ManuscriptTitle, dtype: object
9084    Organic lightemitting devices with silicon anodes
9111    Magnetic and transport characteristics of long...
Name: ManuscriptTitle, dtype: object
877    Correlating ChargeTransfer State Lifetimes wit...
880    Tailorable indirect to direct bandgap double p...
Name: ManuscriptTitle, dtype: object
577    Suppressing phase disproportionation in quasi2...
580    Bond engineering of molecular ferroelectrics r...
Name: ManuscriptTitle, dtype: object
12695    Surface mobility and reactivity of oxygen spec...
12701    Effects of dispersion and partial reduction on...
Name: ManuscriptTitle, dtype: object
4921    Dynamically controlled growth of Cu–Mo–O nanos...
4922    Correction Chlorinedoped SnO 2 hydrophobic sur...
Name: ManuscriptTitle, dtype: object
10119    Polymer Quantum DotSensitized Solar Cell Incor...
10121    Fabrication of ThreeDimensional SingleWalled C...
Name: ManuscriptTitle, dtype: object
8586    > 85% indium reduction for highefficiency sili...
8619    Investigation of high contrast and reversible ...
Name: ManuscriptTitle, dtype: object
12860    A high temperature neutron diffraction study o...
12877    Phase transitions in the hexagonal tungsten br...
Name: ManuscriptTitle, dtype: object
12855    An investigation of the optical properties and...
12899                    IN SITU REDUCTION OF (100) SRTIO3
Name: ManuscriptTitle, dtype: object
3640     Charge Transfer Absorption and Emission at ZnO...
13465    γ‐Valerolactone A Nontoxic Green Solvent for H...
Name: ManuscriptTitle, dtype: object
2227    Ultrafast imaging of carrier cooling in metal ...
2231     Mixedhalide perovskites with stabilized bandgaps
Name: ManuscriptTitle, dtype: object
2906     Unraveling the elastic properties of (quasi) t...
13588    Transition Metal Complexes Coupled to Vacancie...
Name: ManuscriptTitle, dtype: object
8854    Hole injection in triarylamine containing poly...
8921    Carrier recombination losses in inverted polym...
Name: ManuscriptTitle, dtype: object
12152    LongLived Mobile Charge Carriers Formed on Pho...
12187    Nonthermal plasma synthesis of metal sulfide n...
Name: ManuscriptTitle, dtype: object
15542    Potentialassisted assembly of functionalised p...
15543    Reversible binding of molecular dioxygen to Co...
Name: ManuscriptTitle, dtype: object
12166    Aggregationinduced dual emission and unusual l...
12170    Liquid crystalline polyfluorenes for blue pola...
Name: ManuscriptTitle, dtype: object
2913     Extrinsic effects on the optical properties of...
13589    Ab initio and experimental studies of the larg...
Name: ManuscriptTitle, dtype: object
6050    The impact of local work function variations o...
6051    Unraveling the Microstructure of Molecularly D...
Name: ManuscriptTitle, dtype: object
9982    Aluminum oxide as a dualfunctional modifier of...
9988    Coking suppression in solid oxide fuel cells o...
Name: ManuscriptTitle, dtype: object
9983    Lithium and lanthanum promoted NiAl2O3 as an a...
9987    Cogeneration of electricity and syngas on prot...
Name: ManuscriptTitle, dtype: object
12133    Rigidrodlike main chain polymers with rigidly ...
12140    Enhanced electrical conductivity of molecularl...
Name: ManuscriptTitle, dtype: object
8458    Ethylene glycol as a new sustainable fuel for ...
8550    Freestanding colored polymer film with composi...
Name: ManuscriptTitle, dtype: object
8472    Grain size dependence of degradation of alumin...
8475    A regioregular head to tail thiophene based “d...
Name: ManuscriptTitle, dtype: object
9288    Large scale ultravioletbased nanoimprint litho...
9289    Precision material modification and patterning...
9321    Thirdorder optical nonlinearity and figure of ...
9323    Structural and electrical conductivity studies...
9327    Textured BaTiO3 by templated grain growth and ...
Name: ManuscriptTitle, dtype: object
9297    Impact of supercritical  drying on roughness o...
9318    Spectroscopic ellipsometry study of FAxMA1−xPb...
9340    Strain engineering of piezoelectric properties...
9341    Silk fibroin protein as dual mode picric acid ...
9342    Towards highperformance hybrid hydrophilic mem...
9343    Solution‐Processed In2O3/ZnO Heterojunction El...
Name: ManuscriptTitle, dtype: object
12748    Role of copper content and calcination tempera...
12749     Optimized CuO–CeO2 catalysts for COPROX reaction
Name: ManuscriptTitle, dtype: object
7213    Raman scattering in strongly coupled organic s...
7216    Imaging the polariton relaxation bottleneck in...
Name: ManuscriptTitle, dtype: object
9762    Bandwidth limits of luminescent solar concentr...
9764    Ultrafast and broadband photodetectors based o...
Name: ManuscriptTitle, dtype: object
14908    Illuminated outdoor luminescence imaging of ph...
14909                   Prospects for perovskites in space
Name: ManuscriptTitle, dtype: object
11193    Solventfree solidstate synthesis of high yield...
11198    Shaping Tin Nanocomposites through Transient L...
11199    Multilayered Barium and Strontium Carbonate St...
Name: ManuscriptTitle, dtype: object
280      Tunable roomtemperature singlephoton emission ...
13568    Structural Diversity in Layered Hybrid Perovsk...
Name: ManuscriptTitle, dtype: object
1041    Noninjection gramscale synthesis of monodisper...
1049    DefectInduced in Situ Atomic Doping in Transit...
Name: ManuscriptTitle, dtype: object
9979    A NiFeCu alloy anode catalyst for directmethan...
9984    A comprehensive evaluation of a Ni–Al2O3 catal...
Name: ManuscriptTitle, dtype: object
9304    Formation and removal of composite halogenated...
9309    Modulationdoped ZnSe/(Zn Cd Mn) Se quantum wel...
Name: ManuscriptTitle, dtype: object
3530    Robotaccelerated perovskite investigation and ...
3610    Flexible Composite Energy Harvesters from Ferr...
Name: ManuscriptTitle, dtype: object
2663    Tuning the interfacial charge orbital and spin...
2665              Stable halfmetallic monolayers of FeCl2
Name: ManuscriptTitle, dtype: object
17007    Synthesis and Characterization of Poly Vinyl A...
17016    Theoretical and experimental studies on microc...
Name: ManuscriptTitle, dtype: object
1238    Extrinsic and dynamic edge states of twodimens...
8772    A molecular approach to an electrocatalytic hy...
Name: ManuscriptTitle, dtype: object
5476    Direct electrochemistry and nitric oxide inter...
5477    Factors that affect protein adsorption on nano...
Name: ManuscriptTitle, dtype: object
14139    Hydroxyapatite ceramics prepared from two natu...
14165    Cu (II) ions removal from water by charcoal ob...
Name: ManuscriptTitle, dtype: object
14154    Role of precursors on photocatalytic behavior ...
14156    High quantum yield CdSe/ZnS/CdS/ZnS multishell...
Name: ManuscriptTitle, dtype: object
16186    Tailoring the magnetic hyperthermia performanc...
16198    Colossal dielectric response and relaxation pr...
16399    Comparison of Semiconducting and Metallic Carb...
Name: ManuscriptTitle, dtype: object
2540    STRUCTURAL MECHANICAL THERMODYNAMIC AND OPTICA...
2556    Domain wall pinning contribution to the nonlin...
Name: ManuscriptTitle, dtype: object
7711    Optimizing solidstate ligand exchange for coll...
7725    Impact of perovskite/silicon tandem module des...
Name: ManuscriptTitle, dtype: object
10215    62‐9 Invited Paper Hybrid Composite Films with...
10217    P‐4.2 Reducing Chromaticity Shifts of Light Em...
Name: ManuscriptTitle, dtype: object
8542     Phonon lifetimes in model quantum dot superlat...
13530    Group 12 Metal Complexes of an 18Membered N2O2...
Name: ManuscriptTitle, dtype: object
5494    Tungsten work function engineering for dual me...
5633    The impact of grain alignment of the electron ...
Name: ManuscriptTitle, dtype: object
5550    Dielectric properties of bismuth niobate films...
5732    An Air Knife–Assisted Recrystallization Method...
Name: ManuscriptTitle, dtype: object
17114    Development of poly (urethaneester) amide from...
17121    Application of multidimensional (0D 1D 2D) nan...
Name: ManuscriptTitle, dtype: object
1356    Evidence for physisorption of aluminum on the ...
1534    Shelf‐Stable Quantum‐Dot Light‐Emitting Diodes...
Name: ManuscriptTitle, dtype: object
8215    Surface modification via selfassembling large ...
8226    Roadmap and roadblocks for the band gap tunabi...
Name: ManuscriptTitle, dtype: object
16563    Optimization of the Processing of 8‐YSZ Powder...
16629    Electronbeaminduced cracking in organicinorgan...
Name: ManuscriptTitle, dtype: object
9078    Theoretical calculation of the vibrational and...
9081    Direct optical transitions at K and Hpoint of ...
Name: ManuscriptTitle, dtype: object
9059    Experimental and firstprinciples investigation...
9072    Scanning microwave microscopy and scanning cap...
Name: ManuscriptTitle, dtype: object
9109    Strain effects on magnetic characteristics of ...
9116    Symmetry dependent optoelectronic properties o...
Name: ManuscriptTitle, dtype: object
713    Mechanism of charge migration through DNA mole...
714    Effect of structural dynamics on charge transf...
Name: ManuscriptTitle, dtype: object
8394    Doubly stabilized perovskite nanocrystal lumin...
8405    Water An Influential Agent for Lanthanide‐Dope...
Name: ManuscriptTitle, dtype: object
8947    Leadfree hightemperature dielectrics with wide...
8959    Crystal structure and domain‐wall contribution...
Name: ManuscriptTitle, dtype: object
16182    Structural magnetic and magnetocaloric propert...
16183    Magnetocaloric properties of (La1− xPrx) 0.85 ...
Name: ManuscriptTitle, dtype: object
14785    Sulfurization studies of the potential thin fi...
14792    Solution deposition of amorphous IZO films by ...
Name: ManuscriptTitle, dtype: object
7858    Doubling Exponent Models for the Analysis of P...
7974         Organic laser based on thiophene derivatives
Name: ManuscriptTitle, dtype: object
11732    Charge transfer and magnetotransport propertie...
11735    Lanthanum influence on the structure dielectri...
11811    Synthesis and structural characterization of t...
11818    Magnetic behaviour of praseodymium substituted...
11821    Waspwaisted like magnetic behavior of nanocrys...
11833    Planar versus bulk heterojunction perovskite m...
Name: ManuscriptTitle, dtype: object
11773    Optical properties of GST nanoparticles fabric...
11779    Comparative Study On The Impact Of TiN And Mo ...
Name: ManuscriptTitle, dtype: object

12324    Exciton dynamics in an energy upconverting sol...
12330    Excited state dynamics of PPI dendrimers funct...
Name: ManuscriptTitle, dtype: object
1237    Observation of strong valley magnetic response...
1239    Extraordinarily Stable Aqueous Electrochromic ...
Name: ManuscriptTitle, dtype: object
3520     GreenEmitting Powders of ZeroDimensional Cs4Pb...
13173    Atomistic simulation of SiAu melt crystallizat...
Name: ManuscriptTitle, dtype: object
12950    Standardized microbial fuel cell anodes of sil...
12956    Novel amphiphilic corannulene additive for moi...
Name: ManuscriptTitle, dtype: object
976      Prismatic deflection of live tumor cells and c...
15124    Magnetic Anisotropy in “Scorpionate” First‐Row...
Name: ManuscriptTitle, dtype: object
1494    Conjugated polymer mesocrystals with structura...
1496    Solar Cells Spin‐Cast Bulk Heterojunction Sola...
Name: ManuscriptTitle, dtype: object
8541    Hot carrier solar cell absorber prerequisites ...
8543    Hot carrier dynamics in HfN and ZrN measured b...
Name: ManuscriptTitle, dtype: object
14613    Proton conductivity in mixed Bsite doped perov...
14620    Graphene transfer methods for the fabrication ...
14625    Improved understanding of metal–graphene contacts
Name: ManuscriptTitle, dtype: object
1529    Efficient nonfullerene organic solar cells wit...
1532    High‐Efficiency Flexible Solar Cells Based on ...
Name: ManuscriptTitle, dtype: object
194    Breaking of macroscopic centric symmetry in pa...
349    Eliminating the need for anodic gas separation...
Name: ManuscriptTitle, dtype: object
3770    Monitoring Charge Carrier Diffusion across a P...
3821    Free carrier generation and recombination in p...
Name: ManuscriptTitle, dtype: object
14403    Singlestrand DNAnanorod conjugates–tunable ani...
14404    Barium titanate perovskite nanoparticles as a ...
Name: ManuscriptTitle, dtype: object
9506    CMOS integration of epitaxial GdO highk gate d...
9539    Allinorganic nonperovskite copper halides for ...
Name: ManuscriptTitle, dtype: object
7708    Structural origins of lightinduced phase segre...
7709    Colloidal synthesis and charge carrier dynamic...
Name: ManuscriptTitle, dtype: object
3370    Controlled synthesis and optical properties of...
3410    Improved Photovoltaic Efficiency and Amplified...
Name: ManuscriptTitle, dtype: object
8599    Laser fabrication of crystalline silicon nanor...
8678    Charge separation in Ptdecorated CdSe@ CdS oct...
Name: ManuscriptTitle, dtype: object
89     Engineering spinorbit synthetic Hamiltonians i...
124       Observation of roomtemperature polar skyrmions
125    Spatially resolved steadystate negative capaci...
Name: ManuscriptTitle, dtype: object
5882    Effect of Co‐Solvents on the Crystallization a...
5986    Staging Unraveling the Potassium Storage Mecha...
Name: ManuscriptTitle, dtype: object
13932    Rodshaped thiocyanateinduced abnormal band gap...
13933    Synthesis and transformation of zerodimensiona...
Name: ManuscriptTitle, dtype: object
9757    Microlightemitting diodes with quantum dots in...
9760    Broadband perovskite quantum dot spectrometer ...
9761    There is plenty of room at the top generation ...
9770    Waterinduced MAPbBr3@PbBr(OH) with enhanced lu...
Name: ManuscriptTitle, dtype: object
184     Reducing the efficiency–stability–cost gap of ...
1111    Fast neutron imaging with semiconductor nanocr...
Name: ManuscriptTitle, dtype: object
1086    Tunable Multipolar Surface Plasmons in 2D Ti3C...
8731    Facile synthesis of stable water soluble dendr...
Name: ManuscriptTitle, dtype: object
3630    Biexciton resonances reveal exciton localizati...
3631    Electrooptic response in germanium halide pero...
Name: ManuscriptTitle, dtype: object
3550    Improved Photovoltaic Efficiency and Amplified...
3553    Direct Band Gap MixedValence Organic–inorganic...
3555    Design of LeadFree Antiferroelectric (1 – x)Na...
Name: ManuscriptTitle, dtype: object
2833     Strainpromoted perpendicular magnetic anisotro...
13585    Treatment of the multimode Jahn–Teller problem...
Name: ManuscriptTitle, dtype: object
12097    Sequential polymer precipitation of core–shell...
12099    Toward the realization of a practical diketopy...
12130    Relaxation of polar order in poled polymer sys...
12131    Surface structure of semicrystalline naphthale...
Name: ManuscriptTitle, dtype: object
4963    Enhanced emission efficiency in doped CsPbBr 3...
5060    Structure–property trends in a hollandite mult...
Name: ManuscriptTitle, dtype: object
16213    Powder injection moulding of premixed ferritic...
16247    Spectroscopic properties of cerium in glasses ...
Name: ManuscriptTitle, dtype: object
8617    Investigation of high contrast and reversible ...
8668    Radiofrequencytransmitting hexagonal boron nit...
Name: ManuscriptTitle, dtype: object
3562    Polymerassisted synthesis of colloidal germani...
7846    Conductivity Measurements of Electrochemically...
Name: ManuscriptTitle, dtype: object
9624    Longlived charge separation in twodimensional ...
9649    Electrical control of a laterally ordered InAs...
9650    Mapping the plasmonic response of gold nanopar...
Name: ManuscriptTitle, dtype: object
9223    Backcontact perovskite solar cell fabrication ...
9224               Semitransparent quantum dot solar cell
Name: ManuscriptTitle, dtype: object
6704    Rational Design of a Water‐Storable Hierarchic...
6763    Effect of disorder on transport properties in ...
Name: ManuscriptTitle, dtype: object
6723    Mn2+/Yb3+ Codoped CsPbCl3 Perovskite Nanocryst...
6730    Molecular Weight Tuning of Organic Semiconduct...
6768    Ionbeam assisted laser fabrication of sensing ...
Name: ManuscriptTitle, dtype: object
11171    Selfhealing selfassembly of aspectratiotunable...
11172    Growth of SingleCrystal DoubleDirectional Tell...
12751    Effect of higher alcohols on the performances ...
12752    Molecular structure and pH effects on the prod...
Name: ManuscriptTitle, dtype: object
6342    Tunable Band Gap and Rhombohedral Distortion i...
6380    In Situ Synthesis of Conducting Polymers A Nov...
Name: ManuscriptTitle, dtype: object
14831    Fabrication of flexible perovskite solar cells...
14878    Low cost spin coating fabrication of efficient...
Name: ManuscriptTitle, dtype: object
13288    Laser postprocessing of halide perovskites for...
13289    Singlestage fabrication of lowloss dielectric ...
13295    Manipulating fano resonance via fslaser meltin...
13298    Mixed halide perovskite light emitting solar cell
13316    Processing and characterization of GaP nanowir...
Name: ManuscriptTitle, dtype: object
1112    Unraveling the radiative pathways of hot carri...
8741    Optical trapping and manipulation of plasmonic...
Name: ManuscriptTitle, dtype: object
1208    Observation of the full exciton and phonon fin...
8766    Waterinduced fluorescence enhancement of leadf...
Name: ManuscriptTitle, dtype: object
8777    Resonant energy transfer in a van der Waals st...
8800    Enhancement of exciton transport in porphyrin ...
Name: ManuscriptTitle, dtype: object
4463     A mechanistic study of the dopantinduced break...
15120    Recent advances in the use of TiO 2 nanotube p...
Name: ManuscriptTitle, dtype: object
7869    Solvation Dynamics of DCM in a DPPC Vesicle En...
7935    Atomistic simulations of P (NDI2ODT2) morpholo...
Name: ManuscriptTitle, dtype: object
16943    Recent Advances in Cs2AgBiBr6Based Halide Doub...
16968    Photoluminescent and vapochromic properties of...
Name: ManuscriptTitle, dtype: object
16959    High temperature induced phase transitions in ...
16969    Elucidating the influence of high pressure on ...
Name: ManuscriptTitle, dtype: object
16972    Zinc Phthalocyanine Conjugated Dimers as Effic...
16975    Development of wide bandgap perovskites for ne...
Name: ManuscriptTitle, dtype: object
16977    A steel slag–derived Boudouard reaction cataly...
16998    Growth of niobium thin films on Si substrates ...
Name: ManuscriptTitle, dtype: object
16981    Predicting the electronic structure magnetism ...
17008    An Ionic Supported Liquid Membrane for the Rec...
17023    Updated measurement method and uncertainty bud...
Name: ManuscriptTitle, dtype: object
4961     Largescale synthesis and screen printing of up...
5010     Mechanisms for collective inversionsymmetry br...
16956    Perovskite materials in energy storage and con...
Name: ManuscriptTitle, dtype: object
4960     Photochromism in Ruddlesden–Popper copperbased...
4980     Multimodal photodetectors with vacuum deposite...
16955    Solvothermal EtchingAssisted Phase and Morphol...
Name: ManuscriptTitle, dtype: object
13511    Variable Temperature Neutron Diffraction Study...
13520    Tripyridinophane platform containing three ace...
Name: ManuscriptTitle, dtype: object
13503    CaMn1−x NbxO3 (x ≤ 0.08) PerovskiteType Phases...
13504    New Materials Derived from Ybco  CrSr2RECu2O8 ...
Name: ManuscriptTitle, dtype: object
4402    Semicrystalline photovoltaic polymers with eff...
4404    Hot slot die coating for additivefree fabricat...
Name: ManuscriptTitle, dtype: object
2534    Prevention of oxide formation during liquid ph...
2620    Effect of ion mass on the evolution of extende...
Name: ManuscriptTitle, dtype: object
12471    A hightemperature highefficiency solar thermoe...
12474    Organic Solar Cells with Large Insensitivity t...
Name: ManuscriptTitle, dtype: object
5269    Perovskite singlecrystal solar cells going for...
5275    Solutionprocessed airstable mesoscopic seleniu...
Name: ManuscriptTitle, dtype: object
17477                       Solidstate NMR of nanocrystals
17491    Physicochemical characterization of wheat stra...
Name: ManuscriptTitle, dtype: object
6668    Spectral features and charge dynamics of lead ...
6672    Photophysics of Hybrid Lead Halide Perovskites...
6675    Quantum Dot Self‐Assembly Enables Low‐Threshol...
6745    Largearea rainbow holographic diffraction grat...
Name: ManuscriptTitle, dtype: object
5072           Tunable luminescent lead bromide complexes
5082    Highperformance perovskite singlejunction and ...
5182    Highly efficient perovskite solar modules by s...
Name: ManuscriptTitle, dtype: object
14466    Magnetic and dielectric studies of barium hexa...
15212    Electrochemical sensorbased barium zirconate o...
Name: ManuscriptTitle, dtype: object
14462                    Carbon nanotubeceramic composites
14463    Fabrication and characterization of Fe3O4/CNTs...
14476    The physics of terahertz negative photoconduct...
Name: ManuscriptTitle, dtype: object
13296    Direct femtosecond laser writing of optical na...
13297    Synthesis of perovskite nanoparticles in micro...
13299    Femtosecond laser nanostructuring of reinforce...
13300    Multi wall carbon nanotubes as a top electrode...
Name: ManuscriptTitle, dtype: object
13303    Waterstable halide perovskite nanocrystals in ...
13309    Memristive properties of solar cells based on ...
13315    Study of nonlinear optical phenomena in silico...
Name: ManuscriptTitle, dtype: object
10557    Enhanced hole injection in a polymer light emi...
10558    Layer growth and desorption kinetics of a disc...
Name: ManuscriptTitle, dtype: object
16196    Modulation of magnetic ferroelectric and leaka...
17519    Synthesis and Mechanical Properties of Natural...
Name: ManuscriptTitle, dtype: object
3924    Comparison of the Performance of CoPCoated and...
7698    An ammoniumpseudohalide ion pair for synergist...
Name: ManuscriptTitle, dtype: object
1233    RealTime Observation of Exciton–Phonon Couplin...
1236    Fewlayer to multilayer germanium (II) sulfide ...
Name: ManuscriptTitle, dtype: object
2562    Raman spectroscopy of (KNa)NbO3 and (K Na)1xLi...
2565     Preisach modeling of ferroelectric pinched loops
Name: ManuscriptTitle, dtype: object
7044    Theoretical guidelines to create and tune elec...
7049    Enhanced mobility CsPbI3 quantum dot arrays fo...
Name: ManuscriptTitle, dtype: object
10664    [1] Benzothieno [3 2‐b][1] benzothiophene‐Phth...
10689    Electrophoretic deposited oxide thin films as ...
Name: ManuscriptTitle, dtype: object
11729    Modification of capacitive charge storage of T...
11731    Nanocrystals of a new complex perovskite diele...
Name: ManuscriptTitle, dtype: object
16942    Nitrogendoped simple and complex oxides for ph...
16957    A novel heterogeneous La0.8Sr0.2CoO3−δ/(La0.5S...
16960    Effect of the M3+ cation size on the structura...
16984    Phonon phase stability structural mechanical e...
16991    A tin‐incorporated multi‐phase perovskite nano...
16997    Adoption of widebandgap microcrystalline silic...
17002    Highperformance selfpowered color filterfree b...
17021    Effect of silica nanoparticle size on the stab...
Name: ManuscriptTitle, dtype: object
16964    Coordination modes of 3hydroxypicolinic acid S...
16967    Dielectric properties induced by the framework...
Name: ManuscriptTitle, dtype: object
16941    Photoinduced electron transfer between CdS and...
16945    Understanding and engineering of multiphase tr...
Name: ManuscriptTitle, dtype: object
16949    Tuning the ASite Cation Deficiency of La0.8Sr0...
16966    Unraveling the luminescence of new heterolepti...
Name: ManuscriptTitle, dtype: object
10438    Energy and mass of 3D and 2D polarons in the o...
10441    A variational study of the ground Landau level...
Name: ManuscriptTitle, dtype: object
3591    Backbone Randomization in Conjugated PolymerBa...
3592    Trioctylphosphine Oxide Acts as Alkahest for S...
Name: ManuscriptTitle, dtype: object
13759    Functional Molecular System of Bis (pyrazolyl)...
13760    Na–Ni–H Phase Formation at High Pressures and ...
Name: ManuscriptTitle, dtype: object
16560    Understanding the doping effect toward the des...
16613    Recent advances in metal‐organic framework der...
Name: ManuscriptTitle, dtype: object
980     Temperatureinduced selfcompensating defect tra...
1016    Piezoresistive Properties of Suspended Graphen...
1065    Structural optical and electrical properties o...
Name: ManuscriptTitle, dtype: object
11776    Wave correlation of elementary deformation eve...
11790    Solgel silica films embedding NIRemitting Ybqu...
Name: ManuscriptTitle, dtype: object
13761    Facile Way of Making Hydrothermally Synthesize...
13763    A TwoStep Magnetron Sputtering Approach for th...
13764    Mitigating damage to hybrid perovskites using ...
Name: ManuscriptTitle, dtype: object
16649    Thermoelectric properties of pBi2 − x Sb x Te3...
16652                   Highpressure thermopower of sulfur
16666    Octahedral tilting in the polar hexagonal tung...
16673    Ab initio study on halfmetallic electronic and...
Name: ManuscriptTitle, dtype: object
16685    A (2) FeSbO (6)(A= Sr Ca) double perovskites o...
16692    Crystal structure analysis using integrated Xr...
Name: ManuscriptTitle, dtype: object
5221    Underwater organic solar cells via selective r...
5222    Ternary halide perovskites for highly efficien...
Name: ManuscriptTitle, dtype: object
3506     Facile dropletbased microfluidic synthesis of ...
12633    New bifunctional catalytic systems for sorbito...
Name: ManuscriptTitle, dtype: object
4534    Efficient optical amplification in the nanosec...
4595    Methane upgrading of acetic acid as a model co...
Name: ManuscriptTitle, dtype: object
5121    A simple ndopant derived from diquat boosts th...
5124    Low Temperature Crystallization Enables 21.9% ...
5183    Stability in perovskite photovoltaics a paradi...
Name: ManuscriptTitle, dtype: object
1273     Efficient spray‐coated colloidal quantum dot s...
1275     2D Metal Oxyhalide‐Derived Catalysts for Effic...
13147    Effect of the semiconductor quantum dot shell ...
Name: ManuscriptTitle, dtype: object
4794    Transparent organic lightemitting diodes with ...
4797       Nonlinear microscopy of lead iodide nanosheets
Name: ManuscriptTitle, dtype: object
6121    Homeopathic perovskite solar cells effect of h...
6127    Panchromatic SolartoH2 Conversion by a Hybrid ...
Name: ManuscriptTitle, dtype: object
1106    Largearea ordered superlattices from magnetic ...
1290    Effect of solvent environment on colloidal‐qua...
8738    Deep eutectic solventbased manganese molybdate...
Name: ManuscriptTitle, dtype: object
3289    Competing dissolution pathways and ligand pass...
3422    Thermochromic perovskite inks for reversible s...
Name: ManuscriptTitle, dtype: object
244                                      A sensitive pair
8809    Realizing a Highly Luminescent Perovskite Thin...
Name: ManuscriptTitle, dtype: object
207    Localized surface plasmon resonances arising f...
291    Experimental observation of the optical spin–o...
Name: ManuscriptTitle, dtype: object
6465    DualFunctional Optoelectronic and Magnetic Pyr...
6466    Longlived hot carriers in formamidinium lead i...
6467    Temperaturedependent optical properties of PbS...
Name: ManuscriptTitle, dtype: object
13942    Morphological Characterisation of Bacterial Ce...
13945    Exploring graphene quantum dots/TiO2 interface...
Name: ManuscriptTitle, dtype: object
5270     Lead halide perovskite nanocrystals in the res...
5277     Colloidal CsPbX3 (X = Cl Br I) Nanocrystals 2....
12803    Surface mobility of oxygen species on mixedoxi...
Name: ManuscriptTitle, dtype: object
1170    FourStates Multiferroic Memory Embodied Using ...
8756    Phase angle encoded upconversion luminescent n...
Name: ManuscriptTitle, dtype: object
9880    Ion bombardmentinduced enhancement of the prop...
9881    Interface engineering during plasmaenhanced ch...
Name: ManuscriptTitle, dtype: object
3356    Amorphous TiO2 Buffer Layer Boosts Efficiency ...
3402    PercolationLimited Ionic Diffusion in Li0.5xNa...
Name: ManuscriptTitle, dtype: object
3507     Microfluidic reactors provide preparative and ...
12634    Remarkable enhancement of the selective cataly...
Name: ManuscriptTitle, dtype: object
11528    Crossover from exciton to biexciton cavity pol...
11534         Polaronic exciton in a parabolic quantum dot
Name: ManuscriptTitle, dtype: object
12829    Tuning metal–carboxylate coordination in cryst...
12836    Microstructural changes in the reduction of Pr...
Name: ManuscriptTitle, dtype: object
10001    Fabrication BaZrO3/PBIbased nanocomposite as a...
10003    The effect of ethyleneamine ligands enhancing ...
Name: ManuscriptTitle, dtype: object
14752    New diagnostic method for monitoring plasma re...
14760    A combined optical and magneto‐optical measure...
Name: ManuscriptTitle, dtype: object
3502     The Future Is Blue (LEDs) Why Chemistry Is the...
12632    Preferential CO oxidation over nanosized gold ...
Name: ManuscriptTitle, dtype: object
519     The controlled disassembly of mesostructured p...
4857    A visible to nearinfrared nanocrystalline orga...
Name: ManuscriptTitle, dtype: object
15696    Discotic Liquid Crystals with Graphene Supramo...
15697    IIIIVI chalcogenide semiconductor nanocrystals...
Name: ManuscriptTitle, dtype: object
14781    Structure optimization for a high efficiency C...
14783    Challenges in deposition of wide band gap copp...
Name: ManuscriptTitle, dtype: object
254    Imaging the motion of electrons across semicon...
292    Experimental observation of the optical spinor...
Name: ManuscriptTitle, dtype: object
6075    Impact of bimolecular recombination on the fil...
6087    Access to ultrafast surface and interface carr...
6149    Molecular electronic coupling controls charge ...
6180    Luminescence of Nanostructured Eu3+/ZnO Mixed ...
6181    Effects of oxide nanoparticle size and shape o...
Name: ManuscriptTitle, dtype: object
8490    Temperature dependence of opencircuit voltage ...
9701    Charge dissipation in ebeam lithography with N...
Name: ManuscriptTitle, dtype: object
5533    Enhancement of magnetic entropy change in La0....
5844    Revealing morphology evolution in highly effic...

15583    Galvanostatic synthesis of MnCo2O4 nanoflakes ...
15593    High temperature Raman spectroscopy studies of...
Name: ManuscriptTitle, dtype: object
9674    Inchsized aligned polymer nanofiber films with...
9675    A ZnO nanowire array film with stable highly w...
Name: ManuscriptTitle, dtype: object
6109    Properties of contact and bulk impedances in h...
6115    Photosensitization of TiO2 Layers with CdSe Qu...
Name: ManuscriptTitle, dtype: object
16223    Fluctuations and depinning of stripes at acous...
16225    Observation of the transition to the spinglass...
16401    Flexible Organic Photovoltaics with Colorful S...
16403    Tibased MXenes for Energy Storage Application ...
Name: ManuscriptTitle, dtype: object
9052     Interfacial ferromagnetism and atomic structur...
11384    Origin of Performance Enhancement in TiO2‐Carb...
Name: ManuscriptTitle, dtype: object
15741    Solvent free solidstate synthesis of Pr6O11/gC...
15746    Photosensitive antimony triiodide thin films b...
Name: ManuscriptTitle, dtype: object
15721    Lowenergy electroninduced chemistry of condens...
15726    Enhancing silicon solar cells with singlet fis...
15747    Photoluminescence properties of cerium oxide n...
Name: ManuscriptTitle, dtype: object
13061    Wastefree scale up synthesis of nanocrystallin...
13067    Role of alkyl chain length in diaminoalkane li...
13070    Aniondependent coordinative networking of macr...
13071    Networking of macrocycles 1D and 2D coordinati...
13072    Guesttriggered assembly of zinc (II) supramole...
Name: ManuscriptTitle, dtype: object
13060    Oxygen and Hydrogen Surface Mobility in Suppor...
13073    Cationdirected assembly of polyrotaxane and po...
Name: ManuscriptTitle, dtype: object
11867    Fine Structural Details Matter A Lesson from S...
11869              RuddlesdenPopper Perovskite Solar Cells
Name: ManuscriptTitle, dtype: object
11876    Xray standing waves reveal lack of OH terminat...
11883     perovskites Theoretical and experimental inve...
Name: ManuscriptTitle, dtype: object
6155    Synthesis of type II CdTeCdSe nanocrystal hete...
6160    Doublelayer structured WPLEDs based on three p...
Name: ManuscriptTitle, dtype: object
6074    Incorporating fluorine substitution into conju...
6089    Imaging the reduction of electron trap states ...
Name: ManuscriptTitle, dtype: object
6749     Silicon source of frequencybin entangled photons
6751    Ultraviolet C lasing at 263 nm from Ba2LaF7Yb3...
Name: ManuscriptTitle, dtype: object
6691    Toward Strong Near‐Infrared Absorption/Emissio...
6692    Pure 2D Perovskite Formation by Interfacial En...
Name: ManuscriptTitle, dtype: object
12930    Porphyrinic supramolecular daisy chains incorp...
12931    Trapping shapecontrolled nanoparticle nucleati...
Name: ManuscriptTitle, dtype: object
6068    Charge separation in PCPDTBT PCBM blends from ...
6086    Rotationally Free and Rigid Sublattices of the...
Name: ManuscriptTitle, dtype: object
382    Strong coupling between chlorosomes of photosy...
384    Single crystal hybrid perovskite fieldeffect t...
Name: ManuscriptTitle, dtype: object
14971    Collision of a long DNA molecule with an isola...
15004    Perovskite Semiconductors and Fundamental Mech...
Name: ManuscriptTitle, dtype: object
715    Supramolecular control of charge transport in ...
716    Understanding structure− mobility relations fo...
728    Ligand Locking on Quantum Dot Surfaces via a M...
Name: ManuscriptTitle, dtype: object
13845    Influence of halide choice on formation of low...
13865    Deep blue light amplification from a novel tri...
Name: ManuscriptTitle, dtype: object
11283    Impact of surface defects in electron beam eva...
11284    Work function investigations of Aldoped ZnO fo...
Name: ManuscriptTitle, dtype: object
12422    Enhanced performance in inverted organic light...
12424    The refractive index grating formation in azo ...
Name: ManuscriptTitle, dtype: object
11517    Thermoelectric power of sulphur at high pressu...
11518    Influence of P–T pre‐treatment on thermopower ...
Name: ManuscriptTitle, dtype: object
13656    Using lead chalcogenide nanocrystals as spin m...
13658    Magnetic order in a novel 3D oxalatebased coor...
Name: ManuscriptTitle, dtype: object
9546    Structure and internal dynamics of a side chai...
9561          Siesta Recent developments and applications
Name: ManuscriptTitle, dtype: object
13673    Probing magnetic interactions in metal–organic...
13674    Ir (III) complexes designed for lightemitting ...
Name: ManuscriptTitle, dtype: object
4427                Transforming energy using quantum dots
13672    Colloidal assemblies of oriented maghemite nan...
Name: ManuscriptTitle, dtype: object
10116    Vibrational spectrocopic studies of organic mo...
10160    Epitaxial growth and enhanced conductivity of ...
Name: ManuscriptTitle, dtype: object
667    Growth of Oriented SingleCrystalline Rutile Ti...
708    Asymmetric Interfacet Adatom Migration as a Mo...
Name: ManuscriptTitle, dtype: object
1708    Fast‐Response Highly Air‐Stable and Water‐Resi...
7545    Theoretical study of crossed and parallel carb...
Name: ManuscriptTitle, dtype: object
8880    Insulator–metal transition and magnetoresistan...
8881    Prediction of giant magnetoelectric effect in ...
Name: ManuscriptTitle, dtype: object
9870    Investigation of photophysical morphological a...
9876    Improved fill factors in solutionprocessed ZnO...
Name: ManuscriptTitle, dtype: object
15570    P/i interfacial engineering in semitransparent...
15573    Resistive switching functional quantumdot ligh...
Name: ManuscriptTitle, dtype: object
827      Geminate charge recombination in polymer/fulle...
15294    Semitransparent perovskite solar cells for sma...
Name: ManuscriptTitle, dtype: object
4738     Thousand‐fold Conductivity Increase in 2D Pero...
14915    Fundamentals of threeterminal tandem solar cel...
Name: ManuscriptTitle, dtype: object
15539    Practical electricity generation from a paper ...
15547    Performance optimization of PGM and PGMfree ca...
15555    A threedimensional model of CdZnTe gammaray de...
15559    Interpretation of AC conductivity of lightly d...
15562    Investigation of interface properties in oxide...
15563    Interfacial engineering for highly efficient o...
15565    Silicon nanoparticle sizedependent open circui...
Name: ManuscriptTitle, dtype: object
15549    The effect of indium doping on photovoltaic pr...
15566    2 5di (thiophen2yl) thiazolo [5 4d] thiazoleba...
Name: ManuscriptTitle, dtype: object
14906    Highly Efficient PerovskiteonSilicon Tandem So...
14907    Economically sustainable growth of smallscale ...
Name: ManuscriptTitle, dtype: object
14900    Series Interconnection of Monolithic 2Terminal...
14902    Blade coating of diketopyrrolopyrrole based or...
Name: ManuscriptTitle, dtype: object
3039    Highly Efficient Perovskite Solar Cells Based ...
3179    Revealing the Anisotropic Structural and Elect...
Name: ManuscriptTitle, dtype: object
916    The architecture of colloidal quantum dot sola...
920    Oriented Halide Perovskite Nanostructures and ...
Name: ManuscriptTitle, dtype: object
10129    Flexible encapsulation materials based on sili...
10139    The atomiclevel structure of bandgap engineere...
10169    Influence of hidden halogen mobility on local ...
Name: ManuscriptTitle, dtype: object
4474    Interfacial benzenethiol modification facilita...
6967    LowTemperature Phase Transformations of  in th...
Name: ManuscriptTitle, dtype: object
15627    Tandem Nenitzescu reaction/nucleophilic aromat...
15629    Transformations of 5Hydroxy1pyrrolines in Stro...
15636    Analysis of AC permittivity response measured ...
Name: ManuscriptTitle, dtype: object
15633    Complex plane analysis of pn junction forwardv...
15634    The role of instrumentation in the process of ...
Name: ManuscriptTitle, dtype: object
15253    Phase field simulations of ferroelastic toughe...
15260    Magnetic influence on thermoelectric propertie...
Name: ManuscriptTitle, dtype: object
15256    Hightemperature stability structure and thermo...
15268    Dynamic control of ferroionic states in ferroe...
Name: ManuscriptTitle, dtype: object
10567    The impact of Au doping on the charge carrier ...
10606    Photoinduced unidirectional electron transfer ...
10609    Fast transient absorption spectroscopy of the ...
10610    Graphene quantum dots/Au hybrid nanoparticles ...
Name: ManuscriptTitle, dtype: object
10154    Surface radiomineralisation mediates chelatefr...
10155    Identification of dipole disorder in low tempe...
10161    Selfassembled molecular nanowires on prepatter...
Name: ManuscriptTitle, dtype: object
15588    Onestep methylammonium lead bromide films Effe...
15596    High temperature induced phase transitions in ...
Name: ManuscriptTitle, dtype: object
4077    Enhancing resistive switching performance and ...
4104    Recent Progress in Perovskite‐Based Reversible...
6436    Efficient and rapid photocatalytic reduction o...
Name: ManuscriptTitle, dtype: object
8556    Investigation of electronic transport mechanis...
8559    Accessing externally induced spatiallyresolved...
Name: ManuscriptTitle, dtype: object
4241    Charge Generation at Polymer/Metal Oxide Inter...
4267    In‐Situ Switching from Barrier‐Limited to Ohmi...
Name: ManuscriptTitle, dtype: object
1296    Pseudohalide‐exchanged quantum dot solids achi...
1298    A new approach to hybrid polymer–metal and pol...
Name: ManuscriptTitle, dtype: object
16453    Triphenylamino or 9phenyl carbazolylsubstitute...
16454    Molybdenum rods assembled with nanosheets a hi...
Name: ManuscriptTitle, dtype: object
10131    Effects of Hole and Electron Transporting Inte...
10133    Enhanced photocatalytic properties of nanostru...
10144    Tunable and highly efficient lightharvesting a...
10207    62‐8 Invited Paper High Color Gamut QDot™ LCD ...
Name: ManuscriptTitle, dtype: object
6688    Quantum dot passivation of halide perovskite f...
6761    Broadband solar absorption enhancement via per...
Name: ManuscriptTitle, dtype: object
13716    Nonfullerene acceptor fibrils enable efficient...
13726    Semicrystalline photovoltaic polymers with sil...
Name: ManuscriptTitle, dtype: object
6412    Photoinduced interactions in a pyrenecalix [4]...
6413    Zinc 5101520mesoTetraferrocenylporphyrin as an...
Name: ManuscriptTitle, dtype: object
7456    Combined LDA and LDA1/2 method to obtain defec...
7480    Structures of fluorinated graphene and their s...
Name: ManuscriptTitle, dtype: object
2772    The glasslike thermal conductivity in ZrO2Dy3T...
2777    Erratum “Twodimensional porous graphitic carbo...
Name: ManuscriptTitle, dtype: object
10987    Electronic and optical properties of twodimens...
10988    Twodimensional FeTe 2 and predicted Janus FeXS...
Name: ManuscriptTitle, dtype: object
9829    In Situ Methylammonium ChlorideAssisted Perovs...
9831    Underappreciated role of lowenergy facets in n...
Name: ManuscriptTitle, dtype: object
9670    A facile route to synthesize chalcopyrite CuIn...
9683    InxGa1− xAs nanowires with uniform composition...
Name: ManuscriptTitle, dtype: object
9663      Quantum confinement in few layer SnS nanosheets
9667    Boosting the performance of ZnO microrod metal...
Name: ManuscriptTitle, dtype: object
5297    Perovskite/colloidal quantum dot tandem solar ...
5301    Online meetings in times of global crisis Towa...
Name: ManuscriptTitle, dtype: object
4737    Fluorescence Blinking Beyond Nanoconfinement S...
4792    Time resolved fluorescence polarization anisot...
Name: ManuscriptTitle, dtype: object
15500    Improving the power conversion efficiency and ...
15501    Structural and Electrochemical Properties of K...
Name: ManuscriptTitle, dtype: object
6069    CsxFA1–xPb(I1–yBry)3 Perovskite Compositions t...
6088    Intriguing Ultrafast Charge Carrier Dynamics i...
Name: ManuscriptTitle, dtype: object
12676    Study of the oxygen diffusion on threeway cata...
12691    In Situ fourier transform infrared study of th...
Name: ManuscriptTitle, dtype: object
15099    Ultrasonically sprayed Cs3Bi2I9 thin film base...
15100    Effect of Nd3+ ions on structural spectral mag...
Name: ManuscriptTitle, dtype: object
1258                       Perovskites for light emission
6172    Electrodeposited mesoporous ZnO thin films as ...
Name: ManuscriptTitle, dtype: object
14144    Structural and magnetic behavior in nanocrysta...
14169    Epitaxial growth of ZnO nanowires on aand cpla...
14172    MOCVD growth of CdTe on glass analysis of in s...
14173    Influence of twinned structure on the morpholo...
14195    AgBi2I7 layers with controlled surface morphol...
14202    Preparation and characterization of Al and B c...
Name: ManuscriptTitle, dtype: object
10439    On the stability of Fröhlich bipolarons in sph...
10440    Path integral description of lowdimensional po...
Name: ManuscriptTitle, dtype: object
6150    Removing instabilitycaused lowfrequency featur...
6159    Synthesis and cathodoluminescence of morpholog...
Name: ManuscriptTitle, dtype: object
5253    Thermally Activated SecondOrder Recombination ...
5254    Comparing the calculated fermi level splitting...
Name: ManuscriptTitle, dtype: object
444    Efficient photosynthesis of carbon monoxide fr...
446    Spectral splitting photovoltaics using perovsk...
Name: ManuscriptTitle, dtype: object
14145    Structural and Raman studies of MnO2 and Mn2O3...
14151    Investigations on partially exfoliated graphit...
Name: ManuscriptTitle, dtype: object
14124    Structural aspects of the dehydration of αZr (...
14176    Epitaxial lateral overgrowth of Si on (1 0 0) ...
14181    Impurity effects in ZnO and nitrogendoped ZnO ...
14188    Sol–gel preparation and optical characterizati...
Name: ManuscriptTitle, dtype: object
14129    Morphological and dynamical evolution of lanth...
14132    Exploring the thermochemical heat storage capa...
Name: ManuscriptTitle, dtype: object
14167    Effect of sourcesubstrate distance on the tran...
14174    Numerical study of the growth conditions in an...
Name: ManuscriptTitle, dtype: object
15581    An electrochemical study of copper diffusion i...
15582    Novel nanocomposite membranes based on polyben...
15597    Xray diffraction and Raman spectroscopy studie...
Name: ManuscriptTitle, dtype: object
11152    Interrelation between substrate roughness and ...
11153    Synthesis and Characterization of Branched fcc...
Name: ManuscriptTitle, dtype: object
10545    Quantification of ion migration in CH 3 NH 3 P...
10552                        Dislocationtoughened ceramics
Name: ManuscriptTitle, dtype: object
2507    Molecular beam epitaxy of MnAs/ZnSe hybrid fer...
2617    Electrical characterization of the threshold f...
Name: ManuscriptTitle, dtype: object
6169    Role of aspect ratio in the photoluminescence ...
6177    Insights into the hole blocking layer effect o...
Name: ManuscriptTitle, dtype: object
16098    1D heterometallic oxalate compounds as precurs...
16121    Ab initio study of oxygen vacancy effects on e...
16130    Ab Initio study of the crystal structure and t...
16133    Spectral shifts upon halide segregation in per...
16143    Enhanced magnetooptical activity of multilayer...
Name: ManuscriptTitle, dtype: object
9523    Balancing crop production and energy harvestin...
9524    Perovskite Quantum Dots Exhibiting Strong Hole...
Name: ManuscriptTitle, dtype: object
11837    Rietveld refinement and electrical properties ...
11950    Exciton Recombination in Self‐Assembled InAs/G...
Name: ManuscriptTitle, dtype: object
6815    Unusual dimensionality effects and surface cha...
6816    Amplified spontaneous emission threshold reduc...
Name: ManuscriptTitle, dtype: object
10312    Optimising the efficiency of carbazole copolym...
10317    Solution deposited NiO thinfilms as hole trans...
10348    Highly efficient and foldable topemission orga...
10408    Structural stability of a golden semiconductin...
Name: ManuscriptTitle, dtype: object
10337    The doping effect of cesiumbased compounds on ...
10371    Critical light instability in CB/DIO processed...
Name: ManuscriptTitle, dtype: object
10313    Organic photovoltaic devices incorporating a m...
10397    The effect of morphology on the temperaturedep...
Name: ManuscriptTitle, dtype: object
936     ChargeCarrier Recombination in Halide Perovski...
5718    Quasi‐Continuous Wave Near‐Infrared Excitation...
Name: ManuscriptTitle, dtype: object
4121    Heterogeneous nucleation promotes carrier tran...
4149    One‐Step Polymeric Melt Encapsulation Method t...
Name: ManuscriptTitle, dtype: object
1140    Planar aperiodic arrays as metasurfaces for op...
8813    Photo‐cross‐linkable poly(p‐phenylene)s. Synth...
Name: ManuscriptTitle, dtype: object
9167    The expanding world of hybrid perovskites mate...
9168    Hybrid tandem solar cells with depletedheteroj...
Name: ManuscriptTitle, dtype: object
7728    Using Monovalentto TrivalentCation Hybrid Pero...
7729    Dithienogermolebased nonfullerene acceptors ro...
Name: ManuscriptTitle, dtype: object
528      Sub1.4 eV bandgap inorganic perovskite solar c...
13114    Efficient Emission Outcoupling from Perovskite...
Name: ManuscriptTitle, dtype: object
9964    Study of exciton hopping transport in PbS coll...
9965    Ultrastable allinorganic silver bismuth sulfid...
Name: ManuscriptTitle, dtype: object
3067    RealSpace Mapping of SurfaceOxygen Defect Stat...
3073    A Direct nButane Solid Oxide Fuel Cell Using B...
3093    Scalable PbS quantum dot solar cell production...
3096    On the colloidal stability of PbS quantum dots...
3116    Multifunctional silver nanoparticle interlayer...
3145    SolutionProcessed Red Green and Blue Quantum R...
Name: ManuscriptTitle, dtype: object
1004    Hotspotinduced transformation of surfaceenhanc...
1005    Nitrogendoped nanoporous carbon membranes with...
Name: ManuscriptTitle, dtype: object
2234    PolarizationDependent Purcell Enhancement on a...
2363    Piezoelectricity and electrostriction of dye‐d...
Name: ManuscriptTitle, dtype: object
16392    Synthesis and Physical Properties of Asymmetri...
16396    An Unusual PseudoCoordination Polymer of Dithi...
Name: ManuscriptTitle, dtype: object
3071    Promoting the Efficiency and Stability of CsPb...
3089    SelfAssembly of CsPbBr 3 Perovskites in Microp...
3121    Statistical Paradigm for Organic Optoelectroni...
3129    Antibacterial Melamine Foams Decorated with in...
3130    Efficient photoand electroluminescence by trap...
3138    Developing the nextgeneration perovskite/Si ta...
Name: ManuscriptTitle, dtype: object
17409    Employment of electrochemically synthesized TG...
17410    Adsorption and preconcentration of divalent me...
Name: ManuscriptTitle, dtype: object
14435    Scheelitetype rare earth vanadates TVO4 (T= Ho...
14448    Combat antimicrobial resistance emergence and ...
Name: ManuscriptTitle, dtype: object
8252    Temperature influence on morphological progres...
8281    Inorganic lead halide perovskite single crysta...
8282    Solution‐processed visible‐blind ultraviolet p...
Name: ManuscriptTitle, dtype: object
8189    Bulk Recrystallization for Efficient MixedCati...
8190    A low iontransfer resistance and high volumetr...
Name: ManuscriptTitle, dtype: object
12281    Photovoltaic polymers based on difluoroqinoxal...
12283    Highly efficient and stable blue‐light‐emittin...
Name: ManuscriptTitle, dtype: object
10108    CeO2–NiO Nanoflakes Assessment and Their Antic...
10111    Structural Magnetic Electrical and PhotoFenton...
10300    Allsolutionprocessed multilayer polymer/dendri...
Name: ManuscriptTitle, dtype: object
5802    Enhanced nucleation of atomic layer deposited ...
5803    Impact of Hole Transport Layer Surface Propert...
Name: ManuscriptTitle, dtype: object
8009    Synthesis of Cu 2 (Zn 1− x Co x) SnS 4 nanocry...
8036    In situ study of the film formation mechanism ...

10118    Photocurrent Enhancement of CdSe QuantumDot Se...
10120    Improved Field Emission of ThreeDimensional Si...
Name: ManuscriptTitle, dtype: object
888     Formation of LongLived Color Centers for Broad...
5637    Fabry–Pérot Oscillation and Room Temperature L...
Name: ManuscriptTitle, dtype: object
10085    Synthesis of Sb2E3 (E= S Se) Nanorods with a F...
10086    Enhanced Photocurrent from Organic PolymersBas...
10286    Optical Modulation of Amplified Emission in a ...
Name: ManuscriptTitle, dtype: object
16771    A computational investigation on structural me...
16781    Structural Magnetic and Magnetocaloric Propert...
Name: ManuscriptTitle, dtype: object
16867    Cubic PbGeO3 perovskite oxide a compound with ...
16868    Putting DFT to the trial First principles pres...
Name: ManuscriptTitle, dtype: object
17344    Luminescent Copper (I) complexes as promising ...
17347    Colloidal Synthesis of ZnS CdS and Zn x Cd1−x ...
Name: ManuscriptTitle, dtype: object
2644    Lattice parameter and energy band gap of cubic...
2654    Ordenamento induzido por tensão na liga de InGaAs
Name: ManuscriptTitle, dtype: object
13198    Optical isolation via onedimensional magnetoph...
13204    MAPLEdeposited PFO films influence of the lase...
13208    Novel application of MgF2 as a back reflector ...
Name: ManuscriptTitle, dtype: object
13187    How well do implicit solvation models represen...
13202    Timeresolved fluorescence polarization anisotr...
13211    Hightemperature plastic deformation and acoust...
Name: ManuscriptTitle, dtype: object
5179    Defect tolerance in methylammonium lead triiod...
5180    Influence of Electrode Interfaces on the Stabi...
Name: ManuscriptTitle, dtype: object
11190    Semicoordination bond breaking and halogen bon...
11192    Synthesis of ultrathin perovskite nanowires vi...
Name: ManuscriptTitle, dtype: object
15157    Efficient photoinduced energy transfer mediate...
15158    Decoupling fluorescence and photochromism in b...
15163    A Unique Case of Oxidative Addition of Interha...
15168    Precise Control of Intramolecular Charge‐Trans...
Name: ManuscriptTitle, dtype: object
5950    Low Current Density Driving Leads to Efficient...
6015    A facile surface passivation enables thermally...
Name: ManuscriptTitle, dtype: object
5945    Advances in Quantum‐Confined Perovskite Nanocr...
5989    Dopant‐free hole transporting polymers for hig...
Name: ManuscriptTitle, dtype: object
6174    Key growth parameters for the electrodepositio...
6190    Reversible ionic polarization in metal halide ...
Name: ManuscriptTitle, dtype: object
1569    From Bulk to Surface Sodium Treatment Reduces ...
1570      Strategies toward Stable Perovskite Solar Cells
Name: ManuscriptTitle, dtype: object
15454    A rational design strategy for an extremely de...
15469    How Machine Learning Accelerates the Developme...
15497    Ab Initio High Pressure and Temperature Invest...
Name: ManuscriptTitle, dtype: object
15424    Role of CuAlO2 as an absorber layer for solar ...
15488    Influence of Group IVTe Alloying on Nanocompos...
15495    HighTemperature and HighPressure Study of Elec...
Name: ManuscriptTitle, dtype: object
16762    Spin transistors vs. conventional transistors ...
16770    Ab Initio Investigation on Electronic Magnetic...
16782    Microstructural Analysis Magnetic Properties a...
Name: ManuscriptTitle, dtype: object
12562    Cooperative effect of Pt–Rh/Ba/Al and CuZSM5 c...
12570    Electrodeposited Repromoted Ni foams as a cata...
Name: ManuscriptTitle, dtype: object
4477    Organic solar cells with nearunity charge gene...
4481    Dopantfree polymeric hole transport materials ...
Name: ManuscriptTitle, dtype: object
576    Exceptional electrocatalytic oxygen evolution ...
578    Hot carriers perspective on the nature of trap...
Name: ManuscriptTitle, dtype: object
4028    Electronic properties of the interfaces betwee...
4044    Efficient White‐Electrophosphorescent Devices ...
4053    Domain‐Size‐Dependent Residual Stress Governs ...
Name: ManuscriptTitle, dtype: object
4007    Spectroscopy of Resonant Intermediate States f...
4011    Flexible filter‐free narrowband photodetector ...
4015    Dual coordination of Ti and Pb using bilinkabl...
4039    Quantitative analysis of bulk heterojunction f...
Name: ManuscriptTitle, dtype: object
3956    Biexciton Generation and Dissociation Dynamics...
3957    Monitoring the phase formation of coevaporated...
Name: ManuscriptTitle, dtype: object
1095    Separation of empty and waterfilled singlewall...
8734    Correction Facile synthesis of stable water so...
Name: ManuscriptTitle, dtype: object
1997    Jointly tuned plasmonic–excitonic photovoltaic...
2014    Ligand exchange at a covalent surface enables ...
Name: ManuscriptTitle, dtype: object
1933    Colloidal quantum dot solids for solutionproce...
2093    Determining the internal quantum efficiency of...
2132    Coupling Perovskite Quantum Dot Pairs in Solut...
Name: ManuscriptTitle, dtype: object
273                               Quantum dots on demand
282    Detection of gamma photons using solutiongrown...
Name: ManuscriptTitle, dtype: object
9465    Carbonbased allinorganic perovskite solar cell...
9491    Effect of Cu/Ga ratio on deeplevel defects in ...
9494    Quantitative study of electron tunneling dynam...
Name: ManuscriptTitle, dtype: object
4183    Efficient and ambient‐air‐stable solar cell wi...
4193    Layered germanium hybrid perovskite bromides i...
7505    Hydrogeninduced  rehybridization in epitaxial ...
Name: ManuscriptTitle, dtype: object
11941    Engineering solar cells based on correlative X...
11944    Thermal annealing influence on structural magn...
Name: ManuscriptTitle, dtype: object
7667    Firstprinciples investigation of the structura...
7677    Nearly 100% energy transfer at the interface o...
Name: ManuscriptTitle, dtype: object
13801    Induced conductivity in solgel ZnO films by pa...
13879    Raman Spectroscopy Studies on the Barocaloric ...
Name: ManuscriptTitle, dtype: object
13802    Structural electronic and elastic properties o...
13804    Thicknessdependent magnetic and electrical tra...
Name: ManuscriptTitle, dtype: object
1372    Semiconducting polymer nanospheres in aqueous ...
1509    53% Efficient Red Emissive Carbon Quantum Dots...
Name: ManuscriptTitle, dtype: object
1969     Metal halide perovskites for energy applications
2029    Polaronenhanced polariton nonlinearity in lead...
2065    Implications of the negative capacitance obser...
Name: ManuscriptTitle, dtype: object
6775              Hybrid organicinorganic polariton laser
6834    Taguchi grey relational optimization of sol–ge...
Name: ManuscriptTitle, dtype: object
6792    Ultrabright nearinfrared perovskite lightemitt...
6809    Optical determination of ShockleyReadHall and ...
6819    Colloidal antimony sulfide nanoparticles as a ...
Name: ManuscriptTitle, dtype: object
6117    Influence of the potassium chloride concentrat...
6126    Theory of impedance spectroscopy of ambipolar ...
Name: ManuscriptTitle, dtype: object
17179    Grain size and sample size interact to determi...
17184    Activating Inert MXenes for Hydrogen Evolution...
17185    Hydrogen Evolution Reaction Unraveling the Fac...
17186    Machine learning–based charge transport comput...
17187    Impact of phosphorescent sensitizers and morph...
Name: ManuscriptTitle, dtype: object
1162    Electron–Hole Binding Governs Carrier Transpor...
8819    Nonlinear optical figures of merit of processi...
Name: ManuscriptTitle, dtype: object
1098    Direct detection of circularly polarized light...
1146    Cu2Se and Cu Nanocrystals as Local Sources of ...
1269    The in‐gap electronic state spectrum of methyl...
Name: ManuscriptTitle, dtype: object
14809    Improving electron transport in Gadoped Zn0. 7...
14811    Effect of a postdeposition anneal on Al2O3/Si ...
Name: ManuscriptTitle, dtype: object
3454    Controlled Synthesis of LeadFree and Stable Pe...
3455    Controlled synthesis of leadfree cesium tin ha...
Name: ManuscriptTitle, dtype: object
2123    Wiringup hydrogenase with singlewalled carbon ...
2124    Photogenerated free carrier dynamics in metal ...
Name: ManuscriptTitle, dtype: object
1978    Systematic investigation of the impact of oper...
2146    NanoscaleResolved SurfacetoBulk Electron Trans...
Name: ManuscriptTitle, dtype: object
16954    LeadFree Potassium Alloyed Cs2AgBiBr6 Tunable ...
16979    Enhanced dissociation of excitons and charge t...
16986    A first‐principles prediction of thermophysica...
16996    Slightly ruthenium doping enables better alloy...
Name: ManuscriptTitle, dtype: object
13076    Unusual porous crystals via catenation of 1D l...
13077    Discrete and polymeric complexes of a macrocyc...
Name: ManuscriptTitle, dtype: object
15412    Highly efficient quasicubic structured perovsk...
15512    Correction to Electronic Structure Optical and...
Name: ManuscriptTitle, dtype: object
875    Asynchronous photoexcited electronic and struc...
876    Electron Accumulation Induces Efficiency Bottl...
Name: ManuscriptTitle, dtype: object
16118    Comparison of bandfitting and Wannierbased mod...
16138    Publications RepositoryHelmholtzZentrum Dresde...
Name: ManuscriptTitle, dtype: object
16074    Variable switching frequency control of distri...
16120    FTIR ellipsometry study on RF sputtered permal...
Name: ManuscriptTitle, dtype: object
5200    SMART perovskite growth enabling a larger rang...
5237    Temperature coefficients of perovskite photovo...
Name: ManuscriptTitle, dtype: object
14456    Domain wall contributions to the properties of...
14457    Pb (Mg1/3Nb2/3)O3 and (1− x)Pb(Mg1/3Nb2/3)O3−x...
Name: ManuscriptTitle, dtype: object
17326    Highly Efficient UV–Visible Photocatalyst from...
17342    An efficient and stable leadfree organic–inorg...
Name: ManuscriptTitle, dtype: object
5734    Nanofiber‐Directed Anisotropic Self‐Assembly o...
5832    27.6% Perovskite/c‐Si Tandem Solar Cells Using...
Name: ManuscriptTitle, dtype: object
5757    Charge generation and recombination in an orga...
5759    Rationalizing the Molecular Design of Hole‐Sel...
Name: ManuscriptTitle, dtype: object
5699    1D‐2D Synergistic MXene‐Nanotubes Hybrids for ...
5707    Ultrasensitive SERS substrate integrated with ...
Name: ManuscriptTitle, dtype: object
5563    Highperformance MoSe2 homojunction infrared ph...
5569    Polymerase chain reactionfree sampletoanswer b...
Name: ManuscriptTitle, dtype: object
5547    The effect of Sr doping on structural and diel...
5666    Bridging the Interfacial Contact for Improved ...
Name: ManuscriptTitle, dtype: object
17418    Impact of the structural parameters on the pho...
17420    Multipurpose Fully Integrated 128  128 EventDr...
Name: ManuscriptTitle, dtype: object
14504    High voltage gain inverters from artificially ...
14505    A novel lowcost highefficiency micromachined s...
Name: ManuscriptTitle, dtype: object
58     Electronhole diffusion lengths exceeding 1 mic...
616       Selfassembled pbse nanowire Perovskite hybrids
Name: ManuscriptTitle, dtype: object
17267    Trends in the Development of Hydroxyapatite fr...
17272    Dielectric and magnetic properties of BaFe11.7...
Name: ManuscriptTitle, dtype: object
817     Lewis base passivation mediates charge transfe...
1036    Functional twodimensional coordination polymer...
Name: ManuscriptTitle, dtype: object
12715    Selective oxidation of fatty alcohol ethoxylat...
12716    Novel design of photocatalyst coaxial ferromag...
12725    Oxygen surface mobility and isotopic exchange ...
Name: ManuscriptTitle, dtype: object
3714    Tailoring the surface morphology and phase dis...
3716    Manipulation of Band Alignment in TwoDimension...
Name: ManuscriptTitle, dtype: object
7687    Fully airprocessed dynamic hotairassisted M Cs...
7688    Triplet sensitization by lead halide perovskit...
Name: ManuscriptTitle, dtype: object
7659       Symmetry breaking and spin lattice coupling in
7662    Origin of intense bluegreen emission in  thin ...
7686    Unleashing the power of materials science for ...
Name: ManuscriptTitle, dtype: object
8468    Colloidal quantum dot solar cell electrical pa...
8488    Superior performance of V2O5 as hole selective...
Name: ManuscriptTitle, dtype: object
17393               Xray generation using carbon nanotubes
17395    Modern coin debasement discovered by combined ...
17401    Structural Colors on Al Surface via Capped CuS...
17402    Increasing depth penetration in biological tis...
17412    Topology Automated ForceField Interactions (TA...
Name: ManuscriptTitle, dtype: object
17392                           Soft optical metamaterials
17400    Stability assessment of pin perovskite photovo...
Name: ManuscriptTitle, dtype: object
9950    Continuous broadband MWP truetime delay with P...
9951    Fabrication and characterization of highqualit...
9952    HighBandwidth organic photodetector analyzed b...
Name: ManuscriptTitle, dtype: object
10884    Hysteresis phenomena in perovskite solar cells...
10888    Ordered networks of ZnOnanowire hierarchical u...
Name: ManuscriptTitle, dtype: object
9629    Curvaturemediated surface accessibility enable...
9631    Extending roGFP emission via forstertype reson...
Name: ManuscriptTitle, dtype: object
9627    Facile and quantitative estimation of strain i...
9639    Photoluminescence waveguiding in CdSe and CdTe...
Name: ManuscriptTitle, dtype: object

10736    Fabrication and performance evaluation of new ...
10748    Anionmediated synthesis of monodisperse silver...
10753    Investigation of the transport structural and ...
Name: ManuscriptTitle, dtype: object
10704    Supramolecular block copolymer photovoltaics t...
10721    Modulation of singlet and triplet excited stat...
Name: ManuscriptTitle, dtype: object
10708    Photochemical upconversion in metalbased octae...
10742    Porous silicon nanoparticles as a nanophotocat...
Name: ManuscriptTitle, dtype: object
2704    Increased efficiency in pnjunction PbS QD sola...
2750    Surface effects of electrodedependent switchin...
Name: ManuscriptTitle, dtype: object
8428    Deterministic and Scalable Generation of Excit...
8443    Enhanced upconversion via plasmonic nearfield ...
Name: ManuscriptTitle, dtype: object
8342    Water‐Induced and Wavelength‐Dependent Light A...
8368    Simultaneously Enhancing Color Spatial Uniform...
Name: ManuscriptTitle, dtype: object
7050    Lowenergy roomtemperature optical switching in...
7059    Momentummatching and bandalignment van der Waa...
Name: ManuscriptTitle, dtype: object
3629    Multiple SelfTrapped Emissions in the LeadFree...
3632    Dimensional mixing increases the efficiency of...
Name: ManuscriptTitle, dtype: object
16579    Temperaturedependent cyclic response and micro...
16583    Humidity Related Low Temperature Conductivity ...
Name: ManuscriptTitle, dtype: object
8060    Engineering the morphology via processing addi...
8062    Greensolvent processable semiconducting polyme...
Name: ManuscriptTitle, dtype: object
7991    Bandaligned C 3 N 4− x S 3x/2 stabilizes CdS/C...
7998    Selenophene vs. thiophene in benzothiadiazoleb...
8034    Ambient blade coating of mixed cation mixed ha...
8091    Synthesis crystal structure and properties of ...
8115    Twostep growth of CsPbI 3− X Br X films employ...
Name: ManuscriptTitle, dtype: object
8069    The introduction of a perovskite seed layer fo...
8110    Metal oxide alternatives for efficient electro...
Name: ManuscriptTitle, dtype: object
8090    Interplay between humidity temperature and ele...
8092    Facile synthesis of a hole transporting materi...
8174    Fundamental physics behind highefficiency orga...
Name: ManuscriptTitle, dtype: object
8016    Influence of the substrate on the bulk propert...
8031    Efficient inverted bulkheterojunction solar ce...
Name: ManuscriptTitle, dtype: object
8163    Lowtemperature growth of polyethylene glycoldo...
8172    Preserving the stoichiometry of triplecation p...
Name: ManuscriptTitle, dtype: object
7486    Mechanical properties of monolayer GaS and GaS...
7498    Tuning the magnetic anisotropy in singlelayer ...
Name: ManuscriptTitle, dtype: object
14031    Fluorescence relaxation kinetics of poly (meth...
14051    Fast oxygen mobility in tetragonal YBa2Cu3O7x ...
Name: ManuscriptTitle, dtype: object
14380    Spectroscopic and electrochemical study of hyb...
14410    Graphene induced structure and doping level tu...
Name: ManuscriptTitle, dtype: object
17180    Device design of doping‐controlled homojunctio...
17181    Electrocatalytic Reduction of Carbon Dioxide t...
Name: ManuscriptTitle, dtype: object
16871    An Investigation on Drilling of Epoxy Composit...
16876    Engineering the Switching Behavior of Nanomagn...
16878    Exposed Surface and Confinement Effects on the...
16882    Structure and Magnetism of IronSubstituted Nic...
16894    Ab initio calculations of the elastic vibratio...
Name: ManuscriptTitle, dtype: object
11502    Electronic structure and optical properties of...
11508    Excitation relaxation in copper selenide nanow...
11511    Thermoelectric properties and phase transition...
Name: ManuscriptTitle, dtype: object
5005    N N′Dihydrotetraazapentacenes (DHTA) in thin f...
5049    Ultrafast lightinduced symmetry changes in sin...
Name: ManuscriptTitle, dtype: object
4990    Flexible electroluminescent fiber fabricated f...
5048    Additive engineering to improve the efficiency...
Name: ManuscriptTitle, dtype: object
4995    Optical absorption by design in a ferroelectri...
5022    Exploring high temperature templating in nonpl...
Name: ManuscriptTitle, dtype: object
4966     Effects of ambient exposure on photoluminescen...
16961    Synthesis characterization and use of highly s...
Name: ManuscriptTitle, dtype: object
4958    Polarization anisotropy losses due to morpholo...
4977    Pulsedcurrent versus constantvoltage lightemit...
Name: ManuscriptTitle, dtype: object
4976    Host–guest blue lightemitting electrochemical ...
4978    Large area perovskite lightemitting diodes by ...
Name: ManuscriptTitle, dtype: object
4941    Evolution of CsPbBr 3 nanocrystals upon postsy...
4984    Selective excitation of Eu 3+ in the core of s...
4986    The competition between mechanical stability a...
5013    Solutionprocessed broadband photodetectors wit...
Name: ManuscriptTitle, dtype: object
4959    Optoelectronics of PbS quantum dot and narrow ...
5047    Crystalline rubrene via a novel process and re...
Name: ManuscriptTitle, dtype: object
4930    The role of charge generation layers in the op...
4964    Phase control for quasi2D blue emitters by spa...
4987    Mode coupling between nonpolar and polar phono...
5004    Thermally evaporated methylammoniumfree perovs...
Name: ManuscriptTitle, dtype: object
937    Solutionprocessed semiconductors for nextgener...
944       Scalable fabrication of perovskite solar cells
966    Role of bond adaptability in the passivation o...
971    Quantum dotplasmon lasing with controlled pola...
Name: ManuscriptTitle, dtype: object
11906    Decoupling exchange bias and coercivity enhanc...
11939    Roomtemperature optically detected magnetic re...
11945    Compressioninduced charge disproportionation i...
Name: ManuscriptTitle, dtype: object
13086    Lidocaine barbiturate a promising material for...
13100    Nature du dépôt formé au cours de l’oxydation ...
Name: ManuscriptTitle, dtype: object
2177        Nanoparticles heat through light localization
2184    Controlled nanometric phase transitions of pho...
Name: ManuscriptTitle, dtype: object
4     What would it take for renewably powered elect...
14    Erratum What would it take for renewably power...
16    What would it take for renewably powered elect...
Name: ManuscriptTitle, dtype: object
1166    Highly deformable origami paper photodetector ...
8753    Balancing power density based quantum yield ch...
Name: ManuscriptTitle, dtype: object
12932    Anthracenebased donor–acceptor low band gap po...
12943    Electric fieldinduced hole transport in copper...
12946    Surface motifs regulated aggregation induced e...
Name: ManuscriptTitle, dtype: object
14587    Geometric Design Optimisations Towards Improve...
14596    A Biocompatible Design of KappaCarrageenan/Fun...
Name: ManuscriptTitle, dtype: object
14690    Negativebias with illumination stress induced ...
14691    Drain Bias Effect on the Instability of Amorph...
Name: ManuscriptTitle, dtype: object
6566    Probing ultrafast charge separation in CZTS/Cd...
6570    Influence of thermal processing protocol upon ...
6616    AmineThiol/Selenol Chemistry for Efficient and...
Name: ManuscriptTitle, dtype: object
6575    Photophysical Processes Occurring in a Znphtha...
6647    Thermodynamic Studies of Bromide Incorporation...
Name: ManuscriptTitle, dtype: object
972     Proximal bacterial lysis and detection in nano...
3796    Population saturation in trivalent erbium sens...
Name: ManuscriptTitle, dtype: object
12920    Efficient Photocatalytic CO2 Reduction with MI...
12925    Photoelectrochemical Degradation of Organic Po...
Name: ManuscriptTitle, dtype: object
14586    Degradation of indigo carmine in alkaline dyem...
14594    Effect of pulse ontime and peak current densit...
Name: ManuscriptTitle, dtype: object
17188    The role of electrostatic interaction between ...
17189    Conducting Polymers The Role of Electrostatic ...
Name: ManuscriptTitle, dtype: object
7552     Dynamics of phononic dissipation at the atomic...
15639    Surface Passivation of BoronDiffused pType Sil...
Name: ManuscriptTitle, dtype: object
9446    Optical properties and modeling of 2D perovski...
9463    Discovering superior basal plane active twodim...
Name: ManuscriptTitle, dtype: object
15672    Closing the celltomodule efficiency gap a full...
15674    Elucidating PID degradation mechanisms and in ...
Name: ManuscriptTitle, dtype: object
11562    InGaN nanohole arrays coated by lead halide pe...
11568    Defect Variants Based on the 2D Hybrid Organic...
Name: ManuscriptTitle, dtype: object
11574    Graphitic Carbon Nitride−γGallium Oxide (GCNγG...
11577    EthylenediamineAssisted High Yield Exfoliation...
Name: ManuscriptTitle, dtype: object
11458    Measurement of absolute radical densities in a...
11510    Semiconductor–metal transitions in lead chalco...
Name: ManuscriptTitle, dtype: object
11459    Structure and chemical composition of fluorina...
11597    Niobium‐Doped Titanium Dioxide with High Dopan...
11604    Tungsten‐Nitride‐Coated Carbon Nanospheres as ...
Name: ManuscriptTitle, dtype: object
15609    Metal based triazole compounds Their synthesis...
15611    Ferrocenylaniline based amide analogs of metho...
Name: ManuscriptTitle, dtype: object
16342    Lightinduced effects on crystal size and photo...
16344    Mesoporous GOTiO2 nanocomposites for flexible ...
Name: ManuscriptTitle, dtype: object
4952    SWCNT photocathodes sensitised with InP/ZnS co...
4953    A synergistic Cs 2 CO 3 ETL treatment to incor...
Name: ManuscriptTitle, dtype: object
4955     Challenges progress and prospects in solid sta...
4979     Semitransparent nearinfrared Sn–Pb hybrid pero...
16946    Advances in ceramic thin films fabricated by p...
Name: ManuscriptTitle, dtype: object
4996     Highpressure synthesis spinglass behaviour and...
16992    Solvothermal synthesis of Fe doped MnSnO3 An a...
Name: ManuscriptTitle, dtype: object
11347    Ultrabroadband Photodetector Based on Ferromag...
11349    All‐Solid‐State Flexible Asymmetric Supercapac...
Name: ManuscriptTitle, dtype: object
11352    Energy consumption estimation of organic nonvo...
11355    Phenylquinoline Derivatives as Efficient Inter...
Name: ManuscriptTitle, dtype: object
10943    Ultrathin structures of manganese fluorides co...
10944    Rhodiumbased halfHeusler alloys as thermoelect...
10946    Recent developments in the photophysics of sin...
Name: ManuscriptTitle, dtype: object
7538    Traplimited carrier recombination in singlewal...
7539    Optical properties of confined polaronic excit...
Name: ManuscriptTitle, dtype: object
11691    Towards singlemolecule detection A novel hybri...
11770    Enhancement of second harmonic generation in c...
Name: ManuscriptTitle, dtype: object
16346    Perovskite methylammonium lead bromide incorpo...
16353    Study of DOS and energy band structures in ber...
Name: ManuscriptTitle, dtype: object
14927    Insight Into Metastable Defects in Flexible  M...
14929    Paving the Way to BuildingIntegrated Transluce...
Name: ManuscriptTitle, dtype: object
403    Facile fabrication of largegrain CH3NH3PbI3−xB...
693    Theoretical procedure for optimizing dyesensit...
Name: ManuscriptTitle, dtype: object
8645    Lowdimensional phase suppression and defect pa...
8712    Transfer printing gold nanoparticle arrays by ...
Name: ManuscriptTitle, dtype: object
9185    Limitations and solutions for achieving highpe...
9200    Organic nanocrystals induced surface passivati...
Name: ManuscriptTitle, dtype: object
5298    The potential of singlet fission photon multip...
5300    Realistic Efficiency Limits for SingletFission...
Name: ManuscriptTitle, dtype: object

4378    Advances in twodimensional organic–inorganic h...
4393    Interface passivation using ultrathin polymer–...
Name: ManuscriptTitle, dtype: object
885     Highly Absorbing LeadFree Semiconductor Cu2AgB...
5631    Enhanced Optoelectronic Performance of a Passi...
Name: ManuscriptTitle, dtype: object
5766    Explaining the fill‐factor and photocurrent lo...
5770    Metal Halide Perovskites for Solar‐to‐Chemical...
Name: ManuscriptTitle, dtype: object
275    Synergistic strain engineering of perovskite s...
296    Hybrid Perovskite Films Approaching the Radiat...
Name: ManuscriptTitle, dtype: object
5296    Modeling the performance limitations and prosp...
5299    Lattice compression increases the activation b...
5323    Nonradiative energy transfer between thickness...
Name: ManuscriptTitle, dtype: object
5271    Rationalizing and controlling the surface stru...
5278    LowTemperature Crystallization Enables 21.9% E...
Name: ManuscriptTitle, dtype: object
13445    Improved Quality Absorber Layer of I–III–VI2 C...
13446    Zincophilic Laser‐Scribed Graphene Interlayer ...
Name: ManuscriptTitle, dtype: object
16494    Eutectic solvent mediated synthesis of carbona...
16497    UV–vis spectroscopic method for detection and ...
Name: ManuscriptTitle, dtype: object
4745    Focus Issue Organic lightemitting diodes–statu...
4747    Optothermally controlled beam steering in nonl...
Name: ManuscriptTitle, dtype: object
6778    Hybrid organicinorganic polariton laser (vol 7...
6780    Alloptical fiber Hanbury Brown &Twiss interfer...
Name: ManuscriptTitle, dtype: object
1225    PinholeFree and SurfaceNanostructured NiOx Fil...
8769    Allinorganic lead halide perovskite nanohexago...
Name: ManuscriptTitle, dtype: object
4741     Dead zones in colloidal quantum dot photovolta...
7723     Effect of pristine graphene on methylammonium ...
13471    Resonant aluminum nanodisk array for enhanced ...
Name: ManuscriptTitle, dtype: object
15885    Charge driven metalinsulator transitions in La...
15886    Polar P63cm phase as a marginally stable groun...
Name: ManuscriptTitle, dtype: object
15768    A new catalyst Ti doped CdO thin film for none...
15769    Interaction of Langmuir–Blodgett and spincoate...
15771    Labelfree glucose detection over a wide dynami...
Name: ManuscriptTitle, dtype: object
505     Probing femtosecond lattice displacement upon ...
6447    Nanoparticle silver catalysts that show enhanc...
Name: ManuscriptTitle, dtype: object
14616    Highperformance coreshell structured SiOx@ Sis...
14621    Highly selective HBr etch process for fabricat...
Name: ManuscriptTitle, dtype: object
3088    Simultaneous passivation of bulk and interface...
3157    Oxygen Electrocatalysis at MnIII–Ox–C Hybrid H...
Name: ManuscriptTitle, dtype: object
3605    A “tips and tricks” practical guide to the syn...
8228    Understanding the stability of mixed Acation l...
Name: ManuscriptTitle, dtype: object
3641    Photogeneration and recombination in P3HT/PCBM...
3683    Short Photoluminescence Lifetimes in VacuumDep...
Name: ManuscriptTitle, dtype: object
6118    Effect of Different Sensitization Technique on...
6128    Co3O4 Based AllOxide PV A Numerical Simulation...
Name: ManuscriptTitle, dtype: object
6076    Charge generation and mobilitylimited performa...
6092    Silicon nanocrystals produced by nanosecond la...
Name: ManuscriptTitle, dtype: object
8349    Quasi‐2D Hybrid Perovskite Formation Using Ben...
8390    Spontaneous Formation of Nanocrystals in Amorp...
8391    Enhanced Light Emission Performance of Mixed C...
8392    Preferential Orientation of Crystals Induced b...
Name: ManuscriptTitle, dtype: object
4868    Highly flexible organometal halide perovskite ...
4873    Colloidal metal halide perovskite nanocrystals...
Name: ManuscriptTitle, dtype: object
2454    Evolution of magnetic bubble domains in mangan...
2609    Mechanical deformation of InP and GaAs by sphe...
Name: ManuscriptTitle, dtype: object
10858    Effect of fullerene acceptor on the performanc...
10879    A graphene–Mo 2 C heterostructure for a highly...
Name: ManuscriptTitle, dtype: object
5671    Special Issue on the 40th Anniversary of Unive...
5682    Inverted Polymer Solar Cells with Annealing‐Fr...
Name: ManuscriptTitle, dtype: object
12512    Luminescence rise time in selfactivated PbWO4 ...
13689    Structural variations in (001)oriented layered...
Name: ManuscriptTitle, dtype: object
8346    Ion motion determines multiphase performance d...
8348    Plasmonics Hybrid Graphene–Giant Nanocrystal Q...
Name: ManuscriptTitle, dtype: object
7867    Red to blue tunable upconversion in Tm3+doped ...
7949    Photoconductivity in Langmuir—Blodgett multila...
Name: ManuscriptTitle, dtype: object
17612    Balancing the thickness of sensitizing and ine...
17613    Scar prevention through topical delivery of ge...
Name: ManuscriptTitle, dtype: object
15074    Sizeand shapecontrolled synthesis and properti...
15090    Search for halfmetallicity in new ferrimagneti...
Name: ManuscriptTitle, dtype: object
16980    Designing of potential materials for solar‐hyd...
17014    Photovoltaic Performance Optimization of Natur...
Name: ManuscriptTitle, dtype: object
16081    Rotor and flux position estimation in deltacon...
16103    New Variants of (110)‐Oriented Layered Lead Br...
16116    Structures and structurerelated electronic pro...
16135    Perovskitebased sensing scheme for detecting v...
Name: ManuscriptTitle, dtype: object
16076    RealTime Measurement of LiIon Battery Cells Us...
16095    The role of C–H··· H–B interactions in establi...
16096    A Thiacalix Basket and its Anion‐Dependent 2‐D...
16097    Hierarchical hydroxyapatite microspheres compo...
16101    Magnetic Properties of the Ordered Double Pero...
16141    An insert for anelastic spectroscopy measureme...
Name: ManuscriptTitle, dtype: object
5322    Identifying and reducing interfacial losses to...
5326    Control Over Ligand Exchange Reactivity in Hol...
Name: ManuscriptTitle, dtype: object
11331    Dead Ends Limit Charge Carrier Extraction from...
11337    Size‐and temperature‐dependent suppression of ...
Name: ManuscriptTitle, dtype: object
6628    CsPbBr3 MAPbBr3 and FAPbBr3 Bromide Perovskite...
6629    InSitu Degradation Pathway Analyses on Hybrid ...
Name: ManuscriptTitle, dtype: object
9785    Modelling a monolithically integrated vertical...
9788    Effect of phosphorus diffusion to the recombin...
9800    Junction formation by Zn (O S) sputtering yiel...
Name: ManuscriptTitle, dtype: object
2495    Enhanced tunability of the multiphoton absorpt...
2496    Stimulated emission of CdS nanowires grown by ...
Name: ManuscriptTitle, dtype: object
1353    Highly Efficient Color‐Stable Deep‐Blue Multil...
1480    Hybrid perovskite thin‐film photovoltaics in s...
Name: ManuscriptTitle, dtype: object
4218    Oligothia dendrimers for the formation of gold...
4219    Beyond PCBM Understanding the Photovoltaic Per...
Name: ManuscriptTitle, dtype: object
4202    An Aqueous Mg2+‐Based Dual‐Ion Battery with Hi...
4217    Photothermal Catalysis Efficient Visible‐Light...
Name: ManuscriptTitle, dtype: object
16330    3D printing of shape memory polymer (SMP)/carb...
16350    Creation of uniformly dispersed nitrogenvacanc...
Name: ManuscriptTitle, dtype: object
10117    Conductivity Properties of SingleWalled Carbon...
10122    Electric Property Change of SingleWalled Carbo...
Name: ManuscriptTitle, dtype: object
15784    Positively charged membranes for dye/salt sepa...
15789    Automated portable highpressure setup for stud...
Name: ManuscriptTitle, dtype: object
7720     Correlating Nanoscale Morphology with Device P...
11181    Multifunctional Properties of a Zn (II) Coordi...
Name: ManuscriptTitle, dtype: object
2053              A graphenebased hot electron transistor
2057    Monolithically Integrated Perovskite Semicondu...
2060    Photosensitization of ZnO nanowires with CdSe ...
Name: ManuscriptTitle, dtype: object
15255    Determination of the local environment of sili...
15258    Hightemperature thermoelectric properties of S...
Name: ManuscriptTitle, dtype: object
10424    Hyperfine interaction of the CuCl4 (NH3) 22cen...
10431    Efficient calculation of excitonic effects in ...
Name: ManuscriptTitle, dtype: object
1491    Hybrid Modulation‐Doping of Solution‐Processed...
1495    Correction High‐Performance ZnO Transistors Pr...
Name: ManuscriptTitle, dtype: object
14258    VacancyDriven Noncubic Local Structure and Mag...
14259    Integrated source of spectrally filtered corre...
Name: ManuscriptTitle, dtype: object
14268    Ultrafast transient absorption spectroscopic (...
14281    A helical salicyladoximebased manganese triang...
Name: ManuscriptTitle, dtype: object
1100    Spatially Resolved Persistent Photoconductivit...
1288    Crosslinked remote‐doped hole‐extracting conta...
Name: ManuscriptTitle, dtype: object
17099    Sensitizing effect of nanocrysrtalline TiO2 fi...
17103    Toxicity response of highly colloidal bioactiv...
Name: ManuscriptTitle, dtype: object
776    Guanidiniumformamidinium lead iodide a layered...
796    Aqueous synthesis of zinc blende CdTe/CdS magi...
Name: ManuscriptTitle, dtype: object
3538     Sodium DopingEnhanced Emission Efficiency and ...
15295    From tetragonal to cubic perovskite phase stru...
Name: ManuscriptTitle, dtype: object
6386    Slow Electron Cooling Dynamics Mediated by Ele...
6388    Exciton separation in CdS supraparticles upon ...
Name: ManuscriptTitle, dtype: object
2919    Nonvolatile multistates memories for highdensi...
2928    Enhancing the efficiency and stability of PbS ...
Name: ManuscriptTitle, dtype: object
821     2D intrinsic ferromagnets from van der Waals a...
5735    Neodymium‐sensitized nanoconstructs for near‐i...
Name: ManuscriptTitle, dtype: object
10094    Synthesis and TFT properties of fluorenyl core...
10231    54‐1 Invited Paper Development of Electrolumin...
Name: ManuscriptTitle, dtype: object
5705    Control of CH3NH3PbI3 Perovskite Nanostructure...
5709    Competitive reaction pathway for site‐selectiv...
5711    Self‐Assembled Ruddlesden–Popper/Perovskite Hy...
Name: ManuscriptTitle, dtype: object
3997     Pseudohalide (SCN–)Doped MAPbI3 Perovskites A ...
15792    Pressureinduced transition in a heavy fermion ...
Name: ManuscriptTitle, dtype: object
14091    Thermoelectric properties of Czochralskigrown ...
14093    Lightharvesting fullerenes for organic solar c...
Name: ManuscriptTitle, dtype: object
6272     Barrierless Slow Dissociation of Photogenerate...
11431    Conjugated poly (azomethine) s via simple ones...
Name: ManuscriptTitle, dtype: object
4626    Gold doping of silver nanoclusters a 26‐Fold e...
4628    Effect of Zinc‐doping on the Reduction of the ...
Name: ManuscriptTitle, dtype: object
6822    A Variable Temperature Synchrotron Xray Diffra...
6845    Optical electrochemical and photocatalytic pro...
Name: ManuscriptTitle, dtype: object
3279    Critical Coupling of Visible Light Extends Hot...
3281    Polymercontrolled growth and wrapping of perov...
3283    Controlling the Thermoelectric Properties of N...
Name: ManuscriptTitle, dtype: object
14271    Evaluation of Al2O3 and ZrO2 addition to reduc...
14282    Transport and magnetic properties of La0. 8Ce0...
Name: ManuscriptTitle, dtype: object
4926    Enhanced mobility in PbS quantum dot films via...
4927    PCBMblended chlorobenzene hybrid antisolvent e...
Name: ManuscriptTitle, dtype: object
17499    Threedimensionally ordered macroporous materia...
17500    Non‐Fouling Biodegradable Poly (ϵ‐caprolactone...
17511    Efficient continuouswave nonlinear frequency c...
Name: ManuscriptTitle, dtype: object
5554    Modification of NiOx hole transport layers wit...
5556    Structural and electrical transport properties...
Name: ManuscriptTitle, dtype: object
5736    Self‐Promoting Energy Storage in Balsa Wood‐Co...
5742    Highly Passivated n‐Type Colloidal Quantum Dot...
Name: ManuscriptTitle, dtype: object
16405    Elucidating the Effect of Pressure on Structur...
16415    Enhanced Stability of Perovskite Solar Cells u...
Name: ManuscriptTitle, dtype: object
6680    Dinaphthotetrathienoacenes Synthesis Character...
6683    Gas‐assisted spray coating of perovskite solar...
Name: ManuscriptTitle, dtype: object
7086    Quantum dots in a metallopolymer host studies ...
7087    Full electronic structure across a polymer het...
Name: ManuscriptTitle, dtype: object
3751    Defect passivation for red perovskite lightemi...
3767    Modulating the Carrier Relaxation Dynamics in ...
Name: ManuscriptTitle, dtype: object
5186    Improving lowbandgap tin–lead perovskite solar...
5236    Transparent ohmic contacts for solutionprocess...
Name: ManuscriptTitle, dtype: object
3173    Ionic Liquids Modulating CsPbI3 Colloidal Quan...
3185    AllNanoTiO2 Compact Film for HighPerformance D...
Name: ManuscriptTitle, dtype: object
10825    Composition dependent optical structural and p...
10827    Interface structure precursor rheology and die...
Name: ManuscriptTitle, dtype: object
2061    Nonequilibriumplasmasynthesized ZnO nanocrysta...
2072    Formation of nanopatterned polymer blends in p...
Name: ManuscriptTitle, dtype: object
17419    Interfacial electron transfer on cytochromec s...
17421    Updates from the SPADnet project (fully digita...
Name: ManuscriptTitle, dtype: object
878    Spectroscopic investigation of the effect of m...
955    A chargeorbital balance picture of doping in c...
956    Measuring charge carrier diffusion in coupled ...
Name: ManuscriptTitle, dtype: object
16020    Preparation of (1− x%)(Na0. 5Bi0. 5) TiO3–x% S...
16021    Structural and photophysical characterization ...
16022    Novel synthetic approach to the preparation of...
Name: ManuscriptTitle, dtype: object
12560    Optically responsive delivery platforms From t...
12568    The effect of space time on Co/CeO2 catalyst d...
Name: ManuscriptTitle, dtype: object
8386    Rare‐earth metal ions doped graphene quantum d...
8445    In situ detection of soot nanoparticles by tim...
Name: ManuscriptTitle, dtype: object
17375    Systematic review elucidating the generations ...
17377    Innovatory role of nanomaterials as biotools f...
Name: ManuscriptTitle, dtype: object
11871    A bifunctional lewis base additive for microsc...
11873    High members of the 2D RuddlesdenPopper halide...
Name: ManuscriptTitle, dtype: object
9074    Nitrogen incorporation and optical studies of ...
9091    Surface electronic structure of nitrogendoped ...
Name: ManuscriptTitle, dtype: object
5259    Exciton SelfTrapping for White Emission in 100...
5260    Engineering Surface Orientations for Efficient...
Name: ManuscriptTitle, dtype: object
10102    Enhancement of photocurrent of dyesensitized s...
10105    Eucalyptus Concoction Mediated Synthesis of Go...
10110    PhotoFenton activity of magnesium substituted ...
Name: ManuscriptTitle, dtype: object
9590    Monitoring the effect of asymmetrical vertical...
9594    Sizedependent alternation of magnetoresistive ...
Name: ManuscriptTitle, dtype: object
1392    On the Question of the Need for a Built‐In Pot...
1396    Measurements of optical electric field intensi...
Name: ManuscriptTitle, dtype: object
12947    A synthetic approach to a fullerenerich dendro...
12953    Efficacious elimination of intramolecular char...
Name: ManuscriptTitle, dtype: object
17607    Electrochemical sensing of epinephrine on a ca...
17608    Desilication of low alumina to caustic liquor ...
Name: ManuscriptTitle, dtype: object
11887    Highly crystalline synthesis of tellurene shee...
11940    Stability of organic solar cells with PCDTBT d...
Name: ManuscriptTitle, dtype: object
11892    Excitonpolaron spectral structures in twodimen...
11912    Strong magnetochiral dichroism for visible lig...
Name: ManuscriptTitle, dtype: object
10910    Holetransport materials with greatlydiffering ...
10928    Precursor nonstoichiometry to enable improved ...
Name: ManuscriptTitle, dtype: object
13787    Slater halfoccupation technique revisited the ...
13788    Firstprinciples determination of bandtoband el...
Name: ManuscriptTitle, dtype: object
8554     An extensible and tunable fullopaque cascade s...
10402    Spectroscopy and control of nearsurface defect...
Name: ManuscriptTitle, dtype: object
6890    Simultaneous observation of free and defectbou...
6892    Strainenhanced dzyaloshinskii–moriya interacti...
6893           Currentdriven coherent skyrmion generation
Name: ManuscriptTitle, dtype: object
4849    Engineering Srdoping for enabling longterm sta...
4850    Deciphering the role of quantum dot size in th...
Name: ManuscriptTitle, dtype: object
5526    Optical response and structural properties of ...
5532    Investigation of the effect of sintering tempe...
Name: ManuscriptTitle, dtype: object
1949    Tailored interfaces of unencapsulated perovski...
1996    Colloidal CdSe1–xSx Nanoplatelets with Narrow ...
1998    Optimization of band structure and quantumsize...
2122    Prolonging charge separation in P3HT− SWNT com...
2128    Quantum confined electron–phonon interaction i...
Name: ManuscriptTitle, dtype: object
2003     Crosslinked C60 Polymer Breaches the Quantum Gap
2010    Programmable metal/semiconductor nanostructure...
Name: ManuscriptTitle, dtype: object
15046    Interfacial engineering of halide perovskites ...
15047    Colloidal metal oxide nanocrystals as charge t...
Name: ManuscriptTitle, dtype: object
16775    Structural Microstructural and Magnetic Studie...
16779    Magnetocaloric Properties of La0.85Ag0.15MnO3 ...
Name: ManuscriptTitle, dtype: object
15984            Aging memory and oxygen vacancies in PLZT
15985    Memory effects in dielectric and anelastic mea...
Name: ManuscriptTitle, dtype: object
11880    Thermal transport in ZnO nanocrystal networks ...
11924    Hybrid perovskite solar cells In situ investig...
Name: ManuscriptTitle, dtype: object
12004    Deep‐blue low‐threshold amplified spontaneous ...
12005    Efficient Solution‐Processed Inverted Organic ...
Name: ManuscriptTitle, dtype: object
11951    Band Alignments in InxGa1–xP/GaAs Heterostruct...
11968    Al‐Doped ZnO nanowires by electrochemical depo...
Name: ManuscriptTitle, dtype: object
12010    Formation of High‐Pressure Phase of Titanium D...
12053    InSitu NanoAuger Probe of ChlorideIons during ...
Name: ManuscriptTitle, dtype: object
7038    Direct coherent multiink printing of fabric su...
7040    Heterojunction oxide thinfilm transistors with...
Name: ManuscriptTitle, dtype: object
9307    Molecular dynamics study of the interactions o...
9329    Preparation and characterization of ammoniumfu...
Name: ManuscriptTitle, dtype: object
8770    Highly luminescent and ultrastable cesium lead...
8774    Novel silicon compatible pWS 2 2D/3D heterojun...
Name: ManuscriptTitle, dtype: object
3357    Efficient and Stable Blue and RedEmitting Pero...
3377    Electrocrystallization of epitaxial zinc oxide...
3483    Pulsed Laser Deposition of Cs2AgBiBr6 from Mec...
Name: ManuscriptTitle, dtype: object

2002    Highcurvature nanostructuring enhances probe d...
2007    Engineering directionality in quantum dot shel...
2119    Twodimensional covalent crystals by chemical c...
2126    Confirmation of KMomentum Dark Exciton Vibroni...
Name: ManuscriptTitle, dtype: object
16267    Manipulation of the exciton diffusion length o...
16275    Studies on the synthesis and characterization ...
Name: ManuscriptTitle, dtype: object
17298    Facile synthesis of magnetite nanocubes using ...
17305    1 1 and 1 2 Complexes of Mercury (II) Halides ...
Name: ManuscriptTitle, dtype: object
16818    Ab initio study of structural elastic and elec...
16820    Effect of hydrostatic pressure on the structur...
Name: ManuscriptTitle, dtype: object
7463    Theoretical study of straininduced ordering in...
7476    Monolayer honeycomb structures of groupIV elem...
Name: ManuscriptTitle, dtype: object
4133    Operating Modes of Sandwiched Light‐Emitting E...
4136    Reversible formation of gold halides in single...
Name: ManuscriptTitle, dtype: object
4551    Hot Carrier Generation and Extraction of Plasm...
4568    Fourwave mixing in perovskite photovoltaic mat...
4573    Rational design of efficient palladium catalys...
Name: ManuscriptTitle, dtype: object
1120     Random lasing with systematic threshold behavi...
11173    An unusual interweaving in a 3fold interpenetr...
Name: ManuscriptTitle, dtype: object
825     Universal Transients in Polymer and Ionic Tran...
5571    Sampletoanswer isolation and mRNA profiling of...
Name: ManuscriptTitle, dtype: object
8771     Enhancement of photodetection characteristics ...
12941    Efficient passivated phthalocyaninequantum dot...
12942    Lithiumrich sulfide/selenide cathodes for next...
Name: ManuscriptTitle, dtype: object
986     Electronic Properties of a 1D Intrinsic/pDoped...
1072    The subtle chemistry of colloidal quantumconfi...
Name: ManuscriptTitle, dtype: object
16237    Piezoelectricity from Elastic and Dielectric M...
16238    Development of geopolymers for catalyst suppor...
17321    Transport of salicylic acid through supported ...
17324    Bandgap Engineering in Novel Fluorite‐Type Rar...
17329    Computational Prediction of a Novel Superhard ...
17332    Vein detection with near‐infrared organic phot...
17333    Integration of largearea optical imagers for b...
17337    Alkali metal doped nickel oxide clusters A den...
17338    Phonon stability electronic structure results ...
17339    A DFT investigation on electronic structure ch...
17343    Ultrabroadband thermal radiator for daytime pa...
17348    Physical Vapor Deposited [CoCd(dtc)2]/SnO2 Dua...
17349    PVA/Gd2O3@ Zno Nanocomposite Films as New UvBl...
17351    Characterization of Cu2ZnSnSe4 Thin Films Sele...
17354    Halide perovskite materials as chemical playgr...
17355    Experimental verification of optically optimiz...
17366    Impact of single pMOSFET dielectric degradatio...
Name: ManuscriptTitle, dtype: object
16187    Electrical transport and specific heat propert...
16195    Structure and energetics of ZrC (100)|| cZrO2 ...
16207    Review of perovskitestructure related cathode ...
16234    Effect of cobalt doping on structural optical ...
16245    Current status and prospects on chemical struc...
16252    Interaction of alkali alkaline earth and trans...
Name: ManuscriptTitle, dtype: object
16210    Hopping and clustering of oxygen vacancies in ...
16231    Oxygen ordering and mobility in ReBa sub 2 Cu ...
16248    Detection and spectroscopy of the ν1+ ν3 band ...
Name: ManuscriptTitle, dtype: object
16224    Dopinginduced enhancement of the switch rate o...
16402    Tunable Etching of CVD Graphene for Transfer P...
Name: ManuscriptTitle, dtype: object
9956    Capacitive scanning dilatometry and frequencyd...
9958    Nanocrystal quantum dot devices How the lead s...
Name: ManuscriptTitle, dtype: object
7909     Electron and hole transfer from indium phosphi...
12314    Spectroscopic properties and JuddOfelt analysi...
Name: ManuscriptTitle, dtype: object
8527    Rear side sphere gratings for improved light t...
8560    Increased homogeneity and opencircuit voltage ...
Name: ManuscriptTitle, dtype: object
1446    High Quality Inkjet Printed‐Emissive Nanocryst...
1449    Solution‐processed tin‐based perovskite for ne...
Name: ManuscriptTitle, dtype: object
15822    Impedance spectroscopy study of electrochromis...
15823    Impedance spectroscopy study of anodic growth ...
Name: ManuscriptTitle, dtype: object
2563    Position of defects with respect to domain wal...
2564    Relaxor behavior and electromechanical propert...
Name: ManuscriptTitle, dtype: object
12539    Synthesis and luminescence properties of Eu3+ ...
12547    Solidliquid phase transition activated by opti...
Name: ManuscriptTitle, dtype: object
2015    QuantumSizeEffect Tuning Enables Narrowband IR...
2048    Phase selection enabled formation of abrupt ax...
Name: ManuscriptTitle, dtype: object
8356    Perovskite excitonics primary exciton creation...
8403    Light Emission from Low‐Dimensional Pb‐Free Pe...
Name: ManuscriptTitle, dtype: object
10862    Solutionprocessed resistive switching memory d...
10873    Transformation of PbI 2 PbBr 2 and PbCl 2 salt...
Name: ManuscriptTitle, dtype: object
17233    Regioisomers of singly bridged calix [6] crown...
17234    Structural chemistry of layered lead halide pe...
Name: ManuscriptTitle, dtype: object
4317    Acoustic detection of phase transitions at the...
4329    Simultaneous improvement of charge generation ...
Name: ManuscriptTitle, dtype: object
2513    On MottSchottky analysis interpretation of cap...
9818    [Cu23(PhSe)16(Ph3P)8(H)6]·BF4 AtomicLevel Insi...
Name: ManuscriptTitle, dtype: object
2466    Dependence of negative differential resistance...
2608    Long minority carrier lifetime in Aucatalyzed ...
Name: ManuscriptTitle, dtype: object
1669    Cobalt Single‐Atom‐Intercalated Molybdenum Dis...
1687    Rapid Synthesis of Bright ShapeControlled Larg...
Name: ManuscriptTitle, dtype: object
12893    Electrochemical topotactic oxidation of nonsto...
12894                    In situ reduction of (100) SrTiO3
Name: ManuscriptTitle, dtype: object
16835    Terahertz spin currents and inverse spin Hall ...
16837    Deposition uniformity and particle size distri...
Name: ManuscriptTitle, dtype: object
16832    Evaluation of the contributions to the effecti...
16838    Synthesis of a zinc–imidazole metal–organic fr...
Name: ManuscriptTitle, dtype: object
13405    Effect of processing by femtosecond pulsed las...
13407    Physicochemical tools toward a detailed unders...
Name: ManuscriptTitle, dtype: object
15108    Surface passivation of organometal halide pero...
15110    Photoconductivity of PbS/perovskite quantum do...
15113    Photonupconverters for blue organic lightemitt...
15114    Directional quantum dot emission by softstampi...
Name: ManuscriptTitle, dtype: object
15111    Synthesis of twodimensional phenylethylamine t...
15116    Ligandfree allinorganic metal halide nanocubes...
15117    Theoretical insights into C–H bond activation ...
Name: ManuscriptTitle, dtype: object
11452    Study of surface reactions during plasma enhan...
12660    Exsolution of Realloy catalysts with enhanced ...
Name: ManuscriptTitle, dtype: object
11585    DNAmediated threedimensional assembly of hollo...
11586    Multifunctional bismuth nanoparticles as thera...
11587    Defect Passivation of Mn2+Doped CsPbCl3 Perovs...
Name: ManuscriptTitle, dtype: object
11486    Optical depth profiling of strontium titanate ...
11512    Unusual B1–B2 transition in PbSe under high pr...
Name: ManuscriptTitle, dtype: object
8323    Nonlinear Optical Properties of Colloidal CH3N...
8324    Aggregation‐Induced Emission Features of Organ...
Name: ManuscriptTitle, dtype: object
8337    Double active layers constructed with halide p...
8341    Hybrid Perovskite Degradation from an Optical ...
Name: ManuscriptTitle, dtype: object
8321    Solution Coating of Superior Large‐Area Flexib...
8325    Perovskite Quantum Dots Embedded Composite Fil...
Name: ManuscriptTitle, dtype: object
8338    Aligning Transition Dipole Moment toward Light...
8339    Chirality Induced Crystal Structural Differenc...
8340        Gallium polymorphs phase‐dependent plasmonics
Name: ManuscriptTitle, dtype: object
8327    Highly Efficient Light Emitting Diodes Based o...
8411    Negative Thermal Quenching and Size‐Dependent ...
Name: ManuscriptTitle, dtype: object
8382    Halide perovskites a progress report on photon...
8399    Hybrid Plasmonic and Pyroelectric Harvesting o...
8417    Magnetic Manipulation of Spontaneous Emission ...
Name: ManuscriptTitle, dtype: object
8331    Polarization‐Sensitive Ultraviolet Detection f...
8372    Angle and polarization selective spontaneous e...
Name: ManuscriptTitle, dtype: object
8378    A‐Site Cation Engineering in 2D Ruddlesden–Pop...
8379    Optical Gain of Lead Halide Perovskites Measur...
Name: ManuscriptTitle, dtype: object
8353    Can trihalide Lead perovskites support continu...
8359    Organic Nanofibers Extending the Lasing Wavele...
Name: ManuscriptTitle, dtype: object
8371    Flexible Electronics Broadband Light Out‐Coupl...
8441    Twophotonenhanced threephoton absorption in tr...
Name: ManuscriptTitle, dtype: object
8404    Optoelectronic Synapses Based on Photo‐Induced...
8425    The Intrinsic Photoluminescence Spectrum of Pe...
Name: ManuscriptTitle, dtype: object
8369    Illumination‐Induced Halide Segregation in Gra...
8448    Transmission properties of one dimensional fra...
Name: ManuscriptTitle, dtype: object
14813                           Sliver/spl reg/solar cells
14864    Investigation of materials for hot carrier sol...
Name: ManuscriptTitle, dtype: object
7990    Identification of the physical origin behind d...
8086    The effect of structural dimensionality on car...
Name: ManuscriptTitle, dtype: object
13280    Polarization dependent excitation and high har...
13286    Strain Engineering A Pathway for Tunable Funct...
Name: ManuscriptTitle, dtype: object
13267    Ligandlength modification in CsPbBr3 perovskit...
13271                Nanostructured perovskite solar cells
Name: ManuscriptTitle, dtype: object
13337    Photoluminescence spectral position shift gove...
13348    Atom optics with Bose–Einstein condensates qua...
Name: ManuscriptTitle, dtype: object
13327    2D Perovskite Microoptics Enabled by Direct Fe...
13346    Thermopower and phase transition in YbPd2Si2 u...
Name: ManuscriptTitle, dtype: object
2757    Temperaturedependent tunneling electroresistan...
2768    Band alignment at  heterojunctions and electro...
Name: ManuscriptTitle, dtype: object
2655    CONDENSED MATTER STRUCTURAL MECHANICAL THERMAL...
2678    Microscopic investigation of the poly (9 9dioc...
Name: ManuscriptTitle, dtype: object
11091    Energy level alignment at interfaces in organi...
11092    The interface electronic properties of organic...
11094    Observation of filled states at the Fermilevel...
Name: ManuscriptTitle, dtype: object
887     Atomistic Insights into Activation and Degrada...
1026    Ultralowthreshold twophoton pumped amplified s...
Name: ManuscriptTitle, dtype: object
3294     PacketOriented Photonic Networks (Guest Editor...
12731    Citral hydrogenation on high surface area meso...
Name: ManuscriptTitle, dtype: object
4307    Low‐Bandgap Methylammonium‐Rubidium Cation Sn‐...
6855                       Axial plane optical microscopy
Name: ManuscriptTitle, dtype: object
9607    Subnanometer glass surface dynamics induced by...
9608    Mixed halide bulk perovskite triplet sensitize...
Name: ManuscriptTitle, dtype: object

3619     Crucial Contribution of Polarity for the Bulk ...
12646    Oxygen storage capacity of La1x Formula Not Sh...
Name: ManuscriptTitle, dtype: object
1025    Rearranging lowdimensional phase distribution ...
1048    Circularly Polarized Emission from Organic–Ino...
Name: ManuscriptTitle, dtype: object
12857    Doping studies of the magnetic cobaltocuprate ...
12867    Full Heusler alloys (Co2TaSi and Co2TaGe) as p...
Name: ManuscriptTitle, dtype: object
15354    Seed‐Mediated Synthesis of Colloidal 2D Halide...
15358    Color tunable organic lightemitting diodes usi...
Name: ManuscriptTitle, dtype: object
8133    Impact of local structure on halogen ion migra...
8134    Photodecomposition and thermal decomposition i...
Name: ManuscriptTitle, dtype: object
8101    Pt/C–LiCoO 2 composites with ultralow Pt loadi...
8103    Renewable acetic acid in combination with soli...
8137    Facile synthesis of Ge–MWCNT nanocomposite ele...
Name: ManuscriptTitle, dtype: object
8049    Efficient nonfullerene organic solar cells emp...
8146    Pushing efficiency limits for semitransparent ...
Name: ManuscriptTitle, dtype: object
7516    Ultrafast carrier dynamics in core and core/sh...
7526    Semiconductors II Surfaces interfaces microstr...
Name: ManuscriptTitle, dtype: object
3033    Silicon Nanocanyon Onestep bottomup fabricatio...
3133    Borondoped silicon diatom frustules as a photo...
Name: ManuscriptTitle, dtype: object
17086    AcetamidiniumMethylammoniumBased Layered Hybri...
17088    Ultrafast charge and triplet state formation i...
Name: ManuscriptTitle, dtype: object
11875    Gap states induce soft Fermi level pinning upo...
11914    Thermal stability of nanoscale ferroelectric d...
Name: ManuscriptTitle, dtype: object
11893     speciation and energytransfer dynamics in qua...
11908    Enhancement of magnetic properties in compress...
Name: ManuscriptTitle, dtype: object
15284    Effect of the chromophores structures on the p...
15949    Resistance of 2ZrO2· Y2O3 top coat in thermal/...
Name: ManuscriptTitle, dtype: object
806    Triazole bridges as versatile linkers in elect...
822    Tunable magnetism and extraordinary sunlight a...
Name: ManuscriptTitle, dtype: object
7083     Halide perovskite nanocrystal arrays Multiplex...
11178    Influence of angular dicarboxylate ligand on t...
Name: ManuscriptTitle, dtype: object
10008    The effect of doping in the electrochemical pe...
10010    Graph theory model and mechanism analysis of c...
Name: ManuscriptTitle, dtype: object
1336    High‐Rate and Selective CO2 Electrolysis to Et...
1357    Oxygen Vacancies Allow Tuning the Work Functio...
1477    High‐performance ZnO transistors processed via...
Name: ManuscriptTitle, dtype: object
1359    Switching the Electronic Properties of ZnO Sur...
1541    Tethered Small‐Molecule Acceptors Simultaneous...
Name: ManuscriptTitle, dtype: object
1385    Substituted Rigid Rod‐Like Polymers—Building B...
1394    The role of bulk and interface recombination i...
1580    Bragg Stacks Enhancing Upconversion for Photov...
Name: ManuscriptTitle, dtype: object
1387    Direct determination of the emission zone in a...
1408            Chains of superparamagnetic nanoparticles
Name: ManuscriptTitle, dtype: object
1411    Efficient and spectrally stable blue perovskit...
1422    Enhancement of the performance of perovskite s...
1429    Halide perovskites a new era of solution‐proce...
Name: ManuscriptTitle, dtype: object
8130    Inorganic caesium lead iodide perovskite solar...
8135    Thermal degradation of formamidinium based lea...
Name: ManuscriptTitle, dtype: object
17198    Pyrene Solubilization in Aqueous Micellar Solu...
17223    Carbon nanotubes and carbon fibers in a flash ...
Name: ManuscriptTitle, dtype: object
11304    Layered SnSe nanoflakes with anharmonic phonon...
11305    Band bending at magnetic Ni/Ge (001) interface...
Name: ManuscriptTitle, dtype: object
15238    Excitation wavelength dependent fluorescence b...
15239    Natural sensitizers for DSCs improved with nan...
Name: ManuscriptTitle, dtype: object
167                               Boosting plant biology
169    Orientationdependent ionization energies and i...
Name: ManuscriptTitle, dtype: object
9121     Anomalous power dependence of upconversion emi...
11400    Ultrafast Carrier Redistribution in Single  Qu...
Name: ManuscriptTitle, dtype: object
9136    Recombination processes in passivated boronimp...
9166    Experiment Specification Capture and Laborator...
Name: ManuscriptTitle, dtype: object
7278    Logarithmic frequency dependence of the piezoe...
7285    Cation vacancies in ferroelectric PbTiO3 and P...
Name: ManuscriptTitle, dtype: object
5103    Graphene oxide shells on plasmonic nanostructu...
5163    Controlling the phase segregation in mixed hal...
Name: ManuscriptTitle, dtype: object
5155    Energy Spotlight Insights into Lithium Metal B...
5158    Tuning the SurfacePassivating Ligand Anchoring...
Name: ManuscriptTitle, dtype: object
5146    Overcoming Degradation Pathways to Achieve Sta...
5170    Boosting longterm stability of pure formamidin...
Name: ManuscriptTitle, dtype: object
3310    Revealing the Stoichiometric Tolerance of Lead...
3477    Polymerfree films of inorganic halide perovski...
Name: ManuscriptTitle, dtype: object
1497    Photovoltaics Highly Efficient Hybrid Photovol...
1525    Subtle molecular tailoring induces significant...
Name: ManuscriptTitle, dtype: object
12665    Planar heterojunction boosts solardriven photo...
12675    Influence of Mn and Fe Addition on the NO x  S...
Name: ManuscriptTitle, dtype: object
361    Impact of interfacial molecular orientation on...
371    Inversion symmetry and bulk Rashba effect in m...
Name: ManuscriptTitle, dtype: object
16627    Nitrogen doped cuprous oxide as low cost holet...
16628    Effect of grain size on the fracture behavior ...
Name: ManuscriptTitle, dtype: object
16575    Characterization of 430L porous supports obtai...
16594    Structural functional properties and enhanced ...
Name: ManuscriptTitle, dtype: object
7743    Cathode of ZnNi Layered Double Hydroxide Nanos...
7746    MultiScalable Grain Growth via PhenylC60Butyri...
Name: ManuscriptTitle, dtype: object
16256    Nonlinear optical switching and optical limiti...
16257    Unveiling photophysical and photonic phenomena...
Name: ManuscriptTitle, dtype: object
4372    Impedance spectroscopy characterisation of hig...
7794    Feasibility analysis of nanostructured planar ...
Name: ManuscriptTitle, dtype: object
8297    Ecofriendly Perovskites with Giant Self‐Defocu...
8301    Giant Bulk Photostriction and Accurate Photome...
Name: ManuscriptTitle, dtype: object
16543    Metal injection moulding of HS12155 highspeed ...
16552    Biomimetic [MoO3@ ZnO] semiconducting nanocomp...
Name: ManuscriptTitle, dtype: object
10624    Perovskite type BaSnO3reduced graphene oxide n...
15895    Niobium doping and dielectric anomalies in bis...
Name: ManuscriptTitle, dtype: object
3996    Inorganic hole conducting layers for perovskit...
4019    Band engineering via gradient molecular dopant...
4021    Controlling Electron and Hole Charge Injection...
Name: ManuscriptTitle, dtype: object
16355    Magnetic and electronic properties of halfmeta...
16357    GGA based study on electronic structure and th...
Name: ManuscriptTitle, dtype: object
1455    Micro‐and nanostructured lead halide perovskit...
1551    Alkyl side‐chain engineering in wide‐bandgap c...
Name: ManuscriptTitle, dtype: object
13423    Synergistically enhanced electric field in inh...
13433    Combined Fluorescence Fluctuation and Spectrof...
Name: ManuscriptTitle, dtype: object
7829    Sustainable fabrication of ultralong Pb (OH) B...
7831    Electrochemical synthesis of TGAcapped CdTe an...
7954    Bright and efficient blue and green lightemitt...
Name: ManuscriptTitle, dtype: object
5113    Nanoemitting heterostructures violate optical ...
6958    Interplay of couplings between antiferrodistor...
Name: ManuscriptTitle, dtype: object
8422    Ultra‐broadband Polarisers Based on Metastable...
8431    The Multiple Roles of Metal Ion Dopants in Spe...
Name: ManuscriptTitle, dtype: object
8423    Photoluminescence of Bound‐Exciton Complexes a...
8426    Shaping the emission spectral profile of quant...
Name: ManuscriptTitle, dtype: object
8381    Tuning Halide Composition Allows Low Dark Curr...
8402    Experimental Evidence of Chloride‐Induced Trap...
Name: ManuscriptTitle, dtype: object
12176    Extension of the Application of Piers‐Rubinszt...
12186    Requirements for plasma synthesis of nanocryst...
Name: ManuscriptTitle, dtype: object
7406    RAPID COMMUNICATIONSSemiconductors II Surfaces...
7410    Optical properties of  –doped oxides Different...
Name: ManuscriptTitle, dtype: object
5936    Overcoming Electrode‐Induced Losses in Organic...
5942    Requirements for beneficial electrochemical re...
5956    Efficient Thermally Evaporated γ‐CsPbI3 Perovs...
Name: ManuscriptTitle, dtype: object
15715    Functionalisation separation and solvation gen...
15716    Protein adsorption on nanoporous TiO 2 films a...
Name: ManuscriptTitle, dtype: object
15706    Influence of surface charges on the emission p...
15711    Effect of postannealing on the plasma etching ...
Name: ManuscriptTitle, dtype: object
2748    Nonlinear optical properties of benzylamine le...
2764    Polarization offsets of compositionally graded...
Name: ManuscriptTitle, dtype: object
6227    Fluorescence switching of quantum dot in quant...
6228    Ultrafast Relaxation Dynamics of Luminescent C...
6229    Design of a CdS/CdSe Heterostructure for Effic...
Name: ManuscriptTitle, dtype: object
330     The quantumconfined Stark effect in layered hy...
1126    Quasiepitaxial metalhalide perovskite ligand s...
Name: ManuscriptTitle, dtype: object
488      Abnormal band bowing effects in phase instabil...
12652    Selfassembled leadfree double perovskiteMXene ...
Name: ManuscriptTitle, dtype: object
9779    Surface passivation by rehydrogenation of sili...
9780    Reactive ion etching of dielectrics and silico...
Name: ManuscriptTitle, dtype: object
12105    Recent Progress in Polymorphs of Carbon Nitrid...
12128    Investigations of the viscoelastic properties ...
12135    COMMUNICATIONS TO THE EDITORInterplay of Therm...
Name: ManuscriptTitle, dtype: object
12061    SolGel Synthesis and Characterization of Yttri...
12109    Michael Polyaddition Approach Towards Sulfur E...
Name: ManuscriptTitle, dtype: object
12148    Novel electroluminescent polymers with fluoro ...
12149    Easily Attainable PhenothiazineBased Polymers ...
Name: ManuscriptTitle, dtype: object
12074    Nonlinear optical feedback for nanoand micropa...
12076    Halide Perovskites for Photonics and Optoelect...
Name: ManuscriptTitle, dtype: object
12114    Ordering graphoepitaxial orientation and confo...
12137    A phase diagram of the P3HT PCBM organic photo...
Name: ManuscriptTitle, dtype: object
12108    Polyethylene‐Derived Activated Carbon Material...
12134    Orientation and Dynamics of Chainlike Dipole A...
Name: ManuscriptTitle, dtype: object
12121    Preparation of oriented multilayers of poly (s...
12182    Fabrication and properties of B–N codoped ptyp...
Name: ManuscriptTitle, dtype: object
5369      A taxonomy for threeterminal tandem solar cells
5371    Understanding the PerformanceLimiting Factors ...
Name: ManuscriptTitle, dtype: object
9668    Implication of polymeric template agent on the...
9669    Hybrid nanocrystal/polymer solar cells based o...
Name: ManuscriptTitle, dtype: object
10201    Perforated Ndoped monoclinic ZnWO 4 nanorods f...
10254    An Investigation of the Photoinduced Changes o...
10289    Photoswitched Protein Adsorption on Electrosta...
Name: ManuscriptTitle, dtype: object
14233    RotaryJet spin assisted fabrication of MnO2 mi...
14245    Circularly Polarized Emission from Ensembles o...
Name: ManuscriptTitle, dtype: object
7099    Aryl amine substituted low energy gap carbazol...
7100    Localized surface plasmon resonance sensor bas...
Name: ManuscriptTitle, dtype: object
5303    14th International Conference on Hybrid and Or...
5304    Postsynthesis Transformation of Insulating Cs4...
5305    Efficient widebandgap mixedcation and mixedhal...
Name: ManuscriptTitle, dtype: object
2329    Electrodemolecular semiconductor contacts Work...
2351    Charging and excitonmediated decharging of met...
Name: ManuscriptTitle, dtype: object
5897    Characterization of the Valence and Conduction...
5920    Improved open‐circuit voltage in ZnO–PbSe quan...
Name: ManuscriptTitle, dtype: object
9691     Adjusting the Néel relaxation time of Fe3O4/Zn...
13525    Cationselective and anioncontrolled fluorogeni...
Name: ManuscriptTitle, dtype: object
2851    Suspended photonic crystal membranes in AlGaAs...
2883    Tuning the electronic structure of graphene by...
Name: ManuscriptTitle, dtype: object
14335    Magnetostatic spin wave resonance in squarepat...
14336    Tetragonal distortion induced perpendicular ma...
14337    Enhancement of dielectric and magnetic propert...
Name: ManuscriptTitle, dtype: object
234        Nanostructured materials for photon detection
283    Detection of Xray photons by solutionprocessed...
Name: ManuscriptTitle, dtype: object
12571    A K2NiF4type La2Li0. 5Al0. 5O4 catalyst for th...
12573    Design of nanocatalysts for green hydrogen pro...
12580    Nanoscale perovskite‐sensitized solar cell rev...
12597    A TiO2 Nanofiber–Carbon Nanotube‐Composite Pho...
12598    Plasmonic Gold Nanostars Incorporated into Hig...
Name: ManuscriptTitle, dtype: object
2866    Singlecell tumbling enables highresolution siz...
2955    Unravelling the photocatalytic behavior of all...
Name: ManuscriptTitle, dtype: object

15537    Pulsed electrodeposition of WO3–TiO2 composite...
15558    Implementation of a “design of experiments” me...
15564    Effects of Cu2− xS phase removal on surface po...
Name: ManuscriptTitle, dtype: object
5483    Direct evidence for percolation of immobilized...
5485    Twodimensional MOF modulated fiber nanogenerat...
Name: ManuscriptTitle, dtype: object
4714    Metal Coordination Sphere Deformation Induced ...
4715    Solution‐processed reduced graphene oxide film...
Name: ManuscriptTitle, dtype: object
9291    Leakage current effects on  plots of high meta...
9292    Nanowire fin field effect transistors via UVba...
9300    Papers from the 47th International Conference ...
9310    Growth and characterization of MnAs/ZnSe ferro...
9317    Solgel synthesized indium tin oxide as a trans...
9325    The effect of processing conditions on the mor...
9326    Effect of silane coupling agent on the morphol...
9328    Balancing hyperbole and impact in research com...
9332    Rh/CeO2 catalyst preparation and characterizat...
9337    Theoretical study of the strain influence on l...
Name: ManuscriptTitle, dtype: object
9311    Papers from the 19th North American Conference...
9330    Electrode characteristics of Li2Ti3O7ramsdelli...
Name: ManuscriptTitle, dtype: object
15033    Investigating the Role of Lewis AcidBase Inter...
15037    Formations of unexpected chlorobridged bis (ma...
Name: ManuscriptTitle, dtype: object
12071    Fabrication of Pressure Conductive Silicone Ru...
12073    Metaldielectric nanoantenna for radiation cont...
Name: ManuscriptTitle, dtype: object
6655    Fabrication pressure testing and nanopore form...
6707          Light manipulation in organic photovoltaics
Name: ManuscriptTitle, dtype: object
449     Lightactivated photocurrent degradation and se...
1157    Dilutioninduced formation of hybrid perovskite...
Name: ManuscriptTitle, dtype: object
16669    Insight into pressure tunable structural elect...
16684            Synthesis of 13Cdiamonds in CaCO3C system
Name: ManuscriptTitle, dtype: object
14732    Dependability assessment of transfer length me...
14733    A broadband active microwave monolithically in...
Name: ManuscriptTitle, dtype: object
2795    Elucidating possible crystallographic origins ...
2816                   Physics of ultrathin photovoltaics
Name: ManuscriptTitle, dtype: object
14743    Metalassisted chemical etching for very high a...
14749    Characterization of SOI MOSFETs by means of ch...
Name: ManuscriptTitle, dtype: object
3677         Advances in spraycast perovskite solar cells
3678    Lévy defects in matriximmobilized J aggregates...
Name: ManuscriptTitle, dtype: object
4297    Crystalline Mesoporous Complex Oxides Porosity...
4298    High‐Temperature Photoluminescence of CsPbX3 (...
Name: ManuscriptTitle, dtype: object
4982    Ultrasensitive turnon luminescence humidity se...
5001    Effect of density of surface defects on photol...
Name: ManuscriptTitle, dtype: object
5116    Formamidinium lead halide perovskite crystals ...
6965    Nonlinear Dynamics Fluid Dynamics Classical Op...
Name: ManuscriptTitle, dtype: object
2269    An electrochemical clamp assay for direct rapi...
2325    In situ resistance measurement of the type con...
Name: ManuscriptTitle, dtype: object
5497    Perspectives of chalcopyritebased CIGSe thinfi...
5500    Synthesis of NiO–CeO2 nanocomposite for electr...
Name: ManuscriptTitle, dtype: object
14330    Electrical transport properties and transport–...
14370    Comparison of highly conductive natural and sy...
Name: ManuscriptTitle, dtype: object
9583    Bonding in d9 complexes derived from EPR Appli...
9584    Crystalfield and charge transfer transitions d...
Name: ManuscriptTitle, dtype: object
7556    Surface physics lowdimensional systems and rel...
7566    Magnetotransport properties of doped RuSr 2 Gd...
Name: ManuscriptTitle, dtype: object
1307         Mixed lead halide passivation of quantum dots
16738    A novel Tb3+ ions doped barium strontium fluor...
Name: ManuscriptTitle, dtype: object
15223    The effect of Au on TiO2 catalyzed selective p...
15226    Impact of one step alloying on the carrier rel...
Name: ManuscriptTitle, dtype: object
2633    “Smart” silicon Switching between p‐ and n‐con...
2637    Colossal enhancement of the thermoelectric pow...
Name: ManuscriptTitle, dtype: object
4004    Untying the Cesium “Not” Cesium–Iodoplumbate C...
4009    Graphdiyne an efficient hole transporter for s...
Name: ManuscriptTitle, dtype: object
4002    Quantum dot photocatalysts for organic transfo...
4010    Efficient infrared electroluminescent devices ...
Name: ManuscriptTitle, dtype: object
5619    Sustained SolarPowered Electrocatalytic H2 Pro...
5620    Teacarbon dotsreduced graphene oxide an effici...
5621    Green SolventBased Perovskite Precursor Develo...
Name: ManuscriptTitle, dtype: object
12077    Erratum Halide Perovskites for Photonics and O...
12080    Temperature dependent twophoton photoluminesce...
Name: ManuscriptTitle, dtype: object
16708    Self nitrogen and oxygenbroadening coefficient...
16709    Highresolution infrared spectroscopy of the ν2...
Name: ManuscriptTitle, dtype: object
2219    Strain effect in palladium nanostructures as n...
2230    Nanoscale back contact perovskite solar cell d...
Name: ManuscriptTitle, dtype: object
2173    Unveiling the shape evolution and halideionseg...
2185                   Optical force stamping lithography
Name: ManuscriptTitle, dtype: object
9259    Organolead halide perovskite regulated green l...
9261    Improved energy harvesting ability of C3H7NH3P...
Name: ManuscriptTitle, dtype: object
9258    Structure engineering of hierarchical layered ...
9260    Piezophototronic effect in highly stable CsPbI...
Name: ManuscriptTitle, dtype: object
3193    Electrical conductivity of doped organic semic...
3194       Molecular Doping Directed by a Neutral Radical
Name: ManuscriptTitle, dtype: object
3863    Change in tetracene polymorphism facilitates t...
3867    Ultrafast Optical Mapping of Nonlinear Plasmon...
Name: ManuscriptTitle, dtype: object
5346    Women scientists at the forefront of energy re...
5347    Leadfree dion–jacobson tin halide perovskites ...
Name: ManuscriptTitle, dtype: object
2878     Surface State Density Determines the Energy Le...
13587    Sharp Lines Due to Cr3+ and Mn2+ Impurities in...
Name: ManuscriptTitle, dtype: object
4204    Simultaneous Power Conversion Efficiency and S...
4212    Novel Method of Preparation of Gold‐Nanopartic...
Name: ManuscriptTitle, dtype: object
13252    NiO Nanofibers as a Candidate for a Nanophotoc...
13253               Quantum dot sensitized photoelectrodes
Name: ManuscriptTitle, dtype: object
12162    Atomistic investigation of the solubility of 3...
12163    Synthesis of πbridged duallydopable conjugated...
Name: ManuscriptTitle, dtype: object
372    Pure crystal orientation and anisotropic charg...
379    Electrically tunable organic–inorganic hybrid ...
380    Microcavitylike excitonpolaritons can be the p...
Name: ManuscriptTitle, dtype: object
1136    MoS2 Quantum Dot/Graphene Hybrids for Advanced...
1198    Revealing factors influencing the operational ...
Name: ManuscriptTitle, dtype: object
9282    Electrical scanning probe microscopy Investiga...
9285    Twodimensional profiling of carriers in a buri...
9286    Twodimensional transverse crosssection nanopot...
Name: ManuscriptTitle, dtype: object
9305    Real time in situ monitoring of surfaces durin...
9308    Planar metal–insulator–metal diodes based on t...
Name: ManuscriptTitle, dtype: object
9545    On the polarization of the green emission of p...
9564    PseudoJahnTeller origin of geometry and pseudo...
9567    A simple monomerbased modelHamiltonian approac...
Name: ManuscriptTitle, dtype: object
6243    Quenching of confined C480 dye in the presence...
6246    Structural Analysis and Carrier Relaxation Dyn...
Name: ManuscriptTitle, dtype: object
1817    Halide Remixing under Device Operation Imparts...
1841    Neutron Detectors Cesium Lead Bromide (CsPbBr3...
Name: ManuscriptTitle, dtype: object
14496    4Terminal Inorganic Perovskite/Organic Tandem ...
14503    0.86nm CET Gate Stacks With Epitaxial GdO High...
Name: ManuscriptTitle, dtype: object
6067    Effect of solvent additive on generation recom...
6085    Synthesis and Optical Properties of a Dithiola...
Name: ManuscriptTitle, dtype: object
4644    High‐performance perovskite light‐emitting dio...
4657    Biosupramolecular Nanowires from Chlorophyll D...
4689    Metal–organic organopolymeric hybrid framework...
Name: ManuscriptTitle, dtype: object
3064    How Deep Hole Traps Affect the Charge Dynamics...
3100    Enhanced Device Performance with Passivation o...
3118    Direct hotinjection synthesis of lead halide p...
Name: ManuscriptTitle, dtype: object
11446    Photovoltaic manufacturing Present status futu...
11470    Substrate and temperature dependence of the fo...
11569    Potassium and Rubidium Copper Halide A2CuX3 (A...
Name: ManuscriptTitle, dtype: object
13046    Molecularengineered [Ir (Fppy) 2 (Mepic)] towa...
13048    Copper (i) ionic complexes based on imidazo [4...
Name: ManuscriptTitle, dtype: object
13025    Copperzinc oxide catalysts. Part IV. Thermal t...
13026    Chimie douce synthesis and thermochemical char...
Name: ManuscriptTitle, dtype: object
13032    Scalable heterogeneous synthesis of metallic n...
13064    Structural interpretation of SnO 2 nanocrystal...
Name: ManuscriptTitle, dtype: object
3288    Conductivity Optimization of Tysonitetype La1–...
3296    Synthesis of Colloidal CuGaSe2 CuInSe2 and Cu(...
Name: ManuscriptTitle, dtype: object
6605    Oligofluorene molecular wires Synthesis and si...
6606    The photochemistry of crystalline nitromethane...
Name: ManuscriptTitle, dtype: object
10983    Atomicscale origin of piezoelectricity in wurt...
10991    Electronic optical and thermoelectric properti...
10999    Solvent Hbond accepting ability induced confor...
Name: ManuscriptTitle, dtype: object
13194    ABCmodel analysis of gainswitched pulse charac...
13210    Highly stable fluorinepassivated In–Ga–Zn–O th...
Name: ManuscriptTitle, dtype: object
6376    Manipulation of Hydrogen Binding Energy and De...
6379    Understanding acid reaction and diffusion in c...
Name: ManuscriptTitle, dtype: object
17525    Bridged phthalocyanine systems for sensitizati...
17528    Structural dielectric permittivity and optical...
17529    Structure–property relationship of biobased po...
17532    Polyurethane/soya protein isolate green compos...
Name: ManuscriptTitle, dtype: object
5353    High photovoltage of 1 V on a steadystate cert...
5381    Curtailing Perovskite Processing Limitations v...
Name: ManuscriptTitle, dtype: object
4257    Stable Light‐Emitting Electrochemical Cells Us...
4284    Constructing Polymorphic Nanodomains in BaTiO3...
4293    Working principles of perovskite photodetector...
Name: ManuscriptTitle, dtype: object
4227    Stable and Bright Pyridine Manganese Halides f...
4246    Inorganic electron transport materials in pero...
Name: ManuscriptTitle, dtype: object
4234    Magnetic Properties of Layered Hybrid OrganicI...
4260    Enhancing Resistive Switching Performance and ...
Name: ManuscriptTitle, dtype: object
10712    Single layer pbi 2 hydrogenationdriven reconst...
10733    Improved photocatalytic activity by utilizing ...
Name: ManuscriptTitle, dtype: object
3060    PerturbationInduced Seeding and Crystallizatio...
3226    Allpolymer solar cells approaching 12% efficie...
Name: ManuscriptTitle, dtype: object
3120    Controlled fabrication of polypyrrole surfaces...
3125    Degradation Mechanism and Relative Stability o...
Name: ManuscriptTitle, dtype: object
10726    Airstable PbS quantum dots synthesized with sl...
10728    Ab initio calculation of halide ligand passiva...
Name: ManuscriptTitle, dtype: object
9599      Upand downconversion in molecules and materials
9601    Stochastic scattering theory for excitationind...
Name: ManuscriptTitle, dtype: object
9582    Directing charge transfer in perylene based li...
9585    Optical excitations and coupling constants in ...
9596    Straineffect for controlled growth mode and we...
Name: ManuscriptTitle, dtype: object
8127    Enhanced light harvesting in flexible polymer ...
8170    An electron beam evaporated TiO 2 layer for hi...
Name: ManuscriptTitle, dtype: object
2274    Dopantinduced electron localization drives CO2...
2275    Optically switchable transistor via energyleve...
Name: ManuscriptTitle, dtype: object
6327    Highly photoconductive CdSe quantumdot films i...
6329    On Charge Carrier Recombination in Sb2S3 and I...
Name: ManuscriptTitle, dtype: object
5274    Assessing the drawbacks and benefits of ion mi...
5279    Simultaneously improved efficiency and stabili...
Name: ManuscriptTitle, dtype: object
12591    Nickel‐based anode with water storage capabili...
12601    Charge Modulation in Graphitic Carbon Nitride ...
Name: ManuscriptTitle, dtype: object
15193    Separation of transport charge storage and rea...
15194    Electrochemical impedance analysis of the redo...
Name: ManuscriptTitle, dtype: object
12588    Effects of All‐Organic Interlayer Surface Modi...
12606    Additive‐free transparent triarylamine‐based p...
Name: ManuscriptTitle, dtype: object
7537    Theoretical and experimental investigation of ...
7591    Variations of ferroelectric offcentering disto...
Name: ManuscriptTitle, dtype: object
4547    Dephasing and quantum beating of excitons in m...
4587    pDoped graphene/graphitic carbon nitride hybri...
Name: ManuscriptTitle, dtype: object
9766    Lightmodulated vertical heterojunction phototr...
9778    A novel silicon texturization method based on ...
Name: ManuscriptTitle, dtype: object
9753    Assessing health and environmental impacts of ...
9771    Inplane coherent control of plasmon resonances...
9776    On the equilibrium electrostatic potential and...
Name: ManuscriptTitle, dtype: object

In [60]:
print('Total Papers: ', papers_df.shape[0])
print('Total suspicious paper titles: ', j)

Total Papers:  16679
Total suspicious paper titles:  2891

In [64]:
num = papers_df.isna().sum().sum()
print(f'There are {num} null values in the data set')
get_unique_auth(papers_df)

There are 0 null values in the data set
There are 16358 unique author names

In [65]:
papers_df = papers_df.reset_index(drop = True)

In [66]:
papers_df.to_pickle('2023-03-23_NB4_papers_df_part3.pkl')

----